"""One-time enrichment script for the Explore Polish Batch — backfills
19 new Career fields (day-in-the-life through adjacent careers) onto
all 27 existing careers. Uses targeted `.update()` per career id, never
`.upsert()`, so the existing `reality`/`future_lens`/`branches`/etc.
content is never touched or clobbered — this script only ever adds to
what's already there.

Run via: python -m aureon.scripts.enrich_careers

Idempotent: safe to re-run (each update just re-writes the same real
content). Every career gets real, specific, non-generic content across
every field — no placeholders, no filler.
"""

import asyncio

from aureon.domain.models.career import Career
from aureon.services.supabase.client import get_supabase_client

# Only the 19 new fields per career — id is the update key, not part of
# the payload written to the row.
ENRICHMENTS: dict[str, dict] = {
    "physician_general": {
        "day_in_the_life": "A typical day starts with reviewing overnight patient messages and lab results before back-to-back appointments begin. Each visit blends listening, physical examination, and fast clinical decision-making, with documentation happening between patients rather than after.",
        "weekly_routine": "Most weeks run 4-5 patient-facing clinic days, with one afternoon often set aside for paperwork, lab review, or continuing education. On-call rotations add irregular hours a few times a month for physicians with hospital privileges.",
        "daily_tools": ["Electronic Health Records (e.g. Epic, Cerner)", "Stethoscope and diagnostic equipment", "UpToDate clinical decision-support software", "E-prescribing systems"],
        "career_progression": ["Resident Physician (3+ years training)", "General Practitioner", "Senior Physician / Clinic Lead", "Medical Director"],
        "related_industries": ["healthcare", "public health", "medical insurance"],
        "research_areas": ["Primary care outcomes research", "Chronic disease management", "Preventive medicine"],
        "companies": ["Kaiser Permanente", "Apollo Hospitals", "Mayo Clinic", "NHS (UK)"],
        "universities": ["Johns Hopkins University School of Medicine", "All India Institute of Medical Sciences (AIIMS)", "University of Oxford Medical Sciences"],
        "scholarships": ["NHS Bursary (UK)", "AIIMS merit scholarships (India)"],
        "competitions": ["Regional clinical case competitions for medical students"],
        "books": ["When Breath Becomes Air by Paul Kalanithi", "Being Mortal by Atul Gawande", "The House of God by Samuel Shem"],
        "communities": ["r/medicine (Reddit)", "Student Doctor Network"],
        "open_source_projects": ["OpenMRS open-source medical record platform"],
        "certifications": ["Board certification in Family Medicine", "Basic/Advanced Cardiac Life Support (BLS/ACLS)"],
        "projects": ["Volunteer at a free community health clinic", "Shadow multiple specialties to compare them"],
        "videos": ["Osmosis (YouTube)", "Doctor Mike"],
        "common_misconceptions": ["Physicians always know the diagnosis immediately", "It's a purely solo profession, not team-based", "Every physician earns the same regardless of specialty or setting"],
        "faqs": [
            {"question": "How many years of training does it take?", "answer": "Typically 4 years of medical school plus 3-7 years of residency depending on specialty — general practice residencies usually run 3 years."},
            {"question": "Do I need to pick a specialty right away?", "answer": "No — most students explore several rotations during clinical years before deciding, and general practice is itself a real specialty choice."},
        ],
        "adjacent_careers": ["Public Health Policy Analyst", "Health Informatics Specialist", "Hospital Administrator", "Clinical Research Coordinator"],
    },
    "civil_engineer": {
        "day_in_the_life": "Mornings often mean reviewing structural drawings or site survey data, followed by coordination calls with architects, contractors, or regulatory inspectors. Site visits punctuate the week, checking real construction progress against the design.",
        "weekly_routine": "A mix of office design work (CAD, structural calculations) and on-site supervision, with client or permitting-authority meetings woven in. Deadlines cluster around project milestones — foundation pour, structural sign-off, final inspection.",
        "daily_tools": ["AutoCAD / Civil 3D", "Structural analysis software (e.g. STAAD.Pro, ETABS)", "Surveying equipment (total station, GPS)", "Project management software (e.g. Primavera)"],
        "career_progression": ["Graduate Engineer", "Design/Site Engineer", "Project Engineer", "Chartered/Licensed Civil Engineer", "Principal Engineer"],
        "related_industries": ["engineering & construction", "urban development", "infrastructure"],
        "research_areas": ["Seismic-resilient design", "Sustainable/low-carbon construction materials", "Smart infrastructure monitoring"],
        "companies": ["Bechtel", "AECOM", "Larsen & Toubro", "Arup"],
        "universities": ["Georgia Institute of Technology", "Indian Institute of Technology network", "Imperial College London", "ETH Zurich"],
        "scholarships": ["Institution of Civil Engineers (ICE) QUEST scholarships (UK)", "AECOM student scholarships"],
        "competitions": ["ASCE Concrete Canoe Competition", "Steel Bridge Competition"],
        "books": ["Structures: Or Why Things Don't Fall Down by J.E. Gordon", "The Making of a Bridge by David Blockley"],
        "communities": ["r/civilengineering (Reddit)", "local Institution of Civil Engineers student chapters"],
        "open_source_projects": ["FreeCAD (open-source CAD)", "OpenSees (open-source structural simulation)"],
        "certifications": ["Professional Engineer (PE) license", "LEED Green Associate"],
        "projects": ["Design a small bridge or structure in CAD and stress-test it virtually", "Volunteer with Engineers Without Borders on a real community project"],
        "videos": ["Practical Engineering (YouTube)", "The B1M"],
        "common_misconceptions": ["Civil engineering is only about roads and bridges", "It's all desk work with no site involvement", "You need to love math more than problem-solving to succeed"],
        "faqs": [
            {"question": "Is fieldwork or office work more common?", "answer": "It genuinely varies by role and project phase — design-heavy roles skew toward the office, while site engineering involves regular, sometimes daily, site visits."},
            {"question": "What's the licensing path like?", "answer": "Most countries require a degree, several years of supervised experience, and a professional licensing exam (e.g. the PE exam in the US) before you can sign off on designs independently."},
        ],
        "adjacent_careers": ["Urban Planner", "Construction Project Manager", "Structural Consultant", "Sustainability Analyst"],
    },
    "accountant": {
        "day_in_the_life": "Days often start with reconciling transactions or reviewing financial statements against real client or company records. Much of the work is detail-focused — checking figures, flagging discrepancies, and preparing reports — punctuated by client or stakeholder meetings.",
        "weekly_routine": "Workload is uneven across the year: relatively steady reconciliation and reporting most weeks, with intense surges around month-end close, quarter-end, and especially tax season.",
        "daily_tools": ["QuickBooks / Tally / SAP", "Excel (advanced formulas, pivot tables)", "Tax preparation software", "ERP systems"],
        "career_progression": ["Staff Accountant", "Senior Accountant", "Accounting Manager", "Controller", "Chief Financial Officer"],
        "related_industries": ["finance", "corporate services", "public accounting"],
        "research_areas": ["Forensic accounting methods", "International financial reporting standards (IFRS) convergence"],
        "companies": ["Deloitte", "PwC", "EY", "KPMG"],
        "universities": ["Wharton School (UPenn)", "London School of Economics", "Indian Institute of Management network"],
        "scholarships": ["AICPA Scholarship for Minority Accounting Students", "ACCA Global Scholarship"],
        "competitions": ["National Association of Black Accountants case competitions"],
        "books": ["The Intelligent Investor by Benjamin Graham", "Accounting Made Simple by Mike Piper"],
        "communities": ["r/Accounting (Reddit)", "local CPA/CA student chapters"],
        "open_source_projects": ["GnuCash (open-source accounting software)"],
        "certifications": ["Certified Public Accountant (CPA)", "Chartered Accountant (CA)", "ACCA"],
        "projects": ["Build a personal or small-business budget tracker", "Analyze a public company's real financial statements"],
        "videos": ["Khan Academy Finance", "Accounting Stuff (YouTube)"],
        "common_misconceptions": ["Accounting is just data entry", "It's a career with no room for strategic influence", "It's only busy during tax season"],
        "faqs": [
            {"question": "Do I need a CPA to work in accounting?", "answer": "Not for every role — many staff-level positions don't require it — but a CPA/CA license significantly expands senior-level and audit-signing opportunities."},
            {"question": "Is accounting mostly solitary work?", "answer": "No — most roles involve real, regular collaboration with other departments, clients, or auditors, not just solo number-crunching."},
        ],
        "adjacent_careers": ["Financial Analyst", "Corporate Sustainability Analyst (ESG reporting)", "Management Consultant", "Auditor"],
    },
    "teacher_k12": {
        "day_in_the_life": "The day is structured around class periods, with lesson delivery, real-time behavior and engagement management, and quick formative checks for understanding. Planning, grading, and parent communication typically happen before or after direct teaching hours.",
        "weekly_routine": "Weekdays follow the school schedule; evenings and weekends often absorb lesson planning and grading. Weekly team or department meetings coordinate curriculum pacing with colleagues.",
        "daily_tools": ["Learning management systems (e.g. Google Classroom, Canvas)", "Interactive whiteboards", "Gradebook software", "Formative-assessment tools (e.g. Kahoot, Quizizz)"],
        "career_progression": ["Student Teacher", "Classroom Teacher", "Lead/Mentor Teacher", "Department Head", "Instructional Coach or Principal"],
        "related_industries": ["education", "edtech", "curriculum development"],
        "research_areas": ["Differentiated instruction", "Formative assessment design", "Classroom engagement strategies"],
        "companies": ["Khan Academy", "Pearson", "Coursera (curriculum partnerships)"],
        "universities": ["Teachers College, Columbia University", "Harvard Graduate School of Education", "UCL Institute of Education"],
        "scholarships": ["TEACH Grant (US)", "Robertson Scholarship for future teachers"],
        "competitions": ["Regional science-fair or academic-decathlon coaching (teacher-led)"],
        "books": ["Teach Like a Champion by Doug Lemov", "Mindset by Carol Dweck", "The First Days of School by Harry Wong"],
        "communities": ["r/Teachers (Reddit)", "local subject-area teacher associations"],
        "open_source_projects": ["CK-12 open educational resources"],
        "certifications": ["State/national teaching license", "TEFL/TESOL for language teaching"],
        "projects": ["Design and teach a full lesson unit", "Tutor a student one-on-one and track their progress"],
        "videos": ["Edutopia (YouTube)", "Crash Course"],
        "common_misconceptions": ["Teaching ends when the school bell rings", "It's a low-growth career with no advancement", "Anyone can teach well without training"],
        "faqs": [
            {"question": "How much of the job is actually teaching versus admin work?", "answer": "Direct instruction is usually a large share of contracted hours, but real planning, grading, and communication regularly extend beyond the school day."},
            {"question": "Can teachers specialize?", "answer": "Yes — by subject, grade band, special education, gifted education, or instructional coaching, among other real specialization paths."},
        ],
        "adjacent_careers": ["Instructional Designer", "School Counselor", "EdTech Product Manager", "Curriculum Developer"],
    },
    "ai_ops_specialist": {
        "day_in_the_life": "Mornings often start with checking model-performance dashboards for drift or degradation, then triaging any real production alerts. The rest of the day mixes writing monitoring/deployment pipelines with cross-team syncs with data scientists and engineers.",
        "weekly_routine": "A blend of proactive infrastructure work (improving pipelines, cost optimization) and reactive incident response when models misbehave in production. Sprint planning and retrospectives structure the broader cadence.",
        "daily_tools": ["MLflow / Weights & Biases", "Kubernetes and Docker", "Cloud ML platforms (AWS SageMaker, Vertex AI)", "Monitoring tools (Grafana, Prometheus)"],
        "career_progression": ["ML/DevOps Engineer", "AI Operations Specialist", "Senior MLOps Engineer", "MLOps Team Lead", "Head of AI Infrastructure"],
        "related_industries": ["technology", "cloud infrastructure", "data engineering"],
        "research_areas": ["Model monitoring and drift detection", "Efficient model serving at scale"],
        "companies": ["Google", "Amazon Web Services", "Microsoft Azure", "Databricks"],
        "universities": ["Carnegie Mellon University", "Indian Institute of Technology network", "ETH Zurich"],
        "scholarships": ["Google Generation Scholarship", "AWS re/Start program"],
        "competitions": ["Kaggle competitions (MLOps/deployment tracks)"],
        "books": ["Designing Machine Learning Systems by Chip Huyen", "The Site Reliability Workbook (Google)"],
        "communities": ["r/mlops (Reddit)", "MLOps Community Slack"],
        "open_source_projects": ["Kubeflow", "MLflow"],
        "certifications": ["AWS Certified Machine Learning – Specialty", "Google Cloud Professional ML Engineer"],
        "projects": ["Deploy a small ML model with a full monitoring pipeline", "Build a CI/CD pipeline for a machine-learning project"],
        "videos": ["Two Minute Papers", "MLOps Community (YouTube)"],
        "common_misconceptions": ["AI Ops is the same job as a data scientist", "Once a model is deployed, the work is done", "It's purely infrastructure with no ML understanding needed"],
        "faqs": [
            {"question": "Do I need to be a strong data scientist first?", "answer": "Not necessarily — many AI Ops specialists come from software engineering or DevOps backgrounds and build ML-specific knowledge on top, though understanding model behavior does help."},
            {"question": "What happens when a model 'breaks' in production?", "answer": "AI Ops specialists diagnose whether it's a data drift, infrastructure, or pipeline issue, then roll back, retrain, or patch — often under real time pressure."},
        ],
        "adjacent_careers": ["Site Reliability Engineer", "Data Engineer", "Cloud Solutions Architect", "Developer Relations Engineer"],
    },
    "genomics_data_scientist": {
        "day_in_the_life": "Much of the day involves writing analysis pipelines to process raw sequencing data into interpretable variants, then validating findings against known genomic databases. Regular discussions with wet-lab biologists ground the analysis in real experimental context.",
        "weekly_routine": "Heads-down analysis time alternates with lab meetings reviewing findings, and periodic pushes to prepare results for publication or a clinical report.",
        "daily_tools": ["Python/R for bioinformatics", "Bioconductor / Galaxy", "High-performance computing clusters", "Variant-calling pipelines (e.g. GATK)"],
        "career_progression": ["Bioinformatics Analyst", "Genomics Data Scientist", "Senior Computational Biologist", "Principal Scientist / Group Lead"],
        "related_industries": ["biotechnology", "healthcare", "pharmaceuticals"],
        "research_areas": ["Cancer genomics", "Population genetics", "Precision medicine"],
        "companies": ["Illumina", "23andMe", "Regeneron Genetics Center", "Biocon"],
        "universities": ["MIT", "University of Cambridge", "Indian Institute of Technology Bombay"],
        "scholarships": ["Wellcome Trust PhD studentships", "NIH T32 training grants"],
        "competitions": ["CAGI (Critical Assessment of Genome Interpretation) challenge"],
        "books": ["The Gene by Siddhartha Mukherjee", "Bioinformatics Data Skills by Vince Buffalo"],
        "communities": ["r/bioinformatics (Reddit)", "Bioinformatics Stack Exchange"],
        "open_source_projects": ["Bioconductor", "GATK (Genome Analysis Toolkit)"],
        "certifications": ["None universally required — a strong public GitHub/portfolio of pipelines often matters more"],
        "projects": ["Analyze a public genomic dataset (e.g. 1000 Genomes Project)", "Build a variant-calling pipeline from scratch"],
        "videos": ["Bioinformatics.org tutorials", "StatQuest with Josh Starmer"],
        "common_misconceptions": ["It's mostly wet-lab pipetting, not coding", "You need a medical degree to work in genomics", "Results are always definitive, never probabilistic"],
        "faqs": [
            {"question": "Do I need a biology background or a computer science one?", "answer": "Either can work — many genomics data scientists come from CS/statistics and learn biology, while others come from biology and learn to code; the field genuinely rewards both paths."},
            {"question": "Is this the same as a wet-lab geneticist?", "answer": "No — genomics data scientists mostly analyze data computationally, working closely with (but distinct from) the researchers running physical lab experiments."},
        ],
        "adjacent_careers": ["Bioinformatics Scientist", "Health Informatics Specialist", "Data Scientist", "Clinical Research Coordinator"],
    },
    "sustainability_analyst": {
        "day_in_the_life": "Work often starts with gathering real emissions, energy, or supply-chain data from internal systems, then analyzing it against sustainability targets or regulatory frameworks. Cross-functional meetings with operations or procurement teams help translate findings into real action.",
        "weekly_routine": "A mix of data analysis, report-writing (e.g. ESG disclosures), and stakeholder meetings, with intensity increasing around annual sustainability-report deadlines.",
        "daily_tools": ["Excel/Power BI for emissions tracking", "ESG reporting frameworks (GRI, SASB, CDP)", "Carbon accounting software (e.g. Watershed, Persefoni)"],
        "career_progression": ["Sustainability Analyst", "Senior Sustainability Analyst", "Sustainability Manager", "Chief Sustainability Officer"],
        "related_industries": ["corporate sustainability", "consulting", "manufacturing"],
        "research_areas": ["Scope 3 emissions accounting", "Circular economy business models"],
        "companies": ["Patagonia", "Unilever", "Ørsted", "Deloitte Sustainability"],
        "universities": ["Stanford Doerr School of Sustainability", "Yale School of the Environment", "TERI School of Advanced Studies (India)"],
        "scholarships": ["GreenBiz VERGE scholarships", "Yale Environmental Fellows Program"],
        "competitions": ["Net Impact Case Competition"],
        "books": ["Drawdown edited by Paul Hawken", "Cradle to Cradle by William McDonough"],
        "communities": ["r/sustainability (Reddit)", "local Net Impact chapters"],
        "open_source_projects": ["Global Forest Watch (open climate data project)"],
        "certifications": ["LEED Green Associate", "GRI Certified Sustainability Professional"],
        "projects": ["Conduct a real sustainability audit of a school or small business", "Analyze a company's public ESG report"],
        "videos": ["Our Changing Climate (YouTube)", "Kurzgesagt – In a Nutshell"],
        "common_misconceptions": ["Sustainability roles are only 'nice to have,' not core business functions", "It's only about environmental factors, not social/governance too", "Progress is always linear and easy to measure"],
        "faqs": [
            {"question": "Is this the same as an environmental scientist?", "answer": "Not quite — sustainability analysts focus on business/organizational data and reporting, while environmental scientists more often work on ecological or field research."},
            {"question": "Do I need a science degree?", "answer": "It helps but isn't required — many sustainability analysts come from business, economics, or policy backgrounds and build environmental knowledge alongside."},
        ],
        "adjacent_careers": ["ESG Consultant", "Corporate Social Responsibility Manager", "Environmental Policy Analyst", "Supply Chain Analyst"],
    },
    "space_systems_engineer": {
        "day_in_the_life": "Work often centers on designing or testing one subsystem (propulsion, power, communications) against strict mission requirements, with extensive documentation and review since space hardware can't easily be fixed once launched. Integration testing with other subsystems is a recurring, high-stakes activity.",
        "weekly_routine": "Design and simulation work alternates with formal design reviews, where engineers must defend every real decision against mission-critical failure scenarios.",
        "daily_tools": ["MATLAB/Simulink", "CAD software (SolidWorks, CATIA)", "Systems engineering tools (e.g. DOORS)", "Thermal/structural simulation software"],
        "career_progression": ["Junior Systems Engineer", "Space Systems Engineer", "Senior/Lead Systems Engineer", "Chief Engineer / Mission Systems Lead"],
        "related_industries": ["aerospace", "defense", "satellite communications"],
        "research_areas": ["Small satellite (CubeSat) design", "In-space propulsion systems", "Autonomous spacecraft operations"],
        "companies": ["SpaceX", "ISRO", "Northrop Grumman", "Rocket Lab"],
        "universities": ["MIT", "Purdue University", "Indian Institute of Space Science and Technology (IIST)"],
        "scholarships": ["AIAA Foundation scholarships", "ISRO student fellowships"],
        "competitions": ["NASA CubeSat Launch Initiative", "University Rover Challenge"],
        "books": ["Packing for Mars by Mary Roach", "Ignition! by John D. Clark"],
        "communities": ["r/space (Reddit)", "AIAA student chapters"],
        "open_source_projects": ["OreSat (open-source satellite project)"],
        "certifications": ["INCOSE Systems Engineering Professional (CSEP)"],
        "projects": ["Design and build a CubeSat or high-altitude balloon payload", "Simulate an orbital trajectory in Python"],
        "videos": ["Everyday Astronaut", "Scott Manley"],
        "common_misconceptions": ["This career is only for astronauts or rocket scientists in the literal sense", "Space engineering is mostly about launches, not years of subsystem design", "You need a PhD to enter the field"],
        "faqs": [
            {"question": "Do I need to specialize in one subsystem?", "answer": "Most engineers develop deep expertise in one area (propulsion, thermal, avionics) while maintaining a working understanding of how it interacts with the whole spacecraft."},
            {"question": "Is this only government-agency work?", "answer": "No — private companies like SpaceX, Rocket Lab, and a growing number of smaller startups now employ a large share of space systems engineers."},
        ],
        "adjacent_careers": ["Aerospace Test Engineer", "Robotics Engineer", "Satellite Operations Engineer", "Defense Systems Engineer"],
    },
    "bioinformatics_scientist": {
        "day_in_the_life": "The day typically mixes writing and debugging analysis scripts, interpreting biological datasets, and meeting with wet-lab collaborators to align on what the data actually means. A meaningful share of time also goes to documenting and validating pipelines for reproducibility.",
        "weekly_routine": "Deep analysis work is punctuated by lab meetings and periodic pushes to prepare figures or write-ups for publication or internal reporting.",
        "daily_tools": ["Python/R", "Unix/Linux command line", "Bioconductor", "Cloud computing (AWS/GCP for large datasets)"],
        "career_progression": ["Bioinformatics Analyst", "Bioinformatics Scientist", "Senior Computational Biologist", "Director of Bioinformatics"],
        "related_industries": ["biotechnology", "pharmaceuticals", "academic research"],
        "research_areas": ["Single-cell genomics", "Protein structure prediction", "Microbiome analysis"],
        "companies": ["Genentech", "Novozymes", "Ginkgo Bioworks", "Biocon"],
        "universities": ["Stanford University", "University of Cambridge", "Indian Institute of Technology Bombay"],
        "scholarships": ["NSF Graduate Research Fellowship", "Wellcome Trust studentships"],
        "competitions": ["CASP (Critical Assessment of Protein Structure Prediction)"],
        "books": ["Bioinformatics Data Skills by Vince Buffalo", "An Introduction to Bioinformatics Algorithms by Jones and Pevzner"],
        "communities": ["Bioinformatics Stack Exchange", "r/bioinformatics (Reddit)"],
        "open_source_projects": ["Biopython", "Bioconductor"],
        "certifications": ["None universal — a real, working GitHub portfolio of pipelines matters more"],
        "projects": ["Build a protein-sequence analysis tool", "Analyze a public single-cell RNA-seq dataset"],
        "videos": ["StatQuest with Josh Starmer", "Bioinformatics.org tutorials"],
        "common_misconceptions": ["It's the same job as a lab biologist", "All analysis is fully automated with no judgment calls", "You need a medical degree"],
        "faqs": [
            {"question": "How is this different from a genomics data scientist?", "answer": "There's real overlap — bioinformatics scientists often work across a broader range of biological data types (proteins, microbiomes, imaging) beyond just genomic sequencing."},
            {"question": "Is coding a big part of the job?", "answer": "Yes — writing, debugging, and maintaining analysis code is a real, daily core part of the work, not an occasional task."},
        ],
        "adjacent_careers": ["Genomics Data Scientist", "Computational Biologist", "Data Scientist", "Research Scientist"],
    },
    "ux_researcher": {
        "day_in_the_life": "Days often involve planning or conducting user interviews and usability tests, then synthesizing findings into real, actionable insights for design and product teams. Analysis time (coding interview transcripts, building affinity diagrams) is a substantial, less-visible part of the work.",
        "weekly_routine": "Research sprints alternate between fieldwork (interviews, testing sessions) and synthesis/reporting, timed to inform specific product decisions.",
        "daily_tools": ["Figma (for reviewing prototypes)", "UserTesting / Lookback", "Dovetail or Airtable for synthesis", "Survey tools (e.g. Qualtrics)"],
        "career_progression": ["Junior UX Researcher", "UX Researcher", "Senior UX Researcher", "Research Lead / Head of Research"],
        "related_industries": ["technology & design", "product management", "consulting"],
        "research_areas": ["Mixed-methods research design", "Accessibility research", "Longitudinal user-behavior studies"],
        "companies": ["Google", "Airbnb", "Figma", "Microsoft"],
        "universities": ["Stanford d.school", "Carnegie Mellon University (HCI)", "National Institute of Design (India)"],
        "scholarships": ["ACM SIGCHI student scholarships"],
        "competitions": ["local Design Sprint hackathons"],
        "books": ["Just Enough Research by Erika Hall", "Interviewing Users by Steve Portigal"],
        "communities": ["r/UXResearch (Reddit)", "User Interviews community"],
        "open_source_projects": ["Open-source design-system research repositories"],
        "certifications": ["Nielsen Norman Group UX Certification"],
        "projects": ["Conduct 5 real user interviews on a product you use and synthesize findings", "Run a moderated usability test on an existing app"],
        "videos": ["NN/g UX Research videos", "The Futur"],
        "common_misconceptions": ["UX research is the same as UX design", "It's just asking people if they like a product", "Findings are always clear-cut and unambiguous"],
        "faqs": [
            {"question": "Is UX research the same job as UX design?", "answer": "No — researchers investigate user needs and behavior to inform decisions, while designers create the actual interface; they're distinct, closely collaborating roles."},
            {"question": "Do I need a psychology degree?", "answer": "It helps but isn't required — many UX researchers come from psychology, anthropology, sociology, HCI, or even unrelated fields with strong analytical skills."},
        ],
        "adjacent_careers": ["Product Manager", "Data Analyst", "Service Designer", "Market Researcher"],
    },
    "computational_linguist": {
        "day_in_the_life": "Work often involves building or refining natural-language-processing models, annotating linguistic data, and evaluating how well a system captures real language patterns. Collaboration with linguists and ML engineers is a regular part of the job.",
        "weekly_routine": "Model development and data-annotation work alternates with evaluation cycles and paper or documentation writing.",
        "daily_tools": ["Python (NLTK, spaCy, Hugging Face Transformers)", "Annotation tools (e.g. Prodigy)", "Cloud GPU compute", "Linguistic corpora and treebanks"],
        "career_progression": ["NLP Research Assistant", "Computational Linguist", "Senior NLP Engineer", "NLP Research Lead"],
        "related_industries": ["technology & language", "artificial intelligence", "academic research"],
        "research_areas": ["Low-resource language modeling", "Machine translation", "Speech-to-text systems"],
        "companies": ["Google DeepMind", "Hugging Face", "AI4Bharat", "Meta AI"],
        "universities": ["Stanford University", "University of Edinburgh", "Indian Institute of Technology Madras"],
        "scholarships": ["Google PhD Fellowship in NLP", "Fulbright-Nehru scholarships"],
        "competitions": ["SemEval shared tasks", "WMT (machine translation) shared tasks"],
        "books": ["Speech and Language Processing by Jurafsky and Martin", "Natural Language Processing with Transformers by Tunstall et al."],
        "communities": ["r/LanguageTechnology (Reddit)", "Hugging Face community"],
        "open_source_projects": ["Hugging Face Transformers", "spaCy"],
        "certifications": ["None universal — a strong public model/dataset portfolio matters more"],
        "projects": ["Fine-tune a small language model on a niche dataset", "Build a text-classification tool for an underserved language"],
        "videos": ["Yannic Kilcher (YouTube)", "Two Minute Papers"],
        "common_misconceptions": ["It's the same as being a fluent polyglot", "Modern language models make this field obsolete", "It's purely engineering with no linguistics involved"],
        "faqs": [
            {"question": "Do I need to speak many languages?", "answer": "Not necessarily — the work is more about understanding language structure computationally than personal multilingual fluency, though it can help."},
            {"question": "Is this a linguistics job or a computer science job?", "answer": "Genuinely both — the strongest computational linguists combine real linguistic theory with real machine-learning engineering skill."},
        ],
        "adjacent_careers": ["NLP Engineer", "AI Research Scientist", "Translation Technology Specialist", "Data Scientist"],
    },
    "health_informatics_specialist": {
        "day_in_the_life": "Much of the day involves working with clinical data systems — improving how patient data flows between departments, troubleshooting EHR issues, or analyzing health outcomes data. Meetings with clinicians help ground technical decisions in real care-delivery needs.",
        "weekly_routine": "A mix of systems/data work and stakeholder meetings, with periodic project pushes around EHR upgrades or new reporting requirements.",
        "daily_tools": ["EHR systems (Epic, Cerner)", "SQL for health data queries", "HL7/FHIR interoperability standards", "Data visualization tools (Tableau, Power BI)"],
        "career_progression": ["Health Informatics Analyst", "Health Informatics Specialist", "Senior Informatics Manager", "Chief Health Information Officer"],
        "related_industries": ["healthcare & technology", "public health", "health insurance"],
        "research_areas": ["Clinical decision-support systems", "Health data interoperability", "Predictive analytics for patient outcomes"],
        "companies": ["Epic Systems", "Cerner (Oracle Health)", "Apollo Hospitals", "Practo"],
        "universities": ["University of Michigan", "Johns Hopkins University", "Indian Institute of Technology (health informatics programs)"],
        "scholarships": ["AMIA (American Medical Informatics Association) student scholarships"],
        "competitions": ["Health data hackathons (e.g. local hospital innovation challenges)"],
        "books": ["Biomedical Informatics by Edward Shortliffe", "The Digital Doctor by Robert Wachter"],
        "communities": ["AMIA student community", "r/healthIT (Reddit)"],
        "open_source_projects": ["OpenMRS", "HAPI FHIR"],
        "certifications": ["Certified Professional in Health Informatics (CPHI)", "Epic certifications"],
        "projects": ["Build a simple health-data dashboard from public datasets", "Map a real patient-data workflow and identify a real bottleneck"],
        "videos": ["AMIA webinars", "TED-Ed health-technology talks"],
        "common_misconceptions": ["It's just IT support for hospitals", "You need a full medical degree to work in this field", "The job is purely technical with no clinical understanding needed"],
        "faqs": [
            {"question": "Do I need a clinical background?", "answer": "It's not required — many health informatics specialists come from computer science or public health, though clinical experience helps ground the work."},
            {"question": "Is this the same as a data scientist in healthcare?", "answer": "There's overlap, but health informatics specialists focus more on systems, workflows, and interoperability, while data scientists focus more on modeling and analysis."},
        ],
        "adjacent_careers": ["Genomics Data Scientist", "Public Health Policy Analyst", "Health IT Project Manager", "Clinical Research Coordinator"],
    },
    "materials_research_scientist": {
        "day_in_the_life": "Lab time is spent synthesizing or testing new materials, running characterization equipment, and analyzing results against theoretical predictions. Writing up findings and troubleshooting failed experiments both take real, regular time.",
        "weekly_routine": "Experimental work alternates with data analysis and group meetings, with periodic pushes around conference deadlines or funding proposals.",
        "daily_tools": ["Electron microscopy equipment", "X-ray diffraction (XRD) systems", "Materials simulation software (e.g. VASP, LAMMPS)", "Lab notebook software"],
        "career_progression": ["Research Assistant", "Materials Research Scientist", "Senior Scientist", "Principal Investigator / Lab Director"],
        "related_industries": ["manufacturing & research", "electronics", "energy"],
        "research_areas": ["Battery materials", "Semiconductor materials", "Sustainable/biodegradable materials"],
        "companies": ["3M", "Corning", "Tata Steel", "Samsung Advanced Institute of Technology"],
        "universities": ["MIT", "University of Cambridge", "Indian Institute of Science (IISc)"],
        "scholarships": ["Materials Research Society (MRS) student awards", "NSF Graduate Research Fellowship"],
        "competitions": ["Materials Science Olympiad (regional)"],
        "books": ["Materials Science and Engineering by William Callister", "Stuff Matters by Mark Miodownik"],
        "communities": ["r/MaterialsScience (Reddit)", "Materials Research Society student chapters"],
        "open_source_projects": ["Materials Project (open computational materials database)"],
        "certifications": ["None universal — publications and lab experience matter more"],
        "projects": ["Grow and characterize a simple crystal or polymer sample", "Run a materials-simulation exercise using open-source tools"],
        "videos": ["Real Engineering (YouTube)", "The Materials Science Channel"],
        "common_misconceptions": ["Materials science is the same as chemistry", "Progress happens quickly and predictably", "It's purely theoretical with no hands-on lab work"],
        "faqs": [
            {"question": "Is this closer to physics, chemistry, or engineering?", "answer": "Genuinely an interdisciplinary mix of all three — most materials scientists draw real, working knowledge from each field."},
            {"question": "Do I need a PhD to do real research?", "answer": "For independent, lead-researcher roles usually yes, but many technician and research-assistant roles are open to bachelor's or master's graduates."},
        ],
        "adjacent_careers": ["Process Engineer", "Manufacturing Engineer", "Battery Technology Researcher", "Semiconductor Engineer"],
    },
    "neuroscience_postdoc": {
        "day_in_the_life": "Days revolve around running experiments (behavioral tasks, imaging, or electrophysiology), analyzing the resulting data, and reading recent literature to stay current. Mentoring graduate students and writing up findings for publication are recurring responsibilities.",
        "weekly_routine": "Experimental and analysis work fills most weekdays, with lab meetings for real progress updates and periodic intense pushes around grant or paper deadlines.",
        "daily_tools": ["MATLAB/Python for data analysis", "fMRI or EEG equipment", "Statistical software (R)", "Reference management (Zotero/EndNote)"],
        "career_progression": ["PhD Candidate", "Postdoctoral Researcher", "Research Scientist / Assistant Professor", "Principal Investigator"],
        "related_industries": ["academic research", "pharmaceuticals", "biotechnology"],
        "research_areas": ["Cognitive neuroscience", "Neurodegenerative disease mechanisms", "Computational neuroscience"],
        "companies": ["Allen Institute for Brain Science", "Novartis (neuroscience research)", "Biogen"],
        "universities": ["Harvard University", "University College London", "National Institute of Mental Health and Neurosciences (India)"],
        "scholarships": ["NIH NRSA postdoctoral fellowships", "Wellcome Trust fellowships"],
        "competitions": ["Society for Neuroscience poster competitions"],
        "books": ["The Brain That Changes Itself by Norman Doidge", "Phantoms in the Brain by V.S. Ramachandran"],
        "communities": ["r/neuroscience (Reddit)", "Society for Neuroscience student chapters"],
        "open_source_projects": ["NeuroData Without Borders (open neuroscience data standard)"],
        "certifications": ["None universal — publication record and grant funding matter more"],
        "projects": ["Analyze a public neuroscience dataset (e.g. Allen Brain Atlas)", "Design a small behavioral experiment"],
        "videos": ["Allen Institute YouTube channel", "Kurzgesagt neuroscience explainers"],
        "common_misconceptions": ["We already understand how the brain fully works", "Postdocs are highly paid and stable career positions", "It's all imaging with no hands-on behavioral work"],
        "faqs": [
            {"question": "How long does the postdoc stage typically last?", "answer": "Usually 2-5 years, sometimes longer, before moving to an independent research or industry position — it's a real, extended training stage, not a quick step."},
            {"question": "Is academia the only career path from here?", "answer": "No — many neuroscience postdocs move into biotech, pharma research, science policy, or data science roles."},
        ],
        "adjacent_careers": ["Clinical Research Coordinator", "Data Scientist", "Science Policy Analyst", "Medical Science Liaison"],
    },
    "clinical_research_coordinator": {
        "day_in_the_life": "Work centers on managing real trial participants — screening, consenting, scheduling visits, and collecting data accurately per protocol. Regulatory documentation and coordination with the principal investigator and sponsor take up significant time too.",
        "weekly_routine": "Participant visits are scheduled throughout the week; regulatory paperwork and data entry often get batched, with periodic audits or monitoring visits from trial sponsors.",
        "daily_tools": ["Electronic Data Capture (EDC) systems", "Clinical Trial Management Systems (CTMS)", "REDCap", "Regulatory binders/documentation software"],
        "career_progression": ["Clinical Research Assistant", "Clinical Research Coordinator", "Senior CRC / Clinical Research Associate", "Clinical Trial Manager"],
        "related_industries": ["healthcare research", "pharmaceuticals", "biotechnology"],
        "research_areas": ["Trial protocol design", "Patient recruitment and retention strategies"],
        "companies": ["IQVIA", "Parexel", "Apollo Hospitals (clinical trials division)"],
        "universities": ["Johns Hopkins University (clinical research programs)", "University of Cambridge"],
        "scholarships": ["Association of Clinical Research Professionals (ACRP) scholarships"],
        "competitions": [],
        "books": ["Clinical Trials: A Practical Guide by Duley, Elbourne, and Farrell"],
        "communities": ["ACRP student community", "r/clinicalresearch (Reddit)"],
        "open_source_projects": ["REDCap (widely-used, free research data platform)"],
        "certifications": ["Certified Clinical Research Coordinator (CCRC)", "Good Clinical Practice (GCP) certification"],
        "projects": ["Shadow a real clinical trial visit (with permission)", "Design a mock trial protocol for a hypothetical study"],
        "videos": ["ACRP webinars", "NIH clinical trials explainer videos"],
        "common_misconceptions": ["It's the same as being a nurse", "Clinical trials are mostly about giving out experimental drugs", "The role is purely administrative with no scientific understanding needed"],
        "faqs": [
            {"question": "Do I need a nursing or medical degree?", "answer": "Not always — many coordinators come from life-sciences or public-health backgrounds, though some roles (especially those doing clinical assessments) do require a nursing license."},
            {"question": "What's the biggest part of the job people don't expect?", "answer": "How much real time goes into regulatory documentation and precise protocol adherence — a single deviation can jeopardize a whole trial's data integrity."},
        ],
        "adjacent_careers": ["Regulatory Affairs Specialist", "Clinical Data Manager", "Public Health Policy Analyst", "Medical Science Liaison"],
    },
    "startup_founder": {
        "day_in_the_life": "No two days look alike — a founder might spend the morning on customer calls, the afternoon debugging product issues or reviewing financials, and the evening on investor updates. Constant context-switching between roles is the norm, especially early on.",
        "weekly_routine": "Weeks are organized loosely around a few real priorities (a launch, a fundraise, a key hire), with the actual daily work highly reactive to whatever's most urgent.",
        "daily_tools": ["Notion/Airtable for operations", "Stripe or similar for payments", "Slack/Linear for team coordination", "Basic financial modeling in spreadsheets"],
        "career_progression": ["Idea/Validation Stage", "Pre-Seed/Seed-Funded Founder", "Series A+ CEO", "Scaling-Stage Executive or Repeat Founder"],
        "related_industries": ["entrepreneurship", "venture capital", "technology"],
        "research_areas": ["Product-market fit methodology", "Go-to-market strategy"],
        "companies": ["Y Combinator-backed startups broadly", "Razorpay", "Notion"],
        "universities": ["Stanford Graduate School of Business", "Indian School of Business", "Babson College"],
        "scholarships": ["Thiel Fellowship", "Global Student Entrepreneur Awards"],
        "competitions": ["Y Combinator Startup School", "Hult Prize"],
        "books": ["Zero to One by Peter Thiel", "The Lean Startup by Eric Ries", "Shoe Dog by Phil Knight"],
        "communities": ["r/startups (Reddit)", "local startup incubator meetups"],
        "open_source_projects": ["Indie Hackers community projects"],
        "certifications": ["None required — real traction and a working product matter far more"],
        "projects": ["Launch a small real product or service and get paying customers", "Run a lean validation experiment for a business idea"],
        "videos": ["Y Combinator's Startup School (YouTube)", "How I Built This (NPR)"],
        "common_misconceptions": ["Founders are naturally fearless risk-takers", "You need a groundbreaking idea to start", "Funding equals success"],
        "faqs": [
            {"question": "Do I need to raise venture capital?", "answer": "No — many real, successful businesses are bootstrapped; VC funding is one path suited to specific, high-growth business models, not a requirement to be a founder."},
            {"question": "What's the most common reason startups fail?", "answer": "Building something nobody actually wants (no real product-market fit) is consistently cited as the single most common cause, more than running out of money outright."},
        ],
        "adjacent_careers": ["Product Manager", "Venture Capital Analyst", "Business Development Manager", "Growth Marketer"],
    },
    "product_led_growth_specialist": {
        "day_in_the_life": "Work focuses on analyzing real product-usage data to find friction points, then designing and testing changes (onboarding flows, feature nudges) to improve activation and retention. Cross-functional syncs with product and engineering are frequent.",
        "weekly_routine": "Experiment design, running A/B tests, and analyzing results form a recurring cycle, with periodic deep-dives into a specific funnel stage.",
        "daily_tools": ["Amplitude / Mixpanel for product analytics", "A/B testing platforms (e.g. Optimizely)", "SQL for data queries", "Figma (for reviewing UX changes)"],
        "career_progression": ["Growth Associate", "Product-Led Growth Specialist", "Senior Growth PM", "Head of Growth"],
        "related_industries": ["technology", "SaaS", "product management"],
        "research_areas": ["Onboarding funnel optimization", "Pricing and packaging experimentation"],
        "companies": ["Notion", "Figma", "Slack", "Zerodha"],
        "universities": ["No dedicated degree path — MBA/product-management programs at Stanford GSB or Indian School of Business often feed into this role"],
        "scholarships": [],
        "competitions": ["local Product Management case competitions"],
        "books": ["Hooked by Nir Eyal", "Product-Led Growth by Wes Bush"],
        "communities": ["r/ProductManagement (Reddit)", "Reforge community"],
        "open_source_projects": [],
        "certifications": ["Reforge Growth Series (paid, well-regarded)"],
        "projects": ["Redesign an app's onboarding flow and justify the changes with data", "Run a small A/B test on a real side project"],
        "videos": ["Lenny's Podcast (YouTube clips)", "Reforge webinars"],
        "common_misconceptions": ["Growth is just marketing with a different name", "It's all about growth hacks and gimmicks", "Success is only measured by user-count spikes"],
        "faqs": [
            {"question": "Is this a marketing role or a product role?", "answer": "It sits genuinely between both — most PLG specialists report into product but work daily with marketing, data, and engineering."},
            {"question": "Do I need to know how to code?", "answer": "Not required, but comfort with SQL and analytics tools is a real, practical advantage for this role."},
        ],
        "adjacent_careers": ["Product Manager", "Data Analyst", "Growth Marketer", "UX Researcher"],
    },
    "developer_relations_engineer": {
        "day_in_the_life": "A mix of writing documentation or sample code, answering real developer questions in community channels, and building demo projects that show off a product's API. Public speaking or content creation (blog posts, videos) is a recurring part of the role.",
        "weekly_routine": "Content creation and community engagement fill most weeks, with periodic travel or prep for conference talks and workshops.",
        "daily_tools": ["GitHub", "API documentation platforms (e.g. Readme.io)", "Discord/Slack community tools", "Video/screen-recording software"],
        "career_progression": ["Developer Advocate", "Developer Relations Engineer", "Senior DevRel Engineer", "Head of Developer Relations"],
        "related_industries": ["technology", "developer tools", "cloud platforms"],
        "research_areas": ["Developer experience (DX) research", "API design best practices"],
        "companies": ["GitHub", "Stripe", "Twilio", "MongoDB"],
        "universities": ["No dedicated degree — a strong public coding portfolio and communication skills matter most"],
        "scholarships": [],
        "competitions": ["local hackathons (often run by DevRel teams themselves)"],
        "books": ["The Business Value of Developer Relations by Mary Thengvall", "Developer Marketing Does Not Exist by Adam DuVander"],
        "communities": ["DevRel Collective", "r/programming (Reddit)"],
        "open_source_projects": ["Contributing to and maintaining the company's own SDKs/sample repos"],
        "certifications": ["None required — real public technical content and speaking experience matter most"],
        "projects": ["Write a technical tutorial for an API you don't work for", "Build and open-source a small demo app using a public API"],
        "videos": ["freeCodeCamp (YouTube)", "conference DevRel talks on YouTube"],
        "common_misconceptions": ["It's just marketing for developers", "You need to be a top-tier engineer to do this job", "The job is mostly giving conference talks"],
        "faqs": [
            {"question": "Is DevRel a technical or a marketing role?", "answer": "Genuinely both — strong DevRel engineers write real code and documentation while also communicating clearly with a public developer audience."},
            {"question": "How is this different from technical writing?", "answer": "Technical writers focus mainly on documentation; DevRel engineers also build demos, engage community, speak publicly, and often shape product feedback loops."},
        ],
        "adjacent_careers": ["Technical Writer", "Product-Led Growth Specialist", "Software Engineer", "Community Manager"],
    },
    "foreign_service_officer": {
        "day_in_the_life": "Work varies hugely by posting, but often includes drafting political or economic reports, meeting with local officials or civil-society contacts, and assisting citizens abroad with consular needs. Cultural and language fluency shapes daily effectiveness.",
        "weekly_routine": "A mix of scheduled meetings, report writing, and event representation (receptions, briefings), with occasional urgent consular-crisis response.",
        "daily_tools": ["Secure diplomatic cable/reporting systems", "Language translation tools", "Government briefing databases"],
        "career_progression": ["Entry-level Foreign Service Officer", "Second/First Secretary", "Counselor", "Ambassador / Head of Mission"],
        "related_industries": ["diplomacy & international relations", "government", "international development"],
        "research_areas": ["Regional political analysis", "International trade policy"],
        "companies": ["U.S. Department of State", "UK Foreign, Commonwealth & Development Office", "Indian Foreign Service"],
        "universities": ["Georgetown School of Foreign Service", "London School of Economics", "Jawaharlal Nehru University"],
        "scholarships": ["Fulbright Program", "Chevening Scholarships (UK)"],
        "competitions": ["Model United Nations (as preparation, not a formal pathway)"],
        "books": ["The Craft of Diplomacy by Chas Freeman", "Diplomacy by Henry Kissinger"],
        "communities": ["Foreign Service Journal community", "local Model UN alumni networks"],
        "open_source_projects": [],
        "certifications": ["Foreign Service Officer Test (FSOT, US) or equivalent national civil-service exam"],
        "projects": ["Join or lead a Model UN team", "Study a real regional conflict or trade dispute in depth"],
        "videos": ["Council on Foreign Relations (YouTube)", "C-SPAN diplomatic hearings"],
        "common_misconceptions": ["The job is glamorous cocktail parties, not real work", "Postings are always in major world capitals", "Diplomats decide foreign policy independently"],
        "faqs": [
            {"question": "Do I need to speak multiple languages?", "answer": "It's a major real advantage and often required for specific regional postings, though officers can also receive formal language training after being accepted."},
            {"question": "How much control do I have over where I'm posted?", "answer": "Limited — most foreign services rotate officers through a mix of preferred and hardship postings as part of real career development."},
        ],
        "adjacent_careers": ["International NGO Program Manager", "Public Health Policy Analyst", "Trade Policy Analyst", "Human Rights Researcher"],
    },
    "public_health_policy_analyst": {
        "day_in_the_life": "Work often involves reviewing health data or research literature, drafting policy briefs, and meeting with public-health officials or advocacy groups to understand real on-the-ground constraints. Translating complex evidence into actionable recommendations is a core daily skill.",
        "weekly_routine": "Research and writing fill most of the week, with periodic testimony, stakeholder meetings, or legislative-session crunches.",
        "daily_tools": ["Statistical software (R, Stata)", "Policy-brief templates and legislative tracking tools", "Public health databases (WHO, CDC)"],
        "career_progression": ["Policy Research Assistant", "Public Health Policy Analyst", "Senior Policy Advisor", "Director of Health Policy"],
        "related_industries": ["public health & policy", "government", "healthcare"],
        "research_areas": ["Health equity research", "Health-system financing", "Epidemiological policy modeling"],
        "companies": ["World Health Organization", "RAND Corporation", "Kaiser Family Foundation"],
        "universities": ["Harvard T.H. Chan School of Public Health", "London School of Hygiene & Tropical Medicine", "Public Health Foundation of India"],
        "scholarships": ["Fulbright Public Health Fellowships", "Rhodes Scholarship"],
        "competitions": [],
        "books": ["The Body Politic by Jonathan Engel", "Poor Economics by Banerjee and Duflo"],
        "communities": ["American Public Health Association student community"],
        "open_source_projects": ["Our World in Data (open public-health datasets)"],
        "certifications": ["Master of Public Health (MPH) — commonly expected, not strictly universal"],
        "projects": ["Analyze a real public-health dataset and propose a policy recommendation", "Write a policy brief on a genuine local health issue"],
        "videos": ["WHO (YouTube)", "TED Talks on public health policy"],
        "common_misconceptions": ["This role designs medical treatments, not policy", "Policy change happens quickly once evidence is clear", "It's the same job as a public health researcher"],
        "faqs": [
            {"question": "Do I need a medical degree?", "answer": "No — most public health policy analysts hold a master's in public health, public policy, or a related social-science field, not a clinical medical degree."},
            {"question": "How much of the job is research versus advocacy?", "answer": "Genuinely both — strong analysts move fluidly between rigorous evidence review and translating it into real, persuasive policy recommendations."},
        ],
        "adjacent_careers": ["Health Informatics Specialist", "Foreign Service Officer", "NGO Program Manager", "Epidemiologist"],
    },
    "urban_planner": {
        "day_in_the_life": "Work mixes reviewing development proposals against zoning codes, drafting land-use plans, and attending public meetings where real community input shapes decisions. GIS mapping and data analysis support most planning recommendations.",
        "weekly_routine": "Office-based analysis and drafting most days, with periodic public hearings or council meetings requiring real, in-person presentation and Q&A.",
        "daily_tools": ["GIS software (ArcGIS, QGIS)", "Zoning and land-use databases", "AutoCAD for site plans", "Public engagement platforms"],
        "career_progression": ["Planning Assistant", "Urban Planner", "Senior Planner", "Planning Director"],
        "related_industries": ["urban development", "government", "real estate"],
        "research_areas": ["Transit-oriented development", "Affordable housing policy", "Climate-resilient infrastructure planning"],
        "companies": ["Arup", "Gensler", "municipal planning departments broadly"],
        "universities": ["MIT (Department of Urban Studies and Planning)", "University College London", "School of Planning and Architecture, Delhi"],
        "scholarships": ["American Planning Association (APA) student scholarships"],
        "competitions": ["Urban Land Institute (ULI) Hines Student Competition"],
        "books": ["The Death and Life of Great American Cities by Jane Jacobs", "Cities for People by Jan Gehl"],
        "communities": ["r/urbanplanning (Reddit)", "local YIMBY meetup groups"],
        "open_source_projects": ["OpenStreetMap"],
        "certifications": ["American Institute of Certified Planners (AICP)"],
        "projects": ["Map and propose improvements for a real underused public space", "Analyze walkability or transit access in your own neighborhood"],
        "videos": ["The War on Cars (YouTube clips)", "City Beautiful (YouTube)"],
        "common_misconceptions": ["Urban planners just draw pretty maps", "Change happens quickly once a plan is proposed", "It's purely about roads and buildings, not people"],
        "faqs": [
            {"question": "Do I need an architecture background?", "answer": "No — most urban planners hold a Master's in Urban Planning, coming from geography, public policy, sociology, or design backgrounds, not necessarily architecture."},
            {"question": "How much of the job involves public speaking?", "answer": "A real, meaningful amount — presenting proposals at public hearings and responding to community concerns is a core, recurring part of the role."},
        ],
        "adjacent_careers": ["Civil Engineer", "Real Estate Development Analyst", "Transportation Planner", "Sustainability Analyst"],
    },
    "ngo_program_manager": {
        "day_in_the_life": "Work involves coordinating field teams, tracking program budgets and outcomes against real targets, and reporting to donors or headquarters. Site visits (when possible) ground office-based planning in real on-the-ground conditions.",
        "weekly_routine": "Planning and reporting fill most of the week, with periodic field travel and donor-relationship meetings.",
        "daily_tools": ["Monitoring & Evaluation (M&E) frameworks", "Grant management software", "Excel/Power BI for program data", "Field-data collection apps (e.g. KoBoToolbox)"],
        "career_progression": ["Program Officer", "NGO Program Manager", "Country Director", "Regional/Global Program Director"],
        "related_industries": ["international development", "humanitarian aid", "nonprofit management"],
        "research_areas": ["Program impact evaluation methodology", "Humanitarian logistics"],
        "companies": ["Oxfam", "Save the Children", "BRAC", "CARE International"],
        "universities": ["London School of Economics (development studies)", "Tata Institute of Social Sciences", "Fletcher School (Tufts)"],
        "scholarships": ["Chevening Scholarships", "Rotary Peace Fellowships"],
        "competitions": [],
        "books": ["Poor Economics by Banerjee and Duflo", "The Blue Sweater by Jacqueline Novogratz"],
        "communities": ["r/nonprofit (Reddit)", "local Net Impact chapters"],
        "open_source_projects": ["Ushahidi open-source crisis-mapping platform"],
        "certifications": ["PMD Pro (Project Management for Development Professionals)"],
        "projects": ["Volunteer with a local NGO and help track a real program's outcomes", "Design a small monitoring-and-evaluation framework for a hypothetical program"],
        "videos": ["Oxfam (YouTube)", "TED Talks on global development"],
        "common_misconceptions": ["NGO work doesn't pay a livable salary", "It's mostly unstructured volunteering, not a real profession", "Impact is always straightforward to measure"],
        "faqs": [
            {"question": "Do I need to live abroad to do this work?", "answer": "Not necessarily — many program manager roles are based at headquarters coordinating field teams remotely, though field-based roles do exist and are common early in a career."},
            {"question": "Is this the same as social work?", "answer": "There's overlap in mission but program management focuses more on budgeting, logistics, and outcome tracking than direct casework."},
        ],
        "adjacent_careers": ["Foreign Service Officer", "Public Health Policy Analyst", "Grant Writer", "Monitoring & Evaluation Specialist"],
    },
    "conservation_biologist": {
        "day_in_the_life": "Fieldwork days involve collecting real ecological data — species counts, habitat surveys, water-quality samples — often in remote conditions. Office days shift to data analysis, grant writing, or coordinating with local communities and policymakers on conservation plans.",
        "weekly_routine": "Field seasons bring intensive, irregular hours; off-season weeks are more typically 9-5 analysis and writing.",
        "daily_tools": ["GIS mapping software", "Camera traps and field survey equipment", "Statistical software (R)", "Species-tracking databases (e.g. iNaturalist)"],
        "career_progression": ["Field Research Assistant", "Conservation Biologist", "Senior Conservation Scientist", "Conservation Program Director"],
        "related_industries": ["environmental conservation", "ecotourism", "government (natural resources)"],
        "research_areas": ["Habitat restoration ecology", "Human-wildlife conflict mitigation", "Conservation genetics"],
        "companies": ["World Wildlife Fund", "Wildlife Conservation Society", "The Nature Conservancy"],
        "universities": ["University of Cape Town", "Duke University (Nicholas School of the Environment)", "Wildlife Institute of India"],
        "scholarships": ["National Geographic Explorer grants", "Fulbright Environmental Fellowships"],
        "competitions": [],
        "books": ["Silent Spring by Rachel Carson", "The Sixth Extinction by Elizabeth Kolbert"],
        "communities": ["r/conservation (Reddit)", "local wildlife-rehabilitation volunteer networks"],
        "open_source_projects": ["iNaturalist (citizen-science species data)"],
        "certifications": ["Certified Wildlife Biologist (The Wildlife Society)"],
        "projects": ["Run a local biodiversity survey using iNaturalist", "Volunteer with a habitat-restoration project"],
        "videos": ["Our Planet (Netflix, referenced as a documentary)", "National Geographic (YouTube)"],
        "common_misconceptions": ["It's mostly cuddling animals, not rigorous science", "Fieldwork is glamorous travel, not physically demanding work", "Conservation success is quick and easily reversible"],
        "faqs": [
            {"question": "How much fieldwork is really involved?", "answer": "It varies by role, but many conservation biologists spend real, sustained stretches in remote field conditions, especially earlier in their careers."},
            {"question": "Is this career financially viable?", "answer": "Salaries are often modest compared to private-sector science roles, though government, larger NGO, and senior positions can be genuinely competitive."},
        ],
        "adjacent_careers": ["Environmental Policy Analyst", "Wildlife Veterinarian", "Sustainability Analyst", "Park Ranger / Protected Area Manager"],
    },
    "human_rights_researcher": {
        "day_in_the_life": "Work involves documenting real testimonies, verifying facts through cross-referenced sources, and writing detailed reports on rights violations. Interviews (sometimes with vulnerable populations) require real care, ethics training, and trauma-informed practice.",
        "weekly_routine": "Research and documentation fill most weeks, with periodic report launches, advocacy campaigns, or travel for field investigations.",
        "daily_tools": ["Secure documentation and encryption tools", "Open-source investigation techniques (satellite imagery, social media verification)", "Legal case-tracking databases"],
        "career_progression": ["Research Assistant", "Human Rights Researcher", "Senior Researcher", "Research Director"],
        "related_industries": ["human rights advocacy", "international law", "journalism"],
        "research_areas": ["War crimes documentation", "Digital rights and surveillance", "Refugee and migrant rights"],
        "companies": ["Amnesty International", "Human Rights Watch", "International Crisis Group"],
        "universities": ["Columbia Law School (human rights program)", "London School of Economics", "National Law School of India University"],
        "scholarships": ["Open Society Foundations fellowships", "Rhodes Scholarship"],
        "competitions": ["Philip C. Jessup International Law Moot Court Competition"],
        "books": ["Just Mercy by Bryan Stevenson", "Evicted by Matthew Desmond"],
        "communities": ["local Amnesty International student chapters"],
        "open_source_projects": ["Bellingcat's open-source investigation toolkit"],
        "certifications": ["None universal — investigative and legal-research skill matter more"],
        "projects": ["Research and document a real, specific human-rights issue using public sources", "Learn open-source verification techniques (e.g. via Bellingcat's guides)"],
        "videos": ["Amnesty International (YouTube)", "Human Rights Watch (YouTube)"],
        "common_misconceptions": ["This work is the same as being a lawyer", "Documentation alone quickly leads to justice", "It's safe desk research with no real personal risk"],
        "faqs": [
            {"question": "Do I need a law degree?", "answer": "It helps for some roles but isn't required — many human rights researchers come from journalism, area studies, or social science backgrounds."},
            {"question": "Is fieldwork dangerous?", "answer": "It can be — researchers documenting conflicts or repressive environments sometimes face real personal risk, which organizations increasingly train and plan for seriously."},
        ],
        "adjacent_careers": ["International NGO Program Manager", "Investigative Journalist", "International Human Rights Lawyer", "Policy Researcher"],
    },
    "ias_officer_india": {
        "day_in_the_life": "Days vary enormously by posting — a District Collector might handle law-and-order issues, review welfare-scheme implementation, and meet citizens in a public grievance session, all in one day. Real administrative authority comes with real, constant public accountability.",
        "weekly_routine": "A mix of office administration, field inspections, and public hearings, with the specific balance depending heavily on the current posting (district, state secretariat, or central ministry).",
        "daily_tools": ["Government e-governance portals", "District administration MIS systems", "Public grievance redressal systems"],
        "career_progression": ["Sub-Divisional Magistrate", "District Collector/Magistrate", "State Secretary", "Chief Secretary / Cabinet Secretary"],
        "related_industries": ["public administration", "government", "policy implementation"],
        "research_areas": ["Public administration reform", "Welfare-scheme delivery effectiveness"],
        "companies": ["Government of India (state and central administration)"],
        "universities": ["Lal Bahadur Shastri National Academy of Administration (post-selection training)", "Delhi University", "Jawaharlal Nehru University (common preparation backgrounds)"],
        "scholarships": [],
        "competitions": [],
        "books": ["India After Gandhi by Ramachandra Guha", "Indian Administration by S.R. Maheshwari"],
        "communities": ["local UPSC civil-service preparation study groups"],
        "open_source_projects": [],
        "certifications": ["Union Public Service Commission (UPSC) Civil Services Examination"],
        "projects": ["Study a real district administration's public grievance data", "Volunteer with a local government welfare-scheme outreach effort"],
        "videos": ["UPSC preparation channels (YouTube)", "Rajya Sabha TV public-administration documentaries"],
        "common_misconceptions": ["IAS officers have unchecked power", "The exam alone determines success, not the actual administrative work", "Postings are always in major cities"],
        "faqs": [
            {"question": "How competitive is entry into the IAS?", "answer": "Extremely — the UPSC Civil Services Examination has one of the lowest selection rates of any competitive exam globally, often well under 1% of applicants."},
            {"question": "Can I choose my posting location?", "answer": "Preferences can be indicated, but assignments are ultimately made by the government based on need, with officers expected to serve wherever posted."},
        ],
        "adjacent_careers": ["UK Civil Service Fast Streamer (international analogue)", "Public Health Policy Analyst", "Urban Planner", "Foreign Service Officer"],
    },
    "uk_civil_service_fast_streamer": {
        "day_in_the_life": "Work often involves briefing senior civil servants or ministers on a policy area, drafting position papers, and coordinating across departments on real cross-cutting issues. Fast Streamers typically rotate through multiple postings during the scheme.",
        "weekly_routine": "Structured around departmental priorities and parliamentary timetables, with periodic intensive periods around budget announcements or major policy launches.",
        "daily_tools": ["Government briefing and casework systems", "Policy-analysis frameworks", "Cross-departmental collaboration platforms"],
        "career_progression": ["Fast Stream Trainee (2-4 year rotational scheme)", "Higher Executive Officer / Grade 7", "Deputy Director", "Director / Permanent Secretary"],
        "related_industries": ["public administration", "government", "policy"],
        "research_areas": ["Evidence-based policy design", "Public-sector digital transformation"],
        "companies": ["UK Civil Service (across departments — HM Treasury, Home Office, DfE, etc.)"],
        "universities": ["University of Oxford", "University of Cambridge", "London School of Economics"],
        "scholarships": [],
        "competitions": [],
        "books": ["The Blunders of Our Governments by Anthony King and Ivor Crewe", "Recoding America by Jennifer Pahlka"],
        "communities": ["local Civil Service Fast Stream alumni networks"],
        "open_source_projects": ["GOV.UK's open-source design system"],
        "certifications": ["Civil Service Fast Stream selection process (assessment centre, not a formal exam)"],
        "projects": ["Analyze a real UK government policy paper and identify its trade-offs", "Volunteer with a local council on a civic project"],
        "videos": ["Institute for Government (YouTube)", "UK Parliament committee hearings"],
        "common_misconceptions": ["Civil servants make political decisions, not just implement them", "The Fast Stream guarantees rapid promotion regardless of performance", "It's slow-moving bureaucratic work with no real impact"],
        "faqs": [
            {"question": "What's the difference between the Fast Stream and regular civil-service entry?", "answer": "The Fast Stream is a structured, competitive accelerated development scheme with rotations across departments, while standard entry is a direct hire into one role."},
            {"question": "Do I need a specific degree?", "answer": "No — the Fast Stream accepts graduates from any discipline, with different streams (e.g. Economics, Diplomatic) sometimes preferring relevant backgrounds."},
        ],
        "adjacent_careers": ["Indian Administrative Service (IAS) Officer (international analogue)", "Foreign Service Officer", "Public Health Policy Analyst", "Management Consultant"],
    },
    "japan_traditional_craft_master": {
        "day_in_the_life": "Days are structured around long, deliberate hands-on practice — refining technique on real materials (wood, lacquer, ceramics, textiles depending on the craft) under a master's real, ongoing supervision. Precision and patience matter more than speed.",
        "weekly_routine": "Apprentices typically work full days in the workshop for years before creating independent pieces, with the craft's traditional calendar sometimes tied to seasonal materials or festivals.",
        "daily_tools": ["Traditional hand tools specific to the craft (e.g. chisels, kilns, looms)", "Natural raw materials (wood, clay, natural dyes)"],
        "career_progression": ["Apprentice (Deshi)", "Journeyman Craftsperson", "Independent Master (Shokunin)", "Living National Treasure (rare, government-designated status)"],
        "related_industries": ["traditional craftsmanship", "cultural heritage", "luxury goods"],
        "research_areas": ["Traditional technique preservation", "Sustainable natural-material sourcing"],
        "companies": ["Independent workshops; some crafts have guild-like associations (e.g. Kyoto's traditional craft cooperatives)"],
        "universities": ["Kyoto Saga University of Arts (traditional craft programs)", "Formal apprenticeship under a recognized master is the primary real training path, not university"],
        "scholarships": ["Japan Foundation cultural fellowships"],
        "competitions": ["Japan Traditional Kogei Exhibition (Nihon Dento Kogeiten)"],
        "books": ["The Unknown Craftsman by Soetsu Yanagi", "Wabi-Sabi for Artists, Designers, Poets and Philosophers by Leonard Koren"],
        "communities": ["local traditional-craft guild associations in Japan"],
        "open_source_projects": [],
        "certifications": ["Designation as a Traditional Craft by Japan's Ministry of Economy, Trade and Industry (for the craft itself, not individuals)"],
        "projects": ["Learn a basic traditional craft technique through a beginner workshop (e.g. pottery, woodblock printing)", "Study the history and cultural context of one specific traditional craft in depth"],
        "videos": ["Process X (YouTube — Japanese craft documentaries)", "Kyoto Journal craft features"],
        "common_misconceptions": ["Anyone can master a traditional craft in a few years", "This is purely artistic work with no real business/economic dimension", "These crafts are dying out with no real modern relevance"],
        "faqs": [
            {"question": "How long does a real apprenticeship typically take?", "answer": "Often a decade or more before a craftsperson is considered to have real independent mastery — this is a genuinely long, deliberate training path, not a quick certification."},
            {"question": "Is this career path only open to people in Japan?", "answer": "In practice, most master craftspeople train within Japan under a recognized master, though a small number of international apprentices have been accepted by individual workshops."},
        ],
        "adjacent_careers": ["Museum Conservator", "Cultural Heritage Preservationist", "Design Consultant", "Fine Artist"],
    },
}


async def enrich() -> None:
    client = get_supabase_client()
    missing_from_catalog = []
    for career_id, fields in ENRICHMENTS.items():
        # Validate the payload shape against the Career model's field
        # types before writing (catches typos without touching the DB).
        Career.model_validate({**_placeholder_required_fields(), "id": career_id, **fields})

        def _update(cid: str = career_id, payload: dict = fields) -> None:
            result = client.table("careers").update(payload).eq("id", cid).execute()
            if not result.data:
                missing_from_catalog.append(cid)

        await asyncio.to_thread(_update)

    if missing_from_catalog:
        print(f"WARNING — no matching row updated for: {missing_from_catalog}")
    print(f"Enriched {len(ENRICHMENTS) - len(missing_from_catalog)} of {len(ENRICHMENTS)} careers.")


def _placeholder_required_fields() -> dict:
    """Minimal stand-in values for Career's other required fields, used
    only to validate the *shape* of each enrichment payload locally
    before writing — never sent to the database."""
    return {
        "name": "x", "category": "x", "industry": "x", "one_liner": "x",
        "reality": {
            "daily_work": "x", "work_environment": "x", "collaboration_level": "x", "creativity_level": "x",
            "research_intensity": "x", "learning_curve": "x", "travel": "x", "remote_possibility": "x",
            "stress_factors": "x", "typical_challenges": "x", "misconceptions": "x", "long_term_growth": "x",
            "required_education": "x",
        },
        "future_lens": {
            "ai_impact": "x", "automation_risk": "x", "demand_2030": "x", "demand_2035": "x", "demand_2040": "x",
            "emerging_opportunities": "x", "timeline_narrative": "x",
        },
    }


if __name__ == "__main__":
    asyncio.run(enrich())
