"""One-time seed script for Discover Batch 5's Learning Style Discovery
catalog.

Run via: python -m aureon.scripts.seed_learning_styles

All 12 real learning dimensions, each with rich, real, research-backed
content — study strategies, note-taking/memory techniques, productivity
systems, books, courses, and communities. Every entry carries its own
`source_note` honesty disclaimer (see domain/models/learning_style.py).
Idempotent: upserts by id, safe to re-run.
"""

import asyncio

from aureon.domain.models.learning_style import LearningStyle
from aureon.services.supabase.client import get_supabase_client

STYLES: list[dict] = [
    {
        "id": "style_visual",
        "name": "Visual",
        "description": "Learns best through diagrams, images, spatial layouts, and visual organization of information — seeing how ideas connect matters more than hearing or reading them in isolation.",
        "strengths": ["Quickly spots patterns and relationships", "Strong spatial and diagrammatic reasoning", "Remembers what things looked like", "Good at interpreting charts and visual data"],
        "excels_in": ["Subjects with diagrams (biology, geography, engineering)", "Data visualization and analysis", "Design and layout work", "Following visual instructions or maps"],
        "common_struggles": ["Long text-only lectures without visuals", "Purely verbal instructions with no diagram", "Abstract concepts with no visual analogy"],
        "study_strategies": ["Redraw concepts as your own diagrams", "Use color-coding for categories", "Convert notes into mind maps after class", "Watch visual explainer videos before reading dense text"],
        "note_taking_techniques": ["Mind Mapping", "Sketchnoting", "Charting Method", "Concept diagrams with arrows showing relationships"],
        "memory_strategies": ["Method of Loci (memory palace)", "Visual mnemonics", "Color-coded chunking", "Diagram-based spaced repetition"],
        "active_learning_methods": ["Draw the concept before checking the textbook diagram", "Build a visual timeline for historical or process-based topics", "Create infographics summarizing a chapter"],
        "project_ideas": ["Design an infographic explaining a complex topic", "Build a visual concept map connecting a semester's material", "Create a comic strip explaining a process"],
        "practice_routines": ["Redraw yesterday's diagram from memory each morning", "Weekly infographic summary of what you learned", "Color-code notes within 24 hours of taking them"],
        "collaboration_techniques": ["Whiteboard sessions with peers", "Co-building a shared visual concept map", "Peer-review of diagrams for clarity"],
        "learning_environments": ["A space with a whiteboard or large drawing surface", "Well-lit areas with room to spread out visual materials", "Digital tools with an infinite canvas"],
        "productivity_systems": ["Visual Kanban boards", "Bullet Journal Method with diagrams", "Time-blocking with color-coded calendar blocks"],
        "recommended_books": ["The Back of the Napkin by Dan Roam", "Visual Thinking by Temple Grandin", "Make It Stick by Peter C. Brown"],
        "research_backed_resources": ["Dual coding theory research (Allan Paivio)", "Multimedia learning principles (Richard Mayer)"],
        "online_courses": ["Coursera's Learning How to Learn", "MIT OpenCourseWare visual-heavy STEM courses"],
        "communities": ["r/dataisbeautiful (Reddit)", "Sketchnote Army community"],
        "ways_to_strengthen": ["Practice explaining a diagram out loud (Discussion-Based)", "Write a short summary before drawing it (Reading)"],
        "keywords": ["visual", "diagram", "picture", "see it", "visualize", "chart", "image", "map"],
    },
    {
        "id": "style_reading",
        "name": "Reading",
        "description": "Learns best by engaging directly with well-structured written text — articles, textbooks, and long-form explanations that can be reread and annotated at your own pace.",
        "strengths": ["Strong independent comprehension", "Can absorb dense material carefully", "Retains detail from written sources well", "Comfortable with self-paced study"],
        "excels_in": ["Research-heavy subjects", "Humanities and literature", "Self-directed online courses with reading material", "Long-form technical documentation"],
        "common_struggles": ["Fast-paced verbal lectures with no written backup", "Group discussions that move faster than you can process", "Purely hands-on tasks with no written instructions"],
        "study_strategies": ["Annotate as you read, don't just highlight", "Summarize each section in your own words", "Reread key passages a day later", "Convert readings into your own short essays"],
        "note_taking_techniques": ["Cornell Notes", "Outline Method", "Sentence Method", "Marginal annotation"],
        "memory_strategies": ["Active recall through self-quizzing on read material", "Spaced repetition of key passages", "Elaborative rehearsal — explaining what you read in new words"],
        "active_learning_methods": ["Write a one-paragraph summary after each reading", "Turn headings into questions before reading, then answer them", "Compare two texts on the same topic"],
        "project_ideas": ["Write a research essay synthesizing multiple sources", "Keep a reading journal with reflections per book or article", "Curate an annotated reading list for a topic"],
        "practice_routines": ["20-30 minutes of focused reading with no interruptions daily", "Weekly summary writing of everything read that week", "Reread and revise notes every Sunday"],
        "collaboration_techniques": ["Book clubs or reading groups", "Exchange written summaries with a study partner", "Peer-edit each other's written syntheses"],
        "learning_environments": ["Quiet, distraction-free reading space", "A library or dedicated reading nook", "Environments with minimal auditory noise"],
        "productivity_systems": ["Time-blocking dedicated reading sessions", "Getting Things Done (GTD) for tracking reading lists", "Pomodoro Technique for sustained reading focus"],
        "recommended_books": ["How to Read a Book by Mortimer Adler", "Make It Stick by Peter C. Brown", "A Mind for Numbers by Barbara Oakley"],
        "research_backed_resources": ["Research on the generation effect (self-generated summaries aid retention)", "Studies on retrieval practice for reading comprehension"],
        "online_courses": ["Coursera's Learning How to Learn", "edX humanities and literature courses"],
        "communities": ["r/GetStudying (Reddit)", "Goodreads reading groups"],
        "ways_to_strengthen": ["Summarize a reading aloud to someone else (Discussion-Based)", "Sketch a quick diagram of a text's structure (Visual)"],
        "keywords": ["read", "reading", "text", "article", "book", "written"],
    },
    {
        "id": "style_listening",
        "name": "Listening",
        "description": "Learns best through spoken explanation — lectures, podcasts, discussions, and audio — processing ideas most naturally when they're heard rather than read or seen.",
        "strengths": ["Strong auditory memory and recall of spoken detail", "Comfortable following verbal instructions", "Good at picking up nuance in tone and explanation", "Can multitask learning with other activities like commuting"],
        "excels_in": ["Lecture-heavy courses", "Language learning through conversation", "Podcasts and audiobooks", "Verbal storytelling-based subjects like history"],
        "common_struggles": ["Silent, text-only self-study", "Environments with a lot of background noise", "Purely visual or diagram-only material with no narration"],
        "study_strategies": ["Record yourself explaining a concept and listen back", "Convert readings into audio using text-to-speech", "Listen to a topic explained by two different sources for reinforcement", "Recite key facts out loud while studying"],
        "note_taking_techniques": ["Voice-memo notes summarized later", "Verbal Cornell-style recall (say the cue, then the answer aloud)", "Recorded lecture annotations"],
        "memory_strategies": ["Mnemonic rhymes or songs", "Repeating information aloud (active recall by speaking)", "Spaced repetition using audio flashcard apps"],
        "active_learning_methods": ["Explain a concept out loud as if teaching it", "Listen to a podcast episode, then summarize verbally", "Debate a topic with a study partner"],
        "project_ideas": ["Record a podcast episode explaining a topic you're learning", "Host a study group discussion and lead the explanation", "Create an audio study guide for a subject"],
        "practice_routines": ["Daily podcast or audiobook time related to your subject", "Weekly recorded self-explanation of what you learned", "Listen-and-repeat practice for language or technical terms"],
        "collaboration_techniques": ["Study groups centered on verbal discussion", "Teach-back sessions with a peer", "Podcast-style co-review of material with a partner"],
        "learning_environments": ["Environments where speaking aloud is welcome", "Headphone-friendly spaces for audio content", "Group discussion rooms"],
        "productivity_systems": ["Time-blocking dedicated to audio learning during commutes or chores", "Pomodoro Technique combined with recorded review sessions"],
        "recommended_books": ["Fluent Forever by Gabriel Wyner", "Make It Stick by Peter C. Brown"],
        "research_backed_resources": ["Research on the testing effect via verbal recall", "Studies on dual-coding combining audio with imagery"],
        "online_courses": ["Audible Originals learning series", "Duolingo Podcast for language learners"],
        "communities": ["r/podcasts (Reddit)", "language-exchange conversation communities (e.g. Tandem)"],
        "ways_to_strengthen": ["Pair audio learning with written notes afterward (Reading)", "Sketch what you heard as a diagram (Visual)"],
        "keywords": ["listen", "listening", "audio", "podcast", "hear", "lecture", "spoken"],
    },
    {
        "id": "style_practical",
        "name": "Practical",
        "description": "Learns best by physically doing the task — hands-on manipulation, building, and direct application beats reading or watching about it first.",
        "strengths": ["Strong muscle-memory and applied skill retention", "Comfortable learning by trial and error", "Quick to translate theory into working output", "Good troubleshooting instincts"],
        "excels_in": ["Lab work and hands-on engineering", "Trades and craft-based skills", "Coding by building real projects", "Cooking, repair, and physical-skill subjects"],
        "common_struggles": ["Long theory-only lectures before any hands-on work", "Purely abstract math with no applied example", "Waiting through extended reading before getting to try something"],
        "study_strategies": ["Start with a small hands-on task before reading the full theory", "Learn just enough to attempt something, then fill gaps as you go", "Rebuild a working example from scratch without looking"],
        "note_taking_techniques": ["Step-by-step how-to logs written while doing the task", "Annotated diagrams of physical setups", "Troubleshooting logs of what worked and what didn't"],
        "memory_strategies": ["Muscle memory through repeated hands-on practice", "Learning by teaching someone else to do the task", "Physically rebuilding something from memory"],
        "active_learning_methods": ["Build a small working prototype before studying the full theory", "Debug a broken example to understand how it should work", "Reverse-engineer something that already works"],
        "project_ideas": ["Build a physical or digital prototype end-to-end", "Take apart and reassemble something to understand it", "Complete a hands-on tutorial project, then modify it"],
        "practice_routines": ["Daily short hands-on practice session, even 15 minutes", "Weekly build-something-real challenge", "Fix or improve one small thing regularly"],
        "collaboration_techniques": ["Pair-building with a partner (like pair programming)", "Group builds or maker sessions", "Peer troubleshooting sessions"],
        "learning_environments": ["A workshop, lab, or maker space", "A desk set up for hands-on tinkering", "Environments with real tools and materials available"],
        "productivity_systems": ["Kanban boards tracking build progress", "Time-blocking for dedicated build sessions", "Checklists for multi-step hands-on procedures"],
        "recommended_books": ["The Practicing Mind by Thomas M. Sterner", "Shop Class as Soulcraft by Matthew Crawford", "Make It Stick by Peter C. Brown"],
        "research_backed_resources": ["Research on experiential/kinesthetic learning (Kolb's learning cycle)", "Studies on productive failure in hands-on problem-solving"],
        "online_courses": ["freeCodeCamp project-based coding curriculum", "Instructables hands-on project guides"],
        "communities": ["r/DIY (Reddit)", "local maker-space communities"],
        "ways_to_strengthen": ["Write a short explanation of what you built (Reading)", "Explain your build out loud to a peer (Discussion-Based)"],
        "keywords": ["hands-on", "hands on", "practical", "build", "made", "tried it", "physically"],
    },
    {
        "id": "style_experimental",
        "name": "Experimental",
        "description": "Learns best by testing, trying different approaches, and iterating — comfortable with uncertainty, treating learning itself as a series of small experiments.",
        "strengths": ["Comfortable with trial and error", "Adapts quickly when an approach isn't working", "Good at generating and testing hypotheses", "Learns fast from direct feedback"],
        "excels_in": ["Scientific experimentation", "Iterative design and prototyping", "A/B testing and data-driven decision-making", "Creative fields that reward exploration"],
        "common_struggles": ["Rigid, one-correct-method instruction", "Environments that punish failed attempts", "Highly structured curricula with no room to explore"],
        "study_strategies": ["Try multiple approaches to the same problem before settling on one", "Predict an outcome, then test it", "Keep a log of what worked and what didn't and why"],
        "note_taking_techniques": ["Hypothesis-and-result logs", "Iteration journals tracking each attempt", "Before/after comparison notes"],
        "memory_strategies": ["Learning through failure — what didn't work is often stickier than being told the right answer directly", "Testing yourself with variations of a problem"],
        "active_learning_methods": ["Run a small experiment to test an assumption before reading the answer", "Try three different solutions to the same problem and compare", "Deliberately break something to see how it fails"],
        "project_ideas": ["Run a real A/B test on something you control", "Build multiple versions of a small project and compare outcomes", "Design and run a simple experiment with a real hypothesis"],
        "practice_routines": ["Weekly 'try something new' experiment", "Keep an ongoing experiment log", "Revisit failed attempts monthly to see what's changed"],
        "collaboration_techniques": ["Peer hypothesis review before testing", "Group brainstorm-then-test sessions", "Compare results with others who tried the same experiment"],
        "learning_environments": ["Low-stakes environments where failure is safe", "Spaces with room to iterate quickly", "Sandbox or practice environments separate from graded work"],
        "productivity_systems": ["Iterative sprints with short review cycles", "Kanban boards tracking experiments in progress", "Retrospectives after each attempt"],
        "recommended_books": ["The Lean Startup by Eric Ries", "Black Box Thinking by Matthew Syed", "Make It Stick by Peter C. Brown"],
        "research_backed_resources": ["Research on productive failure (Manu Kapur)", "Studies on the benefits of generation before instruction"],
        "online_courses": ["Khan Academy's scientific method modules", "Coursera's Experimentation for Improvement courses"],
        "communities": ["r/AskScience (Reddit)", "local science-fair and hackathon communities"],
        "ways_to_strengthen": ["Write up your experiment results formally afterward (Reading)", "Follow a structured plan for at least one experiment (Structured)"],
        "keywords": ["experiment", "test", "trial", "tried different", "iterate", "hypothesis"],
    },
    {
        "id": "style_collaborative",
        "name": "Collaborative",
        "description": "Learns best with and through other people — discussion, group work, and shared problem-solving sharpen understanding more than solitary study.",
        "strengths": ["Strong at building on others' ideas", "Learns quickly from peer explanation", "Good at synthesizing multiple perspectives", "Motivated by shared accountability"],
        "excels_in": ["Group projects", "Peer tutoring and study groups", "Team-based problem-solving", "Discussion-based seminars"],
        "common_struggles": ["Long stretches of solitary, silent study", "Environments with no opportunity to check understanding with others", "Purely individual, competitive assessment structures"],
        "study_strategies": ["Form or join a regular study group", "Explain concepts to a peer and ask them to explain back", "Divide material among a group and teach each other"],
        "note_taking_techniques": ["Shared collaborative notes (e.g. shared docs)", "Group-annotated readings", "Discussion-summary notes after group sessions"],
        "memory_strategies": ["The protégé effect — teaching material to someone else", "Group quiz-each-other sessions", "Discussing material shortly after learning it to reinforce it"],
        "active_learning_methods": ["Peer teaching", "Group problem-solving sessions", "Structured debate on course material"],
        "project_ideas": ["Organize a study group with a shared syllabus", "Co-author a project or presentation with peers", "Run a peer-teaching series on a topic"],
        "practice_routines": ["Weekly study-group session", "Regular teach-back sessions with a peer", "Post-lecture discussion debrief with classmates"],
        "collaboration_techniques": ["Structured peer teaching", "Jigsaw method — each person masters a part, then teaches the group", "Group concept-mapping sessions"],
        "learning_environments": ["Group study rooms", "Discussion-based classrooms or seminars", "Online study communities with active discussion"],
        "productivity_systems": ["Shared task boards for group projects", "Scheduled recurring study-group meetings", "Shared accountability check-ins"],
        "recommended_books": ["Make It Stick by Peter C. Brown", "Peer Instruction by Eric Mazur"],
        "research_backed_resources": ["Research on peer instruction (Eric Mazur)", "Studies on the protégé effect and teaching-to-learn"],
        "online_courses": ["Coursera courses with active discussion forums", "StudyTogether.com virtual co-study sessions"],
        "communities": ["StudyTogether Discord", "local study-group and peer-tutoring networks"],
        "ways_to_strengthen": ["Spend focused solo time consolidating what the group covered (Independent)", "Write personal notes after a group session (Reading)"],
        "keywords": ["with others", "team", "group", "together", "discuss with", "peers"],
    },
    {
        "id": "style_independent",
        "name": "Independent",
        "description": "Learns best working alone, at your own pace, following your own structure — deep focus without needing external discussion to process ideas.",
        "strengths": ["Strong self-direction and self-motivation", "Comfortable with deep, uninterrupted focus", "Sets and follows a personal learning pace well", "Doesn't need external validation to stay on track"],
        "excels_in": ["Self-paced online courses", "Independent research projects", "Deep-focus technical or creative work", "Long-term personal study goals"],
        "common_struggles": ["Group-mandatory assignments with no individual component", "Environments requiring constant check-ins or discussion", "Learning paths with no room for self-pacing"],
        "study_strategies": ["Set your own study schedule and stick to it", "Work through material at your own depth before seeking outside input", "Use self-testing rather than group quizzing to check understanding"],
        "note_taking_techniques": ["Personal outline systems tailored to your own logic", "Zettelkasten — personal networked notes", "Private journal-style reflection notes"],
        "memory_strategies": ["Self-paced spaced repetition", "Independent retrieval practice without external prompting", "Solo elaborative rehearsal — explaining concepts to yourself"],
        "active_learning_methods": ["Self-quizzing before checking answers", "Independent project-based deep dives", "Solo teach-yourself sessions using the Feynman Technique"],
        "project_ideas": ["Design and complete a self-directed capstone project", "Build a personal learning curriculum for a new skill", "Keep a solo learning journal tracking progress over months"],
        "practice_routines": ["Daily uninterrupted deep-work block", "Weekly solo review of everything learned", "Monthly self-assessment against personal goals"],
        "collaboration_techniques": ["Occasional check-ins with a mentor rather than a peer group", "Asynchronous feedback exchanges instead of live discussion", "Solo-then-share: work alone first, share results after"],
        "learning_environments": ["A quiet, personal workspace", "Environments with minimal interruption", "Flexible-schedule settings that don't require synced group time"],
        "productivity_systems": ["Deep Work-style focus blocks", "Personal Kanban systems", "Self-managed Pomodoro cycles"],
        "recommended_books": ["Deep Work by Cal Newport", "Ultralearning by Scott Young", "Make It Stick by Peter C. Brown"],
        "research_backed_resources": ["Research on self-regulated learning", "Studies on deliberate practice (Anders Ericsson)"],
        "online_courses": ["MIT OpenCourseWare self-paced tracks", "Coursera self-paced specializations"],
        "communities": ["r/GetDisciplined (Reddit)", "solo-learner accountability communities"],
        "ways_to_strengthen": ["Occasionally explain what you've learned to someone else (Discussion-Based)", "Join a study group for one topic a month (Collaborative)"],
        "keywords": ["on my own", "myself", "alone", "independently", "solo", "by myself"],
    },
    {
        "id": "style_project_based",
        "name": "Project-Based",
        "description": "Learns best by working toward a real, tangible outcome — a project with a beginning, middle, and end gives learning purpose and structure that abstract study alone doesn't.",
        "strengths": ["Strong at sustained, goal-directed effort", "Good at connecting separate skills toward one outcome", "Comfortable managing multi-step work", "Motivated by visible, real results"],
        "excels_in": ["Capstone and portfolio projects", "Applied engineering and design work", "Long-form creative work such as writing a book or building an app", "Real-world problem-solving assignments"],
        "common_struggles": ["Learning isolated facts with no larger purpose", "Short, disconnected exercises with no cumulative outcome", "Assessment structures that don't build toward anything real"],
        "study_strategies": ["Frame every topic as 'what project could this support?'", "Break a large project into weekly milestones", "Apply new material directly into an ongoing project"],
        "note_taking_techniques": ["Project logs tracking decisions and progress", "Milestone-based notes", "Retrospective notes after each project phase"],
        "memory_strategies": ["Learning sticks better when tied to a real project outcome", "Reviewing project decisions to reinforce why choices were made", "Building a portfolio as a long-term memory aid"],
        "active_learning_methods": ["Start a project before you feel fully ready", "Apply each new concept directly to the ongoing project", "Do a project retrospective to consolidate learning"],
        "project_ideas": ["Build an end-to-end personal project applying multiple skills", "Complete a public portfolio piece", "Take on a real community or school problem as a project"],
        "practice_routines": ["Weekly project milestone check-ins", "Daily small project progress, even 20 minutes", "Monthly project retrospectives"],
        "collaboration_techniques": ["Team-based project sprints", "Peer project reviews", "Milestone check-ins with a mentor or team"],
        "learning_environments": ["A dedicated project workspace", "Environments that support sustained multi-week work", "Access to the tools a project genuinely requires"],
        "productivity_systems": ["Kanban boards for project management", "Milestone-based Gantt-style planning", "Weekly sprint reviews"],
        "recommended_books": ["Getting Things Done by David Allen", "The Lean Startup by Eric Ries", "Make It Stick by Peter C. Brown"],
        "research_backed_resources": ["Research on project-based learning (Buck Institute for Education)", "Studies on goal-setting theory (Locke and Latham)"],
        "online_courses": ["freeCodeCamp project curriculum", "Coursera project-based specializations"],
        "communities": ["r/SideProject (Reddit)", "local hackathon and project-showcase communities"],
        "ways_to_strengthen": ["Study the underlying theory more deeply between project phases (Reading)", "Get structured feedback partway through (Structured)"],
        "keywords": ["project", "built a", "created a", "milestone", "end to end"],
    },
    {
        "id": "style_structured",
        "name": "Structured",
        "description": "Learns best with clear sequence, defined steps, and a predictable framework — a well-organized curriculum or checklist makes complex material genuinely manageable.",
        "strengths": ["Strong at following multi-step processes reliably", "Good at tracking progress against a clear plan", "Comfortable with defined expectations", "Rarely misses steps in a complex procedure"],
        "excels_in": ["Structured curricula with clear syllabi", "Certification programs with defined modules", "Process-heavy fields like accounting or law", "Step-by-step technical training"],
        "common_struggles": ["Open-ended, ambiguous assignments with no clear framework", "Rapidly changing requirements mid-task", "Purely exploratory, unstructured learning environments"],
        "study_strategies": ["Build a clear study schedule and follow it consistently", "Break material into a numbered sequence of sub-topics", "Use checklists to confirm nothing was skipped"],
        "note_taking_techniques": ["Outline Method with clear hierarchy", "Numbered step-by-step notes", "Checklist-style summaries"],
        "memory_strategies": ["Sequential rehearsal — reviewing material in the same order it was taught", "Structured spaced-repetition schedules", "Framework-based mnemonics such as acronyms for ordered steps"],
        "active_learning_methods": ["Follow a step-by-step tutorial exactly once, then repeat from memory", "Create a checklist for a multi-step process and test yourself against it", "Build a personal syllabus for self-study topics"],
        "project_ideas": ["Create a structured study guide or syllabus for a subject", "Document a multi-step process as a clear how-to guide", "Build a certification-style personal curriculum"],
        "practice_routines": ["Fixed daily or weekly study schedule", "Checklist review at the end of each study session", "Weekly progress tracking against a plan"],
        "collaboration_techniques": ["Structured study groups with a fixed agenda", "Accountability partners tracking a shared schedule", "Peer review against a clear rubric"],
        "learning_environments": ["A consistent, predictable study space", "Environments with minimal last-minute changes", "Settings with clear posted schedules or syllabi"],
        "productivity_systems": ["Getting Things Done (GTD)", "Time-blocking with a fixed weekly template", "Checklists and numbered task lists"],
        "recommended_books": ["Getting Things Done by David Allen", "Atomic Habits by James Clear", "Make It Stick by Peter C. Brown"],
        "research_backed_resources": ["Research on structured practice schedules (Rohrer and Pashler)", "Studies on implementation intentions (Gollwitzer)"],
        "online_courses": ["Coursera specializations with fixed weekly modules", "Structured MOOCs with clear syllabi on edX"],
        "communities": ["r/productivity (Reddit)", "GTD and structured-planning communities"],
        "ways_to_strengthen": ["Try one open-ended, unscheduled study session a week (Exploratory)", "Test a concept in a new, unplanned context (Experimental)"],
        "keywords": ["step by step", "structured", "plan", "schedule", "organized", "checklist"],
    },
    {
        "id": "style_exploratory",
        "name": "Exploratory",
        "description": "Learns best by wandering into a topic out of genuine curiosity — following interesting tangents rather than a fixed path, letting questions lead to more questions.",
        "strengths": ["Strong intrinsic curiosity and self-motivation to explore", "Good at making unexpected connections across topics", "Comfortable with open-ended, undefined learning", "Naturally asks good follow-up questions"],
        "excels_in": ["Independent research with open questions", "Interdisciplinary topics", "Early-stage exploration of a new field", "Self-directed online rabbit-holes that turn into real expertise"],
        "common_struggles": ["Rigid, fixed-sequence curricula with no room to wander", "Assessment structures that penalize going off-topic", "Environments that discourage follow-up questions"],
        "study_strategies": ["Follow your own questions even if they lead off the assigned material", "Start broad, then narrow based on what genuinely interests you", "Keep a running list of tangents to explore later"],
        "note_taking_techniques": ["Zettelkasten — networked, non-linear notes", "Mind Mapping that grows organically", "A running curiosity log of open questions"],
        "memory_strategies": ["Genuine curiosity increases retention (interest-driven encoding)", "Connecting new ideas to existing tangents you already care about", "Revisiting old rabbit-holes to reinforce the connections"],
        "active_learning_methods": ["Start with one interesting question and see where it leads", "Cross-reference a topic across two unrelated fields", "Spend unstructured time simply exploring a topic's related pages"],
        "project_ideas": ["Build a personal wiki documenting your exploration of a topic", "Create a curated resource list from your own exploration", "Write a post connecting two seemingly unrelated interests"],
        "practice_routines": ["Weekly unstructured exploration time with no fixed goal", "Follow-up research on any question that came up that week", "Monthly review of what tangents turned into real interests"],
        "collaboration_techniques": ["Share interesting tangents with a curious peer group", "Exploratory brainstorming sessions with no fixed agenda", "Co-exploring a new topic together with a friend"],
        "learning_environments": ["Environments with easy access to broad resources like a good library or the open internet", "Low-pressure spaces with no fixed deadline", "Settings that welcome follow-up questions"],
        "productivity_systems": ["Loose, flexible task lists rather than rigid schedules", "A curiosity backlog instead of a fixed syllabus", "Time-boxed rather than topic-boxed exploration sessions"],
        "recommended_books": ["Range by David Epstein", "Curious by Ian Leslie", "A Mind for Numbers by Barbara Oakley"],
        "research_backed_resources": ["Research on curiosity and memory encoding (Gruber et al.)", "Studies on interest-driven learning outcomes"],
        "online_courses": ["Wikipedia's Vital Articles as an exploration starting point", "TED-Ed's curated curiosity playlists"],
        "communities": ["r/todayilearned (Reddit)", "r/explainlikeimfive (Reddit)"],
        "ways_to_strengthen": ["Occasionally structure one exploration into a formal project (Project-Based)", "Write up an exploration as organized notes afterward (Structured)"],
        "keywords": ["explore", "curious", "wandered", "wondered", "tangent", "rabbit hole"],
    },
    {
        "id": "style_analytical",
        "name": "Analytical",
        "description": "Learns best by breaking ideas into logical parts, understanding underlying reasoning, and working through the 'why' rather than memorizing the 'what.'",
        "strengths": ["Strong logical reasoning and problem decomposition", "Good at spotting inconsistencies or gaps in an argument", "Comfortable with abstract, rule-based systems", "Retains material better once the logic behind it is clear"],
        "excels_in": ["Mathematics and formal logic", "Debugging and systems troubleshooting", "Argument analysis and critical writing", "Data analysis and statistics"],
        "common_struggles": ["Memorization-only material with no underlying logic explained", "Ambiguous, emotionally-driven content with no clear structure", "Being told an answer without the reasoning behind it"],
        "study_strategies": ["Ask 'why' at every step until the logic is fully clear", "Derive a formula or rule yourself before memorizing it", "Break a complex problem into smaller logical sub-problems"],
        "note_taking_techniques": ["Outline Method organized by logical dependency", "Proof-style notes showing each reasoning step", "Cause-and-effect diagrams"],
        "memory_strategies": ["Understanding-first retention — logic sticks longer than rote memorization", "Deriving rather than memorizing formulas", "Testing understanding by explaining the reasoning, not just the answer"],
        "active_learning_methods": ["Solve a problem before checking the worked solution", "Find the flaw in a deliberately incorrect argument", "Derive a known result from first principles"],
        "project_ideas": ["Build a small logical or mathematical proof from scratch", "Debug a real broken system and document your reasoning", "Analyze a real dataset and justify each conclusion"],
        "practice_routines": ["Daily problem-solving practice with self-explanation", "Weekly 'derive it yourself' session for a known formula or rule", "Review past mistakes by identifying the exact logical gap"],
        "collaboration_techniques": ["Structured debate defending a reasoned position", "Peer problem-solving with reasoning explained aloud", "Group logic-puzzle or case-study sessions"],
        "learning_environments": ["Quiet, distraction-minimal spaces for sustained reasoning", "Environments with a whiteboard for working through logic", "Settings that allow uninterrupted problem-solving time"],
        "productivity_systems": ["Structured problem sets with self-explanation built in", "Time-blocking for deep analytical work", "Checklists for multi-step logical procedures"],
        "recommended_books": ["A Mind for Numbers by Barbara Oakley", "Thinking, Fast and Slow by Daniel Kahneman", "How to Solve It by George Pólya"],
        "research_backed_resources": ["Research on the generation effect for problem-solving", "Studies on self-explanation and learning gains (Michelene Chi)"],
        "online_courses": ["Brilliant.org logic and math courses", "MIT OpenCourseWare mathematics and CS theory"],
        "communities": ["r/learnmath (Reddit)", "r/logic (Reddit)"],
        "ways_to_strengthen": ["Sketch a diagram of the logical structure (Visual)", "Explain your reasoning out loud to a peer (Discussion-Based)"],
        "keywords": ["analyze", "figured out", "logic", "reasoned", "understand why", "systems"],
    },
    {
        "id": "style_discussion_based",
        "name": "Discussion-Based",
        "description": "Learns best by talking ideas through — asking questions, debating, and refining understanding out loud in real-time conversation with others.",
        "strengths": ["Strong at articulating and refining ideas verbally", "Quick to spot gaps in understanding through conversation", "Comfortable challenging and being challenged", "Good at synthesizing multiple viewpoints in real time"],
        "excels_in": ["Seminar and discussion-based courses", "Socratic-method teaching environments", "Debate and argumentation", "Case-study analysis with group discussion"],
        "common_struggles": ["Purely silent, solitary study with no chance to talk it through", "One-way lecture formats with no room for questions", "Written-only assessment with no verbal component"],
        "study_strategies": ["Talk through a concept with someone before considering it learned", "Ask a genuine question and pursue the answer through conversation", "Debate both sides of a topic, even solo, to stress-test understanding"],
        "note_taking_techniques": ["Discussion-summary notes written right after a conversation", "Question-and-answer format notes", "Dialogue-style notes capturing different viewpoints"],
        "memory_strategies": ["Generating and articulating ideas out loud strengthens retention", "Revisiting a topic through a follow-up conversation", "Explaining a concept to someone new to reinforce it"],
        "active_learning_methods": ["Socratic self-questioning out loud", "Structured debate on course material", "Real-time Q&A sessions with an instructor or peer"],
        "project_ideas": ["Organize a discussion or debate series on a topic", "Host a podcast-style conversation exploring a subject", "Run a Socratic seminar with peers"],
        "practice_routines": ["Weekly discussion session on current material", "Daily 'talk it through' review with a study partner", "Regular Q&A with an instructor or mentor"],
        "collaboration_techniques": ["Structured Socratic seminars", "Debate practice with assigned positions", "Real-time peer Q&A sessions"],
        "learning_environments": ["Discussion-based classrooms or seminar rooms", "Environments where speaking up is encouraged", "Small-group settings that allow real conversation"],
        "productivity_systems": ["Scheduled recurring discussion sessions", "Structured debate formats with time limits", "Discussion-log tracking of open questions"],
        "recommended_books": ["Peer Instruction by Eric Mazur", "Getting to Yes by Roger Fisher and William Ury", "Make It Stick by Peter C. Brown"],
        "research_backed_resources": ["Research on Socratic questioning and deep learning", "Studies on peer instruction outcomes (Eric Mazur)"],
        "online_courses": ["Coursera courses with live discussion sections", "Public-speaking and debate courses"],
        "communities": ["StudyTogether Discord", "local debate club and Socratic seminar networks"],
        "ways_to_strengthen": ["Write up your conclusions after a discussion (Reading)", "Spend solo time processing before the next conversation (Independent)"],
        "keywords": ["talked about", "discussion", "conversation", "debate", "asked questions"],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    styles = [LearningStyle.model_validate(s) for s in STYLES]

    def _upsert() -> None:
        client.table("learning_styles").upsert([s.model_dump(mode="json") for s in styles]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(styles)} learning styles.")


if __name__ == "__main__":
    asyncio.run(seed())
