"""Connect Batch 1 — Expert Connect seed data, Technology/Space/Climate
domain group. An expert IS a Mentor (see domain/models/mentor.py) — this
upserts into the same `mentors` table the original 15 mentors live in,
using `expert_*` ids to avoid any collision.

Every profile clears the Content Quality Bar from the approved plan:
specific, first-person, vulnerable narrative — never interchangeable
platitudes. Run via: python -m aureon.scripts.seed_experts_tech_and_science
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_backend_engineer_maria_santos",
        "name": "Maria Santos, Senior Backend Engineer",
        "role_type": "industry_professional",
        "field": "software engineering",
        "bio": "Builds and scales backend systems for a fintech payments platform processing millions of transactions daily; previously worked at two failed startups before landing here.",
        "trait_tags": ["analytical_thinking", "persistence"],
        "learning_style_fit": "Students who learn by breaking things and reading stack traces rather than watching tutorials passively.",
        "organization": "A mid-size fintech company",
        "years_experience": 9,
        "journey_highlights": ["Two startups she joined shut down within a year", "Rebuilt a payments pipeline that was losing the company money on every failed retry"],
        "discussion_topics": ["Distributed systems basics", "Surviving a startup shutdown", "Backend career paths"],
        "profession": "Senior Backend Engineer",
        "specialization": "Distributed payment systems",
        "country": "Brazil",
        "city": "São Paulo",
        "industries": ["technology", "fintech"],
        "education": ["BSc Computer Science, University of São Paulo"],
        "current_role": "Senior Backend Engineer, Payments Infrastructure",
        "languages": ["Portuguese", "English", "Spanish"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": [
            "Students who like solving puzzles more than building visual things",
            "Students confused between frontend and backend paths",
            "Students who want to know what a real on-call rotation feels like",
        ],
        "career_ids": [],
        "career_journey": [
            {"stage": "school", "label": "Public high school, São Paulo", "description": "Discovered programming through a free community coding club, not through school itself.", "year_label": "2007-2010"},
            {"stage": "university", "label": "BSc Computer Science", "description": "Nearly failed her second year after a family financial crisis forced her to work full-time while studying.", "year_label": "2011-2015"},
            {"stage": "first_job", "label": "Junior developer at a small agency", "description": "Built WordPress sites for small businesses — unglamorous, but it paid the bills and taught her real client communication.", "year_label": "2015-2016"},
            {"stage": "career_transition", "label": "Joined a startup as backend engineer", "description": "Took a pay cut to join a startup building logistics software, betting on equity that ultimately became worthless.", "year_label": "2016-2018"},
            {"stage": "failure", "label": "The startup shut down with two weeks' notice", "description": "Was unemployed for four months afterward and seriously considered leaving tech altogether.", "year_label": "2018"},
            {"stage": "turning_point", "label": "Joined the fintech company as a mid-level engineer", "description": "Rebuilt a critical retry-logic bug that had been silently costing the company money for over a year — this is what got her promoted.", "year_label": "2019"},
            {"stage": "promotion", "label": "Promoted to Senior Backend Engineer", "description": "Now leads design reviews for the payments team and mentors two junior engineers.", "year_label": "2022"},
            {"stage": "current_role", "label": "Senior Backend Engineer, Payments Infrastructure", "description": "Owns the reliability of a system that processes millions of dollars in transactions daily.", "year_label": "2022-present"},
        ],
        "day_in_the_life": "Mornings start by checking overnight alerts and dashboards before anything else — a payments system can't wait until 10am to be looked at. Most of the day is a mix of code review, writing or debugging retry logic, and at least one meeting where she has to explain a technical tradeoff to non-engineers.",
        "weekly_routine": "Two days are heads-down coding, one day is almost entirely meetings and design reviews, and Fridays are reserved for smaller cleanup work and mentoring her junior engineers.",
        "biggest_challenges": ["Explaining why a fix will take three weeks, not three days, to non-technical stakeholders", "Being the only senior engineer on-call for a system that can't go down"],
        "favourite_part": "The moment a system she rebuilt handles a spike in traffic without anyone noticing — that invisibility is the actual win.",
        "biggest_misconceptions": ["That senior engineers write more code than junior ones — she writes less code and reviews more", "That backend work is less creative than frontend work"],
        "what_surprised_them": "How much of the job is actually about writing clearly, not just writing code — incident reports and design docs matter as much as the implementation.",
        "biggest_mistake": "In her first startup job, she shipped a database migration on a Friday afternoon without a rollback plan. It corrupted customer data over the weekend, and she spent Saturday and Sunday manually restoring records from backups while barely sleeping.",
        "one_regret": "I wish I had asked for help sooner during my first year. I thought asking questions made me look incompetent, so I stayed stuck on problems for days that a five-minute conversation would have solved.",
        "salary_reality": "Entry-level backend roles in Brazil typically pay far less than what you'll see quoted for US tech jobs online — don't benchmark your expectations against San Francisco salaries. It takes about 5-7 years to reach a senior salary that feels genuinely comfortable, and remote roles for international companies have changed that math significantly in the last few years.",
        "work_life_balance": "On-call weeks are genuinely disruptive — I've had 3am pages that ruined a weekend. Outside of on-call weeks, the job is a normal 40-45 hours, and I've gotten much better at actually logging off since my second startup burned me out.",
        "daily_skills": ["Python", "distributed systems design", "SQL", "incident response", "code review"],
        "daily_tools": ["Kubernetes", "PostgreSQL", "Datadog", "Git"],
        "recommended_books": ["Designing Data-Intensive Applications by Martin Kleppmann", "The Phoenix Project by Gene Kim"],
        "recommended_communities": ["Local Python user group in São Paulo", "r/backend (Reddit)"],
        "advice_for_beginners": "Don't wait until you feel ready to apply for a job — I applied to over 60 places before my first offer, and I still don't feel 100% ready most days. Build one small real project you can talk about in depth rather than ten tutorial clones you can't explain.",
        "advice_for_parents": "It's genuinely normal for a first tech job to pay less than you'd expect, and it's normal for the first year or two to include real failure and self-doubt. The career only starts to feel stable after 3-5 years — please don't judge the whole path by year one.",
        "faqs": [
            {"question": "Do I need a computer science degree to become a backend engineer?", "answer": "It helps, especially for interview preparation, but I've worked with excellent self-taught engineers. What matters more is being able to explain how a system you built actually works under load."},
            {"question": "Is backend engineering less creative than other tech roles?", "answer": "Not at all — designing a system that stays reliable under real, messy, unpredictable traffic is a deeply creative problem, it just doesn't look like a website."},
        ],
        "projects": ["Rebuilt the company's payment retry pipeline, cutting failed-transaction losses by 80%", "Open-source contributor to a Python async database library"],
        "research": [],
        "certifications": ["AWS Certified Solutions Architect – Associate"],
        "conferences": ["PyCon Brasil (speaker, 2023)"],
        "organizations": ["PyLadies São Paulo (mentor)"],
        "volunteer_work": ["Teaches a free weekend coding class for unemployed adults"],
        "portfolio_links": [{"label": "GitHub", "url": "https://github.com/example/mariasantos"}],
        "social_links": [{"label": "LinkedIn", "url": "https://linkedin.com/in/example-mariasantos"}],
    },
    {
        "id": "expert_ml_engineer_daniel_okafor",
        "name": "Daniel Okafor, Machine Learning Engineer",
        "role_type": "industry_professional",
        "field": "artificial intelligence",
        "bio": "Builds and deploys machine learning models for a healthcare startup predicting patient readmission risk; came to ML from a physics PhD he chose not to finish.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "learning_style_fit": "Students who want deep mathematical intuition before jumping to frameworks and libraries.",
        "organization": "A healthcare AI startup",
        "years_experience": 6,
        "journey_highlights": ["Left a physics PhD program after his third year", "Shipped a readmission-risk model now used in 12 hospitals"],
        "discussion_topics": ["Transitioning from academia to industry", "Applied ML vs. ML research", "Healthcare AI ethics"],
        "profession": "Machine Learning Engineer",
        "specialization": "Predictive healthcare models",
        "country": "Nigeria",
        "city": "Lagos",
        "industries": ["technology", "healthcare", "artificial intelligence"],
        "education": ["BSc Physics, University of Lagos", "Left PhD program in Theoretical Physics, unfinished"],
        "current_role": "Machine Learning Engineer, Clinical Risk Models",
        "languages": ["English", "Igbo"],
        "accepts_mentorship": True, "max_students": 4,
        "who_should_talk_to_me": [
            "Students who like mathematics and are confused between AI research and applied AI engineering",
            "Students considering leaving a PhD program",
            "Students interested in healthcare technology specifically",
        ],
        "career_ids": ["ai_ops_specialist", "genomics_data_scientist"],
        "career_journey": [
            {"stage": "school", "label": "Government secondary school, Lagos", "description": "Was the top physics student in his class but had no exposure to programming until university.", "year_label": "2005-2011"},
            {"stage": "university", "label": "BSc Physics", "description": "Fell in love with computational physics simulations in his third year, which is what led him toward programming.", "year_label": "2012-2016"},
            {"stage": "first_job", "label": "PhD student, Theoretical Physics", "description": "Started a doctorate studying condensed matter theory, funded by a research assistantship.", "year_label": "2017-2019"},
            {"stage": "failure", "label": "Struggled badly with his PhD research direction", "description": "Spent over a year on a research problem that ultimately produced no publishable results, and watched his motivation collapse.", "year_label": "2019"},
            {"stage": "career_transition", "label": "Left the PhD program without finishing", "description": "Made the decision after months of therapy and conversations with his advisor — one of the hardest calls of his life, made harder by family expectations.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Self-taught machine learning over eight intense months", "description": "Used his physics background in statistics and optimization as a real head start, but still had to learn software engineering from scratch.", "year_label": "2019-2020"},
            {"stage": "promotion", "label": "First ML engineering job, then a move to healthcare AI", "description": "Joined a small startup as its second ML hire and helped grow the modeling team to eight people.", "year_label": "2020-2022"},
            {"stage": "current_role", "label": "Machine Learning Engineer, Clinical Risk Models", "description": "Builds models that flag patients at high risk of hospital readmission, now deployed in a dozen partner hospitals.", "year_label": "2022-present"},
        ],
        "day_in_the_life": "Most mornings start with checking model performance metrics from the previous day's predictions against real patient outcomes. The rest of the day splits between feature engineering, model retraining, and meetings with clinicians who need the model's decisions explained in plain language, not statistics.",
        "weekly_routine": "Roughly half the week is spent on modeling work, and the other half is spent translating between data science and clinical staff — that communication load surprised him more than anything technical did.",
        "biggest_challenges": ["Explaining model uncertainty to doctors who want a clear yes/no answer", "Handling messy, inconsistent real-world hospital data that never looks like a clean dataset"],
        "favourite_part": "Getting an email from a hospital saying the model genuinely helped a nurse catch a high-risk patient early.",
        "biggest_misconceptions": ["That leaving a PhD program is a failure rather than a real, valid decision", "That machine learning engineering is mostly about model architecture, not data quality"],
        "what_surprised_them": "How little of the job resembles the machine learning papers he used to read — most real work is data cleaning and validation, not novel algorithms.",
        "biggest_mistake": "Early on, I deployed a model that performed beautifully on historical data but had quietly learned to use a data leak — a field that was only available after the outcome was already known. It looked impressive in testing and was useless in production. I didn't catch it until a clinician asked a question I couldn't answer.",
        "one_regret": "I regret staying in my PhD program for two years past the point where I knew, privately, that it wasn't right for me. I was afraid of what people would think if I left, and that fear cost me time I can't get back.",
        "salary_reality": "ML engineering salaries in Nigeria's local market are still catching up to the role's real value, which is part of why many strong engineers here work remotely for companies abroad. That gap is closing, but it's real and worth knowing about before you plan your finances around a purely local job.",
        "work_life_balance": "It's genuinely better than my PhD ever was — a bad week in industry is 50 hours, a bad week in my PhD was 70 with no end date in sight. I protect my weekends fiercely now, partly because I burned out badly once already.",
        "daily_skills": ["Python", "statistics", "feature engineering", "model evaluation", "clear technical communication"],
        "daily_tools": ["scikit-learn", "PyTorch", "MLflow", "SQL"],
        "recommended_books": ["The Elements of Statistical Learning by Hastie, Tibshirani, and Friedman", "Weapons of Math Destruction by Cathy O'Neil"],
        "recommended_communities": ["Data Science Nigeria", "Kaggle forums"],
        "advice_for_beginners": "Don't compare your beginning with someone else's fifth year. I spent my first three months feeling like a fraud surrounded by people who seemed to already know everything — most of them were further along, not smarter.",
        "advice_for_parents": "Leaving a PhD program is not the same as giving up — for my son, it was the decision that let him actually build something real. Please ask what your child wants to build, not just what letters they want after their name.",
        "faqs": [
            {"question": "Do I need a PhD to work in machine learning?", "answer": "No — for applied ML engineering roles like mine, a strong portfolio of real projects matters more than a doctorate. PhDs matter more for pure research roles."},
            {"question": "Is it too late to switch into AI/ML from a different field?", "answer": "I switched from physics in my late twenties and I still consider myself early-career by AI standards — the field is young enough that this is genuinely common."},
        ],
        "projects": ["Built a hospital readmission-risk model deployed in 12 partner hospitals", "Published an open-source feature-engineering library for clinical time-series data"],
        "research": ["Co-authored an internal white paper on fairness auditing for clinical risk models"],
        "certifications": [],
        "conferences": ["Deep Learning Indaba (attendee, 2022)"],
        "organizations": ["Data Science Nigeria (volunteer instructor)"],
        "volunteer_work": ["Runs a free monthly ML study group for career switchers in Lagos"],
        "portfolio_links": [{"label": "GitHub", "url": "https://github.com/example/danielokafor"}],
        "social_links": [{"label": "Twitter/X", "url": "https://twitter.com/example_danielokafor"}],
    },
    {
        "id": "expert_frontend_engineer_priya_menon",
        "name": "Priya Menon, Frontend Engineer",
        "role_type": "industry_professional", "field": "software engineering", "bio": "Builds the customer-facing web app for an e-commerce company; self-taught after a marketing degree she never used.",
        "trait_tags": ["creativity", "persistence"], "learning_style_fit": "Visual learners who want to see immediate results from their code.",
        "organization": "A mid-size e-commerce company", "years_experience": 5,
        "journey_highlights": ["Switched careers from marketing at age 26", "Rebuilt the checkout flow, cutting cart abandonment by 15%"],
        "discussion_topics": ["Career switching into tech without a CS degree", "Frontend vs backend", "Building a portfolio from scratch"],
        "profession": "Frontend Engineer", "specialization": "E-commerce web performance", "country": "India", "city": "Bengaluru",
        "industries": ["technology", "e-commerce"], "education": ["BA Marketing, Christ University", "Self-taught web development"],
        "current_role": "Frontend Engineer, Checkout Experience", "languages": ["English", "Hindi", "Malayalam"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students without a CS degree wondering if tech is still possible for them", "Students who like visual/design work but also want to code", "Career switchers over 25"],
        "career_ids": [],
        "career_journey": [
            {"stage": "school", "label": "Convent school, Kochi", "description": "No exposure to programming; was pushed toward commerce subjects.", "year_label": "2004-2011"},
            {"stage": "university", "label": "BA Marketing", "description": "Chose marketing because it seemed practical, not because she wanted it.", "year_label": "2012-2015"},
            {"stage": "first_job", "label": "Marketing coordinator at a retail chain", "description": "Spent three years writing product descriptions and hating almost every day of it.", "year_label": "2015-2018"},
            {"stage": "career_transition", "label": "Taught herself HTML/CSS/JS at night for a year", "description": "Built small freelance websites while still working her marketing job, terrified of the pay cut a switch would mean.", "year_label": "2018-2019"},
            {"stage": "turning_point", "label": "Landed a junior frontend role", "description": "Took a 30% pay cut to join as the most junior person on a five-person engineering team.", "year_label": "2019"},
            {"stage": "current_role", "label": "Frontend Engineer, Checkout Experience", "description": "Now owns the performance and reliability of the page where the company makes its money.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Starts by checking real user session recordings for checkout drop-offs, then spends most of the day writing and reviewing React components with a designer sitting nearby.",
        "weekly_routine": "Heavy collaboration with design on Mondays and Tuesdays, focused coding the rest of the week, with a Friday demo to the whole product team.",
        "biggest_challenges": ["Making a page fast on a cheap Android phone with bad internet, not just on her own laptop", "Being taken seriously early on without a CS degree"],
        "favourite_part": "Watching a real analytics dashboard move after she ships a change — the feedback loop is almost immediate.",
        "biggest_misconceptions": ["That frontend work is 'easier' than backend — performance and accessibility are genuinely hard problems", "That a CS degree is required to be taken seriously"],
        "what_surprised_them": "How much of frontend work is actually about people on slow phones and bad networks, not the fast laptop she was developing on.",
        "biggest_mistake": "In my first month I shipped a redesign that looked great on my laptop and was unusable on the low-end Android phones most of our actual customers used. It took a week of angry support tickets before anyone realized why.",
        "one_regret": "I wish I hadn't waited three extra years in marketing out of fear. The pay cut I was so scared of only lasted about 18 months before I was earning more than I ever did before.",
        "salary_reality": "The pay cut when switching careers is real and can feel scary, but in tech hubs like Bengaluru it's usually temporary — most switchers I know recovered their old salary within two years and then kept climbing.",
        "work_life_balance": "Genuinely good most weeks, around 45 hours, with occasional crunch before a big product launch.",
        "daily_skills": ["JavaScript", "React", "CSS", "web performance", "accessibility"],
        "daily_tools": ["React", "TypeScript", "Figma", "Lighthouse"],
        "recommended_books": ["Refactoring UI by Adam Wathan and Steve Schoger"],
        "recommended_communities": ["Frontend developers India (Discord)"],
        "advice_for_beginners": "Build one real project that solves a problem you actually have — my first serious project was a site to track my own job applications, and it's what got me my first interview.",
        "advice_for_parents": "A marketing or commerce degree is not wasted if your child moves into tech later — the communication skills transfer directly, and the switch is more common than you'd think.",
        "faqs": [{"question": "Can I switch to tech without a CS degree?", "answer": "Yes — I did it at 26 with a marketing degree. It takes real, sustained self-study, but the degree itself was never the blocker."}],
        "projects": ["Rebuilt the checkout flow, reducing cart abandonment by 15%"], "research": [], "certifications": [],
        "conferences": ["React India (attendee, 2023)"], "organizations": ["Women Who Code Bengaluru"],
        "volunteer_work": ["Mentors career switchers through a local coding bootcamp's alumni network"],
        "portfolio_links": [{"label": "Portfolio site", "url": "https://example.com/priyamenon"}], "social_links": [],
    },
    {
        "id": "expert_cybersecurity_engineer_jonas_weber",
        "name": "Jonas Weber, Cybersecurity Engineer",
        "role_type": "industry_professional", "field": "cybersecurity", "bio": "Runs penetration tests and incident response for a European bank; started as a curious teenager who got in trouble for hacking his school's grading system.",
        "trait_tags": ["analytical_thinking", "curiosity"], "learning_style_fit": "Students who like taking things apart to understand how they break.",
        "organization": "A European retail bank", "years_experience": 11,
        "journey_highlights": ["Got suspended in high school for exploiting a grading system bug", "Led incident response for a real ransomware attempt"],
        "discussion_topics": ["Ethical hacking as a career", "What incident response actually feels like", "Certifications vs. real experience"],
        "profession": "Cybersecurity Engineer", "specialization": "Penetration testing and incident response", "country": "Germany", "city": "Frankfurt",
        "industries": ["technology", "finance", "cybersecurity"], "education": ["BSc Computer Science, Goethe University Frankfurt"],
        "current_role": "Senior Cybersecurity Engineer, Incident Response", "languages": ["German", "English"],
        "accepts_mentorship": False, "max_students": 0,
        "who_should_talk_to_me": ["Students who enjoy finding flaws in systems, not just building them", "Students weighing ethical hacking against a legal/policy path in security", "Students who got in trouble for a harmless hack once"],
        "career_ids": [],
        "career_journey": [
            {"stage": "school", "label": "Gymnasium, Frankfurt", "description": "Exploited a bug in the school's grading portal and got suspended for a week — the incident that first showed him security as a career.", "year_label": "2004-2011"},
            {"stage": "university", "label": "BSc Computer Science", "description": "Focused electives on cryptography and network security.", "year_label": "2012-2016"},
            {"stage": "first_job", "label": "Junior security analyst at a consultancy", "description": "Spent two years doing repetitive vulnerability scans before getting real penetration-testing work.", "year_label": "2016-2018"},
            {"stage": "career_transition", "label": "Moved in-house to a bank's security team", "description": "Traded consulting variety for deeper, ongoing ownership of one organization's real risk.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Led incident response during an attempted ransomware attack", "description": "Coordinated a 30-hour response that contained the breach before any customer data was touched.", "year_label": "2021"},
            {"stage": "current_role", "label": "Senior Cybersecurity Engineer, Incident Response", "description": "Leads the team responsible for detecting and responding to real security incidents.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Most days are quiet monitoring and proactive testing; the rare bad days involve dropping everything to contain a real, active incident.",
        "weekly_routine": "Structured vulnerability assessments most weeks, with unscheduled incident response taking priority whenever it happens.",
        "biggest_challenges": ["Convincing business teams to slow down and fix a real vulnerability instead of shipping a feature on time", "The adrenaline crash after a major incident is resolved"],
        "favourite_part": "The specific moment during an incident when the team finally understands exactly what happened — the puzzle-solving under real pressure.",
        "biggest_misconceptions": ["That hacking is mostly about typing fast in a dark room", "That security is only relevant to large companies"],
        "what_surprised_them": "How much of real security work is about people and process, not just technical exploits.",
        "biggest_mistake": "Early in my career, I found a real vulnerability in a client's system during a test and disclosed it in a way that panicked their team unnecessarily, instead of following the proper escalation process. It damaged trust I had to spend months rebuilding.",
        "one_regret": "I regret not learning to write clearly earlier — a great technical finding poorly communicated in a report gets ignored, and I've watched that happen to my own work.",
        "salary_reality": "Security pays well in Germany relative to general software roles once you have 3-4 years of real experience, but the entry-level path is genuinely competitive and often requires unpaid or low-paid learning time first.",
        "work_life_balance": "Mostly stable, except during active incidents, which can mean days of very little sleep — it's rare, but it happens.",
        "daily_skills": ["network security", "penetration testing", "incident response", "risk assessment"],
        "daily_tools": ["Burp Suite", "Wireshark", "Splunk", "Metasploit"],
        "recommended_books": ["The Web Application Hacker's Handbook by Stuttard and Pinto"],
        "recommended_communities": ["Local OWASP chapter, Frankfurt"],
        "advice_for_beginners": "Build a home lab and break your own systems before you ever touch someone else's — that's how I actually learned, not from a classroom.",
        "advice_for_parents": "If your child got in trouble for a harmless hack, that curiosity is often exactly what makes a great security professional — the key is channeling it toward ethical, legal outlets like capture-the-flag competitions.",
        "faqs": [{"question": "Is hacking illegal to learn?", "answer": "Learning on your own systems or legal platforms like CTF competitions is completely legal — it's unauthorized access to systems you don't own that isn't."}],
        "projects": ["Led incident response for a contained ransomware attempt affecting zero customer data"], "research": [],
        "certifications": ["OSCP (Offensive Security Certified Professional)", "CISSP"],
        "conferences": ["DEF CON (attendee)"], "organizations": ["OWASP Frankfurt chapter"],
        "volunteer_work": ["Runs a free capture-the-flag workshop for university students"],
        "portfolio_links": [], "social_links": [{"label": "LinkedIn", "url": "https://linkedin.com/in/example-jonasweber"}],
    },
    {
        "id": "expert_devops_engineer_grace_muthoni",
        "name": "Grace Muthoni, Cloud/DevOps Engineer",
        "role_type": "industry_professional", "field": "cloud infrastructure", "bio": "Manages cloud infrastructure for a logistics company operating across East Africa; started as a network technician setting up office WiFi.",
        "trait_tags": ["analytical_thinking", "systems_thinking"], "learning_style_fit": "Students who like understanding how many pieces connect into one working system.",
        "organization": "A regional logistics company", "years_experience": 8,
        "journey_highlights": ["Started as an office IT technician", "Migrated the company's entire infrastructure to the cloud in 14 months"],
        "discussion_topics": ["IT support to cloud engineering", "What DevOps actually means day to day", "Building infrastructure for unreliable regional internet"],
        "profession": "Cloud/DevOps Engineer", "specialization": "Infrastructure for logistics systems", "country": "Kenya", "city": "Nairobi",
        "industries": ["technology", "logistics"], "education": ["Diploma in Information Technology, Kenya Institute of Management", "AWS certifications, self-funded"],
        "current_role": "Lead Cloud Infrastructure Engineer", "languages": ["English", "Swahili"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who started in IT support and wonder what's next", "Students who like systems and infrastructure more than writing application code", "Students without a CS degree looking at a technical path"],
        "career_ids": [],
        "career_journey": [
            {"stage": "school", "label": "Public secondary school, Nairobi", "description": "No computer access at school; first touched a computer at a cybercafe.", "year_label": "2003-2007"},
            {"stage": "university", "label": "Diploma in Information Technology", "description": "Chose a diploma over a full degree for cost reasons — a decision she initially felt insecure about.", "year_label": "2008-2010"},
            {"stage": "first_job", "label": "Office IT technician", "description": "Set up printers, WiFi, and helpdesk tickets for three years at a small firm.", "year_label": "2010-2013"},
            {"stage": "career_transition", "label": "Moved into a junior sysadmin role", "description": "Taught herself Linux administration on weekends to qualify.", "year_label": "2013-2016"},
            {"stage": "turning_point", "label": "Led the company's migration to AWS", "description": "Volunteered for a project no one else wanted, taught herself cloud infrastructure under real deadline pressure, and delivered it.", "year_label": "2017-2018"},
            {"stage": "promotion", "label": "Promoted to Lead Cloud Infrastructure Engineer", "description": "Now owns the reliability of systems tracking deliveries across five countries.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Mornings review infrastructure alerts and cost dashboards; afternoons are split between automation scripting and supporting application teams who need infrastructure changes.",
        "weekly_routine": "Proactive infrastructure improvement most weeks, with occasional urgent firefighting when regional internet outages cascade into system issues.",
        "biggest_challenges": ["Building systems resilient to genuinely unreliable regional internet infrastructure", "Justifying cloud costs to finance teams who compare them to cheaper, riskier alternatives"],
        "favourite_part": "The satisfaction of an automated deployment pipeline that used to take a stressful full day now taking fifteen minutes.",
        "biggest_misconceptions": ["That a diploma instead of a full degree limits your ceiling in tech — it hasn't for her", "That cloud engineering is just 'IT but fancier'"],
        "what_surprised_them": "How much of the job is really about cost optimization and reliability tradeoffs, not just technical setup.",
        "biggest_mistake": "During the AWS migration, I misconfigured a security group and briefly left a database publicly accessible for about six hours before a routine audit caught it. Nothing was breached, but it terrified me and changed how carefully I review access controls forever.",
        "one_regret": "I regret feeling embarrassed about my diploma for years around colleagues with full degrees — it never actually held me back, and I wasted energy worrying about it.",
        "salary_reality": "Cloud engineering is one of the better-paid technical tracks in Kenya's local market right now, partly because so few people have real production cloud experience yet.",
        "work_life_balance": "Generally solid, with occasional late nights during major migrations or outages tied to regional power/internet instability.",
        "daily_skills": ["AWS", "Linux administration", "infrastructure as code", "automation scripting"],
        "daily_tools": ["Terraform", "AWS", "Ansible", "Grafana"],
        "recommended_books": ["The Phoenix Project by Gene Kim"],
        "recommended_communities": ["AWS User Group Nairobi"],
        "advice_for_beginners": "A diploma plus real hands-on lab work will get you further than people assume — build a home lab with free-tier cloud accounts and break things on purpose.",
        "advice_for_parents": "A technical diploma is a completely legitimate path into a well-paying tech career here — it doesn't need to be a four-year degree to lead somewhere real.",
        "faqs": [{"question": "Is a diploma enough to get into cloud engineering?", "answer": "Yes, especially paired with real certifications and hands-on project experience — I've hired diploma holders over degree holders when their practical skills were stronger."}],
        "projects": ["Led a full company migration to AWS across five countries in 14 months"], "research": [],
        "certifications": ["AWS Certified Solutions Architect – Professional", "AWS Certified DevOps Engineer"],
        "conferences": ["AWS Summit Cape Town (attendee, 2022)"], "organizations": ["AWS User Group Nairobi (organizer)"],
        "volunteer_work": ["Runs free cloud-fundamentals workshops for IT support staff wanting to move up"],
        "portfolio_links": [], "social_links": [{"label": "LinkedIn", "url": "https://linkedin.com/in/example-gracemuthoni"}],
    },
    {
        "id": "expert_data_scientist_hannah_liu",
        "name": "Hannah Liu, Data Scientist",
        "role_type": "industry_professional", "field": "data science", "bio": "Analyzes user behavior data for a streaming media company; came from a statistics background and nearly went into academia instead.",
        "trait_tags": ["analytical_thinking", "curiosity"], "learning_style_fit": "Students who like finding patterns in messy real-world numbers rather than clean textbook datasets.",
        "organization": "A streaming media company", "years_experience": 7, "journey_highlights": ["Turned down a PhD offer to join industry", "Built the recommendation engine's core ranking signal"],
        "discussion_topics": ["Data science vs. statistics academia", "What a real day of data science looks like", "Building recommendation systems"],
        "profession": "Data Scientist", "specialization": "User behavior analytics and recommendations", "country": "Canada", "city": "Toronto",
        "industries": ["technology", "media"], "education": ["MSc Statistics, University of Toronto"],
        "current_role": "Senior Data Scientist, Recommendations", "languages": ["English", "Mandarin"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who like statistics but aren't sure it leads anywhere outside academia", "Students confused between data science and machine learning engineering", "Students who want to work with real, messy data"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "MSc Statistics", "description": "Was on track for a PhD and a research career until a summer internship changed her mind.", "year_label": "2015-2017"},
            {"stage": "internship", "label": "Summer internship at a tech company", "description": "Discovered she liked seeing her analysis actually ship to real users far more than writing papers.", "year_label": "2016"},
            {"stage": "career_transition", "label": "Turned down a fully-funded PhD offer", "description": "Disappointed her academic advisor, who thought she was making a mistake.", "year_label": "2017"},
            {"stage": "first_job", "label": "Junior data scientist at the streaming company", "description": "Spent her first year mostly building dashboards, which felt far less glamorous than she'd hoped.", "year_label": "2017-2019"},
            {"stage": "turning_point", "label": "Built a new ranking signal for the recommendation engine", "description": "Her feature improved click-through rate significantly and became a core part of the production model.", "year_label": "2020"},
            {"stage": "current_role", "label": "Senior Data Scientist, Recommendations", "description": "Leads experimentation strategy for what content gets recommended to millions of users.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Mornings are spent reviewing A/B test results from experiments launched the week before; afternoons mix SQL analysis with meetings where she has to argue for or against a product idea using data.",
        "weekly_routine": "Monday planning, three days of deep analysis work, Friday experiment readouts presented to the product team.",
        "biggest_challenges": ["Explaining statistical significance to product managers who want a simple yes/no", "Watching a well-designed experiment get overridden by a strong opinion anyway"],
        "favourite_part": "The moment an experiment result surprises everyone, including her, and changes what the team decides to build next.",
        "biggest_misconceptions": ["That data science is mostly building fancy models — it's mostly cleaning data and asking the right question", "That a PhD is required for a real data science career"],
        "what_surprised_them": "How political data can be — the same numbers get used to support opposite conclusions depending on who's presenting them.",
        "biggest_mistake": "I once ran an experiment analysis with a subtle selection bias I didn't catch, and it led the team to ship a change that actually hurt engagement for two months before someone re-analyzed it and found my error.",
        "one_regret": "I regret not learning to communicate results more simply earlier — my first year of overly technical presentations lost people I needed to convince.",
        "salary_reality": "Data science salaries in Toronto are strong compared to most careers, but genuinely below equivalent US roles — many peers eventually move to US companies remotely for that reason.",
        "work_life_balance": "Predictable most weeks, with real spikes around major product launches when experiment analysis becomes urgent.",
        "daily_skills": ["statistics", "SQL", "experimentation design", "data visualization"],
        "daily_tools": ["Python", "SQL", "Looker", "Jupyter"],
        "recommended_books": ["Trustworthy Online Controlled Experiments by Kohavi, Tang, and Xu"],
        "recommended_communities": ["Toronto Data Science Meetup"],
        "advice_for_beginners": "Get comfortable with SQL before anything fancy — I use it every single day and barely touch complex machine learning models most weeks.",
        "advice_for_parents": "A statistics degree is a genuinely strong, flexible foundation for a tech career, not just an academic dead end — please don't push a PhD as the only 'real' outcome.",
        "faqs": [{"question": "Is data science just applied statistics?", "answer": "Statistics is the foundation, but real data science also needs programming, business context, and the ability to communicate findings persuasively."}],
        "projects": ["Built a ranking signal now core to the production recommendation engine"], "research": [],
        "certifications": [], "conferences": ["Strata Data Conference (attendee, 2021)"], "organizations": [],
        "volunteer_work": ["Volunteers with a nonprofit teaching statistics to high schoolers"],
        "portfolio_links": [], "social_links": [{"label": "LinkedIn", "url": "https://linkedin.com/in/example-hannahliu"}],
    },
    {
        "id": "expert_robotics_engineer_ahmed_farouk",
        "name": "Ahmed Farouk, Robotics Engineer",
        "role_type": "industry_professional", "field": "robotics", "bio": "Designs warehouse automation robots for a logistics tech company; built his first robot from spare parts as a teenager in Cairo.",
        "trait_tags": ["analytical_thinking", "creativity"], "learning_style_fit": "Hands-on builders who learn by physically constructing and testing, not just simulating.",
        "organization": "A warehouse automation company", "years_experience": 10, "journey_highlights": ["Built his first robot from e-waste parts at 15", "Led design of a robotic arm now used in 40+ warehouses"],
        "discussion_topics": ["Getting into robotics without an elite university", "Mechanical vs. software robotics work", "What warehouse automation actually looks like"],
        "profession": "Robotics Engineer", "specialization": "Warehouse automation and robotic arms", "country": "Egypt", "city": "Cairo",
        "industries": ["robotics", "logistics", "manufacturing"], "education": ["BSc Mechatronics Engineering, Cairo University"],
        "current_role": "Lead Robotics Engineer, Warehouse Systems", "languages": ["Arabic", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like building physical things, not just writing code", "Students interested in mechatronics or robotics without access to a top-tier university", "Students who want to know what robotics work looks like outside of research labs"],
        "career_ids": ["space_systems_engineer"],
        "career_journey": [
            {"stage": "school", "label": "Public technical secondary school, Cairo", "description": "Built a simple robot from discarded electronics parts he found in a local market.", "year_label": "2005-2008"},
            {"stage": "university", "label": "BSc Mechatronics Engineering", "description": "Studied at a public university, not the elite private ones many classmates attended.", "year_label": "2009-2014"},
            {"stage": "first_job", "label": "Junior automation engineer at a manufacturing plant", "description": "Maintained industrial machinery, learning practical mechanical skills textbooks never covered.", "year_label": "2014-2017"},
            {"stage": "career_transition", "label": "Joined a robotics startup", "description": "Took a real financial risk moving to an unproven company with a much smaller salary.", "year_label": "2017-2019"},
            {"stage": "turning_point", "label": "Designed a robotic arm that became the company's flagship product", "description": "The arm is now deployed in more than 40 warehouses internationally.", "year_label": "2020"},
            {"stage": "current_role", "label": "Lead Robotics Engineer, Warehouse Systems", "description": "Leads a team of six mechanical and software engineers.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Mornings in the lab testing physical prototypes, afternoons split between CAD design work and coordinating with the software team on control systems.",
        "weekly_routine": "Physical build and test days early in the week, design and planning later, occasional travel to client warehouses to see robots in real operation.",
        "biggest_challenges": ["Getting a robot that works perfectly in the lab to work reliably in a messy real warehouse", "Convincing clients that upfront automation costs pay off over years"],
        "favourite_part": "Watching a robot he designed actually working on a real warehouse floor, not just in a simulation.",
        "biggest_misconceptions": ["That robotics requires an elite university — his own path proves otherwise", "That robots in warehouses are replacing all human jobs rather than changing what people do"],
        "what_surprised_them": "How much of robotics work is really about durability and edge cases, not the elegant core algorithm.",
        "biggest_mistake": "My first deployed robotic arm design had a bearing that wore out three times faster in real warehouse dust than it did in our clean lab tests — we had to recall and retrofit an entire batch, which was expensive and embarrassing.",
        "one_regret": "I regret not visiting a real warehouse earlier in that first design process — assumptions from a clean lab cost us months later.",
        "salary_reality": "Robotics engineering pays well in Egypt relative to most local engineering roles, though still meaningfully below equivalent roles in Europe or the US.",
        "work_life_balance": "Generally reasonable, though prototype testing crunches before a client demo can mean long days for a stretch.",
        "daily_skills": ["mechanical design", "CAD", "control systems", "prototyping"],
        "daily_tools": ["SolidWorks", "ROS (Robot Operating System)", "Python"],
        "recommended_books": ["Introduction to Robotics by John J. Craig"],
        "recommended_communities": ["Cairo robotics maker community"],
        "advice_for_beginners": "Build something physical with your own hands before you worry about which university you got into — my first hand-built robot mattered more to my career than my degree's ranking.",
        "advice_for_parents": "A public university engineering degree combined with real hands-on building experience can absolutely lead to a strong robotics career — the brand name of the school mattered far less than what he actually built.",
        "faqs": [{"question": "Do I need to go to a top university for robotics?", "answer": "It helps for some research paths, but for applied engineering roles like mine, a strong portfolio of things you've actually built matters more."}],
        "projects": ["Led design of a robotic arm deployed in 40+ warehouses"], "research": [],
        "certifications": [], "conferences": ["MODEX (logistics automation conference, attendee)"], "organizations": [],
        "volunteer_work": ["Runs a free robotics club for technical secondary school students"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_space_systems_yuki_tanaka",
        "name": "Yuki Tanaka, Space Systems Engineer",
        "role_type": "industry_professional", "field": "aerospace", "bio": "Designs small satellite subsystems for a commercial space startup; grew up obsessed with a single toy rocket she never actually got to launch as a kid.",
        "trait_tags": ["analytical_thinking", "curiosity"], "learning_style_fit": "Students who like long-term, detail-obsessed projects where mistakes are expensive and rare.",
        "organization": "A commercial small-satellite company", "years_experience": 8, "journey_highlights": ["Rejected from her first-choice aerospace program", "Led thermal design for a satellite now in orbit"],
        "discussion_topics": ["Getting into space engineering after rejection from a top program", "What working in commercial space is really like", "Small satellites vs. traditional space agencies"],
        "profession": "Space Systems Engineer", "specialization": "Small satellite thermal and power systems", "country": "Japan", "city": "Tokyo",
        "industries": ["aerospace", "space"], "education": ["BEng Aerospace Engineering, Tokyo Institute of Technology"],
        "current_role": "Senior Systems Engineer, Small Satellites", "languages": ["Japanese", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who want space careers but got rejected from a dream program once", "Students interested in commercial space rather than government agencies", "Students who like precision, detail-heavy engineering work"],
        "career_ids": ["space_systems_engineer"],
        "career_journey": [
            {"stage": "school", "label": "Public high school, Tokyo", "description": "Built and lost a small model rocket that never successfully launched — the failure stuck with her.", "year_label": "2005-2008"},
            {"stage": "university", "label": "Rejected from her first-choice aerospace program, then accepted at a second-tier one", "description": "The rejection devastated her at the time, but the program she attended had hands-on satellite-building clubs the more prestigious one lacked.", "year_label": "2009-2013"},
            {"stage": "first_job", "label": "Junior thermal engineer at a traditional aerospace contractor", "description": "Worked on large government satellite programs with multi-year timelines.", "year_label": "2013-2017"},
            {"stage": "career_transition", "label": "Moved to a commercial small-satellite startup", "description": "Traded stability for the chance to see satellites she worked on actually launch within a year, not a decade.", "year_label": "2017"},
            {"stage": "turning_point", "label": "Led thermal design for the company's first successful satellite", "description": "The satellite has now been operating in orbit for three years.", "year_label": "2019"},
            {"stage": "current_role", "label": "Senior Systems Engineer, Small Satellites", "description": "Leads thermal and power subsystem design for the company's satellite constellation.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Mornings reviewing thermal simulation results, afternoons in design reviews where a single overlooked detail could mean satellite failure months later in orbit.",
        "weekly_routine": "Deep simulation and design work most days, with intense review cycles before any major design freeze.",
        "biggest_challenges": ["Designing for a system you can never physically repair once it launches", "The long feedback loop between a design decision and knowing if it actually worked"],
        "favourite_part": "The first telemetry data confirming a satellite she helped design is actually working in orbit.",
        "biggest_misconceptions": ["That space engineering only happens at government agencies", "That you need a top-ranked university to have a real space career"],
        "what_surprised_them": "How much commercial space work moves like a fast startup, not the slow-paced government programs she started in.",
        "biggest_mistake": "On an early project, I approved a thermal model that didn't account for a specific orbital eclipse pattern. We caught the error in a late-stage review, but it cost the team six weeks of urgent redesign work right before a launch deadline.",
        "one_regret": "I regret how much the university rejection shook my confidence for years afterward — the program I actually attended gave me better hands-on experience than the one that rejected me.",
        "salary_reality": "Space engineering salaries in Japan are solid but not spectacular compared to general tech roles — most people in this field are here for the mission, not the paycheck.",
        "work_life_balance": "Intense and unpredictable close to a launch date, calmer during the long design and simulation phases.",
        "daily_skills": ["thermal analysis", "systems engineering", "orbital mechanics basics", "design review"],
        "daily_tools": ["MATLAB/Simulink", "Thermal Desktop", "CAD software"],
        "recommended_books": ["Space Mission Engineering: The New SMAD"],
        "recommended_communities": ["Japan small satellite engineering community"],
        "advice_for_beginners": "A rejection from your dream program doesn't end the path — my actual hands-on satellite experience came from the 'backup' school I was disappointed to attend.",
        "advice_for_parents": "Commercial space is a real, growing, stable-enough career path now, not just a handful of government jobs — please don't discourage this dream as unrealistic.",
        "faqs": [{"question": "Do I need to work for a government space agency?", "answer": "No — commercial space companies now employ far more engineers than government agencies did a decade ago, and often offer faster-paced, hands-on work."}],
        "projects": ["Led thermal design for a small satellite that has operated in orbit for 3+ years"], "research": [],
        "certifications": [], "conferences": ["Small Satellite Conference (attendee, 2022)"], "organizations": [],
        "volunteer_work": ["Mentors university satellite-building clubs"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_climate_engineer_sofia_castillo",
        "name": "Sofia Castillo, Climate Adaptation Engineer",
        "role_type": "industry_professional", "field": "climate engineering", "bio": "Designs flood-resilient infrastructure for coastal cities in Latin America; switched from traditional civil engineering after her hometown flooded twice in three years.",
        "trait_tags": ["analytical_thinking", "values"], "learning_style_fit": "Students motivated by seeing engineering work protect real communities, not just abstract technical problems.",
        "organization": "A climate infrastructure consultancy", "years_experience": 9, "journey_highlights": ["Her hometown flooded twice in three years, changing her career focus", "Designed flood defenses now protecting three coastal towns"],
        "discussion_topics": ["Climate engineering as a career", "Traditional civil engineering vs. climate adaptation work", "Working in disaster-affected communities"],
        "profession": "Climate Adaptation Engineer", "specialization": "Coastal flood resilience infrastructure", "country": "Chile", "city": "Valparaíso",
        "industries": ["engineering & construction", "climate"], "education": ["BEng Civil Engineering, Universidad de Chile", "MSc Climate Change Engineering, Imperial College London"],
        "current_role": "Lead Climate Adaptation Engineer", "languages": ["Spanish", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who care about climate but want an engineering path, not just policy", "Students from communities directly affected by flooding or climate disasters", "Students weighing traditional civil engineering against newer climate-focused specializations"],
        "career_ids": ["civil_engineer", "sustainability_analyst"],
        "career_journey": [
            {"stage": "school", "label": "Public school, a small coastal town near Valparaíso", "description": "Watched her town flood for the first time at age 14, damaging her family's home.", "year_label": "2003-2010"},
            {"stage": "university", "label": "BEng Civil Engineering", "description": "Chose civil engineering with a vague sense that she wanted to prevent what happened to her family from happening again.", "year_label": "2011-2016"},
            {"stage": "first_job", "label": "Junior structural engineer at a traditional firm", "description": "Designed standard commercial buildings, feeling disconnected from the climate motivation that brought her to engineering.", "year_label": "2016-2018"},
            {"stage": "failure", "label": "Her hometown flooded again in 2018", "description": "The second flood, after years of feeling like her career wasn't addressing the real problem, was a turning point.", "year_label": "2018"},
            {"stage": "career_transition", "label": "Pursued a master's degree in climate change engineering abroad", "description": "Took on significant debt and left her stable job to study in London.", "year_label": "2019-2020"},
            {"stage": "current_role", "label": "Lead Climate Adaptation Engineer", "description": "Designs flood defense systems for coastal towns across Chile and Peru.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Mornings analyzing flood-risk models for a client town, afternoons in community meetings explaining engineering tradeoffs to local residents who will live with the results.",
        "weekly_routine": "Technical modeling work most days, with regular travel to affected communities for site visits and public consultations.",
        "biggest_challenges": ["Balancing the best technical solution against what a town can actually afford", "Community distrust after previous infrastructure promises went unfulfilled"],
        "favourite_part": "Visiting a town years after a project and seeing it survive a storm that would have devastated it before.",
        "biggest_misconceptions": ["That climate engineering is only relevant to wealthy countries", "That flood defenses are a purely technical problem, not also a social and economic one"],
        "what_surprised_them": "How much of the job is actually about earning community trust, not just running the right calculations.",
        "biggest_mistake": "On my first independent project, I recommended a flood barrier design that was technically sound but that the town genuinely couldn't afford to maintain long-term. Within a few years it had degraded and needed the exact intervention I was originally trying to prevent.",
        "one_regret": "I regret not spending more time listening to the community before proposing solutions on that first project — the technically 'best' answer isn't always the right one for the people who have to live with it.",
        "salary_reality": "Climate adaptation engineering pays reasonably well in Chile, though the master's degree required real debt that took years to pay off.",
        "work_life_balance": "Fairly demanding, with significant travel to remote coastal communities, though the mission-driven nature makes the hours feel different than her earlier commercial engineering job.",
        "daily_skills": ["hydrology", "structural engineering", "climate risk modeling", "community engagement"],
        "daily_tools": ["HEC-RAS (flood modeling software)", "GIS mapping tools", "AutoCAD"],
        "recommended_books": ["The Water Will Come by Jeff Goodell"],
        "recommended_communities": ["Latin American climate engineers network"],
        "advice_for_beginners": "Talk to people in affected communities before you ever start designing — the best flood defense is one people actually trust and can maintain.",
        "advice_for_parents": "This career combines real engineering rigor with a mission that matters — it's not 'less serious' than traditional structural engineering, it's structural engineering aimed at protecting people from a real, growing threat.",
        "faqs": [{"question": "Is climate engineering a stable career or just a trend?", "answer": "Given how much coastal infrastructure worldwide needs adaptation, this field has decades of real demand ahead, not a passing trend."}],
        "projects": ["Designed flood defense systems now protecting three coastal towns"], "research": [],
        "certifications": [], "conferences": ["Climate Adaptation Summit (attendee, 2022)"], "organizations": [],
        "volunteer_work": ["Provides pro-bono flood-risk assessments for small coastal communities that can't afford consultants"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (tech_and_science batch).")


if __name__ == "__main__":
    asyncio.run(seed())
