"""Connect Batch 1 — Expert Connect seed data, Medicine/Biotechnology/
Psychology domain group. See seed_experts_tech_and_science.py for the
full module-level convention notes (an expert IS a Mentor; Content
Quality Bar applies to every field).

Run via: python -m aureon.scripts.seed_experts_medicine_and_biotech
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_physician_amara_okonkwo",
        "name": "Dr. Amara Okonkwo, Family Physician",
        "role_type": "industry_professional", "field": "medicine", "bio": "Runs a family practice clinic in a mid-sized city; almost dropped out of medical school during her third year after a family emergency.",
        "trait_tags": ["empathy", "persistence"], "learning_style_fit": "Students who want to know what medicine feels like day-to-day, not just what the exams cover.",
        "organization": "A community family practice clinic", "years_experience": 14, "journey_highlights": ["Nearly withdrew from medical school in year three", "Built a clinic serving an underinsured community"],
        "discussion_topics": ["Surviving medical school burnout", "Choosing family medicine over a specialty", "What patients don't tell you until you ask right"],
        "profession": "Family Physician", "specialization": "Community primary care", "country": "Nigeria", "city": "Abuja",
        "industries": ["healthcare"], "education": ["MBBS, University of Ibadan", "Residency in Family Medicine, National Hospital Abuja"],
        "current_role": "Lead Physician, Community Family Practice", "languages": ["English", "Igbo", "Hausa"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who want to know what medical school burnout really feels like", "Students choosing between specialty and general practice", "Students who want to serve underinsured communities"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "school", "label": "Secondary school, Abuja", "description": "Top of her class in sciences, expected by everyone to become a doctor.", "year_label": "2000-2007"},
            {"stage": "university", "label": "MBBS, University of Ibadan", "description": "A family medical emergency in her third year nearly forced her to withdraw entirely.", "year_label": "2008-2014"},
            {"stage": "failure", "label": "Almost withdrew from medical school", "description": "Took a leave of absence to care for her mother during a serious illness, unsure if she'd return.", "year_label": "2011"},
            {"stage": "turning_point", "label": "Returned to complete her degree a year behind her cohort", "description": "Had to rebuild both her academic confidence and her sense of belonging in her new class.", "year_label": "2012"},
            {"stage": "first_job", "label": "Residency in Family Medicine", "description": "Chose family medicine over more prestigious specialties, disappointing some mentors who expected her to specialize.", "year_label": "2015-2018"},
            {"stage": "current_role", "label": "Lead Physician, Community Family Practice", "description": "Runs a clinic focused on patients who often can't afford specialist care.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Sees 20-25 patients a day for issues ranging from routine checkups to complex chronic disease management, with charting squeezed in between visits, not after them.",
        "weekly_routine": "Clinic five days a week, with one afternoon reserved for lab result review and referral coordination.",
        "biggest_challenges": ["Patients who can't afford the specialist referral she knows they need", "Staying current on medical knowledge while working full clinic days"],
        "favourite_part": "Long-term patients she's followed for a decade — the trust that builds over years of care.",
        "biggest_misconceptions": ["That family medicine is a 'lesser' choice than specializing", "That doctors always know the diagnosis right away"],
        "what_surprised_them": "How much of medicine is actually listening carefully, not running tests — the diagnosis is often in what a patient almost didn't say.",
        "biggest_mistake": "Early in my career, I dismissed a patient's vague chest discomfort as anxiety without ordering further tests. She returned two weeks later having had a minor heart attack. She recovered, but that mistake taught me to never let my own assumptions override a proper workup.",
        "one_regret": "I regret feeling ashamed about taking a leave of absence during medical school — it delayed me by a year, but it also made me a more compassionate doctor for patients dealing with their own family crises.",
        "salary_reality": "Family medicine in Nigeria's public and community systems pays considerably less than specialty practice or private clinics abroad — I chose this path for the mission, and it required real financial sacrifice.",
        "work_life_balance": "Demanding — clinic days are long, and being the only doctor for many patients means she's rarely fully 'off.'",
        "daily_skills": ["clinical diagnosis", "patient communication", "chronic disease management"],
        "daily_tools": ["Electronic health records", "Basic diagnostic equipment", "UpToDate clinical reference"],
        "recommended_books": ["Being Mortal by Atul Gawande"],
        "recommended_communities": ["Nigerian Medical Association local chapter"],
        "advice_for_beginners": "A gap or delay in your training isn't the end of your career — my year away from medical school made me a better doctor, not a worse one.",
        "advice_for_parents": "Family medicine is a real, respected, deeply needed specialty, not a fallback for students who 'couldn't' specialize — please don't pressure your child away from it if it's genuinely what they want.",
        "faqs": [{"question": "Is it bad to take time off during medical training?", "answer": "No — life happens, and programs generally accommodate real emergencies. My year away didn't damage my career; it changed how I practice medicine for the better."}],
        "projects": [], "research": [], "certifications": ["Board certification in Family Medicine"],
        "conferences": ["West African College of Physicians annual conference"], "organizations": ["Nigerian Medical Association"],
        "volunteer_work": ["Runs free monthly health screening clinics in underserved neighborhoods"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_biotech_researcher_lucas_ferreira",
        "name": "Lucas Ferreira, Biotechnology Research Scientist",
        "role_type": "researcher", "field": "biotechnology", "bio": "Develops crop-resilience biotechnology at an agricultural science company; grew up on a small farm that struggled with drought every year.",
        "trait_tags": ["analytical_thinking", "curiosity"], "learning_style_fit": "Students who want to see lab science connect directly to a real-world problem they've personally witnessed.",
        "organization": "An agricultural biotechnology company", "years_experience": 7, "journey_highlights": ["Grew up on a drought-affected family farm", "Co-developed a drought-resistant soybean trait now in field trials"],
        "discussion_topics": ["Biotech beyond pharmaceuticals", "Agricultural science as a career", "Research careers outside pure academia"],
        "profession": "Biotechnology Research Scientist", "specialization": "Crop drought resilience", "country": "Brazil", "city": "Ribeirão Preto",
        "industries": ["biotechnology", "agriculture"], "education": ["BSc Agronomy, University of São Paulo", "PhD Plant Molecular Biology, ESALQ/USP"],
        "current_role": "Senior Research Scientist, Crop Resilience", "languages": ["Portuguese", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who want biotech careers outside pharmaceuticals or medicine", "Students from farming families interested in agricultural science", "Students weighing academic research against industry research"],
        "career_ids": ["bioinformatics_scientist"],
        "career_journey": [
            {"stage": "school", "label": "Rural school near a family farm", "description": "Watched his family's soybean crop fail from drought three years running.", "year_label": "2002-2009"},
            {"stage": "university", "label": "BSc Agronomy", "description": "Chose agronomy specifically to understand why his family's crops kept failing.", "year_label": "2010-2014"},
            {"stage": "university", "label": "PhD Plant Molecular Biology", "description": "Shifted from field agronomy into the molecular biology behind drought tolerance.", "year_label": "2015-2019"},
            {"stage": "career_transition", "label": "Joined an agricultural biotech company instead of pursuing academia", "description": "Chose industry for the chance to see research reach real farms faster than academic publication timelines allow.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Co-developed a drought-resistant soybean trait", "description": "The trait is now in multi-year field trials across three countries.", "year_label": "2021"},
            {"stage": "current_role", "label": "Senior Research Scientist, Crop Resilience", "description": "Leads a small team researching drought and heat tolerance traits.", "year_label": "2022-present"},
        ],
        "day_in_the_life": "Mornings in the lab running molecular assays, afternoons reviewing field trial data from test farms, occasional travel to actual trial sites.",
        "weekly_routine": "Lab-heavy early week, data analysis and team meetings later in the week.",
        "biggest_challenges": ["The years-long gap between a lab discovery and a real, field-tested product", "Explaining genetic modification science to skeptical farming communities"],
        "favourite_part": "Visiting a field trial and seeing a crop his research helped create surviving conditions that would have killed his family's old crops.",
        "biggest_misconceptions": ["That biotech only means pharmaceuticals", "That genetically improved crops are inherently unsafe — the actual research and regulatory process is far more rigorous than most people realize"],
        "what_surprised_them": "How long agricultural research timelines really are — a trait can take 8-10 years from lab discovery to a farmer's field.",
        "biggest_mistake": "Early in a field trial, I didn't account for a regional soil variation that skewed our results, leading the team to draw an overly optimistic conclusion that a later, more careful trial had to walk back.",
        "one_regret": "I regret not talking to more farmers directly earlier in my research — their practical, on-the-ground knowledge caught problems no lab experiment would have.",
        "salary_reality": "Industry biotech research pays meaningfully better than academic postdoc positions in Brazil, part of why I chose this path over staying in a university lab.",
        "work_life_balance": "Generally steady, with periodic travel during field trial seasons.",
        "daily_skills": ["molecular biology", "genetics", "field trial design", "data analysis"],
        "daily_tools": ["PCR equipment", "R", "greenhouse and field trial systems"],
        "recommended_books": ["Tomorrow's Table by Pamela Ronald and Raoul Adamchak"],
        "recommended_communities": ["Brazilian Society of Plant Breeding"],
        "advice_for_beginners": "Talk to the people affected by the problem you're researching before you ever step into a lab — my family's own struggling farm shaped every research question I've asked since.",
        "advice_for_parents": "Biotechnology careers exist well beyond medicine — agricultural biotech is a real, growing field solving problems directly relevant to food security.",
        "faqs": [{"question": "Is agricultural biotech a stable career compared to pharma biotech?", "answer": "Yes — global food security pressures mean demand for this kind of research is real and growing, not a niche corner of the field."}],
        "projects": ["Co-developed a drought-resistant soybean trait now in multi-country field trials"], "research": ["Published research on drought-tolerance gene expression in soybean"],
        "certifications": [], "conferences": ["International Plant and Animal Genome Conference"], "organizations": ["Brazilian Society of Plant Breeding"],
        "volunteer_work": ["Runs agricultural science outreach programs for rural schools"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_clinical_psychologist_noor_al_sayed",
        "name": "Dr. Noor Al-Sayed, Clinical Psychologist",
        "role_type": "industry_professional", "field": "psychology", "bio": "Runs a private practice specializing in anxiety and trauma; changed career paths after a personal experience with therapy in her twenties.",
        "trait_tags": ["empathy", "communication"], "learning_style_fit": "Students who care as much about understanding people as understanding data.",
        "organization": "A private psychology practice", "years_experience": 10, "journey_highlights": ["Switched from a finance career at 26 after her own therapy experience", "Built a practice from zero clients to a multi-year waitlist"],
        "discussion_topics": ["Career switching into psychology later", "What therapy training actually involves", "Building a private practice from scratch"],
        "profession": "Clinical Psychologist", "specialization": "Anxiety and trauma therapy", "country": "Jordan", "city": "Amman",
        "industries": ["healthcare", "psychology"], "education": ["BSc Finance, University of Jordan", "MSc and PhD Clinical Psychology, American University of Beirut"],
        "current_role": "Founder and Lead Therapist, Private Practice", "languages": ["Arabic", "English"],
        "accepts_mentorship": True, "max_students": 4,
        "who_should_talk_to_me": ["Students considering a career switch into psychology from something unrelated", "Students who want to know what clinical training actually involves", "Students interested in eventually running their own practice"],
        "career_ids": ["neuroscience_postdoc"],
        "career_journey": [
            {"stage": "school", "label": "Private school, Amman", "description": "Excelled academically but had no exposure to psychology as a career option.", "year_label": "2000-2007"},
            {"stage": "university", "label": "BSc Finance", "description": "Chose finance for practical, family-driven reasons, not genuine interest.", "year_label": "2008-2012"},
            {"stage": "first_job", "label": "Financial analyst at a bank", "description": "Spent three unhappy years in a career she was competent at but didn't care about.", "year_label": "2012-2015"},
            {"stage": "turning_point", "label": "Began her own therapy after a difficult period", "description": "Her own experience in therapy is what first made psychology feel like a real, viable career, not just an interest.", "year_label": "2015"},
            {"stage": "career_transition", "label": "Left finance to pursue graduate study in clinical psychology", "description": "Started an entirely new degree at 26, alongside classmates years younger than her.", "year_label": "2016-2021"},
            {"stage": "current_role", "label": "Founder and Lead Therapist, Private Practice", "description": "Runs a practice with a waitlist, specializing in anxiety and trauma.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Back-to-back client sessions most of the day, with notes written in short gaps between — the emotional labor of the job doesn't pause between sessions the way people expect.",
        "weekly_routine": "Client sessions Monday through Friday, with weekly supervision consultation for her most complex cases.",
        "biggest_challenges": ["Managing her own emotional load after hearing difficult stories all day", "The financial instability of building a practice from nothing in her first two years"],
        "favourite_part": "The specific session, often months into treatment, when a client visibly recognizes their own progress.",
        "biggest_misconceptions": ["That therapists have all their own issues figured out", "That psychology is a 'soft' science compared to medicine"],
        "what_surprised_them": "How much rigorous science underlies effective therapy — it's far more structured and evidence-based than popular portrayals suggest.",
        "biggest_mistake": "In my first year of practice, I took on more trauma cases than I had the supervision support to properly handle, and I burned out badly within about eight months. I had to scale back and get my own additional training before continuing.",
        "one_regret": "I regret waiting until 26 to acknowledge that finance wasn't right for me — I spent three years unhappy out of fear of disappointing my family by switching.",
        "salary_reality": "Building a private practice took nearly two years of inconsistent, sometimes very low income before it became financially stable — anyone considering this path should have a real financial cushion or backup plan for that period.",
        "work_life_balance": "I've had to be deliberate about boundaries — the emotional nature of the work means over-scheduling clients leads directly to burnout, which I learned the hard way.",
        "daily_skills": ["active listening", "clinical assessment", "evidence-based therapy techniques"],
        "daily_tools": ["Standardized clinical assessment tools", "Secure telehealth platform"],
        "recommended_books": ["The Body Keeps the Score by Bessel van der Kolk"],
        "recommended_communities": ["Jordanian Psychological Association"],
        "advice_for_beginners": "It's never too late to switch — I started my psychology training at 26 surrounded by 22-year-olds, and it was still one of the best decisions I've made.",
        "advice_for_parents": "A career switch away from a 'stable' field like finance into psychology isn't reckless — for my own family, it took time, but the outcome has been a genuinely more fulfilled, capable version of their daughter.",
        "faqs": [{"question": "Is it too late to become a psychologist in your late twenties?", "answer": "Not at all — many strong clinicians I know started graduate training in their late twenties or thirties, often with more life experience that made them better therapists."}],
        "projects": [], "research": [], "certifications": ["Licensed Clinical Psychologist, Jordan"],
        "conferences": ["Middle East Psychology Conference"], "organizations": ["Jordanian Psychological Association"],
        "volunteer_work": ["Offers free monthly group therapy sessions for refugees"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_surgeon_kwame_asante",
        "name": "Dr. Kwame Asante, General Surgeon",
        "role_type": "industry_professional", "field": "medicine", "bio": "Performs general and trauma surgery at a regional hospital; failed his surgical board exam once before passing on his second attempt.",
        "trait_tags": ["persistence", "analytical_thinking"], "learning_style_fit": "Students who handle high-pressure, high-stakes environments and want an honest picture of surgical training's real toll.",
        "organization": "A regional referral hospital", "years_experience": 12, "journey_highlights": ["Failed his surgical board exam on the first attempt", "Performed emergency surgery during a mass-casualty road accident"],
        "discussion_topics": ["Surviving a failed board exam", "What surgical residency really demands", "Trauma surgery in a resource-limited hospital"],
        "profession": "General Surgeon", "specialization": "Trauma and emergency surgery", "country": "Ghana", "city": "Kumasi",
        "industries": ["healthcare"], "education": ["MBChB, Kwame Nkrumah University of Science and Technology", "Surgical residency, Komfo Anokye Teaching Hospital"],
        "current_role": "Consultant General Surgeon", "languages": ["English", "Twi"],
        "accepts_mentorship": False, "max_students": 0,
        "who_should_talk_to_me": ["Students who want an honest picture of what failing a major exam feels like", "Students considering surgery specifically", "Students interested in working in resource-limited hospital settings"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "university", "label": "MBChB", "description": "Was drawn to surgery after watching a mentor perform a life-saving operation during a student rotation.", "year_label": "2005-2011"},
            {"stage": "first_job", "label": "Surgical residency", "description": "Six grueling years combining intense study with brutal on-call schedules.", "year_label": "2012-2018"},
            {"stage": "failure", "label": "Failed his surgical board exam on the first attempt", "description": "The failure came after years of preparation and shook his confidence badly — he seriously considered leaving surgery.", "year_label": "2017"},
            {"stage": "turning_point", "label": "Passed the board exam on his second attempt", "description": "Rebuilt his study approach with a mentor's structured guidance rather than his previous solo cramming.", "year_label": "2018"},
            {"stage": "current_role", "label": "Consultant General Surgeon", "description": "Performs trauma and general surgery, including emergency response during mass-casualty events.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Morning ward rounds, scheduled surgeries most days, with unpredictable emergency cases that can extend a shift by many hours with no notice.",
        "weekly_routine": "A structured operating schedule interrupted regularly by trauma emergencies that take priority over everything else.",
        "biggest_challenges": ["Making life-or-death decisions with incomplete information under real time pressure", "The physical toll of extended emergency surgeries with no advance warning"],
        "favourite_part": "A patient walking out of the hospital who arrived in critical condition.",
        "biggest_misconceptions": ["That failing a board exam ends a surgical career", "That surgeons are naturally fearless — most manage real fear every time, they just act despite it"],
        "what_surprised_them": "How much surgery is really about calm decision-making under pressure, not just technical hand skill.",
        "biggest_mistake": "During my failed board exam attempt, I studied the wrong way entirely — memorizing facts instead of practicing real clinical reasoning under exam conditions. It took an honest, humbling conversation with a mentor to understand what I'd been doing wrong.",
        "one_regret": "I regret how much shame I carried after that failed exam instead of talking to colleagues about it — I later learned several respected surgeons I look up to had failed on a first attempt too.",
        "salary_reality": "Surgical training in Ghana takes many years of relatively low residency pay before consultant-level compensation, which is solid but still well below equivalent roles in wealthier countries.",
        "work_life_balance": "Genuinely difficult, especially during residency — unpredictable trauma cases mean real family sacrifices even now as a consultant.",
        "daily_skills": ["surgical technique", "rapid clinical decision-making", "trauma triage"],
        "daily_tools": ["Standard surgical equipment", "Hospital electronic records where available"],
        "recommended_books": ["Complications by Atul Gawande"],
        "recommended_communities": ["Ghana College of Physicians and Surgeons"],
        "advice_for_beginners": "Don't let one failed exam define your whole career — I know consultant surgeons across this country who failed a board exam once, myself included.",
        "advice_for_parents": "A failed exam during training is common and survivable — please support your child through it rather than treating it as proof they chose the wrong path.",
        "faqs": [{"question": "Does failing a board exam end a medical career?", "answer": "No — it's genuinely common, and most training programs allow retakes. What matters is understanding why it happened and adjusting your preparation."}],
        "projects": [], "research": [], "certifications": ["Fellowship, Ghana College of Physicians and Surgeons"],
        "conferences": ["West African College of Surgeons annual meeting"], "organizations": ["Ghana College of Physicians and Surgeons"],
        "volunteer_work": ["Volunteers with a mobile surgical outreach program to rural clinics"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_genetic_counselor_wei_zhang",
        "name": "Wei Zhang, Genetic Counselor",
        "role_type": "industry_professional", "field": "genetics", "bio": "Counsels families on inherited disease risk at a prenatal genetics clinic; drawn to the field after a family member's own genetic diagnosis.",
        "trait_tags": ["empathy", "analytical_thinking"], "learning_style_fit": "Students who want to combine real science with direct, emotionally significant patient conversations.",
        "organization": "A prenatal and reproductive genetics clinic", "years_experience": 6, "journey_highlights": ["A family member's genetic diagnosis shaped her career choice", "Helped over 1,000 families understand complex genetic test results"],
        "discussion_topics": ["Genetic counseling as an underrated career", "Combining biology with counseling skills", "What genetic counselors actually do day to day"],
        "profession": "Genetic Counselor", "specialization": "Prenatal and reproductive genetics", "country": "Singapore", "city": "Singapore",
        "industries": ["healthcare", "genetics"], "education": ["BSc Biology, National University of Singapore", "MSc Genetic Counseling, University of Melbourne"],
        "current_role": "Senior Genetic Counselor", "languages": ["English", "Mandarin"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like biology but want a more people-facing career than lab research", "Students unfamiliar with genetic counseling as a career option at all", "Students with a personal or family connection to genetic conditions"],
        "career_ids": ["genomics_data_scientist"],
        "career_journey": [
            {"stage": "school", "label": "Secondary school, Singapore", "description": "A close family member received a difficult genetic diagnosis during her final year of school.", "year_label": "2005-2010"},
            {"stage": "university", "label": "BSc Biology", "description": "Discovered genetic counseling as a career only in her final year, through a chance guest lecture.", "year_label": "2011-2014"},
            {"stage": "university", "label": "MSc Genetic Counseling", "description": "Moved abroad for a specialized master's program not available locally at the time.", "year_label": "2015-2017"},
            {"stage": "first_job", "label": "Junior genetic counselor", "description": "Struggled initially with the emotional weight of delivering difficult news to expecting families.", "year_label": "2017-2019"},
            {"stage": "current_role", "label": "Senior Genetic Counselor", "description": "Now trains newer counselors on managing the emotional demands of the role.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Back-to-back patient consultations discussing genetic test results, ranging from routine reassurance to very difficult diagnoses, followed by detailed documentation.",
        "weekly_routine": "Patient-facing consultations most days, with a weekly case review meeting with the clinical genetics team.",
        "biggest_challenges": ["Delivering a difficult diagnosis to an expecting family with genuine compassion, every single time", "Explaining complex genetic probability in a way that doesn't overwhelm anxious patients"],
        "favourite_part": "Helping a family move from panic to a clear, actionable understanding of their real options.",
        "biggest_misconceptions": ["That genetic counselors are lab scientists — the role is much more about communication than lab work", "That genetic counseling only concerns rare diseases"],
        "what_surprised_them": "How much of the job is psychological support, not just relaying test results.",
        "biggest_mistake": "In my first year, I once presented a genetic risk percentage without enough context, and the family understood it as far more alarming than the science actually supported. I had to schedule an urgent follow-up to properly recontextualize it, and I learned to always frame numbers with real-world comparisons afterward.",
        "one_regret": "I regret not discovering this career earlier — I found out about genetic counseling almost by accident in my final year of university, after years of assuming a biology degree only led to lab research.",
        "salary_reality": "Genetic counseling pays well in Singapore's healthcare system, though the field remains small enough that job openings are limited compared to more common healthcare roles.",
        "work_life_balance": "Emotionally demanding but generally predictable hours, unlike surgical or emergency medicine.",
        "daily_skills": ["genetics knowledge", "risk communication", "counseling skills"],
        "daily_tools": ["Genetic risk assessment software", "Pedigree charting tools"],
        "recommended_books": ["The Gene by Siddhartha Mukherjee"],
        "recommended_communities": ["Genetic counseling professional networks in Southeast Asia"],
        "advice_for_beginners": "If you like biology but the idea of a pure lab career doesn't excite you, look into genetic counseling before assuming your only path is research.",
        "advice_for_parents": "This is a genuine, licensed healthcare profession combining science and real human connection — not just an 'alternative' to becoming a doctor.",
        "faqs": [{"question": "What's the difference between a genetic counselor and a geneticist?", "answer": "Geneticists often focus on lab research or diagnosis; genetic counselors specialize in communicating results and supporting patients through decisions."}],
        "projects": [], "research": [], "certifications": ["Certified Genetic Counselor"],
        "conferences": ["Asia Pacific Society of Human Genetics conference"], "organizations": [],
        "volunteer_work": ["Speaks at university biology departments about genetic counseling as a career path"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (medicine_and_biotech batch).")


if __name__ == "__main__":
    asyncio.run(seed())
