"""Connect Batch 1 — Expert Connect seed data, eighth wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch8
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_geologist_ana_torres",
        "name": "Ana Torres, Exploration Geologist",
        "role_type": "industry_professional", "field": "geology", "bio": "Leads mineral exploration surveys for a mining company; her first independent site assessment missed a significant geological hazard that halted operations later.",
        "trait_tags": ["analytical_thinking", "curiosity"], "learning_style_fit": "Students who like fieldwork combining earth science with real economic stakes.",
        "organization": "A mining exploration company", "years_experience": 11, "journey_highlights": ["Missed a geological hazard in her first independent site assessment", "Now leads exploration surveys across three countries"],
        "discussion_topics": ["Recovering from a missed field assessment", "Geology careers beyond academia", "Mining industry ethics and environmental responsibility"],
        "profession": "Senior Exploration Geologist", "specialization": "Mineral exploration surveys", "country": "Chile", "city": "Antofagasta",
        "industries": ["mining", "geology"], "education": ["BSc Geology, Universidad de Chile", "MSc Economic Geology, University of Arizona"],
        "current_role": "Senior Exploration Geologist", "languages": ["Spanish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like earth science fieldwork with real economic and environmental stakes", "Students who've made a field assessment error", "Students interested in mining industry careers responsibly"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BSc Geology, then MSc Economic Geology", "description": "Specialized in mineral deposit formation and exploration methods.", "year_label": "2008-2014"},
            {"stage": "first_job", "label": "Junior field geologist", "description": "Assisted senior geologists on exploration surveys before leading her own.", "year_label": "2014-2017"},
            {"stage": "failure", "label": "Missed a subsurface fault hazard during her first independent site assessment", "description": "The hazard was discovered later during construction, causing costly project delays.", "year_label": "2018"},
            {"stage": "turning_point", "label": "Adopted much more rigorous, multi-method survey protocols going forward", "description": "Never relied on a single survey technique alone again.", "year_label": "2019"},
            {"stage": "current_role", "label": "Senior Exploration Geologist", "description": "Now leads exploration surveys across operations in three countries.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Field survey work alternating with lab analysis of rock and soil samples, and technical reporting.",
        "weekly_routine": "Extended field seasons in remote locations, followed by analysis and reporting periods back at the office.",
        "biggest_challenges": ["Balancing economic pressure to move fast against thorough geological assessment", "Genuine environmental and community concerns around mining projects"],
        "favourite_part": "Identifying a genuinely significant mineral deposit that will support real economic development.",
        "biggest_misconceptions": ["That geology is just rock collecting rather than rigorous, economically consequential science", "That a missed hazard in an early assessment ends a geologist's career"],
        "what_surprised_them": "How much economic and community context factors into geological decision-making, beyond pure science.",
        "biggest_mistake": "I relied on a single survey method for my first independent assessment instead of cross-validating with multiple techniques, missing a subsurface fault that a more thorough approach would have caught. It caused real project delays, and I now insist on multi-method verification for every site.",
        "one_regret": "I regret rushing that first assessment to meet an aggressive project timeline instead of insisting on the thoroughness the site actually needed.",
        "salary_reality": "Exploration geology pays very well in Chile's major mining sector, reflecting genuine, high-stakes technical expertise.",
        "work_life_balance": "Field seasons involve extended time away from home in remote locations; office seasons are more balanced.",
        "daily_skills": ["geological surveying", "sample analysis", "hazard assessment"],
        "daily_tools": ["Geological survey equipment", "GIS mapping software"],
        "recommended_books": ["Basin Analysis by Philip Allen and John Allen"],
        "recommended_communities": ["Chilean Geological Society"],
        "advice_for_beginners": "Never rely on a single survey method for a critical assessment — my missed hazard came directly from skipping proper cross-validation.",
        "advice_for_parents": "Geology is a genuine, well-paid technical career with real economic significance, not just an academic or outdoor hobby field.",
        "faqs": [{"question": "Is geology mostly an academic career?", "answer": "No — industry roles in mining, energy, and environmental consulting employ far more geologists than academia, often with significantly higher pay."}],
        "projects": ["Led exploration surveys identifying significant mineral deposits across three countries"], "research": [],
        "certifications": ["Professional Geologist certification"], "conferences": [], "organizations": ["Chilean Geological Society"],
        "volunteer_work": ["Mentors geology students on field survey methodology"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_pr_specialist_zainab_yusuf",
        "name": "Zainab Yusuf, Public Relations Director",
        "role_type": "industry_professional", "field": "public relations", "bio": "Leads crisis communications for a large consumer brand; badly mishandled her first real corporate crisis response early in her career.",
        "trait_tags": ["communication", "analytical_thinking"], "learning_style_fit": "Students who think quickly under public pressure and care about how organizations communicate honestly.",
        "organization": "A consumer products company", "years_experience": 12, "journey_highlights": ["Badly mishandled her first major corporate crisis response", "Later led a crisis response praised as a case study in honest corporate communication"],
        "discussion_topics": ["Recovering from a mishandled crisis response", "PR as strategic communication, not spin", "Building a career in corporate communications"],
        "profession": "Director of Communications", "specialization": "Crisis and corporate communications", "country": "Nigeria", "city": "Lagos",
        "industries": ["marketing", "public relations"], "education": ["BA Mass Communication, University of Lagos"],
        "current_role": "Director of Communications", "languages": ["English", "Yoruba", "Hausa"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who think quickly under real pressure and care about honest communication", "Students who've badly handled a public or professional mistake", "Students interested in corporate communications beyond traditional journalism"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Mass Communication", "description": "Initially planned a journalism career before shifting toward corporate communications.", "year_label": "2007-2011"},
            {"stage": "first_job", "label": "Junior PR associate", "description": "Handled routine media relations and press releases.", "year_label": "2011-2014"},
            {"stage": "failure", "label": "Badly mishandled her first major product-safety crisis response", "description": "Delayed public communication too long, which was widely criticized as evasive and made the situation significantly worse.", "year_label": "2014"},
            {"stage": "turning_point", "label": "Rebuilt her crisis communication approach around speed and radical honesty", "description": "Studied crisis communication case studies extensively to understand what she'd gotten wrong.", "year_label": "2015"},
            {"stage": "current_role", "label": "Director of Communications", "description": "Later led a crisis response praised publicly as a case study in honest, fast corporate communication.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "A mix of media relations, message strategy, and — during active crises — rapid-response coordination across the organization.",
        "weekly_routine": "Steady strategic communications work punctuated by unpredictable, high-intensity crisis periods.",
        "biggest_challenges": ["The genuine pressure of representing an organization's voice during a real crisis", "Balancing legal caution against the public's need for honest, timely information"],
        "favourite_part": "A crisis handled with such transparency that it actually strengthens public trust rather than damaging it.",
        "biggest_misconceptions": ["That PR is about spinning or hiding bad news", "That one badly handled crisis ends a communications career"],
        "what_surprised_them": "How much good crisis communication is about speed and honesty, not clever messaging.",
        "biggest_mistake": "During my first major crisis, I followed overly cautious legal advice to delay public communication for days while we 'gathered more information,' which the public and media read as evasion. I now advocate strongly for fast, honest initial communication even with incomplete information, a lesson that reshaped my entire approach.",
        "one_regret": "I regret not pushing back harder on that delay recommendation — I had a sense it was the wrong call at the time and didn't trust my own judgment enough to advocate for it.",
        "salary_reality": "Senior communications roles pay well in Nigeria's corporate sector, though the climb from junior PR roles took over a decade.",
        "work_life_balance": "Generally reasonable, with real unpredictable intensity whenever a crisis emerges.",
        "daily_skills": ["crisis communication strategy", "media relations", "message development"],
        "daily_tools": ["Media monitoring software", "internal communication platforms"],
        "recommended_books": ["Damage Control by Eric Dezenhall and John Weber"],
        "recommended_communities": ["Nigerian Institute of Public Relations"],
        "advice_for_beginners": "Advocate for fast, honest communication even with incomplete information — the delay that damaged my first crisis response taught me caution can be its own mistake.",
        "advice_for_parents": "A badly handled early professional crisis, especially a public one, is genuinely recoverable and can become the foundation of real expertise, as it did for my career.",
        "faqs": [{"question": "Is PR just about spinning bad news positively?", "answer": "Good PR, especially crisis communication, is actually about honest, fast, clear communication — attempts to 'spin' bad news typically make situations worse, not better."}],
        "projects": ["Led a crisis response cited publicly as a case study in honest corporate communication"], "research": [],
        "certifications": [], "conferences": [], "organizations": ["Nigerian Institute of Public Relations"],
        "volunteer_work": ["Trains nonprofit communications staff on crisis response basics"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_insurance_underwriter_mikkel_sorensen",
        "name": "Mikkel Sørensen, Insurance Underwriter",
        "role_type": "industry_professional", "field": "insurance", "bio": "Underwrites commercial property insurance policies; a significant risk assessment error early in his career led to a large payout on a policy that should have been priced differently.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who like assessing risk and probability with real financial stakes.",
        "organization": "A commercial insurance company", "years_experience": 9, "journey_highlights": ["A risk assessment error led to a significant unexpected payout", "Now leads underwriting for the company's largest commercial accounts"],
        "discussion_topics": ["Learning from a costly risk assessment mistake", "Insurance underwriting as an analytical career", "How insurance actually protects businesses"],
        "profession": "Senior Commercial Underwriter", "specialization": "Commercial property risk assessment", "country": "Denmark", "city": "Copenhagen",
        "industries": ["finance", "insurance"], "education": ["BSc Finance, Copenhagen Business School"],
        "current_role": "Senior Commercial Underwriter", "languages": ["Danish", "English", "German"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like risk and probability applied to real financial decisions", "Students who've made a costly analytical error early in a career", "Students unfamiliar with insurance as a genuine analytical career, not just sales"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BSc Finance", "description": "Discovered underwriting through a campus recruiting event, having never considered insurance as a career before.", "year_label": "2010-2013"},
            {"stage": "first_job", "label": "Junior underwriter", "description": "Assessed smaller commercial policies under senior review.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Underpriced a significant commercial property policy that later resulted in a large claim payout", "description": "Missed a real fire-risk factor in the property's construction that should have raised the premium significantly.", "year_label": "2017"},
            {"stage": "turning_point", "label": "Adopted a much more thorough, standardized risk assessment checklist", "description": "Never skipped a full site risk review again, regardless of time pressure.", "year_label": "2018"},
            {"stage": "current_role", "label": "Senior Commercial Underwriter", "description": "Now leads underwriting for the company's largest, most complex commercial accounts.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Reviewing policy applications, assessing risk factors, and pricing coverage based on detailed analysis.",
        "weekly_routine": "Steady analytical work throughout the week, with periodic site visits for larger, more complex policies.",
        "biggest_challenges": ["Accurately pricing genuinely novel or complex risks", "Balancing competitive pricing pressure against sound risk assessment"],
        "favourite_part": "A well-priced policy that genuinely protects a business without either overcharging or underpricing the real risk.",
        "biggest_misconceptions": ["That underwriting is just following a formula", "That insurance is only a sales career, not an analytical one"],
        "what_surprised_them": "How much genuine judgment underwriting requires beyond standard formulas, especially for complex properties.",
        "biggest_mistake": "I underpriced a commercial property policy by missing a specific structural fire-risk factor during my assessment, moving too quickly through what should have been a more thorough site review. The resulting claim cost the company far more than the premium difference I was trying to competitively offer.",
        "one_regret": "I regret rushing that risk assessment to win the business competitively instead of insisting on the full review process, regardless of how it affected pricing competitiveness.",
        "salary_reality": "Underwriting pays solidly in Denmark's insurance sector, with senior roles handling complex accounts commanding real premium compensation.",
        "work_life_balance": "Generally predictable, steady analytical work without major crisis-driven demands.",
        "daily_skills": ["risk assessment", "financial analysis", "policy pricing"],
        "daily_tools": ["Underwriting risk assessment software", "actuarial data tools"],
        "recommended_books": ["Against the Gods: The Remarkable Story of Risk by Peter Bernstein"],
        "recommended_communities": ["Danish Insurance Association"],
        "advice_for_beginners": "Never skip a full risk assessment to move faster or win business competitively — my costly underpricing error came from exactly that shortcut.",
        "advice_for_parents": "Insurance underwriting is a genuine analytical career requiring real financial and risk expertise, not just a sales role.",
        "faqs": [{"question": "Is underwriting a sales job?", "answer": "No — underwriters assess and price risk analytically; sales and relationship roles are typically separate functions within insurance companies."}],
        "projects": [], "research": [], "certifications": ["Chartered Insurance Professional"],
        "conferences": [], "organizations": ["Danish Insurance Association"],
        "volunteer_work": ["Mentors finance students interested in insurance careers"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_event_planner_camille_dubois",
        "name": "Camille Dubois, Event Planner",
        "role_type": "founder", "field": "event management", "bio": "Runs an event planning company specializing in large corporate conferences; her first major independent event had a catastrophic venue double-booking.",
        "trait_tags": ["leadership", "communication"], "learning_style_fit": "Students who thrive coordinating many moving logistical pieces under real time pressure.",
        "organization": "An independent event planning company", "years_experience": 10, "journey_highlights": ["Her first major independent event faced a catastrophic venue double-booking", "Now plans conferences for over 1,000 attendees"],
        "discussion_topics": ["Handling a logistical disaster in real time", "Event planning as a genuine business, not just party planning", "Building a client base from scratch"],
        "profession": "Corporate Event Planner", "specialization": "Large-scale corporate conferences", "country": "Belgium", "city": "Brussels",
        "industries": ["hospitality", "event management"], "education": ["BA Hospitality Management, Vatel Brussels"],
        "current_role": "Founder, Event Planning Company", "languages": ["French", "Dutch", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like coordinating complex logistics under pressure", "Students who've faced a real disaster during an important project", "Students interested in event planning as a serious business, not a hobby"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Hospitality Management", "description": "Interned with a hotel events team throughout her studies.", "year_label": "2010-2013"},
            {"stage": "first_job", "label": "Junior event coordinator at a hotel", "description": "Learned event logistics on smaller-scale events.", "year_label": "2013-2016"},
            {"stage": "career_transition", "label": "Started her own independent event planning company", "description": "Took on real financial risk leaving stable employment.", "year_label": "2017"},
            {"stage": "failure", "label": "Her first major independent conference faced a catastrophic venue double-booking discovered days before the event", "description": "Had to scramble to secure an alternate venue with almost no notice, nearly losing the client entirely.", "year_label": "2017"},
            {"stage": "turning_point", "label": "Rebuilt her contract and confirmation process to include multiple independent verification steps", "description": "The relocated event actually went well enough to earn her a strong client referral.", "year_label": "2018"},
            {"stage": "current_role", "label": "Founder, Event Planning Company", "description": "Now plans corporate conferences for over 1,000 attendees.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of client meetings, vendor coordination, and detailed logistical planning, with intense on-site management during actual events.",
        "weekly_routine": "Planning-heavy weeks build toward intensely demanding event days themselves.",
        "biggest_challenges": ["The real risk of things going wrong despite careful planning", "Managing client expectations under real budget and logistical constraints"],
        "favourite_part": "The moment a complex event actually comes together seamlessly for attendees who never see the behind-the-scenes chaos.",
        "biggest_misconceptions": ["That event planning is just picking decorations", "That a major logistical disaster means you're not organized enough for the job"],
        "what_surprised_them": "How much crisis management, not just planning, the job genuinely requires.",
        "biggest_mistake": "I trusted a single email confirmation from the venue without an independent follow-up verification closer to the event date, which is how the double-booking went unnoticed until days before. I now require multiple confirmation checkpoints for every major event booking, no matter how confident I feel.",
        "one_regret": "I regret how close that early disaster came to ending my new company before it really started — a bit more redundancy in my process from day one would have prevented it.",
        "salary_reality": "Corporate event planning can be very profitable once established, though the first year of an independent business involved genuinely unpredictable, often thin income.",
        "work_life_balance": "Demanding around event dates, with real intensity in the days immediately before and during major events.",
        "daily_skills": ["logistics coordination", "vendor management", "client relations"],
        "daily_tools": ["Event management software", "project timeline tools"],
        "recommended_books": ["Special Events by Joe Goldblatt"],
        "recommended_communities": ["Belgian event planners association"],
        "advice_for_beginners": "Never trust a single confirmation for a critical booking — build in independent verification checkpoints, especially close to the event date.",
        "advice_for_parents": "A logistical disaster during an early independent project is a real, survivable business risk, not proof your child lacks the organizational skill for this career.",
        "faqs": [{"question": "Is event planning a legitimate full-time business?", "answer": "Yes — corporate event planning especially can become a genuinely profitable business, though it requires real logistics and business skill beyond creative taste."}],
        "projects": ["Plans corporate conferences for over 1,000 attendees"], "research": [], "certifications": ["Certified Meeting Professional"],
        "conferences": [], "organizations": ["Belgian event planners association"],
        "volunteer_work": ["Mentors new event planners on contract and vendor verification processes"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_nonprofit_fundraiser_grace_owusu",
        "name": "Grace Owusu, Nonprofit Development Director",
        "role_type": "industry_professional", "field": "nonprofit fundraising", "bio": "Leads fundraising for a children's education nonprofit; a major grant application she led was rejected after months of work.",
        "trait_tags": ["persistence", "communication"], "learning_style_fit": "Students who care about mission-driven work and want to know how nonprofits actually get funded.",
        "organization": "A children's education nonprofit", "years_experience": 10, "journey_highlights": ["A major grant application she led was rejected after months of preparation", "Later secured the organization's largest grant in its history"],
        "discussion_topics": ["Handling grant rejection after months of work", "Nonprofit fundraising as a real, skilled career", "How nonprofits are actually funded"],
        "profession": "Development Director", "specialization": "Grant writing and major donor relations", "country": "Ghana", "city": "Kumasi",
        "industries": ["non_profit", "education"], "education": ["BA English, Kwame Nkrumah University of Science and Technology"],
        "current_role": "Development Director", "languages": ["English", "Twi"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who care about mission-driven work but want a real, skilled career, not just goodwill", "Students who've faced rejection after months of dedicated work", "Students interested in how nonprofits are actually funded"],
        "career_ids": ["ngo_program_manager"],
        "career_journey": [
            {"stage": "university", "label": "BA English", "description": "Developed strong writing skills without a clear career direction in mind.", "year_label": "2008-2012"},
            {"stage": "first_job", "label": "Communications assistant at a nonprofit", "description": "Discovered grant writing through covering for a colleague on leave.", "year_label": "2012-2015"},
            {"stage": "failure", "label": "Led a major foundation grant application that was rejected after five months of preparation", "description": "The rejection came after the team had already begun planning programs around the anticipated funding, creating real organizational strain.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Rebuilt her grant strategy around diversified funding rather than single large bets", "description": "Never again let the organization's plans depend entirely on one uncertain grant outcome.", "year_label": "2017"},
            {"stage": "current_role", "label": "Development Director", "description": "Later secured the organization's largest grant in its history.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of grant writing, donor relationship meetings, and coordinating with program staff on funding needs.",
        "weekly_routine": "Grant application cycles dictate much of the schedule, with donor cultivation work happening continuously.",
        "biggest_challenges": ["The real financial precarity of relying on uncertain grant funding", "The emotional toll of months of work ending in rejection"],
        "favourite_part": "Securing funding that directly translates into real programs reaching more children.",
        "biggest_misconceptions": ["That nonprofit fundraising is just asking nicely for money", "That grant rejection reflects poorly on the cause's worthiness"],
        "what_surprised_them": "How much strategic, competitive skill real fundraising requires, similar to sales in a for-profit context.",
        "biggest_mistake": "I let the organization begin planning specific programs around a major grant before the funding was actually confirmed, assuming our strong application would surely succeed. When it was rejected, we faced real organizational strain scrambling to adjust plans. I now insist on funding confirmation before any program commitment.",
        "one_regret": "I regret the false confidence I projected to program staff before that grant was confirmed — it created expectations that were painful to walk back after the rejection.",
        "salary_reality": "Nonprofit fundraising salaries in Ghana are modest, though senior development roles at larger organizations can be genuinely competitive with corporate roles.",
        "work_life_balance": "Generally steady, with periodic intensity around grant deadlines.",
        "daily_skills": ["grant writing", "donor relationship management", "strategic communication"],
        "daily_tools": ["Grant management software", "donor database systems"],
        "recommended_books": ["Asking by Jerold Panas"],
        "recommended_communities": ["Ghana fundraising professionals network"],
        "advice_for_beginners": "Never commit program plans to unconfirmed funding — my organization's strain after a major grant rejection came from exactly that assumption.",
        "advice_for_parents": "Nonprofit fundraising is a genuine, skilled career requiring real strategic and communication expertise, not just charitable goodwill.",
        "faqs": [{"question": "Is grant rejection common in nonprofit fundraising?", "answer": "Very common — most experienced fundraisers face far more rejections than successes, and resilience is a core, expected part of the job."}],
        "projects": ["Secured the organization's largest grant in its history"], "research": [], "certifications": [],
        "conferences": [], "organizations": ["Ghana fundraising professionals network"],
        "volunteer_work": ["Trains smaller nonprofits on grant writing fundamentals"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch8).")


if __name__ == "__main__":
    asyncio.run(seed())
