"""Connect Batch 1 — Parent Connect seed data: `ParentCareerGuide` rows
for all 27 existing careers. Written at the Content Quality Bar's
narrative depth (see the approved plan's biotechnology example) —
specific, honest, addressing real parent concerns directly, never a
one-line summary. Distinct content from `Career.reality`/
`Career.common_misconceptions` (same subject, parent-framed audience).

Run via: python -m aureon.scripts.seed_parent_connect
"""

import asyncio

from aureon.domain.models.parent_connect import ParentCareerGuide
from aureon.services.supabase.client import get_supabase_client

GUIDES: list[dict] = [
    {
        "id": "guide_physician_general",
        "career_id": "physician_general",
        "common_misconceptions": [
            "That becoming a doctor guarantees instant wealth — most physicians spend a decade in training and debt before reaching a comfortable income",
            "That every doctor works in a hospital — most general physicians work in clinics, seeing 20+ patients a day",
            "That the hardest part is the science — most working doctors say the hardest part is the emotional weight of patient care",
        ],
        "earning_reality": "Parents often assume medicine guarantees immediate financial security, but the reality is a long runway: 4-6 years of medical school plus 3+ years of residency at modest pay, often with real student debt, before reaching a stable income. Once established, general practice physicians earn a solid, dependable income — not the highest in medicine, but consistently secure — and that security tends to improve steadily over a 10-15 year career, not overnight.",
        "career_stability": "Medicine remains one of the most stable career paths that exists — demand for primary care physicians is strong and growing almost everywhere, including regions with physician shortages, meaning job security is rarely a real concern once qualified.",
        "work_life_balance": "The training years (medical school and residency) are genuinely demanding, often 60-80 hour weeks. Once established in general practice specifically (as opposed to surgery or emergency medicine), the hours become far more manageable and predictable.",
        "growth_opportunities": "Clinic ownership or partnership. Specialization into a higher-paid field after further training. Medical leadership/administration roles. Teaching and mentoring the next generation of doctors.",
        "alternative_routes": ["Physician assistant or nurse practitioner (shorter training, real clinical responsibility)", "Health informatics or public health if the clinical demands feel like too much"],
        "global_demand": "Physician shortages exist in most countries, including wealthy ones — this is one of the most globally portable careers, with real opportunities to work internationally if desired.",
        "risks": ["High upfront educational debt", "Real burnout risk without deliberate boundaries", "Malpractice liability concerns in some countries"],
        "opportunities": ["Rare job insecurity risk", "Deep, lasting community respect and trust", "Direct, tangible impact on real people's lives"],
    },
    {
        "id": "guide_civil_engineer",
        "career_id": "civil_engineer",
        "common_misconceptions": [
            "That civil engineers only work on roads and bridges — the field spans buildings, water systems, disaster-resilient infrastructure, and more",
            "That it's a desk job — many civil engineering roles involve regular site visits and real physical inspection work",
        ],
        "earning_reality": "Parents often worry civil engineering is a 'construction worker' career with limited earning potential. In reality, licensed civil engineers earn solid, professional-level salaries that climb meaningfully with experience and licensure, and senior engineers who move into project management or their own consultancy can earn considerably more. Entry-level pay is modest relative to the degree's difficulty, but it's a genuinely stable professional trajectory, not a dead end.",
        "career_stability": "Infrastructure needs — housing, transportation, water systems, climate adaptation — are permanent and growing, making civil engineering one of the more recession-resistant engineering fields; government infrastructure spending in particular tends to provide steady demand even in economic downturns.",
        "work_life_balance": "Generally reasonable, standard working hours, with periodic intensity during active construction phases or approaching deadlines — nothing like the extreme hours sometimes associated with finance or law.",
        "growth_opportunities": "Professional licensure unlocking higher-responsibility roles. Specialization in structural, environmental, or transportation engineering. Project management and eventually firm ownership. Growing demand specifically in climate-resilient infrastructure design.",
        "alternative_routes": ["Civil engineering technologist/technician (shorter training path)", "Construction project management without a full engineering license"],
        "global_demand": "Civil engineers are needed everywhere infrastructure exists or needs to be built, making this one of the most globally transferable engineering careers, especially valuable in rapidly urbanizing regions.",
        "risks": ["Licensing exams add years before full professional responsibility", "Project-based work can mean some income variability for consultants specifically"],
        "opportunities": ["Visible, tangible legacy — literally built structures that last decades", "Strong demand in climate adaptation and resilient infrastructure specifically"],
    },
    {
        "id": "guide_accountant",
        "career_id": "accountant",
        "common_misconceptions": [
            "That accounting is just data entry — modern accountants do strategic financial analysis and advisory work",
            "That it's a 'boring' career with no advancement — accounting is a proven path to CFO and even CEO roles",
        ],
        "earning_reality": "Parents often see accounting as a modest, unglamorous salary path. Entry-level pay is indeed moderate, but professional certification (like a CPA or equivalent) meaningfully raises earning potential, and accountants who move into corporate finance, controllership, or their own practice can earn considerably more over a 10-15 year career. It's a reliable, compounding income trajectory rather than a flashy one.",
        "career_stability": "Every organization, in every economic climate, needs accounting — this is one of the most recession-resistant career paths that exists, since financial record-keeping and compliance obligations don't disappear during downturns.",
        "work_life_balance": "Mostly steady, predictable hours, with real, intense crunches during month-end close, quarter-end, and especially tax season — a genuine, known seasonal pattern, not a constant grind.",
        "growth_opportunities": "Professional certification (CPA/CA/ACCA) unlocking senior roles. Controller and CFO career tracks. Specialization in forensic accounting, tax strategy, or ESG reporting. Starting an independent practice.",
        "alternative_routes": ["Bookkeeping as a lower-barrier entry point", "Financial analyst roles without full accounting certification"],
        "global_demand": "Accounting principles and demand for financial expertise are globally consistent, making certified accountants highly portable across countries and industries.",
        "risks": ["Certification exams have real, sometimes multi-attempt pass rates", "Entry-level roles can be repetitive before reaching more strategic work"],
        "opportunities": ["One of the clearest, most well-documented paths to executive leadership (CFO/CEO)", "Growing demand in newer specializations like sustainability/ESG reporting"],
    },
    {
        "id": "guide_teacher_k12",
        "career_id": "teacher_k12",
        "common_misconceptions": [
            "That teaching is a 'fallback' career for people who couldn't do anything else — it requires real, specialized skill in communication and classroom management",
            "That teachers only work during school hours — planning and grading regularly extend into evenings and weekends",
        ],
        "earning_reality": "Parents are often right to flag that teaching salaries are modest relative to the training required — this is a real, honest tradeoff in most countries, not a myth. However, teaching offers genuine stability, meaningful benefits in many public systems, and real paths to higher pay through school leadership, specialized subjects, or moving into curriculum design and educational leadership roles.",
        "career_stability": "Teaching is one of the most stable career paths available — schools will always need teachers, and public education systems in particular offer strong job security, often including pension benefits many other careers no longer provide.",
        "work_life_balance": "The school-day schedule looks appealing on paper, but real planning, grading, and parent communication regularly extend well beyond it — especially for new teachers still building their lesson library and classroom management skills.",
        "growth_opportunities": "Department head or instructional coach roles. School administration (principal/vice-principal) track. Curriculum development and educational consulting. Specialization in special education or gifted education, often with pay premiums.",
        "alternative_routes": ["Tutoring or educational content creation without full classroom teaching", "EdTech roles applying teaching experience to educational products"],
        "global_demand": "Teacher shortages exist in many subjects and regions, particularly in STEM subjects and underserved areas, meaning genuine job security and sometimes recruitment incentives.",
        "risks": ["Genuinely difficult, sometimes overwhelming first year", "Modest pay relative to the emotional and preparation demands"],
        "opportunities": ["Real, lasting influence on young people's lives", "Strong job security and often meaningful public-sector benefits"],
    },
    {
        "id": "guide_ai_ops_specialist",
        "career_id": "ai_ops_specialist",
        "common_misconceptions": [
            "That this is the same job as a data scientist — AI Ops focuses on deploying and maintaining AI systems, not building models from scratch",
            "That it requires a PhD — most AI Ops specialists come from software engineering or DevOps backgrounds",
        ],
        "earning_reality": "Parents unfamiliar with this newer field often assume it's speculative or unstable. In reality, AI Operations Specialists are in genuinely high demand right now as companies rush to deploy AI systems reliably, and salaries reflect that scarcity — often comparable to or higher than traditional software engineering roles at the same seniority level, even for relatively early-career professionals.",
        "career_stability": "This is a genuinely new and fast-growing field, which carries both opportunity and some real uncertainty about how job titles and required skills will evolve — but the underlying need (reliably running AI systems in production) is not going away.",
        "work_life_balance": "Generally similar to other software engineering roles — standard hours, with on-call responsibilities when AI systems in production need urgent attention, similar to any infrastructure-critical tech role.",
        "growth_opportunities": "Senior/staff engineering tracks. Moving into AI infrastructure leadership as companies scale their AI operations. Specializing in a specific domain (healthcare AI, financial AI) for premium roles.",
        "alternative_routes": ["Traditional DevOps/Site Reliability Engineering, adding AI-specific skills over time", "Cloud infrastructure roles with an AI specialization added later"],
        "global_demand": "Extremely high and growing globally as every industry adopts AI — this is one of the most in-demand emerging tech specializations worldwide right now.",
        "risks": ["Field is new enough that job titles and expectations are still standardizing", "Requires continuous learning as tools and best practices evolve quickly"],
        "opportunities": ["Ground-floor opportunity in a genuinely high-growth field", "Strong, currently scarcity-driven compensation"],
    },
    {
        "id": "guide_genomics_data_scientist",
        "career_id": "genomics_data_scientist",
        "common_misconceptions": [
            "That this career only works in medicine — genomics data scientists also work in agriculture, forensics, and biotechnology broadly",
            "That you need a medical degree — most genomics data scientists come from computer science, statistics, or biology backgrounds",
        ],
        "earning_reality": "Parents often worry biotechnology-adjacent careers only pay well in a narrow academic research track. In reality, genomics data scientists working in industry (pharmaceutical companies, biotech startups, diagnostics companies) earn strong salaries comparable to general data science roles, often with premium pay for the specialized genomics domain knowledge. Academic research roles pay considerably less, so the industry-vs-academia choice matters enormously for earning potential.",
        "career_stability": "Falling genomic sequencing costs are driving major, sustained growth in this field — genuinely strong, growing demand, not a niche or fading specialization.",
        "work_life_balance": "Generally similar to other data science roles — steady, standard hours in industry settings, though academic research positions can involve less predictable hours around grant and publication deadlines.",
        "growth_opportunities": "Senior data scientist and eventually research leadership roles. Specializing in precision medicine, a rapidly growing subfield. Moving between academia and industry as the field matures.",
        "alternative_routes": ["General bioinformatics roles without deep genomics specialization", "Data science roles in other domains, transferring skills later"],
        "global_demand": "Strong and growing globally, particularly in countries investing heavily in precision medicine and genomic research infrastructure.",
        "risks": ["Academic research funding can be less predictable than industry roles", "Requires continuous learning across both biology and rapidly evolving computational methods"],
        "opportunities": ["Work directly connected to real medical breakthroughs", "Strong crossover value with the broader, in-demand data science field"],
    },
    {
        "id": "guide_sustainability_analyst",
        "career_id": "sustainability_analyst",
        "common_misconceptions": [
            "That sustainability roles are 'nice to have' rather than essential business functions — regulatory requirements are making this role mandatory at many companies",
            "That it's purely an environmental science career — much of the work is business analysis and regulatory compliance",
        ],
        "earning_reality": "Parents often worry sustainability careers are passion projects with limited pay. In reality, corporate sustainability analyst salaries have risen significantly as environmental regulations tighten and investors demand ESG reporting — pay is now broadly comparable to other corporate analyst roles, with senior sustainability leadership (Chief Sustainability Officer) commanding executive-level compensation at larger companies.",
        "career_stability": "Growing regulatory requirements around emissions reporting and ESG disclosure are making this role increasingly mandatory rather than optional at mid-size and large companies, which is driving genuinely strong, sustained hiring demand.",
        "work_life_balance": "Generally standard corporate hours, with periodic intensity around annual sustainability report deadlines, similar to financial reporting cycles.",
        "growth_opportunities": "Senior sustainability manager and eventually Chief Sustainability Officer track. Specializing in a specific area like carbon accounting or supply chain sustainability. Moving into sustainability consulting.",
        "alternative_routes": ["Environmental compliance roles with narrower scope", "ESG-focused finance/investment roles"],
        "global_demand": "Strong and growing worldwide as regulatory requirements (particularly in the EU, but increasingly elsewhere) mandate corporate sustainability reporting.",
        "risks": ["Field is evolving quickly alongside changing regulations, requiring continuous learning", "Some smaller companies still treat the role as lower-priority than core business functions"],
        "opportunities": ["Genuinely mission-aligned work with growing regulatory backing", "Increasing path to executive leadership roles"],
    },
    {
        "id": "guide_space_systems_engineer",
        "career_id": "space_systems_engineer",
        "common_misconceptions": [
            "That space careers only exist at government agencies like NASA or ISRO — commercial space companies now employ far more engineers",
            "That you need to be an astronaut-caliber genius — most space systems engineering is rigorous but standard engineering work applied to a challenging domain",
        ],
        "earning_reality": "Parents often assume aerospace careers are either extremely lucrative or a financial dead end with no middle ground. In reality, space systems engineers earn solid, professional engineering salaries — good but not the highest in tech — with the real appeal being genuinely exciting mission-driven work rather than exceptional pay. Commercial space companies have somewhat improved compensation relative to the traditional government-contractor pay scale.",
        "career_stability": "The commercial space industry has grown dramatically over the past decade with falling launch costs, creating genuinely more job opportunities and stability than existed even ten years ago, though the field is still smaller than mainstream software or general engineering.",
        "work_life_balance": "Can be demanding, especially approaching a launch date, when schedule pressure is real and significant — calmer during the long design and simulation phases that make up most of a project's timeline.",
        "growth_opportunities": "Senior/lead systems engineer roles. Specializing in a subsystem (propulsion, power, communications) for deep expertise. Moving between traditional aerospace and newer commercial space companies.",
        "alternative_routes": ["General aerospace or mechanical engineering with a space specialization added later", "Satellite operations roles with less design-focused responsibility"],
        "global_demand": "Growing steadily worldwide as more countries and private companies enter the commercial space sector — genuinely more accessible globally than a decade ago.",
        "risks": ["Smaller field than mainstream engineering, meaning somewhat fewer total job openings", "High stakes of designing for systems that can't be physically repaired once launched"],
        "opportunities": ["Genuinely exciting, mission-driven engineering work", "Growing field with real recent expansion beyond traditional government agencies"],
    },
    {
        "id": "guide_bioinformatics_scientist",
        "career_id": "bioinformatics_scientist",
        "common_misconceptions": [
            "That this is the same job as a lab biologist — bioinformatics scientists mostly work computationally, not at a lab bench",
            "That it requires a medical degree — most come from computer science, statistics, or biology with computational training",
        ],
        "earning_reality": "Parents sometimes assume biology-adjacent careers pay less than pure computer science roles. Bioinformatics scientists in industry (pharmaceutical, biotech, agricultural technology companies) earn salaries comparable to general software/data roles, with the specialized biological domain knowledge often commanding a premium; academic bioinformatics roles pay considerably less than industry equivalents.",
        "career_stability": "Strong, growing demand as biological research increasingly depends on computational analysis of large datasets — this dependency is only deepening as sequencing and biological data collection become cheaper and more widespread.",
        "work_life_balance": "Generally steady in industry settings, similar to standard software/data roles; academic research positions can involve less predictable hours tied to grant and publication cycles.",
        "growth_opportunities": "Senior bioinformatics scientist and research leadership roles. Specializing in a high-growth subfield like single-cell genomics or protein structure prediction. Moving between academia and industry.",
        "alternative_routes": ["General data science roles that later add biological domain specialization", "Lab research roles with a computational analysis component"],
        "global_demand": "Strong and growing globally, particularly in countries with significant pharmaceutical and biotechnology industries.",
        "risks": ["Requires continuous learning across both biology and fast-evolving computational methods", "Academic funding can be less predictable than industry positions"],
        "opportunities": ["Work directly connected to real scientific and medical breakthroughs", "Strong transferability into the broader, in-demand data science field"],
    },
    {
        "id": "guide_ux_researcher",
        "career_id": "ux_researcher",
        "common_misconceptions": [
            "That UX research is the same job as UX design — researchers study user behavior, designers create the interface, they're distinct roles",
            "That it requires a psychology degree — many UX researchers come from varied academic backgrounds",
        ],
        "earning_reality": "Parents unfamiliar with tech careers beyond 'engineer' or 'designer' sometimes underestimate this field. UX researcher salaries at established tech companies are genuinely strong, often comparable to software engineering roles at similar seniority, reflecting real, growing demand for evidence-based product decisions.",
        "career_stability": "Generally stable at established companies with mature product teams, though this role can be more vulnerable during tech industry hiring slowdowns than core engineering roles, since some smaller companies view it as a less essential function during cost-cutting.",
        "work_life_balance": "Generally reasonable, standard tech-industry hours, with periodic intensity around major product research sprints or launches.",
        "growth_opportunities": "Senior/staff researcher and research leadership roles. Specializing in a research methodology (quantitative, accessibility research). Moving into broader product strategy roles.",
        "alternative_routes": ["Market research roles with less product-specific focus", "UX design roles for those who want more direct creative input alongside research"],
        "global_demand": "Strong in major tech hubs worldwide, though more concentrated in larger companies and established tech markets than some other tech roles.",
        "risks": ["Can be seen as a 'nice to have' at smaller or resource-constrained companies", "Field is less standardized than engineering, with variable expectations across companies"],
        "opportunities": ["Genuine influence over real product decisions affecting millions of users", "Strong demand at any company serious about evidence-based design"],
    },
    {
        "id": "guide_computational_linguist",
        "career_id": "computational_linguist",
        "common_misconceptions": [
            "That this career requires fluency in many languages — it's about understanding language structure computationally, not personal multilingual skill",
            "That modern AI language models have made this field obsolete — demand for computational linguists has actually grown alongside AI advancement",
        ],
        "earning_reality": "Parents often assume linguistics-adjacent careers pay poorly compared to 'pure' computer science. In reality, computational linguists working on natural language processing at tech companies earn salaries comparable to or exceeding general software engineering roles, reflecting the specialized, currently high-demand skill set involved in building language AI systems.",
        "career_stability": "Very strong and growing given the current AI boom's heavy dependence on language technology — this is one of the more secure specializations within the broader AI field right now.",
        "work_life_balance": "Generally similar to other software/research engineering roles — standard hours, with periodic intensity around major model releases or research deadlines.",
        "growth_opportunities": "Senior NLP engineer and research leadership roles. Specializing in a high-demand subfield like low-resource language modeling or machine translation. Moving between academic NLP research and industry.",
        "alternative_routes": ["General software engineering with an NLP specialization added later", "Linguistics research roles with a computational component"],
        "global_demand": "Very strong worldwide given the current global investment in AI and language technology, with particular opportunity in underserved languages given growing interest in AI fairness across languages.",
        "risks": ["Field moves extremely quickly, requiring continuous learning to stay current", "Highly competitive top-tier roles at major AI labs"],
        "opportunities": ["Working at the center of one of the most active areas of AI development", "Genuine opportunity to work on underserved languages with real social impact"],
    },
    {
        "id": "guide_health_informatics_specialist",
        "career_id": "health_informatics_specialist",
        "common_misconceptions": [
            "That this is just IT support for hospitals — it involves genuine strategic work on healthcare data systems and interoperability",
            "That a clinical background is required — many health informatics specialists come from computer science or public health",
        ],
        "earning_reality": "Parents sometimes assume healthcare-adjacent tech roles pay less than pure tech careers. Health informatics specialists actually earn solid, competitive salaries reflecting the specialized intersection of healthcare knowledge and technical skill, and demand has grown significantly as healthcare systems modernize their data infrastructure.",
        "career_stability": "Strong and growing as healthcare systems worldwide invest heavily in digitizing records and improving data interoperability — a long-term, structural trend rather than a temporary hiring wave.",
        "work_life_balance": "Generally standard, predictable hours, similar to other healthcare-adjacent administrative and technical roles, without the emergency demands of direct clinical care.",
        "growth_opportunities": "Senior health IT management and Chief Health Information Officer track. Specializing in clinical decision-support systems or health data interoperability standards. Moving between hospital systems and health technology companies.",
        "alternative_routes": ["General health IT support roles with narrower technical scope", "Public health data analysis roles without the informatics systems focus"],
        "global_demand": "Strong across countries actively modernizing their healthcare data infrastructure, which describes most healthcare systems worldwide right now.",
        "risks": ["Requires staying current with both healthcare regulation and technology", "Smaller field than general healthcare IT, meaning somewhat fewer total positions"],
        "opportunities": ["Meaningful impact on how healthcare actually gets delivered at a systems level", "Strong demand intersection of two genuinely stable fields (healthcare and technology)"],
    },
    {
        "id": "guide_materials_research_scientist",
        "career_id": "materials_research_scientist",
        "common_misconceptions": [
            "That materials science is the same as chemistry — it's a genuinely interdisciplinary field combining physics, chemistry, and engineering",
            "That you need a PhD for any real research role — many technician and research-assistant positions are open to bachelor's or master's graduates",
        ],
        "earning_reality": "Parents often worry pure research careers pay poorly compared to applied engineering. Materials research scientists in industry (electronics, energy, manufacturing companies) earn solid engineering-comparable salaries, while academic research roles pay considerably less — the industry-versus-academia choice matters enormously here, similar to other research-heavy fields.",
        "career_stability": "Strong demand in specific growth areas like battery materials and semiconductor materials, driven by the broader clean energy and electronics industries — genuinely stable in those applied subfields specifically.",
        "work_life_balance": "Generally steady in industry roles; academic and grant-funded research positions can involve less predictable hours around publication and funding cycles.",
        "growth_opportunities": "Senior scientist and eventually research director track. Specializing in a high-growth area like battery or semiconductor materials. Moving between academic research and industry application.",
        "alternative_routes": ["Materials engineering technician roles requiring less advanced education", "Quality engineering roles in manufacturing with a materials science foundation"],
        "global_demand": "Strong globally, particularly in countries with significant electronics, energy, or advanced manufacturing industries.",
        "risks": ["Independent research leadership roles typically require a PhD, a long educational runway", "Grant funding for academic research can be genuinely unpredictable"],
        "opportunities": ["Work directly connected to major technologies like clean energy and next-generation electronics", "Strong industry demand in specific growth subfields"],
    },
    {
        "id": "guide_neuroscience_postdoc",
        "career_id": "neuroscience_postdoc",
        "common_misconceptions": [
            "That a postdoc position is a well-paid, stable career stage — it's actually a modestly-paid, multi-year training stage before real career stability",
            "That academia is the only path from here — many neuroscience postdocs move into biotech, pharma, or data science",
        ],
        "earning_reality": "Parents should know clearly that postdoctoral positions pay modestly — often less than what the same person could earn in industry with equivalent skills — and this stage typically lasts 2-5 years, sometimes longer, before a more stable, better-paid position. This is a real, honest tradeoff for pursuing independent research training, not a temporary inconvenience before instant high pay.",
        "career_stability": "Genuinely uncertain during the postdoc and early independent-researcher stages — academic positions are competitive, and many postdocs ultimately move into industry roles that offer more stability and better compensation.",
        "work_life_balance": "Often demanding, with hours driven by experiment timelines and publication pressure rather than a fixed schedule — a real, known tradeoff of the research training path.",
        "growth_opportunities": "Academic research scientist or assistant professor track (competitive). Biotech or pharmaceutical industry research roles. Science policy or science writing careers leveraging deep subject expertise. Data science roles for those with strong computational neuroscience skills.",
        "alternative_routes": ["Industry research roles directly after a PhD, skipping the postdoc stage entirely", "Clinical research coordination roles requiring less independent research training"],
        "global_demand": "Varies significantly by country and specific research funding environment — worth researching the specific national research funding landscape before committing to this path.",
        "risks": ["Genuinely uncertain, competitive academic job market", "Multi-year period of modest pay relative to the education level"],
        "opportunities": ["Deep, genuine expertise highly valued in adjacent industries (biotech, pharma, data science) even without an academic position", "Meaningful contribution to understanding the human brain"],
    },
    {
        "id": "guide_clinical_research_coordinator",
        "career_id": "clinical_research_coordinator",
        "common_misconceptions": [
            "That this is the same job as a nurse — coordinators manage trial logistics and regulatory documentation, not direct patient nursing care",
            "That clinical trials are mostly about giving out experimental drugs — the role is largely rigorous documentation and participant management",
        ],
        "earning_reality": "Parents sometimes conflate this with nursing salaries. Clinical research coordinator pay is generally modest at entry level, comparable to other healthcare research support roles, with meaningful increases available through moving into clinical research associate or clinical trial manager roles with more experience and responsibility.",
        "career_stability": "Steady, ongoing demand as pharmaceutical and biotechnology companies continue running clinical trials — a consistent, if not explosively growing, field.",
        "work_life_balance": "Generally standard working hours, with real, predictable intensity around specific trial milestones (participant enrollment periods, regulatory audits).",
        "growth_opportunities": "Clinical research associate and clinical trial manager career track. Specializing in a specific therapeutic area (oncology, cardiology trials). Moving into regulatory affairs with additional training.",
        "alternative_routes": ["Clinical data management roles with less direct participant interaction", "Regulatory affairs roles for those more interested in the documentation/compliance side"],
        "global_demand": "Steady demand in countries with active pharmaceutical research industries, with growing opportunity in countries increasingly hosting international clinical trials.",
        "risks": ["Entry-level pay is modest relative to the precision and responsibility required", "Heavy administrative and regulatory documentation workload"],
        "opportunities": ["Direct contribution to real medical advancement", "Clear career progression path into higher-paid clinical research roles"],
    },
    {
        "id": "guide_startup_founder",
        "career_id": "startup_founder",
        "common_misconceptions": [
            "That founders are naturally fearless risk-takers — most manage real, constant fear and uncertainty",
            "That funding equals success — many well-funded startups still fail",
        ],
        "earning_reality": "Parents are right to be concerned here — most founders pay themselves very little, sometimes nothing, for the first one to two years, and a majority of startups fail without ever providing a meaningful financial return. This is a genuinely high-risk path financially, and it's worth having an honest conversation about how your child plans to support themselves during this period, and what their plan is if the venture doesn't succeed.",
        "career_stability": "Genuinely low in the traditional sense — there's no guaranteed paycheck, no employer safety net, and most ventures don't ultimately succeed. The 'stability' in this path comes from transferable skills and experience, not the venture itself.",
        "work_life_balance": "Often very poor, especially in the early stages — long hours, constant stress, and blurred boundaries between work and personal life are the norm, not the exception, for most founders.",
        "growth_opportunities": "A successful exit (acquisition or IPO) providing significant financial return. Even an unsuccessful venture often leads to valuable experience for a next venture or a strong operating role at another company. Building genuinely transferable leadership and problem-solving skills.",
        "alternative_routes": ["Joining an early-stage startup as an employee to learn the environment with less personal financial risk", "Starting a smaller, bootstrapped side business while maintaining other income"],
        "global_demand": "Entrepreneurship itself isn't 'in demand' in the traditional employment sense — but startup ecosystems and available funding/support infrastructure vary considerably by country and city.",
        "risks": ["High rate of financial failure — most startups do not succeed", "No guaranteed income, benefits, or employment stability", "Significant personal financial risk if self-funded"],
        "opportunities": ["Potential for significant financial and personal reward if successful", "Rapid, compressed learning across every business function", "Full ownership and creative control over the venture's direction"],
    },
    {
        "id": "guide_product_led_growth_specialist",
        "career_id": "product_led_growth_specialist",
        "common_misconceptions": [
            "That growth roles are just marketing with a different name — it's a genuinely data-driven, product-focused discipline",
            "That it's all about growth hacks and gimmicks — real growth work is rigorous experimentation and product design",
        ],
        "earning_reality": "Parents unfamiliar with newer tech job titles sometimes assume this is a less 'serious' role than traditional product management. In reality, product-led growth specialists at established tech companies earn salaries comparable to product management roles, reflecting genuine, measurable business impact on user activation and retention.",
        "career_stability": "Generally stable at companies with mature product organizations, though as with UX research, this can be a role more vulnerable to cuts at smaller or resource-constrained companies compared to core engineering.",
        "work_life_balance": "Generally reasonable, standard tech-industry hours, with periodic intensity around major experiment launches or product changes.",
        "growth_opportunities": "Senior growth PM and eventually Head of Growth roles. Moving into broader product management. Specializing in a specific growth lever (onboarding, pricing, retention).",
        "alternative_routes": ["General product management without the growth specialization", "Marketing roles with a data-driven, product-adjacent focus"],
        "global_demand": "Strong in major tech hubs, concentrated particularly in SaaS and subscription-based technology companies.",
        "risks": ["Newer role type with less standardized career progression than traditional engineering or product management", "Success is closely tied to measurable metrics, which can create real performance pressure"],
        "opportunities": ["Direct, visible impact on a company's growth and revenue", "Genuinely interesting blend of data analysis, product thinking, and user psychology"],
    },
    {
        "id": "guide_developer_relations_engineer",
        "career_id": "developer_relations_engineer",
        "common_misconceptions": [
            "That DevRel is just marketing for developers — strong DevRel engineers write real code and documentation",
            "That you need to be a top-tier engineer — communication skill matters as much as deep technical mastery",
        ],
        "earning_reality": "Parents unfamiliar with this role sometimes assume it's a lower-paid, marketing-adjacent position. In reality, developer relations engineers at established tech companies earn salaries generally comparable to software engineering roles, reflecting the genuine technical skill the role requires alongside public communication ability.",
        "career_stability": "Reasonably stable at companies with real developer-facing products (APIs, developer tools, cloud platforms), though this role can be vulnerable to cuts during company-wide cost reductions since it's sometimes seen as less core than direct product engineering.",
        "work_life_balance": "Generally standard hours, with periodic travel for conference speaking engagements, which can affect work-life balance differently than a typical desk-bound engineering role.",
        "growth_opportunities": "Senior DevRel and Head of Developer Relations track. Moving into product management for developer-facing products. Building a public technical reputation that opens broader career opportunities.",
        "alternative_routes": ["Technical writing roles with narrower documentation focus", "Software engineering roles with occasional community/content contribution"],
        "global_demand": "Strong at companies with genuine developer-facing products, concentrated in tech hubs but increasingly remote-friendly given the role's communication-centric nature.",
        "risks": ["Requires public visibility and comfort with public speaking, not suited to everyone", "Sometimes seen as more 'optional' than core engineering during company cost-cutting"],
        "opportunities": ["Builds a genuinely portable public reputation and network", "Interesting blend of technical work, writing, and public communication"],
    },
    {
        "id": "guide_foreign_service_officer",
        "career_id": "foreign_service_officer",
        "common_misconceptions": [
            "That the job is glamorous social events, not real work — most work is serious casework, reporting, and negotiation",
            "That diplomats decide foreign policy independently — officers implement and inform policy, they don't set it unilaterally",
        ],
        "earning_reality": "Parents often assume diplomatic careers are either extremely prestigious and well-paid, or financially uncertain. In reality, foreign service salaries are typically stable government-employee pay — respectable but not exceptional — with real, valuable benefits like housing allowances and pension plans in many countries' foreign services, but not fast wealth.",
        "career_stability": "Very stable — foreign service is a career civil service position in most countries, offering strong job security and a clear, structured promotion path over a career.",
        "work_life_balance": "Genuinely challenging due to frequent international postings that disrupt family life, and real unpredictability around consular crisis response — a known, honest tradeoff of the career.",
        "growth_opportunities": "Structured promotion through officer ranks toward senior diplomatic and eventually ambassadorial roles. Specializing in a policy area (trade, security, development) for expert-track roles. International organization roles (UN, multilateral institutions) later in a career.",
        "alternative_routes": ["International NGO or development roles requiring less formal government entrance exam process", "International business or trade roles leveraging cross-cultural skills without full diplomatic postings"],
        "global_demand": "Each country has a limited, competitive number of foreign service positions — genuine job security once in, but real competitiveness getting in.",
        "risks": ["Highly competitive entrance exam/selection process, often requiring multiple attempts", "Frequent relocation genuinely disrupts family and personal life"],
        "opportunities": ["Genuine international career with real global exposure", "Strong job security and structured career progression once selected"],
    },
    {
        "id": "guide_public_health_policy_analyst",
        "career_id": "public_health_policy_analyst",
        "common_misconceptions": [
            "That this role designs medical treatments — it's about health system policy and resource allocation, not clinical medicine",
            "That it's the same job as public health research — policy analysts translate evidence into actionable recommendations, a distinct skill from pure research",
        ],
        "earning_reality": "Parents sometimes assume policy roles pay poorly compared to clinical healthcare careers. Public health policy analyst pay is moderate — comparable to other government or nonprofit policy roles, generally less than clinical medicine, but with real, meaningful growth potential moving into senior policy leadership positions over a career.",
        "career_stability": "Generally stable, particularly in government and larger nonprofit organizations, with consistent demand for health policy expertise across economic cycles since public health needs don't disappear during downturns.",
        "work_life_balance": "Generally standard working hours, with periodic intensity around major policy proposal deadlines or legislative sessions.",
        "growth_opportunities": "Senior policy advisor and eventually director of health policy roles. Specializing in a specific policy area (health equity, health financing). Moving between government, nonprofit, and international organization roles.",
        "alternative_routes": ["Health economics roles with narrower financial analysis focus", "Public health research roles without the direct policy translation component"],
        "global_demand": "Steady demand globally, particularly strong in countries actively reforming their healthcare systems or responding to public health crises.",
        "risks": ["Real policy change happens slowly, which can be frustrating for those wanting immediate impact", "Government roles can be affected by political administration changes"],
        "opportunities": ["Genuine influence over health outcomes at a population level, not just individual patients", "Meaningful, mission-driven work"],
    },
    {
        "id": "guide_urban_planner",
        "career_id": "urban_planner",
        "common_misconceptions": [
            "That urban planners just draw maps — it's deeply about community engagement, policy, and negotiation",
            "That it's the same as architecture — planners focus on land use and community systems, not individual building design",
        ],
        "earning_reality": "Parents often underestimate this career's earning potential. Municipal urban planner salaries are solid, stable government or consulting pay, generally comparable to other professional planning and engineering roles, with meaningful increases available through professional certification and senior planning leadership roles.",
        "career_stability": "Strong, stable demand — cities and municipalities always need planning expertise, and this demand is intensifying with growing urbanization and climate adaptation infrastructure needs worldwide.",
        "work_life_balance": "Generally standard working hours, with periodic evening commitments for public hearings and community consultation meetings that are a core, expected part of the job.",
        "growth_opportunities": "Senior planner and planning director track. Professional certification (like AICP) unlocking higher-responsibility roles. Specializing in transit planning or climate-resilient infrastructure, growing subfields.",
        "alternative_routes": ["Planning technician roles requiring less formal graduate education", "Real estate development roles with a planning background"],
        "global_demand": "Strong globally given ongoing urbanization trends, particularly in rapidly growing cities across Asia, Africa, and Latin America.",
        "risks": ["Public criticism of proposed plans is a real, normal part of the job requiring resilience", "Government roles can be affected by budget or political changes"],
        "opportunities": ["Direct, visible impact on how real communities live and move", "Growing demand specifically in climate adaptation and sustainable transit planning"],
    },
    {
        "id": "guide_ngo_program_manager",
        "career_id": "ngo_program_manager",
        "common_misconceptions": [
            "That NGO work doesn't pay a livable wage at any level — senior program management roles can pay reasonably well",
            "That development work is simple charity — it's complex, evidence-based program design and management",
        ],
        "earning_reality": "Parents are right to have real concerns here. Entry-level and volunteer positions in international development are often unpaid or very low-paid, which genuinely limits who can afford to start in this field without other financial support. However, program management and director-level roles at established international NGOs pay considerably more, and the earning trajectory does improve meaningfully with experience — this is a real financial conversation worth having honestly upfront.",
        "career_stability": "Generally stable at larger, well-established international NGOs, though funding for specific programs can be tied to grant cycles, creating some real project-level uncertainty even within a stable organization.",
        "work_life_balance": "Can be demanding, particularly for field-based roles requiring significant travel and time away from home, though headquarters-based program management roles are more predictable.",
        "growth_opportunities": "Country director and regional program director track. Specializing in a sector (education, health, emergency response). Moving between NGO, government, and international organization roles.",
        "alternative_routes": ["Smaller local NGO roles with more immediate hands-on responsibility", "Corporate social responsibility roles within for-profit companies, often better-paid"],
        "global_demand": "Steady demand globally, with international development work concentrated at major NGO headquarters and in regions with significant humanitarian or development needs.",
        "risks": ["Entry-level pay is often very low or unpaid", "Program funding can be affected by shifting donor priorities"],
        "opportunities": ["Deep, direct impact on real communities' wellbeing", "Genuine international career with meaningful cross-cultural experience"],
    },
    {
        "id": "guide_conservation_biologist",
        "career_id": "conservation_biologist",
        "common_misconceptions": [
            "That conservation biology is mostly cuddling animals — it's rigorous field science, often physically demanding",
            "That it's a financially unrealistic career choice — while modest, real, stable careers exist in this field",
        ],
        "earning_reality": "Parents are right to note this field pays modestly compared to many other sciences — conservation biologist salaries, especially at nonprofits, are genuinely lower than equivalent roles in industry or medicine. However, government agency and senior NGO positions offer more competitive, stable pay, and the honest tradeoff here is mission-driven work over maximum earning potential — worth discussing directly with your child.",
        "career_stability": "Reasonably stable in government conservation agencies and larger, established conservation NGOs, though smaller organizations and grant-funded field research positions can have less predictable long-term stability.",
        "work_life_balance": "Field seasons involve real, sometimes physically demanding work in remote conditions with irregular hours; office-based analysis seasons are more standard and predictable.",
        "growth_opportunities": "Senior conservation scientist and program director roles. Specializing in a high-need area like climate resilience or human-wildlife conflict. Moving between field research, policy, and NGO leadership.",
        "alternative_routes": ["Park ranger or wildlife management technician roles requiring less advanced education", "Environmental consulting roles with more consistent private-sector pay"],
        "global_demand": "Meaningful demand globally, particularly in biodiversity-rich regions and countries investing in conservation infrastructure, though overall field size is smaller than many other sciences.",
        "risks": ["Modest pay relative to years of specialized education required", "Grant-dependent funding can create real project-level instability"],
        "opportunities": ["Deeply meaningful, mission-driven work protecting real ecosystems", "Growing demand specifically in climate-resilience-focused conservation"],
    },
    {
        "id": "guide_human_rights_researcher",
        "career_id": "human_rights_researcher",
        "common_misconceptions": [
            "That this work is the same as being a lawyer — many human rights researchers come from journalism or social science backgrounds, not law",
            "That documentation alone quickly leads to justice — real accountability processes are often very slow",
        ],
        "earning_reality": "Parents should know human rights research, particularly at nonprofit organizations, generally pays modestly compared to corporate careers — this is real, mission-driven work with a genuine financial tradeoff, though larger, established human rights organizations (Amnesty International, Human Rights Watch) offer more competitive, stable pay at senior levels than smaller local organizations.",
        "career_stability": "Reasonably stable at large, established international human rights organizations; smaller organizations and specific research projects can be more dependent on grant funding and donor priorities.",
        "work_life_balance": "Can be demanding and emotionally difficult given the subject matter, with real potential safety risk in fieldwork involving conflict or repressive environments — a genuine, serious consideration worth discussing directly.",
        "growth_opportunities": "Senior researcher and research director track. Specializing in a specific area (digital rights, refugee rights, war crimes documentation). Moving into international law or policy roles with additional training.",
        "alternative_routes": ["Investigative journalism roles with overlapping skills and mission", "Policy research roles with narrower advocacy focus"],
        "global_demand": "Steady demand at major international human rights organizations, concentrated in a relatively small number of large, established institutions.",
        "risks": ["Real personal safety risk in fieldwork involving conflict or repressive regimes", "Modest pay relative to the emotional and sometimes physical demands"],
        "opportunities": ["Deeply meaningful work directly documenting and addressing real injustice", "Genuine potential to contribute to real, lasting accountability"],
    },
    {
        "id": "guide_ias_officer_india",
        "career_id": "ias_officer_india",
        "common_misconceptions": [
            "That IAS officers have unchecked personal power — the role carries real administrative authority but also constant public accountability",
            "That success depends only on passing the exam — the actual administrative work requires a very different skill set from exam preparation",
        ],
        "earning_reality": "Parents should understand IAS compensation is a stable government pay scale — respectable and secure, with real benefits including housing and pension, but not comparable to top private-sector salaries. The real appeal of this path is the extraordinary administrative authority, prestige, and public service impact, not maximum earning potential.",
        "career_stability": "Extremely stable — this is one of the most secure career paths that exists in India, a permanent civil service position with clear, structured promotion through a career.",
        "work_life_balance": "Can be genuinely demanding depending on posting, particularly law-and-order or crisis-response responsibilities, with limited control over where in the country an officer is posted.",
        "growth_opportunities": "Structured promotion through District Collector, State Secretary, and eventually Chief Secretary or central ministry roles. Deputation to central government policy roles. Post-retirement roles in public policy, academia, or corporate governance.",
        "alternative_routes": ["State civil service exams with somewhat less competitive entry than the national IAS exam", "Other central civil services (IPS, IFS) via the same UPSC examination process"],
        "global_demand": "This is a nationally-specific career (Indian government service) — not internationally portable in the same way as many other careers, worth understanding clearly.",
        "risks": ["Extremely competitive entrance exam, with selection rates often well under 1%", "Limited control over posting location, which can mean significant family disruption"],
        "opportunities": ["Extraordinary administrative authority and direct ability to shape public policy implementation", "Very high social prestige and strong job security"],
    },
    {
        "id": "guide_uk_civil_service_fast_streamer",
        "career_id": "uk_civil_service_fast_streamer",
        "common_misconceptions": [
            "That civil servants make political decisions — they implement and inform policy, elected officials and ministers make the political calls",
            "That the Fast Stream guarantees rapid promotion regardless of performance — advancement still depends on real, demonstrated performance",
        ],
        "earning_reality": "Parents should know Fast Stream starting salaries are moderate — reasonable but not exceptional compared to private-sector graduate schemes in fields like finance or consulting — with the appeal being genuine influence over national policy and strong long-term career stability rather than maximum early-career earning.",
        "career_stability": "Very stable — UK civil service positions offer strong job security and a structured, well-defined career progression, among the more secure career paths in the UK generally.",
        "work_life_balance": "Generally standard government working hours, with periodic intensity around major policy announcements or legislative deadlines.",
        "growth_opportunities": "Structured Fast Stream rotation building broad experience across government departments. Progression to Deputy Director and eventually Director/Permanent Secretary roles. Specialization in a specific policy area for expert-track advancement.",
        "alternative_routes": ["Standard (non-Fast Stream) civil service entry, a slower but still real career path", "Public policy roles at think tanks or NGOs, often with easier entry"],
        "global_demand": "This is a nationally-specific career (UK government service), though the analytical and policy skills developed are genuinely transferable to public policy roles internationally.",
        "risks": ["Highly competitive selection process for the Fast Stream specifically", "Rotational structure means less control over specific department placement, especially early on"],
        "opportunities": ["Genuine influence over national policy from early in a career", "Strong job security and clear, structured career progression"],
    },
    {
        "id": "guide_japan_traditional_craft_master",
        "career_id": "japan_traditional_craft_master",
        "common_misconceptions": [
            "That traditional crafts have no real modern economic relevance — many traditional craft products command premium prices in both domestic and international markets",
            "That mastery can be achieved quickly — this genuinely takes a decade or more of sustained apprenticeship",
        ],
        "earning_reality": "Parents should have an honest conversation here: financial security in traditional craftsmanship varies enormously depending on the specific craft, market demand, and an individual's eventual reputation — some master craftspeople earn very well through premium products and cultural recognition, while others, especially early in their careers, earn modestly. This is a genuinely long-term financial path requiring real patience and sustained commitment before it typically becomes financially stable.",
        "career_stability": "Uncertain in a modern employment sense — this isn't a career with a standard employer, salary, or benefits structure. Stability instead comes from building a reputation and market for the craft over many years, which varies significantly by specific craft and demand trends.",
        "work_life_balance": "The apprenticeship years demand deep, sustained, deliberate practice, often full working days over many years — a genuine, serious time commitment before independent mastery and more personal schedule control.",
        "growth_opportunities": "Progression from apprentice to independent master craftsperson. Potential government recognition as a Traditional Craft, adding market value and cultural prestige. Teaching future apprentices once established.",
        "alternative_routes": ["Studying craft history and business at a specialized program before or alongside a traditional apprenticeship", "Combining craft skills with modern design or business training for broader market reach"],
        "global_demand": "Traditional craft mastery is deeply tied to a specific cultural and geographic context (in this case, Japan) — this is not a broadly internationally portable career in the way many modern professions are, worth understanding clearly.",
        "risks": ["Very long training timeline (often a decade or more) before real independent mastery", "Market demand for specific traditional crafts can be genuinely uncertain and shifting"],
        "opportunities": ["Preserving and continuing genuinely significant cultural heritage", "Growing appreciation and premium market value for authentic traditional craftsmanship in a mass-produced world"],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    guides = [ParentCareerGuide.model_validate(g) for g in GUIDES]

    def _upsert() -> None:
        client.table("parent_career_guides").upsert([g.model_dump(mode="json") for g in guides]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(guides)} parent career guides.")


if __name__ == "__main__":
    asyncio.run(seed())
