"""Connect Batch 1 — Expert Connect seed data, fourth wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch4
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_nurse_practitioner_ruth_mwangi",
        "name": "Ruth Mwangi, Nurse Practitioner",
        "role_type": "industry_professional", "field": "nursing", "bio": "Runs a rural primary care clinic as a nurse practitioner; almost left nursing after a brutal first year on a hospital ward.",
        "trait_tags": ["empathy", "persistence"], "learning_style_fit": "Students who want frontline patient care with more independence than a standard nursing role.",
        "organization": "A rural community health clinic", "years_experience": 12, "journey_highlights": ["Nearly quit nursing after an exhausting first hospital year", "Now runs her own clinic serving an underserved rural area"],
        "discussion_topics": ["Nursing burnout in the first year", "Nurse practitioner vs. registered nurse paths", "Rural healthcare realities"],
        "profession": "Nurse Practitioner", "specialization": "Rural primary care", "country": "Kenya", "city": "Eldoret",
        "industries": ["healthcare"], "education": ["BSc Nursing, Moi University", "Nurse Practitioner certification"],
        "current_role": "Lead Nurse Practitioner, Rural Clinic", "languages": ["English", "Swahili"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students considering nursing who worry about first-year burnout", "Students interested in nurse practitioner roles for more clinical independence", "Students interested in rural or underserved healthcare"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "university", "label": "BSc Nursing", "description": "Trained in a busy urban teaching hospital.", "year_label": "2008-2012"},
            {"stage": "failure", "label": "Nearly quit after an exhausting, understaffed first hospital year", "description": "Regularly worked double shifts and felt she couldn't provide the care patients deserved.", "year_label": "2013"},
            {"stage": "turning_point", "label": "Moved to a smaller rural clinic and pursued nurse practitioner certification", "description": "Found renewed purpose in a role with more autonomy and closer patient relationships.", "year_label": "2015"},
            {"stage": "current_role", "label": "Lead Nurse Practitioner, Rural Clinic", "description": "Provides primary care to a community with very limited access to physicians.", "year_label": "2017-present"},
        ],
        "day_in_the_life": "Sees a wide range of patients independently, from routine care to complex cases requiring referral to distant hospitals.",
        "weekly_routine": "Clinic days five days a week, with occasional home visits for patients who can't travel.",
        "biggest_challenges": ["Being the only clinical provider for a wide area with no nearby specialist backup", "Chronic under-resourcing of rural healthcare"],
        "favourite_part": "The close, long-term relationships she builds with patients she sees for years.",
        "biggest_misconceptions": ["That nurse practitioners have less clinical responsibility than doctors", "That rural healthcare work is a lesser career choice"],
        "what_surprised_them": "How much independent clinical judgment the role actually requires without a physician nearby.",
        "biggest_mistake": "During my exhausting first hospital year, I once nearly missed a critical change in a patient's condition because I was covering too many patients at once. It didn't lead to harm, but it scared me enough to eventually leave that unsustainable environment for good.",
        "one_regret": "I regret staying in that unsustainable first hospital job as long as I did out of guilt about leaving colleagues short-staffed.",
        "salary_reality": "Rural nurse practitioner pay in Kenya is modest but the role's independence and community impact are what keep her there rather than a hospital.",
        "work_life_balance": "Better than her exhausting hospital years, though being the sole provider for a rural community means real on-call responsibility.",
        "daily_skills": ["clinical assessment", "primary care treatment", "patient education"],
        "daily_tools": ["Basic diagnostic equipment", "portable health records system"],
        "recommended_books": ["Being Mortal by Atul Gawande"],
        "recommended_communities": ["National Nurses Association of Kenya"],
        "advice_for_beginners": "If a first placement is unsustainable, that's the environment's fault, not yours — a different setting changed everything for me.",
        "advice_for_parents": "Nurse practitioners carry real independent clinical responsibility — it's a serious, respected healthcare career, not a stepping stone to 'becoming a real doctor.'",
        "faqs": [{"question": "What can a nurse practitioner do that a registered nurse can't?", "answer": "In many settings, nurse practitioners can diagnose, treat, and prescribe independently — a meaningfully expanded scope of practice."}],
        "projects": [], "research": [], "certifications": ["Nurse Practitioner certification, Kenya"],
        "conferences": [], "organizations": ["National Nurses Association of Kenya"],
        "volunteer_work": ["Runs free monthly health outreach days for surrounding villages"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_dentist_paulo_silva",
        "name": "Dr. Paulo Silva, Dentist",
        "role_type": "industry_professional", "field": "dentistry", "bio": "Runs a private dental practice; struggled financially for years after opening his own clinic too early, without enough patients.",
        "trait_tags": ["persistence", "analytical_thinking"], "learning_style_fit": "Students interested in the technical precision of dentistry combined with running a small business.",
        "organization": "A private dental practice", "years_experience": 14, "journey_highlights": ["Nearly went bankrupt in his clinic's second year", "Now runs a stable practice with a loyal patient base"],
        "discussion_topics": ["The business side of dentistry", "Surviving a near-bankruptcy", "Dental school realities"],
        "profession": "General Dentist", "specialization": "Private general dentistry practice", "country": "Portugal", "city": "Porto",
        "industries": ["healthcare"], "education": ["DDS, University of Porto"],
        "current_role": "Owner and Lead Dentist", "languages": ["Portuguese", "English", "Spanish"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in dentistry as both clinical and small-business work", "Students who've faced a near-financial-failure and want reassurance it's recoverable", "Students weighing dental school's real costs and timeline"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "university", "label": "DDS", "description": "Took on significant student debt to complete his degree.", "year_label": "2003-2008"},
            {"stage": "first_job", "label": "Associate dentist at an established practice", "description": "Built clinical experience before attempting to open his own clinic.", "year_label": "2008-2012"},
            {"stage": "failure", "label": "Opened his own practice too early with too small a patient base", "description": "Nearly went bankrupt in his second year of ownership, close to losing the practice entirely.", "year_label": "2013"},
            {"stage": "turning_point", "label": "Restructured his business with better financial planning and patient outreach", "description": "Hired a part-time practice manager and rebuilt patient acquisition from scratch.", "year_label": "2014"},
            {"stage": "current_role", "label": "Owner and Lead Dentist", "description": "Runs a financially stable practice with a loyal, long-term patient base.", "year_label": "2016-present"},
        ],
        "day_in_the_life": "Patient appointments most of the day, with practice management tasks handled before or after clinical hours.",
        "weekly_routine": "Full clinical schedule with one afternoon reserved for administrative and financial review.",
        "biggest_challenges": ["Running a small business alongside demanding clinical work", "Patient anxiety about dental visits requiring real interpersonal skill to manage"],
        "favourite_part": "A patient who once feared the dentist now coming in comfortably for routine checkups.",
        "biggest_misconceptions": ["That dentistry is purely clinical — running a private practice is a genuine small business", "That opening your own practice immediately after graduation is the ideal path"],
        "what_surprised_them": "How much of a private practice's success depends on business skills he was never taught in dental school.",
        "biggest_mistake": "I opened my own clinic without a real financial cushion or a solid plan for attracting patients, assuming clinical skill alone would be enough. It nearly cost me the practice, and I learned business planning is just as essential as clinical training.",
        "one_regret": "I regret not gaining more business experience or mentorship before opening my own clinic — a few conversations with an experienced practice owner would have prevented my near-bankruptcy.",
        "salary_reality": "Dental practice ownership in Portugal can be very financially rewarding once established, but the early years carry real financial risk that dental school doesn't prepare you for.",
        "work_life_balance": "Generally good now, though the early practice-building years were extremely demanding.",
        "daily_skills": ["clinical dentistry", "practice management", "patient communication"],
        "daily_tools": ["Dental equipment and imaging", "practice management software"],
        "recommended_books": ["The E-Myth Revisited by Michael Gerber"],
        "recommended_communities": ["Portuguese Dental Association"],
        "advice_for_beginners": "Get real business mentorship before opening your own practice — clinical skill alone nearly bankrupted me.",
        "advice_for_parents": "A dentist's near-bankruptcy while building a private practice is a business risk, not a sign of clinical incompetence — the two are genuinely separate skills.",
        "faqs": [{"question": "Should new dentists open their own practice right away?", "answer": "I'd strongly recommend gaining associate experience and business knowledge first — my own early attempt nearly failed for exactly this reason."}],
        "projects": [], "research": [], "certifications": ["Licensed Dentist, Portugal"],
        "conferences": [], "organizations": ["Portuguese Dental Association"],
        "volunteer_work": ["Provides free dental care one day a month for low-income patients"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_social_worker_thandiwe_ndlovu",
        "name": "Thandiwe Ndlovu, Clinical Social Worker",
        "role_type": "industry_professional", "field": "social work", "bio": "Works with foster families and at-risk children at a child welfare agency; a particularly difficult early case led her to briefly leave the field.",
        "trait_tags": ["empathy", "persistence"], "learning_style_fit": "Students drawn to helping vulnerable people who want honesty about the emotional cost.",
        "organization": "A child welfare agency", "years_experience": 13, "journey_highlights": ["Left the field for a year after a devastating case outcome", "Returned and built a specialized foster care support program"],
        "discussion_topics": ["Burnout and stepping away from social work", "The realities of child welfare casework", "Rebuilding after leaving a career you cared about"],
        "profession": "Clinical Social Worker", "specialization": "Foster care and child welfare", "country": "South Africa", "city": "Durban",
        "industries": ["social work", "human services"], "education": ["BSW, University of KwaZulu-Natal", "MSW, University of Cape Town"],
        "current_role": "Senior Clinical Social Worker", "languages": ["English", "Zulu"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students drawn to social work who need honesty about its emotional cost", "Students who've stepped away from a caring profession and wonder about returning", "Students interested in child welfare specifically"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BSW, then MSW", "description": "Specialized her graduate studies in child and family welfare.", "year_label": "2006-2012"},
            {"stage": "first_job", "label": "Caseworker at a child welfare agency", "description": "Carried a heavy caseload of children in crisis situations.", "year_label": "2012-2016"},
            {"stage": "failure", "label": "A case involving a child she'd worked with for years ended in tragedy", "description": "The outcome devastated her and she took an extended leave, ultimately leaving the field entirely for a year.", "year_label": "2016"},
            {"stage": "career_transition", "label": "Worked a corporate HR role during her year away", "description": "Found the work financially stable but personally unfulfilling compared to social work.", "year_label": "2016-2017"},
            {"stage": "turning_point", "label": "Returned to social work with better boundaries and supervision support", "description": "Built a more sustainable approach to the emotional demands of the work.", "year_label": "2018"},
            {"stage": "current_role", "label": "Senior Clinical Social Worker", "description": "Built a specialized foster care support program now used across the agency.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of home visits, court appearances, and case coordination meetings with other service providers.",
        "weekly_routine": "Field visits early in the week, documentation and case planning later.",
        "biggest_challenges": ["Carrying the emotional weight of children's difficult circumstances", "Navigating an overburdened child welfare system with limited resources"],
        "favourite_part": "A foster placement that genuinely stabilizes and improves a child's life.",
        "biggest_misconceptions": ["That leaving a caring profession due to burnout is a permanent failure", "That social work is simple emotional support rather than complex casework requiring real clinical judgment"],
        "what_surprised_them": "How much real systemic and bureaucratic navigation the job requires beyond direct emotional support.",
        "biggest_mistake": "In the years before my leave, I didn't set boundaries around taking on more cases than I could realistically manage well, largely because I felt guilty saying no. Overload contributed directly to my burnout and eventually to leaving.",
        "one_regret": "I regret not seeking professional supervision and support sooner — I tried to carry the emotional weight of the work alone for years before it became unsustainable.",
        "salary_reality": "Social work salaries in South Africa's public and nonprofit sectors are modest, a real and ongoing frustration given the emotional demands of the role.",
        "work_life_balance": "Requires deliberate boundary-setting — without it, the work can consume all available emotional and time reserves, as she learned firsthand.",
        "daily_skills": ["case assessment", "crisis intervention", "systems navigation"],
        "daily_tools": ["Case management software", "risk assessment frameworks"],
        "recommended_books": ["Trauma Stewardship by Laura van Dernoot Lipsky"],
        "recommended_communities": ["South African Council for Social Service Professions"],
        "advice_for_beginners": "Set real boundaries around your caseload from the start — my failure to do this is what led directly to my burnout.",
        "advice_for_parents": "Stepping away from a caring profession due to burnout isn't giving up — for my own life, that year away is what allowed me to return sustainably rather than leaving for good.",
        "faqs": [{"question": "Is it common for social workers to leave and return to the field?", "answer": "Yes — burnout is a well-documented, common challenge in this field, and stepping away temporarily with the right support often leads to a more sustainable long-term career."}],
        "projects": ["Built a specialized foster care support program now used agency-wide"], "research": [],
        "certifications": ["Licensed Clinical Social Worker"], "conferences": [], "organizations": [],
        "volunteer_work": ["Runs peer support groups for social workers experiencing burnout"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_actuary_johan_bergstrom",
        "name": "Johan Bergström, Actuary",
        "role_type": "industry_professional", "field": "actuarial science", "bio": "Prices insurance risk for a Nordic insurance company; failed three actuarial exams over five years while working full-time.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who like rigorous mathematics applied to real financial risk problems.",
        "organization": "A Nordic insurance company", "years_experience": 11, "journey_highlights": ["Failed three professional actuarial exams over five years", "Now leads pricing strategy for a major insurance product line"],
        "discussion_topics": ["The long, grueling actuarial exam process", "Balancing full-time work with professional exams", "What actuaries actually do"],
        "profession": "Senior Actuary", "specialization": "Insurance risk pricing", "country": "Sweden", "city": "Stockholm",
        "industries": ["finance", "insurance"], "education": ["BSc Mathematics, Stockholm University", "Professional actuarial qualification"],
        "current_role": "Senior Actuary, Pricing", "languages": ["Swedish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like mathematics but aren't sure what career applies it directly", "Students facing repeated professional exam failures", "Students confused about what actuaries actually do day to day"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BSc Mathematics", "description": "Discovered actuarial science through a career fair, not knowing much about it beforehand.", "year_label": "2008-2011"},
            {"stage": "first_job", "label": "Actuarial analyst while beginning professional exams", "description": "Began the long process of exams required for full qualification, expecting it to take a few years.", "year_label": "2011-2013"},
            {"stage": "failure", "label": "Failed three separate professional exams across five years", "description": "The exams' low pass rates and the grind of studying after full workdays repeatedly wore down his motivation.", "year_label": "2012-2016"},
            {"stage": "turning_point", "label": "Finally completed his full qualification after restructuring his study schedule around dedicated weekly blocks", "description": "Treated exam study as a non-negotiable weekly commitment rather than something to fit in when convenient.", "year_label": "2017"},
            {"stage": "current_role", "label": "Senior Actuary, Pricing", "description": "Leads pricing strategy for a major line of insurance products.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Statistical modeling and data analysis, with regular meetings translating technical risk findings for non-technical business colleagues.",
        "weekly_routine": "Deep analytical work most days, with periodic collaborative sessions with underwriting and product teams.",
        "biggest_challenges": ["The multi-year exam process while working full-time", "Communicating complex statistical risk in terms business leaders can act on"],
        "favourite_part": "Finding a genuinely better way to price risk that makes the business both fairer and more profitable.",
        "biggest_misconceptions": ["That actuarial work is purely abstract math with no real-world application", "That failing a professional exam disqualifies you from ultimately qualifying"],
        "what_surprised_them": "How much communication skill the role demands, translating statistics for non-technical audiences.",
        "biggest_mistake": "For years I studied for exams in scattered, inconsistent sessions squeezed in whenever I had spare time, which never built the depth I actually needed. Dedicating consistent weekly blocks, treated as non-negotiable, is what finally got me through.",
        "one_regret": "I regret not restructuring my study approach after my first failed exam instead of repeating the same scattered method two more times.",
        "salary_reality": "Actuarial salaries in Sweden are strong once fully qualified, reflecting the difficulty of the exam process — but the multi-year qualification period pays considerably less.",
        "work_life_balance": "Reasonable now, though the years of studying alongside full-time work were genuinely exhausting.",
        "daily_skills": ["statistical modeling", "risk analysis", "data communication"],
        "daily_tools": ["R", "Excel", "actuarial modeling software"],
        "recommended_books": ["The Signal and the Noise by Nate Silver"],
        "recommended_communities": ["Swedish Actuarial Society"],
        "advice_for_beginners": "Build a consistent, non-negotiable weekly study schedule for professional exams from the start — my scattered approach cost me years of repeated failure.",
        "advice_for_parents": "Actuarial qualification is a genuinely long, difficult process with real failure rates built into the profession — repeated exam attempts are normal, not a sign your child isn't capable.",
        "faqs": [{"question": "How long does it take to become a fully qualified actuary?", "answer": "Often 5-10 years of exams alongside full-time work — failing individual exams along the way is extremely common, not a red flag."}],
        "projects": [], "research": [], "certifications": ["Fully qualified Actuary"],
        "conferences": [], "organizations": ["Swedish Actuarial Society"],
        "volunteer_work": ["Runs a study group for actuarial exam candidates"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_real_estate_developer_omar_khalil",
        "name": "Omar Khalil, Real Estate Developer",
        "role_type": "founder", "field": "real estate", "bio": "Develops mixed-use residential projects; his first development project went massively over budget and nearly bankrupted his small company.",
        "trait_tags": ["persistence", "analytical_thinking"], "learning_style_fit": "Students interested in the intersection of finance, construction, and design.",
        "organization": "A real estate development company", "years_experience": 14, "journey_highlights": ["His first development project went 60% over budget", "Now leads a company with several successfully completed developments"],
        "discussion_topics": ["Surviving a catastrophic budget overrun", "Real estate development as a career path", "Balancing risk and ambition in business"],
        "profession": "Real Estate Developer", "specialization": "Mixed-use residential development", "country": "United Arab Emirates", "city": "Dubai",
        "industries": ["real estate", "construction"], "education": ["BSc Civil Engineering, American University of Sharjah", "MBA, London Business School"],
        "current_role": "Founder and Managing Director", "languages": ["Arabic", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in real estate development specifically, not just construction or finance alone", "Students who've experienced a costly early business mistake", "Students weighing entrepreneurship in a capital-intensive industry"],
        "career_ids": ["civil_engineer", "startup_founder"],
        "career_journey": [
            {"stage": "university", "label": "BSc Civil Engineering, then MBA", "description": "Combined technical construction knowledge with business training.", "year_label": "2005-2011"},
            {"stage": "first_job", "label": "Project manager at a large construction firm", "description": "Learned project delivery from the execution side before attempting his own development.", "year_label": "2011-2015"},
            {"stage": "failure", "label": "His first independent development project went 60% over budget", "description": "Underestimated material costs and construction delays, nearly bankrupting his newly founded company.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Restructured the company's financial planning with much larger contingency buffers", "description": "Rebuilt investor trust through transparent communication about what went wrong.", "year_label": "2017"},
            {"stage": "current_role", "label": "Founder and Managing Director", "description": "Has since completed several successful mixed-use developments.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "A mix of site visits, investor and contractor meetings, and financial review of active projects.",
        "weekly_routine": "Deal evaluation and project oversight woven throughout the week, with periodic intensive stretches during financing rounds.",
        "biggest_challenges": ["Accurately forecasting costs in a market with real, unpredictable price volatility", "Managing investor trust after a real setback"],
        "favourite_part": "Walking through a completed development and seeing families actually living in what was once just a financial model.",
        "biggest_misconceptions": ["That real estate development is purely about buying low and selling high", "That one catastrophic project failure ends a developer's career"],
        "what_surprised_them": "How much of development success is disciplined financial risk management, not just vision.",
        "biggest_mistake": "On my first project, I built financial projections with minimal contingency for cost overruns because I was overconfident and eager to move fast. The 60% overrun that followed nearly ended my company before it really started, and I now build substantial contingency into every project by default.",
        "one_regret": "I regret not consulting more experienced developers before that first project — their perspective on realistic contingency planning would have prevented my near-collapse.",
        "salary_reality": "Real estate development can be extremely lucrative once established, but the early years carry genuine, sometimes company-ending financial risk.",
        "work_life_balance": "Demanding, especially during active construction phases of a project.",
        "daily_skills": ["financial modeling", "project management", "negotiation"],
        "daily_tools": ["Financial modeling software", "project management platforms"],
        "recommended_books": ["The Real Estate Game by William Poorvu"],
        "recommended_communities": ["Dubai real estate developers network"],
        "advice_for_beginners": "Build far more financial contingency into your first project than feels necessary — my near-bankruptcy came from underestimating this exact risk.",
        "advice_for_parents": "A costly first business failure in a capital-intensive field like real estate is a real financial risk worth understanding, but it's also a common, survivable part of building genuine expertise.",
        "faqs": [{"question": "How risky is real estate development as a career?", "answer": "Genuinely risky, especially early on — proper financial contingency planning and mentorship from experienced developers meaningfully reduce that risk."}],
        "projects": ["Completed several mixed-use residential developments after recovering from an early near-collapse"], "research": [],
        "certifications": [], "conferences": [], "organizations": [],
        "volunteer_work": ["Mentors young developers on financial risk planning"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_wildlife_biologist_hannah_botha",
        "name": "Hannah Botha, Wildlife Biologist",
        "role_type": "researcher", "field": "wildlife biology", "bio": "Studies elephant migration patterns for a conservation research organization; her first major field study was ruined by an equipment failure that lost a year of data.",
        "trait_tags": ["curiosity", "persistence"], "learning_style_fit": "Students who love fieldwork and can handle real setbacks in remote, unpredictable conditions.",
        "organization": "A wildlife conservation research organization", "years_experience": 9, "journey_highlights": ["Lost a full year of field data to an equipment failure", "Her research now informs a national wildlife corridor policy"],
        "discussion_topics": ["Fieldwork realities in remote conservation research", "Recovering from a devastating research setback", "Wildlife biology as a career beyond zoos and documentaries"],
        "profession": "Wildlife Research Biologist", "specialization": "Elephant migration and habitat corridors", "country": "Botswana", "city": "Maun",
        "industries": ["environmental conservation", "research"], "education": ["BSc Zoology, University of Cape Town", "MSc Conservation Biology, University of Oxford"],
        "current_role": "Senior Research Biologist", "languages": ["English", "Afrikaans", "Setswana"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who love wildlife and want a real research career, not just documentary-style work", "Students who can handle setbacks in remote fieldwork conditions", "Students interested in conservation policy impact"],
        "career_ids": ["conservation_biologist"],
        "career_journey": [
            {"stage": "university", "label": "BSc Zoology, then MSc Conservation Biology", "description": "Focused her graduate research on large mammal migration tracking.", "year_label": "2010-2016"},
            {"stage": "first_job", "label": "Field researcher tracking elephant movement patterns", "description": "Spent months in remote field conditions collecting GPS collar data.", "year_label": "2016-2018"},
            {"stage": "failure", "label": "A GPS tracking system malfunction lost nearly a full year of migration data", "description": "The equipment failure went undetected for months in remote conditions, devastating a key part of her research timeline.", "year_label": "2018"},
            {"stage": "turning_point", "label": "Rebuilt the study with redundant tracking systems and more frequent remote monitoring checks", "description": "The redesigned methodology became more rigorous than the original.", "year_label": "2019"},
            {"stage": "current_role", "label": "Senior Research Biologist", "description": "Her research now directly informs a national wildlife corridor conservation policy.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Alternates between intense remote field expeditions and office-based data analysis and writing.",
        "weekly_routine": "Field seasons bring long, irregular days; office seasons are more standard analytical work.",
        "biggest_challenges": ["Equipment and logistics failures in extremely remote conditions", "The years-long timeline between fieldwork and policy impact"],
        "favourite_part": "Seeing her migration data directly influence a real conservation policy decision.",
        "biggest_misconceptions": ["That wildlife biology is mostly gentle animal-watching — it's rigorous, often physically demanding research", "That equipment failures reflect poorly on a researcher's competence"],
        "what_surprised_them": "How much of fieldwork success depends on redundant planning for equipment failure in remote conditions.",
        "biggest_mistake": "I relied on a single tracking system without adequate backup redundancy for that first study, and when it failed silently in the field, I didn't discover the data loss until months later. I now build multiple redundant monitoring systems into every field study, regardless of added cost.",
        "one_regret": "I regret not budgeting for backup equipment in that first study — the cost I tried to save led to a far more expensive year of lost data.",
        "salary_reality": "Wildlife research salaries in Botswana's conservation sector are modest, sustained mainly through international grant funding rather than steady institutional pay.",
        "work_life_balance": "Field seasons are physically demanding with long, irregular hours; office seasons offer more balance.",
        "daily_skills": ["field data collection", "GIS analysis", "wildlife tracking methodology"],
        "daily_tools": ["GPS tracking collars", "GIS mapping software", "camera traps"],
        "recommended_books": ["Elephant Memories by Cynthia Moss"],
        "recommended_communities": ["African wildlife research network"],
        "advice_for_beginners": "Build redundancy into any remote field equipment plan — a single point of failure cost me a full year of research data.",
        "advice_for_parents": "Wildlife biology is a real, rigorous research career with genuine policy impact, not just an outdoor hobby turned job.",
        "faqs": [{"question": "Is wildlife biology mostly fieldwork or lab/office work?", "answer": "Both, in alternating seasons — intense remote fieldwork followed by substantial data analysis and writing time."}],
        "projects": ["Research now informs a national wildlife corridor policy"], "research": ["Published research on elephant migration corridor use"],
        "certifications": [], "conferences": ["International Congress for Conservation Biology"], "organizations": [],
        "volunteer_work": ["Trains early-career researchers on remote fieldwork methodology"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch4).")


if __name__ == "__main__":
    asyncio.run(seed())
