"""Journey Stories — Technology & Product domain group (Connect Batch 2).
30 new composite Journey Stories across 6 careers already in the Career
Knowledge Base: AI Operations Specialist, Developer Relations Engineer,
Product-Led Growth Specialist, UX Researcher, Computational Linguist,
Health Informatics Specialist. Every entry is an illustrative composite
persona (`story_type="composite"`) — never a claim of a specific real
individual, per this batch's explicit honesty requirement. Deliberately
varied: not every story involves a career switch, gap year, or
uncertainty period — real distribution, not a checklist forced onto
every entry.

Run via: python -m aureon.scripts.seed_journey_stories_technology_and_product
Idempotent: safe to re-run (upsert on id).
"""

import asyncio

from aureon.domain.models.career import CareerStory
from aureon.services.supabase.client import get_supabase_client

STORIES: list[dict] = [
    # --- AI Operations Specialist ---------------------------------------
    {
        "id": "story_ai_ops_specialist_2", "career_id": "ai_ops_specialist",
        "person_label": "AI Reliability Engineer, 2 years experience",
        "background": "Left a computer science degree one exam short of graduating to take a contract role at a startup, planning to finish later.",
        "journey": "The contract role turned into a full-time AI operations job before the degree was finished, and they never went back to complete it.",
        "challenges": "Spent years quietly worried the missing degree would eventually block career growth, even as the work itself went well.",
        "turning_points": "Being hired into a senior role specifically for hands-on production experience, over more traditionally credentialed candidates, settled the question.",
        "advice": "A missing credential matters less in this field than in most — what you can demonstrably ship and debug speaks louder.",
        "lessons_learned": "Worrying about a credential gap cost more energy than the gap itself ever actually cost in real opportunities.",
        "trait_tags": ["analytical_thinking", "motivation"],
        "timeline": [
            {"stage": "university", "label": "Unfinished degree", "description": "Left a computer science degree one exam short to take a startup contract role.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Contract to full-time", "description": "The contract role became a full-time AI operations job.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Hired for experience over credentials", "description": "Was hired into a senior role specifically for hands-on production experience.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Years of quietly worrying an unfinished degree would eventually block career growth.",
        "current_outcome": "Works as an AI reliability engineer, credential concerns settled by real hiring outcomes.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ai_ops_specialist_3", "career_id": "ai_ops_specialist",
        "person_label": "ML Platform Specialist, 7 years experience",
        "background": "Spent the first five years of their career as a traditional backend engineer with no particular interest in machine learning.",
        "journey": "Was assigned, somewhat reluctantly, to support a team's first production ML model and ended up staying in that space permanently.",
        "challenges": "Found the shift from deterministic software bugs to probabilistic model behavior genuinely disorienting at first.",
        "turning_points": "Diagnosing a subtle data drift issue that had puzzled the ML team for weeks, using plain backend debugging instincts, proved the two skill sets combined well.",
        "advice": "You don't need to start as an ML specialist — strong general engineering instincts transfer more than people expect.",
        "lessons_learned": "The most valuable AI operations skill is often just rigorous, patient debugging, not deep model theory.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "first_job", "label": "Backend engineer", "description": "Worked as a traditional backend engineer with no particular interest in machine learning.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Assigned to an ML team", "description": "Was assigned, somewhat reluctantly, to support a team's first production ML model.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "Diagnosing data drift", "description": "Diagnosed a subtle data drift issue that had puzzled the ML team for weeks.", "year_label": "Year 6"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Specializes in ML platform reliability, applying backend debugging instincts to probabilistic systems.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ai_ops_specialist_4", "career_id": "ai_ops_specialist",
        "person_label": "AI Operations Specialist, 3 years experience",
        "background": "Took a year off after university, uncertain whether to pursue graduate school in statistics or enter industry directly.",
        "journey": "Used that year to work through open-source ML operations projects independently, which became the portfolio that got them hired without a graduate degree.",
        "challenges": "Faced real doubt during the gap year about whether self-directed learning would be taken seriously by employers.",
        "turning_points": "A hiring manager specifically citing their open-source contributions as the deciding factor validated the unconventional path.",
        "advice": "A gap year spent building something real and visible can substitute for formal credentials, but only if you can point to concrete output.",
        "lessons_learned": "Employers in this field often care more about demonstrated, inspectable work than about the path that produced it.",
        "trait_tags": ["motivation", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Graduating uncertain", "description": "Took a year off after university, uncertain between graduate school and industry.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Self-directed open-source work", "description": "Worked through open-source ML operations projects independently during the gap year.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Hired on the strength of the portfolio", "description": "A hiring manager cited the open-source contributions as the deciding hiring factor.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": True,
        "uncertainty_period": "A full gap year spent uncertain whether self-directed learning would be taken seriously by employers.",
        "current_outcome": "Works in AI operations, having proven a self-built portfolio can substitute for a graduate credential.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ai_ops_specialist_5", "career_id": "ai_ops_specialist",
        "person_label": "Senior AI Operations Specialist, 9 years experience",
        "background": "Started their career in IT infrastructure, managing servers long before machine learning became a mainstream production concern.",
        "journey": "Watched the infrastructure they managed gradually shift from web servers to model-serving systems as their company adopted AI over several years.",
        "challenges": "Repeatedly had to relearn fundamentals as the tooling around AI infrastructure changed faster than almost anything they'd worked with before.",
        "turning_points": "Leading the infrastructure side of a company-wide migration to a new model-serving platform established them as the team's go-to specialist.",
        "advice": "Infrastructure fundamentals age well — the tools change constantly, but the underlying reliability principles barely do.",
        "lessons_learned": "Staying useful in a fast-changing field is less about chasing every new tool and more about strong fundamentals applied to whatever's current.",
        "trait_tags": ["analytical_thinking", "work_preferences"],
        "timeline": [
            {"stage": "first_job", "label": "IT infrastructure", "description": "Started managing servers long before machine learning became a mainstream production concern.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Infrastructure shifts toward AI", "description": "Watched infrastructure gradually shift from web servers to model-serving systems.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Leading a platform migration", "description": "Led the infrastructure side of a company-wide migration to a new model-serving platform.", "year_label": "Year 8"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Serves as the team's senior AI infrastructure specialist, having grown into the role rather than switching into it abruptly.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ai_ops_specialist_6", "career_id": "ai_ops_specialist",
        "person_label": "AI Operations Specialist, 1 year experience",
        "background": "Entered the field straight out of a bootcamp after being laid off from an unrelated retail management job during a company downsizing.",
        "journey": "The layoff forced a fast, practical career pivot rather than a carefully planned one — the bootcamp was chosen mainly for its job-placement track record.",
        "challenges": "Felt significant financial pressure to become employable quickly, with little room for a slow, exploratory transition.",
        "turning_points": "Landing a junior AI operations role within three months of finishing the bootcamp relieved most of that pressure at once.",
        "advice": "A layoff-driven pivot doesn't have to be a weakness — motivated, fast learning under real pressure is its own credible signal.",
        "lessons_learned": "Career changes forced by circumstance can still lead somewhere genuinely better than the original path.",
        "trait_tags": ["motivation", "learning_style"],
        "timeline": [
            {"stage": "career_transition", "label": "Laid off from retail management", "description": "Was laid off from an unrelated retail management job during a company downsizing.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Bootcamp", "description": "Chose a bootcamp mainly for its job-placement track record, under financial pressure.", "year_label": "Year 0"},
            {"stage": "current_role", "label": "Junior AI Operations Specialist", "description": "Landed a junior role within three months of finishing the bootcamp.", "year_label": "Year 1"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "A financially pressured stretch after the layoff, with little room for a slow or exploratory transition.",
        "current_outcome": "Works in AI operations after a fast, circumstance-driven pivot that turned out better than the original career.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    # --- Developer Relations Engineer ------------------------------------
    {
        "id": "story_developer_relations_engineer_2", "career_id": "developer_relations_engineer",
        "person_label": "Developer Advocate, 5 years experience",
        "background": "Was an active open-source contributor as a hobby for years while working an unrelated day job in operations.",
        "journey": "A company noticed their open-source work and offered a developer relations role, which they took as a significant pay cut from operations management.",
        "challenges": "The pay cut created real financial strain in the first two years, and they seriously considered going back to their old field.",
        "turning_points": "A conference talk they gave, based on their open-source work, led directly to a promotion and a return to their previous salary level.",
        "advice": "A passion project can become a career, but be honest with yourself about whether you can absorb a real pay cut to make that leap.",
        "lessons_learned": "The hardest part of following a passion into a career is often the financial transition, not the skills gap.",
        "trait_tags": ["communication", "motivation"],
        "timeline": [
            {"stage": "first_job", "label": "Operations, open-source on the side", "description": "Worked in operations while contributing to open-source as a hobby.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Offered a DevRel role", "description": "A company noticed the open-source work and offered a developer relations role at a pay cut.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "A conference talk that mattered", "description": "A conference talk based on the open-source work led directly to a promotion.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Two years of real financial strain after taking a significant pay cut to move into developer relations.",
        "current_outcome": "Works as a developer advocate at their previous salary level, the pay cut having been temporary.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_developer_relations_engineer_3", "career_id": "developer_relations_engineer",
        "person_label": "Developer Relations Engineer, 2 years experience",
        "background": "Studied technical writing rather than computer science, assuming it would lead to a documentation-only role.",
        "journey": "Took a technical writing job at a developer tools company and gradually absorbed enough engineering skill from colleagues to move into full DevRel work.",
        "challenges": "Initially felt like an outsider in engineering-heavy rooms, unsure whether a writing background counted as a real technical qualification.",
        "turning_points": "Successfully debugging a sample project live during a workshop, unprompted, changed how engineering colleagues saw their technical credibility.",
        "advice": "A non-engineering background doesn't disqualify you from developer relations — the writing and communication skills are just as central as the code.",
        "lessons_learned": "Technical credibility in this field can be built gradually, on the job, rather than requiring a traditional computer science background upfront.",
        "trait_tags": ["communication", "learning_style"],
        "timeline": [
            {"stage": "university", "label": "Technical writing degree", "description": "Studied technical writing, assuming it would lead to a documentation-only role.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Technical writer", "description": "Took a technical writing job at a developer tools company.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Debugging live, unprompted", "description": "Debugged a sample project live during a workshop, changing how engineering colleagues saw their credibility.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Early uncertainty about whether a writing background counted as a real technical qualification.",
        "current_outcome": "Works in full developer relations, having built engineering credibility gradually rather than starting with it.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_developer_relations_engineer_4", "career_id": "developer_relations_engineer",
        "person_label": "Developer Relations Lead, 8 years experience",
        "background": "Spent the first four years of their career as a frustrated support engineer, repeatedly answering the same unresolved developer complaints.",
        "journey": "Proposed and built a completely new onboarding flow to reduce those repeated complaints, which became the pitch that got them moved into developer relations.",
        "challenges": "Had to convince skeptical leadership that fixing onboarding, not writing more support macros, was the actual solution to ticket volume.",
        "turning_points": "The new onboarding flow cut support tickets by a visible, measurable amount within the first quarter of launch.",
        "advice": "If you're frustrated by the same recurring problem in your current role, that frustration might be pointing at your next role.",
        "lessons_learned": "Some of the best developer relations work starts as a support engineer's frustration with a fixable, recurring problem.",
        "trait_tags": ["analytical_thinking", "leadership"],
        "timeline": [
            {"stage": "first_job", "label": "Support engineer", "description": "Spent four years repeatedly answering the same unresolved developer complaints.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Proposing a new onboarding flow", "description": "Proposed and built a new onboarding flow to reduce repeated support complaints.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Measurable ticket reduction", "description": "The new onboarding flow cut support tickets by a visible amount within one quarter.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Leads developer relations, having turned support-engineer frustration into a measurable product fix.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_developer_relations_engineer_5", "career_id": "developer_relations_engineer",
        "person_label": "Developer Relations Engineer, 4 years experience",
        "background": "Studied computer science with the singular goal of becoming a backend engineer at a large tech company, with no interest in public speaking.",
        "journey": "Was asked, somewhat against their will, to give an internal demo, discovered they genuinely enjoyed explaining technical concepts, and requested a transfer to DevRel a year later.",
        "challenges": "Struggled with real anxiety about public speaking for the first several talks, well after deciding this was the right direction.",
        "turning_points": "Watching an audience visibly understand a concept they'd struggled to explain in writing for months was the moment the anxiety felt worth pushing through.",
        "advice": "Don't rule out a field just because your current self is uncomfortable with a core skill it requires — comfort can be built.",
        "lessons_learned": "Enjoying a skill and being naturally comfortable with it are two different things, and only one of them is required to start.",
        "trait_tags": ["communication", "creativity"],
        "timeline": [
            {"stage": "university", "label": "Backend-focused CS degree", "description": "Studied computer science aiming specifically for backend engineering, with no interest in public speaking.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "An internal demo", "description": "Was asked to give an internal demo and discovered they enjoyed explaining technical concepts.", "year_label": "Year 1"},
            {"stage": "career_transition", "label": "Transfer to DevRel", "description": "Requested a transfer to developer relations a year after the demo.", "year_label": "Year 2"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Real public-speaking anxiety through the first several talks, even after deciding DevRel was the right direction.",
        "current_outcome": "Works in developer relations, having built comfort with public speaking rather than starting with it.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_developer_relations_engineer_6", "career_id": "developer_relations_engineer",
        "person_label": "Principal Developer Advocate, 11 years experience",
        "background": "Worked across three different engineering roles at three different companies before finding developer relations, each move driven by mild dissatisfaction rather than a clear plan.",
        "journey": "Only recognized the throughline after the fact — every role they'd genuinely enjoyed had involved teaching or explaining something to someone else.",
        "challenges": "Spent years without a clear career narrative, which made job interviews and performance reviews genuinely difficult to frame.",
        "turning_points": "A mentor explicitly naming the teaching pattern across their past roles was the first time the career path made sense as a coherent story.",
        "advice": "If your career looks scattered, look for what you actually enjoyed in each role rather than what the job titles suggest it should be.",
        "lessons_learned": "A career doesn't need a clean narrative in the moment — the coherent throughline is sometimes only visible in hindsight.",
        "trait_tags": ["curiosity", "communication"],
        "timeline": [
            {"stage": "first_job", "label": "Three engineering roles, three companies", "description": "Moved across three different engineering roles, each driven by mild dissatisfaction rather than a clear plan.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A mentor names the pattern", "description": "A mentor named the teaching pattern running across their past roles.", "year_label": "Year 7"},
            {"stage": "career_transition", "label": "Deliberate move into DevRel", "description": "Deliberately moved into developer relations once the pattern was clear.", "year_label": "Year 8"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Years without a clear career narrative, making interviews and performance reviews genuinely difficult.",
        "current_outcome": "Works as a principal developer advocate, the scattered early career now understood as consistent teaching instinct.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    # --- Product-Led Growth Specialist ------------------------------------
    {
        "id": "story_product_led_growth_specialist_1", "career_id": "product_led_growth_specialist",
        "person_label": "Product-Led Growth Specialist, 4 years experience",
        "background": "Studied marketing and expected to work in traditional brand advertising after graduation.",
        "journey": "Took an entry-level growth marketing role at a software company almost by accident and discovered product-led growth as a discipline distinct from advertising.",
        "challenges": "Had to unlearn brand-marketing instincts that didn't translate to a discipline built around product usage data, not campaigns.",
        "turning_points": "Running their first successful in-product experiment, with measurable signup impact, made the shift from campaign thinking to product thinking click.",
        "advice": "If you come from traditional marketing, expect to relearn your instincts around data and experimentation, not just the vocabulary.",
        "lessons_learned": "Product-led growth rewards a scientific, testing mindset far more than the creative instincts traditional marketing prizes.",
        "trait_tags": ["analytical_thinking", "creativity"],
        "timeline": [
            {"stage": "university", "label": "Marketing degree", "description": "Studied marketing expecting to work in traditional brand advertising.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Growth marketing, almost by accident", "description": "Took an entry-level growth marketing role at a software company.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "First successful in-product experiment", "description": "Ran a successful in-product experiment with measurable signup impact.", "year_label": "Year 2"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Specializes in product-led growth, having replaced campaign instincts with an experimentation mindset.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_product_led_growth_specialist_2", "career_id": "product_led_growth_specialist",
        "person_label": "Growth Product Manager, 6 years experience",
        "background": "Started as a data analyst, pulling growth metrics for a product team without much say in what got built.",
        "journey": "Kept proposing product changes based on the data they were reporting, and the team eventually created a dedicated growth role around that instinct.",
        "challenges": "Faced real skepticism from a product team that saw growth experimentation as secondary to the core roadmap.",
        "turning_points": "A single onboarding change, proposed from the data, increased activation rate enough that leadership formally funded a growth team.",
        "advice": "If you're in an analyst role and keep seeing product opportunities in the data, start proposing them — the role you want might not exist yet.",
        "lessons_learned": "Sometimes the fastest way into a role is demonstrating the work before the title exists to describe it.",
        "trait_tags": ["analytical_thinking", "motivation"],
        "timeline": [
            {"stage": "first_job", "label": "Data analyst", "description": "Pulled growth metrics for a product team without much say in what got built.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Proposing product changes", "description": "Kept proposing product changes based on the data being reported.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "A funded growth team", "description": "A proposed onboarding change increased activation enough that leadership funded a dedicated growth team.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Leads growth product work, having created the role through demonstrated results before it formally existed.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_product_led_growth_specialist_3", "career_id": "product_led_growth_specialist",
        "person_label": "Product-Led Growth Specialist, 3 years experience",
        "background": "Left a graduate economics program after one year, uncertain whether academic research was actually the right fit.",
        "journey": "Took a break to work retail while deciding on next steps, then found a growth analyst role that used the same statistical thinking from the abandoned program.",
        "challenges": "Felt significant uncertainty during the retail period about whether leaving the graduate program had been a mistake.",
        "turning_points": "Realizing the statistical methods from their unfinished coursework applied directly to product experimentation reframed the program as useful, not wasted.",
        "advice": "An unfinished path isn't automatically wasted time — the skills sometimes transfer to a field you haven't considered yet.",
        "lessons_learned": "What looks like an abandoned direction can still supply the exact skill set a very different field turns out to need.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Graduate economics, unfinished", "description": "Left a graduate economics program after one year, uncertain about academic research.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Retail while deciding", "description": "Worked retail while deciding on next steps.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Statistics apply to growth", "description": "Realized statistical methods from unfinished coursework applied directly to product experimentation.", "year_label": "Year 2"},
        ],
        "career_switch": True, "gap_year": True,
        "uncertainty_period": "A period working retail after leaving graduate school, uncertain whether leaving had been a mistake.",
        "current_outcome": "Works in product-led growth, applying statistical training from an unfinished graduate program.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_product_led_growth_specialist_4", "career_id": "product_led_growth_specialist",
        "person_label": "Senior Product-Led Growth Specialist, 7 years experience",
        "background": "Was a founding, non-technical member of a startup that eventually failed after three years, then had to rebuild a career from that experience.",
        "journey": "Took the growth lessons from watching their own startup's user funnel collapse and applied them, this time as an employee, at a larger company.",
        "challenges": "Carried real self-doubt after the startup's failure about whether they had anything valuable to offer a larger, more established company.",
        "turning_points": "Being explicitly hired for having lived through a failed funnel, not despite it, reframed the failure as direct, hard-won expertise.",
        "advice": "A failed startup isn't disqualifying experience — the specific, painful lessons from watching something not work are genuinely valuable elsewhere.",
        "lessons_learned": "Failure at one company can become exactly the credibility a different company is looking to hire for.",
        "trait_tags": ["motivation", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Startup founding member", "description": "Was a founding, non-technical member of a startup.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Startup fails", "description": "The startup failed after three years.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Hired for the failure itself", "description": "Was hired at a larger company explicitly because of the lessons from the failed funnel.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Real self-doubt after the startup's failure about having anything valuable left to offer.",
        "current_outcome": "Works as a senior growth specialist, the startup's failure now treated as direct professional expertise.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_product_led_growth_specialist_5", "career_id": "product_led_growth_specialist",
        "person_label": "Product-Led Growth Specialist, 2 years experience",
        "background": "Studied computer science and expected to become a software engineer, with no plans around marketing or growth.",
        "journey": "Took a summer internship on a growth engineering team, building the technical side of experiments, and realized the intersection of code and user behavior interested them more than pure engineering.",
        "challenges": "Faced confusion from peers and family about why they were choosing a less conventional path than a straightforward engineering role.",
        "turning_points": "Shipping an experiment that meaningfully changed a real user behavior metric, and seeing the data prove it, was more satisfying than any pure engineering task had been.",
        "advice": "Try an internship or rotation outside your expected track before committing — the intersection roles are easy to miss from the outside.",
        "lessons_learned": "The most satisfying part of a technical skill set can turn out to be a use of it you hadn't originally planned for.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Computer science degree", "description": "Studied computer science expecting to become a software engineer.", "year_label": "Year 0"},
            {"stage": "internship", "label": "Growth engineering internship", "description": "Interned on a growth engineering team, building the technical side of experiments.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "An experiment that moved a metric", "description": "Shipped an experiment that meaningfully changed a real user behavior metric.", "year_label": "Year 1"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works in product-led growth, having found the intersection of code and user behavior more compelling than pure engineering.",
        "industry": "technology", "story_type": "composite", "source_reference": "",
    },
    # --- UX Researcher ------------------------------------------------------
    {
        "id": "story_ux_researcher_2", "career_id": "ux_researcher",
        "person_label": "UX Researcher, 3 years experience",
        "background": "Trained as an anthropologist, expecting an academic career studying communities in the field.",
        "journey": "Left academia after struggling to secure a permanent research position and found that UX research used nearly identical fieldwork and interview skills.",
        "challenges": "Grieved the loss of the academic path for over a year before feeling genuinely committed to the corporate research alternative.",
        "turning_points": "Conducting their first user interview and recognizing the exact same skill of drawing out honest, unguarded answers reassured them the transition wasn't a downgrade.",
        "advice": "Academic fieldwork skills transfer more directly to UX research than most people expect — the setting changes, the craft doesn't.",
        "lessons_learned": "Leaving an original career plan doesn't mean abandoning the skills you built for it — often it's the opposite.",
        "trait_tags": ["curiosity", "communication"],
        "timeline": [
            {"stage": "university", "label": "Anthropology PhD", "description": "Trained as an anthropologist expecting an academic career.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Leaving academia", "description": "Left academia after struggling to secure a permanent research position.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "First user interview", "description": "Recognized the same fieldwork skill of drawing out honest answers in a corporate interview setting.", "year_label": "Year 6"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Over a year grieving the lost academic path before feeling committed to UX research.",
        "current_outcome": "Works as a UX researcher, applying anthropological fieldwork skills to product research.",
        "industry": "technology & design", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ux_researcher_3", "career_id": "ux_researcher",
        "person_label": "UX Researcher, 5 years experience",
        "background": "Worked as a customer support representative for two years, hearing the same product complaints repeatedly with no formal channel to escalate them.",
        "journey": "Started informally documenting recurring complaints, which caught a product manager's attention and led to an internal move into research.",
        "challenges": "Had no formal research training and had to learn interview and synthesis methods largely through self-study while already doing the job.",
        "turning_points": "A synthesis report they wrote, based purely on support-ticket patterns, directly shaped a major product redesign.",
        "advice": "If you're closest to users in a support role, your informal pattern-spotting might already be research — it just needs a formal outlet.",
        "lessons_learned": "Some of the most useful research insight comes from roles that sit closest to frustrated users, not formal research teams.",
        "trait_tags": ["communication", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "Customer support representative", "description": "Heard the same product complaints repeatedly with no formal escalation channel.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Documenting patterns informally", "description": "Started informally documenting recurring complaints, catching a product manager's attention.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A synthesis report that shaped a redesign", "description": "A synthesis report based on support-ticket patterns directly shaped a major product redesign.", "year_label": "Year 2"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a UX researcher, having formalized pattern-spotting skills built in a support role.",
        "industry": "technology & design", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ux_researcher_4", "career_id": "ux_researcher",
        "person_label": "Senior UX Researcher, 8 years experience",
        "background": "Was laid off from a research role during a company-wide restructuring after four years, with no immediate job offers lined up.",
        "journey": "Spent five months freelancing small research projects for startups that couldn't afford a full-time researcher, before landing a senior role.",
        "challenges": "Faced significant financial stress during the freelance stretch, taking on projects below their experience level just to stay afloat.",
        "turning_points": "One freelance client's product succeeding partly on the strength of their research became a portfolio piece that opened doors the layoff had closed.",
        "advice": "A layoff doesn't erase your expertise — freelance work, even below your level, can rebuild both income and a stronger portfolio.",
        "lessons_learned": "A forced gap between roles can be used deliberately to build proof of impact that a steady job rarely generates as clearly.",
        "trait_tags": ["motivation", "curiosity"],
        "timeline": [
            {"stage": "first_job", "label": "Research role, laid off", "description": "Was laid off during a company-wide restructuring after four years.", "year_label": "Year 4"},
            {"stage": "career_transition", "label": "Freelance research", "description": "Spent five months freelancing small research projects for startups.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "A client's product succeeds", "description": "A freelance client's product succeeded partly on the strength of their research.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Five months of freelance work under real financial stress after an unexpected layoff.",
        "current_outcome": "Works as a senior UX researcher, the layoff having become an unplanned but effective portfolio-building period.",
        "industry": "technology & design", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ux_researcher_5", "career_id": "ux_researcher",
        "person_label": "UX Researcher, 4 years experience",
        "background": "Studied journalism and worked as a local news reporter for three years before the local paper's newsroom was significantly downsized.",
        "journey": "Applied the interviewing and story-synthesis skills from journalism directly to a UX research role at a mid-sized tech company.",
        "challenges": "Struggled initially to translate journalistic storytelling into the more structured, method-driven format research stakeholders expected.",
        "turning_points": "A hiring manager explicitly telling them their reporter's interviewing instincts were rarer and more valuable than a research degree reframed the transition.",
        "advice": "Journalism and UX research share more DNA than it looks like from the outside — both are about drawing out honest human accounts.",
        "lessons_learned": "A shrinking industry doesn't necessarily waste the core skills built within it — those skills can transfer to a growing one.",
        "trait_tags": ["communication", "curiosity"],
        "timeline": [
            {"stage": "first_job", "label": "Local news reporter", "description": "Worked as a local news reporter for three years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Newsroom downsizing", "description": "The local paper's newsroom was significantly downsized.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Interviewing instincts valued", "description": "A hiring manager explicitly valued their reporter's interviewing instincts over a research degree.", "year_label": "Year 3"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a UX researcher, having carried journalistic interviewing instincts into a structured research practice.",
        "industry": "technology & design", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ux_researcher_6", "career_id": "ux_researcher",
        "person_label": "UX Research Lead, 10 years experience",
        "background": "Began as a market researcher doing quantitative survey work, with no exposure to qualitative interviewing methods.",
        "journey": "Gradually shifted from purely quantitative surveys to mixed-methods research as the company's product team grew and needed deeper qualitative insight.",
        "challenges": "Had to unlearn a preference for large sample sizes and statistical significance in favor of the smaller, deeper qualitative studies UX work often needs.",
        "turning_points": "A five-person qualitative study surfacing a usability problem that a thousand-person survey had completely missed changed how they weighed the two methods.",
        "advice": "Don't assume a quantitative background is a mismatch for UX research — it becomes a real strength once paired with qualitative methods.",
        "lessons_learned": "Rigor in research isn't defined by sample size — a small, well-run qualitative study can reveal what a large survey structurally can't.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "first_job", "label": "Quantitative market researcher", "description": "Did quantitative survey work with no exposure to qualitative interviewing.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Shift to mixed methods", "description": "Gradually shifted to mixed-methods research as the product team grew.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Five people beat a thousand", "description": "A five-person qualitative study surfaced a problem a thousand-person survey had missed.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Leads UX research combining quantitative rigor with qualitative depth, rather than treating them as opposed.",
        "industry": "technology & design", "story_type": "composite", "source_reference": "",
    },
    # --- Computational Linguist -----------------------------------------
    {
        "id": "story_computational_linguist_1", "career_id": "computational_linguist",
        "person_label": "Computational Linguist, 4 years experience",
        "background": "Studied linguistics with a focus on endangered language documentation, expecting a purely academic career.",
        "journey": "Applied linguistic documentation methods to a natural language processing project for underrepresented languages, discovering an industry role that used the same expertise.",
        "challenges": "Had to learn programming largely from scratch in their late twenties, well after most peers in the technical field had already built those skills.",
        "turning_points": "Building a working translation tool for a language with almost no digital resources proved the linguistics expertise, not just the coding, was the scarce skill.",
        "advice": "Deep expertise in an underrepresented language is a genuinely rare asset in computational linguistics — don't assume coding skill alone competes with it.",
        "lessons_learned": "Specialized academic knowledge can be the differentiator in a technical field, even when the technical skills themselves are learned later and more slowly.",
        "trait_tags": ["curiosity", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Endangered language documentation", "description": "Studied linguistics with a focus on endangered language documentation.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Learning to program", "description": "Learned programming largely from scratch well after most technical peers.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A translation tool from nothing", "description": "Built a working translation tool for a language with almost no digital resources.", "year_label": "Year 3"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a computational linguist, treating deep language expertise as the scarce skill technical training alone can't replace.",
        "industry": "technology & language", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_computational_linguist_2", "career_id": "computational_linguist",
        "person_label": "Computational Linguist, 6 years experience",
        "background": "Grew up multilingual and studied computer science, initially planning a generic software engineering career.",
        "journey": "Took a graduate elective in natural language processing almost as an afterthought and found it combined both halves of their background for the first time.",
        "challenges": "Faced a genuinely uncertain job market early on, since computational linguistics roles were far less common than general software roles.",
        "turning_points": "Landing a research assistantship specifically focused on low-resource multilingual models gave the uncertain path its first concrete direction.",
        "advice": "A niche combination of skills can feel like a liability in a thin job market, until you find the specific role built for exactly that combination.",
        "lessons_learned": "Being multilingual and technical is a genuinely rare pairing — the right role for it just takes longer to find than a generic one would.",
        "trait_tags": ["curiosity", "learning_style"],
        "timeline": [
            {"stage": "university", "label": "Computer science, multilingual background", "description": "Studied computer science, initially planning a generic software engineering career.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "An NLP elective", "description": "Took a graduate NLP elective almost as an afterthought, combining both halves of their background.", "year_label": "Year 2"},
            {"stage": "career_transition", "label": "Research assistantship", "description": "Landed a research assistantship focused on low-resource multilingual models.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "An uncertain early job market, since computational linguistics roles were far less common than general software roles.",
        "current_outcome": "Works as a computational linguist specializing in multilingual, low-resource language models.",
        "industry": "technology & language", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_computational_linguist_3", "career_id": "computational_linguist",
        "person_label": "Computational Linguist, 3 years experience",
        "background": "Worked as a professional translator for five years before machine translation tools began visibly affecting demand for the work.",
        "journey": "Rather than compete against the tools, took a graduate certificate in computational linguistics to work on building and evaluating them instead.",
        "challenges": "Felt real anxiety watching a stable, decade-long career path shrink due to the very technology they were now choosing to work on.",
        "turning_points": "Being hired specifically to evaluate translation quality — using the exact judgment their translation career had built — reframed the shift as a continuation, not a defeat.",
        "advice": "If automation is affecting your field, consider working on the systems themselves rather than only competing against them.",
        "lessons_learned": "Deep domain expertise in a field being automated often becomes exactly what's needed to build and evaluate the automation well.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Professional translator", "description": "Worked as a professional translator for five years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Machine translation affects demand", "description": "Machine translation tools began visibly affecting demand for translation work.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "Hired to evaluate translation quality", "description": "Was hired specifically to evaluate translation quality using their translation-honed judgment.", "year_label": "Year 6"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Real anxiety watching a decade-long translation career shrink due to the technology they were about to start working on.",
        "current_outcome": "Works as a computational linguist evaluating translation systems, using expertise the same technology once threatened.",
        "industry": "technology & language", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_computational_linguist_4", "career_id": "computational_linguist",
        "person_label": "Computational Linguist, 7 years experience",
        "background": "Pursued a PhD in theoretical syntax, expecting a traditional academic linguistics career.",
        "journey": "Left academia after struggling for two years to find a permanent faculty position, and moved into industry NLP work using the same formal grammar expertise.",
        "challenges": "Initially saw the industry move as a step down from the academic path they'd spent nearly a decade preparing for.",
        "turning_points": "Realizing their theoretical syntax training gave them an edge other industry NLP engineers lacked, in diagnosing subtle model grammar errors, shifted that perception.",
        "advice": "Deep theoretical training isn't wasted outside academia — it often becomes a distinguishing edge in applied roles that need that depth.",
        "lessons_learned": "A field that looks like a step down can turn out to specifically need the depth an academic path built, just applied differently.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "PhD in theoretical syntax", "description": "Pursued a PhD expecting a traditional academic linguistics career.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Leaving academia", "description": "Left academia after two years struggling to find a permanent faculty position.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "Theoretical training becomes an edge", "description": "Realized theoretical syntax training gave them an edge diagnosing subtle model grammar errors.", "year_label": "Year 7"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Two years struggling to find a permanent academic position before moving to industry.",
        "current_outcome": "Works as a computational linguist, applying theoretical syntax expertise to diagnosing model errors most engineers miss.",
        "industry": "technology & language", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_computational_linguist_5", "career_id": "computational_linguist",
        "person_label": "Computational Linguist, 2 years experience",
        "background": "Studied both linguistics and data science as a double major, deliberately planning to work at the intersection from the start.",
        "journey": "Took an internship in a language model evaluation team during university and converted it directly into a full-time role after graduation.",
        "challenges": "Had to prove to skeptical interviewers that a double major meant genuine depth in both fields, not a shallow spread across two.",
        "turning_points": "A technical assessment specifically designed to test both linguistic and statistical reasoning, which they passed clearly, settled that skepticism.",
        "advice": "If you deliberately build an unusual double-major combination, be ready to actively prove its depth — interviewers will assume it's a compromise until shown otherwise.",
        "lessons_learned": "A deliberately chosen interdisciplinary path still has to be actively defended, not just assumed to speak for itself.",
        "trait_tags": ["analytical_thinking", "learning_style"],
        "timeline": [
            {"stage": "university", "label": "Double major", "description": "Studied both linguistics and data science, deliberately planning to work at the intersection.", "year_label": "Year 0"},
            {"stage": "internship", "label": "Language model evaluation", "description": "Interned on a language model evaluation team during university.", "year_label": "Year 3"},
            {"stage": "current_role", "label": "Computational Linguist", "description": "Converted the internship directly into a full-time role after graduation.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a computational linguist, the deliberately planned double major now proven rather than just assumed.",
        "industry": "technology & language", "story_type": "composite", "source_reference": "",
    },
    # --- Health Informatics Specialist -----------------------------------
    {
        "id": "story_health_informatics_specialist_1", "career_id": "health_informatics_specialist",
        "person_label": "Health Informatics Specialist, 5 years experience",
        "background": "Worked as a registered nurse for six years before growing frustrated with the electronic health record system used at every hospital they worked in.",
        "journey": "Went back to school part-time for a health informatics certificate while still working full-time as a nurse, then moved into a hybrid clinical-technical role.",
        "challenges": "Balancing full-time nursing shifts with part-time coursework left almost no time for rest over nearly two years.",
        "turning_points": "Being asked to consult on a hospital-wide electronic health record redesign, specifically because of their nursing background, validated the exhausting transition.",
        "advice": "Clinical experience is a genuine asset in health informatics, not something to leave behind — the best systems are designed by people who've used the bad ones.",
        "lessons_learned": "Frustration with a broken system, if you stay with it, can become the exact expertise needed to help fix it.",
        "trait_tags": ["analytical_thinking", "motivation"],
        "timeline": [
            {"stage": "first_job", "label": "Registered nurse", "description": "Worked as a nurse for six years, growing frustrated with electronic health record systems.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Part-time informatics certificate", "description": "Went back to school part-time for a health informatics certificate while working full-time.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "Consulting on a system redesign", "description": "Was asked to consult on a hospital-wide electronic health record redesign because of their nursing background.", "year_label": "Year 8"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Nearly two exhausting years balancing full-time nursing shifts with part-time informatics coursework.",
        "current_outcome": "Works in health informatics in a hybrid clinical-technical role, treating clinical experience as central, not peripheral.",
        "industry": "healthcare & technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_health_informatics_specialist_2", "career_id": "health_informatics_specialist",
        "person_label": "Health Informatics Specialist, 3 years experience",
        "background": "Studied computer science with no particular interest in healthcare, planning a general software engineering career.",
        "journey": "Took a first job at a health technology company mainly because it was the best offer available, and grew genuinely interested in the domain over the following year.",
        "challenges": "Had to learn an enormous amount of clinical and regulatory context that had nothing to do with their technical training.",
        "turning_points": "Sitting in on a clinician's workflow for a full week, observing exactly where the software slowed them down, reframed the work as solving real human problems, not abstract technical ones.",
        "advice": "A first job taken for practical reasons can still turn into a genuine calling — give the domain a real chance before assuming it was just a placeholder.",
        "lessons_learned": "Interest in a field can develop after joining it, not only before — the work itself can be what creates the passion.",
        "trait_tags": ["curiosity", "learning_style"],
        "timeline": [
            {"stage": "university", "label": "Computer science degree", "description": "Studied computer science with no particular interest in healthcare.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Health technology company", "description": "Took a first job at a health technology company mainly for practical reasons.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A week observing clinical workflow", "description": "Sat in on a clinician's workflow for a full week, seeing exactly where software slowed them down.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works in health informatics, having developed genuine domain interest on the job rather than beforehand.",
        "industry": "healthcare & technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_health_informatics_specialist_3", "career_id": "health_informatics_specialist",
        "person_label": "Health Informatics Specialist, 8 years experience",
        "background": "Worked in hospital IT support for years, largely resetting passwords and fixing printers, with no clear path to more meaningful work.",
        "journey": "Volunteered for an unpopular data migration project nobody else wanted, and used it to build genuine expertise in clinical data systems.",
        "challenges": "The migration project was widely seen as thankless and career-stalling by colleagues, who advised against taking it on.",
        "turning_points": "Successfully completing the migration without the data-loss incidents leadership had feared made them the obvious internal expert for the next major system project.",
        "advice": "The unpopular, unglamorous project nobody wants can be exactly the opportunity that builds real expertise no one else has.",
        "lessons_learned": "Career advancement sometimes comes from taking on the work others actively avoid, not from waiting for the visible opportunities.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "Hospital IT support", "description": "Worked in hospital IT support with no clear path to more meaningful work.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Volunteering for a data migration", "description": "Volunteered for an unpopular data migration project nobody else wanted.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "A migration without incidents", "description": "Successfully completed the migration without the feared data-loss incidents.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as the internal expert for major clinical data system projects, built from a project no one else wanted.",
        "industry": "healthcare & technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_health_informatics_specialist_4", "career_id": "health_informatics_specialist",
        "person_label": "Health Informatics Specialist, 4 years experience",
        "background": "Was pursuing a medical degree and withdrew after two years, realizing clinical practice itself wasn't the right fit despite genuine interest in healthcare.",
        "journey": "Used the medical coursework as a foundation for a health informatics master's program, entering the field from a clinical-adjacent rather than clinical path.",
        "challenges": "Faced difficult conversations with family about leaving medical school after such a significant early investment of time and expectation.",
        "turning_points": "Realizing during a systems-design course that they could still meaningfully improve patient care without direct clinical practice reframed the withdrawal as a redirection, not a failure.",
        "advice": "Leaving a demanding path partway through isn't wasted time if you can identify what part of the original goal is still reachable a different way.",
        "lessons_learned": "There's often more than one route to the underlying goal that drew you to a field in the first place.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Medical school, withdrawn", "description": "Withdrew from medical school after two years, realizing clinical practice wasn't the right fit.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Health informatics master's", "description": "Used medical coursework as a foundation for a health informatics master's program.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Improving care without practicing", "description": "Realized during a systems-design course they could improve patient care without direct clinical practice.", "year_label": "Year 3"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Difficult conversations with family after leaving medical school partway through.",
        "current_outcome": "Works in health informatics, having found a route to improving patient care that doesn't require clinical practice.",
        "industry": "healthcare & technology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_health_informatics_specialist_5", "career_id": "health_informatics_specialist",
        "person_label": "Health Informatics Specialist, 6 years experience",
        "background": "Studied public health with a focus on epidemiology, expecting a career in disease surveillance or public health research.",
        "journey": "Took a role building the data systems behind a regional disease surveillance program, discovering the informatics side interested them as much as the epidemiology itself.",
        "challenges": "Found the technical, systems-building side of the work far less familiar than the statistical and epidemiological training they'd built in school.",
        "turning_points": "A data system they built helping catch an outbreak pattern earlier than manual review would have was the moment the technical work felt as consequential as the science.",
        "advice": "Public health training doesn't lock you into research or field epidemiology — the data infrastructure behind it is its own genuinely impactful specialty.",
        "lessons_learned": "The systems supporting public health work can matter as much as the research itself, and both draw on the same underlying training.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "university", "label": "Epidemiology degree", "description": "Studied public health with a focus on epidemiology.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Disease surveillance data systems", "description": "Built the data systems behind a regional disease surveillance program.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Catching an outbreak pattern early", "description": "A data system they built helped catch an outbreak pattern earlier than manual review would have.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works in health informatics, treating the data infrastructure behind public health as its own consequential specialty.",
        "industry": "healthcare & technology", "story_type": "composite", "source_reference": "",
    },
]


async def seed() -> None:
    client = get_supabase_client()
    stories = [CareerStory.model_validate(s) for s in STORIES]

    def _upsert() -> None:
        client.table("career_stories").upsert(
            [s.model_dump(mode="json") for s in stories]
        ).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(stories)} technology & product Journey Stories.")


if __name__ == "__main__":
    asyncio.run(seed())
