"""Journey Stories — Science & Research domain group (Connect Batch 2).
30 new composite Journey Stories across 6 careers: Genomics Data
Scientist, Bioinformatics Scientist, Materials Science Research
Scientist, Neuroscience Postdoctoral Researcher, Clinical Research
Coordinator, Space Systems Engineer. Every entry is an illustrative
composite persona (`story_type="composite"`) — never a claim of a
specific real individual.

Run via: python -m aureon.scripts.seed_journey_stories_science_and_research
Idempotent: safe to re-run (upsert on id).
"""

import asyncio

from aureon.domain.models.career import CareerStory
from aureon.services.supabase.client import get_supabase_client

STORIES: list[dict] = [
    # --- Genomics Data Scientist ------------------------------------------
    {
        "id": "story_genomics_data_scientist_2", "career_id": "genomics_data_scientist",
        "person_label": "Genomics Data Scientist, 3 years experience",
        "background": "Studied pure mathematics with no biology background, planning a career in quantitative finance.",
        "journey": "Took a data science bootcamp after growing disillusioned with finance, and a genomics lab hired them specifically for strong statistics rather than biology knowledge.",
        "challenges": "Spent the first year constantly looking up basic biological terms colleagues used casually in meetings.",
        "turning_points": "A senior biologist explicitly telling them their outsider statistical rigor had caught an error the biology team had missed built real confidence in the switch.",
        "advice": "You don't need a biology background to contribute meaningfully to genomics — rigorous statistics is its own form of essential expertise.",
        "lessons_learned": "Being the person who doesn't take domain assumptions for granted can be a genuine asset, not just a knowledge gap to apologize for.",
        "trait_tags": ["analytical_thinking", "learning_style"],
        "timeline": [
            {"stage": "university", "label": "Pure mathematics degree", "description": "Studied pure mathematics planning a career in quantitative finance.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Bootcamp after disillusionment with finance", "description": "Took a data science bootcamp after growing disillusioned with finance.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Outsider rigor catches an error", "description": "A senior biologist credited their statistical rigor with catching an error the biology team missed.", "year_label": "Year 3"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a genomics data scientist, contributing statistical rigor without a formal biology background.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_genomics_data_scientist_3", "career_id": "genomics_data_scientist",
        "person_label": "Genomics Data Scientist, 6 years experience",
        "background": "A family member's rare genetic disorder diagnosis during university reshaped an original plan to study general computer science.",
        "journey": "Switched majors to bioinformatics specifically to understand the disorder better, then pursued genomics data science as a direct continuation of that motivation.",
        "challenges": "Found it emotionally difficult at times to work professionally in a field so personally connected to their family's experience.",
        "turning_points": "Contributing to a research project studying a related genetic condition, years later, connected the personal motivation directly to real scientific output.",
        "advice": "A deeply personal reason for entering a field is a legitimate, sustaining motivation — it doesn't need to be purely academic curiosity.",
        "lessons_learned": "Work that stays connected to a genuine personal stake can sustain motivation through the field's inevitable difficult stretches.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "university", "label": "Switching to bioinformatics", "description": "Switched majors to bioinformatics after a family member's rare genetic disorder diagnosis.", "year_label": "Year 1"},
            {"stage": "first_job", "label": "Genomics data science", "description": "Pursued genomics data science as a continuation of that motivation.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Research on a related condition", "description": "Contributed to a research project studying a related genetic condition.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works in genomics data science, professionally connected to the personal motivation that started the path.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_genomics_data_scientist_4", "career_id": "genomics_data_scientist",
        "person_label": "Genomics Data Scientist, 2 years experience",
        "background": "Took two years off after an undergraduate biology degree, uncertain whether to pursue medical school, a PhD, or industry work.",
        "journey": "Worked as a lab technician during that period, which exposed them to genomics data analysis and clarified industry data science as the right direction.",
        "challenges": "Faced repeated questions from family about the extended uncertainty and lack of a clear next step during those two years.",
        "turning_points": "Being asked, as a technician, to help analyze a dataset no one else had time for gave a first real taste of the data science side of genomics.",
        "advice": "A genuinely uncertain stretch between degree and career isn't wasted if you use it to get exposure to different possible directions.",
        "lessons_learned": "Sometimes clarity about a career direction only comes from direct exposure to the day-to-day work, not from planning in the abstract.",
        "trait_tags": ["curiosity", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Undergraduate biology, uncertain next step", "description": "Took two years off after a biology degree, uncertain between medical school, a PhD, or industry.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Lab technician", "description": "Worked as a lab technician during the uncertain period.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A dataset no one else had time for", "description": "Was asked to help analyze a dataset, getting a first real taste of genomics data science.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": True,
        "uncertainty_period": "Two years genuinely uncertain between medical school, a PhD, and industry work.",
        "current_outcome": "Works as a genomics data scientist, the direction clarified by hands-on exposure rather than abstract planning.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_genomics_data_scientist_5", "career_id": "genomics_data_scientist",
        "person_label": "Senior Genomics Data Scientist, 9 years experience",
        "background": "Completed a PhD studying a narrow topic in plant genomics with no initial interest in human health applications.",
        "journey": "Was recruited to a human genomics company specifically because the statistical methods from plant genomics transferred directly to their work.",
        "challenges": "Initially worried a plant biology background would be seen as irrelevant, or even a liability, in a human health context.",
        "turning_points": "Successfully adapting a plant genomics statistical method to solve a stalled human genomics problem proved the transferability the recruiter had bet on.",
        "advice": "Statistical and computational methods often transfer across biological domains more readily than the domain knowledge itself.",
        "lessons_learned": "A narrow academic specialty can apply in unexpected adjacent fields, especially at the level of method rather than subject matter.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "PhD in plant genomics", "description": "Completed a PhD in a narrow plant genomics topic with no interest in human health.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Recruited to human genomics", "description": "Was recruited to a human genomics company for transferable statistical methods.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A plant method solves a human problem", "description": "Adapted a plant genomics statistical method to solve a stalled human genomics problem.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a senior genomics data scientist, having proven methods transfer across biological domains more readily than subject expertise.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_genomics_data_scientist_6", "career_id": "genomics_data_scientist",
        "person_label": "Genomics Data Scientist, 1 year experience",
        "background": "Worked for three years as a high school biology teacher before deciding to leave the classroom for a research-oriented career.",
        "journey": "Returned to school for a master's degree in genomics, drawing on years of explaining complex biology simply to students as an unexpected communication asset.",
        "challenges": "Felt behind peers who had gone straight from undergraduate biology into research, having spent years teaching instead of publishing.",
        "turning_points": "Being specifically praised in a job interview for their ability to explain a complex genomics finding clearly reframed the teaching years as an asset, not a delay.",
        "advice": "Time spent teaching or explaining a subject builds a genuinely rare communication skill that research careers often lack and need.",
        "lessons_learned": "A path that looks like a detour from research can build exactly the communication skill research careers are usually missing.",
        "trait_tags": ["communication", "learning_style"],
        "timeline": [
            {"stage": "first_job", "label": "High school biology teacher", "description": "Worked as a high school biology teacher for three years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Master's in genomics", "description": "Returned to school for a master's degree in genomics.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Communication skill praised in interview", "description": "Was praised in a job interview for clearly explaining a complex genomics finding.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Felt behind peers who went straight from undergraduate biology into research without a teaching detour.",
        "current_outcome": "Works as a genomics data scientist, using communication skills built while teaching as a genuine professional asset.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    # --- Bioinformatics Scientist -----------------------------------------
    {
        "id": "story_bioinformatics_scientist_2", "career_id": "bioinformatics_scientist",
        "person_label": "Bioinformatics Scientist, 4 years experience",
        "background": "Studied veterinary medicine for two years before realizing clinical animal care wasn't a sustainable long-term fit.",
        "journey": "Left the veterinary program and pursued a bioinformatics degree instead, drawn to the genetics coursework that had been the most engaging part of vet school.",
        "challenges": "Had to explain the switch repeatedly to family who had strongly supported the original veterinary path.",
        "turning_points": "Publishing their first bioinformatics research paper, on a genetics topic connected to animal health, tied the new path back to the original motivation.",
        "advice": "Leaving a demanding program partway through isn't a failure if you can identify and follow the specific part that genuinely engaged you.",
        "lessons_learned": "The part of a training program you found most interesting is often a better guide to your real direction than the program's overall label.",
        "trait_tags": ["curiosity", "values"],
        "timeline": [
            {"stage": "university", "label": "Veterinary medicine, unfinished", "description": "Studied veterinary medicine for two years before realizing it wasn't a sustainable fit.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Bioinformatics degree", "description": "Left veterinary school and pursued bioinformatics, drawn to the genetics coursework.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "First published paper", "description": "Published a bioinformatics research paper connected to animal health.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a bioinformatics scientist, having followed the genetics interest that stood out from an unfinished veterinary path.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_bioinformatics_scientist_3", "career_id": "bioinformatics_scientist",
        "person_label": "Bioinformatics Scientist, 7 years experience",
        "background": "Worked as a software engineer at a large tech company for five years, entirely outside biology or healthcare.",
        "journey": "Took a sabbatical after a period of burnout, used it to volunteer with a genomics nonprofit, and never returned to the original tech job.",
        "challenges": "Took a significant pay cut moving from a well-compensated tech role into an entry-level bioinformatics position.",
        "turning_points": "Watching the nonprofit's genomics work directly help identify a treatable condition in a study participant reframed what 'meaningful work' meant to them.",
        "advice": "A sabbatical taken to address burnout can end up reshaping your entire career direction, not just providing rest.",
        "lessons_learned": "Burnout can be an opening to reassess what kind of impact you actually want your work to have, not just a problem to recover from and return to the same role.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "first_job", "label": "Software engineer", "description": "Worked as a software engineer at a large tech company for five years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Sabbatical and volunteering", "description": "Took a sabbatical after burnout and volunteered with a genomics nonprofit.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "A treatable condition identified", "description": "The nonprofit's genomics work helped identify a treatable condition in a study participant.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": True,
        "uncertainty_period": "A burnout-driven sabbatical that ended up reshaping the entire career direction rather than just providing rest.",
        "current_outcome": "Works as a bioinformatics scientist, having taken a significant pay cut for work they consider more meaningful.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_bioinformatics_scientist_4", "career_id": "bioinformatics_scientist",
        "person_label": "Bioinformatics Scientist, 3 years experience",
        "background": "Studied biology as an undergraduate with a strong aversion to programming, actively avoiding any coding-heavy coursework.",
        "journey": "Was forced to learn basic scripting for a required lab rotation, discovered they didn't hate it as expected, and pursued a bioinformatics master's afterward.",
        "challenges": "Started the master's program significantly behind classmates who already had strong programming backgrounds.",
        "turning_points": "Completing a capstone project that outperformed more experienced classmates', by leaning on strong biological intuition to guide the analysis, rebuilt lost confidence.",
        "advice": "An early aversion to a required skill doesn't necessarily predict how you'll feel about it once you're forced to actually use it.",
        "lessons_learned": "Biological intuition can compensate for a technical skills gap in ways that are easy to underestimate before you've tested it.",
        "trait_tags": ["learning_style", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Undergraduate biology, avoiding coding", "description": "Actively avoided coding-heavy coursework during an undergraduate biology degree.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Forced scripting in a lab rotation", "description": "Was forced to learn basic scripting for a required lab rotation.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "A strong capstone project", "description": "Completed a capstone project that outperformed more experienced classmates using biological intuition.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Started the master's program significantly behind classmates with stronger programming backgrounds.",
        "current_outcome": "Works as a bioinformatics scientist, having found biological intuition compensates for an initially weaker technical background.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_bioinformatics_scientist_5", "career_id": "bioinformatics_scientist",
        "person_label": "Bioinformatics Scientist, 5 years experience",
        "background": "Immigrated for graduate study and had to rebuild a scientific network entirely from scratch in a new country with a different research culture.",
        "journey": "Struggled through an isolating first year before finding a bioinformatics lab whose collaborative style suited them better than their first, more competitive lab placement.",
        "challenges": "Faced language barriers in technical discussions and a genuine sense of professional isolation during the first year.",
        "turning_points": "Switching labs to a more collaborative environment, after an honest conversation with their advisor, changed the entire trajectory of the graduate program.",
        "advice": "If a lab or team's culture is actively working against you, changing environments — not just working harder — can be the right move.",
        "lessons_learned": "The right scientific environment matters as much as the right scientific problem — struggling with a mismatched culture isn't a personal failure.",
        "trait_tags": ["motivation", "work_preferences"],
        "timeline": [
            {"stage": "university", "label": "Graduate study abroad", "description": "Immigrated for graduate study, rebuilding a scientific network from scratch.", "year_label": "Year 0"},
            {"stage": "failure", "label": "An isolating first lab", "description": "Struggled through an isolating first year in a competitive first lab placement.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Switching to a collaborative lab", "description": "Switched labs to a more collaborative environment after an honest conversation with their advisor.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "A genuinely isolating first year adjusting to a new country, language, and competitive lab culture.",
        "current_outcome": "Works as a bioinformatics scientist, having learned that environment fit matters as much as the scientific problem itself.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_bioinformatics_scientist_6", "career_id": "bioinformatics_scientist",
        "person_label": "Bioinformatics Scientist, 10 years experience",
        "background": "Started a bioinformatics PhD with a clear plan to become a tenure-track professor, following their advisor's own career path closely.",
        "journey": "Watched the academic job market shrink significantly during their PhD, and made a deliberate decision partway through to target industry roles instead.",
        "challenges": "Had to manage real disappointment from an advisor who had assumed they'd pursue the same academic path.",
        "turning_points": "Attending an industry-focused conference and seeing the range and scale of problems industry bioinformatics tackled reframed the pivot as a genuine choice, not a consolation prize.",
        "advice": "Watch the actual state of the job market in your intended field, not just your advisor's own path through it a decade or two earlier.",
        "lessons_learned": "A deliberate pivot away from an original plan, made with clear eyes about market realities, isn't a lesser outcome than the original plan.",
        "trait_tags": ["analytical_thinking", "motivation"],
        "timeline": [
            {"stage": "university", "label": "PhD, aiming for tenure track", "description": "Started a PhD with a clear plan to become a tenure-track professor.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Watching the academic market shrink", "description": "Watched the academic job market shrink significantly during the PhD.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "An industry conference", "description": "Attended an industry-focused conference and reframed the pivot as a genuine choice.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a bioinformatics scientist in industry, a deliberate pivot made with clear-eyed awareness of the academic job market.",
        "industry": "biotechnology", "story_type": "composite", "source_reference": "",
    },
    # --- Materials Science Research Scientist -----------------------------
    {
        "id": "story_materials_research_scientist_2", "career_id": "materials_research_scientist",
        "person_label": "Materials Research Scientist, 4 years experience",
        "background": "Worked as a high school chemistry teacher for three years, drawn back to research by a persistent curiosity that teaching alone didn't satisfy.",
        "journey": "Left teaching to pursue a graduate degree in materials science in their late twenties, older than most incoming graduate students.",
        "challenges": "Felt out of place initially among classmates several years younger with more recent, continuous academic experience.",
        "turning_points": "Mentoring younger labmates through teaching instincts built in the classroom earned genuine respect that offset the age gap.",
        "advice": "Returning to research later than typical isn't a disadvantage — the experience gained elsewhere often becomes a distinct strength in the lab.",
        "lessons_learned": "A non-linear path into research can bring skills, like teaching and mentoring, that a straight-through academic path often doesn't build as early.",
        "trait_tags": ["communication", "curiosity"],
        "timeline": [
            {"stage": "first_job", "label": "High school chemistry teacher", "description": "Worked as a chemistry teacher for three years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Graduate school, older than peers", "description": "Left teaching to pursue a materials science graduate degree later than most classmates.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Mentoring earns respect", "description": "Mentoring younger labmates using classroom-built teaching instincts earned respect.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a materials research scientist, bringing teaching and mentoring skills built before entering the lab.",
        "industry": "manufacturing & research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_materials_research_scientist_3", "career_id": "materials_research_scientist",
        "person_label": "Materials Research Scientist, 6 years experience",
        "background": "Grew up in a manufacturing town where the local factory, employing much of the community including family members, eventually closed.",
        "journey": "Studied materials science specifically motivated by wanting to help develop the next generation of manufacturing technology for communities like the one they grew up in.",
        "challenges": "Faced skepticism from some family members who saw academic research as disconnected from the practical, job-creating work the community actually needed.",
        "turning_points": "Their research on a new manufacturing material being licensed by a company that opened a small factory in a similar town connected the work directly back to its original motivation.",
        "advice": "A research career motivated by a specific real-world outcome can stay grounded through years of abstract lab work if you hold onto that original 'why.'",
        "lessons_learned": "Research that feels abstract day-to-day can still be aimed, deliberately, at a very concrete and personal real-world goal.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "university", "label": "Materials science, motivated by hometown", "description": "Studied materials science motivated by their hometown factory's closure.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Research scientist", "description": "Began materials research aimed at future manufacturing technology.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "Research licensed to a new factory", "description": "Research on a new manufacturing material was licensed by a company opening a factory in a similar town.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a materials research scientist, having connected abstract lab research directly back to a personal community goal.",
        "industry": "manufacturing & research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_materials_research_scientist_4", "career_id": "materials_research_scientist",
        "person_label": "Materials Research Scientist, 2 years experience",
        "background": "Pursued a PhD in physics, expecting to work on purely theoretical problems with no applied focus.",
        "journey": "Took an unplanned elective in applied materials physics to fill a schedule gap and found the combination of theory and tangible application more satisfying than pure theory alone.",
        "challenges": "Had to defend the elective-driven pivot to an advisor who saw applied work as a lesser path than pure theoretical physics.",
        "turning_points": "Presenting applied research at a conference and fielding genuine, practical questions from industry attendees — rather than only theoretical ones from academics — confirmed the shift felt right.",
        "advice": "Give unplanned electives or requirements a genuine chance — sometimes the class you almost skip reveals the direction that actually fits.",
        "lessons_learned": "A field's prestige hierarchy, as seen by an advisor or department, doesn't have to determine what kind of work is actually the best fit for you.",
        "trait_tags": ["curiosity", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Physics PhD, theoretical focus", "description": "Pursued a PhD in physics expecting purely theoretical work.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "An unplanned applied elective", "description": "Took an unplanned elective in applied materials physics and found it more satisfying than pure theory.", "year_label": "Year 2"},
            {"stage": "current_role", "label": "Materials Research Scientist", "description": "Presented applied research at a conference, confirming the shift felt right.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a materials research scientist in applied physics, a direction found through an almost-skipped elective.",
        "industry": "manufacturing & research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_materials_research_scientist_5", "career_id": "materials_research_scientist",
        "person_label": "Materials Research Scientist, 8 years experience",
        "background": "Spent the first three years of a PhD on a research direction that ultimately produced no usable results, a common but rarely discussed experience.",
        "journey": "Had to restart with a new research question in year four, working with an unusually short remaining timeline to produce a dissertation.",
        "challenges": "Faced serious doubt about whether to leave the program entirely rather than restart under significant time pressure.",
        "turning_points": "The restarted project, done under real time constraints, ended up more focused and produced stronger results than the original meandering direction had.",
        "advice": "A failed research direction isn't wasted if you're willing to genuinely restart rather than force the original approach to work.",
        "lessons_learned": "Real constraints, like a shortened timeline, can sometimes produce sharper, more focused work than an open-ended original plan.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Three years on a failed direction", "description": "Spent the first three years of a PhD on a research direction that produced no usable results.", "year_label": "Year 3"},
            {"stage": "failure", "label": "Considering leaving the program", "description": "Faced serious doubt about whether to leave the program entirely.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "A sharper restarted project", "description": "The restarted project, under real time pressure, produced stronger results than the original direction.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Serious doubt in year three about whether to leave the PhD program entirely after a failed research direction.",
        "current_outcome": "Works as a materials research scientist, having learned real constraints can sharpen research more than open-ended time.",
        "industry": "manufacturing & research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_materials_research_scientist_6", "career_id": "materials_research_scientist",
        "person_label": "Materials Research Scientist, 5 years experience",
        "background": "Studied mechanical engineering with a focus on manufacturing processes, with no specific interest in the underlying materials science.",
        "journey": "Took a job at a manufacturing company where recurring product failures traced back to material choice, not process design, pulling them deeper into materials science over several years.",
        "challenges": "Had to independently teach themselves materials science fundamentals on the job, since their formal training was in process engineering, not materials.",
        "turning_points": "Correctly diagnosing a recurring product failure as a materials issue, after process engineers had exhausted their own explanations, established their credibility in the new specialty.",
        "advice": "A specific, recurring problem at work can pull you into an adjacent specialty more effectively than any deliberate career planning.",
        "lessons_learned": "Expertise in an adjacent field can be built through solving one real, recurring problem deeply, not just formal training.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Mechanical engineering, manufacturing focus", "description": "Studied mechanical engineering with a focus on manufacturing processes.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Manufacturing company", "description": "Worked at a manufacturing company where recurring failures traced back to material choice.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Diagnosing a materials issue", "description": "Correctly diagnosed a recurring product failure as a materials issue after process engineers had exhausted their explanations.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a materials research scientist, having built the specialty by solving one recurring problem deeply rather than through formal training.",
        "industry": "manufacturing & research", "story_type": "composite", "source_reference": "",
    },
    # --- Neuroscience Postdoctoral Researcher ------------------------------
    {
        "id": "story_neuroscience_postdoc_1", "career_id": "neuroscience_postdoc",
        "person_label": "Neuroscience Postdoctoral Researcher, 2 years experience",
        "background": "A close family member's neurological condition during high school first drew their interest toward brain science, well before any formal training.",
        "journey": "Pursued neuroscience through undergraduate and graduate study with that early motivation as a consistent throughline, into a postdoctoral position studying a related condition.",
        "challenges": "Found it emotionally taxing at times to study a condition so closely tied to a personal family experience.",
        "turning_points": "Presenting research findings directly to a patient advocacy group, rather than only to academic peers, reconnected the abstract research with its original human motivation.",
        "advice": "If your interest in a research field started from something deeply personal, staying connected to that original motivation can sustain you through years of slow academic work.",
        "lessons_learned": "Presenting research to the people it's meant to eventually help, not just to academic peers, can renew motivation that pure publication cycles don't.",
        "trait_tags": ["values", "curiosity"],
        "timeline": [
            {"stage": "school", "label": "A family member's condition", "description": "A close family member's neurological condition first drew interest toward brain science.", "year_label": "Year 0"},
            {"stage": "university", "label": "Neuroscience training", "description": "Pursued neuroscience through undergraduate and graduate study.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Presenting to a patient advocacy group", "description": "Presented research findings directly to a patient advocacy group.", "year_label": "Year 9"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a neuroscience postdoctoral researcher, studying a condition connected to a formative personal experience.",
        "industry": "academic research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_neuroscience_postdoc_2", "career_id": "neuroscience_postdoc",
        "person_label": "Neuroscience Postdoctoral Researcher, 1 year experience",
        "background": "Completed a PhD in a different subfield of neuroscience than they now work in, after a difficult final year that nearly ended the degree entirely.",
        "journey": "A severe illness during the final year of the PhD delayed graduation by over a year, but ultimately led to a postdoctoral position in a subfield they discovered while recovering and reading broadly.",
        "challenges": "Faced real uncertainty about whether the illness-driven delay would permanently derail an academic career already running behind typical timelines.",
        "turning_points": "A paper read purely out of recovery-period boredom sparked the specific research question that became their postdoctoral project.",
        "advice": "A serious health setback during training doesn't have to end an academic path — it can, unpredictably, redirect it toward something you wouldn't have found otherwise.",
        "lessons_learned": "Even a difficult, unplanned delay can open unexpected intellectual directions if you stay curious during the recovery itself.",
        "trait_tags": ["motivation", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "A difficult final PhD year", "description": "A severe illness during the final PhD year delayed graduation by over a year.", "year_label": "Year 5"},
            {"stage": "failure", "label": "Uncertainty about the delay", "description": "Faced real uncertainty about whether the delay would derail an already-behind academic career.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "A paper read during recovery", "description": "A paper read out of recovery-period boredom sparked the postdoctoral research question.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Over a year's delay from a severe illness during the final PhD year, with real uncertainty about the career impact.",
        "current_outcome": "Works as a neuroscience postdoctoral researcher in a subfield discovered while recovering from the delay.",
        "industry": "academic research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_neuroscience_postdoc_3", "career_id": "neuroscience_postdoc",
        "person_label": "Neuroscience Postdoctoral Researcher, 4 years experience",
        "background": "Applied to over twenty postdoctoral positions after finishing a PhD, facing an unusually difficult funding environment for new neuroscience postdocs that year.",
        "journey": "Took a temporary industry data science role for eight months while continuing to apply, before finally securing a postdoctoral position.",
        "challenges": "Watched several PhD cohort peers leave academic research entirely during that stretch, questioning whether to do the same.",
        "turning_points": "A rejected grant application's reviewer feedback, incorporated into a stronger revised proposal, was ultimately what secured the eventual postdoctoral funding.",
        "advice": "A difficult job market year doesn't reflect your work's quality as directly as it feels like it does in the moment — persistence and revision matter.",
        "lessons_learned": "Rejected applications, read carefully rather than just felt as failures, often contain the specific feedback that gets the next attempt funded.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "A difficult postdoc market", "description": "Applied to over twenty postdoctoral positions in an unusually difficult funding year.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Temporary industry role", "description": "Took a temporary industry data science role for eight months while continuing to apply.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "Revised proposal secures funding", "description": "Incorporated rejected-grant reviewer feedback into a stronger proposal that secured funding.", "year_label": "Year 1"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Eight months in a temporary industry role while continuing to apply during a difficult academic job market.",
        "current_outcome": "Works as a neuroscience postdoctoral researcher, funded on a revised proposal built from earlier rejection feedback.",
        "industry": "academic research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_neuroscience_postdoc_4", "career_id": "neuroscience_postdoc",
        "person_label": "Neuroscience Postdoctoral Researcher, 3 years experience",
        "background": "Started graduate school planning to study cognitive neuroscience, then pivoted to a more molecular subfield after a required rotation in a molecular lab.",
        "journey": "The rotation, meant to be a brief formality before returning to their original cognitive interest, revealed a genuine excitement for molecular methods they hadn't expected.",
        "challenges": "Had to abandon significant preliminary work already done in their original intended subfield to make the switch.",
        "turning_points": "Their first successful molecular experiment, after weeks of technical failures typical for the new methods, confirmed the switch was worth the lost preliminary work.",
        "advice": "Required rotations exist partly to reveal genuine interests you didn't know you had — take them seriously even when you think you already know your direction.",
        "lessons_learned": "Sunk preliminary work in one subfield is a real cost, but not a good enough reason alone to ignore a genuinely stronger fit discovered elsewhere.",
        "trait_tags": ["curiosity", "learning_style"],
        "timeline": [
            {"stage": "university", "label": "Planning cognitive neuroscience", "description": "Started graduate school planning to study cognitive neuroscience.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A required molecular rotation", "description": "A required rotation in a molecular lab revealed genuine excitement for molecular methods.", "year_label": "Year 1"},
            {"stage": "career_transition", "label": "Switching subfields", "description": "Abandoned preliminary cognitive work to switch into the molecular subfield.", "year_label": "Year 1"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a neuroscience postdoctoral researcher in a molecular subfield discovered through a required rotation.",
        "industry": "academic research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_neuroscience_postdoc_5", "career_id": "neuroscience_postdoc",
        "person_label": "Senior Neuroscience Postdoctoral Researcher, 6 years experience",
        "background": "Completed two consecutive postdoctoral positions, an unusually long stretch, after the first didn't lead to the faculty offer they'd hoped for.",
        "journey": "Used the second postdoc deliberately to build a specific technical skill set the first position hadn't required, targeting faculty searches that valued that skill.",
        "challenges": "Faced real anxiety about the length of the postdoctoral stretch relative to peers who'd moved to faculty positions after a single postdoc.",
        "turning_points": "A faculty search committee explicitly citing the specific technical skill from the second postdoc as the deciding factor validated the deliberate strategy.",
        "advice": "If a first postdoc doesn't lead where you hoped, a second one can be used deliberately to close a specific gap, rather than just extending the same path.",
        "lessons_learned": "An unusually long postdoctoral stretch isn't automatically a red flag — it can reflect a deliberate, strategic skill-building decision.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "First postdoc, no faculty offer", "description": "Completed a first postdoc that didn't lead to a hoped-for faculty offer.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "A deliberate second postdoc", "description": "Used a second postdoc deliberately to build a specific technical skill set.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "The skill closes the gap", "description": "A faculty search committee cited the specific new skill as the deciding hiring factor.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Real anxiety about an unusually long two-postdoc stretch relative to peers on faster faculty timelines.",
        "current_outcome": "Works as a senior neuroscience postdoctoral researcher, a deliberately extended path that closed a specific skill gap.",
        "industry": "academic research", "story_type": "composite", "source_reference": "",
    },
    # --- Clinical Research Coordinator -------------------------------------
    {
        "id": "story_clinical_research_coordinator_1", "career_id": "clinical_research_coordinator",
        "person_label": "Clinical Research Coordinator, 3 years experience",
        "background": "Worked as a medical scribe for two years while applying, unsuccessfully, to several medical schools.",
        "journey": "Took a clinical research coordinator role as a fallback plan while reapplying, and found the work engaging enough to stop reapplying to medical school entirely.",
        "challenges": "Felt like the coordinator role was a consolation prize for the first year, still mentally holding onto the original medical school plan.",
        "turning_points": "Coordinating a trial that led directly to a new treatment approach for trial participants shifted their sense of what kind of medical impact actually mattered to them.",
        "advice": "A fallback plan can turn out to be a genuinely better fit than the original goal — give it real time before assuming it's just a placeholder.",
        "lessons_learned": "The specific kind of impact you want to have can be more important than the specific role or title you originally set out to reach.",
        "trait_tags": ["values", "work_preferences"],
        "timeline": [
            {"stage": "first_job", "label": "Medical scribe", "description": "Worked as a medical scribe for two years while applying to medical schools.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Coordinator role as a fallback", "description": "Took a clinical research coordinator role as a fallback plan while reapplying.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "A trial that changed treatment", "description": "Coordinated a trial that led directly to a new treatment approach for participants.", "year_label": "Year 3"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Two years applying unsuccessfully to medical schools before finding the coordinator role.",
        "current_outcome": "Works as a clinical research coordinator, no longer pursuing the original medical school plan.",
        "industry": "healthcare research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_clinical_research_coordinator_2", "career_id": "clinical_research_coordinator",
        "person_label": "Senior Clinical Research Coordinator, 8 years experience",
        "background": "Immigrated as a licensed nurse from another country, whose nursing credentials weren't directly recognized in the new country's licensing system.",
        "journey": "Took a clinical research coordinator role, which didn't require re-licensing, as a way to stay in healthcare while navigating the lengthy credential recognition process.",
        "challenges": "Faced years of bureaucratic delay in the credential recognition process, with genuine uncertainty about whether nursing would ever be practical again.",
        "turning_points": "After finally completing the credentialing process, deliberately chose to stay in clinical research rather than return to nursing, having grown to prefer the research side of healthcare.",
        "advice": "A credentialing detour into an adjacent field can end up becoming the actual destination, not just a waiting room for the original plan.",
        "lessons_learned": "Sometimes the practical path taken while waiting for the 'real' plan turns out to be the better fit once you're honest about which one you actually prefer.",
        "trait_tags": ["work_preferences", "motivation"],
        "timeline": [
            {"stage": "career_transition", "label": "Immigration, credentials not recognized", "description": "Immigrated as a licensed nurse whose credentials weren't directly recognized.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Clinical research coordinator", "description": "Took a coordinator role that didn't require re-licensing.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Choosing to stay in research", "description": "After completing credentialing, deliberately chose to stay in clinical research over returning to nursing.", "year_label": "Year 6"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Years of bureaucratic delay in credential recognition, with genuine uncertainty about ever practicing nursing again.",
        "current_outcome": "Works as a senior clinical research coordinator by deliberate choice, having found it a better fit than a return to nursing.",
        "industry": "healthcare research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_clinical_research_coordinator_3", "career_id": "clinical_research_coordinator",
        "person_label": "Clinical Research Coordinator, 2 years experience",
        "background": "Studied psychology as an undergraduate with a vague plan toward clinical practice, without a strong specific direction.",
        "journey": "Took a clinical research coordinator role at a psychiatric research center mainly because it was available, and discovered a genuine interest in trial methodology over direct clinical practice.",
        "challenges": "Struggled early on to explain to family why they'd chosen research coordination over the clinical psychology path they'd originally described.",
        "turning_points": "Realizing they found the rigor of trial design more intellectually satisfying than the clinical practice electives they'd taken in undergraduate study clarified the direction.",
        "advice": "A vague original plan doesn't have to be honored just because you described it to people first — let direct experience update the plan.",
        "lessons_learned": "The specific part of a broad field you actually enjoy day-to-day is a better guide than the version of the field you described before trying it.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Psychology, vague clinical plan", "description": "Studied psychology with a vague plan toward clinical practice.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Psychiatric research center", "description": "Took a coordinator role at a psychiatric research center mainly because it was available.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Trial design over clinical practice", "description": "Realized trial design rigor was more intellectually satisfying than clinical practice electives.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a clinical research coordinator, having let direct experience clarify an originally vague plan.",
        "industry": "healthcare research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_clinical_research_coordinator_4", "career_id": "clinical_research_coordinator",
        "person_label": "Clinical Research Coordinator, 5 years experience",
        "background": "Worked in pharmaceutical sales for four years, financially successful but increasingly uncomfortable with the sales-driven incentive structure.",
        "journey": "Took a significant pay cut to move into clinical research coordination, drawn to a role in the same industry with less pressure to prioritize commercial targets over patient welfare.",
        "challenges": "Faced real financial adjustment after leaving a commission-based sales income for a fixed research salary.",
        "turning_points": "Being trusted to flag a trial safety concern, without any commercial pressure weighing on the decision, was the moment the pay cut felt clearly worth it.",
        "advice": "If a values mismatch with your current role's incentive structure is the real problem, a lateral move within the same industry can resolve it without starting over.",
        "lessons_learned": "The same industry can offer very different relationships to commercial pressure, depending on which specific role you're in within it.",
        "trait_tags": ["values", "work_preferences"],
        "timeline": [
            {"stage": "first_job", "label": "Pharmaceutical sales", "description": "Worked in pharmaceutical sales for four years, uncomfortable with the incentive structure.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Move to clinical research", "description": "Took a pay cut to move into clinical research coordination.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Flagging a safety concern freely", "description": "Was trusted to flag a trial safety concern without commercial pressure weighing on the decision.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Real financial adjustment after leaving a commission-based sales income for a fixed research salary.",
        "current_outcome": "Works as a clinical research coordinator, having resolved a values mismatch through a lateral move within the same industry.",
        "industry": "healthcare research", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_clinical_research_coordinator_5", "career_id": "clinical_research_coordinator",
        "person_label": "Clinical Research Coordinator, 1 year experience",
        "background": "Participated as a trial volunteer in a clinical study during university, out of curiosity about a family member's chronic condition.",
        "journey": "The experience of being a study participant led directly to volunteering at the research site, and eventually to a paid coordinator role after graduation.",
        "challenges": "Had to learn the operational and regulatory side of trials from the ground up, having only ever seen the participant-facing side before.",
        "turning_points": "Being asked by the research team to help redesign the participant consent process, drawing on their own experience as a study volunteer, validated the unusual entry point.",
        "advice": "Being a research participant can be a genuine, legitimate entry point into a research career — not just an interesting one-off experience.",
        "lessons_learned": "First-hand experience as a research subject can bring a genuinely useful, uncommon perspective to a research team.",
        "trait_tags": ["curiosity", "values"],
        "timeline": [
            {"stage": "university", "label": "Trial volunteer", "description": "Participated as a trial volunteer during university out of curiosity about a family condition.", "year_label": "Year 0"},
            {"stage": "internship", "label": "Volunteering at the research site", "description": "Volunteered at the research site following the participant experience.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Redesigning the consent process", "description": "Was asked to help redesign the participant consent process using their own experience as a study volunteer.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a clinical research coordinator, having entered the field through the unusual route of being a study participant first.",
        "industry": "healthcare research", "story_type": "composite", "source_reference": "",
    },
    # --- Space Systems Engineer --------------------------------------------
    {
        "id": "story_space_systems_engineer_1", "career_id": "space_systems_engineer",
        "person_label": "Space Systems Engineer, 4 years experience",
        "background": "Studied mechanical engineering with an interest in automotive design, having never seriously considered the aerospace industry.",
        "journey": "Took a job at an automotive supplier that also produced components for a satellite manufacturer, and requested a transfer to the satellite division after learning more about it.",
        "challenges": "Had to learn an entirely different set of reliability standards, since space hardware has essentially no opportunity for in-field repair once launched.",
        "turning_points": "Watching a satellite component they'd worked on successfully deploy in orbit, after years of design work with no room for post-launch correction, was unlike any feedback automotive work had given them.",
        "advice": "An adjacent industry can be a genuine entry point into aerospace — the transferable engineering fundamentals often matter more than industry-specific experience.",
        "lessons_learned": "Space systems engineering rewards an almost obsessive standard of pre-launch reliability that most other engineering fields don't require to the same degree.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Mechanical engineering, automotive focus", "description": "Studied mechanical engineering with an interest in automotive design.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Automotive supplier", "description": "Worked at an automotive supplier that also produced satellite components.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A successful orbital deployment", "description": "Watched a satellite component they worked on successfully deploy in orbit.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a space systems engineer, having entered aerospace through an adjacent automotive supplier role.",
        "industry": "aerospace", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_space_systems_engineer_2", "career_id": "space_systems_engineer",
        "person_label": "Space Systems Engineer, 7 years experience",
        "background": "Applied to a national space agency's engineering program three separate times over five years before finally being accepted.",
        "journey": "Worked in a general aerospace manufacturing role during the years between rejections, deliberately building the specific technical experience the program's feedback had suggested was missing.",
        "challenges": "Faced real discouragement after each rejection, with growing uncertainty about whether to keep pursuing a space-specific career or settle for the general aerospace path instead.",
        "turning_points": "Explicit written feedback after the second rejection, naming a specific missing skill area, gave the persistence a concrete target rather than blind hope.",
        "advice": "Repeated rejection from a specific, competitive program is more useful than it feels in the moment if you can extract concrete feedback to work on.",
        "lessons_learned": "Persistence toward a specific goal is far more effective when paired with concretely addressing the actual gaps behind each rejection.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "General aerospace manufacturing", "description": "Worked in general aerospace manufacturing between three rejections from a space agency program.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Repeated rejection", "description": "Was rejected from the program three separate times over five years.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Concrete feedback to work on", "description": "Written feedback after the second rejection named a specific missing skill area.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Five years and three rejections, with growing uncertainty about whether to keep pursuing a space-specific path.",
        "current_outcome": "Works as a space systems engineer, having turned repeated rejection feedback into a concrete plan that eventually succeeded.",
        "industry": "aerospace", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_space_systems_engineer_3", "career_id": "space_systems_engineer",
        "person_label": "Space Systems Engineer, 3 years experience",
        "background": "Grew up in a country with no domestic space program, assuming a space-related career would require emigrating.",
        "journey": "Watched a domestic commercial space startup launch during their university years and joined its founding engineering team directly out of school.",
        "challenges": "Worked with a team building processes and standards essentially from scratch, without the established institutional knowledge a mature space agency would have provided.",
        "turning_points": "Being part of the team's first successful launch, as one of the country's first domestically built spacecraft, carried weight beyond just a career milestone.",
        "advice": "A country without an established space industry isn't necessarily a dead end — it can mean joining one at its earliest, most formative stage instead.",
        "lessons_learned": "Being early in a national industry's development means building the standards yourself, which is harder but can be more formative than joining an established one.",
        "trait_tags": ["motivation", "leadership"],
        "timeline": [
            {"stage": "university", "label": "No domestic space program", "description": "Grew up assuming a space career would require emigrating, with no domestic space program.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Founding engineering team", "description": "Joined a domestic commercial space startup's founding engineering team directly out of school.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "First domestic launch", "description": "Was part of the team's first successful launch, one of the country's first domestically built spacecraft.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a space systems engineer, having helped build a national space industry from its earliest stage.",
        "industry": "aerospace", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_space_systems_engineer_4", "career_id": "space_systems_engineer",
        "person_label": "Space Systems Engineer, 6 years experience",
        "background": "Served in the military as an aircraft maintenance technician for six years before transitioning to civilian engineering study.",
        "journey": "Used military tuition benefits to complete an aerospace engineering degree, entering a space systems role at an older age than most engineering graduates.",
        "challenges": "Had to adjust from a highly structured military environment to the more ambiguous, self-directed problem-solving expected of engineers in industry.",
        "turning_points": "Being specifically recognized for hands-on troubleshooting instincts built during years of aircraft maintenance, in a way newer graduates hadn't developed, reframed the military years as a direct asset.",
        "advice": "Military technical experience translates more directly into space systems engineering than it might seem — the hands-on discipline is genuinely valued.",
        "lessons_learned": "Structured, high-stakes technical environments outside engineering, like military maintenance, can build instincts that formal engineering education alone doesn't.",
        "trait_tags": ["analytical_thinking", "work_preferences"],
        "timeline": [
            {"stage": "first_job", "label": "Military aircraft maintenance", "description": "Served as an aircraft maintenance technician for six years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Aerospace engineering degree", "description": "Used military tuition benefits to complete an aerospace engineering degree.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "Troubleshooting instincts recognized", "description": "Was recognized for hands-on troubleshooting instincts built during military maintenance work.", "year_label": "Year 8"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a space systems engineer, having entered engineering later via military technical experience that's now a direct asset.",
        "industry": "aerospace", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_space_systems_engineer_5", "career_id": "space_systems_engineer",
        "person_label": "Space Systems Engineer, 2 years experience",
        "background": "Studied electrical engineering with a general interest in signal processing, without a specific focus on aerospace applications.",
        "journey": "Joined a satellite communications team after graduation mainly because it offered the strongest signal processing work available, and the space context became a genuine interest afterward.",
        "challenges": "Initially treated the role as just an application of signal processing skills, with little emotional investment in the space aspect specifically.",
        "turning_points": "Visiting mission control during a satellite's first data downlink, and seeing their signal processing work directly enable that moment, shifted space from context to genuine motivation.",
        "advice": "The context around a technical skill you already have can become a genuine passion after the fact, even if it wasn't the reason you first took the job.",
        "lessons_learned": "Motivation for a field doesn't have to precede taking the job — sometimes it develops from witnessing the real-world outcome of work you were already doing well.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Electrical engineering, signal processing focus", "description": "Studied electrical engineering with a general interest in signal processing.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Satellite communications team", "description": "Joined a satellite communications team mainly for the strongest available signal processing work.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Witnessing a first data downlink", "description": "Visited mission control during a satellite's first data downlink, enabled by their own signal processing work.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a space systems engineer, motivation for the space context having developed after joining rather than before.",
        "industry": "aerospace", "story_type": "composite", "source_reference": "",
    },
]


async def seed() -> None:
    client = get_supabase_client()
    stories = [CareerStory.model_validate(s) for s in STORIES]

    def _upsert() -> None:
        client.table("career_stories").upsert(
            [s.model_dump(mode="json") for s in stories]
        ).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(stories)} science & research Journey Stories.")


if __name__ == "__main__":
    asyncio.run(seed())
