"""Journey Stories — Business & Education domain group (Connect Batch
2). 20 new composite Journey Stories across 4 careers: Startup Founder
(Generalist), Accountant (Corporate Finance), K-12 Teacher, Corporate
Sustainability Analyst. Every entry is an illustrative composite
persona (`story_type="composite"`) — never a claim of a specific real
individual. This is the final domain-group file for Connect Batch 2's
Journey Stories, bringing the total to 15 existing + 135 new = 150.

Run via: python -m aureon.scripts.seed_journey_stories_business_and_education
Idempotent: safe to re-run (upsert on id).
"""

import asyncio

from aureon.domain.models.career import CareerStory
from aureon.services.supabase.client import get_supabase_client

STORIES: list[dict] = [
    # --- Startup Founder (Generalist) ---------------------------------------
    {
        "id": "story_startup_founder_2", "career_id": "startup_founder",
        "person_label": "Startup Founder, 2 years experience",
        "background": "Founded a first startup at 23 that failed completely within eighteen months, leaving significant personal debt.",
        "journey": "Took a stable corporate job for three years specifically to pay off the debt before attempting a second startup, this time far more cautiously.",
        "challenges": "Faced real fear of repeating the same failure, which made the second attempt's early decisions slower and more hesitant than the first.",
        "turning_points": "Explicitly listing every mistake from the first failure and building the second company's plan around avoiding each one gave structure to the caution.",
        "advice": "A first startup failure with real financial consequences doesn't disqualify a second attempt — but expect to need real time to recover both financially and psychologically first.",
        "lessons_learned": "A documented, specific list of past mistakes is more useful for a second attempt than vague caution or renewed confidence alone.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "First startup fails", "description": "Founded a first startup at 23 that failed completely within eighteen months.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Paying off debt", "description": "Took a stable corporate job for three years to pay off startup debt.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "A second, structured attempt", "description": "Built a second startup's plan explicitly around avoiding every documented first-startup mistake.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Three years working a stable job to recover financially and psychologically from a first startup's complete failure.",
        "current_outcome": "Runs a second startup, built explicitly around lessons documented from an earlier complete failure.",
        "industry": "entrepreneurship", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_startup_founder_3", "career_id": "startup_founder",
        "person_label": "Startup Founder, 6 years experience",
        "background": "Worked as an engineer at a large tech company for eight years, financially comfortable with no strong plans to leave.",
        "journey": "Was laid off unexpectedly during a company-wide restructuring, and used the severance package as unplanned seed funding for a company idea they'd never seriously pursued.",
        "challenges": "Had never planned to start a company and had none of the preparation — business plan, cofounder search, market research — typical founders build in advance.",
        "turning_points": "A first customer signing on within two months of the layoff, faster than expected, turned what began as a forced pivot into a genuine, deliberate business.",
        "advice": "An unplanned layoff can become an unplanned opportunity if you have an idea you've been sitting on — the severance can function as accidental seed funding.",
        "lessons_learned": "Sometimes a company gets built not from careful planning but from being pushed, suddenly, into finally testing an idea that had been sitting untested for years.",
        "trait_tags": ["motivation", "creativity"],
        "timeline": [
            {"stage": "first_job", "label": "Comfortable corporate engineer", "description": "Worked as an engineer at a large tech company for eight years, comfortable with no plans to leave.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Unexpected layoff", "description": "Was laid off unexpectedly during a company-wide restructuring.", "year_label": "Year 8"},
            {"stage": "turning_point", "label": "A first customer, fast", "description": "A first customer signed on within two months of the layoff.", "year_label": "Year 8"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Runs a company built from an unplanned layoff, severance functioning as accidental seed funding.",
        "industry": "entrepreneurship", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_startup_founder_4", "career_id": "startup_founder",
        "person_label": "Startup Founder, 9 years experience",
        "background": "Co-founded a company with a close friend, a partnership that ended acrimoniously after four years over irreconcilable differences in vision.",
        "journey": "Bought out the departing cofounder's stake and continued the company alone, having to rebuild both the leadership structure and the personal toll of the lost friendship.",
        "challenges": "Lost the friendship entirely alongside the cofounder relationship, a cost that took much longer to process than the business restructuring itself.",
        "turning_points": "Successfully hiring a new leadership team member who complemented their own gaps, the way the original cofounder once had, restored confidence in the company's direction.",
        "advice": "A cofounder split is a real personal loss, not just a business restructuring — give yourself time to grieve the relationship separately from fixing the company.",
        "lessons_learned": "The business and personal costs of a cofounder split are genuinely separate, and both need real, honest processing, not just quick operational fixes.",
        "trait_tags": ["leadership", "motivation"],
        "timeline": [
            {"stage": "first_job", "label": "Co-founding with a close friend", "description": "Co-founded a company with a close friend.", "year_label": "Year 0"},
            {"stage": "failure", "label": "An acrimonious split", "description": "The cofounder partnership ended acrimoniously after four years over irreconcilable differences.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Rebuilding leadership", "description": "Hired a new leadership team member who complemented their own gaps.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "A period processing the personal loss of a lost friendship alongside the business restructuring.",
        "current_outcome": "Continues running the company solo, having rebuilt leadership after a difficult cofounder split.",
        "industry": "entrepreneurship", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_startup_founder_5", "career_id": "startup_founder",
        "person_label": "Startup Founder, 1 year experience",
        "background": "Was a stay-at-home parent for six years after leaving a marketing career, with no immediate plans to return to formal employment.",
        "journey": "Started a small business from home, initially as a part-time way to generate independent income, that grew into a full company faster than expected.",
        "challenges": "Faced real skepticism, including from close family, about whether the small home business could realistically become anything beyond a hobby.",
        "turning_points": "A local news feature on the business drove enough new demand that hiring the first employee became necessary within the year.",
        "advice": "A career gap for caregiving doesn't have to mean starting from zero — skills built before the gap can still directly launch a new venture.",
        "lessons_learned": "A part-time venture, started with modest expectations during a caregiving period, can outgrow those expectations faster than anyone involved anticipated.",
        "trait_tags": ["motivation", "creativity"],
        "timeline": [
            {"stage": "career_transition", "label": "Stay-at-home parent", "description": "Was a stay-at-home parent for six years after leaving a marketing career.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "A part-time home business", "description": "Started a small business from home as a part-time source of independent income.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "A local news feature", "description": "A local news feature drove enough demand to require hiring a first employee.", "year_label": "Year 7"},
        ],
        "career_switch": True, "gap_year": True,
        "uncertainty_period": "A six-year career gap for caregiving before the business launched.",
        "current_outcome": "Runs a growing company that started as a part-time venture during a caregiving career gap.",
        "industry": "entrepreneurship", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_startup_founder_6", "career_id": "startup_founder",
        "person_label": "Startup Founder, 4 years experience",
        "background": "Studied business with a clear, deliberate plan to start a company directly after graduation, having planned the general direction since high school.",
        "journey": "Launched the company immediately after graduating, exactly as planned, but the specific product idea failed within a year and had to be replaced with a completely different one under the same company.",
        "challenges": "Had to pivot the entire product and business model within the company's first year, after the original carefully planned idea failed to find real customers.",
        "turning_points": "The pivot's replacement idea, developed in weeks under real pressure rather than years of planning, found paying customers within the first month.",
        "advice": "Even a carefully, deliberately planned entrepreneurial path can still require a fast, unplanned pivot — build in the willingness to abandon the original plan.",
        "lessons_learned": "Years of deliberate planning toward starting a company don't guarantee the first specific idea will work — the willingness to pivot fast matters more than the plan itself.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "A deliberate, long-planned path", "description": "Studied business with a plan to start a company directly after graduation.", "year_label": "Year 0"},
            {"stage": "failure", "label": "The original idea fails", "description": "Launched the planned product idea, which failed to find real customers within a year.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A fast pivot finds customers", "description": "A replacement idea, developed in weeks, found paying customers within its first month.", "year_label": "Year 1"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Runs a company built on a pivoted idea, after a carefully planned original product failed within its first year.",
        "industry": "entrepreneurship", "story_type": "composite", "source_reference": "",
    },
    # --- Accountant (Corporate Finance) --------------------------------------
    {
        "id": "story_accountant_1", "career_id": "accountant",
        "person_label": "Corporate Accountant, 3 years experience",
        "background": "Studied fine arts as an undergraduate, with no exposure to accounting or finance until well after graduation.",
        "journey": "Took a bookkeeping job at a small business out of financial necessity after struggling to find paid work as an artist, and discovered a genuine aptitude for the detail-oriented work.",
        "challenges": "Felt significant identity conflict initially, having spent years identifying as an artist before taking on an accounting role purely for financial stability.",
        "turning_points": "Being praised by a small business owner for catching a costly bookkeeping error that would have gone unnoticed for months reframed the work as a real skill, not just a fallback.",
        "advice": "A financially necessary fallback job can turn into a genuine second career if you stay open to the possibility, rather than only treating it as temporary.",
        "lessons_learned": "An unrelated creative background doesn't preclude genuine satisfaction and skill in detail-oriented financial work — the two aren't as opposed as they might seem.",
        "trait_tags": ["analytical_thinking", "work_preferences"],
        "timeline": [
            {"stage": "university", "label": "Fine arts degree", "description": "Studied fine arts with no exposure to accounting until after graduation.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Bookkeeping out of necessity", "description": "Took a bookkeeping job out of financial necessity after struggling as an artist.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Catching a costly error", "description": "Was praised for catching a costly bookkeeping error that would have gone unnoticed.", "year_label": "Year 3"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a corporate accountant, having found genuine skill in work initially taken purely out of financial necessity.",
        "industry": "finance", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_accountant_2", "career_id": "accountant",
        "person_label": "Senior Accountant, 10 years experience",
        "background": "Immigrated as a qualified accountant from another country, where professional credentials weren't automatically recognized in the new country.",
        "journey": "Spent nearly three years completing local certification exams while working in lower-level bookkeeping roles below their actual qualification level.",
        "challenges": "Faced real frustration working in roles significantly below their prior professional level while re-certifying, despite having years of genuine experience.",
        "turning_points": "Finally passing the local certification exams and being promoted directly into a senior role, based on the combination of prior international experience and new local credentials, validated the multi-year wait.",
        "advice": "Immigrating with an unrecognized professional credential is genuinely frustrating, but the underlying years of experience aren't erased — they compound with the new certification once it's earned.",
        "lessons_learned": "A period working below your actual qualification level, while re-certifying after immigration, is temporary — prior experience still counts once local credentials are in place.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "career_transition", "label": "Immigration, credentials not recognized", "description": "Immigrated as a qualified accountant whose credentials weren't automatically recognized.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Lower-level bookkeeping roles", "description": "Worked lower-level bookkeeping roles while completing local certification exams.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Promoted to senior accountant", "description": "Passed local certification and was promoted directly into a senior role.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Nearly three years working below their qualification level while completing local re-certification.",
        "current_outcome": "Works as a senior accountant, prior international experience compounding with new local credentials.",
        "industry": "finance", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_accountant_3", "career_id": "accountant",
        "person_label": "Corporate Accountant, 5 years experience",
        "background": "Worked as an auditor for a large accounting firm for three years, finding the constant travel and client turnover exhausting.",
        "journey": "Moved in-house to a single company's corporate accounting team, trading the variety of audit work for the stability of one organization.",
        "challenges": "Missed the broad exposure to different companies and industries that audit work had provided, at least initially after the move.",
        "turning_points": "Being given ownership of a full financial reporting cycle from start to finish, something audit work never offered as an outside party, provided a different but genuine kind of satisfaction.",
        "advice": "If constant travel and client turnover in audit work is wearing you down, in-house corporate accounting offers real depth and ownership in exchange for that breadth.",
        "lessons_learned": "The kind of ownership possible inside a single company's finance team is different from, but not lesser than, the breadth of exposure external audit work provides.",
        "trait_tags": ["work_preferences", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "External auditor", "description": "Worked as an auditor for three years, exhausted by constant travel and client turnover.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Moving in-house", "description": "Moved to a single company's corporate accounting team.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Owning a full reporting cycle", "description": "Was given ownership of a full financial reporting cycle from start to finish.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a corporate accountant, having traded audit breadth for the depth of ownership one company's finance team offers.",
        "industry": "finance", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_accountant_4", "career_id": "accountant",
        "person_label": "Corporate Accountant, 2 years experience",
        "background": "Failed a required professional certification exam three times before finally passing on a fourth attempt, an unusually high number of attempts even for a notoriously difficult exam.",
        "journey": "Continued working as an unqualified accounting assistant throughout the repeated attempts, unable to advance to a fully qualified role until passing.",
        "challenges": "Faced growing anxiety about whether they were fundamentally suited to the profession after each repeated failure, despite performing well in the actual day-to-day work.",
        "turning_points": "A colleague pointing out that day-to-day job performance and exam performance are genuinely different skills helped separate professional competence from testing anxiety.",
        "advice": "Struggling specifically with a certification exam, even repeatedly, doesn't necessarily reflect your actual competence at the day-to-day work itself.",
        "lessons_learned": "Exam performance and job performance can be genuinely different skills — repeated exam failure isn't the same signal as repeated job failure.",
        "trait_tags": ["motivation", "learning_style"],
        "timeline": [
            {"stage": "first_job", "label": "Unqualified accounting assistant", "description": "Worked as an unqualified accounting assistant while attempting a required certification.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Three failed exam attempts", "description": "Failed a required certification exam three times.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Passing on the fourth attempt", "description": "Passed the certification exam on a fourth attempt.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Growing anxiety across three failed certification attempts, despite strong day-to-day job performance.",
        "current_outcome": "Works as a qualified corporate accountant, having separated exam performance anxiety from genuine professional competence.",
        "industry": "finance", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_accountant_5", "career_id": "accountant",
        "person_label": "Corporate Accountant, 7 years experience",
        "background": "Was let go from a large accounting firm during a round of layoffs after five years, an outcome that felt arbitrary given strong performance reviews.",
        "journey": "Struggled for four months to find a comparable role before accepting a position at a smaller company, at first seen as a step down from the large-firm prestige.",
        "challenges": "Faced real financial and emotional strain during the four-month job search, compounded by the sense that the layoff hadn't reflected their actual performance.",
        "turning_points": "Being given far more direct responsibility and visibility at the smaller company, within months, than years at the large firm had ever offered reframed the layoff as an unplanned opportunity.",
        "advice": "A layoff driven by broad restructuring, not individual performance, can still lead somewhere better — a smaller company can offer responsibility a larger one delays for years.",
        "lessons_learned": "Prestige at a large organization and actual professional responsibility aren't the same thing — a smaller company can offer more of the latter much sooner.",
        "trait_tags": ["motivation", "leadership"],
        "timeline": [
            {"stage": "first_job", "label": "Large accounting firm, laid off", "description": "Was let go from a large accounting firm during layoffs after five years of strong performance.", "year_label": "Year 5"},
            {"stage": "failure", "label": "A difficult job search", "description": "Struggled for four months to find a comparable role.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "Real responsibility at a smaller company", "description": "Was given far more direct responsibility and visibility at a smaller company within months.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Four months of real financial and emotional strain during a job search following an arbitrary-feeling layoff.",
        "current_outcome": "Works as a corporate accountant at a smaller company, having found more genuine responsibility than the larger firm offered.",
        "industry": "finance", "story_type": "composite", "source_reference": "",
    },
    # --- K-12 Teacher ---------------------------------------------------------
    {
        "id": "story_teacher_k12_2", "career_id": "teacher_k12",
        "person_label": "K-12 Teacher, 4 years experience",
        "background": "Worked as a corporate trainer for six years, delivering standardized training content to adult employees with little room for personalization.",
        "journey": "Took a significant pay cut to move into K-12 teaching, drawn to working with students at an age where genuine intellectual curiosity was still forming.",
        "challenges": "Had to relearn classroom management for a completely different age group, since corporate training audiences required no discipline strategies at all.",
        "turning_points": "A student who'd been consistently disengaged asking an unprompted, genuinely curious question mid-lesson gave a form of engagement corporate training had never produced.",
        "advice": "Corporate training experience builds real presentation and instructional design skills that transfer to teaching, even though classroom management has to be learned separately.",
        "lessons_learned": "Genuine, unprompted curiosity from a young student can be a more meaningful form of engagement than any amount of polished corporate presentation feedback.",
        "trait_tags": ["communication", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Corporate trainer", "description": "Worked as a corporate trainer for six years with little room for personalization.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Move to K-12 teaching", "description": "Took a pay cut to move into K-12 teaching.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "An unprompted curious question", "description": "A consistently disengaged student asked a genuinely curious question mid-lesson.", "year_label": "Year 7"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a K-12 teacher, applying instructional design skills from corporate training to a genuinely curious age group.",
        "industry": "education", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_teacher_k12_3", "career_id": "teacher_k12",
        "person_label": "K-12 Teacher, 12 years experience",
        "background": "Taught the same subject at the same school for eight years before a sudden district budget cut eliminated their specific position.",
        "journey": "Had to requalify to teach a different, related subject within a single summer to remain employed at the same school under the district's new staffing structure.",
        "challenges": "Faced real anxiety about starting over as a less experienced teacher in a new subject after nearly a decade of expertise in the original one.",
        "turning_points": "Discovering genuine new intellectual excitement about the new subject, something the original subject hadn't produced in years, turned a forced change into an unexpected renewal.",
        "advice": "A forced subject change due to circumstances outside your control can feel like starting over, but it can also renew an interest that years of routine had quietly worn down.",
        "lessons_learned": "A sudden, unwanted professional disruption can sometimes restore an enthusiasm that years of comfortable routine had gradually eroded without you noticing.",
        "trait_tags": ["curiosity", "motivation"],
        "timeline": [
            {"stage": "first_job", "label": "Eight years, one subject", "description": "Taught the same subject at the same school for eight years.", "year_label": "Year 0"},
            {"stage": "failure", "label": "A budget cut eliminates the position", "description": "A sudden district budget cut eliminated their specific position.", "year_label": "Year 8"},
            {"stage": "turning_point", "label": "New excitement in a new subject", "description": "Requalified to teach a different subject and found genuine new intellectual excitement.", "year_label": "Year 9"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Real anxiety requalifying as a less experienced teacher in a new subject after nearly a decade of expertise.",
        "current_outcome": "Teaches a new subject after a forced budget-driven change, having rediscovered enthusiasm routine had quietly worn down.",
        "industry": "education", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_teacher_k12_4", "career_id": "teacher_k12",
        "person_label": "K-12 Teacher, 1 year experience",
        "background": "Was homeschooled through most of primary and secondary education, giving an unconventional first-hand view of alternative education before ever entering a traditional classroom.",
        "journey": "Studied education specifically to bring what worked from their own homeschool experience into mainstream classroom teaching, while adapting it to a much larger student group.",
        "challenges": "Had to unlearn assumptions built from one-on-one homeschool teaching that didn't directly translate to managing thirty students simultaneously.",
        "turning_points": "Successfully adapting a project-based learning method from their own homeschool experience for a full class, and seeing it genuinely engage students, validated the unconventional background as useful, not just unusual.",
        "advice": "An unconventional educational background of your own, like homeschooling, can be a genuine asset in teaching if you're deliberate about adapting what worked to a classroom context.",
        "lessons_learned": "Personal educational history, even one very different from a traditional classroom, can supply real, adaptable methods rather than just an unusual personal story.",
        "trait_tags": ["creativity", "learning_style"],
        "timeline": [
            {"stage": "school", "label": "Homeschooled through K-12", "description": "Was homeschooled through most of primary and secondary education.", "year_label": "Year 0"},
            {"stage": "university", "label": "Education degree", "description": "Studied education to bring homeschool methods into mainstream classroom teaching.", "year_label": "Year 12"},
            {"stage": "turning_point", "label": "Adapting a project-based method", "description": "Successfully adapted a homeschool project-based learning method for a full class.", "year_label": "Year 17"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a K-12 teacher, adapting methods from an unconventional homeschool background for classroom use.",
        "industry": "education", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_teacher_k12_5", "career_id": "teacher_k12",
        "person_label": "K-12 Teacher, 7 years experience",
        "background": "Worked in educational publishing for four years, writing textbook content without direct classroom teaching experience.",
        "journey": "Took a leave from publishing to substitute teach for a semester, purely out of curiosity about how the material was actually used, and never returned to publishing.",
        "challenges": "Had significantly underestimated how different writing curriculum content was from actually delivering it to a room of real, varied students.",
        "turning_points": "Watching a lesson they'd personally written fail badly in a real classroom, for reasons the writing process had never revealed, fundamentally changed how they thought about educational content.",
        "advice": "If you write or design educational content without classroom experience, spend real time actually teaching it — the gap between design and delivery is larger than it looks.",
        "lessons_learned": "Writing curriculum content and actually delivering it in a live classroom require different, only partially overlapping skills — direct classroom exposure changes how you write.",
        "trait_tags": ["communication", "learning_style"],
        "timeline": [
            {"stage": "first_job", "label": "Educational publishing", "description": "Worked in educational publishing for four years without direct classroom experience.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Substitute teaching out of curiosity", "description": "Took a leave to substitute teach for a semester out of curiosity.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "A written lesson fails in practice", "description": "Watched a lesson they'd written fail badly in a real classroom.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a K-12 teacher, having learned firsthand the gap between writing curriculum and delivering it live.",
        "industry": "education", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_teacher_k12_6", "career_id": "teacher_k12",
        "person_label": "K-12 Teacher, 20 years experience",
        "background": "Taught for fifteen years using largely the same lesson plans and methods, before a school-wide shift toward technology-integrated teaching required significant adaptation.",
        "journey": "Initially resisted the required technology adoption, feeling genuine skepticism about replacing methods that had worked reliably for over a decade.",
        "challenges": "Struggled visibly in the first year of the transition, with student engagement metrics that were, by the school's own measures, worse than under the old methods.",
        "turning_points": "A younger colleague's patient, unhurried mentoring on the new tools, rather than the school's formal training sessions, was what finally made the technology feel usable rather than imposed.",
        "advice": "Resisting a mandated change after years of success with the old way is a natural reaction — informal peer mentoring, not just formal training, is often what actually makes a new method click.",
        "lessons_learned": "Long professional success with one method doesn't make adapting to a genuinely new required method easier — and informal peer support often matters more than formal training in making that adaptation work.",
        "trait_tags": ["learning_style", "work_preferences"],
        "timeline": [
            {"stage": "first_job", "label": "Fifteen years, consistent methods", "description": "Taught for fifteen years using largely the same lesson plans and methods.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Struggling with mandated technology adoption", "description": "Struggled visibly in the first year of a required technology-integrated teaching shift.", "year_label": "Year 15"},
            {"stage": "turning_point", "label": "Informal peer mentoring", "description": "A younger colleague's informal mentoring made the new technology feel usable.", "year_label": "Year 16"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "A visibly difficult first year adapting to a mandated technology-integrated teaching shift after fifteen years of consistent methods.",
        "current_outcome": "Continues teaching with technology now genuinely integrated, adaptation aided more by peer mentoring than formal training.",
        "industry": "education", "story_type": "composite", "source_reference": "",
    },
    # --- Corporate Sustainability Analyst -------------------------------------
    {
        "id": "story_sustainability_analyst_2", "career_id": "sustainability_analyst",
        "person_label": "Corporate Sustainability Analyst, 2 years experience",
        "background": "Worked in oil and gas industry operations for five years, an industry with an increasingly public tension around its environmental impact.",
        "journey": "Moved internally into the same company's newly formed sustainability team, using operational knowledge of the industry to help design realistic emissions-reduction targets.",
        "challenges": "Faced skepticism from environmental advocates who assumed anyone from the fossil fuel industry couldn't genuinely contribute to sustainability work.",
        "turning_points": "A specific emissions-reduction proposal, informed by real operational constraints the external sustainability consultants hadn't understood, was the one that actually got implemented over more idealistic but impractical alternatives.",
        "advice": "Operational experience inside a high-emissions industry can be a genuine asset for realistic sustainability work, not a disqualifying conflict of interest.",
        "lessons_learned": "Practical, operationally grounded sustainability proposals sometimes succeed where more idealistic external ones fail, precisely because of insider knowledge of real constraints.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Oil and gas operations", "description": "Worked in oil and gas industry operations for five years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Internal move to sustainability", "description": "Moved internally into the company's newly formed sustainability team.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "A realistic proposal gets implemented", "description": "An operationally grounded emissions-reduction proposal was implemented over more idealistic alternatives.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a corporate sustainability analyst, operational industry knowledge now applied to realistic emissions targets.",
        "industry": "corporate sustainability", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_sustainability_analyst_3", "career_id": "sustainability_analyst",
        "person_label": "Corporate Sustainability Analyst, 5 years experience",
        "background": "Studied environmental activism-adjacent political science, initially planning a career in nonprofit environmental advocacy rather than corporate work.",
        "journey": "Took a corporate sustainability role reluctantly, mainly for the salary, after struggling to find funded nonprofit positions, expecting to eventually return to advocacy.",
        "challenges": "Felt real internal conflict for the first two years, viewing the corporate role as a compromise of their original activist values.",
        "turning_points": "Realizing a single successful internal sustainability policy affected far more emissions reduction than years of grassroots advocacy work had, at their previous nonprofit volunteering, reframed the corporate role's actual impact.",
        "advice": "Corporate sustainability work, even taken reluctantly, can produce a scale of environmental impact that's genuinely comparable to, or larger than, nonprofit advocacy work.",
        "lessons_learned": "A role taken as a values compromise can turn out to deliver more of the impact you originally wanted than the values-aligned path you'd initially preferred.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Planning nonprofit advocacy", "description": "Studied political science planning a career in nonprofit environmental advocacy.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "A reluctant corporate role", "description": "Took a corporate sustainability role reluctantly, mainly for the salary.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Corporate impact exceeds advocacy impact", "description": "A single internal sustainability policy affected more emissions reduction than years of grassroots advocacy.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Two years of internal conflict viewing the corporate role as a compromise of original activist values.",
        "current_outcome": "Works as a corporate sustainability analyst, having found a scale of environmental impact rivaling nonprofit advocacy.",
        "industry": "corporate sustainability", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_sustainability_analyst_4", "career_id": "sustainability_analyst",
        "person_label": "Senior Corporate Sustainability Analyst, 8 years experience",
        "background": "Led a sustainability initiative that was cancelled after two years of work when a change in company leadership deprioritized environmental spending.",
        "journey": "Had to rebuild the business case from scratch under new leadership, this time framing sustainability entirely in terms of cost savings and risk management rather than environmental values.",
        "challenges": "Felt significant frustration having to strip environmental language from proposals to make them palatable to leadership focused purely on financial metrics.",
        "turning_points": "The purely financially framed proposal was approved within weeks, achieving the same environmental outcome the cancelled initiative had targeted, just reached through different language.",
        "advice": "If a values-framed sustainability proposal isn't landing with leadership, reframing the same substance in purely financial terms can achieve the same real outcome.",
        "lessons_learned": "The underlying environmental outcome can sometimes be achieved just as effectively through financial framing as through values-based framing, even if the latter feels more honest.",
        "trait_tags": ["analytical_thinking", "communication"],
        "timeline": [
            {"stage": "first_job", "label": "A cancelled initiative", "description": "Led a sustainability initiative cancelled after two years when leadership deprioritized environmental spending.", "year_label": "Year 3"},
            {"stage": "failure", "label": "Stripping values language from proposals", "description": "Had to rebuild the business case, stripping environmental language for a financially focused leadership.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "A financially framed proposal succeeds", "description": "A purely financially framed proposal was approved within weeks, achieving the original environmental outcome.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Frustration reframing sustainability proposals in purely financial terms after a values-framed initiative was cancelled.",
        "current_outcome": "Works as a senior sustainability analyst, having learned financial framing can achieve the same outcomes as values-based framing.",
        "industry": "corporate sustainability", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_sustainability_analyst_5", "career_id": "sustainability_analyst",
        "person_label": "Corporate Sustainability Analyst, 1 year experience",
        "background": "Studied chemical engineering with a focus on industrial processes, without a specific interest in sustainability as a discipline.",
        "journey": "Took a role optimizing manufacturing processes for efficiency, which turned out to overlap almost entirely with reducing the company's carbon footprint.",
        "challenges": "Hadn't initially framed their engineering work as 'sustainability' at all, and had to learn the broader sustainability reporting and stakeholder communication side of the role separately.",
        "turning_points": "Realizing their efficiency optimization work was being cited in the company's public sustainability report reframed engineering process improvement as directly climate-relevant work.",
        "advice": "Efficiency-focused engineering roles often overlap substantially with sustainability outcomes, even when neither the role nor the engineer initially frames it that way.",
        "lessons_learned": "Technical efficiency work and sustainability impact can be the same work under two different names — the framing can shift how you understand your own role's significance.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Chemical engineering, industrial processes", "description": "Studied chemical engineering with a focus on industrial processes.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Manufacturing efficiency optimization", "description": "Took a role optimizing manufacturing processes for efficiency.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Cited in the sustainability report", "description": "Realized efficiency optimization work was being cited in the company's public sustainability report.", "year_label": "Year 1"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a corporate sustainability analyst, having realized efficiency-focused engineering work was climate-relevant all along.",
        "industry": "corporate sustainability", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_sustainability_analyst_6", "career_id": "sustainability_analyst",
        "person_label": "Corporate Sustainability Analyst, 4 years experience",
        "background": "Grew up in a coastal town that experienced repeated, worsening flooding events throughout their adolescence.",
        "journey": "Studied environmental science motivated directly by watching their hometown's infrastructure repeatedly fail to handle worsening flooding, aiming to work on climate resilience from inside industry rather than only government.",
        "challenges": "Struggled with a sense that corporate sustainability roles moved far too slowly relative to the urgency the flooding back home had made viscerally clear.",
        "turning_points": "Successfully pushing a company-wide climate risk assessment that led to real infrastructure investment in coastal facilities gave the abstract corporate role a concrete link back to the original motivation.",
        "advice": "If a personal experience of climate impact is your motivation, look for the specific point in a corporate sustainability role where that urgency can translate into concrete infrastructure decisions.",
        "lessons_learned": "The slow pace of corporate sustainability work can still connect to urgent, personally felt climate concerns if you find the specific decisions where that urgency actually has leverage.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "school", "label": "Repeated coastal flooding", "description": "Grew up in a coastal town that experienced repeated, worsening flooding events.", "year_label": "Year 0"},
            {"stage": "university", "label": "Environmental science, motivated by flooding", "description": "Studied environmental science motivated by watching infrastructure repeatedly fail.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "A climate risk assessment leads to investment", "description": "Pushed a company-wide climate risk assessment that led to real coastal infrastructure investment.", "year_label": "Year 10"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "A persistent sense that corporate sustainability work moved too slowly relative to the urgency of childhood flooding experiences.",
        "current_outcome": "Works as a corporate sustainability analyst, having found the specific point where corporate decisions carry real climate-resilience leverage.",
        "industry": "corporate sustainability", "story_type": "composite", "source_reference": "",
    },
]


async def seed() -> None:
    client = get_supabase_client()
    stories = [CareerStory.model_validate(s) for s in STORIES]

    def _upsert() -> None:
        client.table("career_stories").upsert(
            [s.model_dump(mode="json") for s in stories]
        ).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(stories)} business & education Journey Stories.")


if __name__ == "__main__":
    asyncio.run(seed())
