"""One-time seed script for the shared topic-keyed exploration resource
catalog, composed into Knowledge Circles.

Run via: python -m aureon.scripts.seed_topic_resources

22 broad curiosity/exploration domains spanning technology, arts,
sciences, humanities, and business — deliberately not tech-only.
Content favors domain-specific real entities over generically-famous
names, and deliberately spans multiple countries and regions (India,
Japan, Germany, Kenya, Singapore, UK, US, and more), never career-
outcome-shaped content (no colleges/companies/internships — this
catalog is exploration/curiosity-shaped: creators, hackathons, museums,
challenge platforms). Every entry carries its own `source_note` honesty
disclaimer (see domain/models/resource_domain.py). Idempotent: upserts
by id, safe to re-run.
"""

import asyncio

from aureon.domain.models.resource_domain import TopicResourceDomain
from aureon.services.supabase.client import get_supabase_client

DOMAINS: list[dict] = [
    {
        "id": "passion_ai_robotics",
        "name": "AI & Robotics",
        "keywords": ["ai", "artificial intelligence", "robotics", "machine learning", "robots"],
        "books": ["Life 3.0 by Max Tegmark", "Human Compatible by Stuart Russell", "The Alignment Problem by Brian Christian", "AI Superpowers by Kai-Fu Lee"],
        "documentaries": ["AlphaGo (2017)", "Do You Trust This Computer?", "iHuman"],
        "podcasts": ["Lex Fridman Podcast", "The TWIML AI Podcast", "Practical AI"],
        "youtube_channels": ["Two Minute Papers", "Yannic Kilcher", "Robert Miles AI Safety"],
        "creators": ["Andrej Karpathy", "Fei-Fei Li", "Demis Hassabis"],
        "communities": ["r/MachineLearning (Reddit)", "Hugging Face community", "AI4Bharat community (India)"],
        "competitions": ["Kaggle competitions", "RoboCup", "FIRST Robotics Competition"],
        "workshops": ["DeepLearning.AI workshops", "local RoboCup regional workshops"],
        "hackathons": ["AngelHack AI tracks", "local university AI hackathons"],
        "research_organizations": ["DeepMind (UK)", "AI4Bharat (India)", "RIKEN AIP (Japan)"],
        "museums_and_science_centers": ["Science Museum London AI gallery", "Miraikan — The National Museum of Emerging Science and Innovation (Tokyo)"],
        "exhibitions_and_conferences": ["NeurIPS", "Deep Learning Indaba (Africa-wide)"],
        "journals_and_newsletters": ["The Batch by DeepLearning.AI", "Import AI newsletter"],
        "learning_platforms": ["DeepLearning.AI (Coursera)", "fast.ai", "Kaggle Learn"],
        "open_source_projects": ["Hugging Face Transformers", "PyTorch", "OpenCV"],
        "challenge_platforms": ["Kaggle", "DrivenData"],
    },
    {
        "id": "passion_space_astronomy",
        "name": "Space & Astronomy",
        "keywords": ["space", "astronomy", "astrophysics", "stars", "planets"],
        "books": ["Cosmos by Carl Sagan", "Astrophysics for People in a Hurry by Neil deGrasse Tyson", "The Order of Time by Carlo Rovelli"],
        "documentaries": ["The Farthest", "In the Shadow of the Moon", "Apollo 11"],
        "podcasts": ["Planetary Radio (The Planetary Society)", "StarTalk with Neil deGrasse Tyson"],
        "youtube_channels": ["Scott Manley", "Everyday Astronaut", "PBS Space Time"],
        "creators": ["Neil deGrasse Tyson", "Sarah Al-Ahmed"],
        "communities": ["r/space (Reddit)", "local astronomy club networks"],
        "competitions": ["NASA App Development Challenge", "CanSat competition"],
        "workshops": ["local planetarium stargazing workshops", "ISRO student outreach workshops (India)"],
        "hackathons": ["NASA Space Apps Challenge"],
        "research_organizations": ["NASA (US)", "ISRO (India)", "European Space Agency"],
        "museums_and_science_centers": ["Smithsonian National Air and Space Museum (US)", "Nehru Planetarium (India)", "Tsukuba Space Center (Japan)"],
        "exhibitions_and_conferences": ["International Astronautical Congress", "Starmus Festival"],
        "journals_and_newsletters": ["The Planetary Report", "Sky & Telescope newsletter"],
        "learning_platforms": ["Coursera's Astronomy courses (University of Arizona)", "NASA's free online courses"],
        "open_source_projects": ["OpenSpace visualization software", "Stellarium planetarium software"],
        "challenge_platforms": ["NASA Space Apps Challenge platform"],
    },
    {
        "id": "passion_biology_life_sciences",
        "name": "Biology & Life Sciences",
        "keywords": ["biology", "life sciences", "genetics", "ecology", "biotech"],
        "books": ["The Gene by Siddhartha Mukherjee", "The Selfish Gene by Richard Dawkins", "Lab Girl by Hope Jahren"],
        "documentaries": ["Microcosmos", "Human: The World Within", "My Octopus Teacher"],
        "podcasts": ["This Week in Virology", "The Story Collider"],
        "youtube_channels": ["Amoeba Sisters", "iBiology"],
        "creators": ["Hope Jahren", "Jennifer Doudna"],
        "communities": ["r/biology (Reddit)", "iGEM synthetic biology community"],
        "competitions": ["iGEM — International Genetically Engineered Machine", "Regeneron Science Talent Search"],
        "workshops": ["local university open-lab days", "Cold Spring Harbor Laboratory summer workshops"],
        "hackathons": ["local biohackathon and BioMakerspace events"],
        "research_organizations": ["Cold Spring Harbor Laboratory (US)", "National Centre for Biological Sciences (India)", "Max Planck Institute for Biology (Germany)"],
        "museums_and_science_centers": ["Natural History Museum London (UK)", "National Science Centre India"],
        "exhibitions_and_conferences": ["ASCB Cell Bio conference", "iGEM Giant Jamboree"],
        "journals_and_newsletters": ["Nature News", "Science Daily biology section"],
        "learning_platforms": ["iBiology.org", "Khan Academy Biology"],
        "open_source_projects": ["OpenWorm", "BioPython"],
        "challenge_platforms": ["iGEM's own project platform"],
    },
    {
        "id": "passion_climate_environment",
        "name": "Climate & Environment",
        "keywords": ["climate", "environment", "sustainability", "ecology", "conservation"],
        "books": ["Drawdown edited by Paul Hawken", "The Uninhabitable Earth by David Wallace-Wells", "Braiding Sweetgrass by Robin Wall Kimmerer"],
        "documentaries": ["Kiss the Ground", "Chasing Coral", "Our Planet"],
        "podcasts": ["How to Save a Planet", "Outrage + Optimism"],
        "youtube_channels": ["Our Changing Climate", "Kurzgesagt – In a Nutshell"],
        "creators": ["Greta Thunberg", "Wanjira Mathai (Kenya)"],
        "communities": ["r/climate (Reddit)", "local Fridays for Future chapters"],
        "competitions": ["The Earth Prize", "Greenpreneurs global competition"],
        "workshops": ["local Climate Reality Leadership Corps trainings"],
        "hackathons": ["MIT Climate CoLab", "local climate hackathons"],
        "research_organizations": ["Potsdam Institute for Climate Impact Research (Germany)", "TERI — The Energy and Resources Institute (India)", "Rocky Mountain Institute (US)"],
        "museums_and_science_centers": ["California Academy of Sciences (US)", "Singapore Science Centre climate gallery"],
        "exhibitions_and_conferences": ["UN Climate Change Conference (COP)", "Climate Week NYC"],
        "journals_and_newsletters": ["Yale Climate Connections newsletter", "Carbon Brief"],
        "learning_platforms": ["Coursera's Climate Change courses", "Project Drawdown's free resources"],
        "open_source_projects": ["Global Forest Watch", "OpenAQ air-quality data project"],
        "challenge_platforms": ["MIT Climate CoLab"],
    },
    {
        "id": "passion_visual_arts",
        "name": "Visual Arts",
        "keywords": ["art", "painting", "drawing", "illustration", "sculpture"],
        "books": ["Ways of Seeing by John Berger", "Art & Fear by David Bayles and Ted Orland", "The Artist's Way by Julia Cameron"],
        "documentaries": ["Exit Through the Gift Shop", "Frida", "Kusama: Infinity"],
        "podcasts": ["Art Curious", "The Great Women Artists"],
        "youtube_channels": ["The Art Assignment", "Proko"],
        "creators": ["Yayoi Kusama (Japan)", "Ai Weiwei"],
        "communities": ["r/Art (Reddit)", "local art collective and co-op studios"],
        "competitions": ["Scholastic Art & Writing Awards", "International Emerging Artist Award"],
        "workshops": ["local community-center life-drawing workshops", "Sir J.J. School of Art open workshops (India)"],
        "hackathons": ["local art-and-technology hack events"],
        "research_organizations": ["Tate Research Centre (UK)"],
        "museums_and_science_centers": ["Tate Modern (UK)", "National Gallery of Modern Art (India)", "Mori Art Museum (Japan)"],
        "exhibitions_and_conferences": ["Venice Biennale", "India Art Fair"],
        "journals_and_newsletters": ["Hyperallergic newsletter", "ArtReview"],
        "learning_platforms": ["Proko figure-drawing courses", "Skillshare illustration classes"],
        "open_source_projects": ["Krita open-source painting software"],
        "challenge_platforms": ["Inktober annual drawing challenge"],
    },
    {
        "id": "passion_music",
        "name": "Music",
        "keywords": ["music", "composition", "audio production", "instrument", "songwriting"],
        "books": ["This Is Your Brain on Music by Daniel Levitin", "The Music Lesson by Victor Wooten", "How Music Works by David Byrne"],
        "documentaries": ["20 Feet from Stardom", "Score: A Film Music Documentary"],
        "podcasts": ["Song Exploder", "Switched on Pop"],
        "youtube_channels": ["Rick Beato", "Adam Neely"],
        "creators": ["Victor Wooten", "Hans Zimmer"],
        "communities": ["r/WeAreTheMusicMakers (Reddit)", "local music-production Discord servers"],
        "competitions": ["International Songwriting Competition", "Global Battle of the Bands"],
        "workshops": ["local community-college music-production workshops", "Berklee Online short courses"],
        "hackathons": ["local music-tech hackathons"],
        "research_organizations": ["IRCAM — Institute for Research and Coordination in Acoustics/Music (France)"],
        "museums_and_science_centers": ["National Museum of African American Music (US)", "The Beatles Story museum (UK)"],
        "exhibitions_and_conferences": ["SXSW Music", "WOMEX world music expo"],
        "journals_and_newsletters": ["Pitchfork newsletter", "Music Business Worldwide"],
        "learning_platforms": ["Soundfly", "Coursera's Berklee music courses"],
        "open_source_projects": ["Audacity", "MuseScore"],
        "challenge_platforms": ["NPR Tiny Desk Contest"],
    },
    {
        "id": "passion_creative_writing",
        "name": "Creative Writing",
        "keywords": ["writing", "creative writing", "storytelling", "poetry", "fiction"],
        "books": ["Bird by Bird by Anne Lamott", "On Writing by Stephen King", "The Elements of Style by Strunk and White"],
        "documentaries": ["Author: The JT LeRoy Story", "Life, Animated"],
        "podcasts": ["Writing Excuses", "The Creative Penn Podcast"],
        "youtube_channels": ["Brandon Sanderson's BYU lecture series", "Jenna Moreci"],
        "creators": ["Neil Gaiman", "Chimamanda Ngozi Adichie (Nigeria)"],
        "communities": ["r/writing (Reddit)", "NaNoWriMo community"],
        "competitions": ["National Novel Writing Month (NaNoWriMo)", "Commonwealth Short Story Prize"],
        "workshops": ["local library creative-writing workshops", "Iowa Writers' Workshop summer programs"],
        "hackathons": ["flash-fiction write-a-thons"],
        "research_organizations": ["The Poetry Foundation (US)"],
        "museums_and_science_centers": ["The Writers' Museum (Edinburgh, UK)"],
        "exhibitions_and_conferences": ["Jaipur Literature Festival (India)", "Hay Festival (UK)"],
        "journals_and_newsletters": ["The Paris Review", "Poets & Writers magazine"],
        "learning_platforms": ["MasterClass writing courses", "Coursera's creative-writing specializations"],
        "open_source_projects": ["Project Gutenberg"],
        "challenge_platforms": ["NaNoWriMo platform"],
    },
    {
        "id": "passion_game_design",
        "name": "Game Design",
        "keywords": ["game design", "gaming", "video games", "game development"],
        "books": ["The Art of Game Design by Jesse Schell", "Blood, Sweat, and Pixels by Jason Schreier", "Rules of Play by Katie Salen and Eric Zimmerman"],
        "documentaries": ["Indie Game: The Movie", "Free to Play"],
        "podcasts": ["Game Maker's Notebook", "Design Doc"],
        "youtube_channels": ["Extra Credits", "GMTK — Game Maker's Toolkit"],
        "creators": ["Jonathan Blow", "Rami Ismail (Netherlands/Indonesia)"],
        "communities": ["r/gamedev (Reddit)", "itch.io community"],
        "competitions": ["Global Game Jam", "Ludum Dare"],
        "workshops": ["local Global Game Jam site workshops"],
        "hackathons": ["Global Game Jam", "GitHub Game Off"],
        "research_organizations": ["MIT Game Lab (US)"],
        "museums_and_science_centers": ["National Videogame Museum (UK)", "Tokyo Game Show museum exhibits (Japan)"],
        "exhibitions_and_conferences": ["Game Developers Conference (GDC)", "Tokyo Game Show (Japan)"],
        "journals_and_newsletters": ["Game Developer (Gamasutra) newsletter"],
        "learning_platforms": ["Brackeys game-dev tutorials", "Unity Learn"],
        "open_source_projects": ["Godot Engine", "Unity open-source tools"],
        "challenge_platforms": ["itch.io game jams", "Ludum Dare"],
    },
    {
        "id": "passion_mathematics",
        "name": "Mathematics",
        "keywords": ["math", "mathematics", "numbers", "geometry", "algebra"],
        "books": ["A Mathematician's Lament by Paul Lockhart", "How to Solve It by George Pólya", "The Man Who Knew Infinity by Robert Kanigel"],
        "documentaries": ["The Man Who Knew Infinity", "N Is a Number: A Portrait of Paul Erdős"],
        "podcasts": ["My Favorite Theorem", "Numberphile Podcast"],
        "youtube_channels": ["3Blue1Brown", "Numberphile"],
        "creators": ["Grant Sanderson (3Blue1Brown)", "Terence Tao"],
        "communities": ["r/learnmath (Reddit)", "Art of Problem Solving community"],
        "competitions": ["International Mathematical Olympiad", "AMC/AIME (US math competitions)"],
        "workshops": ["Art of Problem Solving online workshops", "local math-circle programs"],
        "hackathons": ["MathWorks Math Modeling Challenge"],
        "research_organizations": ["Tata Institute of Fundamental Research (India)", "Clay Mathematics Institute (US)"],
        "museums_and_science_centers": ["Museum of Mathematics — MoMath (US)"],
        "exhibitions_and_conferences": ["International Congress of Mathematicians"],
        "journals_and_newsletters": ["Quanta Magazine"],
        "learning_platforms": ["Brilliant.org", "Art of Problem Solving"],
        "open_source_projects": ["GeoGebra"],
        "challenge_platforms": ["Project Euler"],
    },
    {
        "id": "passion_physics",
        "name": "Physics",
        "keywords": ["physics", "quantum", "mechanics", "energy"],
        "books": ["A Brief History of Time by Stephen Hawking", "Seven Brief Lessons on Physics by Carlo Rovelli", "QED by Richard Feynman"],
        "documentaries": ["Particle Fever", "A Brief History of Time"],
        "podcasts": ["Physics World Weekly", "StarTalk"],
        "youtube_channels": ["PBS Space Time", "minutephysics"],
        "creators": ["Sabine Hossenfelder (Germany)", "Brian Greene"],
        "communities": ["r/Physics (Reddit)", "local physics-olympiad training groups"],
        "competitions": ["International Physics Olympiad", "British Physics Olympiad"],
        "workshops": ["CERN's summer student programs", "local physics-society workshops"],
        "hackathons": ["local physics-simulation hackathons"],
        "research_organizations": ["CERN (Switzerland/France)", "RIKEN (Japan)", "Raman Research Institute (India)"],
        "museums_and_science_centers": ["CERN's Microcosm exhibition (Switzerland)", "Exploratorium (US)"],
        "exhibitions_and_conferences": ["American Physical Society March Meeting"],
        "journals_and_newsletters": ["Physics World", "Quanta Magazine physics section"],
        "learning_platforms": ["MIT OpenCourseWare Physics", "Brilliant.org physics courses"],
        "open_source_projects": ["QuTiP open-source quantum simulation toolkit"],
        "challenge_platforms": ["Physics Olympiad training platforms"],
    },
    {
        "id": "passion_psychology_behavior",
        "name": "Psychology & Behavior",
        "keywords": ["psychology", "behavior", "mind", "mental health", "cognition"],
        "books": ["Thinking, Fast and Slow by Daniel Kahneman", "Man's Search for Meaning by Viktor Frankl", "The Body Keeps the Score by Bessel van der Kolk"],
        "documentaries": ["Crazywise", "The Mask You Live In"],
        "podcasts": ["Hidden Brain", "The Happiness Lab"],
        "youtube_channels": ["Kati Morton", "Crash Course Psychology"],
        "creators": ["Angela Duckworth", "Brené Brown"],
        "communities": ["r/psychology (Reddit)", "Psi Chi psychology honor society"],
        "competitions": ["regional psychology research poster competitions"],
        "workshops": ["local peer-counseling training workshops"],
        "hackathons": ["mental-health-tech hackathons"],
        "research_organizations": ["NIMHANS — National Institute of Mental Health and Neurosciences (India)", "Max Planck Institute for Human Development (Germany)"],
        "museums_and_science_centers": ["Wellcome Collection (UK)"],
        "exhibitions_and_conferences": ["American Psychological Association Convention"],
        "journals_and_newsletters": ["Psychology Today"],
        "learning_platforms": ["Yale's The Science of Well-Being (Coursera)", "Khan Academy Psychology"],
        "open_source_projects": ["Open Science Framework replication projects"],
        "challenge_platforms": ["Open Science Framework preregistration challenges"],
    },
    {
        "id": "passion_history",
        "name": "History",
        "keywords": ["history", "historical", "archaeology", "civilization"],
        "books": ["Sapiens by Yuval Noah Harari", "Guns, Germs, and Steel by Jared Diamond", "A People's History of the United States by Howard Zinn"],
        "documentaries": ["The Vietnam War (Ken Burns)", "Civilisation (BBC)"],
        "podcasts": ["Hardcore History by Dan Carlin", "The History of Rome"],
        "youtube_channels": ["Extra History", "OverSimplified"],
        "creators": ["Dan Carlin", "Mary Beard (UK)"],
        "communities": ["r/history (Reddit)", "local historical-society volunteer networks"],
        "competitions": ["National History Day (US)"],
        "workshops": ["local museum docent-training workshops"],
        "hackathons": ["digital-history and archive hackathons"],
        "research_organizations": ["Archaeological Survey of India", "British Museum research department (UK)"],
        "museums_and_science_centers": ["British Museum (UK)", "National Museum New Delhi (India)", "Tokyo National Museum (Japan)"],
        "exhibitions_and_conferences": ["American Historical Association Annual Meeting"],
        "journals_and_newsletters": ["Smithsonian Magazine history section"],
        "learning_platforms": ["Coursera history courses (Yale, Princeton)", "Khan Academy World History"],
        "open_source_projects": ["Wikipedia history WikiProjects"],
        "challenge_platforms": ["National History Day project platform"],
    },
    {
        "id": "passion_entrepreneurship",
        "name": "Entrepreneurship",
        "keywords": ["entrepreneurship", "startup", "business", "founder"],
        "books": ["Zero to One by Peter Thiel", "The Lean Startup by Eric Ries", "Shoe Dog by Phil Knight"],
        "documentaries": ["Startup.com", "General Magic"],
        "podcasts": ["How I Built This", "Masters of Scale"],
        "youtube_channels": ["Y Combinator's Startup School", "Ali Abdaal"],
        "creators": ["Sara Blakely", "Falguni Nayar (India)"],
        "communities": ["r/startups (Reddit)", "local startup incubator meetups"],
        "competitions": ["Global Student Entrepreneur Awards", "Hult Prize"],
        "workshops": ["local Startup Weekend events"],
        "hackathons": ["Startup Weekend", "university entrepreneurship-cell hackathons"],
        "research_organizations": ["Stanford Center for Entrepreneurial Studies (US)", "Indian School of Business Entrepreneurship Centre"],
        "museums_and_science_centers": ["The Henry Ford Museum (US)"],
        "exhibitions_and_conferences": ["Web Summit", "TechCrunch Disrupt"],
        "journals_and_newsletters": ["TechCrunch newsletter", "Entrepreneur magazine"],
        "learning_platforms": ["Y Combinator's Startup School", "Coursera entrepreneurship specializations"],
        "open_source_projects": ["Indie Hackers community projects"],
        "challenge_platforms": ["Hult Prize challenge platform"],
    },
    {
        "id": "passion_film_video",
        "name": "Film & Video",
        "keywords": ["film", "filmmaking", "video", "cinema", "directing"],
        "books": ["Save the Cat by Blake Snyder", "In the Blink of an Eye by Walter Murch", "Rebel Without a Crew by Robert Rodriguez"],
        "documentaries": ["Jodorowsky's Dune", "Life Itself"],
        "podcasts": ["The Business (KCRW)", "Filmspotting"],
        "youtube_channels": ["Every Frame a Painting", "StudioBinder"],
        "creators": ["Bong Joon-ho (South Korea)", "Ava DuVernay"],
        "communities": ["r/filmmakers (Reddit)", "local film-festival volunteer networks"],
        "competitions": ["Student Academy Awards", "48 Hour Film Project"],
        "workshops": ["local community film-school weekend workshops"],
        "hackathons": ["48 Hour Film Project"],
        "research_organizations": ["British Film Institute (UK)", "Film and Television Institute of India"],
        "museums_and_science_centers": ["Academy Museum of Motion Pictures (US)"],
        "exhibitions_and_conferences": ["Sundance Film Festival", "International Film Festival of India (Goa)"],
        "journals_and_newsletters": ["IndieWire newsletter"],
        "learning_platforms": ["MasterClass filmmaking courses", "No Film School tutorials"],
        "open_source_projects": ["Blender", "DaVinci Resolve free edition community"],
        "challenge_platforms": ["48 Hour Film Project"],
    },
    {
        "id": "passion_product_ux_design",
        "name": "Product & UX Design",
        "keywords": ["design", "ux", "ui", "product design", "user experience"],
        "books": ["The Design of Everyday Things by Don Norman", "Don't Make Me Think by Steve Krug", "Hooked by Nir Eyal"],
        "documentaries": ["Objectified", "Abstract: The Art of Design"],
        "podcasts": ["Design Matters with Debbie Millman", "NN/g UX Podcast"],
        "youtube_channels": ["The Futur", "AJ&Smart"],
        "creators": ["Don Norman", "Julie Zhuo"],
        "communities": ["r/UXDesign (Reddit)", "Designer Hangout community"],
        "competitions": ["Adobe Design Achievement Awards"],
        "workshops": ["local IxDA (Interaction Design Association) chapter workshops"],
        "hackathons": ["local Design Sprint hackathons"],
        "research_organizations": ["Nielsen Norman Group (US)"],
        "museums_and_science_centers": ["Design Museum London (UK)"],
        "exhibitions_and_conferences": ["Config (Figma's conference)", "IxDA Interaction conference"],
        "journals_and_newsletters": ["UX Collective newsletter"],
        "learning_platforms": ["Interaction Design Foundation", "Google's UX Design Certificate (Coursera)"],
        "open_source_projects": ["Material Design guidelines", "Penpot open-source design tool"],
        "challenge_platforms": ["Daily UI challenge"],
    },
    {
        "id": "passion_social_impact_community",
        "name": "Social Impact & Community",
        "keywords": ["social impact", "community", "nonprofit", "activism"],
        "books": ["How to Change the World by David Bornstein", "Banker to the Poor by Muhammad Yunus", "Give and Take by Adam Grant"],
        "documentaries": ["Waging Change", "Poverty, Inc."],
        "podcasts": ["Freakonomics Radio (development episodes)", "Community Signal"],
        "youtube_channels": ["TED Talks social-entrepreneurship playlist"],
        "creators": ["Muhammad Yunus (Bangladesh)", "Jacqueline Novogratz"],
        "communities": ["r/nonprofit (Reddit)", "local Net Impact chapters"],
        "competitions": ["Hult Prize", "Global Social Venture Competition"],
        "workshops": ["local community-organizing training workshops"],
        "hackathons": ["Random Hacks of Kindness"],
        "research_organizations": ["Skoll Centre for Social Entrepreneurship (Oxford, UK)", "Ashoka (global, strong presence in India and Africa)"],
        "museums_and_science_centers": ["National Museum of African American History and Culture (US)", "Gandhi Smriti (India)"],
        "exhibitions_and_conferences": ["Skoll World Forum", "Social Enterprise World Forum"],
        "journals_and_newsletters": ["Stanford Social Innovation Review"],
        "learning_platforms": ["+Acumen courses", "Coursera social-entrepreneurship specializations"],
        "open_source_projects": ["Ushahidi open-source crisis-mapping platform (Kenya)"],
        "challenge_platforms": ["Hult Prize challenge platform"],
    },
    {
        "id": "passion_sports_athletics",
        "name": "Sports & Athletics",
        "keywords": ["sports", "athletics", "fitness", "training"],
        "books": ["The Sports Gene by David Epstein", "Relentless by Tim Grover", "Moneyball by Michael Lewis"],
        "documentaries": ["The Last Dance", "Free Solo"],
        "podcasts": ["The Bill Simmons Podcast", "The Real Science of Sport"],
        "youtube_channels": ["Team Whistle", "GMB Fitness"],
        "creators": ["David Epstein", "Eliud Kipchoge (Kenya)"],
        "communities": ["r/sportsanalytics (Reddit)", "local youth-league coaching networks"],
        "competitions": ["Youth Olympic Games", "local school athletics championships"],
        "workshops": ["local coaching-certification workshops"],
        "hackathons": ["sports-analytics hackathons"],
        "research_organizations": ["Australian Institute of Sport", "German Sport University Cologne"],
        "museums_and_science_centers": ["National Sports Museum (Australia)", "The Olympic Museum (Switzerland)"],
        "exhibitions_and_conferences": ["MIT Sloan Sports Analytics Conference"],
        "journals_and_newsletters": ["ESPN's The Undefeated newsletter"],
        "learning_platforms": ["NASM fitness certification courses", "Coursera sports-science courses"],
        "open_source_projects": ["Kaggle sports-analytics open datasets"],
        "challenge_platforms": ["Kaggle sports-prediction competitions"],
    },
    {
        "id": "passion_fashion_textiles",
        "name": "Fashion & Textiles",
        "keywords": ["fashion", "textiles", "clothing", "design"],
        "books": ["Gods and Kings by Dana Thomas", "Overdressed by Elizabeth Cline", "The Fashion System by Roland Barthes"],
        "documentaries": ["The True Cost", "Dior and I"],
        "podcasts": ["Business of Fashion Podcast"],
        "youtube_channels": ["Business of Fashion (YouTube)"],
        "creators": ["Diane von Fürstenberg", "Sabyasachi Mukherjee (India)"],
        "communities": ["r/fashiondesign (Reddit)", "local sewing and textile guilds"],
        "competitions": ["International Fashion Showcase", "Redress Design Award (Hong Kong)"],
        "workshops": ["local pattern-making and sewing workshops"],
        "hackathons": ["fashion-tech hackathons"],
        "research_organizations": ["London College of Fashion research centre (UK)"],
        "museums_and_science_centers": ["Victoria and Albert Museum fashion galleries (UK)", "Calico Museum of Textiles (India)"],
        "exhibitions_and_conferences": ["Lakmé Fashion Week (India)", "Copenhagen Fashion Week"],
        "journals_and_newsletters": ["Business of Fashion newsletter"],
        "learning_platforms": ["Parsons' fashion courses on edX", "Skillshare sewing classes"],
        "open_source_projects": ["Seamly2D open-pattern sewing software"],
        "challenge_platforms": ["Redress Design Award challenge"],
    },
    {
        "id": "passion_food_culinary_arts",
        "name": "Food & Culinary Arts",
        "keywords": ["cooking", "culinary", "food", "baking", "chef"],
        "books": ["Salt, Fat, Acid, Heat by Samin Nosrat", "Kitchen Confidential by Anthony Bourdain", "On Food and Cooking by Harold McGee"],
        "documentaries": ["Chef's Table", "Jiro Dreams of Sushi"],
        "podcasts": ["The Splendid Table", "Home Cooking"],
        "youtube_channels": ["Bon Appétit", "Joshua Weissman"],
        "creators": ["Samin Nosrat", "Massimo Bottura (Italy)"],
        "communities": ["r/Cooking (Reddit)", "local culinary-guild communities"],
        "competitions": ["Bocuse d'Or", "local Junior Chef competitions"],
        "workshops": ["Le Cordon Bleu short courses", "local community cooking classes"],
        "hackathons": ["food-tech hackathons"],
        "research_organizations": ["Culinary Institute of America research programs (US)"],
        "museums_and_science_centers": ["Museum of Food and Drink (US)"],
        "exhibitions_and_conferences": ["Madrid Fusión", "World Street Food Congress (Singapore)"],
        "journals_and_newsletters": ["Bon Appétit newsletter"],
        "learning_platforms": ["MasterClass culinary courses", "America's Test Kitchen online school"],
        "open_source_projects": ["OpenRecipes open data project"],
        "challenge_platforms": ["local Junior MasterChef-style competitions"],
    },
    {
        "id": "passion_languages_linguistics",
        "name": "Languages & Linguistics",
        "keywords": ["language", "linguistics", "languages", "translation"],
        "books": ["Fluent Forever by Gabriel Wyner", "The Language Instinct by Steven Pinker", "Babel by Gaston Dorren"],
        "documentaries": ["The Linguists", "Language Matters with Bob Holman"],
        "podcasts": ["Lingthusiasm", "The Allusionist"],
        "youtube_channels": ["Langfocus", "NativLang"],
        "creators": ["Gretchen McCulloch (Lingthusiasm)", "Ken Jennings"],
        "communities": ["r/languagelearning (Reddit)", "local language-exchange meetups"],
        "competitions": ["National Spelling Bee (US)", "Linguistics Olympiad"],
        "workshops": ["local language-exchange conversation workshops"],
        "hackathons": ["language-tech hackathons"],
        "research_organizations": ["Max Planck Institute for Psycholinguistics (Netherlands)", "Living Tongues Institute for Endangered Languages"],
        "museums_and_science_centers": ["The British Library language exhibits (UK)"],
        "exhibitions_and_conferences": ["Linguistic Society of America Annual Meeting"],
        "journals_and_newsletters": ["Language Log"],
        "learning_platforms": ["Duolingo", "italki live tutors"],
        "open_source_projects": ["Tatoeba open sentence-translation database"],
        "challenge_platforms": ["Linguistics Olympiad problem sets"],
    },
    {
        "id": "passion_philosophy_ethics",
        "name": "Philosophy & Ethics",
        "keywords": ["philosophy", "ethics", "logic", "morality"],
        "books": ["Meditations by Marcus Aurelius", "Justice by Michael Sandel", "The Ethics of Ambiguity by Simone de Beauvoir"],
        "documentaries": ["Examined Life", "Waking Life"],
        "podcasts": ["Philosophize This!", "The Partially Examined Life"],
        "youtube_channels": ["CrashCourse Philosophy", "Wireless Philosophy"],
        "creators": ["Michael Sandel", "Kwame Anthony Appiah"],
        "communities": ["r/philosophy (Reddit)", "local philosophy discussion clubs"],
        "competitions": ["National Ethics Bowl"],
        "workshops": ["local Socratic-seminar reading groups"],
        "hackathons": ["AI-ethics-focused hackathons"],
        "research_organizations": ["Oxford Uehiro Centre for Practical Ethics (UK)"],
        "museums_and_science_centers": ["Acropolis Museum (Greece)"],
        "exhibitions_and_conferences": ["American Philosophical Association meetings"],
        "journals_and_newsletters": ["Aeon essays newsletter"],
        "learning_platforms": ["Harvard's Justice course (edX)", "Wireless Philosophy videos"],
        "open_source_projects": ["Stanford Encyclopedia of Philosophy (open access)"],
        "challenge_platforms": ["National Ethics Bowl case platform"],
    },
    {
        "id": "passion_economics_finance",
        "name": "Economics & Finance",
        "keywords": ["economics", "finance", "markets", "trade"],
        "books": ["Freakonomics by Steven Levitt and Stephen Dubner", "Poor Economics by Abhijit Banerjee and Esther Duflo", "The Intelligent Investor by Benjamin Graham"],
        "documentaries": ["Inside Job", "The Ascent of Money"],
        "podcasts": ["Planet Money", "Freakonomics Radio"],
        "youtube_channels": ["Economics Explained", "Marginal Revolution University"],
        "creators": ["Esther Duflo", "Raghuram Rajan (India)"],
        "communities": ["r/economics (Reddit)", "local investment-club networks"],
        "competitions": ["National Economics Challenge", "Fed Challenge"],
        "workshops": ["local investment-literacy workshops"],
        "hackathons": ["fintech hackathons"],
        "research_organizations": ["National Bureau of Economic Research (US)", "Abdul Latif Jameel Poverty Action Lab — J-PAL"],
        "museums_and_science_centers": ["Museum of American Finance (US)"],
        "exhibitions_and_conferences": ["American Economic Association Annual Meeting"],
        "journals_and_newsletters": ["The Economist's free newsletters"],
        "learning_platforms": ["Khan Academy Economics", "Marginal Revolution University"],
        "open_source_projects": ["World Bank Open Data project"],
        "challenge_platforms": ["National Economics Challenge platform"],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    domains = [TopicResourceDomain.model_validate(d) for d in DOMAINS]

    def _upsert() -> None:
        client.table("topic_resource_domains").upsert([d.model_dump(mode="json") for d in domains]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(domains)} passion resource domains.")


if __name__ == "__main__":
    asyncio.run(seed())
