"""Connect Batch 1 — Expert Connect seed data, seventh wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch7
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_marine_biologist_keanu_makoa",
        "name": "Keanu Makoa, Marine Biologist",
        "role_type": "researcher", "field": "marine biology", "bio": "Studies coral reef resilience for a Pacific marine research institute; a major coral restoration project he led died off completely within a year.",
        "trait_tags": ["curiosity", "persistence"], "learning_style_fit": "Students who love the ocean and want real research work, not just diving for fun.",
        "organization": "A Pacific marine research institute", "years_experience": 9, "journey_highlights": ["His first major coral restoration project died off entirely within a year", "A redesigned restoration method he developed has since spread to reefs across the Pacific"],
        "discussion_topics": ["Recovering from a total project failure", "Marine biology as fieldwork-heavy research", "Coral reef conservation realities"],
        "profession": "Marine Research Biologist", "specialization": "Coral reef restoration", "country": "Fiji", "city": "Suva",
        "industries": ["environmental conservation", "research"], "education": ["BSc Marine Biology, University of the South Pacific", "PhD Marine Ecology, James Cook University"],
        "current_role": "Senior Research Scientist, Coral Restoration", "languages": ["English", "Fijian"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who love the ocean and want real research, not recreational diving", "Students who've had a major project completely fail", "Students interested in climate-related conservation work"],
        "career_ids": ["conservation_biologist"],
        "career_journey": [
            {"stage": "university", "label": "BSc Marine Biology, then PhD Marine Ecology", "description": "Grew up diving on reefs already visibly damaged by warming waters.", "year_label": "2010-2018"},
            {"stage": "first_job", "label": "Led his first independent coral restoration project", "description": "Transplanted coral fragments onto a degraded reef section using a widely-used standard technique.", "year_label": "2018"},
            {"stage": "failure", "label": "The entire restoration site died off within a year due to an unanticipated heat stress event", "description": "Years of planning and funding were lost, and he seriously questioned whether restoration work was worth pursuing at all given the pace of warming.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Developed a new restoration method selecting for naturally heat-resistant coral genotypes", "description": "The redesigned approach has since been adopted by restoration projects across the Pacific.", "year_label": "2021"},
            {"stage": "current_role", "label": "Senior Research Scientist, Coral Restoration", "description": "Leads a research program focused on climate-resilient reef restoration.", "year_label": "2022-present"},
        ],
        "day_in_the_life": "A mix of dive-based fieldwork monitoring reef sites and lab-based genetic and thermal tolerance analysis.",
        "weekly_routine": "Field dive days alternate with lab analysis and grant-writing periods.",
        "biggest_challenges": ["The pace of ocean warming outstripping restoration science's ability to keep up", "The emotional toll of watching a reef ecosystem visibly decline over a research career"],
        "favourite_part": "Returning to a restoration site years later and finding it not just surviving but thriving.",
        "biggest_misconceptions": ["That marine biology is mostly recreational diving", "That a failed restoration project means the underlying science or the researcher's skill was flawed"],
        "what_surprised_them": "How much genetic variation within a single coral species matters for real-world resilience.",
        "biggest_mistake": "My first restoration project used standard coral fragments without screening for heat tolerance, assuming the technique that worked elsewhere would transfer directly. It didn't account for how quickly local conditions were changing, and the entire site was lost. I now always screen for genetic resilience before any new restoration effort.",
        "one_regret": "I regret not questioning the standard restoration technique sooner — I trusted established methods without adequately accounting for how fast local ocean conditions were shifting.",
        "salary_reality": "Marine research salaries in Fiji rely heavily on international grant funding rather than stable institutional pay, which creates real career uncertainty.",
        "work_life_balance": "Field seasons involve intense, sometimes physically demanding diving work; lab seasons are more predictable.",
        "daily_skills": ["marine field research", "coral genetics", "grant writing"],
        "daily_tools": ["Scientific diving equipment", "genetic analysis lab tools"],
        "recommended_books": ["The Reef by Iain McCalman"],
        "recommended_communities": ["Pacific coral reef research network"],
        "advice_for_beginners": "Never assume a standard technique will transfer to your specific local conditions without testing — my total project loss came from exactly that assumption.",
        "advice_for_parents": "Marine conservation research is genuine, rigorous science with real career paths, not just an extension of a childhood love of the ocean.",
        "faqs": [{"question": "Is marine biology mostly about diving?", "answer": "Diving is a real part of fieldwork, but the job also involves significant lab analysis, data work, and grant writing — it's a genuine research career, not primarily recreational."}],
        "projects": ["Developed a heat-resilient coral restoration method now used across the Pacific"], "research": ["Published research on coral genotype selection for climate resilience"],
        "certifications": ["Scientific diving certification"], "conferences": ["International Coral Reef Symposium"], "organizations": [],
        "volunteer_work": ["Trains local community members in reef monitoring techniques"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_tax_consultant_henrik_olsen",
        "name": "Henrik Olsen, Tax Consultant",
        "role_type": "industry_professional", "field": "tax and finance", "bio": "Advises small businesses on tax strategy; made an error on an early client's filing that led to a significant, personally-covered penalty.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who like detail-oriented, rules-based work with real financial consequences.",
        "organization": "An independent tax consultancy", "years_experience": 11, "journey_highlights": ["A filing error led him to personally cover a client's tax penalty", "Now advises over 50 small businesses on tax strategy"],
        "discussion_topics": ["Making a costly professional error and taking responsibility", "Tax consulting as an independent career", "Working with small business owners"],
        "profession": "Independent Tax Consultant", "specialization": "Small business tax strategy", "country": "Norway", "city": "Oslo",
        "industries": ["finance", "tax and accounting"], "education": ["BA Economics, University of Oslo", "Professional tax advisor certification"],
        "current_role": "Founder, Independent Tax Consultancy", "languages": ["Norwegian", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in tax and finance as detail-oriented, rules-based work", "Students who've made a costly professional error", "Students considering independent consulting versus working at a larger firm"],
        "career_ids": ["accountant"],
        "career_journey": [
            {"stage": "university", "label": "BA Economics", "description": "Took an interest in tax policy during an elective course.", "year_label": "2007-2010"},
            {"stage": "first_job", "label": "Junior tax associate at an accounting firm", "description": "Learned tax filing fundamentals under senior supervision.", "year_label": "2010-2014"},
            {"stage": "failure", "label": "Made a filing error for an early independent client that triggered a significant tax penalty", "description": "Personally covered the penalty out of his own savings to make the client whole, a costly and humbling decision.", "year_label": "2015"},
            {"stage": "turning_point", "label": "Built a rigorous personal double-checking system for every filing", "description": "Never repeated a similar error in the years since.", "year_label": "2016"},
            {"stage": "current_role", "label": "Founder, Independent Tax Consultancy", "description": "Now advises over 50 small businesses on tax strategy.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "Client consultations, detailed filing review, and staying current on frequently changing tax regulations.",
        "weekly_routine": "Steady client work most of the year, with intense filing season crunches around tax deadlines.",
        "biggest_challenges": ["The real financial consequences of any filing error", "Constantly changing tax regulations requiring continuous learning"],
        "favourite_part": "Helping a small business owner find a legitimate tax strategy that meaningfully improves their financial position.",
        "biggest_misconceptions": ["That tax consulting is simple, mechanical work", "That a costly professional error should be hidden rather than owned"],
        "what_surprised_them": "How much genuine judgment and up-to-date knowledge tax work requires, beyond following fixed rules.",
        "biggest_mistake": "I filed a client's return without a proper second review, trusting my own single pass through the numbers during a particularly busy period. The resulting error cost real money, and I chose to cover the penalty myself rather than let the client bear a mistake that was entirely mine.",
        "one_regret": "I don't regret covering the client's penalty, but I regret not having a review system in place before that error happened — it was an entirely preventable mistake.",
        "salary_reality": "Independent tax consulting can be very profitable once established in Norway, though building an initial client base took several genuinely lean years.",
        "work_life_balance": "Reasonable most of the year, with real intensity during tax filing season.",
        "daily_skills": ["tax law knowledge", "financial analysis", "client advisory"],
        "daily_tools": ["Tax preparation software", "financial modeling spreadsheets"],
        "recommended_books": ["Rich Dad's Guide to Investing tax chapters, or a local equivalent tax strategy guide"],
        "recommended_communities": ["Norwegian tax advisors association"],
        "advice_for_beginners": "Build a rigorous double-check system into every filing from day one — my costly error came from trusting a single pass through the numbers during a busy period.",
        "advice_for_parents": "A costly professional mistake, especially one handled with real integrity like taking responsibility, is a formative lesson, not a permanent black mark.",
        "faqs": [{"question": "Is independent tax consulting a financially stable career?", "answer": "It can become very stable once you build a client base, though the first few years often involve real income unpredictability."}],
        "projects": [], "research": [], "certifications": ["Certified Tax Advisor, Norway"],
        "conferences": [], "organizations": ["Norwegian tax advisors association"],
        "volunteer_work": ["Offers free tax workshops for new small business owners"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_supply_chain_manager_priyanka_shah",
        "name": "Priyanka Shah, Supply Chain Manager",
        "role_type": "industry_professional", "field": "supply chain management", "bio": "Manages global supply chain operations for a consumer electronics company; a shipping decision she made caused a major product to arrive three months late.",
        "trait_tags": ["analytical_thinking", "systems_thinking"], "learning_style_fit": "Students who like complex logistics puzzles with real, global-scale consequences.",
        "organization": "A consumer electronics company", "years_experience": 10, "journey_highlights": ["A shipping route decision delayed a major product launch by three months", "Redesigned the company's shipping contingency planning entirely"],
        "discussion_topics": ["Recovering from a costly logistics failure", "Supply chain management as a global, strategic career", "What happened during major global shipping disruptions"],
        "profession": "Global Supply Chain Manager", "specialization": "Consumer electronics logistics", "country": "India", "city": "Mumbai",
        "industries": ["logistics", "manufacturing"], "education": ["BEng Industrial Engineering, Indian Institute of Technology Bombay", "MBA, Indian Institute of Management Ahmedabad"],
        "current_role": "Head of Global Supply Chain", "languages": ["English", "Hindi", "Gujarati"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like complex systems and logistics puzzles", "Students interested in global operations and international trade", "Students who've made a decision with major downstream consequences"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BEng Industrial Engineering, then MBA", "description": "Combined technical systems training with business strategy.", "year_label": "2009-2015"},
            {"stage": "first_job", "label": "Supply chain analyst", "description": "Learned logistics operations from the ground up before taking on major routing decisions.", "year_label": "2015-2018"},
            {"stage": "failure", "label": "Chose a shipping route that proved vulnerable to a major disruption, delaying a product launch by three months", "description": "The decision cost the company significant revenue and damaged a key retail partnership.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Redesigned the company's entire shipping contingency and route diversification strategy", "description": "Built in redundancy that has since prevented similar disruptions from causing major delays.", "year_label": "2020"},
            {"stage": "current_role", "label": "Head of Global Supply Chain", "description": "Now oversees logistics strategy across multiple international markets.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Monitoring global shipping data, coordinating with manufacturing and retail partners, and managing risk across the supply chain.",
        "weekly_routine": "Strategic planning and data review most weeks, with urgent problem-solving whenever disruptions occur.",
        "biggest_challenges": ["The genuine unpredictability of global shipping and geopolitical disruptions", "Balancing cost efficiency against resilience to disruption"],
        "favourite_part": "A well-executed contingency plan that keeps products moving despite a real, unexpected disruption.",
        "biggest_misconceptions": ["That supply chain management is just tracking packages", "That a major logistics failure reflects poor overall competence rather than genuine, hard-to-predict risk"],
        "what_surprised_them": "How much of the job is scenario planning for disruptions that may never happen, not just optimizing the normal case.",
        "biggest_mistake": "I chose the most cost-efficient shipping route for a major product launch without adequately weighing its vulnerability to a specific known disruption risk. When that risk materialized, we had no real backup plan, and it cost us three months and a damaged partnership. I now always build contingency routing into every major logistics decision.",
        "one_regret": "I regret prioritizing cost efficiency so heavily on that decision — the money saved on the cheaper route was dwarfed by what the delay ultimately cost the company.",
        "salary_reality": "Supply chain management pays very well in India's growing manufacturing and consumer goods sectors, especially at senior strategic levels.",
        "work_life_balance": "Generally steady, with real intensity during major disruptions or product launches.",
        "daily_skills": ["logistics planning", "risk management", "cross-border trade knowledge"],
        "daily_tools": ["Supply chain management software", "logistics data analytics tools"],
        "recommended_books": ["The Resilient Enterprise by Yossi Sheffi"],
        "recommended_communities": ["Indian supply chain professionals network"],
        "advice_for_beginners": "Always build contingency planning into major logistics decisions, even when it costs more upfront — my three-month delay came from prioritizing cost savings over resilience.",
        "advice_for_parents": "A costly logistics decision that goes wrong due to genuinely unpredictable global disruptions isn't a sign of poor judgment — it's a normal, if painful, part of managing complex global systems.",
        "faqs": [{"question": "Is supply chain management a growing career field?", "answer": "Yes, especially given recent global disruptions that have made resilient supply chain expertise more valued than ever."}],
        "projects": ["Redesigned the company's global shipping contingency strategy"], "research": [],
        "certifications": ["APICS Certified Supply Chain Professional"], "conferences": [], "organizations": [],
        "volunteer_work": ["Mentors engineering students transitioning into supply chain careers"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_occupational_therapist_grace_lindberg",
        "name": "Grace Lindberg, Occupational Therapist",
        "role_type": "industry_professional", "field": "occupational therapy", "bio": "Works with stroke survivors on rehabilitation at a hospital; her first patient after certification made almost no progress for months, which shook her confidence badly.",
        "trait_tags": ["empathy", "persistence"], "learning_style_fit": "Students interested in helping people regain independence after illness or injury.",
        "organization": "A hospital rehabilitation unit", "years_experience": 9, "journey_highlights": ["Her first post-certification patient showed almost no progress for months", "That same patient eventually regained enough function to live independently again"],
        "discussion_topics": ["Handling a case where progress feels impossibly slow", "Occupational therapy vs. physical therapy", "What sustains you through slow rehabilitation work"],
        "profession": "Occupational Therapist", "specialization": "Stroke rehabilitation", "country": "Sweden", "city": "Malmö",
        "industries": ["healthcare"], "education": ["MSc Occupational Therapy, Lund University"],
        "current_role": "Senior Occupational Therapist", "languages": ["Swedish", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students interested in helping people regain daily life skills after illness or injury", "Students who need patience with genuinely slow, incremental progress", "Students confused about occupational therapy versus physical therapy"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "MSc Occupational Therapy", "description": "Drawn to the field's focus on practical daily-life independence, not just physical function.", "year_label": "2011-2016"},
            {"stage": "first_job", "label": "Junior occupational therapist at a hospital rehabilitation unit", "description": "Her first major stroke patient showed almost no visible progress for the first four months of treatment.", "year_label": "2016-2017"},
            {"stage": "failure", "label": "Began to doubt her own clinical competence during that stalled case", "description": "Considered whether she'd chosen the wrong specialty entirely.", "year_label": "2017"},
            {"stage": "turning_point", "label": "The patient's progress finally accelerated in month five, and he eventually regained independent living ability", "description": "This case taught her that slow visible progress doesn't mean no progress is happening.", "year_label": "2017"},
            {"stage": "current_role", "label": "Senior Occupational Therapist", "description": "Now specializes in complex stroke rehabilitation cases.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Direct patient therapy sessions focused on relearning daily tasks like dressing, cooking, and mobility.",
        "weekly_routine": "Structured patient sessions throughout the week, with regular team meetings alongside physicians and physical therapists.",
        "biggest_challenges": ["Sustaining motivation and hope through genuinely slow-progress cases", "Managing patient and family frustration during difficult recovery periods"],
        "favourite_part": "A patient regaining a specific, meaningful daily task — making their own coffee, buttoning a shirt.",
        "biggest_misconceptions": ["That occupational therapy is the same as physical therapy", "That slow visible progress means treatment isn't working"],
        "what_surprised_them": "How much psychological resilience, both hers and the patient's, matters in recovery as much as the clinical technique.",
        "biggest_mistake": "During that stalled first case, I nearly recommended discontinuing intensive therapy after four months of minimal visible progress, based purely on short-term metrics rather than the full recovery trajectory research actually supports. I'm grateful a senior colleague urged patience, because the patient's real progress came just weeks later.",
        "one_regret": "I regret how much self-doubt I let that slow case create — I nearly let it convince me I'd chosen the wrong career.",
        "salary_reality": "Occupational therapy salaries in Sweden are stable within the public healthcare system, though not among the highest-paid healthcare specialties.",
        "work_life_balance": "Generally predictable clinical hours without emergency on-call demands.",
        "daily_skills": ["functional assessment", "rehabilitation planning", "patient motivation"],
        "daily_tools": ["Adaptive equipment", "standardized functional assessment tools"],
        "recommended_books": ["My Stroke of Insight by Jill Bolte Taylor"],
        "recommended_communities": ["Swedish Association of Occupational Therapists"],
        "advice_for_beginners": "Trust the full recovery timeline, not just short-term progress metrics — my instinct to give up on a stalled case nearly cost a patient his eventual full recovery.",
        "advice_for_parents": "Occupational therapy requires real patience with slow, sometimes invisible progress — that's the nature of rehabilitation work, not a sign it isn't working.",
        "faqs": [{"question": "What's the difference between occupational and physical therapy?", "answer": "Physical therapy focuses more on physical function and movement; occupational therapy focuses on regaining the ability to perform meaningful daily life activities."}],
        "projects": [], "research": [], "certifications": ["Licensed Occupational Therapist, Sweden"],
        "conferences": [], "organizations": ["Swedish Association of Occupational Therapists"],
        "volunteer_work": ["Supports a peer group for occupational therapists managing difficult, slow-progress cases"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch7).")


if __name__ == "__main__":
    asyncio.run(seed())
