"""Knowledge Circles seed data (Connect Batch 2) — one KnowledgeCircle
per CareerWorld (31 total), reusing CareerWorld's already-curated,
career-ecosystem-shaped domain names rather than inventing a fifth,
competing taxonomy (see the Connect Batch 2 plan's Decisions Log).

Each circle only carries the fields genuinely missing from every other
catalog model (overview, what_this_field_is_about, beginner_projects,
advanced_projects, laboratories, startups, ngos, scholarships) — every
other resource category (books, communities, conferences, etc.) is
composed at read time from the linked CareerWorld, TopicResourceDomain(s),
matching Career industries, matching Trends, and matching LifeMissions
by `knowledge_circle_service.py::build_circle_view`, never re-authored
here.

Real, well-known organizations are used where genuinely applicable
(same convention as `seed_career_worlds.py`'s companies/videos lists) —
illustrative and honestly labeled via `source_note`, never claimed as a
continuously verified or exhaustive directory.

Run via: python -m aureon.scripts.seed_knowledge_circles
Idempotent: safe to re-run (upsert on id).
"""

import asyncio

from aureon.domain.models.knowledge_circle import KnowledgeCircle
from aureon.services.supabase.client import get_supabase_client

CIRCLES: list[dict] = [
    {
        "id": "circle_space", "name": "Space",
        "overview": "Space is where physics, engineering, and mission operations meet — designing, building, launching, and operating everything from small CubeSats to interplanetary probes.",
        "what_this_field_is_about": "Most of the work happens years before any launch: structural analysis, orbital mechanics, systems testing, and the unglamorous engineering discipline of building something that has to work perfectly the first time, with no chance of an in-field repair.",
        "beginner_projects": ["Build and fly a model or high-power rocket", "Join a CanSat or student satellite competition team", "Simulate an orbital transfer using open-source astrodynamics software", "Build a ground station to receive real satellite telemetry"],
        "advanced_projects": ["Design and fly a CubeSat through a university or amateur program", "Contribute to an open-source satellite attitude-control system", "Build a Mars rover analog for a robotics competition"],
        "laboratories": ["NASA Jet Propulsion Laboratory", "ESA European Space Research and Technology Centre", "ISRO Satellite Centre"],
        "startups": ["Rocket Lab", "Relativity Space", "Astroscale"],
        "ngos": ["The Planetary Society", "Space Generation Advisory Council"],
        "scholarships": ["NASA Space Grant Fellowship", "ESA Academy programmes", "International Space University scholarships"],
        "linked_career_world_id": "world_space",
        "linked_topic_domain_ids": ["passion_space_astronomy"],
        "related_career_industries": ["aerospace"],
        "related_trend_ids": ["trend_space_commercialization"],
        "related_life_mission_ids": ["mission_explore_space"],
    },
    {
        "id": "circle_biotechnology", "name": "Biotechnology",
        "overview": "Biotechnology applies biology at the molecular and cellular level to real problems in medicine, agriculture, and industry — from gene therapies to lab-grown materials.",
        "what_this_field_is_about": "The daily work spans wet-lab experimentation, computational analysis of biological data, and increasingly, the two working together as computational biology and genomics mature.",
        "beginner_projects": ["Complete an online course in molecular biology or bioinformatics basics", "Analyze a public genomic dataset with beginner-friendly tools", "Volunteer in an undergraduate research lab", "Enter a synthetic biology student competition (iGEM)"],
        "advanced_projects": ["Contribute to an open-source bioinformatics pipeline", "Publish undergraduate research in a student journal", "Design a CRISPR-based experiment under lab supervision"],
        "laboratories": ["Broad Institute of MIT and Harvard", "Wellcome Sanger Institute", "Max Planck Institute of Molecular Cell Biology and Genetics"],
        "startups": ["Ginkgo Bioworks", "Recursion Pharmaceuticals", "Benchling"],
        "ngos": ["iGEM Foundation", "Wellcome Trust"],
        "scholarships": ["Wellcome Trust PhD Studentships", "Boehringer Ingelheim Fonds fellowships", "HHMI Gilliam Fellowships"],
        "linked_career_world_id": "world_biotechnology",
        "linked_topic_domain_ids": ["passion_biology_life_sciences"],
        "related_career_industries": ["biotechnology"],
        "related_trend_ids": ["trend_genomics_cost_decline", "trend_ai_assisted_scientific_discovery"],
        "related_life_mission_ids": ["mission_improve_healthcare", "mission_advance_science"],
    },
    {
        "id": "circle_marine_sciences", "name": "Marine Sciences",
        "overview": "Marine sciences study the ocean itself — its ecosystems, chemistry, and physical processes — and how human activity is reshaping all three.",
        "what_this_field_is_about": "Work ranges from scuba-based field surveys and research cruises to lab analysis of water samples and climate modeling of ocean systems.",
        "beginner_projects": ["Volunteer with a local beach or reef cleanup and monitoring program", "Get scientific diving certified", "Analyze open ocean-temperature datasets", "Join a citizen-science marine species tracking project"],
        "advanced_projects": ["Participate in a research cruise as a student assistant", "Contribute to a coral reef restoration project", "Build a low-cost ocean sensor for a citizen-science network"],
        "laboratories": ["Woods Hole Oceanographic Institution", "Scripps Institution of Oceanography", "Monterey Bay Aquarium Research Institute"],
        "startups": ["Coral Vita", "Notpla"],
        "ngos": ["Ocean Conservancy", "Mission Blue"],
        "scholarships": ["NOAA Hollings Scholarship", "Woods Hole Summer Student Fellowship"],
        "linked_career_world_id": "world_marine_sciences",
        "linked_topic_domain_ids": ["passion_biology_life_sciences", "passion_climate_environment"],
        "related_career_industries": ["environmental conservation"],
        "related_trend_ids": ["trend_climate_adaptation_engineering"],
        "related_life_mission_ids": ["mission_protect_wildlife", "mission_protect_nature"],
    },
    {
        "id": "circle_public_policy", "name": "Public Policy",
        "overview": "Public policy is the discipline of designing, analyzing, and implementing the rules and programs governments use to address collective problems.",
        "what_this_field_is_about": "Analysts spend most of their time reading evidence, modeling tradeoffs, and writing clearly for decision-makers who need to act under real time pressure and political constraint.",
        "beginner_projects": ["Analyze a local government budget or policy proposal", "Intern with a city council or local representative's office", "Write a policy memo on a real, current issue", "Join a Model UN or policy debate program"],
        "advanced_projects": ["Complete a policy fellowship with a government office", "Publish a policy brief with a think tank", "Build a data model evaluating a real policy's outcomes"],
        "laboratories": ["Harvard Kennedy School policy labs", "Brookings Institution research centers"],
        "startups": ["GovTech-focused civic startups (e.g. mySociety)"],
        "ngos": ["Brookings Institution", "RAND Corporation"],
        "scholarships": ["Presidential Management Fellowship", "Rhodes Scholarship (public policy track)"],
        "linked_career_world_id": "world_public_policy",
        "linked_topic_domain_ids": ["passion_social_impact_community", "passion_economics_finance"],
        "related_career_industries": ["public health & policy", "public administration"],
        "related_trend_ids": ["trend_public_health_data_systems"],
        "related_life_mission_ids": ["mission_improve_government"],
    },
    {
        "id": "circle_design", "name": "Design",
        "overview": "Design shapes how products, spaces, and digital experiences actually work for the people using them — a discipline of research, iteration, and craft, not just aesthetics.",
        "what_this_field_is_about": "Designers spend as much time observing real users and testing prototypes as they do drawing — the visible output is usually the smallest part of the actual work.",
        "beginner_projects": ["Redesign an app or product you use daily and explain your reasoning", "Complete a UX case study from scratch", "Run a small usability test with five real users", "Build a portfolio site showcasing 2-3 projects"],
        "advanced_projects": ["Contribute to an open-source design system", "Complete a design internship with real shipped work", "Run a full research-to-prototype design sprint for a real problem"],
        "laboratories": ["MIT Media Lab", "Stanford d.school"],
        "startups": ["Figma", "Framer", "Linear"],
        "ngos": ["AIGA (American Institute of Graphic Arts)"],
        "scholarships": ["AIGA Worldstudio Scholarship", "Adobe Design Circle"],
        "linked_career_world_id": "world_design",
        "linked_topic_domain_ids": ["passion_product_ux_design", "passion_visual_arts"],
        "related_career_industries": ["technology & design"],
        "related_trend_ids": ["trend_ai_literacy_as_baseline_skill"],
        "related_life_mission_ids": ["mission_design_better_products"],
    },
    {
        "id": "circle_agriculture", "name": "Agriculture",
        "overview": "Modern agriculture blends traditional farming knowledge with genetics, data science, and engineering to grow food more sustainably for a changing climate.",
        "what_this_field_is_about": "Work spans hands-on fieldwork, plant and soil science, and increasingly, precision agriculture technology like sensors, drones, and yield-prediction models.",
        "beginner_projects": ["Volunteer or work a season on a farm", "Grow and document a small crop experiment", "Build a simple soil-moisture sensor with a microcontroller", "Join a 4-H or FFA agricultural program"],
        "advanced_projects": ["Contribute to a precision agriculture data project", "Design a low-cost irrigation optimization system", "Complete an agronomy research internship"],
        "laboratories": ["USDA Agricultural Research Service labs", "CGIAR research centers"],
        "startups": ["Indigo Ag", "Farmers Business Network", "Ecoation"],
        "ngos": ["CGIAR", "Heifer International"],
        "scholarships": ["USDA 1890 National Scholars Program", "Borlaug International Agricultural Science Fellowship"],
        "linked_career_world_id": "world_agriculture",
        "linked_topic_domain_ids": ["passion_climate_environment", "passion_biology_life_sciences"],
        "related_career_industries": [],
        "related_trend_ids": ["trend_climate_adaptation_engineering"],
        "related_life_mission_ids": ["mission_improve_agriculture"],
    },
    {
        "id": "circle_hospitality", "name": "Hospitality",
        "overview": "Hospitality is the business of designing memorable, well-run guest experiences — hotels, restaurants, travel, and events — built on operations as much as service.",
        "what_this_field_is_about": "Behind every smooth guest experience is detailed logistics: staffing, supply chains, quality control, and constant problem-solving under real-time pressure.",
        "beginner_projects": ["Work a part-time role in a restaurant, hotel, or event venue", "Plan and run a small real event start to finish", "Shadow a hospitality manager for a day", "Study a hotel or restaurant's operations and propose one improvement"],
        "advanced_projects": ["Complete a hospitality management internship", "Lead operations for a student-run event", "Design a guest-experience improvement plan for a real business"],
        "laboratories": ["Cornell School of Hotel Administration research centers"],
        "startups": ["Sonder", "Tock", "Resy"],
        "ngos": ["American Hotel & Lodging Educational Foundation"],
        "scholarships": ["AHLEF scholarships", "Cornell Hotel Ezra Cornell scholarships"],
        "linked_career_world_id": "world_hospitality",
        "linked_topic_domain_ids": ["passion_food_culinary_arts"],
        "related_career_industries": [],
        "related_trend_ids": [],
        "related_life_mission_ids": [],
    },
    {
        "id": "circle_law", "name": "Law",
        "overview": "Law is the discipline of interpreting, arguing, and shaping the rules that govern society — spanning courtroom advocacy, contract drafting, and policy work.",
        "what_this_field_is_about": "Most legal work is reading and writing carefully, not courtroom drama — building airtight arguments and anticipating counterarguments long before any hearing.",
        "beginner_projects": ["Join a school debate or Model UN team", "Shadow a lawyer or attend real public court proceedings", "Write a legal analysis of a real, current case", "Volunteer with a legal aid clinic"],
        "advanced_projects": ["Complete a legal internship or clerkship", "Participate in a moot court competition", "Assist with real pro bono casework under supervision"],
        "laboratories": ["Harvard Law School legal clinics", "Yale Law School Information Society Project"],
        "startups": ["Clio", "DoNotPay"],
        "ngos": ["American Civil Liberties Union", "Legal Aid Society"],
        "scholarships": ["AccessLex Law School scholarships", "Council on Legal Education Opportunity (CLEO) Fellowship"],
        "linked_career_world_id": "world_law",
        "linked_topic_domain_ids": ["passion_philosophy_ethics"],
        "related_career_industries": [],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_advance_human_rights"],
    },
    {
        "id": "circle_finance", "name": "Finance",
        "overview": "Finance is the discipline of managing, allocating, and analyzing capital — from personal accounting and corporate finance to investment banking and markets.",
        "what_this_field_is_about": "The core skill across every finance role is disciplined, rigorous analysis under uncertainty, whether that's a company's books or a market's next move.",
        "beginner_projects": ["Build and track a real or simulated investment portfolio", "Complete an introductory financial modeling course", "Analyze a public company's financial statements", "Manage a club's or small organization's real budget"],
        "advanced_projects": ["Complete a finance or accounting internship", "Build a full financial model for a real or simulated company", "Pass a Level I professional finance certification exam (e.g. CFA)"],
        "laboratories": ["Wharton FinTech research initiatives"],
        "startups": ["Stripe", "Plaid", "Wise"],
        "ngos": ["CFA Institute", "Financial Planning Association"],
        "scholarships": ["CFA Institute Access Scholarship", "AICPA Accounting Scholars"],
        "linked_career_world_id": "world_finance",
        "linked_topic_domain_ids": ["passion_economics_finance"],
        "related_career_industries": ["finance"],
        "related_trend_ids": ["trend_declining_routine_bookkeeping"],
        "related_life_mission_ids": ["mission_improve_financial_literacy"],
    },
    {
        "id": "circle_psychology", "name": "Psychology",
        "overview": "Psychology studies how people think, feel, and behave — spanning clinical practice, research, and applied fields like organizational and user-experience psychology.",
        "what_this_field_is_about": "The scientific side involves rigorous experimental design and statistics; the applied side involves patient, careful listening — both are core to most real psychology careers.",
        "beginner_projects": ["Volunteer with a crisis line or peer support program", "Run a small, ethical survey-based research project", "Read and summarize a landmark psychology study", "Shadow a school counselor or therapist"],
        "advanced_projects": ["Assist in a university psychology research lab", "Complete a clinical or research internship", "Co-author a student research poster or paper"],
        "laboratories": ["Max Planck Institute for Human Development", "Stanford Psychology Department labs"],
        "startups": ["Lyra Health", "Headspace"],
        "ngos": ["American Psychological Association", "Mental Health America"],
        "scholarships": ["APA Minority Fellowship Program", "NIMH research supplements"],
        "linked_career_world_id": "world_psychology",
        "linked_topic_domain_ids": ["passion_psychology_behavior"],
        "related_career_industries": [],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_improve_mental_health"],
    },
    {
        "id": "circle_film", "name": "Film",
        "overview": "Film is the craft of visual storytelling at scale — writing, directing, cinematography, editing, and the production logistics that make it all possible.",
        "what_this_field_is_about": "Most working time on a film career isn't glamorous — it's technical problem-solving, scheduling, and revision, long before or after the camera actually rolls.",
        "beginner_projects": ["Write, shoot, and edit a short film with basic equipment", "Volunteer on a local independent film production", "Learn a specific craft (editing, sound, cinematography) deeply", "Submit a short film to a student festival"],
        "advanced_projects": ["Work as a production assistant on a professional set", "Complete a film school thesis project", "Build a portfolio reel from three or more completed projects"],
        "laboratories": ["Sundance Institute labs", "USC School of Cinematic Arts production facilities"],
        "startups": ["A24", "Neon"],
        "ngos": ["Sundance Institute", "Film Independent"],
        "scholarships": ["Sundance Institute Fellowships", "Academy Nicholl Fellowships in Screenwriting"],
        "linked_career_world_id": "world_film",
        "linked_topic_domain_ids": ["passion_film_video"],
        "related_career_industries": [],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_entertain_millions"],
    },
    {
        "id": "circle_music", "name": "Music",
        "overview": "Music careers span performance, composition, production, and the business side of the industry — a field where craft and commerce are deeply intertwined.",
        "what_this_field_is_about": "Beyond performance itself, most working musicians spend significant time on production, marketing, and the business logistics of a creative career.",
        "beginner_projects": ["Record and release an original song or short EP", "Learn a digital audio workstation (DAW) and produce a track", "Perform at an open mic or local venue", "Collaborate remotely with another musician online"],
        "advanced_projects": ["Complete a home studio production of a full project", "Score music for a short film or game", "Book and run a small live tour or residency"],
        "laboratories": ["Berklee College of Music production studios", "IRCAM (Institute for Research and Coordination in Acoustics/Music)"],
        "startups": ["Splice", "BandLab", "DistroKid"],
        "ngos": ["The Recording Academy", "Sound Exchange"],
        "scholarships": ["Berklee City Music Scholarship", "ASCAP Foundation grants"],
        "linked_career_world_id": "world_music",
        "linked_topic_domain_ids": ["passion_music"],
        "related_career_industries": [],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_entertain_millions", "mission_create_art"],
    },
    {
        "id": "circle_gaming", "name": "Gaming",
        "overview": "The gaming industry builds interactive entertainment — spanning game design, programming, art, narrative, and the live operations of running a game after launch.",
        "what_this_field_is_about": "Game development is deeply cross-disciplinary: a single title needs design, code, art, sound, and production working in tight coordination, often for years before release.",
        "beginner_projects": ["Build a small game in a free engine (Godot, Unity, Unreal)", "Join a game jam and ship something in 48 hours", "Design a tabletop game and playtest it with real players", "Mod an existing game to learn its systems"],
        "advanced_projects": ["Ship a complete small game to a public platform", "Contribute to an open-source game engine", "Complete a game development internship or co-op"],
        "laboratories": ["MIT Game Lab", "USC Games research programs"],
        "startups": ["Supercell", "Mihoyo", "Devolver Digital"],
        "ngos": ["International Game Developers Association"],
        "scholarships": ["IGDA Foundation scholarships", "Take-This game industry scholarships"],
        "linked_career_world_id": "world_gaming",
        "linked_topic_domain_ids": ["passion_game_design"],
        "related_career_industries": [],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_entertain_millions"],
    },
    {
        "id": "circle_defense", "name": "Defense",
        "overview": "The defense sector engineers and operates the systems — from cybersecurity to aerospace to logistics — that national security depends on.",
        "what_this_field_is_about": "Much of the work is deeply technical engineering and systems work under strict reliability and security requirements, more similar to aerospace or advanced manufacturing than combat itself.",
        "beginner_projects": ["Study a public case study of a real defense engineering challenge", "Join a cybersecurity capture-the-flag competition", "Learn systems engineering fundamentals", "Participate in a robotics or drone competition"],
        "advanced_projects": ["Complete a defense-sector engineering internship", "Contribute to an open-source cybersecurity tool", "Build a working prototype in an autonomous systems competition"],
        "laboratories": ["MIT Lincoln Laboratory", "DARPA-funded university research programs"],
        "startups": ["Anduril Industries", "Shield AI"],
        "ngos": [],
        "scholarships": ["ROTC scholarships", "SMART Defense Scholarship-for-Service"],
        "linked_career_world_id": "world_defense",
        "linked_topic_domain_ids": ["passion_ai_robotics"],
        "related_career_industries": [],
        "related_trend_ids": ["trend_ai_incident_response_skills"],
        "related_life_mission_ids": [],
    },
    {
        "id": "circle_climate", "name": "Climate",
        "overview": "Climate work spans science, engineering, and policy aimed at understanding and responding to a changing climate — from emissions modeling to renewable infrastructure.",
        "what_this_field_is_about": "Careers here range from hands-on engineering of clean energy systems to data-driven climate modeling to the policy and corporate work of implementing change at scale.",
        "beginner_projects": ["Analyze local climate or emissions data", "Build a small renewable energy demonstration project (solar, wind)", "Calculate and propose reductions for a real carbon footprint", "Join a climate advocacy or youth climate organization"],
        "advanced_projects": ["Contribute to an open climate-modeling dataset or tool", "Complete a renewable energy engineering internship", "Design a decarbonization plan for a real organization"],
        "laboratories": ["NASA Goddard Institute for Space Studies", "National Renewable Energy Laboratory"],
        "startups": ["Climeworks", "Watershed", "Form Energy"],
        "ngos": ["World Resources Institute", "Environmental Defense Fund"],
        "scholarships": ["Barry Goldwater Scholarship (climate/environmental track)", "Udall Undergraduate Scholarship"],
        "linked_career_world_id": "world_climate",
        "linked_topic_domain_ids": ["passion_climate_environment"],
        "related_career_industries": ["corporate sustainability", "environmental conservation"],
        "related_trend_ids": ["trend_climate_adaptation_engineering"],
        "related_life_mission_ids": ["mission_solve_climate_problems"],
    },
    {
        "id": "circle_manufacturing", "name": "Manufacturing",
        "overview": "Manufacturing turns designs into physical products at scale — spanning process engineering, materials science, robotics, and increasingly, software-driven automation.",
        "what_this_field_is_about": "Modern manufacturing work blends hands-on process knowledge with data-driven quality control and automation, rarely the purely manual-labor image people expect.",
        "beginner_projects": ["Build a project using 3D printing or a school makerspace", "Learn CAD software and design a manufacturable part", "Tour a local factory and document its process flow", "Join a robotics or FIRST manufacturing competition"],
        "advanced_projects": ["Complete a manufacturing or process engineering internship", "Design and prototype a product from concept to physical part", "Contribute to a factory automation or quality-control project"],
        "laboratories": ["Fraunhofer Institute for Manufacturing Engineering", "MIT Manufacturing Systems and Technology Program labs"],
        "startups": ["Fictiv", "Formlabs", "Xometry"],
        "ngos": ["Manufacturing Institute", "SME Education Foundation"],
        "scholarships": ["SME Education Foundation scholarships", "National Tooling and Machining Association scholarships"],
        "linked_career_world_id": "world_manufacturing",
        "linked_topic_domain_ids": ["passion_ai_robotics", "passion_physics"],
        "related_career_industries": ["manufacturing & research", "engineering & construction"],
        "related_trend_ids": ["trend_climate_adaptation_engineering"],
        "related_life_mission_ids": ["mission_build_technology"],
    },
    {
        "id": "circle_research", "name": "Research",
        "overview": "Research careers pursue new knowledge systematically — in academia, government labs, and industry — through hypothesis, experiment, and rigorous peer review.",
        "what_this_field_is_about": "The daily reality of research is mostly failed experiments, careful documentation, and slow iteration — real breakthroughs are the rare, visible tip of years of unglamorous work.",
        "beginner_projects": ["Assist in a research lab, even informally, as an undergraduate", "Read and summarize primary research papers in a field of interest", "Design and run a small, original experiment", "Present findings at a school or regional science fair"],
        "advanced_projects": ["Co-author a research paper or poster presentation", "Complete a formal summer research program (REU or equivalent)", "Present original research at an academic conference"],
        "laboratories": ["CERN", "Max Planck Institutes", "National Institutes of Health intramural labs"],
        "startups": [],
        "ngos": ["National Science Foundation", "Howard Hughes Medical Institute"],
        "scholarships": ["NSF Graduate Research Fellowship", "Goldwater Scholarship"],
        "linked_career_world_id": "world_research",
        "linked_topic_domain_ids": ["passion_physics", "passion_mathematics"],
        "related_career_industries": ["academic research", "manufacturing & research", "healthcare research", "biotechnology"],
        "related_trend_ids": ["trend_ai_safety_research_growth", "trend_low_resource_language_ai"],
        "related_life_mission_ids": ["mission_advance_science", "mission_discover_knowledge"],
    },
    {
        "id": "circle_ngos", "name": "NGOs",
        "overview": "Nongovernmental organizations design and run programs addressing humanitarian, development, and social problems, often where government or market solutions fall short.",
        "what_this_field_is_about": "The work combines genuine field-level program delivery with the operational realities of funding, logistics, and measuring real impact against limited resources.",
        "beginner_projects": ["Volunteer consistently with a local nonprofit for a full season", "Help a small nonprofit with a real fundraising or outreach campaign", "Research and write a case study on an NGO program's impact", "Join a student chapter of an international development organization"],
        "advanced_projects": ["Complete an international development internship or fellowship", "Design a program evaluation for a real nonprofit", "Lead a student-run service project with measurable outcomes"],
        "laboratories": [],
        "startups": [],
        "ngos": ["Oxfam", "Doctors Without Borders", "Save the Children"],
        "scholarships": ["Rotary Peace Fellowship", "Fulbright Program (development track)"],
        "linked_career_world_id": "world_ngos",
        "linked_topic_domain_ids": ["passion_social_impact_community"],
        "related_career_industries": ["international development", "human rights advocacy"],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_help_communities", "mission_fight_poverty"],
    },
    {
        "id": "circle_sports", "name": "Sports",
        "overview": "Sports careers extend well beyond athletes themselves — coaching, sports science, analytics, management, and medicine all support competitive and recreational athletics.",
        "what_this_field_is_about": "Behind every performance is a team of specialists using data, physiology, and careful training design — sports careers reward both technical rigor and genuine people skills.",
        "beginner_projects": ["Coach or assist a youth sports team", "Track and analyze your own or a team's performance data", "Volunteer as team support staff for a school sports program", "Complete a basic sports science or coaching certification"],
        "advanced_projects": ["Complete a sports science or performance analytics internship", "Build a data model analyzing a real team's performance", "Assist a college or professional team's coaching staff"],
        "laboratories": ["English Institute of Sport", "Australian Institute of Sport"],
        "startups": ["Whoop", "Hudl", "Catapult Sports"],
        "ngos": ["International Olympic Committee", "Special Olympics"],
        "scholarships": ["NCAA athletic scholarships", "United States Sports Academy scholarships"],
        "linked_career_world_id": "world_sports",
        "linked_topic_domain_ids": ["passion_sports_athletics"],
        "related_career_industries": [],
        "related_trend_ids": [],
        "related_life_mission_ids": [],
    },
    {
        "id": "circle_fashion", "name": "Fashion",
        "overview": "Fashion combines design, textile craft, and business — spanning garment construction, sustainable materials, and the operational realities of a global apparel industry.",
        "what_this_field_is_about": "The visible runway work is a small fraction of the industry — most careers involve production, sourcing, sustainability, or the business side of getting clothing made and sold.",
        "beginner_projects": ["Design and sew a complete original garment", "Study and document a supply chain for a clothing item you own", "Build a small portfolio of original design sketches", "Learn a textile or pattern-making skill hands-on"],
        "advanced_projects": ["Complete a fashion design or merchandising internship", "Launch a small original clothing line or capsule collection", "Research and propose a sustainable materials alternative for a real product"],
        "laboratories": ["Fashion Institute of Technology textile labs", "Parsons School of Design materials studios"],
        "startups": ["Reformation", "Allbirds", "Faire"],
        "ngos": ["Council of Fashion Designers of America"],
        "scholarships": ["CFDA Scholarship Fund", "Fashion Scholarship Fund"],
        "linked_career_world_id": "world_fashion",
        "linked_topic_domain_ids": ["passion_fashion_textiles"],
        "related_career_industries": [],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_create_art"],
    },
    {
        "id": "circle_architecture", "name": "Architecture",
        "overview": "Architecture designs the buildings and spaces people live and work in, balancing structural engineering, aesthetics, and the practical constraints of real construction.",
        "what_this_field_is_about": "The work spans conceptual design, detailed technical drawings, and years-long collaboration with engineers and contractors to see a design actually built.",
        "beginner_projects": ["Learn architectural drafting or a CAD tool and design a small structure", "Build a physical scale model of a design concept", "Analyze a local building's design and propose an improvement", "Attend a public city planning or design review meeting"],
        "advanced_projects": ["Complete an architecture firm internship", "Enter a student design competition", "Contribute to a real community design or planning project"],
        "laboratories": ["MIT Department of Architecture design labs", "Harvard Graduate School of Design research labs"],
        "startups": ["WeWork (workplace design)", "Katerra (construction technology, historical)"],
        "ngos": ["American Institute of Architects", "Architecture for Humanity"],
        "scholarships": ["AIA Diversity Advancement Scholarship", "American Architectural Foundation scholarships"],
        "linked_career_world_id": "world_architecture",
        "linked_topic_domain_ids": ["passion_product_ux_design"],
        "related_career_industries": ["engineering & construction", "urban development"],
        "related_trend_ids": ["trend_climate_adaptation_engineering"],
        "related_life_mission_ids": ["mission_build_better_cities"],
    },
    {
        "id": "circle_aviation", "name": "Aviation",
        "overview": "Aviation covers the design, manufacture, and operation of aircraft — from commercial airliners to drones — spanning engineering, piloting, and air traffic operations.",
        "what_this_field_is_about": "Safety and reliability standards are unusually strict compared to most engineering fields, shaping everything from design review processes to maintenance culture.",
        "beginner_projects": ["Build and fly radio-controlled aircraft or drones", "Take an introductory flight lesson", "Study aerodynamics fundamentals through open courseware", "Join a school aviation or aerospace club"],
        "advanced_projects": ["Complete a private pilot certification", "Intern with an aerospace manufacturer or airline", "Design and test a small unmanned aircraft system"],
        "laboratories": ["NASA Langley Research Center", "Boeing Research & Technology labs"],
        "startups": ["Joby Aviation", "Zipline", "Skydio"],
        "ngos": ["Aircraft Owners and Pilots Association", "Experimental Aircraft Association"],
        "scholarships": ["AOPA Flight Training Scholarship", "Boeing aviation scholarships"],
        "linked_career_world_id": "world_aviation",
        "linked_topic_domain_ids": ["passion_physics"],
        "related_career_industries": ["aerospace"],
        "related_trend_ids": ["trend_space_commercialization"],
        "related_life_mission_ids": ["mission_explore_space"],
    },
    {
        "id": "circle_journalism", "name": "Journalism",
        "overview": "Journalism investigates, verifies, and communicates real events to the public — spanning print, broadcast, and digital reporting under real deadline pressure.",
        "what_this_field_is_about": "The core skill is rigorous verification, not just writing — a good story is built on confirmed facts and multiple sources, checked carefully before publication.",
        "beginner_projects": ["Write and publish articles for a school or community publication", "Practice interviewing real people on a specific topic", "Fact-check a published news article independently", "Start a focused newsletter or blog on a beat you care about"],
        "advanced_projects": ["Complete a newsroom internship", "Report and publish an original investigative piece", "Cover a real, live news event start to finish"],
        "laboratories": ["Columbia Journalism School Tow Center for Digital Journalism"],
        "startups": ["Substack", "The Athletic (historical)", "Axios"],
        "ngos": ["Committee to Protect Journalists", "Pulitzer Center"],
        "scholarships": ["Pulitzer Center Student Fellowship", "Society of Professional Journalists scholarships"],
        "linked_career_world_id": "world_journalism",
        "linked_topic_domain_ids": ["passion_creative_writing", "passion_history"],
        "related_career_industries": [],
        "related_trend_ids": ["trend_ai_literacy_as_baseline_skill"],
        "related_life_mission_ids": ["mission_preserve_culture_and_heritage"],
    },
    {
        "id": "circle_healthcare", "name": "Healthcare",
        "overview": "Healthcare spans direct clinical care, medical research, and the systems and technology that support both — a field defined by direct, high-stakes human impact.",
        "what_this_field_is_about": "Every healthcare role, clinical or not, ultimately traces back to patient outcomes — the work rewards both scientific rigor and sustained, careful attention to people.",
        "beginner_projects": ["Volunteer at a hospital or clinic", "Shadow a healthcare professional in a role you're curious about", "Get certified in basic first aid or CPR", "Research and present on a real public health issue"],
        "advanced_projects": ["Complete a clinical or research internship", "Assist with a real public health data project", "Participate in a structured pre-health mentorship program"],
        "laboratories": ["Mayo Clinic research labs", "Johns Hopkins School of Medicine research centers"],
        "startups": ["Oscar Health", "Ro", "Cerebral"],
        "ngos": ["Doctors Without Borders", "World Health Organization"],
        "scholarships": ["Tylenol Future Care Scholarship", "AMA Foundation Physicians of Tomorrow Scholarship"],
        "linked_career_world_id": "world_healthcare",
        "linked_topic_domain_ids": ["passion_biology_life_sciences", "passion_psychology_behavior"],
        "related_career_industries": ["healthcare", "healthcare & technology", "healthcare research"],
        "related_trend_ids": ["trend_decentralized_clinical_trials", "trend_public_health_data_systems"],
        "related_life_mission_ids": ["mission_improve_healthcare"],
    },
    {
        "id": "circle_education", "name": "Education",
        "overview": "Education shapes how people learn — spanning classroom teaching, curriculum design, educational technology, and the research behind how learning actually works.",
        "what_this_field_is_about": "Great teaching is a genuine craft built on noticing which individual students need something different, far more than delivering a fixed curriculum uniformly.",
        "beginner_projects": ["Tutor a student one-on-one, consistently, for a semester", "Design and teach a short lesson to peers or younger students", "Volunteer with an after-school education program", "Research and present on a real learning-science concept"],
        "advanced_projects": ["Complete a formal teaching assistant or student-teaching placement", "Design a full lesson unit and pilot it with real students", "Contribute to an open educational resource project"],
        "laboratories": ["Stanford Graduate School of Education research centers", "MIT Teaching Systems Lab"],
        "startups": ["Duolingo", "Khan Academy", "Outschool"],
        "ngos": ["Teach For All", "Room to Read"],
        "scholarships": ["TEACH Grant", "Woodrow Wilson Teaching Fellowship"],
        "linked_career_world_id": "world_education",
        "linked_topic_domain_ids": ["passion_psychology_behavior", "passion_history"],
        "related_career_industries": ["education"],
        "related_trend_ids": ["trend_ai_literacy_as_baseline_skill"],
        "related_life_mission_ids": ["mission_educate_people"],
    },
    {
        "id": "circle_entrepreneurship", "name": "Entrepreneurship",
        "overview": "Entrepreneurship is the discipline of building something new from scratch — a product, a company, a market — under genuine uncertainty and real resource constraints.",
        "what_this_field_is_about": "Most founder time goes to unglamorous work — talking to potential customers, fixing operational problems, and making difficult tradeoff decisions with incomplete information.",
        "beginner_projects": ["Start a small real business or side project and get your first customer", "Interview 10 potential customers about a problem you want to solve", "Build and launch a minimum viable product", "Join a student entrepreneurship club or startup competition"],
        "advanced_projects": ["Complete a startup accelerator or incubator program", "Raise a small round of funding or grant for a real venture", "Build a company to its first meaningful revenue milestone"],
        "laboratories": ["Stanford StartX", "MIT Martin Trust Center for Entrepreneurship"],
        "startups": ["Y Combinator portfolio companies broadly"],
        "ngos": ["Kauffman Foundation"],
        "scholarships": ["Thiel Fellowship", "Kauffman Foundation entrepreneurship fellowships"],
        "linked_career_world_id": "world_entrepreneurship",
        "linked_topic_domain_ids": ["passion_entrepreneurship"],
        "related_career_industries": ["entrepreneurship", "technology"],
        "related_trend_ids": ["trend_applied_ai_engineering"],
        "related_life_mission_ids": ["mission_build_businesses"],
    },
    {
        "id": "circle_government", "name": "Government",
        "overview": "Government careers span policy, administration, diplomacy, and public service — designing and running the institutions that provide public goods and services at scale.",
        "what_this_field_is_about": "The pace is often slower and more procedural than private-sector work, but decisions can affect entire populations rather than a single company's customers.",
        "beginner_projects": ["Intern with a local government office or elected representative", "Attend and take notes on a public government meeting", "Research and write about a real local policy issue", "Volunteer on a political campaign or civic organization"],
        "advanced_projects": ["Complete a competitive government fellowship or graduate scheme", "Prepare for a national civil service entrance exam", "Work on a real public-sector project with measurable community impact"],
        "laboratories": ["Harvard Ash Center for Democratic Governance"],
        "startups": [],
        "ngos": ["Partnership for Public Service"],
        "scholarships": ["Presidential Management Fellowship", "Truman Scholarship"],
        "linked_career_world_id": "world_government",
        "linked_topic_domain_ids": ["passion_economics_finance", "passion_philosophy_ethics"],
        "related_career_industries": ["public administration", "diplomacy & international relations"],
        "related_trend_ids": ["trend_public_health_data_systems"],
        "related_life_mission_ids": ["mission_improve_government"],
    },
    {
        "id": "circle_skilled_trades", "name": "Skilled Trades",
        "overview": "Skilled trades — from electricians to traditional craftspeople — build and maintain the physical world through hands-on expertise developed over years of practice.",
        "what_this_field_is_about": "Mastery here comes almost entirely through apprenticeship and repetition, not classroom study — the learning curve is long, but the resulting expertise is deeply valuable and hard to automate.",
        "beginner_projects": ["Take an introductory trade skills class (woodworking, electrical, plumbing)", "Shadow a licensed tradesperson for a day", "Complete a small hands-on build project start to finish", "Research a formal apprenticeship program in a trade of interest"],
        "advanced_projects": ["Enter a formal trade apprenticeship program", "Complete a trade skills competition (e.g. SkillsUSA)", "Build a substantial independent project demonstrating trade mastery"],
        "laboratories": [],
        "startups": ["Angi (trade services platform)"],
        "ngos": ["SkillsUSA", "Mike Rowe Works Foundation"],
        "scholarships": ["Mike Rowe Works Foundation scholarships", "National Center for Construction Education and Research scholarships"],
        "linked_career_world_id": "world_skilled_trades",
        "linked_topic_domain_ids": ["passion_visual_arts"],
        "related_career_industries": ["traditional craftsmanship", "engineering & construction"],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_preserve_culture_and_heritage"],
    },
    {
        "id": "circle_social_impact", "name": "Social Impact",
        "overview": "Social impact work applies business and design thinking to social problems — spanning social enterprises, impact investing, and mission-driven corporate roles.",
        "what_this_field_is_about": "The field constantly balances measurable impact against financial sustainability — genuinely effective social impact work has to solve both problems at once.",
        "beginner_projects": ["Volunteer consistently with a mission-driven organization", "Research and evaluate a real social enterprise's impact model", "Start a small community project addressing a real local need", "Join a student social entrepreneurship program"],
        "advanced_projects": ["Complete a social enterprise or impact investing internship", "Design and pilot a small social impact project with measurable results", "Publish a case study evaluating a nonprofit or social enterprise"],
        "laboratories": ["Stanford Center for Social Innovation"],
        "startups": ["Warby Parker (Buy a Pair, Give a Pair model)", "TOMS"],
        "ngos": ["Ashoka", "Skoll Foundation"],
        "scholarships": ["Ashoka Youth Venture grants", "Echoing Green Fellowship"],
        "linked_career_world_id": "world_social_impact",
        "linked_topic_domain_ids": ["passion_social_impact_community", "passion_philosophy_ethics"],
        "related_career_industries": ["human rights advocacy", "international development", "public health & policy"],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_help_communities", "mission_advance_human_rights"],
    },
    {
        "id": "circle_arts", "name": "Arts",
        "overview": "The arts — visual art, sculpture, craft, and creative practice broadly — turn ideas into tangible, expressive work, spanning both fine art and applied creative careers.",
        "what_this_field_is_about": "A sustainable arts career usually blends genuine creative practice with the business skills — marketing, client work, grant writing — that keep that practice funded.",
        "beginner_projects": ["Build a consistent creative practice and document a body of work", "Exhibit or share work publicly, even informally", "Learn a new medium or technique deliberately", "Apply for a small local grant or exhibition opportunity"],
        "advanced_projects": ["Complete a formal artist residency", "Mount an independent or group exhibition", "Build a portfolio strong enough for competitive gallery or grant applications"],
        "laboratories": ["Rhode Island School of Design studios", "Skowhegan School of Painting and Sculpture"],
        "startups": ["Artsy", "Saatchi Art"],
        "ngos": ["National Endowment for the Arts", "Creative Capital"],
        "scholarships": ["National YoungArts Foundation awards", "Creative Capital grants"],
        "linked_career_world_id": "world_arts",
        "linked_topic_domain_ids": ["passion_visual_arts", "passion_creative_writing"],
        "related_career_industries": ["traditional craftsmanship"],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_create_art", "mission_preserve_culture_and_heritage"],
    },
    {
        "id": "circle_international_development", "name": "International Development",
        "overview": "International development works to reduce poverty and expand opportunity globally, spanning program implementation, policy, and cross-border institutional work.",
        "what_this_field_is_about": "Effective development work requires deep, sustained understanding of local context — solutions that work in one community rarely transfer directly to another without real adaptation.",
        "beginner_projects": ["Volunteer with an international development organization's local chapter", "Study a real development program's outcomes and design", "Learn a second or third language relevant to a region of interest", "Join a student global health or development organization"],
        "advanced_projects": ["Complete an international development fellowship or field placement", "Design a program evaluation for a real development initiative", "Contribute to a cross-border research or policy project"],
        "laboratories": ["MIT Poverty Action Lab (J-PAL)"],
        "startups": ["Kiva", "GiveDirectly"],
        "ngos": ["World Bank", "United Nations Development Programme"],
        "scholarships": ["Fulbright Program", "Boren Awards for International Study"],
        "linked_career_world_id": "world_international_development",
        "linked_topic_domain_ids": ["passion_social_impact_community", "passion_languages_linguistics"],
        "related_career_industries": ["international development", "diplomacy & international relations"],
        "related_trend_ids": [],
        "related_life_mission_ids": ["mission_fight_poverty", "mission_help_communities"],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    circles = [KnowledgeCircle.model_validate(c) for c in CIRCLES]

    def _upsert() -> None:
        client.table("knowledge_circles").upsert(
            [c.model_dump(mode="json") for c in circles]
        ).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(circles)} Knowledge Circles.")


if __name__ == "__main__":
    asyncio.run(seed())
