"""Connect Batch 1 — Expert Connect seed data, fifteenth (closing) wave.
See seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch15
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_commercial_pilot_erik_johansson",
        "name": "Erik Johansson, Commercial Airline Pilot",
        "role_type": "industry_professional", "field": "aviation", "bio": "Flies commercial passenger routes for a European airline; failed a critical flight simulator check during training, a genuine setback that delayed his certification by months.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who like precise, high-responsibility technical work with a clear path of career progression.",
        "organization": "A European airline", "years_experience": 14, "journey_highlights": ["Failed a critical flight simulator check during training", "Now flies as a senior captain on long-haul international routes"],
        "discussion_topics": ["Failing a major flight training checkpoint", "The real path to becoming a commercial pilot", "What flying actually involves beyond takeoff and landing"],
        "profession": "Airline Captain", "specialization": "Long-haul international passenger flights", "country": "Sweden", "city": "Stockholm",
        "industries": ["aviation"], "education": ["Commercial pilot license and airline training program"],
        "current_role": "Senior Captain", "languages": ["Swedish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in commercial aviation as a career", "Students who've failed a major training checkpoint and worry about their prospects", "Students curious what pilots actually do beyond flying the plane"],
        "career_ids": [],
        "career_journey": [
            {"stage": "first_job", "label": "Began commercial pilot training", "description": "Pursued flight training through a structured airline cadet program.", "year_label": "2008-2010"},
            {"stage": "failure", "label": "Failed a critical flight simulator check during his training program", "description": "The failure delayed his certification by several months and required additional, self-funded training hours to pass on his second attempt.", "year_label": "2009"},
            {"stage": "turning_point", "label": "Identified specific technical weaknesses with an instructor and rebuilt his skills systematically", "description": "Passed the retest with a much deeper technical understanding than his first attempt had required.", "year_label": "2010"},
            {"stage": "promotion", "label": "Progressed from first officer to senior captain over more than a decade", "description": "Now flies long-haul international routes as a senior captain.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "Extensive pre-flight preparation and checks, the flight itself requiring sustained focus, and post-flight reporting.",
        "weekly_routine": "Irregular schedule dictated by flight rosters, including significant time away from home on long-haul routes.",
        "biggest_challenges": ["Sustaining focus and decision-making across long flights, sometimes across many time zones", "The significant time away from family that international routes require"],
        "favourite_part": "A smooth, well-executed flight bringing passengers safely to a new place.",
        "biggest_misconceptions": ["That flying a modern aircraft is mostly automated with little pilot involvement", "That failing a training checkpoint disqualifies you from a pilot career"],
        "what_surprised_them": "How much ongoing training and recurrent testing the job requires throughout an entire career, not just initial certification.",
        "biggest_mistake": "During my failed simulator check, I hadn't adequately prepared for a specific emergency procedure scenario, having focused my study time on areas I found more intuitively interesting rather than systematically covering everything the check required. The failure taught me to approach training comprehensively rather than according to my own preferences.",
        "one_regret": "I regret not seeking more structured guidance on my study approach before that first check — a more systematic method would likely have gotten me through on the first attempt.",
        "salary_reality": "Commercial airline pilots in Sweden are well-compensated once past the training and early career stages, though initial training costs and lower early-career pay are real financial considerations.",
        "work_life_balance": "Genuinely challenging — irregular schedules and significant time away from home on long-haul routes are a real, ongoing career tradeoff.",
        "daily_skills": ["aircraft systems management", "emergency procedure execution", "crew coordination"],
        "daily_tools": ["Aircraft flight and navigation systems", "flight simulators for recurrent training"],
        "recommended_books": ["Skyfaring by Mark Vanhoenacker"],
        "recommended_communities": ["Swedish Airline Pilots Association"],
        "advice_for_beginners": "Study systematically and comprehensively, not just the areas you find interesting — my failed check came from focusing too narrowly on what I preferred.",
        "advice_for_parents": "Failing a major training checkpoint is a normal, real part of pilot training that many successful captains, myself included, have experienced — it doesn't end the path.",
        "faqs": [{"question": "Is it common to fail a flight training checkpoint?", "answer": "It happens regularly during the rigorous, high-stakes training process — pass rates on certain check rides are well below 100%, and retesting after focused additional preparation is standard."}],
        "projects": [], "research": [], "certifications": ["Airline Transport Pilot License"],
        "conferences": [], "organizations": ["Swedish Airline Pilots Association"],
        "volunteer_work": ["Mentors aspiring pilots on training preparation strategies"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_zoo_keeper_behaviorist_claire_botha",
        "name": "Claire Botha, Zoo Animal Behaviorist",
        "role_type": "industry_professional", "field": "animal behavior science", "bio": "Manages animal welfare and enrichment programs at a wildlife conservation park; a behavioral assessment error early in her career put her at real physical risk during an enclosure interaction.",
        "trait_tags": ["empathy", "analytical_thinking"], "learning_style_fit": "Students who love animals and want a genuine science career, not just an animal-adjacent job.",
        "organization": "A wildlife conservation park", "years_experience": 10, "journey_highlights": ["A behavioral misjudgment put her at real physical risk during an enclosure interaction", "Now designs enrichment programs recognized as a regional model for animal welfare"],
        "discussion_topics": ["A frightening near-miss with a large animal and what it taught her", "Zoo careers as genuine animal behavior science, not just caretaking", "Animal welfare and enrichment as a specialized field"],
        "profession": "Animal Behaviorist and Welfare Coordinator", "specialization": "Large mammal enrichment and welfare", "country": "South Africa", "city": "Cape Town",
        "industries": ["environmental conservation"], "education": ["BSc Zoology, Stellenbosch University", "Animal behavior and welfare certification"],
        "current_role": "Senior Animal Behaviorist", "languages": ["English", "Afrikaans"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who love animals and want real science, not just a caretaking role", "Students who've had a frightening near-miss due to a misjudgment", "Students interested in conservation-focused zoo careers specifically"],
        "career_ids": ["conservation_biologist"],
        "career_journey": [
            {"stage": "university", "label": "BSc Zoology, then specialized animal behavior certification", "description": "Focused her studies on large mammal behavior and welfare science.", "year_label": "2009-2014"},
            {"stage": "first_job", "label": "Junior animal keeper", "description": "Learned enclosure management and animal handling under senior supervision.", "year_label": "2014-2016"},
            {"stage": "failure", "label": "Misjudged a large predator's behavioral signals during a routine enclosure interaction", "description": "The misjudgment put her at real physical risk before she was able to safely disengage, a genuinely frightening experience.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Underwent additional specialized behavioral assessment training", "description": "Rebuilt her confidence through much more rigorous, systematic behavioral reading protocols.", "year_label": "2017"},
            {"stage": "current_role", "label": "Senior Animal Behaviorist", "description": "Now designs enrichment programs recognized as a regional model for animal welfare practice.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of direct animal observation, enrichment program design, and staff training on animal welfare protocols.",
        "weekly_routine": "Daily animal welfare checks and enrichment implementation, with periodic program review and staff training sessions.",
        "biggest_challenges": ["The genuine physical risk inherent in working closely with large animals", "Balancing animal welfare ideals against real facility resource constraints"],
        "favourite_part": "Designing an enrichment activity that visibly improves an animal's wellbeing and natural behavior expression.",
        "biggest_misconceptions": ["That zoo work is simple animal caretaking rather than genuine behavioral science", "That a frightening near-miss means someone isn't suited for animal care work"],
        "what_surprised_them": "How much rigorous behavioral science and risk assessment the role actually requires.",
        "biggest_mistake": "I misread a large predator's subtle warning behavioral signals during a routine interaction, having grown slightly overconfident after months of uneventful daily contact. The situation could have ended very badly, and it fundamentally reshaped how seriously I take behavioral assessment protocols, no matter how routine an interaction has become.",
        "one_regret": "I regret how comfortable I'd become with a large predator's presence before that incident — genuine expertise requires never letting familiarity replace careful, ongoing behavioral assessment.",
        "salary_reality": "Animal behaviorist roles in South Africa's conservation sector pay modestly, reflecting broader conservation-sector compensation, despite the specialized science required.",
        "work_life_balance": "Generally steady, though animal welfare needs don't pause for weekends or holidays, requiring some rotating coverage.",
        "daily_skills": ["animal behavioral assessment", "enrichment program design", "risk management"],
        "daily_tools": ["Behavioral observation and tracking systems", "enrichment design tools"],
        "recommended_books": ["Beyond Words by Carl Safina"],
        "recommended_communities": ["Southern African Association for Zoos and Aquaria"],
        "advice_for_beginners": "Never let familiarity with an animal replace careful, ongoing behavioral assessment — my near-miss came directly from growing overconfident after months of routine contact.",
        "advice_for_parents": "Zoo and conservation animal work is a genuine science career requiring rigorous behavioral training, not simply a job for people who 'like animals.'",
        "faqs": [{"question": "Is zoo work dangerous?", "answer": "Working closely with large animals carries real, inherent risk, which is why rigorous behavioral assessment training and protocols are such a central part of the job."}],
        "projects": ["Designed enrichment programs recognized as a regional model"], "research": [], "certifications": ["Animal Behavior and Welfare Certification"],
        "conferences": [], "organizations": ["Southern African Association for Zoos and Aquaria"],
        "volunteer_work": ["Trains new keepers on behavioral risk assessment protocols"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_mining_engineer_lucas_pereira",
        "name": "Lucas Pereira, Mining Engineer",
        "role_type": "industry_professional", "field": "mining engineering", "bio": "Manages underground mine safety and operations; a ventilation design oversight early in his career created a real safety hazard caught before any harm occurred.",
        "trait_tags": ["analytical_thinking", "systems_thinking"], "learning_style_fit": "Students interested in engineering with immediate, tangible physical and safety stakes.",
        "organization": "A mining operations company", "years_experience": 12, "journey_highlights": ["A ventilation design oversight created a real safety hazard caught before harm occurred", "Now leads safety systems design for the company's underground operations"],
        "discussion_topics": ["A caught safety hazard and what it taught him about engineering responsibility", "Mining engineering beyond the stereotype of environmental controversy", "What underground mine safety actually involves"],
        "profession": "Mining Engineer", "specialization": "Underground mine safety systems", "country": "Chile", "city": "Copiapó",
        "industries": ["mining", "engineering & construction"], "education": ["BEng Mining Engineering, Universidad de Chile"],
        "current_role": "Senior Mining Safety Engineer", "languages": ["Spanish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in engineering with immediate physical and safety stakes", "Students who've caught or nearly missed a real safety hazard", "Students interested in mining as a technically rigorous engineering field"],
        "career_ids": ["civil_engineer"],
        "career_journey": [
            {"stage": "university", "label": "BEng Mining Engineering", "description": "Focused coursework specifically on underground operations and safety systems.", "year_label": "2008-2013"},
            {"stage": "first_job", "label": "Junior mining engineer", "description": "Worked on ventilation and safety system design under senior supervision.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Made a ventilation design oversight that created a real air-quality safety hazard in a section of the mine", "description": "The issue was caught during a routine safety audit before any worker was harmed, but it was a genuinely serious near-miss.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Became a strong internal advocate for more rigorous, redundant ventilation system verification", "description": "Channeled the frightening near-miss into meaningful improvements to the company's safety review process.", "year_label": "2017"},
            {"stage": "current_role", "label": "Senior Mining Safety Engineer", "description": "Now leads safety systems design for all the company's underground operations.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of underground site inspections, safety system design, and coordination with mine operations teams.",
        "weekly_routine": "Regular underground site visits combined with office-based design and safety planning work.",
        "biggest_challenges": ["The genuine, serious physical stakes of underground mine safety", "Balancing production pressure against uncompromising safety standards"],
        "favourite_part": "A safety system he designed working exactly as intended during a real operational stress test.",
        "biggest_misconceptions": ["That mining engineering is purely about extraction, not safety and environmental systems", "That a caught near-miss reflects poor engineering rather than safety systems working correctly"],
        "what_surprised_them": "How much of mining engineering is genuinely about human safety systems, not just resource extraction.",
        "biggest_mistake": "I designed a ventilation system update based on standard calculations without adequately accounting for a specific change in the mine's excavation pattern, which would have created a real air-quality hazard in one section. A routine safety audit caught it before any worker was exposed, but it terrified me and taught me to never assume standard calculations apply without verifying against the mine's actual current conditions.",
        "one_regret": "I regret not personally re-inspecting the specific excavation area before finalizing that design — physical verification would have caught the discrepancy before it became a real hazard.",
        "salary_reality": "Mining engineering pays very well in Chile's major mining sector, reflecting the genuine technical expertise and safety responsibility required.",
        "work_life_balance": "Generally steady, with periodic intensive periods around major safety system implementations.",
        "daily_skills": ["mine ventilation design", "safety systems engineering", "underground operations management"],
        "daily_tools": ["Mine ventilation modeling software", "safety monitoring systems"],
        "recommended_books": ["Introductory Mining Engineering by Hartman and Mutmansky"],
        "recommended_communities": ["Chilean Institute of Mining Engineers"],
        "advice_for_beginners": "Always verify design calculations against actual current physical conditions, never just standard assumptions — my near-miss came from skipping exactly that verification step.",
        "advice_for_parents": "Mining engineering carries real safety responsibility and rigorous technical training, and safety-focused roles within it are a genuine, well-regarded specialization within the field.",
        "faqs": [{"question": "Is mining engineering only about resource extraction?", "answer": "No — safety systems, environmental management, and ventilation engineering are all major, technically rigorous specializations within mining engineering."}],
        "projects": ["Leads safety systems design for underground operations"], "research": [], "certifications": ["Professional Mining Engineer, Chile"],
        "conferences": [], "organizations": ["Chilean Institute of Mining Engineers"],
        "volunteer_work": ["Trains junior mining engineers on rigorous safety verification protocols"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_software_qa_engineer_leila_ahmadi",
        "name": "Leila Ahmadi, Quality Assurance Engineer",
        "role_type": "industry_professional", "field": "software engineering", "bio": "Leads software quality assurance for a financial technology company; a bug she signed off on reached production and caused a real financial calculation error for users.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who like methodical, detail-oriented technical work and think about how systems can fail.",
        "organization": "A financial technology company", "years_experience": 8, "journey_highlights": ["A bug she approved reached production, causing a real financial calculation error for users", "Now leads the company's automated testing strategy"],
        "discussion_topics": ["Approving a bug that reached real users", "QA engineering as a genuine, specialized technical career", "Building testing systems that actually catch problems"],
        "profession": "Senior QA Engineer", "specialization": "Financial software testing", "country": "Iran", "city": "Isfahan",
        "industries": ["technology", "fintech"], "education": ["BSc Software Engineering, Isfahan University of Technology"],
        "current_role": "Lead QA Engineer", "languages": ["Persian", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who like methodical, detail-oriented technical work", "Students who've approved something that later caused a real problem", "Students interested in QA as a genuine technical specialization, not just 'testing'"],
        "career_ids": ["ai_ops_specialist"],
        "career_journey": [
            {"stage": "university", "label": "BSc Software Engineering", "description": "Discovered an interest in systematic testing during a university software project.", "year_label": "2011-2015"},
            {"stage": "first_job", "label": "Junior QA tester", "description": "Learned manual and early automated testing practices.", "year_label": "2015-2018"},
            {"stage": "failure", "label": "Signed off on a release containing a bug that caused a real financial calculation error for users in production", "description": "Her test coverage had missed a specific edge case involving currency conversion rounding, which affected real user account balances before being caught and fixed.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Rebuilt the team's test coverage strategy around systematic edge-case identification", "description": "Championed a much more rigorous approach to financial calculation testing specifically.", "year_label": "2020"},
            {"stage": "current_role", "label": "Lead QA Engineer", "description": "Now leads the company's entire automated testing strategy.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Writing and reviewing automated tests, investigating reported bugs, and collaborating with developers on edge-case scenarios.",
        "weekly_routine": "Steady testing and quality review work, with intensive periods before major releases.",
        "biggest_challenges": ["The genuine impossibility of testing every possible edge case, requiring real judgment about priorities", "The financial stakes of errors reaching production in a fintech context"],
        "favourite_part": "Catching a genuinely subtle bug before it ever reaches a real user.",
        "biggest_misconceptions": ["That QA is a lesser technical role compared to software development", "That a bug reaching production always reflects careless testing"],
        "what_surprised_them": "How much genuine engineering skill and systems thinking real QA work requires, beyond simply 'trying to break things.'",
        "biggest_mistake": "I approved a release without adequately testing a specific currency-conversion rounding edge case, assuming our standard test suite's broader coverage was sufficient for that type of calculation. The bug affected real user account balances before we caught and fixed it, a genuinely serious incident in financial software. I now specifically prioritize systematic edge-case identification for any calculation-related code.",
        "one_regret": "I regret trusting our general test suite's coverage for that specific financial calculation without adding a dedicated edge-case test — the gap was narrow but the consequences were real.",
        "salary_reality": "QA engineering pays reasonably well in Iran's growing tech sector, generally somewhat below software development roles but with genuine, specialized demand.",
        "work_life_balance": "Generally steady, with periodic intensity before major releases.",
        "daily_skills": ["test design", "automated testing frameworks", "bug investigation"],
        "daily_tools": ["Automated testing frameworks", "bug tracking software"],
        "recommended_books": ["Agile Testing by Lisa Crispin and Janet Gregory"],
        "recommended_communities": ["Iranian software quality engineers network"],
        "advice_for_beginners": "Prioritize systematic edge-case identification, especially for financial calculations, rather than trusting general test coverage — my production bug came from exactly that gap.",
        "advice_for_parents": "QA engineering is a genuine, specialized technical career requiring real systems thinking, not a lesser or entry-level alternative to software development.",
        "faqs": [{"question": "Is QA engineering less technical than software development?", "answer": "No — modern QA engineering, especially with automated testing, requires genuine programming and systems-thinking skill, just applied to a different problem than building the feature itself."}],
        "projects": ["Leads the company's automated testing strategy"], "research": [], "certifications": ["ISTQB Certified Tester"],
        "conferences": [], "organizations": ["Iranian software quality engineers network"],
        "volunteer_work": ["Mentors junior developers on systematic edge-case thinking"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch15).")


if __name__ == "__main__":
    asyncio.run(seed())
