"""Connect Batch 1 — Expert Connect seed data, fourteenth (final) wave,
crossing the 100-expert floor. See seed_experts_tech_and_science.py for
full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch14
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_radiologist_wei_lin",
        "name": "Dr. Wei Lin, Radiologist",
        "role_type": "industry_professional", "field": "medicine", "bio": "Reads diagnostic imaging at a hospital radiology department; missed a subtle early-stage tumor on a scan early in his career, caught later at a more advanced stage.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who like pattern recognition and detailed visual analysis within medicine.",
        "organization": "A hospital radiology department", "years_experience": 13, "journey_highlights": ["Missed a subtle early-stage tumor on a scan that was caught later at a more advanced stage", "Now trains radiology residents on systematic scan review protocols"],
        "discussion_topics": ["A missed diagnosis and how it changed his practice", "Radiology as a medical specialty with minimal direct patient contact", "What makes diagnostic imaging genuinely difficult"],
        "profession": "Radiologist", "specialization": "Diagnostic imaging, oncology-focused", "country": "China", "city": "Guangzhou",
        "industries": ["healthcare"], "education": ["MD, Sun Yat-sen University", "Radiology residency"],
        "current_role": "Senior Radiologist", "languages": ["Mandarin", "Cantonese", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like pattern recognition and visual analysis in medicine", "Students who've missed something important and want to know how to recover professionally", "Students interested in medical specialties with less direct patient interaction"],
        "career_ids": ["physician_general", "genomics_data_scientist"],
        "career_journey": [
            {"stage": "university", "label": "MD, then radiology residency", "description": "Drawn to radiology's blend of medical knowledge and visual pattern analysis.", "year_label": "2005-2013"},
            {"stage": "first_job", "label": "Junior radiologist", "description": "Reviewed a high volume of scans daily under real time pressure.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Missed a subtle early-stage tumor on a routine scan", "description": "The tumor was caught eighteen months later at a more advanced stage, a devastating realization that haunted him deeply.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Adopted a rigorous, systematic scan review checklist rather than relying purely on pattern recognition instinct", "description": "Never skipped the full systematic review again, regardless of how routine a scan initially appeared.", "year_label": "2017"},
            {"stage": "current_role", "label": "Senior Radiologist", "description": "Now trains residents specifically on systematic review protocols to prevent similar misses.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Reviewing a high volume of diagnostic images throughout the day, writing detailed reports, and consulting with referring physicians on complex cases.",
        "weekly_routine": "Steady scan review work throughout the week, with periodic case conferences discussing complex or unusual findings.",
        "biggest_challenges": ["The genuine difficulty of catching extremely subtle findings among a high daily scan volume", "The emotional weight of knowing a missed finding can have serious real consequences"],
        "favourite_part": "Catching a genuinely difficult, early-stage finding that leads to a patient's successful treatment.",
        "biggest_misconceptions": ["That radiology involves no real patient impact since there's minimal direct patient contact", "That a missed diagnosis reflects incompetence rather than the genuine, documented limits of visual detection"],
        "what_surprised_them": "How much of accurate radiology depends on systematic process discipline, not just visual skill.",
        "biggest_mistake": "I relied primarily on pattern-recognition instinct when reviewing a routine scan rather than following the full systematic review protocol, and I missed a subtle early-stage finding as a result. It wasn't caught until eighteen months later at a more advanced stage, one of the most painful professional experiences of my career. I now follow a rigorous systematic checklist for every single scan, without exception.",
        "one_regret": "I regret trusting instinct over full systematic protocol on that scan — the few extra minutes a complete review would have taken feels like nothing next to what was ultimately lost.",
        "salary_reality": "Radiology is a well-compensated medical specialty in China, reflecting its demanding, highly specialized training.",
        "work_life_balance": "Generally more predictable than many clinical specialties, without direct emergency on-call patient responsibilities in most settings.",
        "daily_skills": ["diagnostic image interpretation", "systematic review protocols", "clinical correlation"],
        "daily_tools": ["Diagnostic imaging software", "picture archiving and communication systems (PACS)"],
        "recommended_books": ["The Emperor of All Maladies by Siddhartha Mukherjee"],
        "recommended_communities": ["Chinese Society of Radiology"],
        "advice_for_beginners": "Follow a full systematic review checklist for every scan, no matter how routine it seems or how confident your instinct feels — my missed diagnosis came from skipping exactly that discipline.",
        "advice_for_parents": "A missed diagnosis, especially one that leads to real, lasting practice changes, is a devastating but genuinely instructive part of a long medical career, not evidence your child shouldn't practice medicine.",
        "faqs": [{"question": "How do radiologists avoid missing subtle findings?", "answer": "Rigorous systematic review protocols, not just visual pattern recognition, are what catch the most subtle and easily-missed findings."}],
        "projects": [], "research": [], "certifications": ["Board certification in Radiology"],
        "conferences": [], "organizations": ["Chinese Society of Radiology"],
        "volunteer_work": ["Trains radiology residents on systematic scan review protocols"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_judge_margarethe_fischer",
        "name": "Margarethe Fischer, District Court Judge",
        "role_type": "industry_professional", "field": "law", "bio": "Presides over civil cases at a district court; a ruling she made as a young judge was overturned on appeal, a professionally humbling early experience.",
        "trait_tags": ["analytical_thinking", "values"], "learning_style_fit": "Students interested in the judiciary as a distinct legal career path from advocacy.",
        "organization": "A district court", "years_experience": 16, "journey_highlights": ["A ruling she made early in her judicial career was overturned on appeal", "Now recognized for particularly thorough, well-reasoned written opinions"],
        "discussion_topics": ["Having a ruling overturned and what it taught her", "Becoming a judge as a distinct legal career path", "What judges actually do beyond courtroom appearances"],
        "profession": "District Court Judge", "specialization": "Civil litigation", "country": "Germany", "city": "Munich",
        "industries": ["law", "government"], "education": ["Law degree and state examinations, Ludwig Maximilian University of Munich"],
        "current_role": "District Court Judge", "languages": ["German", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in the judiciary specifically, not just legal advocacy", "Students who've had a decision or judgment publicly overturned or criticized", "Students curious what judges actually do day to day"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "Law degree and state examinations", "description": "Pursued the specific judicial career track available within the German legal system.", "year_label": "1998-2005"},
            {"stage": "first_job", "label": "Junior judge", "description": "Began presiding over civil cases relatively early in her legal career, per the German judicial system's structure.", "year_label": "2006-2010"},
            {"stage": "failure", "label": "One of her early rulings was overturned on appeal for a legal reasoning error", "description": "The reversal was professionally humbling and publicly documented in the appellate court's written opinion.", "year_label": "2009"},
            {"stage": "turning_point", "label": "Developed a much more rigorous personal process for researching precedent before major rulings", "description": "Became known over time for particularly thorough, well-researched written opinions.", "year_label": "2010"},
            {"stage": "current_role", "label": "District Court Judge", "description": "Now recognized specifically for the thoroughness of her legal reasoning.", "year_label": "2015-present"},
        ],
        "day_in_the_life": "Court hearings, extensive case research, and writing detailed legal opinions explaining her rulings.",
        "weekly_routine": "Scheduled court sessions combined with significant research and writing time between hearings.",
        "biggest_challenges": ["The weight of decisions that significantly affect people's lives and finances", "Managing a substantial caseload while maintaining real thoroughness"],
        "favourite_part": "Writing a ruling she's confident is both legally sound and genuinely fair to all parties.",
        "biggest_misconceptions": ["That judges simply apply the law mechanically with little real judgment involved", "That having a ruling overturned reflects poor overall judicial competence"],
        "what_surprised_them": "How much genuine research and writing the role involves beyond courtroom appearances.",
        "biggest_mistake": "In one of my early rulings, I didn't research a specific area of precedent as thoroughly as the case actually required, leading to a legal reasoning error that the appellate court identified and corrected. It was professionally humbling to have that documented publicly, and it fundamentally reshaped how thoroughly I research every subsequent ruling.",
        "one_regret": "I regret how much that early reversal shook my confidence for longer than was useful — I now understand appellate review exists precisely to catch and correct exactly this kind of error, as part of the system working as intended.",
        "salary_reality": "Judicial salaries in Germany are stable and respectable within public service, reflecting the significant responsibility and specialized training the role requires.",
        "work_life_balance": "Generally more predictable than private legal practice, without the unpredictable demands of client-facing law firm work.",
        "daily_skills": ["legal reasoning and analysis", "case research", "judicial writing"],
        "daily_tools": ["Legal research databases", "case management systems"],
        "recommended_books": ["How Judges Think by Richard Posner"],
        "recommended_communities": ["German Association of Judges"],
        "advice_for_beginners": "Research precedent as thoroughly as a case genuinely requires, never assuming your own legal instinct is sufficient — my overturned ruling came from exactly that gap.",
        "advice_for_parents": "Having a judicial ruling overturned on appeal is a normal, expected part of how the legal system's checks work, not a sign your child made a career mistake.",
        "faqs": [{"question": "Is it common for judicial rulings to be overturned on appeal?", "answer": "It happens regularly across the judiciary and is part of the system's intentional design — appellate review exists specifically to catch and correct these kinds of errors."}],
        "projects": [], "research": [], "certifications": ["Qualified Judge, Germany"],
        "conferences": [], "organizations": ["German Association of Judges"],
        "volunteer_work": ["Speaks to law students about judicial careers as an alternative to advocacy"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_naval_architect_erik_nilsson",
        "name": "Erik Nilsson, Naval Architect",
        "role_type": "industry_professional", "field": "naval architecture", "bio": "Designs commercial vessels at a shipbuilding company; a stability calculation error early in his career was caught during sea trials rather than after delivery.",
        "trait_tags": ["analytical_thinking", "systems_thinking"], "learning_style_fit": "Students interested in a specialized engineering field combining physics, design, and maritime systems.",
        "organization": "A commercial shipbuilding company", "years_experience": 11, "journey_highlights": ["A stability calculation error was caught during sea trials before vessel delivery", "Has since led design on over a dozen commercial vessels"],
        "discussion_topics": ["A near-miss caught during testing rather than after delivery", "Naval architecture as a specialized, less commonly known engineering field", "What ship design actually involves"],
        "profession": "Naval Architect", "specialization": "Commercial vessel design", "country": "Sweden", "city": "Gothenburg",
        "industries": ["manufacturing", "maritime"], "education": ["MSc Naval Architecture, Chalmers University of Technology"],
        "current_role": "Senior Naval Architect", "languages": ["Swedish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in specialized, less commonly discussed engineering fields", "Students who've had an error caught just before serious consequences", "Students interested in maritime industries specifically"],
        "career_ids": ["civil_engineer", "space_systems_engineer"],
        "career_journey": [
            {"stage": "university", "label": "MSc Naval Architecture", "description": "Chose the specialization after a childhood fascination with ships and maritime engineering.", "year_label": "2008-2013"},
            {"stage": "first_job", "label": "Junior naval architect", "description": "Worked on stability and structural calculations for commercial vessel designs.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Made a stability calculation error on a vessel design that was caught during sea trials, not after delivery", "description": "The error would have caused real handling problems in certain sea conditions had it not been caught in testing.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Adopted a much more rigorous independent verification process for all stability calculations", "description": "Never had a similar error reach even the sea trial stage again.", "year_label": "2017"},
            {"stage": "current_role", "label": "Senior Naval Architect", "description": "Has since led design work on over a dozen commercial vessels.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Vessel design calculations, coordination with shipyard engineering teams, and review of testing and sea trial data.",
        "weekly_routine": "Design and calculation work most weeks, with periodic sea trial attendance for vessels nearing completion.",
        "biggest_challenges": ["The genuine complexity of designing for real, unpredictable sea conditions", "The high stakes of stability calculations that affect vessel and crew safety"],
        "favourite_part": "Watching a vessel he designed handle real sea conditions exactly as intended.",
        "biggest_misconceptions": ["That naval architecture is the same as marine engineering (which focuses more on propulsion and mechanical systems)", "That an error caught during testing reflects poor overall engineering competence"],
        "what_surprised_them": "How much real-world sea trial testing catches that theoretical calculation alone can miss.",
        "biggest_mistake": "I made a stability calculation error based on a simplified assumption about cargo distribution that didn't fully account for a realistic loading scenario. It was caught during sea trials, before the vessel was delivered to the client, but it taught me to never rely on a single calculation pass without independent verification for anything safety-critical.",
        "one_regret": "I regret not having a colleague independently verify that specific calculation before it reached sea trials — a second set of eyes would have caught it much earlier in the process.",
        "salary_reality": "Naval architecture is a well-compensated, specialized engineering field in Sweden's maritime industry, reflecting the technical expertise required.",
        "work_life_balance": "Generally steady, with periodic travel for sea trials attendance.",
        "daily_skills": ["vessel stability analysis", "structural engineering", "maritime design software"],
        "daily_tools": ["Naval architecture design and simulation software"],
        "recommended_books": ["Principles of Naval Architecture by the Society of Naval Architects and Marine Engineers"],
        "recommended_communities": ["Swedish Society of Naval Architects and Marine Engineers"],
        "advice_for_beginners": "Never trust a single calculation pass for anything safety-critical — get independent verification, especially for stability work, as my near-miss taught me directly.",
        "advice_for_parents": "Naval architecture is a genuine, specialized engineering career most people know little about — it's a legitimate, well-regarded field within maritime engineering.",
        "faqs": [{"question": "What's the difference between naval architecture and marine engineering?", "answer": "Naval architects focus on vessel design, stability, and structure; marine engineers focus more on propulsion, mechanical, and electrical systems aboard the vessel."}],
        "projects": ["Led design work on over a dozen commercial vessels"], "research": [], "certifications": [],
        "conferences": [], "organizations": ["Swedish Society of Naval Architects and Marine Engineers"],
        "volunteer_work": ["Mentors engineering students interested in maritime careers"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_voice_actor_marco_rinaldi",
        "name": "Marco Rinaldi, Voice Actor",
        "role_type": "creator", "field": "voice acting", "bio": "Voices characters for animation and video games; was let go from a major recurring role after struggling to maintain vocal consistency during a health issue.",
        "trait_tags": ["creativity", "persistence"], "learning_style_fit": "Students drawn to performance who want a career less dependent on physical appearance.",
        "organization": "Independent freelance voice actor", "years_experience": 10, "journey_highlights": ["Lost a major recurring voice role after struggling with vocal health issues", "Has since voiced lead characters in several successful animated productions"],
        "discussion_topics": ["Losing a major role due to a health setback", "Voice acting as a genuine, competitive creative career", "Protecting your voice as a professional instrument"],
        "profession": "Voice Actor", "specialization": "Animation and video game character voices", "country": "Italy", "city": "Rome",
        "industries": ["entertainment", "media"], "education": ["Acting training program, self-directed voice acting specialization"],
        "current_role": "Freelance Voice Actor", "languages": ["Italian", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students drawn to performance who want a career not dependent on physical appearance", "Students who've lost an opportunity due to a health setback", "Students interested in voice acting for animation or games specifically"],
        "career_ids": [],
        "career_journey": [
            {"stage": "first_job", "label": "Began auditioning for voice roles after traditional stage acting training", "description": "Found voice work suited his skills better than on-camera acting.", "year_label": "2013-2015"},
            {"stage": "promotion", "label": "Landed a major recurring voice role in a popular animated series", "description": "The role became his primary income source and creative focus for several years.", "year_label": "2016-2019"},
            {"stage": "failure", "label": "Developed a vocal health issue that made maintaining the character's voice increasingly difficult", "description": "Was ultimately let go from the recurring role when he couldn't reliably deliver the required vocal consistency during recovery.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Worked with a vocal health specialist and rebuilt his career around roles suited to his recovered voice", "description": "Learned to treat his voice with the same care a professional athlete gives their body.", "year_label": "2020"},
            {"stage": "current_role", "label": "Freelance Voice Actor", "description": "Has since voiced lead characters in several successful animated productions.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Auditions, recording sessions, and dedicated vocal health maintenance routines.",
        "weekly_routine": "Irregular, audition and booking-dependent schedule, with consistent vocal care practices built into every day regardless of bookings.",
        "biggest_challenges": ["Protecting his voice as his literal professional instrument", "The unpredictable, competitive nature of freelance voice work"],
        "favourite_part": "Bringing a character fully to life purely through vocal performance.",
        "biggest_misconceptions": ["That voice acting is easy compared to on-camera performance", "That losing a major role due to health issues ends a voice acting career"],
        "what_surprised_them": "How much voice acting is a genuine athletic and health discipline, not just a creative performance skill.",
        "biggest_mistake": "I didn't take early warning signs of vocal strain seriously enough during that recurring role, continuing to push through recording sessions without proper rest or professional vocal health support. By the time I sought real help, the issue had become serious enough to cost me the role. I now treat vocal health maintenance as a non-negotiable daily discipline.",
        "one_regret": "I regret not seeking a vocal health specialist's help at the first sign of strain — early intervention likely would have let me keep that role.",
        "salary_reality": "Voice acting income is genuinely unpredictable and audition-dependent, especially before establishing a strong reputation — many voice actors supplement with other performance or teaching work.",
        "work_life_balance": "Irregular by nature, dictated by auditions and bookings rather than a fixed schedule.",
        "daily_skills": ["vocal performance range", "character interpretation", "vocal health maintenance"],
        "daily_tools": ["Home recording studio equipment", "vocal warm-up and care routines"],
        "recommended_books": ["The Art of Voice Acting by James Alburger"],
        "recommended_communities": ["Italian voice actors guild"],
        "advice_for_beginners": "Treat vocal health as a daily, non-negotiable discipline from the very start of your career — my lost role came directly from ignoring early warning signs.",
        "advice_for_parents": "Voice acting is a genuine, competitive creative career, and a health setback affecting your child's voice is a real occupational risk worth taking seriously, but it's often recoverable with proper care.",
        "faqs": [{"question": "Is voice acting a stable career?", "answer": "It's genuinely competitive and often unpredictable, especially early on — most successful voice actors build a career gradually over years, often alongside other performance work."}],
        "projects": ["Has voiced lead characters in several successful animated productions"], "research": [], "certifications": [],
        "conferences": [], "organizations": ["Italian voice actors guild"],
        "volunteer_work": ["Speaks to drama students about vocal health for performers"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_water_resource_engineer_amara_diallo",
        "name": "Amara Diallo, Water Resource Engineer",
        "role_type": "industry_professional", "field": "civil engineering", "bio": "Designs clean water access infrastructure for rural communities; her first well-drilling project failed to find viable water after months of work and significant funding.",
        "trait_tags": ["persistence", "values"], "learning_style_fit": "Students interested in engineering with a direct, tangible community impact.",
        "organization": "A water infrastructure nonprofit", "years_experience": 9, "journey_highlights": ["Her first major well-drilling project failed to find viable water after months of work", "Has since brought clean water access to over 40 rural communities"],
        "discussion_topics": ["A completely failed infrastructure project and what came after", "Water engineering as mission-driven civil engineering", "Working directly with communities on infrastructure"],
        "profession": "Water Resource Engineer", "specialization": "Rural clean water access infrastructure", "country": "Mali", "city": "Bamako",
        "industries": ["engineering & construction", "international development"], "education": ["BEng Civil Engineering, École Nationale d'Ingénieurs Bamako"],
        "current_role": "Lead Water Resource Engineer", "languages": ["French", "Bambara", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students interested in engineering with direct community impact", "Students who've had a project fail completely despite real effort", "Students interested in international development engineering"],
        "career_ids": ["civil_engineer", "ngo_program_manager"],
        "career_journey": [
            {"stage": "university", "label": "BEng Civil Engineering", "description": "Focused her final-year project on rural water access challenges.", "year_label": "2010-2015"},
            {"stage": "first_job", "label": "Junior engineer at a water infrastructure nonprofit", "description": "Led her first independent well-drilling project in a rural community.", "year_label": "2015-2016"},
            {"stage": "failure", "label": "The project failed to find viable groundwater after months of drilling and significant donor funding", "description": "Faced real disappointment from the community and difficult conversations with funders about the failed investment.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Invested in better hydrogeological survey technology before any future drilling", "description": "Never again began a drilling project without much more rigorous upfront geological assessment.", "year_label": "2017"},
            {"stage": "current_role", "label": "Lead Water Resource Engineer", "description": "Has since brought clean water access to over 40 rural communities.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "A mix of hydrogeological survey work, community consultation, and construction oversight for water infrastructure projects.",
        "weekly_routine": "Significant field travel to rural project sites, with office-based planning and reporting between site visits.",
        "biggest_challenges": ["The genuine unpredictability of groundwater availability despite careful planning", "Managing community expectations and trust after visible project setbacks"],
        "favourite_part": "A community's first day with reliable access to clean water after years of walking hours to collect it.",
        "biggest_misconceptions": ["That finding groundwater is straightforward once you pick a location", "That a failed drilling project reflects poor engineering competence rather than genuine geological uncertainty"],
        "what_surprised_them": "How much upfront geological survey work matters compared to the drilling itself.",
        "biggest_mistake": "I began my first major drilling project with only basic geological assessment, trusting local knowledge and simplified survey methods rather than investing in more rigorous hydrogeological testing upfront. The site turned out to lack viable groundwater despite months of drilling, wasting real time and donor funding. I now insist on thorough survey technology before committing to any drilling site.",
        "one_regret": "I regret not advocating harder for proper survey funding before that first project — the cost of rigorous upfront assessment is far less than the cost of a failed drilling attempt.",
        "salary_reality": "Water infrastructure engineering in the nonprofit sector pays modestly in Mali, though the direct community impact is what sustains most engineers in this specific field.",
        "work_life_balance": "Significant field travel to often remote communities, with real physical demands, though a generally predictable project-based schedule.",
        "daily_skills": ["hydrogeological assessment", "water infrastructure design", "community engagement"],
        "daily_tools": ["Groundwater survey equipment", "well drilling technology"],
        "recommended_books": ["Water 4.0 by David Sedlak"],
        "recommended_communities": ["West African water engineers network"],
        "advice_for_beginners": "Invest in rigorous upfront geological survey work before any drilling project — my failed first project wasted real resources that better assessment would have prevented.",
        "advice_for_parents": "Water infrastructure engineering carries real project risk given genuine geological uncertainty, but it's a mission-driven, deeply impactful engineering career, not a lesser specialization.",
        "faqs": [{"question": "Why do some well-drilling projects fail to find water?", "answer": "Groundwater availability is genuinely difficult to predict with certainty — even with good survey work, some sites simply don't have viable water, which is why thorough upfront assessment matters so much."}],
        "projects": ["Has brought clean water access to over 40 rural communities"], "research": [], "certifications": [],
        "conferences": [], "organizations": ["West African water engineers network"],
        "volunteer_work": ["Trains junior engineers on rigorous hydrogeological survey methods"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch14).")


if __name__ == "__main__":
    asyncio.run(seed())
