"""Connect Batch 1 — Expert Connect seed data, eleventh wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch11
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_anesthesiologist_farid_hosseini",
        "name": "Dr. Farid Hosseini, Anesthesiologist",
        "role_type": "industry_professional", "field": "medicine", "bio": "Practices anesthesiology at a surgical hospital; a dosing miscalculation early in residency, caught by a supervising physician, still shapes his practice today.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who want extreme precision work with immediate, high-stakes feedback.",
        "organization": "A surgical hospital", "years_experience": 12, "journey_highlights": ["Made a dosing miscalculation during residency caught just in time by a supervisor", "Now trains anesthesiology residents on medication safety protocols"],
        "discussion_topics": ["A near-miss medication error during training", "Anesthesiology as an intensely precise medical specialty", "Handling the pressure of patient safety in real time"],
        "profession": "Anesthesiologist", "specialization": "Surgical anesthesia", "country": "Iran", "city": "Tehran",
        "industries": ["healthcare"], "education": ["MD, Tehran University of Medical Sciences", "Anesthesiology residency"],
        "current_role": "Attending Anesthesiologist", "languages": ["Persian", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who want extremely precise, high-stakes medical work", "Students who've had a near-miss error caught by someone else", "Students choosing a medical specialty involving less direct patient conversation but intense technical precision"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "university", "label": "MD", "description": "Drawn to anesthesiology's blend of pharmacology and real-time physiological monitoring.", "year_label": "2006-2012"},
            {"stage": "first_job", "label": "Anesthesiology residency", "description": "Learned dosing calculations and patient monitoring under close supervision.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Miscalculated a medication dose during a complex case, caught just in time by his supervising physician", "description": "The near-miss, though it caused no harm, terrified him and reshaped his entire approach to double-checking every calculation.", "year_label": "2014"},
            {"stage": "turning_point", "label": "Adopted a strict personal protocol of independently re-verifying every dosage calculation", "description": "Never had a similar near-miss again through the rest of his training and career.", "year_label": "2015"},
            {"stage": "current_role", "label": "Attending Anesthesiologist", "description": "Now trains residents specifically on medication safety protocols.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "Pre-operative patient assessment, administering and monitoring anesthesia throughout surgeries, and post-operative recovery oversight.",
        "weekly_routine": "Scheduled surgical cases throughout the week, with occasional emergency surgery coverage.",
        "biggest_challenges": ["The zero-margin-for-error nature of medication dosing", "Sustained intense focus required throughout long surgical procedures"],
        "favourite_part": "A patient waking up safely and comfortably after a complex surgery.",
        "biggest_misconceptions": ["That anesthesiologists just 'put people to sleep' with minimal ongoing involvement", "That a near-miss error reflects incompetence rather than the genuine, appropriate rigor of safety systems working as designed"],
        "what_surprised_them": "How much continuous, real-time physiological monitoring and adjustment the role requires throughout a procedure, not just at the start.",
        "biggest_mistake": "During a complex case in residency, I made a dosing calculation error under time pressure that my supervising physician caught before it reached the patient. It terrified me, but it also taught me that the safety systems — the requirement for supervisor verification — exist for exactly this reason, and I never resented the additional check again.",
        "one_regret": "I regret feeling ashamed of that near-miss for longer than was useful — it was a normal part of training, precisely why the verification system exists.",
        "salary_reality": "Anesthesiology is a well-compensated medical specialty in Iran, reflecting its demanding training and the precision required.",
        "work_life_balance": "Generally more predictable than emergency specialties, though surgical schedules can extend hours unpredictably.",
        "daily_skills": ["pharmacology", "real-time patient monitoring", "precise dosing calculation"],
        "daily_tools": ["Anesthesia delivery and monitoring equipment"],
        "recommended_books": ["Anesthesia: A Very Short Introduction by Aidan O'Donnell"],
        "recommended_communities": ["Iranian Society of Anesthesiology"],
        "advice_for_beginners": "Never skip an independent double-check on dosing calculations, no matter how confident you feel or how much time pressure exists — the safety system caught my one near-miss for exactly this reason.",
        "advice_for_parents": "A caught near-miss error during training is the safety system working correctly, not a sign your child shouldn't continue in medicine.",
        "faqs": [{"question": "What does an anesthesiologist actually do during surgery?", "answer": "Far more than administering initial anesthesia — continuous real-time monitoring and adjustment of a patient's vital functions throughout the entire procedure."}],
        "projects": [], "research": [], "certifications": ["Board certification in Anesthesiology"],
        "conferences": [], "organizations": ["Iranian Society of Anesthesiology"],
        "volunteer_work": ["Trains residents on medication safety verification protocols"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_interior_designer_chloe_bernard",
        "name": "Chloé Bernard, Interior Designer",
        "role_type": "founder", "field": "interior design", "bio": "Runs a residential and commercial interior design studio; her first major commercial project went significantly over budget due to poor cost estimation.",
        "trait_tags": ["creativity", "analytical_thinking"], "learning_style_fit": "Students who like combining creative vision with real budget and client management.",
        "organization": "An independent interior design studio", "years_experience": 11, "journey_highlights": ["Her first major commercial project went significantly over budget", "Now leads a studio with a growing portfolio of hospitality and residential clients"],
        "discussion_topics": ["Learning to budget realistically as a creative professional", "Interior design as a genuine business, not just aesthetics", "Building a design studio from freelance work"],
        "profession": "Interior Designer", "specialization": "Residential and boutique hospitality design", "country": "France", "city": "Marseille",
        "industries": ["design", "hospitality"], "education": ["BA Interior Architecture, École Camondo"],
        "current_role": "Founder and Principal Designer", "languages": ["French", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like design but need real business and budgeting skills too", "Students who've gone significantly over budget on a project", "Students interested in hospitality or residential design specifically"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Interior Architecture", "description": "Focused her studies on spatial design theory, with limited practical budgeting coursework.", "year_label": "2008-2012"},
            {"stage": "first_job", "label": "Junior designer at a design firm", "description": "Worked on smaller residential projects under supervision.", "year_label": "2012-2015"},
            {"stage": "failure", "label": "Her first independent major commercial project went significantly over budget", "description": "Underestimated material and labor costs, straining her relationship with the client and her own emerging business's finances.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Built a rigorous cost-estimation and contingency system for every subsequent project", "description": "Partnered with a contractor consultant to validate her budget estimates before presenting them to clients.", "year_label": "2017"},
            {"stage": "current_role", "label": "Founder and Principal Designer", "description": "Now leads a studio with a growing portfolio of hospitality and residential clients.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "A mix of design concept work, client presentations, and coordination with contractors and suppliers.",
        "weekly_routine": "Design development early in projects, heavy coordination and site visits during construction phases.",
        "biggest_challenges": ["Realistic budget estimation for creative, sometimes novel design elements", "Balancing client vision against practical construction constraints"],
        "favourite_part": "Walking through a completed space and seeing a client's genuine emotional reaction to it.",
        "biggest_misconceptions": ["That interior design is just choosing furniture and colors", "That going over budget on a project reflects a lack of real design skill"],
        "what_surprised_them": "How much of successful interior design is really project management and cost estimation, not aesthetic choices.",
        "biggest_mistake": "On my first major commercial project, I estimated material and labor costs based on rough assumptions rather than getting real contractor quotes before presenting the budget to my client. The gap between my estimate and reality strained the client relationship badly, and I now always validate budgets with real contractor input before any client presentation.",
        "one_regret": "I regret not partnering with a contractor consultant from the very start of my independent career — it would have prevented that costly, relationship-straining mistake entirely.",
        "salary_reality": "Interior design income in France varies enormously by client base — established studios like mine can be quite profitable, but the early years of freelance work were genuinely financially unstable.",
        "work_life_balance": "Demanding during active project phases, particularly near installation deadlines.",
        "daily_skills": ["spatial design", "budget management", "client relations"],
        "daily_tools": ["3D design and rendering software", "project budgeting spreadsheets"],
        "recommended_books": ["The Interior Design Business Handbook by Mary Knackstedt"],
        "recommended_communities": ["French interior designers association"],
        "advice_for_beginners": "Get real contractor quotes before presenting any project budget to a client — my costly overrun came from rough estimates instead of verified numbers.",
        "advice_for_parents": "Interior design is a genuine business requiring real budgeting and project management skill, not just creative talent — a costly early project taught her this, and it's a normal part of the learning curve.",
        "faqs": [{"question": "Is interior design mostly about aesthetics?", "answer": "Aesthetics matter, but successful interior design businesses depend just as much on realistic budgeting, contractor coordination, and project management."}],
        "projects": ["Leads a studio with a growing hospitality and residential portfolio"], "research": [], "certifications": [],
        "conferences": [], "organizations": ["French interior designers association"],
        "volunteer_work": ["Mentors design school graduates on real-world project budgeting"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_special_education_teacher_amina_yusuf",
        "name": "Amina Yusuf, Special Education Teacher",
        "role_type": "industry_professional", "field": "education", "bio": "Teaches students with learning disabilities at a public school; struggled deeply with feelings of ineffectiveness during her first year before finding her real approach.",
        "trait_tags": ["empathy", "persistence"], "learning_style_fit": "Students drawn to teaching who want to work specifically with students who learn differently.",
        "organization": "A public school special education program", "years_experience": 10, "journey_highlights": ["Felt deeply ineffective and considered leaving during her first year", "Developed an individualized reading program now used across her school district"],
        "discussion_topics": ["Feeling like you're failing your students in your first year", "Special education as a distinct teaching specialty", "What individualized education actually requires"],
        "profession": "Special Education Teacher", "specialization": "Learning disabilities, elementary level", "country": "Malaysia", "city": "Kuala Lumpur",
        "industries": ["education"], "education": ["BEd Special Education, Universiti Malaya"],
        "current_role": "Lead Special Education Teacher", "languages": ["Malay", "English", "Mandarin"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students interested in special education specifically, not general classroom teaching", "Students who've felt ineffective in a caring role and wanted to quit", "Students who want to know what individualized education planning really involves"],
        "career_ids": ["teacher_k12"],
        "career_journey": [
            {"stage": "university", "label": "BEd Special Education", "description": "Chose the specialization after volunteering with a learning disabilities support program during her studies.", "year_label": "2009-2013"},
            {"stage": "first_job", "label": "First special education teaching position", "description": "Felt overwhelmed and ineffective managing a classroom with widely varying individual needs.", "year_label": "2014"},
            {"stage": "failure", "label": "Seriously considered leaving teaching after a difficult first year", "description": "Felt she wasn't making real progress with several students despite her best efforts, and doubted whether she had the right skills for the role.", "year_label": "2014"},
            {"stage": "turning_point", "label": "A mentor teacher helped her develop truly individualized approaches rather than a one-size-fits-all classroom method", "description": "Her approach to each student's specific learning profile transformed her effectiveness.", "year_label": "2015"},
            {"stage": "current_role", "label": "Lead Special Education Teacher", "description": "Developed an individualized reading program now used across her entire school district.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Highly individualized instruction sessions, progress monitoring, and coordination with parents and other specialists.",
        "weekly_routine": "Structured individualized sessions throughout the week, with regular case review meetings for each student's progress.",
        "biggest_challenges": ["Managing widely varying individual student needs simultaneously", "Communicating realistic progress expectations to parents while remaining genuinely hopeful"],
        "favourite_part": "A student's breakthrough moment — a first successfully read sentence, a math concept finally clicking.",
        "biggest_misconceptions": ["That special education is a 'less academic' teaching path", "That struggling deeply in your first year means you're not suited to the work"],
        "what_surprised_them": "How much individualization the role genuinely requires — no single approach works for every student.",
        "biggest_mistake": "In my first year, I tried applying the same instructional strategies across all my students despite their genuinely different learning profiles, assuming more practice with one method would eventually work for everyone. It wasn't until I learned to build truly individualized plans for each student that I saw real progress.",
        "one_regret": "I regret how close I came to leaving the field during that difficult first year — the right mentorship, which I almost didn't seek out, completely changed my trajectory.",
        "salary_reality": "Special education teaching salaries in Malaysia's public system are modest, similar to general teaching pay, despite the additional specialized training required.",
        "work_life_balance": "Demanding — individualized planning for each student requires significant time beyond classroom hours.",
        "daily_skills": ["individualized education planning", "differentiated instruction", "behavioral support strategies"],
        "daily_tools": ["Individualized education program (IEP) tracking systems", "specialized learning materials"],
        "recommended_books": ["The Explosive Child by Ross Greene"],
        "recommended_communities": ["Malaysian special education teachers network"],
        "advice_for_beginners": "Find a mentor who can help you build genuinely individualized approaches early — my first year nearly ended in burnout before that mentorship transformed my effectiveness.",
        "advice_for_parents": "A difficult, doubt-filled first year is common among special education teachers — please know that persistence through it, with the right support, often leads to genuinely transformative work.",
        "faqs": [{"question": "Is special education a less rigorous teaching path?", "answer": "Not at all — it requires additional specialized training in individualized instruction and often more complex daily planning than general classroom teaching."}],
        "projects": ["Developed an individualized reading program now used across her school district"], "research": [],
        "certifications": ["Special Education Teaching Certification"], "conferences": [], "organizations": [],
        "volunteer_work": ["Mentors new special education teachers through their difficult first years"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_election_campaign_manager_diego_santos",
        "name": "Diego Santos, Political Campaign Manager",
        "role_type": "industry_professional", "field": "political campaigns", "bio": "Manages local and regional political campaigns; his first campaign as lead manager lost by a narrow margin, largely due to a strategic miscalculation.",
        "trait_tags": ["leadership", "communication"], "learning_style_fit": "Students interested in politics and organizing who want a behind-the-scenes strategic career.",
        "organization": "An independent political consulting firm", "years_experience": 9, "journey_highlights": ["Lost his first campaign as lead manager by a narrow margin", "Has since managed several successful regional campaigns"],
        "discussion_topics": ["Losing a close election as campaign manager", "Political campaign work as a career, not just activism", "What actually wins local elections"],
        "profession": "Political Campaign Manager", "specialization": "Local and regional election campaigns", "country": "Mexico", "city": "Guadalajara",
        "industries": ["government", "public policy"], "education": ["BA Political Science, Universidad de Guadalajara"],
        "current_role": "Senior Campaign Strategist", "languages": ["Spanish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in politics who want strategy work rather than running for office themselves", "Students who've lost a close competition due to a strategic error", "Students curious what actually wins local elections"],
        "career_ids": ["foreign_service_officer"],
        "career_journey": [
            {"stage": "university", "label": "BA Political Science", "description": "Volunteered on several campaigns throughout his studies before taking on real strategic responsibility.", "year_label": "2010-2014"},
            {"stage": "first_job", "label": "Field organizer, then deputy campaign manager", "description": "Built experience in voter outreach and campaign logistics.", "year_label": "2014-2017"},
            {"stage": "failure", "label": "Led his first campaign as lead manager to a narrow, disappointing loss", "description": "A strategic decision to prioritize media advertising over ground-level voter outreach in the campaign's final weeks proved to be a costly miscalculation.", "year_label": "2018"},
            {"stage": "turning_point", "label": "Rebuilt his campaign strategy framework to prioritize data-driven voter contact over broad advertising", "description": "Studied the specific data from his losing campaign extensively to understand exactly what went wrong.", "year_label": "2019"},
            {"stage": "current_role", "label": "Senior Campaign Strategist", "description": "Has since managed several successful regional campaigns using his revised, data-driven approach.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of strategic planning, coordinating with campaign staff, and analyzing voter data and polling.",
        "weekly_routine": "Campaign work is intensely cyclical — building slowly, then becoming extremely demanding in the final weeks before an election.",
        "biggest_challenges": ["The genuine unpredictability of voter behavior despite careful data analysis", "The emotional weight of a loss that affects an entire campaign team and candidate"],
        "favourite_part": "Election night when careful strategic work translates into a genuine electoral win.",
        "biggest_misconceptions": ["That campaigns are won primarily through advertising and media presence", "That a lost election reflects a manager's overall incompetence rather than one specific strategic misjudgment"],
        "what_surprised_them": "How much campaign success comes down to direct, personal voter contact rather than broad media strategy.",
        "biggest_mistake": "In my first campaign as lead manager, I allocated too much of our limited budget to media advertising in the final weeks, based on an assumption about voter behavior that the actual data didn't fully support. Ground-level voter contact, which we underfunded, is what data later showed mattered more in that specific race. I now build every campaign strategy around rigorous ground-game data first.",
        "one_regret": "I regret trusting a general campaign strategy playbook over the specific data from our own race — the numbers were telling a different story than the strategy I followed.",
        "salary_reality": "Political campaign management income in Mexico is highly cyclical, tied to election cycles, requiring real financial planning for the gaps between campaigns.",
        "work_life_balance": "Extremely demanding in the weeks before an election, with more balanced periods between campaign cycles.",
        "daily_skills": ["campaign strategy", "voter data analysis", "team management"],
        "daily_tools": ["Voter database software", "polling and data analytics tools"],
        "recommended_books": ["The Victory Lab by Sasha Issenberg"],
        "recommended_communities": ["Latin American political consultants network"],
        "advice_for_beginners": "Trust your own campaign's specific data over general strategic playbooks — my narrow loss came from following an assumption the actual numbers didn't support.",
        "advice_for_parents": "Political campaign work is cyclical and unpredictable by nature — losing a close election is a normal, painful, but genuinely instructive part of building real strategic expertise.",
        "faqs": [{"question": "What actually wins local political campaigns?", "answer": "Direct, personal voter contact and data-driven targeting consistently matter more than broad advertising in most local races, based on what I've seen across many campaigns."}],
        "projects": ["Has managed several successful regional political campaigns"], "research": [], "certifications": [],
        "conferences": [], "organizations": ["Latin American political consultants network"],
        "volunteer_work": ["Trains first-time campaign managers on data-driven strategy"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch11).")


if __name__ == "__main__":
    asyncio.run(seed())
