"""Connect Batch 1 — Expert Connect seed data, third wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch3
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_game_developer_felix_nguyen",
        "name": "Felix Nguyen, Game Developer",
        "role_type": "industry_professional", "field": "game development", "bio": "Builds gameplay systems at an independent game studio; his first solo game project took three years and sold fewer than 100 copies.",
        "trait_tags": ["creativity", "persistence"], "learning_style_fit": "Students who want honesty about how hard indie game development is financially.",
        "organization": "An independent game studio", "years_experience": 7, "journey_highlights": ["His first solo game sold fewer than 100 copies after three years of work", "Joined a studio whose second game became a modest commercial hit"],
        "discussion_topics": ["Indie game development financial realities", "Solo development vs. joining a studio", "Game design vs. game programming"],
        "profession": "Gameplay Programmer", "specialization": "Independent narrative games", "country": "Vietnam", "city": "Ho Chi Minh City",
        "industries": ["technology", "game development"], "education": ["BSc Computer Science, Vietnam National University"],
        "current_role": "Senior Gameplay Programmer", "languages": ["Vietnamese", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students dreaming of solo indie game development who need a realistic financial picture", "Students choosing between game programming and game design", "Students who've poured years into a project with a disappointing outcome"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BSc Computer Science", "description": "Made small game prototypes as hobby projects throughout his degree.", "year_label": "2012-2016"},
            {"stage": "first_job", "label": "Started developing a solo indie game", "description": "Worked part-time jobs to support himself while building his dream project alone.", "year_label": "2016-2019"},
            {"stage": "failure", "label": "Released the game to almost no commercial success", "description": "Sold fewer than 100 copies after three years of unpaid solo work, leaving him financially depleted.", "year_label": "2019"},
            {"stage": "career_transition", "label": "Joined an established indie studio instead of continuing solo", "description": "Traded full creative control for financial stability and collaborative support.", "year_label": "2020"},
            {"stage": "current_role", "label": "Senior Gameplay Programmer", "description": "The studio's second game became a modest but real commercial success.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Programming gameplay systems and debugging, with regular playtesting sessions with the rest of the small team.",
        "weekly_routine": "Feature development most days, with a weekly team playtest and design review.",
        "biggest_challenges": ["Balancing creative ambition against realistic scope and budget", "The financial precarity of the indie game industry generally"],
        "favourite_part": "Watching a stranger play something he built and genuinely enjoy it.",
        "biggest_misconceptions": ["That indie game development is a reliable way to make a living quickly", "That solo development is always more 'authentic' than joining a team"],
        "what_surprised_them": "How much a team's combined skills produce better results than one person's total control.",
        "biggest_mistake": "During my solo project, I kept expanding the game's scope for three years without ever validating whether people actually wanted what I was building — I never released anything playable until the very end. I now believe in releasing something small and testable early, always.",
        "one_regret": "I regret not seeking feedback or collaboration during those three solo years — isolation let me avoid hearing hard truths about the project that could have redirected it sooner.",
        "salary_reality": "Solo indie development rarely provides a living wage in the first years — my three-year solo project earned me almost nothing, and joining a studio was what finally provided real financial stability.",
        "work_life_balance": "Generally reasonable at the studio, far more balanced than his exhausting solo years.",
        "daily_skills": ["C#/C++", "Unity or Unreal Engine", "gameplay systems design"],
        "daily_tools": ["Unity", "Git", "Trello"],
        "recommended_books": ["A Game Design Vocabulary by Anna Anthropy and Naomi Clark"],
        "recommended_communities": ["Ho Chi Minh City game developers meetup"],
        "advice_for_beginners": "Release something small and playable early instead of chasing your dream game's full scope alone for years — my three years of isolation taught me this the hard way.",
        "advice_for_parents": "Independent game development carries real financial risk, especially solo — joining an established team is often a more sustainable path than working alone for years on one project.",
        "faqs": [{"question": "Can you make a living as a solo indie developer?", "answer": "It's possible but genuinely rare — most successful indie developers I know either have a team, outside income, or built a following before their first commercial release."}],
        "projects": ["Contributed gameplay programming to a studio's modestly successful commercial game"], "research": [],
        "certifications": [], "conferences": ["Game Developers Conference (attendee)"], "organizations": [],
        "volunteer_work": ["Mentors aspiring solo developers on realistic project scoping"],
        "portfolio_links": [{"label": "itch.io", "url": "https://felixnguyen.itch.io"}], "social_links": [],
    },
    {
        "id": "expert_veterinarian_sanne_de_vries",
        "name": "Dr. Sanne de Vries, Veterinarian",
        "role_type": "industry_professional", "field": "veterinary medicine", "bio": "Runs a mixed-animal veterinary practice; the emotional toll of her first euthanasia case nearly made her leave vet school.",
        "trait_tags": ["empathy", "persistence"], "learning_style_fit": "Students who love animals but want an honest picture of the emotional demands of the job.",
        "organization": "A mixed-animal veterinary clinic", "years_experience": 10, "journey_highlights": ["Nearly left veterinary school after a difficult first euthanasia case", "Now trains veterinary students through the same emotional challenges"],
        "discussion_topics": ["The emotional weight of veterinary medicine", "Mixed-animal vs. specialized veterinary practice", "What vet school doesn't prepare you for"],
        "profession": "Veterinarian", "specialization": "Mixed small and large animal practice", "country": "Netherlands", "city": "Utrecht",
        "industries": ["veterinary medicine", "healthcare"], "education": ["DVM, Utrecht University"],
        "current_role": "Lead Veterinarian, Mixed Practice Clinic", "languages": ["Dutch", "English", "German"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who love animals and want honesty about the emotional demands of the job", "Students choosing between small-animal and mixed practice", "Students worried they're 'too sensitive' for veterinary medicine"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "DVM", "description": "Excelled academically but had limited hands-on exposure to end-of-life care before clinical rotations.", "year_label": "2008-2014"},
            {"stage": "failure", "label": "A difficult first euthanasia case during a clinical rotation shook her deeply", "description": "Cried in her car afterward and seriously questioned whether she could handle this part of the job long-term.", "year_label": "2013"},
            {"stage": "turning_point", "label": "A mentor vet talked her through building sustainable emotional coping strategies", "description": "Learned this part of the job never becomes easy, but it becomes manageable with the right support.", "year_label": "2013"},
            {"stage": "first_job", "label": "Associate veterinarian at a small practice", "description": "Built confidence gradually across a range of case types.", "year_label": "2014-2018"},
            {"stage": "current_role", "label": "Lead Veterinarian, Mixed Practice Clinic", "description": "Now trains veterinary students through the same emotional challenges she once faced.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "A mix of routine checkups, surgeries, and difficult conversations with pet owners about serious diagnoses.",
        "weekly_routine": "Scheduled appointments most days, with occasional emergency cases that override the schedule.",
        "biggest_challenges": ["The emotional toll of euthanasia and difficult diagnoses, which never fully goes away", "Balancing what treatment is medically ideal against what an owner can afford"],
        "favourite_part": "A challenging medical case with a genuinely good outcome, and the owner's relief.",
        "biggest_misconceptions": ["That being a vet is just 'playing with cute animals all day'", "That struggling emotionally with hard cases means you're not cut out for the job"],
        "what_surprised_them": "How much of veterinary medicine is really about communicating with worried, grieving humans, not just treating animals.",
        "biggest_mistake": "Early in my career, I avoided being fully present and emotionally honest during difficult conversations with owners because it was easier for me, not because it served them. I learned that genuine presence, even when hard, is what owners actually need most from their vet in those moments.",
        "one_regret": "I regret almost quitting during vet school over that first euthanasia case — I didn't yet know that the difficulty gets more manageable, not that it disappears.",
        "salary_reality": "Veterinary salaries in the Netherlands are solid but reflect real, ongoing student debt from an intensive and expensive degree.",
        "work_life_balance": "Demanding, with real emergency on-call responsibilities that can disrupt evenings and weekends.",
        "daily_skills": ["veterinary diagnosis", "surgery", "client communication", "end-of-life care conversations"],
        "daily_tools": ["Veterinary diagnostic equipment", "practice management software"],
        "recommended_books": ["All Creatures Great and Small by James Herriot"],
        "recommended_communities": ["Royal Dutch Veterinary Association"],
        "advice_for_beginners": "The emotional difficulty of this job never fully disappears, but it becomes manageable — struggling with your first hard case doesn't mean you're in the wrong field.",
        "advice_for_parents": "Veterinary medicine is emotionally demanding in ways that surprise many students — please support your child through the hard cases rather than assuming difficulty means the wrong career choice.",
        "faqs": [{"question": "Does veterinary medicine get emotionally easier over time?", "answer": "It becomes more manageable with real coping strategies and support, but the difficult cases never become 'easy' — that's actually a sign of continued empathy, not weakness."}],
        "projects": [], "research": [], "certifications": ["Licensed Veterinarian, Netherlands"],
        "conferences": [], "organizations": ["Royal Dutch Veterinary Association"],
        "volunteer_work": ["Mentors veterinary students on the emotional aspects of clinical practice"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_urban_planner_kojo_asante",
        "name": "Kojo Asante, Urban Planner",
        "role_type": "industry_professional", "field": "urban planning", "bio": "Plans public transit infrastructure for a growing city government; his first major proposal was publicly rejected at a contentious town hall meeting.",
        "trait_tags": ["analytical_thinking", "communication"], "learning_style_fit": "Students interested in how cities work, and who can handle public criticism of their ideas.",
        "organization": "A municipal planning department", "years_experience": 9, "journey_highlights": ["His first major transit proposal was publicly rejected at a town hall", "Later led a bus rapid transit project now used by 50,000 daily riders"],
        "discussion_topics": ["Handling public rejection of your work", "Urban planning as a career combining design and policy", "Getting community buy-in for infrastructure projects"],
        "profession": "Senior Urban Planner", "specialization": "Public transit infrastructure", "country": "Ghana", "city": "Accra",
        "industries": ["urban development", "government"], "education": ["BSc Geography and Resource Development, University of Ghana", "MSc Urban Planning, University of Cape Town"],
        "current_role": "Senior Urban Planner, Transit Division", "languages": ["English", "Twi"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in city planning and public transit specifically", "Students who need to handle public criticism of their work", "Students weighing design-focused vs. policy-focused planning paths"],
        "career_ids": ["urban_planner", "civil_engineer"],
        "career_journey": [
            {"stage": "university", "label": "BSc Geography, then MSc Urban Planning", "description": "Developed a specific interest in transit access after growing up commuting long distances by informal transport.", "year_label": "2008-2015"},
            {"stage": "first_job", "label": "Junior planner at the municipal government", "description": "Worked on smaller zoning and land-use projects before larger infrastructure work.", "year_label": "2015-2018"},
            {"stage": "failure", "label": "His first major transit corridor proposal was rejected at a contentious public town hall", "description": "Residents felt the plan hadn't genuinely accounted for their daily needs, and the public criticism was intense and personal.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Redesigned his community engagement process before proposing again", "description": "Spent months in direct neighborhood consultations before drafting a revised plan.", "year_label": "2020"},
            {"stage": "current_role", "label": "Senior Urban Planner, Transit Division", "description": "Led a bus rapid transit project now used by roughly 50,000 daily riders.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "A mix of technical planning work, data analysis, and public consultation meetings with residents and community leaders.",
        "weekly_routine": "Technical design work most weeks, with periodic public engagement sessions during active project phases.",
        "biggest_challenges": ["Balancing technical best-practice design against genuine community needs and concerns", "The slow pace of infrastructure projects compared to a growing city's urgent needs"],
        "favourite_part": "Riding a bus route he helped design and seeing it genuinely used by the community it was built for.",
        "biggest_misconceptions": ["That urban planning is just drawing maps — it's deeply about politics and community trust", "That public rejection of a plan means the underlying idea was wrong"],
        "what_surprised_them": "How much planning success depends on relationships with the community, not just technical design quality.",
        "biggest_mistake": "My first rejected proposal failed largely because I designed it based on traffic data alone without genuinely consulting the residents who'd actually use it — I assumed the numbers spoke for themselves. That town hall taught me numbers alone never win real community trust.",
        "one_regret": "I regret not starting community consultations earlier in that first project — by the time residents saw the plan, it already felt finished and imposed on them rather than built with them.",
        "salary_reality": "Municipal planning salaries in Ghana are modest, but this project's real, visible community impact matters more to him than a higher private-sector salary would.",
        "work_life_balance": "Generally steady, with intensive periods during public consultation phases of major projects.",
        "daily_skills": ["urban design", "transit planning", "community engagement", "GIS mapping"],
        "daily_tools": ["GIS software", "traffic modeling tools"],
        "recommended_books": ["Human Transit by Jarrett Walker"],
        "recommended_communities": ["Ghana Institute of Planners"],
        "advice_for_beginners": "Start community consultation before you draft anything, not after — my rejected first proposal taught me that data alone never wins genuine public trust.",
        "advice_for_parents": "Public criticism of a young planner's early work is a normal, survivable part of the job — it shaped my son's career for the better, not worse.",
        "faqs": [{"question": "How do you handle public rejection of a project you worked hard on?", "answer": "It genuinely stings, but treating it as feedback rather than failure — and rebuilding community trust before proposing again — is what actually leads to lasting infrastructure that works."}],
        "projects": ["Led a bus rapid transit project used by roughly 50,000 daily riders"], "research": [],
        "certifications": [], "conferences": ["Africa Transportation Policy Program conference"], "organizations": ["Ghana Institute of Planners"],
        "volunteer_work": ["Runs community workshops explaining transit planning processes to residents"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_chef_isabelle_moreau",
        "name": "Isabelle Moreau, Executive Chef",
        "role_type": "industry_professional", "field": "culinary arts", "bio": "Runs the kitchen of a mid-size restaurant; was fired from her first professional kitchen job for a service mistake that still embarrasses her.",
        "trait_tags": ["creativity", "leadership"], "learning_style_fit": "Students drawn to intense, hands-on creative work under real time pressure.",
        "organization": "A mid-size restaurant", "years_experience": 16, "journey_highlights": ["Was fired from her first professional kitchen job", "Now leads a kitchen team of 12"],
        "discussion_topics": ["Getting fired and rebuilding a culinary career", "The real physical and emotional demands of professional kitchens", "Culinary school vs. working your way up"],
        "profession": "Executive Chef", "specialization": "Modern French-influenced cuisine", "country": "France", "city": "Lyon",
        "industries": ["hospitality", "culinary arts"], "education": ["Culinary diploma, Institut Paul Bocuse"],
        "current_role": "Executive Chef", "languages": ["French", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who want a realistic picture of professional kitchen culture", "Students who've been fired or failed early in a job and wonder if they can recover", "Students weighing culinary school against working their way up without one"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "Culinary diploma", "description": "Trained under classical French technique instruction.", "year_label": "2003-2005"},
            {"stage": "first_job", "label": "Line cook at a high-pressure fine dining restaurant", "description": "Struggled to keep pace during a chaotic dinner service.", "year_label": "2005-2006"},
            {"stage": "failure", "label": "Was fired after a serious service mistake during a busy night", "description": "Sent out an incorrectly prepared dish during a critical service period, embarrassing the head chef in front of the restaurant's owner.", "year_label": "2006"},
            {"stage": "turning_point", "label": "Took a humbler prep cook role at a smaller restaurant to rebuild her skills and confidence", "description": "Spent two years mastering fundamentals before returning to a fast-paced kitchen.", "year_label": "2007-2008"},
            {"stage": "promotion", "label": "Worked her way up through sous chef roles across several restaurants", "description": "Built a reputation for reliability that outweighed her early setback.", "year_label": "2009-2018"},
            {"stage": "current_role", "label": "Executive Chef", "description": "Leads a kitchen team of 12 at a well-regarded restaurant.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Menu planning and prep in the morning, intense service management during lunch and dinner rushes.",
        "weekly_routine": "Six demanding days a week, with the schedule built entirely around service hours, not standard business hours.",
        "biggest_challenges": ["Maintaining consistency and quality under real, unrelenting time pressure", "The physical toll of long hours standing in a hot, fast-paced kitchen"],
        "favourite_part": "A perfectly executed service where the whole team moves like one coordinated unit.",
        "biggest_misconceptions": ["That professional cooking is glamorous like television portrays", "That being fired once means you don't have what it takes"],
        "what_surprised_them": "How much leadership and team psychology matters in running a kitchen, beyond pure cooking skill.",
        "biggest_mistake": "The mistake that got me fired came from trying to move too fast without properly checking my work during a chaotic service — I let the pressure override the discipline I'd been trained in. It's a mistake I now specifically train my own team to avoid, no matter how busy service gets.",
        "one_regret": "I regret how ashamed I felt after being fired — I almost left the industry entirely instead of taking the humbler rebuilding role that ultimately relaunched my career.",
        "salary_reality": "Executive chef salaries in Lyon are respectable, but years of low-paid, physically grueling line cook work are the real, unavoidable dues most chefs pay first.",
        "work_life_balance": "Genuinely demanding — long hours, evening and weekend work, and real physical exhaustion are standard in this career.",
        "daily_skills": ["culinary technique", "kitchen management", "menu development"],
        "daily_tools": ["Professional kitchen equipment", "inventory and cost management systems"],
        "recommended_books": ["Kitchen Confidential by Anthony Bourdain"],
        "recommended_communities": ["Lyon culinary professionals association"],
        "advice_for_beginners": "Being fired once doesn't end a culinary career — taking a humbler role to rebuild my fundamentals is what actually relaunched mine.",
        "advice_for_parents": "Professional kitchens are genuinely demanding, high-pressure environments — a setback early on is common, and persistence through it is often what separates a lasting career from a short one.",
        "faqs": [{"question": "Do you need culinary school to become a chef?", "answer": "It helps with fundamentals, but many respected chefs worked their way up through kitchens without formal training — consistency and resilience matter as much as technique."}],
        "projects": [], "research": [], "certifications": [],
        "conferences": [], "organizations": [], "volunteer_work": ["Trains at-risk youth in basic culinary skills through a local nonprofit"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch3).")


if __name__ == "__main__":
    asyncio.run(seed())
