"""One-time seed script for Opportunity Hub's Opportunity Knowledge Base
(Phase 2 Stage 2).

Run via: python -m aureon.scripts.seed_opportunities

~18 illustrative composite postings spanning all 12 supported
categories — real structured content, not prompt text, proving the
matching/scoring architecture. Not presented as full coverage and not
claimed as live/currently-open/contactable listings scraped from real
organizations — same honesty convention as
seed_mentors_institutions.py's mentor/institution personas and each
Opportunity's own `source_note`. Idempotent: uses
OpportunityRepository.upsert_opportunity, which only bumps `version`
when real content differs, so re-running with unchanged data is a true
no-op.
"""

import asyncio

from aureon.domain.models.opportunity import Opportunity
from aureon.services.supabase.repositories.opportunity_repository import OpportunityRepository

OPPORTUNITIES: list[dict] = [
    {
        "id": "opp_applied_ai_internship",
        "title": "Applied AI Engineering Internship",
        "category": "internship",
        "organization": "A mid-size AI product company",
        "organization_kind": "company",
        "description": "An 8-week internship building applied ML features for a real production product.",
        "eligibility": ["Undergraduate or graduate students", "Basic Python proficiency required"],
        "required_skills": ["python", "machine learning", "git"],
        "preferred_skills": ["pytorch", "docker"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["ai", "machine learning", "software engineering"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "Paid stipend",
        "duration_label": "8 weeks", "duration_weeks": 8,
        "difficulty_level": "intermediate", "estimated_competitiveness": "high",
        "application_deadline": "2026-09-15T00:00:00Z",
        "application_steps": ["Submit resume + GitHub link", "Take-home ML exercise", "Interview"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-09-15T00:00:00Z"}],
        "benefits": ["Mentorship from senior engineers", "Letter of recommendation on completion"],
        "official_link": "https://example.org/opportunities/applied-ai-internship",
        "required_documents": ["Resume", "GitHub profile link"],
    },
    {
        "id": "opp_frontend_web_internship",
        "title": "Frontend Web Development Internship",
        "category": "internship",
        "organization": "A regional e-commerce company",
        "organization_kind": "company",
        "description": "A 10-week internship building customer-facing web features.",
        "eligibility": ["Undergraduate students in their 2nd year or later"],
        "required_skills": ["javascript", "react", "css"],
        "preferred_skills": ["typescript"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["web development", "frontend", "software engineering"],
        "location": "Bengaluru, India", "is_remote": False, "countries": ["India"],
        "paid": True, "compensation_summary": "Paid stipend + travel allowance",
        "duration_label": "10 weeks", "duration_weeks": 10,
        "difficulty_level": "intermediate", "estimated_competitiveness": "medium",
        "application_deadline": "2026-08-05T00:00:00Z",
        "application_steps": ["Submit resume", "Coding assessment", "Interview"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-08-05T00:00:00Z"}],
        "benefits": ["Full-time offer track", "Mentorship"],
        "official_link": "https://example.org/opportunities/frontend-internship",
        "required_documents": ["Resume"],
    },
    {
        "id": "opp_data_science_internship",
        "title": "Data Science Summer Internship",
        "category": "internship",
        "organization": "A logistics analytics company",
        "organization_kind": "company",
        "description": "A 12-week internship applying statistics and ML to real logistics data.",
        "eligibility": ["Undergraduate or graduate students", "Coursework in statistics or ML preferred"],
        "required_skills": ["python", "sql", "statistics"],
        "preferred_skills": ["pandas"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["data science", "machine learning", "analytics"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "Paid stipend",
        "duration_label": "12 weeks", "duration_weeks": 12,
        "difficulty_level": "intermediate", "estimated_competitiveness": "high",
        "application_deadline": "2026-07-24T00:00:00Z",
        "application_steps": ["Submit resume", "Data case study", "Interview"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-07-24T00:00:00Z"}],
        "benefits": ["Mentorship", "Conference travel stipend"],
        "official_link": "https://example.org/opportunities/data-science-internship",
        "required_documents": ["Resume", "Unofficial transcript"],
    },
    {
        "id": "opp_open_robotics_hackathon",
        "title": "Open Robotics Build Sprint",
        "category": "hackathon",
        "organization": "A regional robotics community group",
        "organization_kind": "community",
        "description": "A weekend hackathon building small autonomous robots from provided kits.",
        "eligibility": ["Open to all students"],
        "required_skills": ["robotics", "arduino", "python"],
        "preferred_skills": ["3d printing"],
        "min_academic_level": "any",
        "domain_tags": ["robotics", "hardware", "embedded systems"],
        "location": "Hyderabad, India", "is_remote": False, "countries": ["India"],
        "paid": False, "compensation_summary": None,
        "duration_label": "2 days", "duration_weeks": 0.3,
        "difficulty_level": "intermediate", "estimated_competitiveness": "medium",
        "application_deadline": "2026-07-20T00:00:00Z",
        "application_steps": ["Register as a team of up to 4", "Attend the build sprint"],
        "timeline": [{"label": "Registration closes", "detail": "Last day to register a team", "date": "2026-07-20T00:00:00Z"}],
        "benefits": ["Robotics kit to keep", "Cash prizes for top 3 teams"],
        "official_link": "https://example.org/opportunities/robotics-build-sprint",
        "required_documents": [],
    },
    {
        "id": "opp_global_ai_hackathon",
        "title": "Global AI Hack Weekend",
        "category": "hackathon",
        "organization": "A global developer community",
        "organization_kind": "community",
        "description": "A 48-hour remote hackathon building AI-powered prototypes.",
        "eligibility": ["Open to all students and early-career developers"],
        "required_skills": ["python", "machine learning"],
        "preferred_skills": ["llm apis"],
        "min_academic_level": "any",
        "domain_tags": ["ai", "machine learning", "hackathon"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "48 hours", "duration_weeks": 0.3,
        "difficulty_level": "beginner", "estimated_competitiveness": "medium",
        "application_deadline": "2026-08-25T00:00:00Z",
        "application_steps": ["Register a team", "Submit a working prototype by the deadline"],
        "timeline": [{"label": "Registration closes", "detail": "Last day to register", "date": "2026-08-20T00:00:00Z"}],
        "benefits": ["Cash prizes", "Mentorship from industry judges"],
        "official_link": "https://example.org/opportunities/global-ai-hackathon",
        "required_documents": [],
    },
    {
        "id": "opp_computer_vision_research",
        "title": "Computer Vision Undergraduate Research Program",
        "category": "research_program",
        "organization": "A public research university",
        "organization_kind": "university",
        "description": "A semester-long undergraduate research placement in a computer vision lab.",
        "eligibility": ["Undergraduate students only", "Coursework in linear algebra and programming"],
        "required_skills": ["python", "machine learning", "research"],
        "preferred_skills": ["pytorch", "opencv"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["ai", "computer vision", "research"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "Small research stipend",
        "duration_label": "1 semester", "duration_weeks": 16,
        "difficulty_level": "advanced", "estimated_competitiveness": "high",
        "application_deadline": "2026-10-01T00:00:00Z",
        "application_steps": ["Submit resume + statement of interest", "Faculty interview"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-10-01T00:00:00Z"}],
        "benefits": ["Co-authorship opportunity on publications", "Letter of recommendation"],
        "official_link": "https://example.org/opportunities/cv-research-program",
        "required_documents": ["Resume", "Statement of interest", "Unofficial transcript"],
    },
    {
        "id": "opp_materials_science_research",
        "title": "Materials Science Undergraduate Research Program",
        "category": "research_program",
        "organization": "A public research university",
        "organization_kind": "university",
        "description": "A semester-long placement in a materials science lab studying battery materials.",
        "eligibility": ["Undergraduate students only"],
        "required_skills": ["research", "lab work"],
        "preferred_skills": ["data analysis"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["materials science", "research", "engineering"],
        "location": "Cambridge, USA", "is_remote": False, "countries": ["United States"],
        "paid": True, "compensation_summary": "Research stipend",
        "duration_label": "1 semester", "duration_weeks": 16,
        "difficulty_level": "advanced", "estimated_competitiveness": "medium",
        "application_deadline": "2026-11-01T00:00:00Z",
        "application_steps": ["Submit resume + statement of interest", "Faculty interview"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-11-01T00:00:00Z"}],
        "benefits": ["Lab experience", "Letter of recommendation"],
        "official_link": "https://example.org/opportunities/materials-research-program",
        "required_documents": ["Resume", "Statement of interest"],
    },
    {
        "id": "opp_robotics_innovation_competition",
        "title": "National Robotics Innovation Competition",
        "category": "competition",
        "organization": "A national student engineering association",
        "organization_kind": "nonprofit",
        "description": "A national competition to design and demo an original robotics solution.",
        "eligibility": ["Undergraduate teams of up to 5"],
        "required_skills": ["robotics", "engineering design"],
        "preferred_skills": ["cad"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["robotics", "engineering", "innovation"],
        "location": "Delhi, India", "is_remote": False, "countries": ["India"],
        "paid": False, "compensation_summary": None,
        "duration_label": "3 months (build phase) + 2-day final", "duration_weeks": 14,
        "difficulty_level": "advanced", "estimated_competitiveness": "very_high",
        "application_deadline": "2026-08-10T00:00:00Z",
        "application_steps": ["Submit team registration + concept proposal", "Advance to build phase if selected"],
        "timeline": [{"label": "Proposals due", "detail": "Concept proposal deadline", "date": "2026-08-10T00:00:00Z"}],
        "benefits": ["Cash prizes", "National recognition"],
        "official_link": "https://example.org/opportunities/robotics-innovation-competition",
        "required_documents": ["Concept proposal"],
    },
    {
        "id": "opp_open_source_security_challenge",
        "title": "Open Source Security Challenge",
        "category": "competition",
        "organization": "A cybersecurity nonprofit",
        "organization_kind": "nonprofit",
        "description": "A capture-the-flag style competition finding real vulnerabilities in sample open-source codebases.",
        "eligibility": ["Open to all students"],
        "required_skills": ["security", "git", "python"],
        "preferred_skills": ["linux"],
        "min_academic_level": "any",
        "domain_tags": ["security", "open source", "software engineering"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "1 week", "duration_weeks": 1,
        "difficulty_level": "advanced", "estimated_competitiveness": "high",
        "application_deadline": "2026-07-28T00:00:00Z",
        "application_steps": ["Register", "Compete during the live window"],
        "timeline": [{"label": "Registration closes", "detail": "Last day to register", "date": "2026-07-26T00:00:00Z"}],
        "benefits": ["Cash prizes", "Recognition from sponsor companies"],
        "official_link": "https://example.org/opportunities/oss-security-challenge",
        "required_documents": [],
    },
    {
        "id": "opp_germany_excellence_scholarship",
        "title": "Global Excellence Scholarship for Study in Germany",
        "category": "scholarship",
        "organization": "A German academic exchange foundation",
        "organization_kind": "government",
        "description": "A scholarship covering partial tuition and living costs for international students admitted to a German university program.",
        "eligibility": ["Admitted or applying to a German university program", "Strong academic record"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "undergraduate",
        "domain_tags": ["scholarship", "study abroad", "engineering", "computer science"],
        "location": "Germany", "is_remote": False, "countries": ["Germany"],
        "paid": True, "compensation_summary": "Partial tuition + monthly stipend",
        "duration_label": "Up to 2 years", "duration_weeks": 104,
        "difficulty_level": "advanced", "estimated_competitiveness": "very_high",
        "application_deadline": "2026-12-01T00:00:00Z",
        "application_steps": ["Submit application + essays", "Academic reference letters", "Interview"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-12-01T00:00:00Z"}],
        "benefits": ["Partial tuition coverage", "Monthly living stipend", "Alumni network"],
        "official_link": "https://example.org/opportunities/germany-excellence-scholarship",
        "required_documents": ["Academic transcript", "Essays", "Reference letters"],
    },
    {
        "id": "opp_women_in_stem_scholarship",
        "title": "Women in STEM Scholarship",
        "category": "scholarship",
        "organization": "A STEM education nonprofit",
        "organization_kind": "nonprofit",
        "description": "A scholarship supporting women pursuing undergraduate STEM degrees.",
        "eligibility": ["Undergraduate students identifying as women", "Enrolled in a STEM major"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "undergraduate",
        "domain_tags": ["scholarship", "stem", "diversity"],
        "location": "Global", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "One-time award",
        "duration_label": "One-time award", "duration_weeks": None,
        "difficulty_level": "intermediate", "estimated_competitiveness": "high",
        "application_deadline": "2026-09-30T00:00:00Z",
        "application_steps": ["Submit application + essay"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-09-30T00:00:00Z"}],
        "benefits": ["One-time monetary award", "Mentorship program access"],
        "official_link": "https://example.org/opportunities/women-in-stem-scholarship",
        "required_documents": ["Essay", "Proof of enrollment"],
    },
    {
        "id": "opp_open_source_contributor_program",
        "title": "Community Open Source Contributor Program",
        "category": "open_source_program",
        "organization": "A community-maintained open-source foundation",
        "organization_kind": "nonprofit",
        "description": "An ongoing program pairing new contributors with maintainers on real open-source projects.",
        "eligibility": ["Open to all students", "Basic git familiarity"],
        "required_skills": ["git", "python"],
        "preferred_skills": ["documentation"],
        "min_academic_level": "any",
        "domain_tags": ["open source", "software engineering"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Ongoing", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Open a first-timers-only issue", "Get paired with a mentor"],
        "timeline": [],
        "benefits": ["Real open-source contribution history", "Mentor guidance"],
        "official_link": "https://example.org/opportunities/oss-contributor-program",
        "required_documents": [],
    },
    {
        "id": "opp_early_career_research_fellowship",
        "title": "Early Career Research Fellowship",
        "category": "fellowship",
        "organization": "An independent research foundation",
        "organization_kind": "nonprofit",
        "description": "A year-long fellowship supporting independent research projects proposed by the fellow.",
        "eligibility": ["Final-year undergraduates or graduate students"],
        "required_skills": ["research", "writing"],
        "preferred_skills": ["data analysis"],
        "min_academic_level": "graduate",
        "domain_tags": ["research", "fellowship"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "Annual stipend",
        "duration_label": "1 year", "duration_weeks": 52,
        "difficulty_level": "advanced", "estimated_competitiveness": "very_high",
        "application_deadline": "2026-11-15T00:00:00Z",
        "application_steps": ["Submit research proposal", "Reference letters", "Interview"],
        "timeline": [{"label": "Proposals due", "detail": "Final day to submit a proposal", "date": "2026-11-15T00:00:00Z"}],
        "benefits": ["Annual stipend", "Publication support", "Fellow network"],
        "official_link": "https://example.org/opportunities/early-career-fellowship",
        "required_documents": ["Research proposal", "Reference letters"],
    },
    {
        "id": "opp_campus_ambassador_program",
        "title": "Tech Campus Ambassador Program",
        "category": "campus_ambassador_program",
        "organization": "A developer tools company",
        "organization_kind": "company",
        "description": "An ongoing program where students represent the company on their own campus, hosting events and workshops.",
        "eligibility": ["Enrolled students with an active campus community"],
        "required_skills": ["communication", "event organizing"],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["community", "marketing", "software engineering"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "Small monthly stipend + swag",
        "duration_label": "1 academic year", "duration_weeks": 32,
        "difficulty_level": "beginner", "estimated_competitiveness": "medium",
        "application_deadline": None,
        "application_steps": ["Submit application", "Short interview"],
        "timeline": [],
        "benefits": ["Monthly stipend", "Company swag", "Networking with the developer relations team"],
        "official_link": "https://example.org/opportunities/campus-ambassador-program",
        "required_documents": [],
    },
    {
        "id": "opp_student_ai_robotics_conference",
        "title": "Student AI & Robotics Conference",
        "category": "conference",
        "organization": "A regional student engineering association",
        "organization_kind": "nonprofit",
        "description": "A 2-day student conference with talks and workshops on AI and robotics.",
        "eligibility": ["Open to all students"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["ai", "robotics", "conference"],
        "location": "Bengaluru, India", "is_remote": False, "countries": ["India"],
        "paid": False, "compensation_summary": None,
        "duration_label": "2 days", "duration_weeks": 0.3,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": "2026-08-18T00:00:00Z",
        "application_steps": ["Register for a ticket"],
        "timeline": [{"label": "Registration closes", "detail": "Last day to register", "date": "2026-08-18T00:00:00Z"}],
        "benefits": ["Networking", "Access to talks and workshops"],
        "official_link": "https://example.org/opportunities/student-ai-robotics-conference",
        "required_documents": [],
    },
    {
        "id": "opp_intro_ml_workshop",
        "title": "Intro to Machine Learning Workshop",
        "category": "workshop",
        "organization": "A university computer science department",
        "organization_kind": "university",
        "description": "A half-day hands-on workshop introducing core machine learning concepts and tools.",
        "eligibility": ["Open to all students"],
        "required_skills": ["python"],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["ai", "machine learning", "workshop"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Half day", "duration_weeks": 0.1,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": "2026-07-21T00:00:00Z",
        "application_steps": ["Register for a seat"],
        "timeline": [{"label": "Registration closes", "detail": "Last day to register", "date": "2026-07-21T00:00:00Z"}],
        "benefits": ["Hands-on ML exercise", "Course materials to keep"],
        "official_link": "https://example.org/opportunities/intro-ml-workshop",
        "required_documents": [],
    },
    {
        "id": "opp_fullstack_bootcamp",
        "title": "Full-Stack Web Development Bootcamp",
        "category": "bootcamp",
        "organization": "An independent coding school",
        "organization_kind": "company",
        "description": "An intensive 8-week bootcamp covering full-stack web development from fundamentals to deployment.",
        "eligibility": ["Open to all students", "No prior experience required"],
        "required_skills": [],
        "preferred_skills": ["javascript"],
        "min_academic_level": "any",
        "domain_tags": ["web development", "software engineering", "bootcamp"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "8 weeks", "duration_weeks": 8,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": "2026-08-30T00:00:00Z",
        "application_steps": ["Submit application", "Enrollment"],
        "timeline": [{"label": "Enrollment closes", "detail": "Last day to enroll", "date": "2026-08-30T00:00:00Z"}],
        "benefits": ["Career services support", "Portfolio projects"],
        "official_link": "https://example.org/opportunities/fullstack-bootcamp",
        "required_documents": [],
    },
    {
        "id": "opp_sustainable_tech_challenge",
        "title": "Sustainable Tech Innovation Challenge",
        "category": "innovation_challenge",
        "organization": "A sustainability-focused nonprofit",
        "organization_kind": "nonprofit",
        "description": "A challenge inviting student teams to prototype technology solutions for a real sustainability problem.",
        "eligibility": ["Undergraduate or graduate teams of up to 4"],
        "required_skills": ["engineering design", "research"],
        "preferred_skills": ["prototyping"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["sustainability", "innovation", "engineering"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "2 months", "duration_weeks": 8,
        "difficulty_level": "intermediate", "estimated_competitiveness": "medium",
        "application_deadline": "2026-09-05T00:00:00Z",
        "application_steps": ["Submit team registration + problem statement", "Submit final prototype"],
        "timeline": [{"label": "Registration closes", "detail": "Last day to register a team", "date": "2026-09-05T00:00:00Z"}],
        "benefits": ["Cash prizes", "Incubator introduction for top teams"],
        "official_link": "https://example.org/opportunities/sustainable-tech-challenge",
        "required_documents": ["Problem statement"],
    },
    # Explore Polish Batch — 22 new entries concentrated in the
    # previously-absent/sparse categories (government schemes,
    # mentorship, free certifications, funding, communities), plus a
    # few more scholarships/competitions, with deliberate global
    # diversity beyond the original catalog's US/UK/India skew.
    {
        "id": "opp_india_national_merit_scheme",
        "title": "National Merit-cum-Means Scholarship Scheme",
        "category": "government_scheme",
        "organization": "A national government scholarship body",
        "organization_kind": "government",
        "description": "A government scheme providing tuition support and a monthly stipend to meritorious students from economically weaker backgrounds.",
        "eligibility": ["Enrolled in a recognized undergraduate program", "Household income below the scheme's published threshold"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "undergraduate",
        "domain_tags": ["government scheme", "financial aid", "merit scholarship"],
        "location": "India", "is_remote": False, "countries": ["India"],
        "paid": True, "compensation_summary": "Tuition support + monthly stipend",
        "duration_label": "Renewable annually, up to degree completion", "duration_weeks": None,
        "difficulty_level": "intermediate", "estimated_competitiveness": "high",
        "application_deadline": "2026-10-31T00:00:00Z",
        "application_steps": ["Submit income and academic documentation via the government portal", "Await verification"],
        "timeline": [{"label": "Applications close", "detail": "Final day to submit documentation", "date": "2026-10-31T00:00:00Z"}],
        "benefits": ["Tuition support", "Monthly stipend", "Renewable each academic year"],
        "official_link": "https://example.org/opportunities/india-national-merit-scheme",
        "required_documents": ["Income certificate", "Academic transcript"],
    },
    {
        "id": "opp_nigeria_higher_education_grant",
        "title": "Higher Education Access Grant",
        "category": "government_scheme",
        "organization": "A national higher-education funding agency",
        "organization_kind": "government",
        "description": "A government grant program covering partial tuition costs for students in public universities, prioritizing STEM enrollment.",
        "eligibility": ["Enrolled at a public university", "Nigerian citizen"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "undergraduate",
        "domain_tags": ["government scheme", "financial aid", "stem"],
        "location": "Nigeria", "is_remote": False, "countries": ["Nigeria"],
        "paid": True, "compensation_summary": "Partial tuition coverage",
        "duration_label": "Renewable annually", "duration_weeks": None,
        "difficulty_level": "intermediate", "estimated_competitiveness": "medium",
        "application_deadline": "2026-09-20T00:00:00Z",
        "application_steps": ["Submit application through the university financial aid office", "Provide proof of enrollment"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-09-20T00:00:00Z"}],
        "benefits": ["Partial tuition coverage", "Priority renewal for STEM students"],
        "official_link": "https://example.org/opportunities/nigeria-education-access-grant",
        "required_documents": ["Proof of enrollment", "Citizenship documentation"],
    },
    {
        "id": "opp_brazil_science_mobility_scheme",
        "title": "Science and Technology Student Mobility Scheme",
        "category": "government_scheme",
        "organization": "A national science and technology ministry program",
        "organization_kind": "government",
        "description": "A government-funded scheme supporting short-term research placements abroad for STEM undergraduates.",
        "eligibility": ["Enrolled in a STEM undergraduate program", "Minimum GPA threshold set by the program"],
        "required_skills": [],
        "preferred_skills": ["english proficiency"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["government scheme", "study abroad", "research"],
        "location": "Brazil", "is_remote": False, "countries": ["Brazil"],
        "paid": True, "compensation_summary": "Travel + living stipend for placement duration",
        "duration_label": "3-6 months abroad", "duration_weeks": 20,
        "difficulty_level": "advanced", "estimated_competitiveness": "high",
        "application_deadline": "2026-11-10T00:00:00Z",
        "application_steps": ["Submit application with faculty endorsement", "Language proficiency check", "Placement matching"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-11-10T00:00:00Z"}],
        "benefits": ["Travel and living stipend", "International research experience", "Host-lab mentorship"],
        "official_link": "https://example.org/opportunities/brazil-science-mobility-scheme",
        "required_documents": ["Faculty endorsement letter", "Academic transcript"],
    },
    {
        "id": "opp_philippines_digital_skills_scheme",
        "title": "Digital Skills for Youth Government Program",
        "category": "government_scheme",
        "organization": "A national workforce development agency",
        "organization_kind": "government",
        "description": "A free government-run digital-skills training scheme for young adults, covering basic coding, data literacy, and digital tools.",
        "eligibility": ["Ages 18-28", "Philippine citizen or resident"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["government scheme", "digital skills", "workforce development"],
        "location": "Philippines", "is_remote": True, "countries": ["Philippines"],
        "paid": False, "compensation_summary": None,
        "duration_label": "12 weeks", "duration_weeks": 12,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Register online", "Complete an initial digital-literacy assessment"],
        "timeline": [],
        "benefits": ["Free training", "Government-issued completion certificate", "Job-placement referrals"],
        "official_link": "https://example.org/opportunities/philippines-digital-skills-scheme",
        "required_documents": ["Proof of residency or citizenship"],
    },
    {
        "id": "opp_global_women_tech_mentorship",
        "title": "Global Women in Tech Mentorship Circle",
        "category": "mentorship_program",
        "organization": "An international women-in-tech nonprofit",
        "organization_kind": "nonprofit",
        "description": "A 6-month remote mentorship program pairing early-career women in tech with senior industry mentors for regular 1:1 guidance.",
        "eligibility": ["Students or early-career professionals identifying as women", "Interest in a technology career path"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["mentorship", "women in tech", "career guidance"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "6 months", "duration_weeks": 26,
        "difficulty_level": "beginner", "estimated_competitiveness": "medium",
        "application_deadline": "2026-08-31T00:00:00Z",
        "application_steps": ["Submit application + goals statement", "Mentor matching"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-08-31T00:00:00Z"}],
        "benefits": ["Monthly 1:1 mentor sessions", "Peer cohort community", "Career-goal accountability check-ins"],
        "official_link": "https://example.org/opportunities/global-women-tech-mentorship",
        "required_documents": ["Goals statement"],
    },
    {
        "id": "opp_first_gen_college_mentorship",
        "title": "First-Generation College Student Mentorship Network",
        "category": "mentorship_program",
        "organization": "A first-generation student support nonprofit",
        "organization_kind": "nonprofit",
        "description": "An ongoing mentorship program connecting first-generation college students with alumni mentors who share that experience.",
        "eligibility": ["First-generation college student (neither parent completed a 4-year degree)"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "undergraduate",
        "domain_tags": ["mentorship", "first-generation", "college support"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Ongoing, renewable each semester", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Complete a short intake form", "Get matched with a mentor within 2 weeks"],
        "timeline": [],
        "benefits": ["Ongoing mentor relationship", "Access to a first-gen peer community", "Application and career-planning guidance"],
        "official_link": "https://example.org/opportunities/first-gen-mentorship-network",
        "required_documents": [],
    },
    {
        "id": "opp_southeast_asia_founder_mentorship",
        "title": "Southeast Asia Student Founder Mentorship",
        "category": "mentorship_program",
        "organization": "A regional startup ecosystem nonprofit",
        "organization_kind": "nonprofit",
        "description": "A 4-month mentorship program pairing student entrepreneurs across Southeast Asia with regional startup founders and investors.",
        "eligibility": ["Currently building or seriously planning an early-stage venture", "Enrolled student in Southeast Asia"],
        "required_skills": [],
        "preferred_skills": ["business planning"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["mentorship", "entrepreneurship", "startups"],
        "location": "Remote", "is_remote": True, "countries": ["Singapore", "Indonesia", "Philippines", "Vietnam"],
        "paid": False, "compensation_summary": None,
        "duration_label": "4 months", "duration_weeks": 17,
        "difficulty_level": "intermediate", "estimated_competitiveness": "medium",
        "application_deadline": "2026-09-12T00:00:00Z",
        "application_steps": ["Submit venture summary", "Founder mentor matching interview"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-09-12T00:00:00Z"}],
        "benefits": ["Biweekly mentor sessions", "Regional founder community access", "Investor-intro opportunities for standout ventures"],
        "official_link": "https://example.org/opportunities/sea-founder-mentorship",
        "required_documents": ["Venture summary"],
    },
    {
        "id": "opp_indigenous_stem_mentorship",
        "title": "Indigenous Students in STEM Mentorship Program",
        "category": "mentorship_program",
        "organization": "An Indigenous education advocacy nonprofit",
        "organization_kind": "nonprofit",
        "description": "A mentorship program connecting Indigenous students pursuing STEM degrees with Indigenous professionals working in STEM fields.",
        "eligibility": ["Self-identifying Indigenous student", "Enrolled in or planning a STEM program"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["mentorship", "stem", "indigenous students"],
        "location": "Remote", "is_remote": True, "countries": ["Australia", "Canada", "United States", "New Zealand"],
        "paid": False, "compensation_summary": None,
        "duration_label": "Ongoing, renewable each semester", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Complete an intake form", "Mentor matching"],
        "timeline": [],
        "benefits": ["Ongoing mentor relationship", "Community events", "Scholarship application guidance"],
        "official_link": "https://example.org/opportunities/indigenous-stem-mentorship",
        "required_documents": [],
    },
    {
        "id": "opp_free_cloud_certification",
        "title": "Free Cloud Computing Foundations Certification",
        "category": "certification",
        "organization": "A major cloud platform's education initiative",
        "organization_kind": "company",
        "description": "A free, self-paced certification covering core cloud computing concepts, ending in a proctored exam and shareable credential.",
        "eligibility": ["Open to all students"],
        "required_skills": [],
        "preferred_skills": ["basic command-line familiarity"],
        "min_academic_level": "any",
        "domain_tags": ["certification", "cloud computing", "free training"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Self-paced, ~6 weeks", "duration_weeks": 6,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Enroll for free", "Complete modules", "Pass the proctored exam"],
        "timeline": [],
        "benefits": ["Free shareable certification", "Practice labs included", "Recognized entry-level cloud credential"],
        "official_link": "https://example.org/opportunities/free-cloud-certification",
        "required_documents": [],
    },
    {
        "id": "opp_free_cybersecurity_certification",
        "title": "Free Cybersecurity Fundamentals Certification",
        "category": "certification",
        "organization": "A cybersecurity education nonprofit",
        "organization_kind": "nonprofit",
        "description": "A free certification program covering core cybersecurity concepts, network defense basics, and ethical hacking fundamentals.",
        "eligibility": ["Open to all students"],
        "required_skills": [],
        "preferred_skills": ["basic networking knowledge"],
        "min_academic_level": "any",
        "domain_tags": ["certification", "cybersecurity", "free training"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Self-paced, ~8 weeks", "duration_weeks": 8,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Enroll for free", "Complete modules and hands-on labs", "Pass the final assessment"],
        "timeline": [],
        "benefits": ["Free shareable certification", "Hands-on lab environment", "Community forum access"],
        "official_link": "https://example.org/opportunities/free-cybersecurity-certification",
        "required_documents": [],
    },
    {
        "id": "opp_free_data_analytics_certification",
        "title": "Free Data Analytics Professional Certificate",
        "category": "certification",
        "organization": "A technology company's professional-education program",
        "organization_kind": "company",
        "description": "A free, structured certificate program teaching data cleaning, visualization, and analysis using real datasets.",
        "eligibility": ["Open to all students", "No prior experience required"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["certification", "data analytics", "free training"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Self-paced, ~10 weeks", "duration_weeks": 10,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Enroll for free", "Complete guided projects", "Earn the completion certificate"],
        "timeline": [],
        "benefits": ["Free shareable certificate", "Portfolio-ready guided projects", "Career-resource library access"],
        "official_link": "https://example.org/opportunities/free-data-analytics-certificate",
        "required_documents": [],
    },
    {
        "id": "opp_free_digital_marketing_certification",
        "title": "Free Digital Marketing Certification",
        "category": "certification",
        "organization": "A global technology company's skills program",
        "organization_kind": "company",
        "description": "A free certification covering digital marketing fundamentals, analytics, and campaign strategy, widely recognized by employers.",
        "eligibility": ["Open to all students"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["certification", "digital marketing", "free training"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Self-paced, ~40 hours", "duration_weeks": 4,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Enroll for free", "Complete course modules", "Pass the certification exam"],
        "timeline": [],
        "benefits": ["Free shareable certification", "Widely recognized by employers", "Self-paced learning"],
        "official_link": "https://example.org/opportunities/free-digital-marketing-certification",
        "required_documents": [],
    },
    {
        "id": "opp_undergrad_research_micro_grant",
        "title": "Undergraduate Research Micro-Grant",
        "category": "funding_grant",
        "organization": "An independent academic research foundation",
        "organization_kind": "nonprofit",
        "description": "A small grant (up to a few hundred dollars) supporting undergraduate-led research projects with materials, software, or travel costs.",
        "eligibility": ["Undergraduate student with a defined research project", "Faculty advisor sign-off"],
        "required_skills": [],
        "preferred_skills": ["research"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["funding", "research", "grant"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "One-time micro-grant, amount varies by project scope",
        "duration_label": "One-time award", "duration_weeks": None,
        "difficulty_level": "intermediate", "estimated_competitiveness": "medium",
        "application_deadline": "2026-10-15T00:00:00Z",
        "application_steps": ["Submit project proposal + budget", "Faculty advisor endorsement"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-10-15T00:00:00Z"}],
        "benefits": ["One-time project funding", "Listed in the foundation's funded-projects registry"],
        "official_link": "https://example.org/opportunities/undergrad-research-micro-grant",
        "required_documents": ["Project proposal", "Budget breakdown", "Faculty endorsement"],
    },
    {
        "id": "opp_student_startup_seed_grant",
        "title": "Student Startup Seed Grant",
        "category": "funding_grant",
        "organization": "A university-affiliated entrepreneurship fund",
        "organization_kind": "nonprofit",
        "description": "A non-dilutive seed grant supporting student founders building an early-stage venture, paired with light-touch advisory support.",
        "eligibility": ["Currently enrolled student", "Pre-revenue or early-revenue venture"],
        "required_skills": [],
        "preferred_skills": ["business planning"],
        "min_academic_level": "undergraduate",
        "domain_tags": ["funding", "entrepreneurship", "grant"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "Non-dilutive seed grant, amount varies",
        "duration_label": "One-time award", "duration_weeks": None,
        "difficulty_level": "intermediate", "estimated_competitiveness": "high",
        "application_deadline": "2026-09-25T00:00:00Z",
        "application_steps": ["Submit pitch deck + application", "Pitch panel review"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-09-25T00:00:00Z"}],
        "benefits": ["Non-dilutive funding", "Advisory office hours", "Founder community access"],
        "official_link": "https://example.org/opportunities/student-startup-seed-grant",
        "required_documents": ["Pitch deck"],
    },
    {
        "id": "opp_environmental_action_grant",
        "title": "Youth Environmental Action Grant",
        "category": "funding_grant",
        "organization": "An international environmental nonprofit",
        "organization_kind": "nonprofit",
        "description": "A grant funding student-led environmental or conservation projects, from local clean-up initiatives to research-backed advocacy campaigns.",
        "eligibility": ["Students aged 16-25", "A defined environmental project proposal"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["funding", "environment", "conservation", "grant"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "One-time project grant",
        "duration_label": "One-time award", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "medium",
        "application_deadline": "2026-10-05T00:00:00Z",
        "application_steps": ["Submit project proposal", "Impact plan review"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-10-05T00:00:00Z"}],
        "benefits": ["Project funding", "Featured in the nonprofit's youth impact showcase"],
        "official_link": "https://example.org/opportunities/environmental-action-grant",
        "required_documents": ["Project proposal"],
    },
    {
        "id": "opp_arts_humanities_project_grant",
        "title": "Student Arts and Humanities Project Grant",
        "category": "funding_grant",
        "organization": "An independent arts and culture foundation",
        "organization_kind": "nonprofit",
        "description": "A grant supporting original student-led projects in the arts, humanities, or cultural preservation, from short films to community history archives.",
        "eligibility": ["Enrolled student with a defined creative or cultural project"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["funding", "arts", "humanities", "grant"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": True, "compensation_summary": "One-time project grant",
        "duration_label": "One-time award", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "medium",
        "application_deadline": "2026-11-20T00:00:00Z",
        "application_steps": ["Submit project proposal + creative sample"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-11-20T00:00:00Z"}],
        "benefits": ["Project funding", "Featured artist/creator spotlight"],
        "official_link": "https://example.org/opportunities/arts-humanities-project-grant",
        "required_documents": ["Project proposal", "Creative sample"],
    },
    {
        "id": "opp_global_open_source_community",
        "title": "Global Student Open Source Community",
        "category": "community_program",
        "organization": "An independent open-source foundation",
        "organization_kind": "nonprofit",
        "description": "An ongoing global community for student developers to find collaborators, get code review, and join real open-source projects together.",
        "eligibility": ["Open to all students", "Basic git familiarity"],
        "required_skills": ["git"],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["community", "open source", "software engineering"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Ongoing", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Join the community platform", "Introduce yourself in the newcomers channel"],
        "timeline": [],
        "benefits": ["Peer code review", "Project-matching help", "Regular community events"],
        "official_link": "https://example.org/opportunities/global-open-source-community",
        "required_documents": [],
    },
    {
        "id": "opp_women_stem_community",
        "title": "Women in STEM Global Community",
        "category": "community_program",
        "organization": "An international women-in-STEM nonprofit",
        "organization_kind": "nonprofit",
        "description": "An ongoing peer community for women in STEM to share resources, find study groups, and access recorded talks from women across STEM fields.",
        "eligibility": ["Students identifying as women in a STEM field"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["community", "women in stem"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Ongoing", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Join the community platform"],
        "timeline": [],
        "benefits": ["Peer study groups", "Recorded talks library", "Regional meetup listings"],
        "official_link": "https://example.org/opportunities/women-stem-community",
        "required_documents": [],
    },
    {
        "id": "opp_regional_coding_club_network",
        "title": "Regional Student Coding Club Network",
        "category": "community_program",
        "organization": "A regional student technology association",
        "organization_kind": "nonprofit",
        "description": "A network connecting individual campus coding clubs across a region, sharing workshop materials and co-hosting joint events.",
        "eligibility": ["Member of an affiliated campus coding club, or interested in starting one"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["community", "coding", "student clubs"],
        "location": "Remote", "is_remote": True, "countries": ["Kenya", "Uganda", "Tanzania", "Rwanda"],
        "paid": False, "compensation_summary": None,
        "duration_label": "Ongoing", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Register your club or join an existing one", "Attend the next joint event"],
        "timeline": [],
        "benefits": ["Shared workshop materials", "Joint cross-campus events", "Regional recognition for active clubs"],
        "official_link": "https://example.org/opportunities/regional-coding-club-network",
        "required_documents": [],
    },
    {
        "id": "opp_student_entrepreneurship_community",
        "title": "Student Entrepreneurship Community",
        "category": "community_program",
        "organization": "A global student entrepreneurship nonprofit",
        "organization_kind": "nonprofit",
        "description": "An ongoing global community for student founders to trade feedback, find co-founders, and access recorded founder AMAs.",
        "eligibility": ["Currently building or interested in building a venture"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "any",
        "domain_tags": ["community", "entrepreneurship", "startups"],
        "location": "Remote", "is_remote": True, "countries": [],
        "paid": False, "compensation_summary": None,
        "duration_label": "Ongoing", "duration_weeks": None,
        "difficulty_level": "beginner", "estimated_competitiveness": "low",
        "application_deadline": None,
        "application_steps": ["Join the community platform"],
        "timeline": [],
        "benefits": ["Co-founder matching channel", "Recorded founder AMAs", "Peer feedback threads"],
        "official_link": "https://example.org/opportunities/student-entrepreneurship-community",
        "required_documents": [],
    },
    {
        "id": "opp_south_korea_stem_scholarship",
        "title": "South Korea STEM Excellence Scholarship",
        "category": "scholarship",
        "organization": "A South Korean university consortium",
        "organization_kind": "university",
        "description": "A scholarship covering tuition and a living stipend for international students admitted to STEM graduate programs in South Korea.",
        "eligibility": ["Admitted to a participating South Korean graduate STEM program", "Strong academic record"],
        "required_skills": [],
        "preferred_skills": [],
        "min_academic_level": "graduate",
        "domain_tags": ["scholarship", "study abroad", "stem"],
        "location": "South Korea", "is_remote": False, "countries": ["South Korea"],
        "paid": True, "compensation_summary": "Full tuition + monthly living stipend",
        "duration_label": "Up to 2 years", "duration_weeks": 104,
        "difficulty_level": "advanced", "estimated_competitiveness": "very_high",
        "application_deadline": "2026-12-10T00:00:00Z",
        "application_steps": ["Submit application + research statement", "Reference letters", "Interview"],
        "timeline": [{"label": "Applications close", "detail": "Final day to apply", "date": "2026-12-10T00:00:00Z"}],
        "benefits": ["Full tuition coverage", "Monthly living stipend", "Korean language support courses"],
        "official_link": "https://example.org/opportunities/south-korea-stem-scholarship",
        "required_documents": ["Research statement", "Reference letters", "Academic transcript"],
    },
    {
        "id": "opp_mexico_remote_data_competition",
        "title": "Latin America Remote Data Science Competition",
        "category": "competition",
        "organization": "A regional data science community group",
        "organization_kind": "community",
        "description": "A month-long remote data science competition open to students across Latin America, working with real regional datasets.",
        "eligibility": ["Open to all students in Latin America"],
        "required_skills": ["python", "statistics"],
        "preferred_skills": ["machine learning"],
        "min_academic_level": "any",
        "domain_tags": ["data science", "competition", "analytics"],
        "location": "Remote", "is_remote": True, "countries": ["Mexico", "Colombia", "Chile", "Argentina", "Brazil"],
        "paid": False, "compensation_summary": None,
        "duration_label": "1 month", "duration_weeks": 4,
        "difficulty_level": "intermediate", "estimated_competitiveness": "medium",
        "application_deadline": "2026-08-22T00:00:00Z",
        "application_steps": ["Register individually or as a team of up to 3", "Submit final analysis notebook"],
        "timeline": [{"label": "Registration closes", "detail": "Last day to register", "date": "2026-08-22T00:00:00Z"}],
        "benefits": ["Cash prizes", "Regional recognition", "Judged feedback from data professionals"],
        "official_link": "https://example.org/opportunities/latam-data-science-competition",
        "required_documents": [],
    },
]


async def seed() -> None:
    repository = OpportunityRepository()
    written: list[Opportunity] = []
    for raw in OPPORTUNITIES:
        opportunity = Opportunity.model_validate(raw)
        written.append(await repository.upsert_opportunity(opportunity))
    print(f"Seeded {len(written)} opportunities.")


if __name__ == "__main__":
    asyncio.run(seed())
