"""Connect Batch 1 — Expert Connect seed data, Finance/Entrepreneurship/
Government/Public Policy/NGO domain group. See
seed_experts_tech_and_science.py for the full module-level convention
notes.

Run via: python -m aureon.scripts.seed_experts_business_and_government
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_startup_founder_ines_dubois",
        "name": "Inès Dubois, Startup Founder",
        "role_type": "founder", "field": "entrepreneurship", "bio": "Founded and sold a logistics-tech startup after her first company failed completely; now runs a second, growing company.",
        "trait_tags": ["persistence", "leadership"], "learning_style_fit": "Students who want an honest picture of startup failure, not just success stories.",
        "organization": "A logistics technology startup", "years_experience": 11, "journey_highlights": ["Her first startup failed and left her in significant debt", "Sold her second company's core technology to a larger competitor"],
        "discussion_topics": ["Surviving a startup failure and trying again", "Fundraising realities", "What founders don't post on LinkedIn"],
        "profession": "Startup Founder & CEO", "specialization": "Logistics and supply chain technology", "country": "France", "city": "Lyon",
        "industries": ["entrepreneurship", "technology", "logistics"], "education": ["MBA, EM Lyon Business School"],
        "current_role": "Founder and CEO, second logistics startup", "languages": ["French", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who want honesty about startup failure, not just success stories", "Students considering entrepreneurship straight out of school", "Students weighing a stable job against founding something risky"],
        "career_ids": ["startup_founder"],
        "career_journey": [
            {"stage": "university", "label": "MBA", "description": "Started her first company as a class project that she decided to pursue seriously after graduation.", "year_label": "2010-2012"},
            {"stage": "first_job", "label": "Founded her first startup, a food delivery app", "description": "Raised a small seed round from friends and family.", "year_label": "2013"},
            {"stage": "failure", "label": "The company ran out of money and shut down", "description": "Left her personally in debt and required her to move back in with her parents at 27.", "year_label": "2015"},
            {"stage": "career_transition", "label": "Took a corporate job to rebuild financially", "description": "Spent two years at a logistics company, which is where she found the idea for her second startup.", "year_label": "2016-2018"},
            {"stage": "turning_point", "label": "Founded her second company", "description": "This time raised proper institutional funding and built a stronger founding team.", "year_label": "2019"},
            {"stage": "current_role", "label": "Founder and CEO, second logistics startup", "description": "Recently sold the company's core routing technology to a larger competitor while continuing to grow the core business.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Mornings are investor and board communications, most of the day is split between product decisions and putting out whatever fire is most urgent that day.",
        "weekly_routine": "No two weeks look the same — the job is fundamentally reactive to whatever the business needs most urgently.",
        "biggest_challenges": ["Making high-stakes decisions with incomplete information, constantly", "The isolation of being the person everyone else looks to for confidence"],
        "favourite_part": "The early stage when an idea most people dismissed starts showing real signs of working.",
        "biggest_misconceptions": ["That founders are fearless risk-takers — most manage real, constant fear", "That funding equals success — her failed company was actually well-funded"],
        "what_surprised_them": "How much of being a founder is emotional resilience management, not strategy.",
        "biggest_mistake": "In my first company, I hired too fast on too little revenue because investors expected rapid headcount growth. When the company ran out of runway, I had to lay off people I'd personally recruited and who trusted me — that's the hardest professional experience I've had.",
        "one_regret": "I regret not talking openly about my first company's failure for almost two years — the shame kept me isolated when I actually needed to process it and learn from it with other founders.",
        "salary_reality": "Founders often pay themselves far less than they could earn elsewhere for years — I paid myself close to nothing for the first 18 months of my second company.",
        "work_life_balance": "Genuinely poor in the early stages of a company; it improved significantly once the second company had a stronger team in place.",
        "daily_skills": ["fundraising", "product strategy", "team leadership", "crisis management"],
        "daily_tools": ["Notion", "financial modeling spreadsheets", "Slack"],
        "recommended_books": ["The Hard Thing About Hard Things by Ben Horowitz"],
        "recommended_communities": ["Lyon startup founders network"],
        "advice_for_beginners": "Talk to founders who failed, not just the ones who succeeded — I learned far more from my own failure than from any success story I'd read beforehand.",
        "advice_for_parents": "A failed first company isn't proof your child shouldn't be an entrepreneur — most successful founders I know failed at least once before something worked.",
        "faqs": [{"question": "Does a failed startup ruin your career?", "answer": "No — investors and employers in the startup world often view a well-understood failure as real, valuable experience, not a disqualifier."}],
        "projects": ["Sold core routing technology to a larger logistics competitor"], "research": [],
        "certifications": [], "conferences": ["Web Summit (speaker, 2022)"], "organizations": [],
        "volunteer_work": ["Mentors early-stage founders through a regional startup accelerator"],
        "portfolio_links": [], "social_links": [{"label": "LinkedIn", "url": "https://linkedin.com/in/example-inesdubois"}],
    },
    {
        "id": "expert_investment_banker_arjun_mehta",
        "name": "Arjun Mehta, Investment Banking Analyst-turned-VC",
        "role_type": "industry_professional", "field": "finance", "bio": "Moved from investment banking to venture capital after burning out badly in his first two years; now invests in early-stage startups.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students drawn to finance but wary of the lifestyle reputation associated with it.",
        "organization": "An early-stage venture capital fund", "years_experience": 9, "journey_highlights": ["Worked 100-hour weeks in investment banking before burning out", "Moved to VC and now sits on five startup boards"],
        "discussion_topics": ["Investment banking burnout, honestly", "Banking vs. venture capital", "Breaking into finance without an elite pedigree"],
        "profession": "Venture Capital Investor", "specialization": "Early-stage technology investing", "country": "India", "city": "Mumbai",
        "industries": ["finance", "venture capital"], "education": ["BCom, Narsee Monjee College of Commerce and Economics", "MBA, Indian School of Business"],
        "current_role": "Principal, Early-Stage Venture Fund", "languages": ["English", "Hindi", "Gujarati"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students drawn to finance but worried about burnout culture", "Students confused between investment banking and venture capital paths", "Students without a background from a top-tier school wondering if finance is closed to them"],
        "career_ids": ["accountant"],
        "career_journey": [
            {"stage": "university", "label": "BCom, then MBA", "description": "Studied commerce at a well-regarded but not globally elite institution.", "year_label": "2009-2015"},
            {"stage": "first_job", "label": "Investment banking analyst", "description": "Regularly worked past midnight, sometimes pulling all-nighters before major deal closings.", "year_label": "2015-2017"},
            {"stage": "failure", "label": "Experienced a serious burnout episode", "description": "Was hospitalized briefly for exhaustion-related health issues during his second year, which forced a real reckoning.", "year_label": "2017"},
            {"stage": "career_transition", "label": "Moved into venture capital", "description": "Took a pay cut initially to join a smaller fund with a healthier culture.", "year_label": "2018"},
            {"stage": "current_role", "label": "Principal, Early-Stage Venture Fund", "description": "Now sits on the boards of five portfolio companies.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of reviewing startup pitch decks, due diligence calls, and board meetings for companies he's already invested in.",
        "weekly_routine": "Meeting-heavy, with dedicated blocks for reading through new investment opportunities.",
        "biggest_challenges": ["Saying no to founders he genuinely likes when the numbers don't work", "The pressure of decisions that affect other people's companies and livelihoods"],
        "favourite_part": "Watching a company he backed early actually succeed, years later.",
        "biggest_misconceptions": ["That all finance careers require the same brutal hours investment banking does", "That you need an elite global MBA to break into VC"],
        "what_surprised_them": "How much VC is really about pattern recognition and judgment calls, not just spreadsheet modeling.",
        "biggest_mistake": "During my banking years, I ignored clear physical warning signs of exhaustion for months because I was afraid asking for help would look weak. It ended in a hospital visit that could have been avoided with an honest conversation much earlier.",
        "one_regret": "I regret not setting boundaries earlier in my banking career — I thought the extreme hours were simply the unavoidable cost of the path, and I now know that wasn't entirely true even within banking itself.",
        "salary_reality": "Investment banking pays extremely well early but at a real cost to health and relationships; venture capital pays less upfront but with a dramatically better lifestyle and long-term upside through carried interest.",
        "work_life_balance": "Dramatically better than his banking years, though board commitments still mean real busy stretches.",
        "daily_skills": ["financial modeling", "due diligence", "negotiation", "startup evaluation"],
        "daily_tools": ["Excel", "Pitchbook", "CRM software"],
        "recommended_books": ["Venture Deals by Brad Feld and Jason Mendelson"],
        "recommended_communities": ["Mumbai angel investor network"],
        "advice_for_beginners": "Ask people currently in the role about their actual hours and health before choosing a finance path based only on the salary numbers.",
        "advice_for_parents": "If your child is showing real exhaustion in a finance career, please take it seriously — I nearly didn't, and it cost me my health for a period.",
        "faqs": [{"question": "Is investment banking worth the reputation for brutal hours?", "answer": "It can be a real launching pad, but go in with eyes open about the toll — I'd recommend setting a personal time limit for how long you'll stay in that environment."}],
        "projects": [], "research": [], "certifications": ["CFA Level II"],
        "conferences": ["TechSparks India (attendee)"], "organizations": [],
        "volunteer_work": ["Speaks at business schools about mental health in high-pressure finance careers"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_foreign_service_officer_elena_popescu",
        "name": "Elena Popescu, Foreign Service Officer",
        "role_type": "industry_professional", "field": "diplomacy", "bio": "Serves as a diplomat with postings across three continents; failed the foreign service entrance exam twice before passing.",
        "trait_tags": ["communication", "values"], "learning_style_fit": "Students drawn to international affairs who want to know what the entrance process really demands.",
        "organization": "Romanian Ministry of Foreign Affairs", "years_experience": 13, "journey_highlights": ["Failed the foreign service entrance exam twice", "Managed evacuation logistics for citizens during a regional crisis"],
        "discussion_topics": ["Failing a competitive exam and trying again", "What diplomatic postings actually involve", "Building a career that requires frequent international moves"],
        "profession": "Foreign Service Officer", "specialization": "Consular affairs and crisis response", "country": "Romania", "city": "Bucharest",
        "industries": ["government", "diplomacy"], "education": ["BA International Relations, University of Bucharest", "MA Diplomacy, College of Europe"],
        "current_role": "Deputy Head of Mission", "languages": ["Romanian", "English", "French", "German"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students preparing for a competitive government entrance exam", "Students who want an honest picture of frequent international relocation", "Students interested in crisis response work"],
        "career_ids": ["foreign_service_officer"],
        "career_journey": [
            {"stage": "university", "label": "BA International Relations, then MA Diplomacy", "description": "Studied specifically to prepare for the foreign service exam.", "year_label": "2005-2011"},
            {"stage": "failure", "label": "Failed the foreign service entrance exam on her first attempt", "description": "The written exam's specific format caught her off guard despite years of preparation.", "year_label": "2011"},
            {"stage": "failure", "label": "Failed a second time", "description": "This failure was harder — she began seriously doubting whether the career was actually meant for her.", "year_label": "2012"},
            {"stage": "turning_point", "label": "Passed on her third attempt after a full year of structured, mentor-guided preparation", "description": "Found a retired diplomat willing to coach her through mock interviews and exam strategy.", "year_label": "2013"},
            {"stage": "first_job", "label": "Junior diplomatic posting", "description": "Her first posting required leaving her home country for the first time.", "year_label": "2014-2017"},
            {"stage": "current_role", "label": "Deputy Head of Mission", "description": "Has since served in three countries, including managing a real citizen evacuation during a regional political crisis.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "A mix of official meetings, consular casework helping citizens abroad, and internal reporting back to the ministry.",
        "weekly_routine": "Structured office hours punctuated by unpredictable urgent consular cases that override the schedule entirely.",
        "biggest_challenges": ["The personal toll of frequent international moves on relationships and family", "Making fast decisions during a real crisis with incomplete information"],
        "favourite_part": "The moment during a crisis when a citizen she's helping reaches safety.",
        "biggest_misconceptions": ["That diplomacy is mostly formal receptions, not real, high-stakes casework", "That failing the entrance exam once or twice disqualifies you permanently"],
        "what_surprised_them": "How much of real diplomatic work is quiet, unglamorous casework, not high-level negotiation.",
        "biggest_mistake": "During my first posting, I underestimated how isolating a new country could be and didn't build a support network early enough, which led to a difficult period of loneliness that affected my work.",
        "one_regret": "I regret the year I spent after my second exam failure convinced I'd never pass — that self-doubt nearly made me give up a career I now love.",
        "salary_reality": "Foreign service salaries in Romania are stable but modest relative to private-sector international careers — people choose this path for the mission and experience more than the pay.",
        "work_life_balance": "Genuinely difficult around postings and crises, though calmer during standard rotations.",
        "daily_skills": ["cross-cultural communication", "crisis management", "diplomatic writing"],
        "daily_tools": ["Secure diplomatic communication systems", "Multiple language fluency"],
        "recommended_books": ["The Craft of Diplomacy by Chas Freeman"],
        "recommended_communities": ["Romanian diplomatic alumni network"],
        "advice_for_beginners": "If you fail a competitive exam once, or even twice, that doesn't mean the path isn't for you — it means you need a different preparation strategy, which is exactly what changed things for me.",
        "advice_for_parents": "Two exam failures felt devastating to watch as a parent might imagine, but persistence through them is what actually built her career — please don't let early setbacks decide the outcome for your child.",
        "faqs": [{"question": "How many times can you retake the foreign service exam?", "answer": "This varies by country, but many services allow multiple attempts — mine allowed unlimited retakes, and my third attempt succeeded."}],
        "projects": [], "research": [], "certifications": [],
        "conferences": [], "organizations": ["Romanian diplomatic alumni association"],
        "volunteer_work": ["Coaches exam candidates preparing for the foreign service entrance process"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_ngo_director_fatima_hassan",
        "name": "Fatima Hassan, NGO Program Director",
        "role_type": "industry_professional", "field": "international development", "bio": "Directs education programs for an international NGO across East Africa; started as an unpaid volunteer teacher in a refugee camp.",
        "trait_tags": ["empathy", "leadership"], "learning_style_fit": "Students motivated by mission over money, but who want an honest look at NGO sector realities.",
        "organization": "An international education-focused NGO", "years_experience": 12, "journey_highlights": ["Started as an unpaid volunteer teacher in a refugee camp", "Scaled an education program from one camp to twelve"],
        "discussion_topics": ["NGO sector career realities", "Volunteering vs. paid development work", "Program scaling and funding challenges"],
        "profession": "NGO Program Director", "specialization": "Refugee and crisis-affected education programs", "country": "Kenya", "city": "Nairobi",
        "industries": ["non_profit", "international development"], "education": ["BA Education, Kenyatta University", "MSc International Development, University of Edinburgh"],
        "current_role": "Regional Program Director, Education in Emergencies", "languages": ["English", "Swahili", "Somali"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who want to work in international development but worry about job stability", "Students considering starting with unpaid volunteer work", "Students interested in education access for displaced communities"],
        "career_ids": ["ngo_program_manager", "public_health_policy_analyst"],
        "career_journey": [
            {"stage": "university", "label": "BA Education", "description": "Initially planned to become a classroom teacher domestically.", "year_label": "2005-2009"},
            {"stage": "first_job", "label": "Unpaid volunteer teacher in a refugee camp", "description": "Took the unpaid role against her family's advice, living on savings for nearly a year.", "year_label": "2010"},
            {"stage": "career_transition", "label": "Hired as a paid program officer by the NGO she'd volunteered for", "description": "Her volunteer work directly led to a paid role once the organization saw her impact.", "year_label": "2011"},
            {"stage": "university", "label": "MSc International Development", "description": "Pursued further study while continuing to work part-time in the field.", "year_label": "2013-2014"},
            {"stage": "promotion", "label": "Promoted through several program roles", "description": "Helped scale the education program from a single camp to twelve locations.", "year_label": "2015-2020"},
            {"stage": "current_role", "label": "Regional Program Director, Education in Emergencies", "description": "Oversees education programming across multiple countries in the region.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "A mix of program strategy meetings, donor reporting, and field visits to schools operating in genuinely difficult conditions.",
        "weekly_routine": "Office-based strategy and funding work most weeks, with regular field travel to program sites.",
        "biggest_challenges": ["Chronic underfunding forcing hard choices about which communities get served", "The emotional toll of working closely with crisis-affected children and families"],
        "favourite_part": "Visiting a school years after it started and seeing children who are now old enough to become teachers themselves.",
        "biggest_misconceptions": ["That NGO work doesn't pay a livable wage at any level — it can, especially in senior roles, though entry points are often unpaid or low-paid", "That development work is simple charity rather than complex, evidence-based program design"],
        "what_surprised_them": "How much of the job is actually about budgeting and logistics, not the direct teaching work she originally expected.",
        "biggest_mistake": "Early in scaling the program, I approved an expansion into a new camp without adequately assessing local security conditions, and we had to suspend operations there for months after a serious safety incident. It taught me to never let funding pressure override a proper risk assessment again.",
        "one_regret": "I don't regret the unpaid year, but I regret not being honest with my family about how financially difficult it was — I hid it out of pride, and it strained our relationship for a while.",
        "salary_reality": "Entry-level NGO work is often unpaid or very low-paid, which genuinely limits who can afford to start in this field — this is a real structural issue in the sector worth knowing before committing.",
        "work_life_balance": "Field visits can be intense and require real time away from family, though headquarters-based weeks are more predictable.",
        "daily_skills": ["program management", "donor reporting", "cross-cultural communication", "budgeting"],
        "daily_tools": ["Monitoring and evaluation frameworks", "Grant management software"],
        "recommended_books": ["The Blue Sweater by Jacqueline Novogratz"],
        "recommended_communities": ["East Africa education-in-emergencies network"],
        "advice_for_beginners": "If you can find a way to afford it, real field experience — even unpaid — opens doors in this sector that a degree alone doesn't.",
        "advice_for_parents": "The unpaid entry period into NGO work is a real financial strain, and it's fair to want to understand your child's plan for it — but please don't assume it means the career itself is unstable long-term.",
        "faqs": [{"question": "Can you make a real living in the NGO sector?", "answer": "Yes, especially at program management and director levels, though it usually takes years of sometimes low-paid entry work to get there."}],
        "projects": ["Scaled an education program from one refugee camp to twelve"], "research": [],
        "certifications": [], "conferences": ["Global Education Summit"], "organizations": [],
        "volunteer_work": ["Mentors young women considering international development careers"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_policy_analyst_james_whitfield",
        "name": "James Whitfield, Public Policy Analyst",
        "role_type": "industry_professional", "field": "public policy", "bio": "Analyzes housing policy for a national government department; switched from a corporate law path after a formative volunteering experience.",
        "trait_tags": ["analytical_thinking", "communication"], "learning_style_fit": "Students who like research and writing more than courtroom-style advocacy.",
        "organization": "A national government policy department", "years_experience": 8, "journey_highlights": ["Left a corporate law training contract after six months", "Co-authored housing policy now adopted in two regions"],
        "discussion_topics": ["Leaving a 'safe' career path for policy work", "What government policy work actually involves", "Policy vs. law as career paths"],
        "profession": "Senior Policy Analyst", "specialization": "Housing and urban policy", "country": "United Kingdom", "city": "London",
        "industries": ["government", "public policy"], "education": ["BA Politics, Philosophy and Economics, University of Oxford", "MPP Public Policy, University College London"],
        "current_role": "Senior Policy Analyst, Housing Directorate", "languages": ["English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students weighing law against public policy careers", "Students who like research-heavy work over courtroom advocacy", "Students interested in housing or urban policy specifically"],
        "career_ids": ["urban_planner", "uk_civil_service_fast_streamer"],
        "career_journey": [
            {"stage": "university", "label": "BA Politics, Philosophy and Economics", "description": "Assumed law was the natural next step after his degree, as most of his peers did.", "year_label": "2010-2013"},
            {"stage": "internship", "label": "Corporate law training contract", "description": "Secured a competitive training contract at a prestigious law firm.", "year_label": "2013-2014"},
            {"stage": "failure", "label": "Left the training contract after six months", "description": "Realized the work felt disconnected from any issue he actually cared about, despite the prestige and pay.", "year_label": "2014"},
            {"stage": "career_transition", "label": "Volunteered with a housing charity while deciding his next step", "description": "This unpaid experience is what pointed him toward policy work.", "year_label": "2014-2015"},
            {"stage": "university", "label": "MPP Public Policy", "description": "Pursued a master's specifically to move into government policy work.", "year_label": "2015-2016"},
            {"stage": "current_role", "label": "Senior Policy Analyst, Housing Directorate", "description": "Co-authored a housing policy reform now adopted in two regions.", "year_label": "2017-present"},
        ],
        "day_in_the_life": "Research and writing dominate most days — reading evidence, drafting briefs, and revising policy recommendations based on ministerial feedback.",
        "weekly_routine": "Structured research blocks with periodic stakeholder consultation meetings.",
        "biggest_challenges": ["Watching well-researched recommendations get diluted by political considerations", "The slow pace of real policy change compared to the urgency of the problems it addresses"],
        "favourite_part": "Seeing a policy he helped write actually implemented and improving something concrete, like housing availability.",
        "biggest_misconceptions": ["That policy work requires a law degree — mine is in politics, not law", "That leaving a prestigious training contract is career suicide"],
        "what_surprised_them": "How much policy work is really persuasive writing, not abstract theorizing.",
        "biggest_mistake": "In an early policy brief, I relied on outdated housing data without properly verifying it was still current, and a minister used the flawed figure in a public statement that later had to be corrected. It was a humbling lesson in triple-checking every number that leaves my desk.",
        "one_regret": "I regret not leaving the law training contract sooner — I stayed six months out of fear of 'wasting' the opportunity, when I already knew within the first few weeks it wasn't right for me.",
        "salary_reality": "Public policy salaries in the UK civil service are steady and reasonable, but meaningfully below what the same law degree could have earned in corporate law — I chose the tradeoff deliberately.",
        "work_life_balance": "Generally good, standard government hours with occasional crunches before major policy announcements.",
        "daily_skills": ["policy research", "persuasive writing", "stakeholder consultation"],
        "daily_tools": ["Statistical analysis software", "Government briefing templates"],
        "recommended_books": ["The Blunders of Our Governments by Anthony King and Ivor Crewe"],
        "recommended_communities": ["Institute for Government policy network"],
        "advice_for_beginners": "Don't assume the most prestigious first job is automatically the right one — leaving my law training contract felt like a failure at the time and turned out to be the best decision of my career.",
        "advice_for_parents": "Leaving a prestigious training contract isn't the same as giving up on ambition — for my son, it was the decision that led to work he actually finds meaningful.",
        "faqs": [{"question": "Do you need a law degree for policy work?", "answer": "No — mine is in politics, philosophy and economics. A public policy master's degree is a more direct route into government policy roles."}],
        "projects": ["Co-authored housing policy reform adopted in two regions"], "research": ["Published policy briefs on affordable housing supply"],
        "certifications": [], "conferences": [], "organizations": ["Institute for Government"],
        "volunteer_work": ["Still volunteers with the housing charity that first inspired his career change"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_accountant_beatriz_lopez",
        "name": "Beatriz López, Corporate Finance Accountant",
        "role_type": "industry_professional", "field": "accounting", "bio": "Leads financial reporting for a manufacturing company; failed her professional accounting exams twice before qualifying.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who want a realistic picture of professional accounting exams and career progression.",
        "organization": "A regional manufacturing company", "years_experience": 10, "journey_highlights": ["Failed professional accounting exams twice", "Now leads financial reporting for a company with regional operations"],
        "discussion_topics": ["Failing professional exams and requalifying", "Accounting career paths beyond auditing", "Balancing exams with a full-time job"],
        "profession": "Financial Controller", "specialization": "Corporate financial reporting", "country": "Mexico", "city": "Monterrey",
        "industries": ["finance", "manufacturing"], "education": ["BA Accounting, Tecnológico de Monterrey", "Professional accounting qualification (requalified)"],
        "current_role": "Financial Controller", "languages": ["Spanish", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who failed or are worried about failing professional exams", "Students balancing full-time work with further qualification", "Students who think accounting is only about audit"],
        "career_ids": ["accountant"],
        "career_journey": [
            {"stage": "university", "label": "BA Accounting", "description": "A solid but not exceptional student, expecting the professional exams to be straightforward.", "year_label": "2008-2012"},
            {"stage": "first_job", "label": "Junior accountant while studying for professional qualification", "description": "Balanced full-time work with intense exam preparation.", "year_label": "2012-2014"},
            {"stage": "failure", "label": "Failed a core professional exam paper twice", "description": "The stress of balancing a demanding job with repeated exam failure nearly led her to abandon the qualification entirely.", "year_label": "2013-2014"},
            {"stage": "turning_point", "label": "Restructured her study schedule with a study group and passed", "description": "Found that studying in isolation had been part of the problem — a peer study group made the material click.", "year_label": "2015"},
            {"stage": "promotion", "label": "Progressed through senior accountant to controller roles", "description": "Moved from a services firm into corporate finance at a manufacturing company.", "year_label": "2016-2020"},
            {"stage": "current_role", "label": "Financial Controller", "description": "Leads financial reporting and compliance for a company with operations across three Mexican states.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Month-end periods are intense reconciliation and reporting work; other weeks are more balanced between analysis and cross-departmental meetings.",
        "weekly_routine": "Relatively steady most of the month, with a demanding close-out period around month-end and especially year-end.",
        "biggest_challenges": ["The intensity of year-end close periods, which regularly mean 60-hour weeks for a stretch", "Explaining financial constraints to department heads who want more budget than exists"],
        "favourite_part": "The satisfaction of a clean, accurate financial close after a genuinely difficult quarter.",
        "biggest_misconceptions": ["That accounting is just data entry — it's increasingly about analysis and strategic advice", "That failing a professional exam means you're not cut out for the field"],
        "what_surprised_them": "How much real communication and cross-departmental negotiation the job demands, beyond the numbers.",
        "biggest_mistake": "During a busy month-end close early in my career, I rushed a reconciliation and missed a significant currency conversion error that overstated a subsidiary's results. It was caught during audit, but fixing it after the fact was far more painful than catching it would have been.",
        "one_regret": "I regret how alone I felt during my exam failures — a study group would have helped much sooner if I'd been willing to admit I was struggling.",
        "salary_reality": "Accounting salaries in Mexico's manufacturing sector are solid at the controller level, though early-career pay while studying for qualifications is modest.",
        "work_life_balance": "Reasonable most of the year, genuinely difficult during month-end and year-end close periods.",
        "daily_skills": ["financial reporting", "reconciliation", "regulatory compliance", "Excel modeling"],
        "daily_tools": ["SAP", "Excel", "Financial reporting software"],
        "recommended_books": ["Financial Intelligence by Karen Berman and Joe Knight"],
        "recommended_communities": ["Local professional accountants' association"],
        "advice_for_beginners": "If you fail a professional exam, change how you're studying before you assume you're not capable — a study group is what finally worked for me after solo studying failed twice.",
        "advice_for_parents": "A failed professional exam is common and recoverable — please don't treat it as a sign your child chose the wrong career.",
        "faqs": [{"question": "Is it common to fail professional accounting exams?", "answer": "Yes, pass rates on core papers are often well below 50% — failing once or twice is genuinely common, not a sign you shouldn't continue."}],
        "projects": [], "research": [], "certifications": ["Professional accounting qualification"],
        "conferences": [], "organizations": ["Regional professional accountants' association"],
        "volunteer_work": ["Runs a free study group for candidates preparing for professional accounting exams"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (business_and_government batch).")


if __name__ == "__main__":
    asyncio.run(seed())
