"""Connect Batch 1 — Expert Connect seed data, twelfth wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch12
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_patent_attorney_soo_jin_park",
        "name": "Soo-jin Park, Patent Attorney",
        "role_type": "industry_professional", "field": "intellectual property law", "bio": "Prosecutes technology patents for a law firm; missed a critical filing deadline early in her career that cost a client valuable patent rights in one country.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who like combining technical/scientific understanding with detailed legal work.",
        "organization": "An intellectual property law firm", "years_experience": 10, "journey_highlights": ["Missed a critical international filing deadline early in her career", "Now leads patent strategy for the firm's technology clients"],
        "discussion_topics": ["Recovering from a costly deadline error", "Patent law as a career combining science and law", "What patent attorneys actually do"],
        "profession": "Patent Attorney", "specialization": "Technology and software patents", "country": "South Korea", "city": "Seoul",
        "industries": ["law", "technology"], "education": ["BSc Electrical Engineering, Seoul National University", "JD, Korea University"],
        "current_role": "Senior Patent Attorney", "languages": ["Korean", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students with a technical/engineering background considering law", "Students who've missed a critical deadline with real consequences", "Students interested in intellectual property law specifically"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BSc Electrical Engineering, then JD", "description": "Combined her engineering background with legal training specifically for patent work.", "year_label": "2007-2014"},
            {"stage": "first_job", "label": "Junior patent attorney", "description": "Managed a growing caseload of international patent filings.", "year_label": "2014-2017"},
            {"stage": "failure", "label": "Missed a critical international filing deadline for a client's patent application", "description": "The error, caused by a scheduling oversight in a complex multi-country filing, cost the client patent rights in one specific country.", "year_label": "2017"},
            {"stage": "turning_point", "label": "Built an obsessively redundant deadline-tracking system with multiple independent checks", "description": "Never missed another critical deadline in the years since.", "year_label": "2018"},
            {"stage": "current_role", "label": "Senior Patent Attorney", "description": "Now leads patent strategy for the firm's major technology clients.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Reviewing technical inventions, drafting patent applications, and managing complex international filing deadlines.",
        "weekly_routine": "Steady drafting and review work, with periodic intense periods around major filing deadlines.",
        "biggest_challenges": ["The unforgiving nature of legal deadlines with no flexibility for error", "Translating deeply technical inventions into precise legal language"],
        "favourite_part": "Successfully securing a patent that genuinely protects a client's breakthrough innovation.",
        "biggest_misconceptions": ["That patent law is only accessible to people with a legal background, not a technical one", "That a missed deadline permanently damages a patent attorney's career"],
        "what_surprised_them": "How much the job depends on precise administrative systems, not just legal or technical knowledge.",
        "biggest_mistake": "I tracked a complex multi-country filing deadline using a single calendar reminder system that failed to account for a time zone discrepancy, causing us to miss the actual deadline in one jurisdiction. It cost the client real patent rights, and I now use a redundant, multiply-verified deadline tracking system for every filing.",
        "one_regret": "I regret trusting a single-point tracking system for something with such serious, irreversible consequences — redundancy should have been standard from day one.",
        "salary_reality": "Patent law in South Korea's technology sector pays very well, reflecting the combined technical and legal expertise required.",
        "work_life_balance": "Generally steady, with periodic intensity around major filing deadlines.",
        "daily_skills": ["patent drafting", "technical analysis", "deadline management"],
        "daily_tools": ["Patent filing databases", "technical drawing software"],
        "recommended_books": ["Patent It Yourself by David Pressman"],
        "recommended_communities": ["Korean Patent Attorneys Association"],
        "advice_for_beginners": "Build redundant systems for tracking critical deadlines from your very first case — my one missed deadline came from trusting a single point of failure.",
        "advice_for_parents": "A technical or engineering background is a genuine asset for a legal career in patent law, not a detour from it.",
        "faqs": [{"question": "Do you need a science or engineering degree to become a patent attorney?", "answer": "It's often required or strongly preferred for technical patent prosecution work, since you need to deeply understand the inventions you're protecting."}],
        "projects": [], "research": [], "certifications": ["Licensed Patent Attorney, South Korea"],
        "conferences": [], "organizations": ["Korean Patent Attorneys Association"],
        "volunteer_work": ["Mentors engineering students considering intellectual property law"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_esports_coach_viktor_petrov",
        "name": "Viktor Petrov, Esports Coach",
        "role_type": "industry_professional", "field": "esports", "bio": "Coaches a professional esports team; his own competitive gaming career ended after a public tournament collapse that went viral for the wrong reasons.",
        "trait_tags": ["leadership", "analytical_thinking"], "learning_style_fit": "Students passionate about gaming who want to know esports careers are real, structured, and professional.",
        "organization": "A professional esports organization", "years_experience": 7, "journey_highlights": ["His competitive career ended after a public tournament collapse", "Coached a team from a low ranking to a regional championship title"],
        "discussion_topics": ["Recovering from a public competitive failure", "Esports coaching as a legitimate career", "Transitioning from player to coach"],
        "profession": "Head Esports Coach", "specialization": "Competitive team strategy and player development", "country": "Bulgaria", "city": "Sofia",
        "industries": ["esports", "entertainment"], "education": ["Self-taught, transitioned from competitive play"],
        "current_role": "Head Coach, Professional Esports Team", "languages": ["Bulgarian", "English", "Russian"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students passionate about gaming who want to know esports careers are real and structured", "Students whose competitive career ended publicly and painfully", "Students interested in coaching rather than competing themselves"],
        "career_ids": [],
        "career_journey": [
            {"stage": "first_job", "label": "Competitive professional gamer", "description": "Competed at a high level in a major esports title for several years.", "year_label": "2015-2018"},
            {"stage": "failure", "label": "Collapsed under pressure during a major tournament final, a moment that went viral publicly", "description": "The public mockery that followed was intense, and it effectively ended his competitive playing career.", "year_label": "2018"},
            {"stage": "career_transition", "label": "Moved into coaching after a difficult period away from the game entirely", "description": "Initially doubted whether he could return to esports in any capacity after such a public failure.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Coached a struggling team to a regional championship title", "description": "The win validated his transition and established his coaching credibility independent of his playing history.", "year_label": "2021"},
            {"stage": "current_role", "label": "Head Coach, Professional Esports Team", "description": "Leads strategy and player development for a competitive professional team.", "year_label": "2022-present"},
        ],
        "day_in_the_life": "A mix of gameplay strategy analysis, individual player coaching sessions, and team practice oversight.",
        "weekly_routine": "Structured practice schedules building toward tournament competition periods.",
        "biggest_challenges": ["Managing player psychology and pressure, drawing directly on his own painful experience", "The public, sometimes brutal nature of esports fan criticism"],
        "favourite_part": "Watching a player he's coached handle high-pressure moments with the composure he once lacked himself.",
        "biggest_misconceptions": ["That esports coaching isn't a 'real' career", "That a public competitive collapse should permanently define someone's future in the field"],
        "what_surprised_them": "How much of coaching is sports psychology, directly informed by his own painful competitive experience.",
        "biggest_mistake": "During my own collapse, I hadn't developed any real strategies for managing pressure in the moment, having relied purely on raw skill throughout my competitive career. That gap is exactly what I now prioritize teaching every player I coach, before it becomes a problem in a real tournament.",
        "one_regret": "I regret how long I stayed away from esports entirely after that public failure — I could have started coaching sooner if I hadn't assumed the door was permanently closed.",
        "salary_reality": "Esports coaching salaries in Bulgaria are still developing as the industry matures, though top-tier team salaries internationally have grown substantially in recent years.",
        "work_life_balance": "Demanding around tournament periods, with practice schedules that can extend into evenings.",
        "daily_skills": ["strategic game analysis", "player psychology coaching", "team management"],
        "daily_tools": ["Game replay analysis software", "performance tracking tools"],
        "recommended_books": ["The Inner Game of Tennis by Timothy Gallwey"],
        "recommended_communities": ["European esports coaching network"],
        "advice_for_beginners": "Develop real pressure-management strategies before you need them in a high-stakes moment — my public collapse happened because I'd never built this skill.",
        "advice_for_parents": "Esports is a genuine, growing professional industry with real coaching and management careers beyond just playing, and a public setback in competition is recoverable, as it was for him.",
        "faqs": [{"question": "Is esports coaching a legitimate full-time career?", "answer": "Increasingly yes — professional esports organizations now employ dedicated coaches, analysts, and support staff much like traditional sports."}],
        "projects": ["Coached a team from a low ranking to a regional championship title"], "research": [], "certifications": [],
        "conferences": [], "organizations": [], "volunteer_work": ["Speaks to young competitive gamers about handling public pressure and failure"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_university_professor_helena_kovac",
        "name": "Dr. Helena Kovač, University Professor",
        "role_type": "professor", "field": "economics", "bio": "Teaches and researches development economics at a public university; was denied tenure at her first academic position before succeeding at a second institution.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students interested in academia who want honesty about its competitive, uncertain career track.",
        "organization": "A public university", "years_experience": 15, "journey_highlights": ["Was denied tenure at her first academic institution", "Now leads a research center studying regional economic development"],
        "discussion_topics": ["Being denied tenure and rebuilding an academic career", "Academia as a genuinely competitive career path", "Economics research beyond finance"],
        "profession": "Professor of Economics", "specialization": "Development economics", "country": "Croatia", "city": "Zagreb",
        "industries": ["education", "research"], "education": ["BA Economics, University of Zagreb", "PhD Economics, London School of Economics"],
        "current_role": "Full Professor of Economics", "languages": ["Croatian", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students considering academia who want honesty about its competitiveness", "Students who've faced a major professional rejection like being denied tenure", "Students interested in economics beyond finance and banking"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Economics, then PhD Economics", "description": "Developed a research interest in development economics during her doctoral studies.", "year_label": "2001-2010"},
            {"stage": "first_job", "label": "Assistant professor at her first academic institution", "description": "Built a research and teaching record over a demanding six-year tenure track.", "year_label": "2010-2016"},
            {"stage": "failure", "label": "Was denied tenure at her first institution", "description": "The rejection meant losing her position entirely and having to rebuild her academic career elsewhere, a genuinely devastating professional setback.", "year_label": "2016"},
            {"stage": "career_transition", "label": "Secured a position at a second university and rebuilt her research program", "description": "Used the rejection as motivation to more strategically align her research with the department's priorities.", "year_label": "2017"},
            {"stage": "current_role", "label": "Full Professor of Economics", "description": "Now leads a research center studying regional economic development.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of teaching, research, grant writing, and advising graduate students.",
        "weekly_routine": "Teaching during term time, with research and writing woven throughout, intensifying during academic breaks.",
        "biggest_challenges": ["The genuinely uncertain, competitive nature of academic career progression", "Balancing teaching responsibilities against research output pressure"],
        "favourite_part": "A graduate student's research finding something genuinely new that changes how a real economic problem is understood.",
        "biggest_misconceptions": ["That academic careers are stable once you have a PhD", "That being denied tenure reflects a lack of real academic ability rather than institutional fit and priorities"],
        "what_surprised_them": "How much academic success depends on institutional fit and priorities, not purely on research quality.",
        "biggest_mistake": "At my first institution, I focused my research too narrowly on my own specific interests without adequately aligning with the department's stated priorities for tenure evaluation, not fully understanding how much that alignment would matter. I learned to research what I care about while also being strategic about institutional fit.",
        "one_regret": "I regret not seeking more honest, direct feedback about my tenure prospects earlier in that first position — I might have adjusted my approach or sought a better-fitting institution sooner.",
        "salary_reality": "Full professor salaries in Croatia's public university system are reasonable but modest compared to private sector economics roles — most academics choose this path for the research and teaching mission.",
        "work_life_balance": "Generally flexible in structure, though genuinely demanding total hours between teaching, research, and administrative responsibilities.",
        "daily_skills": ["economic research methodology", "teaching", "grant writing"],
        "daily_tools": ["Statistical analysis software", "academic research databases"],
        "recommended_books": ["Poor Economics by Banerjee and Duflo"],
        "recommended_communities": ["European Economic Association"],
        "advice_for_beginners": "Understand your institution's specific priorities early in an academic career, not just your own research interests — my tenure denial came partly from not doing this.",
        "advice_for_parents": "Being denied tenure is a genuinely common, career-altering setback in academia, not a reflection of your child's actual research ability — many respected professors have faced it.",
        "faqs": [{"question": "How common is it to be denied tenure?", "answer": "More common than people outside academia realize — tenure rates vary significantly by institution and field, and a denial doesn't end an academic career, though it does require rebuilding elsewhere."}],
        "projects": [], "research": ["Leads a research center studying regional economic development"], "certifications": [],
        "conferences": ["European Economic Association annual congress"], "organizations": ["European Economic Association"],
        "volunteer_work": ["Advises graduate students navigating the academic job market"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_orthodontist_rania_saad",
        "name": "Dr. Rania Saad, Orthodontist",
        "role_type": "industry_professional", "field": "dentistry", "bio": "Runs an orthodontic practice specializing in adolescent and adult treatment; a treatment planning error early in her career prolonged a patient's treatment by nearly a year.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who like precise, long-term treatment planning work with visible results.",
        "organization": "A private orthodontic practice", "years_experience": 11, "journey_highlights": ["A treatment planning error prolonged a patient's care by nearly a year", "Now runs a practice known for complex case management"],
        "discussion_topics": ["A treatment error that taught her thoroughness", "Orthodontics as a specialized dental career requiring additional years of training", "Long-term patient relationship building"],
        "profession": "Orthodontist", "specialization": "Adolescent and adult orthodontic treatment", "country": "Lebanon", "city": "Beirut",
        "industries": ["healthcare"], "education": ["DDS, American University of Beirut", "Orthodontic specialty residency"],
        "current_role": "Owner and Lead Orthodontist", "languages": ["Arabic", "English", "French"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in dentistry specialization specifically", "Students who've made a planning error with real prolonged consequences", "Students who like long-term treatment relationships with patients"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "university", "label": "DDS, then orthodontic specialty residency", "description": "Pursued additional years of specialized training beyond general dentistry.", "year_label": "2005-2013"},
            {"stage": "first_job", "label": "Associate orthodontist", "description": "Began independently managing full treatment plans for patients.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Made a treatment planning error on a complex case that prolonged the patient's treatment by nearly a year", "description": "Underestimated a specific tooth movement challenge during initial planning, requiring a significant mid-treatment correction.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Adopted much more rigorous initial diagnostic imaging and planning review for complex cases", "description": "Began routinely consulting with colleagues on unusually complex treatment plans before starting them.", "year_label": "2017"},
            {"stage": "current_role", "label": "Owner and Lead Orthodontist", "description": "Now runs a practice specifically known for managing complex orthodontic cases well.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Patient appointments involving treatment adjustments, progress monitoring, and new patient consultations.",
        "weekly_routine": "Steady clinical schedule with recurring patient visits spaced over months of ongoing treatment.",
        "biggest_challenges": ["Accurately predicting how complex cases will respond to treatment over long timeframes", "Managing patient and parent expectations about treatment duration"],
        "favourite_part": "A patient's final reveal moment after years of treatment, seeing their new smile and confidence.",
        "biggest_misconceptions": ["That orthodontics is simple compared to general dentistry", "That a prolonged treatment timeline always reflects poor initial planning"],
        "what_surprised_them": "How much long-term biological unpredictability orthodontic treatment involves, even with careful planning.",
        "biggest_mistake": "I underestimated the difficulty of a specific tooth movement in a complex case's initial treatment plan, not seeking a colleague's second opinion despite the case's genuine complexity. The resulting correction added nearly a year to the patient's treatment, and I now always seek peer consultation on unusually complex cases before finalizing a plan.",
        "one_regret": "I regret not consulting a colleague on that case's plan from the start — my confidence in handling it alone cost the patient real additional time in treatment.",
        "salary_reality": "Orthodontics is one of the more financially rewarding dental specialties in Lebanon, reflecting the additional years of specialized training required.",
        "work_life_balance": "Generally predictable clinical hours, without emergency demands typical of general medicine.",
        "daily_skills": ["treatment planning", "diagnostic imaging analysis", "patient communication"],
        "daily_tools": ["Orthodontic imaging and planning software", "treatment tracking systems"],
        "recommended_books": ["Contemporary Orthodontics by William Proffit"],
        "recommended_communities": ["Lebanese Orthodontic Society"],
        "advice_for_beginners": "Seek a colleague's second opinion on genuinely complex treatment plans before starting — my solo confidence on one case cost a patient a year of extra treatment time.",
        "advice_for_parents": "Orthodontics requires years of additional specialized training beyond general dentistry — it's a genuinely rigorous specialty, not a simpler alternative career path.",
        "faqs": [{"question": "How is orthodontics different from general dentistry?", "answer": "Orthodontists complete additional years of specialized residency training focused specifically on tooth and jaw alignment, beyond a general dentistry degree."}],
        "projects": [], "research": [], "certifications": ["Licensed Orthodontist, Lebanon"],
        "conferences": [], "organizations": ["Lebanese Orthodontic Society"],
        "volunteer_work": ["Provides discounted orthodontic care for families facing financial hardship"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch12).")


if __name__ == "__main__":
    asyncio.run(seed())
