"""Connect Batch 1 — Expert Connect seed data, second wave adding more
specializations within already-covered domains (real-world careers have
far more variety than one expert per domain suggests). See
seed_experts_tech_and_science.py for the full module-level convention
notes — Content Quality Bar applies to every field here too.

Run via: python -m aureon.scripts.seed_experts_batch2
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_mobile_dev_sara_haddad",
        "name": "Sara Haddad, Mobile App Developer",
        "role_type": "industry_professional", "field": "software engineering", "bio": "Builds iOS apps for a health-tracking startup; her first published app was rejected by the App Store five times before approval.",
        "trait_tags": ["persistence", "creativity"], "learning_style_fit": "Students who like precise, detail-oriented work with immediate visual feedback.",
        "organization": "A health-tracking startup", "years_experience": 6, "journey_highlights": ["Had an app rejected by Apple's review process five times", "Her app now has over 500,000 downloads"],
        "discussion_topics": ["Getting an app through App Store review", "iOS vs Android development", "Building a first app from scratch"],
        "profession": "iOS Developer", "specialization": "Health and fitness mobile apps", "country": "Jordan", "city": "Amman",
        "industries": ["technology"], "education": ["BSc Computer Engineering, Jordan University of Science and Technology"],
        "current_role": "Senior iOS Developer", "languages": ["Arabic", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who want to build mobile apps specifically, not general software", "Students frustrated by repeated app store rejections", "Students who like design and code together"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BSc Computer Engineering", "description": "Built her first simple app as a graduation project.", "year_label": "2013-2017"},
            {"stage": "first_job", "label": "Junior Android developer", "description": "Started on Android before specializing in iOS later.", "year_label": "2017-2019"},
            {"stage": "failure", "label": "Had a personal app rejected by Apple five separate times", "description": "Each rejection cited a different guideline issue, forcing repeated redesigns over four frustrating months.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Finally got the app approved and it grew organically", "description": "The app now has over 500,000 downloads and led directly to her current job offer.", "year_label": "2020"},
            {"stage": "current_role", "label": "Senior iOS Developer", "description": "Leads iOS development for a growing health-tracking app.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Coding new features in the morning, testing and debugging on real devices in the afternoon.",
        "weekly_routine": "Sprint-based development cycles with a release roughly every two weeks.",
        "biggest_challenges": ["Apple's strict and sometimes opaque review guidelines", "Supporting many different device sizes and iOS versions at once"],
        "favourite_part": "Seeing real user reviews describing how the app changed a daily habit.",
        "biggest_misconceptions": ["That app rejection means your app idea is bad", "That mobile development is easier than web development"],
        "what_surprised_them": "How much of mobile development is about platform-specific rules, not just writing good code.",
        "biggest_mistake": "On my third rejection, I got so frustrated I made changes without carefully reading Apple's actual feedback, which led to a fourth rejection for an unrelated new issue. I learned to read review feedback slowly and completely before making any change.",
        "one_regret": "I regret how discouraged I let those rejections make me feel — I nearly abandoned the app on the fourth rejection, right before the fix that finally worked.",
        "salary_reality": "Mobile development pays well in Jordan's growing tech sector, and remote work for international companies has opened up salaries well above the local market average.",
        "work_life_balance": "Generally reasonable, with predictable release cycles.",
        "daily_skills": ["Swift", "iOS SDK", "UI design implementation"],
        "daily_tools": ["Xcode", "TestFlight", "Figma"],
        "recommended_books": ["The Swift Programming Language (Apple's official guide)"],
        "recommended_communities": ["Amman iOS developers meetup"],
        "advice_for_beginners": "Read app store rejection feedback slowly and completely — rushing to fix it made my process slower, not faster.",
        "advice_for_parents": "Repeated app rejections are a normal part of publishing, not a sign the idea or the developer isn't good enough.",
        "faqs": [{"question": "Why do apps get rejected from app stores?", "answer": "Usually for specific guideline violations, not because the idea is bad — careful, complete reading of the feedback almost always reveals a fixable issue."}],
        "projects": ["Built a health app with over 500,000 downloads"], "research": [], "certifications": [],
        "conferences": [], "organizations": [], "volunteer_work": ["Teaches a free weekend iOS development course"],
        "portfolio_links": [{"label": "GitHub", "url": "https://github.com/example/sarahaddad"}], "social_links": [],
    },
    {
        "id": "expert_product_manager_owen_clarke",
        "name": "Owen Clarke, Product Manager",
        "role_type": "industry_professional", "field": "product management", "bio": "Leads product strategy for a B2B SaaS company; his first product launch was a commercial failure that got quietly shut down after six months.",
        "trait_tags": ["communication", "leadership"], "learning_style_fit": "Students who like connecting business strategy, design, and engineering rather than specializing in just one.",
        "organization": "A B2B SaaS company", "years_experience": 8, "journey_highlights": ["His first product launch was shut down after six months", "Led a feature that became the company's top revenue driver"],
        "discussion_topics": ["Surviving a failed product launch", "What product managers actually do", "Getting into PM without a technical background"],
        "profession": "Senior Product Manager", "specialization": "B2B SaaS product strategy", "country": "Australia", "city": "Melbourne",
        "industries": ["technology"], "education": ["BCom Business, University of Melbourne"],
        "current_role": "Senior Product Manager", "languages": ["English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who like both business and technology but aren't sure which side to specialize in", "Students who've had a project or product fail", "Students without an engineering background wondering if PM is open to them"],
        "career_ids": ["product_led_growth_specialist"],
        "career_journey": [
            {"stage": "university", "label": "BCom Business", "description": "Interned at a marketing agency, unsure yet what career direction to pursue.", "year_label": "2011-2014"},
            {"stage": "first_job", "label": "Associate product manager at a startup", "description": "Learned the role largely by trial and error, with little formal mentorship.", "year_label": "2015-2017"},
            {"stage": "failure", "label": "Led a product launch that was shut down after six months", "description": "The product had solved a problem customers didn't actually prioritize, despite months of development.", "year_label": "2017"},
            {"stage": "turning_point", "label": "Rebuilt his approach around customer research before building anything", "description": "Adopted much more rigorous validation before committing engineering resources to any idea.", "year_label": "2018"},
            {"stage": "current_role", "label": "Senior Product Manager", "description": "Led a feature that became the company's top revenue driver.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of customer interviews, roadmap planning, and coordinating between design and engineering teams.",
        "weekly_routine": "Customer research and stakeholder meetings early in the week, planning and prioritization later.",
        "biggest_challenges": ["Saying no to feature requests that don't align with real customer needs", "Aligning engineering, design, and sales around one product direction"],
        "favourite_part": "The moment customer usage data confirms a hypothesis he was nervous about being wrong on.",
        "biggest_misconceptions": ["That PMs need a technical/engineering background — mine is business", "That product management is just writing feature specs"],
        "what_surprised_them": "How much of the job is saying no, not saying yes to new ideas.",
        "biggest_mistake": "My failed product launch happened because I trusted my own intuition about what customers wanted instead of actually validating it with real customer conversations first. I built an entire product around an assumption nobody had confirmed.",
        "one_regret": "I regret not talking to more customers before committing engineering resources to that first product — a few conversations would have revealed the flaw months earlier.",
        "salary_reality": "Product management pays well in Australia's tech sector, generally on par with or slightly above senior engineering roles at the same company.",
        "work_life_balance": "Generally good, with periodic intensity around major launches.",
        "daily_skills": ["customer research", "roadmap prioritization", "cross-functional communication"],
        "daily_tools": ["Jira", "Amplitude", "Figma"],
        "recommended_books": ["Inspired by Marty Cagan"],
        "recommended_communities": ["Melbourne product management meetup"],
        "advice_for_beginners": "Talk to real customers before you build anything — my failed launch happened because I skipped this step entirely.",
        "advice_for_parents": "A business degree is a genuinely strong foundation for a tech product career — you don't need an engineering degree to lead technology products.",
        "faqs": [{"question": "Do product managers need to know how to code?", "answer": "It helps for communicating with engineers, but isn't required — my background is business, not engineering."}],
        "projects": ["Led a feature that became the company's top revenue driver"], "research": [], "certifications": [],
        "conferences": ["Mind the Product Melbourne"], "organizations": [],
        "volunteer_work": ["Mentors aspiring PMs transitioning from non-technical backgrounds"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_pharmacist_layla_ibrahim",
        "name": "Layla Ibrahim, Clinical Pharmacist",
        "role_type": "industry_professional", "field": "medicine", "bio": "Works as a clinical pharmacist in a hospital setting; failed a critical licensing exam once due to a scheduling mistake, not lack of knowledge.",
        "trait_tags": ["analytical_thinking", "communication"], "learning_style_fit": "Students who like the precision of pharmacology combined with direct patient interaction.",
        "organization": "A regional hospital", "years_experience": 9, "journey_highlights": ["Missed her first licensing exam attempt due to a scheduling error", "Now leads medication safety reviews for an entire hospital ward"],
        "discussion_topics": ["Pharmacy as a clinical, patient-facing career", "Recovering from a preventable administrative mistake", "Hospital vs. retail pharmacy paths"],
        "profession": "Clinical Pharmacist", "specialization": "Hospital medication safety", "country": "Egypt", "city": "Alexandria",
        "industries": ["healthcare"], "education": ["PharmD, Alexandria University"],
        "current_role": "Senior Clinical Pharmacist", "languages": ["Arabic", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like chemistry and biology but want a clinical, patient-facing career", "Students weighing hospital pharmacy against retail pharmacy", "Students who've made a costly administrative mistake"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "university", "label": "PharmD", "description": "Chose pharmacy specifically for its blend of chemistry and direct patient impact.", "year_label": "2010-2015"},
            {"stage": "failure", "label": "Missed her first licensing exam sitting due to a registration deadline error", "description": "A simple administrative mistake cost her six months of delay entering the workforce.", "year_label": "2015"},
            {"stage": "turning_point", "label": "Passed on her rescheduled attempt and built a rigorous personal organization system afterward", "description": "The experience taught her administrative discipline that later helped in medication safety work.", "year_label": "2016"},
            {"stage": "first_job", "label": "Retail pharmacist", "description": "Worked in community pharmacy before moving to a hospital setting.", "year_label": "2016-2018"},
            {"stage": "current_role", "label": "Senior Clinical Pharmacist", "description": "Leads medication safety reviews for an entire hospital ward, catching potentially dangerous drug interactions before they reach patients.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Reviewing physician medication orders for safety, consulting with nursing staff, and counseling patients on complex medication regimens.",
        "weekly_routine": "Ward rounds with the medical team several days a week, plus dedicated medication review time.",
        "biggest_challenges": ["Catching a dangerous drug interaction before it reaches a patient, under real time pressure", "Being taken seriously as a clinical voice among physicians"],
        "favourite_part": "Catching a genuinely dangerous prescribing error before it affects a patient.",
        "biggest_misconceptions": ["That pharmacists just count and dispense pills", "That hospital pharmacy is less patient-facing than being a doctor"],
        "what_surprised_them": "How much clinical judgment and physician collaboration the role actually involves.",
        "biggest_mistake": "I missed my first licensing exam sitting because I misread a registration deadline by two weeks — a purely administrative error that delayed my career start by six months and taught me to never assume I have more time than I do for anything important.",
        "one_regret": "I regret the panic and self-doubt that mistake caused — I worried it reflected badly on my competence, when it was really just a scheduling error anyone could make.",
        "salary_reality": "Hospital pharmacy pays solidly in Egypt relative to retail pharmacy, though the specialized training and often more demanding hours are real tradeoffs.",
        "work_life_balance": "Generally steady, with occasional demanding stretches during ward rounds or short-staffed periods.",
        "daily_skills": ["pharmacology", "medication safety review", "clinical collaboration"],
        "daily_tools": ["Hospital electronic prescribing systems", "drug interaction databases"],
        "recommended_books": ["Applied Therapeutics: The Clinical Use of Drugs"],
        "recommended_communities": ["Egyptian Pharmacists Syndicate"],
        "advice_for_beginners": "Double-check every deadline yourself instead of trusting memory — my six-month delay came from one missed date, not a lack of preparation.",
        "advice_for_parents": "Hospital pharmacy is a genuinely clinical, patient-facing career, not just a retail job behind a counter.",
        "faqs": [{"question": "Is hospital pharmacy different from working at a retail pharmacy?", "answer": "Significantly — hospital pharmacists work directly with medical teams on complex cases, rather than primarily dispensing prescriptions to walk-in patients."}],
        "projects": [], "research": [], "certifications": ["Licensed Pharmacist, Egypt"],
        "conferences": [], "organizations": ["Egyptian Pharmacists Syndicate"],
        "volunteer_work": ["Runs medication safety awareness sessions for nursing students"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_marketing_director_carla_pereira",
        "name": "Carla Pereira, Marketing Director",
        "role_type": "industry_professional", "field": "marketing", "bio": "Leads marketing for a consumer goods company; a major campaign she led early in her career was pulled after public backlash.",
        "trait_tags": ["creativity", "communication"], "learning_style_fit": "Students who like combining creative storytelling with measurable business results.",
        "organization": "A consumer goods company", "years_experience": 12, "journey_highlights": ["A campaign she led was pulled after significant public backlash", "Later led a campaign that won a regional advertising award"],
        "discussion_topics": ["Surviving a public campaign failure", "Marketing as a data-driven creative career", "Building a marketing career without an MBA"],
        "profession": "Marketing Director", "specialization": "Consumer brand campaigns", "country": "Portugal", "city": "Lisbon",
        "industries": ["marketing", "consumer goods"], "education": ["BA Communications, Universidade Nova de Lisboa"],
        "current_role": "Marketing Director", "languages": ["Portuguese", "English", "Spanish"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who like creative work but also want to see measurable business impact", "Students worried about a public professional failure", "Students without an MBA wondering if marketing leadership is accessible"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Communications", "description": "Interned at an advertising agency during her final year.", "year_label": "2007-2010"},
            {"stage": "first_job", "label": "Junior marketing associate", "description": "Worked on smaller campaigns while learning the fundamentals.", "year_label": "2010-2013"},
            {"stage": "failure", "label": "Led a major campaign that was pulled after public backlash over a tone-deaf message", "description": "The public criticism was intense and personally embarrassing, and she considered leaving marketing entirely.", "year_label": "2014"},
            {"stage": "turning_point", "label": "Rebuilt her approach with much more rigorous audience testing before launch", "description": "Never again launched a major campaign without extensive pre-testing with real target audiences.", "year_label": "2015"},
            {"stage": "current_role", "label": "Marketing Director", "description": "Led a later campaign that won a regional advertising award.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "A mix of creative review sessions, data analysis of campaign performance, and budget planning meetings.",
        "weekly_routine": "Creative development early in campaign cycles, heavy data analysis once campaigns are live.",
        "biggest_challenges": ["Balancing bold creative ideas against the real risk of public backlash", "Proving marketing's return on investment to finance-focused leadership"],
        "favourite_part": "Watching a campaign she believed in resonate exactly as intended with real audiences.",
        "biggest_misconceptions": ["That marketing is just 'making things look nice' — it's increasingly data-driven and accountable for business results", "That a public campaign failure ends a marketing career"],
        "what_surprised_them": "How much marketing leadership is really about risk management, not just creative vision.",
        "biggest_mistake": "The pulled campaign happened because we rushed testing to hit a launch deadline and skipped a crucial round of audience feedback that would have flagged the tone-deaf messaging. I now refuse to compromise on pre-launch testing, regardless of deadline pressure.",
        "one_regret": "I regret how personally I took the public backlash — I read every critical comment for weeks, which delayed my recovery far more than it needed to.",
        "salary_reality": "Marketing director roles pay well in Portugal's consumer goods sector, though the climb from junior roles took over a decade of steady progression.",
        "work_life_balance": "Reasonable most of the year, with real intensity during major campaign launches.",
        "daily_skills": ["campaign strategy", "brand storytelling", "marketing analytics"],
        "daily_tools": ["Google Analytics", "Adobe Creative Suite", "marketing automation platforms"],
        "recommended_books": ["Building a StoryBrand by Donald Miller"],
        "recommended_communities": ["Lisbon marketing professionals network"],
        "advice_for_beginners": "Never skip audience testing to hit a deadline — the campaign failure that taught me this cost far more than the testing time I tried to save.",
        "advice_for_parents": "A public professional failure, even one that generates real backlash, is survivable and often becomes a genuine turning point, not a career-ending event.",
        "faqs": [{"question": "Do you need an MBA to become a marketing director?", "answer": "Not necessarily — my path was a communications degree plus over a decade of progressively senior roles, not graduate business school."}],
        "projects": ["Led a campaign that won a regional advertising award"], "research": [], "certifications": [],
        "conferences": ["Cannes Lions (attendee, 2022)"], "organizations": [],
        "volunteer_work": ["Speaks at universities about recovering from public professional failure"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_psychiatrist_daniel_kim",
        "name": "Dr. Daniel Kim, Psychiatrist",
        "role_type": "industry_professional", "field": "medicine", "bio": "Practices adult psychiatry at a community mental health center; struggled with his own anxiety during residency, which shaped his clinical approach.",
        "trait_tags": ["empathy", "analytical_thinking"], "learning_style_fit": "Students interested in the intersection of biology and mental health, and how personal experience can inform clinical work.",
        "organization": "A community mental health center", "years_experience": 11, "journey_highlights": ["Struggled with significant anxiety during his own psychiatric residency", "Now runs a specialized anxiety disorders clinic"],
        "discussion_topics": ["Being a psychiatrist who has personally struggled with mental health", "Psychiatry vs. psychology career paths", "Combining medication management with therapy"],
        "profession": "Psychiatrist", "specialization": "Anxiety and mood disorders", "country": "South Korea", "city": "Seoul",
        "industries": ["healthcare"], "education": ["MD, Seoul National University", "Psychiatric residency, Seoul National University Hospital"],
        "current_role": "Attending Psychiatrist, Anxiety Disorders Clinic", "languages": ["Korean", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in psychiatry specifically, as distinct from psychology", "Students who've personally struggled with anxiety or mental health and wonder if that disqualifies them from the field", "Students weighing medical school specialties"],
        "career_ids": ["physician_general", "neuroscience_postdoc"],
        "career_journey": [
            {"stage": "university", "label": "MD", "description": "Chose psychiatry as a specialty after a formative rotation in his fourth year.", "year_label": "2007-2013"},
            {"stage": "first_job", "label": "Psychiatric residency", "description": "Developed significant personal anxiety during his second year, partly from the intensity of the work itself.", "year_label": "2014-2018"},
            {"stage": "failure", "label": "His anxiety became severe enough to require his own treatment", "description": "Feared that seeking treatment as a psychiatric trainee would be seen as weakness or professional risk.", "year_label": "2015"},
            {"stage": "turning_point", "label": "Sought treatment and found it directly shaped his clinical approach", "description": "His own experience with therapy and medication gave him a genuinely different, more empathetic clinical perspective.", "year_label": "2016"},
            {"stage": "current_role", "label": "Attending Psychiatrist, Anxiety Disorders Clinic", "description": "Runs a specialized clinic drawing partly on his own recovery experience.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Patient appointments combining medication management with brief therapeutic check-ins, plus care coordination with therapists.",
        "weekly_routine": "Full clinical days with patients, one afternoon reserved for case documentation and coordination with the broader care team.",
        "biggest_challenges": ["The stigma some patients and colleagues still attach to psychiatric treatment, including his own", "Balancing medication management against overreliance on medication alone"],
        "favourite_part": "A patient describing their first genuinely calm week in years.",
        "biggest_misconceptions": ["That psychiatrists just prescribe medication without real therapeutic engagement", "That a psychiatrist with their own mental health history is less credible, not more"],
        "what_surprised_them": "How much his own struggle with anxiety, once he stopped hiding it, actually deepened his patients' trust in him.",
        "biggest_mistake": "Early in my career, I hid my own anxiety treatment from colleagues out of fear of professional judgment, which meant I also couldn't discuss it usefully with patients navigating the same stigma. Being more open about it, once I felt safe to be, changed how effectively I could connect with patients.",
        "one_regret": "I regret staying silent about my own treatment for as long as I did — my silence reinforced the very stigma I now try to help patients overcome.",
        "salary_reality": "Psychiatry is one of the better-compensated medical specialties in South Korea, reflecting the years of additional training required after medical school.",
        "work_life_balance": "Generally more predictable than surgical specialties, though the emotional weight of the work requires real self-care.",
        "daily_skills": ["psychiatric assessment", "medication management", "therapeutic communication"],
        "daily_tools": ["Clinical assessment scales", "electronic health records"],
        "recommended_books": ["An Unquiet Mind by Kay Redfield Jamison"],
        "recommended_communities": ["Korean Neuropsychiatric Association"],
        "advice_for_beginners": "Your own mental health struggles don't disqualify you from this field — for me, they became one of the most useful clinical tools I have.",
        "advice_for_parents": "A doctor who has faced their own mental health challenges and sought treatment is not a weaker doctor — often, the opposite is true.",
        "faqs": [{"question": "Can someone with anxiety or depression become a psychiatrist?", "answer": "Yes — many excellent psychiatrists, myself included, have personal experience with mental health conditions, and it often deepens rather than undermines clinical empathy."}],
        "projects": [], "research": [], "certifications": ["Board certification in Psychiatry"],
        "conferences": ["Korean Neuropsychiatric Association annual conference"], "organizations": ["Korean Neuropsychiatric Association"],
        "volunteer_work": ["Speaks publicly about physician mental health and reducing stigma"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_hr_director_natasha_ivanova",
        "name": "Natasha Ivanova, HR Director",
        "role_type": "industry_professional", "field": "human resources", "bio": "Leads people operations for a mid-size tech company; had to lay off a third of her first company's staff during a downturn, which reshaped how she approaches the role.",
        "trait_tags": ["empathy", "leadership"], "learning_style_fit": "Students interested in the human side of business, not just policy and compliance.",
        "organization": "A mid-size technology company", "years_experience": 13, "journey_highlights": ["Led layoffs affecting a third of her first company's staff during a downturn", "Built a retention program that cut voluntary turnover in half"],
        "discussion_topics": ["The hardest parts of HR work honestly", "HR as a strategic career, not just administration", "Leading layoffs with integrity"],
        "profession": "HR Director", "specialization": "People operations and organizational culture", "country": "Bulgaria", "city": "Sofia",
        "industries": ["human resources", "technology"], "education": ["BA Psychology, Sofia University"],
        "current_role": "HR Director", "languages": ["Bulgarian", "English", "Russian"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students interested in HR beyond just recruiting and paperwork", "Students who care about organizational psychology and culture", "Students who want honesty about HR's hardest responsibilities"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Psychology", "description": "Drawn to organizational psychology specifically, not clinical practice.", "year_label": "2005-2009"},
            {"stage": "first_job", "label": "HR generalist at a growing startup", "description": "Handled recruiting, onboarding, and policy work across a rapidly scaling company.", "year_label": "2009-2013"},
            {"stage": "failure", "label": "Led layoffs affecting a third of the company's staff during an economic downturn", "description": "Personally delivered difficult news to people she'd hired and worked closely with, an experience that stayed with her for years.", "year_label": "2013"},
            {"stage": "turning_point", "label": "Redesigned how the company handled workforce planning to avoid repeating the same crisis", "description": "Built more conservative hiring practices tied to sustainable revenue, not just growth targets.", "year_label": "2014"},
            {"stage": "current_role", "label": "HR Director", "description": "Built a retention program that cut voluntary turnover by half at her current company.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "A mix of employee relations conversations, policy work, and strategic planning meetings with executive leadership.",
        "weekly_routine": "Employee-facing conversations and strategic planning woven throughout most weeks.",
        "biggest_challenges": ["Balancing genuine care for employees against real business financial constraints", "Being the person people come to with their hardest workplace problems"],
        "favourite_part": "Watching someone she's supported through a difficult period thrive in the company long-term.",
        "biggest_misconceptions": ["That HR is just paperwork and compliance — much of the real work is organizational psychology and strategy", "That HR always sides with management over employees"],
        "what_surprised_them": "How much emotional labor the role requires, especially during difficult organizational moments like layoffs.",
        "biggest_mistake": "During those layoffs, I initially followed a purely process-driven script for the difficult conversations, and it came across as cold to people who deserved more compassion in a genuinely hard moment. I completely rebuilt my approach to be more personal and honest in every subsequent difficult conversation.",
        "one_regret": "I regret not pushing back harder on the aggressive hiring pace that led to those layoffs in the first place — I saw warning signs I didn't feel senior enough to raise at the time.",
        "salary_reality": "HR leadership roles pay well in Bulgaria's growing tech sector, on par with senior management roles in other departments.",
        "work_life_balance": "Generally steady, though genuinely difficult during periods involving layoffs or serious workplace conflicts.",
        "daily_skills": ["organizational psychology", "employee relations", "workforce planning"],
        "daily_tools": ["HR information systems", "employee engagement survey tools"],
        "recommended_books": ["Work Rules! by Laszlo Bock"],
        "recommended_communities": ["Sofia HR professionals network"],
        "advice_for_beginners": "Speak up early if you see hiring or workforce decisions heading toward a problem — I stayed quiet once, and it led to layoffs I still think about.",
        "advice_for_parents": "HR leadership is a real strategic career requiring psychology, business judgment, and genuine emotional strength — not just administrative paperwork.",
        "faqs": [{"question": "Is HR just about hiring and paperwork?", "answer": "At senior levels, no — it's genuinely strategic work involving organizational psychology, culture design, and difficult judgment calls."}],
        "projects": ["Built a retention program that cut voluntary turnover in half"], "research": [], "certifications": ["SHRM Senior Certified Professional"],
        "conferences": [], "organizations": [], "volunteer_work": ["Mentors early-career HR professionals on handling difficult conversations"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch2).")


if __name__ == "__main__":
    asyncio.run(seed())
