"""Connect Batch 1 — Expert Connect seed data, Law/Education/Agriculture/
Sports/Hospitality/Manufacturing/Research domain group. See
seed_experts_tech_and_science.py for the full module-level convention
notes.

Run via: python -m aureon.scripts.seed_experts_other_domains
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_lawyer_diego_ramirez",
        "name": "Diego Ramírez, Human Rights Lawyer",
        "role_type": "industry_professional", "field": "law", "bio": "Litigates human rights cases at a public interest law firm; failed the bar exam once before passing on his second attempt.",
        "trait_tags": ["values", "communication"], "learning_style_fit": "Students drawn to law for its social impact rather than corporate prestige.",
        "organization": "A public interest legal nonprofit", "years_experience": 11, "journey_highlights": ["Failed the bar exam on his first attempt", "Won a landmark case protecting indigenous land rights"],
        "discussion_topics": ["Failing the bar exam and retaking it", "Public interest law vs. corporate law", "What litigation actually looks like day to day"],
        "profession": "Human Rights Litigator", "specialization": "Indigenous land rights", "country": "Peru", "city": "Lima",
        "industries": ["law", "human rights"], "education": ["Law degree, Pontificia Universidad Católica del Perú"],
        "current_role": "Senior Litigator", "languages": ["Spanish", "Quechua", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who failed or fear failing the bar exam", "Students drawn to law for social justice reasons, not corporate prestige", "Students interested in indigenous rights or environmental law"],
        "career_ids": ["human_rights_researcher"],
        "career_journey": [
            {"stage": "university", "label": "Law degree", "description": "Volunteered with a legal aid clinic throughout his studies.", "year_label": "2007-2012"},
            {"stage": "failure", "label": "Failed the bar exam on his first attempt", "description": "The failure was a genuine blow after years of confident academic performance.", "year_label": "2012"},
            {"stage": "turning_point", "label": "Passed on his second attempt after restructuring his study approach", "description": "Joined a structured study group instead of preparing alone.", "year_label": "2013"},
            {"stage": "first_job", "label": "Junior lawyer at a public interest firm", "description": "Chose lower pay over a corporate firm offer to work on cases he believed in.", "year_label": "2013-2017"},
            {"stage": "current_role", "label": "Senior Litigator", "description": "Won a landmark case protecting indigenous land rights against a mining company.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "Case research and document review most mornings, client and community meetings in the afternoon, court appearances scheduled around case timelines.",
        "weekly_routine": "Steady case preparation punctuated by intense periods before major filings or hearings.",
        "biggest_challenges": ["The years-long timeline of major litigation compared to communities' urgent needs", "Being consistently outresourced by opposing corporate legal teams"],
        "favourite_part": "The moment a community he's represented hears a favorable court ruling read aloud.",
        "biggest_misconceptions": ["That failing the bar exam once disqualifies you from a serious legal career", "That public interest law is less rigorous than corporate law"],
        "what_surprised_them": "How much legal work is patient relationship-building with communities, not just courtroom argument.",
        "biggest_mistake": "On an early case, I missed a procedural filing deadline due to poor case-tracking systems, which nearly cost a client their claim entirely. We managed to get an extension, but it taught me to never trust memory alone for deadlines again.",
        "one_regret": "I regret how ashamed I felt about failing the bar exam — I later learned several respected lawyers I admire had also failed on a first attempt.",
        "salary_reality": "Public interest law pays substantially less than corporate law in Peru — I earn roughly a third of what law school classmates in corporate firms earn, a tradeoff I made deliberately.",
        "work_life_balance": "Demanding around major filings and trials, more predictable during case research phases.",
        "daily_skills": ["legal research", "litigation strategy", "client communication"],
        "daily_tools": ["Legal research databases", "case management software"],
        "recommended_books": ["Just Mercy by Bryan Stevenson"],
        "recommended_communities": ["Peruvian public interest lawyers network"],
        "advice_for_beginners": "A failed bar exam attempt is genuinely common and doesn't end your legal career — restructure how you study, don't just study harder the same way.",
        "advice_for_parents": "Public interest law pays less than corporate law, and that's a real, valid concern to raise — but it's also a stable, respected legal career, not a fallback path.",
        "faqs": [{"question": "Does failing the bar exam end your legal career?", "answer": "No — most jurisdictions allow retakes, and a first-attempt failure is common even among lawyers who go on to distinguished careers."}],
        "projects": ["Won a landmark indigenous land rights case"], "research": [], "certifications": ["Licensed to practice law, Peru"],
        "conferences": [], "organizations": ["Peruvian public interest lawyers association"],
        "volunteer_work": ["Runs free legal clinics in rural indigenous communities"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_teacher_grace_adeyemi",
        "name": "Grace Adeyemi, High School Teacher",
        "role_type": "industry_professional", "field": "education", "bio": "Teaches mathematics at a public high school; considered quitting teaching entirely after a brutal first year.",
        "trait_tags": ["communication", "persistence"], "learning_style_fit": "Students considering teaching who want an honest picture of the first-year struggle.",
        "organization": "A public high school", "years_experience": 9, "journey_highlights": ["Nearly quit after a difficult first year", "Now leads the school's math department"],
        "discussion_topics": ["Surviving a brutal first year of teaching", "Why teachers leave the profession", "Teaching as a long-term career, not a stopgap"],
        "profession": "Mathematics Teacher", "specialization": "Secondary school mathematics", "country": "Nigeria", "city": "Ibadan",
        "industries": ["education"], "education": ["BSc Mathematics Education, University of Ibadan"],
        "current_role": "Head of Mathematics Department", "languages": ["English", "Yoruba"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students considering teaching but worried about burnout", "Students who like mathematics and want to teach it, not just study it", "Students who've had a genuinely hard first year at any job"],
        "career_ids": ["teacher_k12"],
        "career_journey": [
            {"stage": "university", "label": "BSc Mathematics Education", "description": "Confident in her subject knowledge but unprepared for classroom management.", "year_label": "2010-2014"},
            {"stage": "first_job", "label": "First teaching position", "description": "Struggled badly with classroom discipline and nearly quit within her first term.", "year_label": "2015"},
            {"stage": "failure", "label": "Considered leaving teaching entirely after her first year", "description": "Felt like a failure despite strong subject knowledge, because classroom management wasn't something her degree had prepared her for.", "year_label": "2015"},
            {"stage": "turning_point", "label": "Found a mentor teacher who taught her real classroom strategies", "description": "The mentorship, not her degree, is what actually taught her how to teach.", "year_label": "2016"},
            {"stage": "promotion", "label": "Promoted to Head of Mathematics Department", "description": "Now mentors new teachers through the same struggles she faced.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Back-to-back classes most of the day, with grading and lesson planning happening before or after school hours, not during them.",
        "weekly_routine": "Teaching all week, with department meetings and parent communication woven throughout.",
        "biggest_challenges": ["Managing large class sizes with genuinely varied ability levels", "The emotional toll of students facing hardships beyond the classroom's control"],
        "favourite_part": "A student who once struggled coming back years later to say math clicked because of her class.",
        "biggest_misconceptions": ["That teaching ends when the school day ends", "That subject knowledge alone makes someone a good teacher"],
        "what_surprised_them": "How much of teaching is classroom management and relationship-building, not subject delivery.",
        "biggest_mistake": "In my first term, I tried to run my classroom exactly like the ideal, calm lessons I'd imagined in my training, and it fell apart because I hadn't built real relationships or clear routines with my students first. I had to completely rebuild my approach around relationships before the material.",
        "one_regret": "I regret how close I came to quitting before finding a mentor — I nearly left a career I now genuinely love because I assumed struggling meant I wasn't cut out for it.",
        "salary_reality": "Teaching salaries in Nigeria's public school system are modest and a real point of frustration for many committed teachers — it's a genuine tradeoff for the mission, not a secret.",
        "work_life_balance": "Demanding — grading and planning regularly extend into evenings and weekends, especially early in a teaching career.",
        "daily_skills": ["classroom management", "lesson planning", "differentiated instruction"],
        "daily_tools": ["Whiteboard and basic teaching materials", "school gradebook system"],
        "recommended_books": ["Teach Like a Champion by Doug Lemov"],
        "recommended_communities": ["Nigerian mathematics teachers association"],
        "advice_for_beginners": "Find a mentor teacher in your first year — my mentor taught me more about actual teaching in six months than my entire degree did.",
        "advice_for_parents": "A hard first year of teaching is genuinely common and doesn't mean your child chose the wrong career — most teachers who stick with it say the second and third years feel completely different.",
        "faqs": [{"question": "Is it normal to struggle badly in your first year of teaching?", "answer": "Extremely common — most experienced teachers I know had a difficult first year, and mentorship is usually what turns things around."}],
        "projects": [], "research": [], "certifications": ["Teaching license, Nigeria"],
        "conferences": [], "organizations": ["Nigerian mathematics teachers association"],
        "volunteer_work": ["Mentors first-year teachers at her school and nearby schools"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_agronomist_carlos_mendoza",
        "name": "Carlos Mendoza, Agricultural Scientist",
        "role_type": "researcher", "field": "agriculture", "bio": "Advises smallholder coffee farmers on sustainable growing techniques; grew up on a coffee farm that nearly went bankrupt during a price crash.",
        "trait_tags": ["analytical_thinking", "values"], "learning_style_fit": "Students who want science applied directly to real farming communities, not just lab or field research.",
        "organization": "An agricultural extension nonprofit", "years_experience": 10, "journey_highlights": ["His family's coffee farm nearly went bankrupt during a price crash", "Helped over 200 farms adopt disease-resistant coffee varieties"],
        "discussion_topics": ["Agricultural science as a career beyond the lab", "Working directly with farming communities", "Climate change's impact on smallholder agriculture"],
        "profession": "Agricultural Extension Scientist", "specialization": "Smallholder coffee farming resilience", "country": "Colombia", "city": "Manizales",
        "industries": ["agriculture"], "education": ["BSc Agronomy, National University of Colombia", "MSc Plant Pathology, CATIE Costa Rica"],
        "current_role": "Lead Agricultural Extension Scientist", "languages": ["Spanish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students from farming families interested in agricultural science", "Students who want fieldwork over pure lab research", "Students interested in climate resilience for smallholder farmers"],
        "career_ids": ["sustainability_analyst"],
        "career_journey": [
            {"stage": "school", "label": "Rural school near the family coffee farm", "description": "Watched a coffee price crash nearly bankrupt his family when he was 16.", "year_label": "2001-2008"},
            {"stage": "university", "label": "BSc Agronomy, then MSc Plant Pathology", "description": "Studied specifically to understand crop disease resilience after watching disease damage his family's crops too.", "year_label": "2009-2016"},
            {"stage": "first_job", "label": "Field researcher for an agricultural nonprofit", "description": "Worked directly with smallholder farmers rather than pursuing a purely academic path.", "year_label": "2016-2019"},
            {"stage": "turning_point", "label": "Led a program introducing disease-resistant coffee varieties", "description": "The program has now reached over 200 farms.", "year_label": "2020"},
            {"stage": "current_role", "label": "Lead Agricultural Extension Scientist", "description": "Trains other extension workers across the region.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "A mix of field visits to farms, soil and plant sample analysis, and farmer training sessions.",
        "weekly_routine": "Heavy field travel most weeks, with periodic lab analysis and program planning.",
        "biggest_challenges": ["Convincing farmers to adopt new techniques after generations of doing things one way", "Watching climate change outpace some of his own recommendations"],
        "favourite_part": "Visiting a farm years after introducing a new technique and seeing a family genuinely more financially secure.",
        "biggest_misconceptions": ["That agricultural science is only relevant to large industrial farms", "That farmers resist change out of stubbornness rather than real financial risk aversion"],
        "what_surprised_them": "How much trust-building the job requires — farmers won't adopt a new technique from someone they don't trust, no matter how sound the science.",
        "biggest_mistake": "Early in my career, I recommended a new coffee variety to several farms without adequately warning them about a multi-year transition period with reduced yields, and a few farmers faced real financial strain during that gap. I now always model the full transition timeline honestly before recommending any change.",
        "one_regret": "I regret not spending more time simply listening to farmers' existing knowledge before proposing changes — some of what I initially dismissed as 'tradition' turned out to be sound practical wisdom.",
        "salary_reality": "Agricultural extension work pays modestly in Colombia, well below what a private-sector agribusiness role might offer, but it's the direct community impact that keeps him in the field.",
        "work_life_balance": "Significant travel to rural farms, though generally predictable, seasonal scheduling.",
        "daily_skills": ["plant pathology", "soil science", "farmer training and communication"],
        "daily_tools": ["Field diagnostic kits", "soil testing equipment"],
        "recommended_books": ["Tomorrow's Table by Pamela Ronald and Raoul Adamchak"],
        "recommended_communities": ["Colombian coffee growers federation network"],
        "advice_for_beginners": "Spend real time listening to farmers before recommending anything — the science only works if people trust and can afford to use it.",
        "advice_for_parents": "Agricultural science is a real, needed career combining rigorous research with direct community impact — it's not a fallback for students who 'couldn't' do other sciences.",
        "faqs": [{"question": "Is agricultural science only for people from farming backgrounds?", "answer": "No, but real field experience helps enormously — my own farming background gave me credibility with the communities I now serve."}],
        "projects": ["Helped over 200 farms adopt disease-resistant coffee varieties"], "research": ["Published research on coffee leaf rust resistance in smallholder conditions"],
        "certifications": [], "conferences": ["World Coffee Producers Forum"], "organizations": ["Colombian coffee growers federation"],
        "volunteer_work": ["Trains new extension workers for free through his nonprofit"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_sports_coach_leon_baptiste",
        "name": "Léon Baptiste, Track and Field Coach",
        "role_type": "industry_professional", "field": "sports coaching", "bio": "Coaches sprinters at a national training center; his own competitive career ended early due to a serious injury.",
        "trait_tags": ["leadership", "persistence"], "learning_style_fit": "Students whose own athletic dreams didn't work out as planned and want to know coaching is a real, separate path.",
        "organization": "A national athletics training center", "years_experience": 14, "journey_highlights": ["A career-ending injury ended his own competitive running at 23", "Coached an athlete to a national championship title"],
        "discussion_topics": ["Transitioning from athlete to coach after injury", "What sports coaching actually involves beyond training sessions", "Building a coaching career without having been an elite athlete yourself"],
        "profession": "Track and Field Coach", "specialization": "Sprint training", "country": "Jamaica", "city": "Kingston",
        "industries": ["sports"], "education": ["BSc Sports Science, University of the West Indies"],
        "current_role": "Head Sprint Coach", "languages": ["English", "Jamaican Patois"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students whose athletic career was cut short by injury", "Students interested in coaching rather than competing", "Students who want to know what a coach actually does beyond training sessions"],
        "career_ids": [],
        "career_journey": [
            {"stage": "school", "label": "Secondary school track program", "description": "A standout sprinter with real hopes of competing internationally.", "year_label": "2001-2008"},
            {"stage": "university", "label": "BSc Sports Science, while competing", "description": "Balanced serious training with academic study.", "year_label": "2009-2013"},
            {"stage": "failure", "label": "A serious hamstring injury ended his competitive career at 23", "description": "Spent nearly a year in denial before accepting his running career was over.", "year_label": "2013"},
            {"stage": "career_transition", "label": "Moved into coaching", "description": "Started as an assistant coach at his old university program, unsure if he'd find real purpose outside competing himself.", "year_label": "2014-2016"},
            {"stage": "turning_point", "label": "Coached an athlete to a national championship title", "description": "This is when coaching started feeling like his own real achievement, not a consolation path.", "year_label": "2019"},
            {"stage": "current_role", "label": "Head Sprint Coach", "description": "Leads training for a roster of competitive sprinters at a national center.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Early morning training sessions, video review of athlete technique, and individualized training plan adjustments throughout the day.",
        "weekly_routine": "Structured training cycles building toward competition seasons, with recovery periods built in deliberately.",
        "biggest_challenges": ["Managing an athlete's injury risk against their own desire to push harder", "The emotional weight of an athlete's Olympic or championship dreams resting partly on his coaching decisions"],
        "favourite_part": "An athlete's personal best time after months of patient, incremental training work.",
        "biggest_misconceptions": ["That you need to have been an elite athlete yourself to become a great coach", "That coaching is just running the same training sessions the coach once did as an athlete"],
        "what_surprised_them": "How much of coaching is psychology and communication, not just physical training design.",
        "biggest_mistake": "Early in my coaching career, I pushed an athlete through a training load modeled on my own competitive training, without accounting for her different injury history. She suffered a significant setback that could have been avoided with more individualized, cautious programming.",
        "one_regret": "I regret how long I mourned my own competitive career before really committing to coaching — that grieving period delayed me finding real purpose in this work.",
        "salary_reality": "Coaching salaries in Jamaica's athletics system are modest at developmental levels and improve significantly only once you're working with elite, internationally competitive athletes.",
        "work_life_balance": "Early mornings are non-negotiable, and competition season travel disrupts normal routine significantly.",
        "daily_skills": ["training program design", "biomechanics analysis", "athlete psychology"],
        "daily_tools": ["Video analysis software", "GPS training trackers"],
        "recommended_books": ["The Sports Gene by David Epstein"],
        "recommended_communities": ["Jamaica Athletics Administrative Association coaching network"],
        "advice_for_beginners": "An injury that ends your competing career doesn't end your career in sport — coaching gave me a version of purpose I didn't expect to find again.",
        "advice_for_parents": "If your child's athletic dream was cut short by injury, coaching is a genuine, respected path to stay in the sport they love, not a lesser consolation.",
        "faqs": [{"question": "Do you need to have been a professional athlete to coach at a high level?", "answer": "It helps with credibility, but many excellent coaches, myself included, had their competitive careers cut short — coaching skill is genuinely a separate craft."}],
        "projects": ["Coached an athlete to a national championship title"], "research": [], "certifications": ["World Athletics Level 3 Coaching Certification"],
        "conferences": [], "organizations": ["Jamaica Athletics Administrative Association"],
        "volunteer_work": ["Runs free youth track clinics in his home community"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_hotel_manager_isabella_conti",
        "name": "Isabella Conti, Hotel General Manager",
        "role_type": "industry_professional", "field": "hospitality", "bio": "Manages operations for a boutique hotel chain; started as a housekeeping staff member at 18 while supporting her family.",
        "trait_tags": ["leadership", "communication"], "learning_style_fit": "Students who want to know a hospitality career can start from the ground floor and lead somewhere real.",
        "organization": "A boutique hotel chain", "years_experience": 15, "journey_highlights": ["Started as housekeeping staff at 18", "Now oversees operations for three hotel properties"],
        "discussion_topics": ["Building a hospitality career from an entry-level role", "What hotel management actually involves", "Balancing guest experience with real operational costs"],
        "profession": "Regional General Manager", "specialization": "Boutique hotel operations", "country": "Italy", "city": "Florence",
        "industries": ["hospitality"], "education": ["Hospitality management diploma, completed part-time while working"],
        "current_role": "Regional General Manager, Three Properties", "languages": ["Italian", "English", "French"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students starting hospitality careers from entry-level roles", "Students who worked to support family while studying part-time", "Students interested in operations and management, not just front-of-house guest service"],
        "career_ids": [],
        "career_journey": [
            {"stage": "first_job", "label": "Housekeeping staff at a small hotel", "description": "Took the job at 18 to help support her family financially, with no plan for it to become a career.", "year_label": "2009"},
            {"stage": "promotion", "label": "Promoted to front desk, then guest services supervisor", "description": "Pursued a part-time hospitality management diploma alongside full-time work.", "year_label": "2011-2015"},
            {"stage": "career_transition", "label": "Moved into assistant hotel management", "description": "Faced real skepticism from colleagues who remembered her as housekeeping staff.", "year_label": "2016"},
            {"stage": "promotion", "label": "Became General Manager of her first property", "description": "Turned around a struggling hotel's guest satisfaction ratings within a year.", "year_label": "2019"},
            {"stage": "current_role", "label": "Regional General Manager, Three Properties", "description": "Now oversees operations, staffing, and guest experience across three boutique hotels.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "A mix of staff management, budget review, and handling guest issues that front-line staff couldn't resolve alone.",
        "weekly_routine": "Property visits across her three hotels, financial review, and staff development meetings.",
        "biggest_challenges": ["Balancing guest experience quality against real cost pressures", "Staff turnover in an industry with historically difficult working conditions"],
        "favourite_part": "Promoting a staff member from an entry-level role, the way she was once promoted herself.",
        "biggest_misconceptions": ["That hospitality careers cap out at front-desk or housekeeping work", "That hotel management is just about being friendly to guests"],
        "what_surprised_them": "How much of hotel management is financial and operational strategy, not just guest service.",
        "biggest_mistake": "Early in my first General Manager role, I cut housekeeping staff hours too aggressively to hit a budget target, without accounting for the real toll on remaining staff and guest satisfaction. Both suffered until I reversed the decision and found savings elsewhere.",
        "one_regret": "I regret how much self-doubt I carried during my transition into management — some colleagues' skepticism about my background made me question whether I belonged in that role.",
        "salary_reality": "Hospitality careers in Italy start at genuinely low entry-level wages, but management-level roles pay solidly — the climb from housekeeping to regional management took me over a decade.",
        "work_life_balance": "Demanding, especially during peak tourist seasons, with real limits on personal time during those stretches.",
        "daily_skills": ["staff management", "budgeting", "guest relations", "operations"],
        "daily_tools": ["Property management software", "budgeting and forecasting spreadsheets"],
        "recommended_books": ["Setting the Table by Danny Meyer"],
        "recommended_communities": ["Italian hotel managers association"],
        "advice_for_beginners": "Don't assume an entry-level hospitality job is a dead end — my career started in housekeeping, and it taught me operational details that make me a better manager today.",
        "advice_for_parents": "Hospitality offers real career progression from entry-level roles into genuine management careers — it's not just seasonal or temporary work.",
        "faqs": [{"question": "Can you really build a management career starting from housekeeping?", "answer": "Yes — my own path is proof, though it requires deliberately pursuing further training and being willing to prove yourself repeatedly along the way."}],
        "projects": ["Turned around guest satisfaction ratings at a struggling property within a year"], "research": [],
        "certifications": ["Hospitality management diploma"], "conferences": [], "organizations": ["Italian hotel managers association"],
        "volunteer_work": ["Mentors entry-level hospitality staff on career progression"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_manufacturing_engineer_wen_jie",
        "name": "Wen Jie, Manufacturing Process Engineer",
        "role_type": "industry_professional", "field": "manufacturing", "bio": "Optimizes production lines at an electronics manufacturing plant; his first major process redesign caused a costly production shutdown.",
        "trait_tags": ["analytical_thinking", "systems_thinking"], "learning_style_fit": "Students who like optimizing complex physical systems with many interacting parts.",
        "organization": "An electronics manufacturing plant", "years_experience": 9, "journey_highlights": ["A process redesign he led caused a costly two-day production shutdown", "Later redesigned the same line to cut defect rates by 40%"],
        "discussion_topics": ["Recovering from a costly professional mistake", "What manufacturing engineering actually involves", "Industrial careers beyond the factory floor stereotype"],
        "profession": "Manufacturing Process Engineer", "specialization": "Electronics production line optimization", "country": "China", "city": "Shenzhen",
        "industries": ["manufacturing"], "education": ["BEng Industrial Engineering, South China University of Technology"],
        "current_role": "Senior Process Engineer", "languages": ["Mandarin", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in industrial or manufacturing engineering specifically", "Students who've made a costly mistake at work and worry it defines them", "Students who like optimizing complex systems"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BEng Industrial Engineering", "description": "Focused coursework on production systems and quality control.", "year_label": "2010-2014"},
            {"stage": "first_job", "label": "Junior process engineer", "description": "Worked on incremental process improvements under close supervision.", "year_label": "2014-2017"},
            {"stage": "failure", "label": "Led a major process redesign that caused a two-day production shutdown", "description": "A miscalculated changeover procedure halted the line and cost the company significant revenue.", "year_label": "2018"},
            {"stage": "turning_point", "label": "Rebuilt trust by redesigning the same line more carefully", "description": "The revised design ultimately cut the line's defect rate by 40%.", "year_label": "2019"},
            {"stage": "current_role", "label": "Senior Process Engineer", "description": "Now leads process redesign projects with a much more rigorous testing protocol.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Time split between the factory floor observing production and an office analyzing process data for bottlenecks and defects.",
        "weekly_routine": "Data analysis and design work most days, with periodic intensive implementation weeks when a new process goes live.",
        "biggest_challenges": ["Balancing production speed against quality and defect rates", "The real financial stakes of a process change that doesn't go as planned"],
        "favourite_part": "Watching a redesigned process run smoothly after months of careful testing.",
        "biggest_misconceptions": ["That manufacturing engineering is just factory floor supervision", "That one major professional mistake permanently damages your career"],
        "what_surprised_them": "How much of the job is really risk management and testing, not just clever process design.",
        "biggest_mistake": "The two-day shutdown I caused came from skipping a full pilot test before rolling a new process change across the entire line — I was under deadline pressure and took a shortcut I shouldn't have. It was expensive and humbling, but it's why I now insist on full pilot testing no matter the time pressure.",
        "one_regret": "I regret giving in to the deadline pressure that led to that shortcut — the two-day shutdown cost far more time and money than the pilot test I skipped would have taken.",
        "salary_reality": "Manufacturing engineering pays well in China's electronics manufacturing hubs like Shenzhen, reflecting genuine demand for engineers who can improve production efficiency.",
        "work_life_balance": "Generally steady, with real intensity during major process rollouts.",
        "daily_skills": ["process design", "statistical process control", "root cause analysis"],
        "daily_tools": ["Six Sigma tools", "production data analytics software"],
        "recommended_books": ["The Toyota Way by Jeffrey Liker"],
        "recommended_communities": ["Shenzhen manufacturing engineers network"],
        "advice_for_beginners": "Never skip a pilot test to save time — the shutdown I caused cost far more time than the shortcut I took to avoid it.",
        "advice_for_parents": "A costly professional mistake early in a career, especially one openly learned from, is a normal part of engineering growth, not a permanent mark against your child.",
        "faqs": [{"question": "Does one major mistake ruin an engineering career?", "answer": "Not if you learn visibly from it — my career actually strengthened after I rebuilt trust by redesigning the same process more carefully."}],
        "projects": ["Redesigned a production line, cutting defect rates by 40%"], "research": [], "certifications": ["Six Sigma Green Belt"],
        "conferences": [], "organizations": [], "volunteer_work": ["Mentors junior engineers on process testing rigor"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_research_scientist_elif_yildiz",
        "name": "Dr. Elif Yıldız, Materials Research Scientist",
        "role_type": "researcher", "field": "materials science", "bio": "Researches battery materials at a university lab; her PhD thesis experiment failed to replicate for nearly two years before finally working.",
        "trait_tags": ["persistence", "analytical_thinking"], "learning_style_fit": "Students who want an honest picture of how much research is repeated failure before any success.",
        "organization": "A public university research lab", "years_experience": 8, "journey_highlights": ["Her core PhD experiment failed to replicate for almost two years", "Her eventual published findings are now cited in over 50 papers"],
        "discussion_topics": ["Handling years of failed experiments during a PhD", "Academic research career realities", "Battery materials research"],
        "profession": "Research Scientist", "specialization": "Next-generation battery materials", "country": "Turkey", "city": "Ankara",
        "industries": ["manufacturing & research"], "education": ["BSc Materials Science, Middle East Technical University", "PhD Materials Science, Middle East Technical University"],
        "current_role": "Research Scientist, Battery Materials Lab", "languages": ["Turkish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students starting a PhD who are discouraged by early failed experiments", "Students interested in materials science and energy research", "Students weighing academic research against industry research"],
        "career_ids": ["materials_research_scientist"],
        "career_journey": [
            {"stage": "university", "label": "BSc Materials Science", "description": "Developed a fascination with battery chemistry during an undergraduate lab course.", "year_label": "2007-2011"},
            {"stage": "university", "label": "PhD Materials Science", "description": "Chose a genuinely ambitious, high-risk thesis topic on a new battery electrode material.", "year_label": "2012-2018"},
            {"stage": "failure", "label": "Her core experiment failed to replicate reliably for almost two years", "description": "Watched labmates with more straightforward projects graduate while she remained stuck, seriously questioning whether to abandon the topic.", "year_label": "2014-2016"},
            {"stage": "turning_point", "label": "Identified a subtle contamination source causing the inconsistent results", "description": "A months-long systematic elimination process finally found the real cause.", "year_label": "2016"},
            {"stage": "current_role", "label": "Research Scientist, Battery Materials Lab", "description": "Her eventual published findings are now cited in over 50 subsequent papers.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Lab experiment time in the mornings, data analysis and literature review in the afternoons, with regular grant-writing during funding cycles.",
        "weekly_routine": "Experimental work most days, with a weekly lab group meeting reviewing everyone's progress and setbacks.",
        "biggest_challenges": ["The genuine uncertainty of whether years of work will ever produce a publishable result", "Competing for limited research funding"],
        "favourite_part": "The specific moment an experiment finally works after months of failed attempts — nothing else compares.",
        "biggest_misconceptions": ["That research is a steady, linear process of discovery — it's mostly repeated failure with occasional breakthroughs", "That a stalled PhD project means the researcher isn't capable"],
        "what_surprised_them": "How much of research success is really about systematic troubleshooting patience, not sudden inspiration.",
        "biggest_mistake": "During my stalled years, I kept re-running the same failed protocol with minor tweaks instead of stepping back to question my fundamental assumptions. Once I finally did a systematic root-cause investigation instead of small tweaks, I found the answer within months.",
        "one_regret": "I regret not seeking help from other labs' contamination-control expertise sooner — I tried to solve the problem alone out of a sense that I should be able to figure it out myself.",
        "salary_reality": "Academic research salaries in Turkey are modest, especially during PhD and early postdoc years — financial stability came only several years into her research career.",
        "work_life_balance": "The stalled years were genuinely stressful and consumed evenings and weekends; it's more balanced now with a steadier research direction.",
        "daily_skills": ["experimental design", "materials characterization", "data analysis"],
        "daily_tools": ["Electron microscopy equipment", "electrochemical testing systems"],
        "recommended_books": ["Lab Girl by Hope Jahren"],
        "recommended_communities": ["Materials Research Society"],
        "advice_for_beginners": "If an experiment keeps failing, question your fundamental assumptions, not just your execution — small tweaks to a flawed approach rarely fix a fundamental problem.",
        "advice_for_parents": "Years of what looks like 'no progress' during a PhD is genuinely normal in research — please don't interpret a stalled project as your child failing.",
        "faqs": [{"question": "Is it normal for a PhD project to stall for years?", "answer": "Yes — many successful researchers, myself included, went through multi-year stretches of failed experiments before a breakthrough."}],
        "projects": [], "research": ["Published foundational work on a next-generation battery electrode material, now cited in 50+ papers"],
        "certifications": [], "conferences": ["Materials Research Society annual meeting"], "organizations": ["Materials Research Society"],
        "volunteer_work": ["Mentors PhD students going through stalled or failing experiments"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (other_domains batch).")


if __name__ == "__main__":
    asyncio.run(seed())
