"""Connect Batch 1 — Expert Connect seed data, fifth wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch5
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_chemical_engineer_ravi_krishnan",
        "name": "Ravi Krishnan, Chemical Engineer",
        "role_type": "industry_professional", "field": "chemical engineering", "bio": "Optimizes production processes at a pharmaceutical manufacturing plant; a process error he approved once contaminated an entire batch of product.",
        "trait_tags": ["analytical_thinking", "systems_thinking"], "learning_style_fit": "Students who like applying chemistry to large-scale industrial systems.",
        "organization": "A pharmaceutical manufacturing company", "years_experience": 10, "journey_highlights": ["Approved a process change that contaminated an entire product batch", "Later redesigned the process to eliminate the contamination risk entirely"],
        "discussion_topics": ["Recovering from a costly quality failure", "Chemical engineering beyond oil and gas", "Pharmaceutical manufacturing as a career"],
        "profession": "Process Engineer", "specialization": "Pharmaceutical manufacturing", "country": "India", "city": "Hyderabad",
        "industries": ["manufacturing", "pharmaceuticals"], "education": ["BTech Chemical Engineering, Indian Institute of Technology Hyderabad"],
        "current_role": "Senior Process Engineer", "languages": ["English", "Telugu", "Hindi"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like chemistry applied to industrial-scale problems", "Students interested in pharmaceutical manufacturing specifically", "Students who've made a costly professional mistake"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BTech Chemical Engineering", "description": "Focused coursework on process design and control systems.", "year_label": "2009-2013"},
            {"stage": "first_job", "label": "Junior process engineer", "description": "Learned plant operations under close senior supervision.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Approved a process modification that contaminated an entire production batch", "description": "A cross-contamination risk he'd underestimated cost the company a significant batch and delayed a product launch.", "year_label": "2017"},
            {"stage": "turning_point", "label": "Redesigned the process with additional containment safeguards", "description": "The redesigned process has run without a similar incident since.", "year_label": "2018"},
            {"stage": "current_role", "label": "Senior Process Engineer", "description": "Now leads process safety reviews for new manufacturing changes.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Monitoring production data, reviewing process change proposals, and coordinating with quality assurance teams.",
        "weekly_routine": "Steady monitoring and improvement work, with periodic intensive reviews before major process changes.",
        "biggest_challenges": ["Balancing production efficiency against uncompromising safety and quality standards", "The regulatory scrutiny pharmaceutical manufacturing requires"],
        "favourite_part": "A process improvement that measurably increases both safety and efficiency at once.",
        "biggest_misconceptions": ["That chemical engineering is only about oil and gas", "That a major quality failure permanently damages an engineer's career"],
        "what_surprised_them": "How much regulatory and quality assurance knowledge the role requires beyond core engineering.",
        "biggest_mistake": "I approved a process change without running a full cross-contamination risk assessment, trusting my own quick judgment instead of the formal review process designed to catch exactly this kind of risk. It cost the company a full batch and taught me to never skip that formal process again, no matter the time pressure.",
        "one_regret": "I regret prioritizing speed over the full review process on that one decision — the time I thought I was saving cost far more in the end.",
        "salary_reality": "Chemical engineering in India's pharmaceutical sector pays well relative to many local engineering roles, reflecting the specialized regulatory knowledge required.",
        "work_life_balance": "Generally steady, with occasional intensity during major process changes or regulatory audits.",
        "daily_skills": ["process engineering", "quality risk assessment", "regulatory compliance"],
        "daily_tools": ["Process simulation software", "statistical process control tools"],
        "recommended_books": ["Perry's Chemical Engineers' Handbook"],
        "recommended_communities": ["Indian Institute of Chemical Engineers"],
        "advice_for_beginners": "Never skip a formal safety or quality review to save time — my one shortcut cost far more than the process it was meant to speed up.",
        "advice_for_parents": "A costly manufacturing error, especially one openly learned from, is a normal part of an engineer's growth in a high-stakes industry, not a permanent mark against them.",
        "faqs": [{"question": "Is chemical engineering only relevant to oil and gas?", "answer": "No — pharmaceuticals, food production, and materials manufacturing all rely heavily on chemical engineers too."}],
        "projects": ["Redesigned a manufacturing process eliminating a contamination risk"], "research": [],
        "certifications": [], "conferences": [], "organizations": ["Indian Institute of Chemical Engineers"],
        "volunteer_work": ["Mentors engineering students on industrial safety culture"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_meteorologist_lena_johansson",
        "name": "Lena Johansson, Meteorologist",
        "role_type": "industry_professional", "field": "meteorology", "bio": "Forecasts severe weather for a national weather service; a missed forecast early in her career led to real property damage in a town she was covering.",
        "trait_tags": ["analytical_thinking", "communication"], "learning_style_fit": "Students who like physics and data applied to real, time-sensitive public safety decisions.",
        "organization": "A national meteorological service", "years_experience": 9, "journey_highlights": ["A missed severe storm forecast contributed to real property damage", "Now leads severe weather forecasting for an entire region"],
        "discussion_topics": ["The pressure of forecasts that affect real public safety", "Meteorology as a data science career", "Recovering from a professional error with public consequences"],
        "profession": "Senior Meteorologist", "specialization": "Severe weather forecasting", "country": "Sweden", "city": "Norrköping",
        "industries": ["meteorology", "government"], "education": ["MSc Meteorology, Stockholm University"],
        "current_role": "Senior Regional Meteorologist", "languages": ["Swedish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like physics and want to see it applied to real-time public safety decisions", "Students who've made a professional error with real consequences", "Students interested in climate and weather sciences"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "MSc Meteorology", "description": "Focused her thesis on severe convective storm prediction models.", "year_label": "2011-2016"},
            {"stage": "first_job", "label": "Junior forecaster", "description": "Learned operational forecasting under senior supervision.", "year_label": "2016-2018"},
            {"stage": "failure", "label": "Missed the severity of an approaching storm system during an early solo shift", "description": "The storm caused real property damage in a town that received a less urgent warning than the situation actually required.", "year_label": "2018"},
            {"stage": "turning_point", "label": "Rebuilt her forecasting checklist around more conservative uncertainty communication", "description": "Learned to communicate genuine forecast uncertainty clearly rather than defaulting to overconfidence.", "year_label": "2019"},
            {"stage": "current_role", "label": "Senior Regional Meteorologist", "description": "Leads severe weather forecasting for an entire region.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Continuous monitoring of weather models and real-time data, issuing and updating public forecasts and warnings as conditions evolve.",
        "weekly_routine": "Rotating shift work, including nights and weekends, since severe weather doesn't follow business hours.",
        "biggest_challenges": ["The genuine uncertainty inherent in forecasting, communicated to a public that wants certainty", "Shift work disrupting normal sleep and social patterns"],
        "favourite_part": "A well-communicated severe weather warning that helps a community prepare in time.",
        "biggest_misconceptions": ["That meteorologists can predict weather with total certainty", "That a missed or wrong forecast reflects laziness rather than the field's genuine complexity"],
        "what_surprised_them": "How much of the job is really about communicating uncertainty clearly, not eliminating it.",
        "biggest_mistake": "During that early missed forecast, I trusted a single model output too heavily instead of properly weighing the genuine disagreement between multiple forecasting models, which understated the storm's real risk. I now always communicate model disagreement explicitly rather than picking one confident-sounding number.",
        "one_regret": "I regret how much guilt I carried afterward instead of using the experience constructively sooner — it took real support from senior colleagues to help me learn from it rather than just feel ashamed by it.",
        "salary_reality": "Meteorology salaries in Sweden's public weather service are stable and reasonable, reflecting a specialized science career within government service.",
        "work_life_balance": "Genuinely disrupted by shift work, including nights, weekends, and holidays during severe weather events.",
        "daily_skills": ["weather model interpretation", "risk communication", "data analysis"],
        "daily_tools": ["Numerical weather prediction models", "radar and satellite data systems"],
        "recommended_books": ["The Signal and the Noise by Nate Silver"],
        "recommended_communities": ["European Meteorological Society"],
        "advice_for_beginners": "Always communicate genuine forecast uncertainty rather than false confidence — the mistake I made early on came from picking one model's clean answer over the messier, more honest truth.",
        "advice_for_parents": "A missed forecast with real consequences is a devastating experience for any meteorologist, but it's also survivable and often becomes a formative professional lesson, not a career-ending failure.",
        "faqs": [{"question": "Why are weather forecasts sometimes wrong?", "answer": "Weather systems are genuinely chaotic and complex — forecasters work with probability, not certainty, and communicating that honestly is a core part of the job."}],
        "projects": [], "research": [], "certifications": [],
        "conferences": ["European Meteorological Society annual meeting"], "organizations": ["European Meteorological Society"],
        "volunteer_work": ["Trains junior forecasters on uncertainty communication"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_museum_curator_beatrice_hall",
        "name": "Beatrice Hall, Museum Curator",
        "role_type": "industry_professional", "field": "museum studies", "bio": "Curates historical exhibitions at a national museum; her first major exhibition proposal was rejected as too niche to attract visitors.",
        "trait_tags": ["creativity", "communication"], "learning_style_fit": "Students who like research and storytelling combined with public-facing creative work.",
        "organization": "A national history museum", "years_experience": 12, "journey_highlights": ["Her first major exhibition proposal was rejected outright", "Her fourth exhibition became the museum's most-attended show that year"],
        "discussion_topics": ["Getting a major creative proposal rejected", "Museum careers beyond tour guides", "Balancing academic rigor with public accessibility"],
        "profession": "Senior Curator", "specialization": "Social history exhibitions", "country": "United Kingdom", "city": "Manchester",
        "industries": ["museums", "culture"], "education": ["BA History, University of Manchester", "MA Museum Studies, University of Leicester"],
        "current_role": "Senior Curator, Social History", "languages": ["English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like history and research but want a career beyond teaching", "Students who've had a creative proposal rejected", "Students interested in making academic knowledge accessible to the public"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA History, then MA Museum Studies", "description": "Interned at a small regional museum during her master's degree.", "year_label": "2008-2013"},
            {"stage": "first_job", "label": "Junior curatorial assistant", "description": "Supported senior curators on exhibition research and logistics.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Her first major independent exhibition proposal was rejected as too academically niche", "description": "Museum leadership worried the topic wouldn't attract enough public visitors to justify the budget.", "year_label": "2017"},
            {"stage": "turning_point", "label": "Learned to pair rigorous research with more accessible public storytelling", "description": "Revised her approach to exhibition proposals around visitor experience, not just academic content.", "year_label": "2018"},
            {"stage": "current_role", "label": "Senior Curator, Social History", "description": "Her fourth major exhibition became the museum's most-attended show that year.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of archival research, exhibition design meetings, and coordinating with conservators and designers.",
        "weekly_routine": "Research-heavy periods alternate with intensive exhibition build phases before openings.",
        "biggest_challenges": ["Balancing academic rigor against genuinely engaging public storytelling", "Securing limited exhibition budget and space for ambitious ideas"],
        "favourite_part": "Watching a visitor genuinely moved by an object or story she chose to include.",
        "biggest_misconceptions": ["That museum curators just decide what looks nice on a wall", "That academic rigor and public accessibility are in conflict"],
        "what_surprised_them": "How much curatorial work is really about audience psychology and storytelling, not just historical research.",
        "biggest_mistake": "My rejected first proposal focused entirely on academic significance without genuinely considering how a general visitor would connect with the material emotionally. I learned to always start exhibition planning with the visitor's experience, not just the historical content.",
        "one_regret": "I regret how discouraged that rejection made me feel for months — it delayed me proposing new ideas out of fear of a second rejection.",
        "salary_reality": "Museum curator salaries in the UK are modest relative to the graduate qualifications required, a real and known tradeoff for those drawn to the field's cultural mission.",
        "work_life_balance": "Generally reasonable, with real intensity during exhibition installation periods before an opening.",
        "daily_skills": ["archival research", "exhibition design", "public storytelling"],
        "daily_tools": ["Museum collection management databases", "exhibition design software"],
        "recommended_books": ["The Participatory Museum by Nina Simon"],
        "recommended_communities": ["Museums Association (UK)"],
        "advice_for_beginners": "Always design an exhibition around the visitor's experience first, not just the academic content — my rejected proposal taught me this the hard way.",
        "advice_for_parents": "Museum curation is a genuine career combining serious research with creative public communication, not just a hobby-adjacent job.",
        "faqs": [{"question": "Do museum curators need a PhD?", "answer": "Not always — a master's in museum studies or a relevant field, combined with real curatorial experience, is often sufficient for many roles."}],
        "projects": ["Curated the museum's most-attended exhibition of the year"], "research": [], "certifications": [],
        "conferences": [], "organizations": ["Museums Association"], "volunteer_work": ["Advises university museum studies students on exhibition proposals"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_translator_interpreter_yuki_hoshino",
        "name": "Yuki Hoshino, Conference Interpreter",
        "role_type": "industry_professional", "field": "translation and interpretation", "bio": "Works as a simultaneous interpreter for international conferences and diplomatic meetings; froze completely during her first professional assignment.",
        "trait_tags": ["communication", "analytical_thinking"], "learning_style_fit": "Students with strong language skills who want to know what real interpretation work demands beyond fluency.",
        "organization": "Independent conference interpreter", "years_experience": 11, "journey_highlights": ["Froze mid-sentence during her first professional interpretation assignment", "Now interprets for major international diplomatic conferences"],
        "discussion_topics": ["Freezing during a live professional performance and recovering", "Interpretation vs. translation as careers", "Building a freelance interpreting career"],
        "profession": "Simultaneous Conference Interpreter", "specialization": "Diplomatic and international conference interpretation", "country": "Japan", "city": "Tokyo",
        "industries": ["translation & language", "diplomacy"], "education": ["BA International Relations, Sophia University", "Graduate diploma in Conference Interpreting, Monterey Institute"],
        "current_role": "Independent Conference Interpreter", "languages": ["Japanese", "English", "French"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students with strong bilingual or multilingual skills considering interpretation careers", "Students who've frozen or failed publicly during a live performance and want reassurance", "Students weighing translation against live interpretation work"],
        "career_ids": ["foreign_service_officer"],
        "career_journey": [
            {"stage": "university", "label": "BA International Relations, then a specialized interpreting diploma", "description": "Pursued interpretation training abroad after realizing language fluency alone wasn't enough for professional work.", "year_label": "2008-2013"},
            {"stage": "first_job", "label": "First professional simultaneous interpretation assignment", "description": "Froze mid-sentence under the pressure of a live diplomatic meeting, unable to continue for several agonizing seconds before a colleague stepped in.", "year_label": "2014"},
            {"stage": "turning_point", "label": "Worked with a coach on performance anxiety and rebuilt her confidence through smaller assignments", "description": "Gradually took on larger events again after months of deliberate, lower-stakes practice.", "year_label": "2015"},
            {"stage": "current_role", "label": "Independent Conference Interpreter", "description": "Now regularly interprets for major international diplomatic conferences.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "Intensive preparation researching an event's specific terminology beforehand, followed by mentally exhausting real-time simultaneous interpretation during the event itself.",
        "weekly_routine": "Irregular, assignment-based work — some weeks are packed with events, others are quiet preparation and business development time.",
        "biggest_challenges": ["The intense mental fatigue of sustained simultaneous interpretation", "Managing real performance anxiety before high-stakes assignments"],
        "favourite_part": "Successfully bridging a genuinely difficult, high-stakes conversation between parties who couldn't otherwise communicate.",
        "biggest_misconceptions": ["That fluency in two languages is enough to become a professional interpreter", "That freezing once during a live assignment ends your career"],
        "what_surprised_them": "How much specific preparation and mental stamina, not just language skill, real interpretation requires.",
        "biggest_mistake": "I took my first major solo assignment without enough preparation time on the event's specific technical terminology, which contributed directly to the freeze — I simply didn't have the vocabulary ready when I needed it. I now over-prepare terminology for every assignment, no matter how experienced I've become.",
        "one_regret": "I regret not seeking a mentor's guidance before that first assignment — a more experienced interpreter would have flagged my under-preparation immediately.",
        "salary_reality": "Freelance conference interpretation can pay very well per assignment, but the irregular schedule means real income unpredictability, especially in the early years of building a client base.",
        "work_life_balance": "Genuinely irregular — some months are packed with high-intensity work, others quiet, requiring real financial planning.",
        "daily_skills": ["simultaneous interpretation", "terminology research", "high-pressure concentration"],
        "daily_tools": ["Interpretation booth equipment", "specialized glossary databases"],
        "recommended_books": ["Conference Interpreting Explained by Roderick Jones"],
        "recommended_communities": ["International Association of Conference Interpreters"],
        "advice_for_beginners": "Over-prepare terminology for every single assignment, especially early on — my freeze happened because I trusted general fluency over specific preparation.",
        "advice_for_parents": "Freezing during a live professional performance is a real, recoverable setback, not proof of a lack of skill — with the right support, it became a turning point in her career, not an ending.",
        "faqs": [{"question": "Is bilingual fluency enough to become a professional interpreter?", "answer": "No — professional interpretation requires specialized training in simultaneous processing and terminology preparation well beyond general language fluency."}],
        "projects": [], "research": [], "certifications": ["Accredited Conference Interpreter"],
        "conferences": [], "organizations": ["International Association of Conference Interpreters"],
        "volunteer_work": ["Coaches new interpreters on managing performance anxiety"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_photographer_esteban_diaz",
        "name": "Esteban Díaz, Photojournalist",
        "role_type": "creator", "field": "photography", "bio": "Covers social and political events across Latin America as a freelance photojournalist; lost a major photo essay's entire memory card to corruption before ever backing it up.",
        "trait_tags": ["creativity", "persistence"], "learning_style_fit": "Students drawn to visual storytelling who want a realistic picture of freelance creative income.",
        "organization": "Independent freelance photojournalist", "years_experience": 10, "journey_highlights": ["Lost an entire photo essay's images to a corrupted memory card", "His photo essay on urban migration was published internationally"],
        "discussion_topics": ["Losing an entire project's work and rebuilding", "Freelance photography income realities", "Photojournalism ethics and access"],
        "profession": "Freelance Photojournalist", "specialization": "Social and political documentary photography", "country": "Argentina", "city": "Buenos Aires",
        "industries": ["journalism", "photography"], "education": ["Self-taught, with a short documentary photography workshop program"],
        "current_role": "Independent Photojournalist", "languages": ["Spanish", "English", "Portuguese"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students drawn to visual storytelling and documentary work", "Students who've lost significant creative work to a technical failure", "Students weighing freelance photography's real financial instability"],
        "career_ids": [],
        "career_journey": [
            {"stage": "first_job", "label": "Started as a self-taught freelance photographer covering local events", "description": "Built early skills through repetition and study of other photographers' work, not formal training.", "year_label": "2013-2015"},
            {"stage": "failure", "label": "Lost an entire multi-week photo essay to a corrupted memory card", "description": "Had not backed up the images before the card failed, losing weeks of documentation work with subjects he couldn't easily re-photograph.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Rebuilt a rigorous backup discipline and slowly re-earned access to document the same community", "description": "Spent months regaining the trust needed to recreate parts of the lost project.", "year_label": "2017"},
            {"stage": "current_role", "label": "Independent Photojournalist", "description": "His photo essay on urban migration was later published internationally.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Varies enormously by assignment — days in the field shooting, days editing and pitching work to publications.",
        "weekly_routine": "No fixed routine; freelance assignments and pitch deadlines dictate the schedule entirely.",
        "biggest_challenges": ["Genuinely unpredictable freelance income", "Gaining and maintaining trust with vulnerable communities he documents"],
        "favourite_part": "A photograph that captures something true enough to change how a viewer understands an issue.",
        "biggest_misconceptions": ["That photojournalism is a stable, well-paying career for most who pursue it", "That losing work to a technical failure reflects a lack of professionalism"],
        "what_surprised_them": "How much of the job is really about relationship-building and trust, not just technical photography skill.",
        "biggest_mistake": "I didn't back up my photos regularly during that project, trusting a single memory card with weeks of irreplaceable work. Losing it taught me to back up images in at least two places immediately after every single shoot, without exception.",
        "one_regret": "I regret how close that loss came to making me quit entirely — the emotional toll of losing weeks of work nearly outweighed my passion for the craft.",
        "salary_reality": "Freelance photojournalism income in Argentina is genuinely unpredictable and often modest — many photographers I know supplement it with commercial or wedding photography work.",
        "work_life_balance": "Highly irregular, dictated entirely by assignments and deadlines rather than any fixed schedule.",
        "daily_skills": ["photography technique", "photo editing", "pitching and storytelling"],
        "daily_tools": ["DSLR/mirrorless cameras", "Lightroom", "cloud backup systems"],
        "recommended_books": ["On Photography by Susan Sontag"],
        "recommended_communities": ["Latin American photojournalists collective"],
        "advice_for_beginners": "Back up every shoot immediately, in at least two places — losing weeks of irreplaceable work taught me this lesson permanently.",
        "advice_for_parents": "Freelance photojournalism carries real financial instability, and that's a fair, valid concern — but it can become a sustainable career with time, persistence, and often some supplementary work.",
        "faqs": [{"question": "Can you make a stable living as a photojournalist?", "answer": "It's genuinely difficult for many — most freelance photojournalists I know combine editorial work with commercial photography to build a stable income."}],
        "projects": ["Published an internationally recognized photo essay on urban migration"], "research": [],
        "certifications": [], "conferences": [], "organizations": [],
        "volunteer_work": ["Teaches free documentary photography workshops for young people in his neighborhood"],
        "portfolio_links": [{"label": "Portfolio", "url": "https://example.com/estebandiaz"}], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch5).")


if __name__ == "__main__":
    asyncio.run(seed())
