"""Connect Batch 1 — Expert Connect seed data, ninth wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch9
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_astronomer_ines_almeida",
        "name": "Dr. Inês Almeida, Astronomer",
        "role_type": "researcher", "field": "astronomy", "bio": "Researches exoplanet atmospheres at a national observatory; her PhD thesis's central finding was later found to be a data artifact, not a real discovery.",
        "trait_tags": ["curiosity", "analytical_thinking"], "learning_style_fit": "Students who love space and want honesty about how much of research is chasing false leads.",
        "organization": "A national astronomical observatory", "years_experience": 8, "journey_highlights": ["Her PhD's central 'discovery' turned out to be a data processing artifact", "Later co-discovered a real exoplanet atmospheric signature now cited widely"],
        "discussion_topics": ["When a major research finding turns out to be wrong", "Astronomy as a data-heavy research career", "Working with major telescope facilities"],
        "profession": "Research Astronomer", "specialization": "Exoplanet atmospheric characterization", "country": "Portugal", "city": "Lisbon",
        "industries": ["astronomy", "research"], "education": ["BSc Physics, University of Lisbon", "PhD Astrophysics, University of Cambridge"],
        "current_role": "Research Astronomer", "languages": ["Portuguese", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who love space and astronomy specifically", "Students worried about a research finding turning out to be wrong", "Students interested in observational versus theoretical astronomy"],
        "career_ids": ["space_systems_engineer"],
        "career_journey": [
            {"stage": "university", "label": "BSc Physics, then PhD Astrophysics", "description": "Focused her doctoral research on detecting atmospheric signatures in exoplanet data.", "year_label": "2010-2016"},
            {"stage": "failure", "label": "Her central PhD finding was later found to be a data processing artifact, not a real signal", "description": "Discovered this only after a peer researcher couldn't replicate her result, forcing a painful public retraction of part of her published work.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Rebuilt her research with far more rigorous independent verification protocols", "description": "The experience, while humbling, made her a notably more careful and respected researcher.", "year_label": "2017"},
            {"stage": "current_role", "label": "Research Astronomer", "description": "Later co-discovered a real exoplanet atmospheric signature now cited in dozens of subsequent papers.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Analyzing telescope data, running statistical models, and collaborating with international research teams across time zones.",
        "weekly_routine": "Deep data analysis most days, with periodic telescope observation time and international team calls.",
        "biggest_challenges": ["Distinguishing genuine signals from data artifacts in extremely faint astronomical measurements", "The competitive pressure to publish exciting findings quickly"],
        "favourite_part": "The moment a genuinely real signal, verified multiple independent ways, confirms something new about a distant world.",
        "biggest_misconceptions": ["That astronomical discoveries are always straightforward once you have the data", "That a retracted finding permanently damages a researcher's credibility"],
        "what_surprised_them": "How much of modern astronomy is really about statistical rigor and data processing, not looking through telescopes.",
        "biggest_mistake": "My PhD's central finding came from a data processing pipeline that had a subtle systematic error I didn't catch before publication, because I was eager to have an exciting result. Publicly retracting part of my own published work was one of the hardest professional moments of my life, but it's what taught me the rigor I now insist on for every subsequent finding.",
        "one_regret": "I regret rushing to publish that early finding without more independent verification — the pressure to have an exciting PhD result led me to skip a step I now consider non-negotiable.",
        "salary_reality": "Academic astronomy research salaries in Portugal are modest, especially in postdoctoral positions, reflecting broader academic research career economics.",
        "work_life_balance": "Generally reasonable, with occasional intense periods around major telescope observation windows or publication deadlines.",
        "daily_skills": ["statistical data analysis", "astrophysical modeling", "scientific writing"],
        "daily_tools": ["Python/astronomical data analysis software", "telescope data pipelines"],
        "recommended_books": ["The Exoplanet Handbook by Michael Perryman"],
        "recommended_communities": ["European Astronomical Society"],
        "advice_for_beginners": "Never rush an exciting finding to publication without independent verification — my public retraction taught me this in the most painful way possible.",
        "advice_for_parents": "A retracted research finding, especially one honestly corrected, is a normal part of how science actually works, not a permanent mark against a researcher's competence.",
        "faqs": [{"question": "Does a retracted finding end a scientist's career?", "answer": "Not if handled with integrity — retractions happen throughout science, and how a researcher responds matters more than the fact it happened."}],
        "projects": [], "research": ["Co-discovered an exoplanet atmospheric signature now cited in dozens of papers"], "certifications": [],
        "conferences": ["European Astronomical Society annual meeting"], "organizations": ["European Astronomical Society"],
        "volunteer_work": ["Runs public astronomy outreach nights at the observatory"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_park_ranger_malia_kahale",
        "name": "Malia Kahale, National Park Ranger",
        "role_type": "industry_professional", "field": "environmental conservation", "bio": "Manages wildlife protection and visitor safety at a national park; a serious hiking accident on her watch during her first season shaped her entire approach to the job.",
        "trait_tags": ["values", "leadership"], "learning_style_fit": "Students who love the outdoors and want a career combining conservation, safety, and public education.",
        "organization": "A national park service", "years_experience": 11, "journey_highlights": ["A serious visitor hiking accident occurred during her first season on the job", "Redesigned the park's trail safety signage system, now used as a model by other parks"],
        "discussion_topics": ["Handling a serious safety incident on your first job", "Park ranger careers beyond tourism", "Balancing conservation with public access"],
        "profession": "Senior Park Ranger", "specialization": "Wildlife protection and visitor safety", "country": "United States", "city": "near Yellowstone National Park",
        "industries": ["environmental conservation", "government"], "education": ["BSc Environmental Science, University of Montana"],
        "current_role": "Senior Park Ranger", "languages": ["English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who love the outdoors and want a real conservation career", "Students who've experienced or witnessed a serious incident early in a job", "Students weighing conservation research against direct field management roles"],
        "career_ids": ["conservation_biologist"],
        "career_journey": [
            {"stage": "university", "label": "BSc Environmental Science", "description": "Spent summers volunteering at state parks throughout her degree.", "year_label": "2008-2012"},
            {"stage": "first_job", "label": "Junior park ranger", "description": "A serious visitor fall on an inadequately marked trail occurred during her very first season, requiring an emergency rescue.", "year_label": "2013"},
            {"stage": "turning_point", "label": "Led an effort to completely redesign the park's trail warning and safety signage", "description": "The incident, though frightening, became the direct motivation for lasting safety improvements.", "year_label": "2014"},
            {"stage": "promotion", "label": "Promoted through several ranger roles into a senior position", "description": "Her redesigned signage system has since been adopted as a model by several other national parks.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "A mix of trail patrols, wildlife monitoring, visitor education, and emergency response readiness.",
        "weekly_routine": "Seasonal variation is significant — summer visitor season is intensely busy, winter is quieter and more focused on wildlife monitoring.",
        "biggest_challenges": ["Balancing genuine public access to the park against real conservation and safety needs", "The unpredictable nature of wilderness emergencies"],
        "favourite_part": "A visitor leaving with a genuine new appreciation for wildlife conservation after an educational encounter.",
        "biggest_misconceptions": ["That park ranger work is mostly relaxing outdoor time", "That a safety incident during your watch reflects personal failure rather than a systemic gap"],
        "what_surprised_them": "How much of the job is really public safety management and infrastructure planning, not just wildlife work.",
        "biggest_mistake": "During my first season, I didn't push hard enough to flag a trail section I privately thought was inadequately marked, assuming existing signage was sufficient because it always had been. The resulting accident showed me that a ranger's job includes actively questioning existing safety systems, not just following them.",
        "one_regret": "I regret not trusting my own instinct about that trail sooner — I noticed the inadequate marking weeks before the accident but didn't escalate it as urgently as I should have.",
        "salary_reality": "Park ranger salaries in the US National Park Service are modest relative to the training and responsibility required, a genuine tradeoff for those drawn to the mission.",
        "work_life_balance": "Highly seasonal — summer months are extremely demanding, winter offers more balance.",
        "daily_skills": ["wilderness safety management", "wildlife monitoring", "emergency response", "public education"],
        "daily_tools": ["Wilderness first aid equipment", "wildlife tracking tools", "radio communication systems"],
        "recommended_books": ["Desert Solitaire by Edward Abbey"],
        "recommended_communities": ["National Park Service ranger network"],
        "advice_for_beginners": "If you notice a genuine safety gap, escalate it immediately and persistently — I noticed one before an accident happened and didn't push hard enough.",
        "advice_for_parents": "Park ranger work carries real responsibility for public safety and conservation, not just an outdoor lifestyle choice — it's a serious career with genuine training requirements.",
        "faqs": [{"question": "Is park ranger work mostly about relaxing in nature?", "answer": "No — it involves real public safety responsibility, wildlife management science, and often demanding physical and emergency response work."}],
        "projects": ["Redesigned trail safety signage now used as a model by other national parks"], "research": [],
        "certifications": ["Wilderness First Responder certification"], "conferences": [], "organizations": [],
        "volunteer_work": ["Trains new rangers on proactive safety hazard identification"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_immigration_lawyer_sofia_martins",
        "name": "Sofia Martins, Immigration Lawyer",
        "role_type": "industry_professional", "field": "law", "bio": "Represents asylum seekers and immigrants at a legal aid organization; lost her first major asylum case due to an avoidable documentation error.",
        "trait_tags": ["empathy", "persistence"], "learning_style_fit": "Students drawn to law for its direct human impact, who can handle high emotional stakes.",
        "organization": "An immigration legal aid organization", "years_experience": 10, "journey_highlights": ["Lost her first major asylum case due to a documentation error", "Has since successfully represented over 200 asylum seekers"],
        "discussion_topics": ["Losing a case that genuinely changes someone's life", "Immigration law as a career combining law and advocacy", "Working with legal aid versus private practice"],
        "profession": "Immigration Attorney", "specialization": "Asylum and refugee law", "country": "Portugal", "city": "Lisbon",
        "industries": ["law", "human rights"], "education": ["Law degree, University of Lisbon"],
        "current_role": "Senior Immigration Attorney", "languages": ["Portuguese", "English", "French"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students drawn to law for direct human impact rather than corporate work", "Students who've lost something important due to an avoidable mistake", "Students interested in asylum and refugee law specifically"],
        "career_ids": ["human_rights_researcher"],
        "career_journey": [
            {"stage": "university", "label": "Law degree", "description": "Volunteered with a refugee support organization throughout her studies.", "year_label": "2008-2013"},
            {"stage": "first_job", "label": "Junior attorney at a legal aid organization", "description": "Took on her first major independent asylum case within her first year.", "year_label": "2013-2014"},
            {"stage": "failure", "label": "Lost that first case after missing a critical documentation filing deadline", "description": "The client's asylum claim was denied partly due to her administrative error, a devastating outcome she carried real guilt over for years.", "year_label": "2014"},
            {"stage": "turning_point", "label": "Built an obsessively thorough case management and deadline-tracking system", "description": "Never missed another critical filing deadline in the years since.", "year_label": "2015"},
            {"stage": "current_role", "label": "Senior Immigration Attorney", "description": "Has since successfully represented over 200 asylum seekers.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "Client interviews, case documentation preparation, and court or hearing appearances, all under real, high emotional stakes.",
        "weekly_routine": "Steady casework punctuated by hearing dates and filing deadlines that structure much of the schedule.",
        "biggest_challenges": ["The devastating real consequences of a lost case for a client's safety and future", "Managing an overwhelming caseload with limited legal aid resources"],
        "favourite_part": "A client receiving asylum status and beginning to rebuild a safe life.",
        "biggest_misconceptions": ["That immigration law is simple paperwork rather than genuinely complex, high-stakes legal work", "That losing a case always reflects a weak legal argument rather than a preventable process error"],
        "what_surprised_them": "How much administrative precision matters as much as legal argument in immigration cases.",
        "biggest_mistake": "I missed a critical documentation filing deadline on my first major case because I was managing too many cases without a rigorous tracking system, trusting memory instead of a formal process. The client's asylum claim was denied partly as a result, and it's a mistake I've spent my entire career since making sure never happens again.",
        "one_regret": "I regret not asking a senior colleague to review my case management approach earlier — a simple system check would have caught the gap before it cost someone their case.",
        "salary_reality": "Immigration legal aid work pays considerably less than private immigration law practice in Portugal — a real, deliberate tradeoff for the clients she chooses to serve.",
        "work_life_balance": "Demanding — high caseloads and the emotional weight of clients' circumstances make full disconnection genuinely difficult.",
        "daily_skills": ["immigration law", "case documentation", "client advocacy"],
        "daily_tools": ["Legal case management software", "immigration filing systems"],
        "recommended_books": ["The Ungrateful Refugee by Dina Nayeri"],
        "recommended_communities": ["Portuguese immigration lawyers network"],
        "advice_for_beginners": "Build a rigorous case tracking system from day one, and never trust memory alone for critical deadlines — my first lost case came from exactly that gap.",
        "advice_for_parents": "Immigration and asylum law carries genuinely high emotional stakes and real financial tradeoffs compared to corporate law — it's a mission-driven choice, not a lack of ambition.",
        "faqs": [{"question": "Is legal aid immigration work financially sustainable?", "answer": "It pays considerably less than private practice, but many attorneys, including me, find the direct human impact worth the tradeoff, and senior legal aid roles do offer real career progression."}],
        "projects": ["Has successfully represented over 200 asylum seekers"], "research": [], "certifications": ["Licensed Attorney, Portugal"],
        "conferences": [], "organizations": ["Portuguese immigration lawyers network"],
        "volunteer_work": ["Trains junior legal aid attorneys on case management systems"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_radio_broadcaster_kwabena_owusu",
        "name": "Kwabena Owusu, Radio Broadcaster",
        "role_type": "creator", "field": "broadcasting", "bio": "Hosts a popular morning radio show; was fired from his first radio job for an on-air mistake that went viral for the wrong reasons.",
        "trait_tags": ["communication", "persistence"], "learning_style_fit": "Students who think quickly on their feet and want a career built on live, real-time communication.",
        "organization": "A national radio station", "years_experience": 13, "journey_highlights": ["Was fired from his first radio job after an on-air mistake went viral", "Now hosts one of the country's most-listened-to morning shows"],
        "discussion_topics": ["Getting fired publicly and rebuilding a broadcasting career", "Radio as a career in the streaming era", "What live broadcasting actually feels like"],
        "profession": "Radio Show Host", "specialization": "Morning talk and entertainment radio", "country": "Ghana", "city": "Accra",
        "industries": ["media", "broadcasting"], "education": ["BA Communication Studies, University of Ghana"],
        "current_role": "Host, Morning Drive Show", "languages": ["English", "Twi"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who think quickly on their feet and love live communication", "Students who've been publicly fired or embarrassed and worry about their career", "Students weighing broadcasting against podcasting or other media paths"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Communication Studies", "description": "Hosted a student radio show throughout his degree.", "year_label": "2005-2009"},
            {"stage": "first_job", "label": "Junior radio host at a local station", "description": "Was still developing his on-air judgment and comedic timing.", "year_label": "2009-2011"},
            {"stage": "failure", "label": "Made an inappropriate on-air comment during a live segment that went viral for the wrong reasons", "description": "Was fired within days as public backlash grew, and struggled to find broadcasting work for nearly a year afterward.", "year_label": "2011"},
            {"stage": "turning_point", "label": "Rebuilt his career starting with a small community radio station willing to give him a second chance", "description": "Used the difficult year to genuinely reflect on and rebuild his on-air judgment.", "year_label": "2012-2014"},
            {"stage": "current_role", "label": "Host, Morning Drive Show", "description": "Now hosts one of the country's most-listened-to morning radio programs.", "year_label": "2017-present"},
        ],
        "day_in_the_life": "Early morning show preparation, live broadcasting, and post-show planning for upcoming segments.",
        "weekly_routine": "Very early mornings define the schedule, with show preparation happening the evening before.",
        "biggest_challenges": ["The real, permanent risk of a single on-air mistake going viral", "The physically demanding early morning schedule"],
        "favourite_part": "A live moment of genuine, unscripted connection with listeners that couldn't be planned.",
        "biggest_misconceptions": ["That radio is a dying medium irrelevant in the streaming era", "That one public professional failure permanently ends a media career"],
        "what_surprised_them": "How much careful judgment live broadcasting requires in split-second moments, unlike pre-recorded media.",
        "biggest_mistake": "The comment that got me fired came from not pausing to think before speaking during a live, unscripted moment — I let momentum and a desire to be entertaining override my judgment. That single moment cost me a year of my career, and I now deliberately build in more careful judgment before every live, spontaneous moment.",
        "one_regret": "I regret how close I came to leaving broadcasting entirely during that difficult year — I nearly gave up on a career I genuinely loved because of one bad moment.",
        "salary_reality": "Successful radio hosting in Ghana can be genuinely lucrative, though the early years, especially after a setback like mine, involved real financial instability.",
        "work_life_balance": "The early morning schedule genuinely disrupts normal sleep and social patterns, a real, ongoing tradeoff of the role.",
        "daily_skills": ["live broadcasting", "improvisation", "audience engagement"],
        "daily_tools": ["Broadcasting equipment", "show production software"],
        "recommended_books": ["Talk Radio by Michael Harrison"],
        "recommended_communities": ["Ghana broadcasters association"],
        "advice_for_beginners": "Pause before speaking in unscripted live moments, even when the pressure is to be quick and entertaining — the mistake that cost me a year came from not doing exactly that.",
        "advice_for_parents": "A public professional failure, even one that costs a job, is genuinely recoverable with real reflection and persistence — it doesn't have to define a career permanently.",
        "faqs": [{"question": "Can you recover from being publicly fired for an on-air mistake?", "answer": "Yes — it takes real humility and time, but many successful broadcasters, myself included, have setbacks like this in their history."}],
        "projects": [], "research": [], "certifications": [],
        "conferences": [], "organizations": ["Ghana broadcasters association"],
        "volunteer_work": ["Mentors young broadcasters on on-air judgment and professionalism"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch9).")


if __name__ == "__main__":
    asyncio.run(seed())
