"""Journey Stories, redefined — student/young-person self-discovery
narratives (Expert Connect / Journey Stories purpose split). Every entry
is `story_type="composite_student_discovery"`: an illustrative composite
built from common exploration patterns, never a claim of a specific real
individual, and never presented as a verified real student. This is
explicitly NOT professional-success storytelling (that stays on the
career detail page's "Human Stories", `story_type="composite"`) — every
story here centers uncertainty, exploration, and self-discovery rather
than an already-built career.

`discovery_themes` are only ever applied when a story genuinely
demonstrates that pattern — "do not create empty filters" holds by
construction, since the standalone Journey Stories screen only exposes
themes that appear on at least one real row here.

Run via: python -m aureon.scripts.seed_student_discovery_stories
Idempotent: safe to re-run (upsert on id).
"""

import asyncio

from aureon.domain.models.career import CareerStory
from aureon.services.supabase.client import get_supabase_client

STORIES: list[dict] = [
    {
        "id": "student_story_ux_researcher_1", "career_id": "ux_researcher",
        "person_label": "Second-Year Computer Science Student",
        "background": "Chose computer science because everyone around them said technology had the best job prospects, without much thought beyond that.",
        "journey": "Struggled through the first year's coding-heavy courses, then took a required human-computer-interaction elective almost by accident — and realized understanding *why* people struggled with software interested them far more than writing the software itself.",
        "challenges": "Spent months confused about whether disliking pure coding meant they'd chosen the wrong major entirely, or just the wrong part of a broad field.",
        "turning_points": "A small class project interviewing real users about a confusing app made clear that the 'research' half of the work, not the 'engineering' half, was what pulled their attention.",
        "advice": "Struggling with one part of a field doesn't mean the whole field is wrong for you — it might mean there's a different part of it you haven't found yet.",
        "lessons_learned": "Curiosity about people can live inside a technical field without requiring you to be the strongest coder in the room.",
        "trait_tags": ["curiosity", "empathy", "analytical_thinking"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Most of first year, genuinely unsure whether disliking core coursework meant a wrong major choice.",
        "current_outcome": "Now pursuing a UX research specialization within the same degree, without having to start over.",
        "industry": "technology & design",
        "discovery_themes": ["changed_my_mind", "found_my_passion", "interdisciplinary_path"],
    },
    {
        "id": "student_story_conservation_biologist_1", "career_id": "conservation_biologist",
        "person_label": "High School Senior",
        "background": "Grew up loving nature documentaries and keeping a small backyard garden, but only ever heard 'doctor' or 'engineer' mentioned as real career paths at school.",
        "journey": "During a school career fair, a single booth about environmental conservation work was the first time they'd heard it described as an actual, paid profession rather than volunteer work.",
        "challenges": "Had no idea what the day-to-day of the field even looked like, or what to study to get there, since no one in their family or school network had ever worked in it.",
        "turning_points": "Reaching out to the career fair volunteer directly and asking blunt, specific questions about the actual job — not just the mission — turned a vague interest into a real, researchable path.",
        "advice": "If you've never heard of a career, that usually means you haven't been shown it yet — not that it doesn't exist.",
        "lessons_learned": "The careers you know about by default are shaped entirely by who happens to be around you, not by what actually exists.",
        "trait_tags": ["curiosity", "nature", "patience"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Applying to university programs in environmental science, now able to name the specific field they're aiming for.",
        "industry": "environmental conservation",
        "discovery_themes": ["missing_world_discovery", "unexpected_career", "found_my_passion"],
    },
    {
        "id": "student_story_genomics_data_scientist_1", "career_id": "genomics_data_scientist",
        "person_label": "Third-Year Student, Switched Majors Once",
        "background": "Was consistently the strongest math student in every class growing up, and every adult around them treated that as proof they should study engineering.",
        "journey": "Started an engineering degree out of that expectation, but a genetics elective — taken only to fill a requirement — showed a completely different application for the same underlying math skills.",
        "challenges": "Felt genuine pressure switching away from engineering, since being 'good at math' had always been narrated as leading to exactly one kind of career.",
        "turning_points": "Realizing that a strength like mathematical reasoning isn't owned by any single field — it was just as real and useful inside genomics as it would have been in engineering.",
        "advice": "Being good at a subject is evidence you can succeed in many different careers, not proof that one specific career is 'yours.'",
        "lessons_learned": "A strength is a tool you carry with you, not a fixed destination.",
        "trait_tags": ["analytical_thinking", "curiosity", "persistence"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "A full semester weighing whether switching away from the 'expected' engineering path was a mistake.",
        "current_outcome": "Now in a genomics-focused data science track, using the same mathematical strengths in a field they hadn't known existed a year earlier.",
        "industry": "biotechnology",
        "discovery_themes": ["hidden_strength", "interdisciplinary_path", "stem_path"],
    },
    {
        "id": "student_story_civil_engineer_1", "career_id": "civil_engineer",
        "person_label": "Gap-Year Student",
        "background": "Spent two years preparing specifically for a medical career, following a plan set early in high school that never really got questioned.",
        "journey": "A summer volunteering on a community infrastructure project — helping rebuild a bridge after flooding — was the first hands-on experience that felt more genuinely engaging than any of the medical-track preparation had.",
        "challenges": "Changing direction after two years of visible, public preparation for medicine felt like admitting failure, especially to family who had already told others about the plan.",
        "turning_points": "A conversation with a civil engineer on the project, who described exactly what had pulled them into the field, mirrored the volunteer's own experience closely enough to take the shift seriously.",
        "advice": "Two years spent preparing for one direction is not two years wasted — it's real evidence about what does and doesn't hold your attention.",
        "lessons_learned": "Changing your mind after real experience is a sign the exploration is working, not a sign of failure.",
        "trait_tags": ["hands_on", "problem_solving", "community"],
        "career_switch": True, "gap_year": True,
        "uncertainty_period": "The months after the volunteer project, unsure whether to abandon two years of medical-track preparation.",
        "current_outcome": "Enrolled in a civil engineering program, having redirected two years of discipline rather than losing it.",
        "industry": "engineering & construction",
        "discovery_themes": ["changed_my_mind", "still_figuring_it_out", "gap_year"],
    },
    {
        "id": "student_story_teacher_k12_1", "career_id": "teacher_k12",
        "person_label": "First-Generation University Student",
        "background": "Came from a family that saw becoming a doctor or engineer as the only real markers of a degree being 'worth it,' especially as the first in the family to attend university.",
        "journey": "Took a part-time tutoring job for younger students purely for the income, and found themself looking forward to it more than any of their actual coursework.",
        "challenges": "Worried that choosing teaching would look like underachieving relative to what their family had sacrificed for their education.",
        "turning_points": "A tutoring student's parent thanking them for a breakthrough moment made the value of the work impossible to keep dismissing, regardless of how it might look on paper.",
        "advice": "A path chosen to make family proud isn't the same as a path that will actually let you show up fully for years — both are worth taking seriously.",
        "lessons_learned": "Respecting a family's sacrifice and choosing your own direction aren't actually opposites.",
        "trait_tags": ["patience", "communication", "mentorship"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Ongoing tension, not fully resolved, between family expectations and a growing personal certainty about teaching.",
        "current_outcome": "Pursuing a teaching credential alongside their original degree, still working through the conversation with family.",
        "industry": "education",
        "discovery_themes": ["parent_expectations", "found_my_passion", "still_figuring_it_out"],
    },
    {
        "id": "student_story_craft_master_1", "career_id": "japan_traditional_craft_master",
        "person_label": "University Dropout, Now Apprenticing",
        "background": "Enrolled in a business degree mostly because it seemed like the safe, flexible option when nothing else stood out.",
        "journey": "Left university after a year and a half, and spent months doing short-term work before a chance visit to a traditional craft workshop turned into an informal apprenticeship offer.",
        "challenges": "Leaving a degree program was treated by almost everyone around them as a serious mistake, with little language available for 'not finishing' as anything other than failure.",
        "turning_points": "The first object they made with their own hands that was genuinely good, not just acceptable, was the first moment the apprenticeship felt like a real direction rather than a stopgap.",
        "advice": "A traditional, well-worn path isn't automatically the safe one if it doesn't hold your attention — and an unconventional path isn't automatically reckless.",
        "lessons_learned": "Skill built slowly with your hands can be just as real a career foundation as a degree, even when it doesn't look like one at first.",
        "trait_tags": ["hands_on", "patience", "craftsmanship"],
        "career_switch": True, "gap_year": True,
        "uncertainty_period": "Roughly a year of short-term, undirected work between leaving university and finding the apprenticeship.",
        "current_outcome": "Several years into a formal apprenticeship, on a path with no direct equivalent to the degree they left.",
        "industry": "traditional craftsmanship",
        "discovery_themes": ["non_traditional_path", "vocational_path", "found_my_passion", "gap_year"],
    },
    {
        "id": "student_story_dev_rel_1", "career_id": "developer_relations_engineer",
        "person_label": "Computer Science Student, Runs a Tech Blog",
        "background": "Studied computer science and separately, unrelated to any coursework, kept a personal blog explaining programming concepts they'd struggled to learn themselves.",
        "journey": "Assumed for years that the blog was just a hobby, until a post explaining a confusing library got shared widely and the library's own maintainers reached out to thank them.",
        "challenges": "Had never considered that writing *about* code could be a career distinct from writing the code itself, since no one around them talked about that kind of role.",
        "turning_points": "Realizing that developer relations roles exist specifically for people who can do both — explain technical things clearly and actually build them — connected two things they'd never thought to combine.",
        "advice": "A hobby that keeps pulling your attention outside of your 'real' work is worth investigating as a career, not dismissing as a distraction.",
        "lessons_learned": "Two separate interests you've never connected might actually be describing one real job.",
        "trait_tags": ["communication", "curiosity", "technical_writing"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Interning in a developer relations role, treating the blog as real career evidence rather than a side project.",
        "industry": "technology",
        "discovery_themes": ["interdisciplinary_path", "creative_path", "found_my_passion", "hidden_strength"],
    },
    {
        "id": "student_story_foreign_service_1", "career_id": "foreign_service_officer",
        "person_label": "Exchange Student, Studied Abroad Twice",
        "background": "Started university intending to study literature, with no particular career direction attached to the choice.",
        "journey": "Two separate study-abroad experiences, in very different countries, left them consistently more interested in how the countries' policies and institutions worked than in the literature courses that had brought them there.",
        "challenges": "Struggled to explain to advisors what they actually wanted, since 'interested in how other countries work' didn't map onto any single existing major.",
        "turning_points": "A professor pointed out, almost offhand, that the pattern across both trips sounded a lot like an interest in diplomacy or international relations — a field the student hadn't previously had a name for.",
        "advice": "Sometimes the direction is obvious to someone watching from outside long before it's obvious to you.",
        "lessons_learned": "A repeated pattern across unrelated experiences is real data about what you care about, even before you have a name for it.",
        "trait_tags": ["curiosity", "cultural_awareness", "communication"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "A year of not having language for what they wanted, despite a clear repeated pattern in what engaged them.",
        "current_outcome": "Added an international relations minor and is now preparing for foreign service entrance exams.",
        "industry": "diplomacy & international relations",
        "discovery_themes": ["unexpected_career", "changed_my_mind", "interdisciplinary_path"],
    },
    {
        "id": "student_story_human_rights_1", "career_id": "human_rights_researcher",
        "person_label": "Undergraduate, Started in Pre-Law",
        "background": "Entered university on a pre-law track, mostly because a legal career had always been described at home as a stable, respected path.",
        "journey": "A single elective course on international human rights law, taken to satisfy a requirement, ended up mattering more to them than any of the pre-law core courses.",
        "challenges": "Worried that being drawn to research and advocacy rather than courtroom law meant abandoning the 'law' identity they'd built their plans around.",
        "turning_points": "Realizing that human rights research was still fundamentally connected to law and justice — just applied differently than the courtroom image they'd started with.",
        "advice": "Finding a more specific, less obvious version of a broad field you're already drawn to isn't a rejection of that field.",
        "lessons_learned": "A field can hold more than one legitimate way to work within it.",
        "trait_tags": ["justice", "research", "empathy"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Shifted focus within the same broad interest in law toward human rights research specifically.",
        "industry": "human rights advocacy",
        "discovery_themes": ["found_my_passion", "life_mission", "interdisciplinary_path"],
    },
    {
        "id": "student_story_startup_founder_1", "career_id": "startup_founder",
        "person_label": "Recent Graduate, Turned Down a Corporate Offer",
        "background": "Spent their entire degree assuming the goal was a stable job at a large, well-known company — the kind of offer that would make the years of study feel validated.",
        "journey": "Received exactly that offer in their final year, and instead of relief, felt a specific dread about the day-to-day routine it implied, based on internship experience at a similar company.",
        "challenges": "Turning down a 'good' offer that everyone around them saw as an obvious success was difficult to explain, since nothing was visibly wrong with it.",
        "turning_points": "A small side project — building a tool for a problem a friend's small business had — got real, unprompted use, and was more energizing in a weekend than the entire internship had been.",
        "advice": "An offer that looks correct on paper isn't the same as an offer that will actually hold your attention for years.",
        "lessons_learned": "Dread about a specific, concrete future is worth listening to, even when the alternative is unclear.",
        "trait_tags": ["motivation", "independence", "risk_tolerance"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Several tense months turning down a secured offer with no equally secure alternative lined up.",
        "current_outcome": "Building the side project into an early-stage company, without the safety net the corporate offer would have provided.",
        "industry": "entrepreneurship",
        "discovery_themes": ["changed_my_mind", "unexpected_career", "found_my_passion"],
    },
    {
        "id": "student_story_urban_planner_1", "career_id": "urban_planner",
        "person_label": "Gap-Year Student, Worked Odd Jobs",
        "background": "Finished secondary school with genuinely no idea what to study, and took a gap year mostly to avoid making a decision under pressure.",
        "journey": "Took a temporary job assisting a local city planning office, chosen only because it was hiring, and found themself unexpectedly fascinated by decisions about how streets, parks, and housing actually get planned.",
        "challenges": "Had never considered urban planning a real field of study, and felt behind starting to research it only after a gap year most peers hadn't taken.",
        "turning_points": "Sitting in on a public planning meeting and watching a specific proposal change based on real resident feedback made the abstract job suddenly concrete and appealing.",
        "advice": "A gap year spent trying things, even by accident, is doing exactly what it's supposed to do.",
        "lessons_learned": "Direction can come from a job you took for practical reasons, not just from careful planning.",
        "trait_tags": ["systems_thinking", "community", "curiosity"],
        "career_switch": False, "gap_year": True,
        "uncertainty_period": "The full gap year, spent without a clear plan before the planning-office job began.",
        "current_outcome": "Applying to urban planning programs, using the gap-year job directly as the reason in application essays.",
        "industry": "urban development",
        "discovery_themes": ["gap_year", "found_my_passion", "still_figuring_it_out"],
    },
    {
        "id": "student_story_ai_ops_1", "career_id": "ai_ops_specialist",
        "person_label": "Student Club Treasurer",
        "background": "Never thought of themself as particularly technical, and assumed their strength was just 'being organized,' which didn't feel like it pointed toward any specific career.",
        "journey": "Volunteering to manage logistics for a university AI/ML club — not to study the technical material itself — put them in constant contact with the operational side of how machine learning systems actually get deployed and maintained.",
        "challenges": "Dismissed the operational role as 'just admin work' for a long time, assuming the real career value was in the technical modeling work happening around them.",
        "turning_points": "A guest speaker described AI operations as its own real specialization, one that specifically needs people who are strong at exactly the organizational, process-oriented thinking the student had been undervaluing in themself.",
        "advice": "Being 'the organized one' in a technical group is a real, specific skill — not a consolation role.",
        "lessons_learned": "A strength that doesn't look glamorous can still be the exact thing a field is short on.",
        "trait_tags": ["organization", "reliability", "systems_thinking"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Pursuing an AI operations specialization, having reframed 'organized' as a real technical strength.",
        "industry": "technology",
        "discovery_themes": ["hidden_strength", "stem_path", "found_my_passion"],
    },
    {
        "id": "student_story_clinical_research_1", "career_id": "clinical_research_coordinator",
        "person_label": "Pre-Med Student, Two Years In",
        "background": "Had wanted to become a physician for as long as they could remember, without ever really questioning the assumption.",
        "journey": "A summer volunteering in a hospital, meant to confirm the plan, instead revealed that the parts of medicine they found most engaging were the clinical trials happening alongside patient care, not the patient care itself.",
        "challenges": "Questioning a career goal held since childhood felt like losing part of their own identity, not just changing a plan.",
        "turning_points": "Talking to a clinical research coordinator who explained the role — sitting at the intersection of medicine and research, without the same path to being a treating physician — named exactly what had been pulling their interest.",
        "advice": "A career goal you've held for a long time deserves real testing through direct experience, not just continued assumption.",
        "lessons_learned": "Admiring a field doesn't mean only one specific role within it is right for you.",
        "trait_tags": ["research", "empathy", "attention_to_detail"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Ongoing, weighing whether to continue toward medical school or pivot fully toward clinical research.",
        "current_outcome": "Still enrolled pre-med, but now also seeking clinical research assistant positions to test the alternative directly.",
        "industry": "healthcare research",
        "discovery_themes": ["changed_my_mind", "still_figuring_it_out"],
    },
    {
        "id": "student_story_computational_linguist_1", "career_id": "computational_linguist",
        "person_label": "Bilingual Student, Studied Two Unrelated Majors",
        "background": "Grew up speaking two languages at home and separately became interested in programming through a school elective, treating the two as completely unconnected parts of their life.",
        "journey": "A university course on natural language processing was the first time either interest showed up inside the other, revealing an entire field built on combining exactly the two things they'd never thought to connect.",
        "challenges": "Had structured their coursework around two separate majors for over a year before realizing a combined path existed.",
        "turning_points": "Building a small project analyzing text in both of their languages made the overlap concrete instead of theoretical.",
        "advice": "Two interests that feel unrelated are worth mentioning to someone in either field — the connection between them might already be a real career.",
        "lessons_learned": "Not every interest needs its own separate box; some of the most specific career fits come from where two boxes overlap.",
        "trait_tags": ["languages", "analytical_thinking", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Restructured their coursework around a formal computational linguistics track.",
        "industry": "technology & language",
        "discovery_themes": ["interdisciplinary_path", "found_my_passion", "unexpected_career"],
    },
    {
        "id": "student_story_materials_science_1", "career_id": "materials_research_scientist",
        "person_label": "Art Student, Took One Science Elective",
        "background": "Spent years focused on ceramics and sculpture, with science treated as an unrelated, mostly avoided subject.",
        "journey": "A required general-science elective on materials properties, taken reluctantly, connected directly to questions they'd been asking for years about why certain clays and glazes behaved the way they did in the kiln.",
        "challenges": "Had built a strong identity around being 'an art person, not a science person,' making it genuinely disorienting to find real curiosity on the science side.",
        "turning_points": "Realizing that materials science was, in a real sense, the same underlying curiosity about material behavior that had drawn them to ceramics in the first place — just studied more formally.",
        "advice": "The labels 'art person' or 'science person' are usually less true than they feel — the same curiosity often shows up in both places.",
        "lessons_learned": "An identity built early doesn't have to limit which subjects are actually available to you later.",
        "trait_tags": ["curiosity", "hands_on", "creativity"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "A semester of genuine identity confusion after years of self-describing as 'not a science person.'",
        "current_outcome": "Added a materials science minor alongside their studio art major, connecting both formally.",
        "industry": "manufacturing & research",
        "discovery_themes": ["unexpected_career", "interdisciplinary_path", "creative_path", "stem_path"],
    },
    {
        "id": "student_story_public_health_policy_1", "career_id": "public_health_policy_analyst",
        "person_label": "Second-Generation Medical Family",
        "background": "Both parents were physicians, and medicine was treated as the default, unquestioned expectation for their own path.",
        "journey": "A public health elective, taken almost as an afterthought, showed a way to work on healthcare's biggest problems at a population level rather than one patient at a time — closer to what actually interested them than clinical practice.",
        "challenges": "Explaining the distinction between 'public health policy' and 'medicine' to a family where medicine was the only healthcare career anyone had modeled took real, repeated conversations.",
        "turning_points": "Showing their parents a specific policy analysis project, and watching them recognize real rigor in it despite it not being clinical work, shifted the conversation from resistance to support.",
        "advice": "Family expectations are often about a value — like 'help people's health' — more specifically than about one exact job title; naming the shared value can open the conversation.",
        "lessons_learned": "You can honor what a family actually cares about without taking the exact path they assumed.",
        "trait_tags": ["analytical_thinking", "justice", "communication"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Months of difficult conversations before the family fully understood the alternative path.",
        "current_outcome": "Studying public health policy, with family support secured through direct, specific conversations rather than assumption.",
        "industry": "public health & policy",
        "discovery_themes": ["parent_expectations", "found_my_passion", "unexpected_career"],
    },
    {
        "id": "student_story_ngo_program_manager_1", "career_id": "ngo_program_manager",
        "person_label": "Gap-Year Volunteer Abroad",
        "background": "Took a gap year originally just to save money before university, with no specific plan for how to spend the time.",
        "journey": "A short-term volunteer placement with an international NGO, meant to be a brief experience, turned into an extended stay after being asked to help coordinate a specific program.",
        "challenges": "Coming home to apply to university, it was difficult to explain how a 'gap year volunteer trip' had turned into something closer to real work experience.",
        "turning_points": "Being handed real responsibility for part of a program, and seeing it succeed, was the first time the work felt like a career rather than a temporary trip.",
        "advice": "A gap year built around service, not just travel, can turn into something closer to real professional experience than expected.",
        "lessons_learned": "Responsibility given early, even informally, can reveal a career direction faster than years of academic planning.",
        "trait_tags": ["community", "adaptability", "organization"],
        "career_switch": False, "gap_year": True,
        "uncertainty_period": "",
        "current_outcome": "Applying to university programs in international development, citing the gap-year program work directly.",
        "industry": "international development",
        "discovery_themes": ["gap_year", "non_traditional_path", "life_mission", "found_my_passion"],
    },
    {
        "id": "student_story_sustainability_analyst_1", "career_id": "sustainability_analyst",
        "person_label": "Business Student, Cared About Climate Separately",
        "background": "Studied business because it felt practical, while treating a personal concern about climate change as a completely separate, unrelated part of their life.",
        "journey": "A guest lecture on corporate sustainability roles was the first time they realized companies actively hire people specifically to work on exactly the environmental questions they cared about — not as a side project, but as a real, salaried function.",
        "challenges": "Had assumed 'caring about climate change' and 'studying business' belonged to two different, incompatible versions of their future.",
        "turning_points": "Researching the guest lecturer's actual job responsibilities in detail showed a real, specific role sitting exactly at the intersection they hadn't known existed.",
        "advice": "A personal value and a practical major aren't automatically in conflict — sometimes there's a real job built exactly where they meet.",
        "lessons_learned": "Not knowing a career combination exists is different from that combination not existing.",
        "trait_tags": ["values_driven", "analytical_thinking", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Pursuing a sustainability-focused concentration within their existing business degree.",
        "industry": "corporate sustainability",
        "discovery_themes": ["missing_world_discovery", "unexpected_career", "life_mission"],
    },
    {
        "id": "student_story_bioinformatics_1", "career_id": "bioinformatics_scientist",
        "person_label": "Biology Major, Reluctant Coder",
        "background": "Chose biology specifically to avoid programming, having found an introductory coding class frustrating in secondary school.",
        "journey": "A required data-analysis course in their biology degree forced them back into code, this time applied directly to real genetic datasets they already cared about — a very different experience than the abstract exercises that had frustrated them before.",
        "challenges": "Had written off programming entirely based on one difficult early experience, without separating 'coding is hard in the abstract' from 'coding is hard when disconnected from anything I care about.'",
        "turning_points": "Successfully debugging a script that revealed a real pattern in genetic data was the first time code felt like a tool for something, not an end in itself.",
        "advice": "One bad early experience with a skill, especially taught in the abstract, isn't reliable evidence about how you'll feel about that skill applied to something you actually care about.",
        "lessons_learned": "Context can completely change your relationship with a skill you thought you'd ruled out.",
        "trait_tags": ["persistence", "analytical_thinking", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Now deliberately combining biology and computation, the exact pairing they'd once tried to avoid.",
        "industry": "biotechnology",
        "discovery_themes": ["changed_my_mind", "interdisciplinary_path", "stem_path"],
    },
    {
        "id": "student_story_physician_general_1", "career_id": "physician_general",
        "person_label": "Pre-Med Student, Explored Three Specialties",
        "background": "Entered pre-med certain about becoming a doctor, but with no real sense of which kind — assuming that decision could wait until much later.",
        "journey": "Shadowing experiences across a surgeon, a specialist, and a general practitioner showed three genuinely different day-to-day realities, and it was the least 'prestigious' of the three — general practice — that actually felt right.",
        "challenges": "Felt pressure, mostly self-imposed, that choosing general practice over a subspecialty represented settling for less than they were capable of.",
        "turning_points": "Watching the general practitioner build a long-term relationship with a patient across multiple visits — something the other two specialties didn't offer in the same way — clarified what actually mattered to them.",
        "advice": "The most prestigious option inside a field you admire isn't automatically the right one for you specifically.",
        "lessons_learned": "Trying on different versions of a broad career goal before committing can prevent years of chasing prestige over fit.",
        "trait_tags": ["empathy", "communication", "patience"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Committed to a general practice track after directly comparing three specialties through shadowing.",
        "industry": "healthcare",
        "discovery_themes": ["still_figuring_it_out", "found_my_passion"],
    },
    {
        "id": "student_story_neuroscience_1", "career_id": "neuroscience_postdoc",
        "person_label": "Undergraduate Research Assistant",
        "background": "Assumed research careers required a kind of instant brilliance they didn't feel they had, and avoided pursuing research seriously for most of their degree.",
        "journey": "A part-time research assistant role, taken mainly for the pay, put them through months of slow, repetitive data collection before any real result appeared — and they discovered they could tolerate that slowness better than most of their peers.",
        "challenges": "Nearly quit twice during the most repetitive stretches, assuming their frustration meant research wasn't for them.",
        "turning_points": "A supervisor pointed out that the specific trait keeping them going through the tedium — real patience with slow, uncertain progress — is exactly what separates people who finish research careers from people who don't.",
        "advice": "The daily reality of a field is often less glamorous than its reputation — and your fit for that daily reality matters more than whether you feel 'brilliant.'",
        "lessons_learned": "Patience with tedium is a real, valuable research skill, not a sign you're in the wrong field.",
        "trait_tags": ["patience", "persistence", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Two separate points during the assistantship where quitting research entirely felt like the right call.",
        "current_outcome": "Pursuing graduate research in neuroscience, having reframed patience with tedium as a genuine strength.",
        "industry": "academic research",
        "discovery_themes": ["hidden_strength", "stem_path", "still_figuring_it_out"],
    },
    {
        "id": "student_story_space_systems_1", "career_id": "space_systems_engineer",
        "person_label": "Robotics Club Member",
        "background": "Joined a general robotics club in secondary school mostly for the social aspect, with no strong interest in any specific engineering discipline yet.",
        "journey": "A club project building a small satellite-simulation module was the first specific engineering task that fully absorbed their attention for hours without noticing the time pass.",
        "challenges": "Had tried several other club projects before this one without feeling the same pull, and worried the earlier lack of interest meant engineering broadly wasn't for them.",
        "turning_points": "Comparing how differently they felt during the satellite project versus the earlier ones made clear the issue had never been engineering itself, just which specific application of it.",
        "advice": "If a broad field feels wrong, try a genuinely different specific project inside it before ruling the whole field out.",
        "lessons_learned": "'I don't like this field' is sometimes really 'I haven't found the right part of this field yet.'",
        "trait_tags": ["hands_on", "problem_solving", "focus"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Applying to aerospace engineering programs specifically, after ruling out other engineering disciplines through direct comparison.",
        "industry": "aerospace",
        "discovery_themes": ["found_my_passion", "stem_path"],
    },
    {
        "id": "student_story_accountant_1", "career_id": "accountant",
        "person_label": "Business Student, Dismissed a 'Boring' Career",
        "background": "Had always assumed accounting was a boring, purely technical fallback option, choosing a broader business major specifically to avoid narrowing into it.",
        "journey": "A required introductory accounting course, taken reluctantly, turned out to appeal directly to a long-standing personal preference for clear rules, precision, and things that either balance or don't.",
        "challenges": "Felt embarrassed admitting an interest in a field they and their peers had casually mocked as boring for years.",
        "turning_points": "Recognizing that the specific satisfaction of a fully reconciled ledger was the same feeling they got from any well-solved precise problem — not a lesser interest, just an unfashionable one.",
        "advice": "A career other people call boring might be precisely engaging to you if it matches how your mind actually likes to work.",
        "lessons_learned": "A field's reputation among peers has nothing to do with whether it will genuinely suit you.",
        "trait_tags": ["precision", "reliability", "analytical_thinking"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Pursuing an accounting concentration, no longer avoiding it to seem more interesting to peers.",
        "industry": "finance",
        "discovery_themes": ["found_my_passion", "vocational_path", "hidden_strength"],
    },
    {
        "id": "student_story_ias_officer_1", "career_id": "ias_officer_india",
        "person_label": "Multi-Year Exam Preparation Student",
        "background": "Came from a family with a strong, explicit expectation of public service through the civil services, treated as the single most respected path available.",
        "journey": "Years of exam preparation gave real time to sit with the expectation itself, and rather than resenting it, a genuine personal sense of purpose around public administration grew alongside the inherited one.",
        "challenges": "Spent a long stretch unsure whether their motivation was genuinely their own or simply inherited from family pressure, and being unable to tell the difference was its own source of doubt.",
        "turning_points": "A specific local governance internship during preparation, where they helped resolve a real community issue, produced a sense of purpose that felt clearly their own rather than borrowed.",
        "advice": "An expectation you were handed can still turn into something genuinely yours — the key is testing it against real experience, not just inheriting it untested.",
        "lessons_learned": "It's possible for family expectation and authentic personal purpose to end up pointing at the same place.",
        "trait_tags": ["public_service", "persistence", "justice"],
        "career_switch": False, "gap_year": True,
        "uncertainty_period": "Years of preparation spent genuinely unsure whether the goal was authentically their own.",
        "current_outcome": "Continuing exam preparation with a personal sense of purpose now distinct from, though aligned with, family expectation.",
        "industry": "public administration",
        "discovery_themes": ["parent_expectations", "life_mission", "gap_year"],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    # Set uniformly here rather than repeated 24 times in the literal
    # list above — every row in this file is this exact type, by
    # definition of what this script seeds.
    stories = [CareerStory.model_validate({**s, "story_type": "composite_student_discovery"}) for s in STORIES]

    def _upsert() -> None:
        client.table("career_stories").upsert(
            [s.model_dump(mode="json") for s in stories]
        ).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(stories)} student discovery Journey Stories.")


if __name__ == "__main__":
    asyncio.run(seed())
