"""Connect Batch 1 — Expert Connect seed data, tenth wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch10
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_dietitian_valentina_rossi",
        "name": "Valentina Rossi, Clinical Dietitian",
        "role_type": "industry_professional", "field": "nutrition", "bio": "Works with patients managing diabetes and metabolic conditions through nutrition; her own struggle with disordered eating in her twenties shaped her clinical philosophy.",
        "trait_tags": ["empathy", "analytical_thinking"], "learning_style_fit": "Students interested in the science of nutrition combined with real behavioral change work.",
        "organization": "A hospital metabolic health clinic", "years_experience": 9, "journey_highlights": ["Struggled with disordered eating in her own twenties", "Built a nutrition program that measurably improved diabetes management for hundreds of patients"],
        "discussion_topics": ["Bringing a personal health struggle into clinical work responsibly", "Nutrition science versus diet culture", "Dietetics as a clinical, evidence-based career"],
        "profession": "Clinical Dietitian", "specialization": "Diabetes and metabolic nutrition", "country": "Italy", "city": "Milan",
        "industries": ["healthcare", "nutrition"], "education": ["BSc Nutrition Science, University of Milan", "Clinical dietetics certification"],
        "current_role": "Senior Clinical Dietitian", "languages": ["Italian", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students interested in nutrition as clinical science, not diet culture", "Students with their own history of disordered eating considering the field", "Students who want to help people with chronic conditions like diabetes"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "school", "label": "Struggled with disordered eating during her later teenage years", "description": "Developed an unhealthy relationship with food that took years to fully recover from.", "year_label": "2004-2008"},
            {"stage": "university", "label": "BSc Nutrition Science", "description": "Chose the field specifically to understand her own past struggle scientifically.", "year_label": "2009-2013"},
            {"stage": "first_job", "label": "Junior dietitian", "description": "Learned to separate her personal history from clinical objectivity with patients.", "year_label": "2013-2017"},
            {"stage": "current_role", "label": "Senior Clinical Dietitian", "description": "Built a nutrition program that measurably improved diabetes management outcomes for hundreds of patients.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "Patient consultations developing individualized nutrition plans, combined with ongoing monitoring of clinical outcomes.",
        "weekly_routine": "Clinical appointments throughout the week, with periodic program development and outcomes review.",
        "biggest_challenges": ["Helping patients make sustainable changes amid conflicting, often unscientific diet information online", "Keeping her own history from over-influencing clinical objectivity"],
        "favourite_part": "A patient's lab results showing genuine, measurable improvement after sustained nutrition changes.",
        "biggest_misconceptions": ["That dietitians just tell people to eat less", "That a personal history with disordered eating disqualifies someone from nutrition work"],
        "what_surprised_them": "How much of the job is behavioral psychology, not just nutrition science.",
        "biggest_mistake": "Early in my career, I let my own past struggle with restriction subtly influence how I approached a patient's weight management plan, being overly cautious about calorie guidance in a way that wasn't actually evidence-based for that patient's needs. I learned to actively separate my personal history from clinical decision-making through supervision and ongoing self-reflection.",
        "one_regret": "I regret not addressing my own relationship with food more fully before starting clinical practice — it took real, ongoing work to ensure it strengthened rather than clouded my clinical judgment.",
        "salary_reality": "Clinical dietetics pays reasonably within Italy's healthcare system, though it's not among the highest-paid healthcare specialties.",
        "work_life_balance": "Generally steady clinical hours without emergency demands.",
        "daily_skills": ["nutrition science", "behavioral counseling", "clinical assessment"],
        "daily_tools": ["Nutrition analysis software", "clinical assessment tools"],
        "recommended_books": ["Intuitive Eating by Evelyn Tribole and Elyse Resch"],
        "recommended_communities": ["Italian Association of Dietitians"],
        "advice_for_beginners": "If you have your own history with food struggles, work through it with real support before bringing it into clinical practice — it can become a strength, but only with genuine self-awareness.",
        "advice_for_parents": "A personal history with disordered eating, once genuinely processed, can become a real clinical asset in nutrition work, not a disqualifying factor.",
        "faqs": [{"question": "Can someone with a history of disordered eating become a dietitian?", "answer": "Yes, with genuine recovery and self-awareness — many excellent clinical dietitians, myself included, bring valuable personal insight to the work."}],
        "projects": ["Built a nutrition program improving diabetes management for hundreds of patients"], "research": [],
        "certifications": ["Registered Dietitian, Italy"], "conferences": [], "organizations": ["Italian Association of Dietitians"],
        "volunteer_work": ["Speaks at schools about the difference between diet culture and real nutrition science"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_midwife_adaeze_nwosu",
        "name": "Adaeze Nwosu, Midwife",
        "role_type": "industry_professional", "field": "midwifery", "bio": "Attends births at a maternity clinic; a difficult delivery early in her career that required emergency transfer shaped her entire approach to risk assessment.",
        "trait_tags": ["empathy", "persistence"], "learning_style_fit": "Students interested in maternal healthcare and hands-on clinical work with real, immediate stakes.",
        "organization": "A community maternity clinic", "years_experience": 12, "journey_highlights": ["A difficult early delivery required an emergency hospital transfer", "Has since safely attended over 800 births"],
        "discussion_topics": ["Handling a birth complication that required emergency intervention", "Midwifery versus obstetric nursing as career paths", "What makes a birth genuinely safe"],
        "profession": "Certified Midwife", "specialization": "Low-risk community births", "country": "Nigeria", "city": "Enugu",
        "industries": ["healthcare"], "education": ["BSc Midwifery, University of Nigeria Nsukka"],
        "current_role": "Senior Midwife", "languages": ["English", "Igbo"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students interested in maternal healthcare specifically", "Students who've faced a frightening moment early in a clinical career", "Students weighing midwifery against obstetric medicine"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "university", "label": "BSc Midwifery", "description": "Drawn to the field after supporting her own sister through a difficult pregnancy.", "year_label": "2008-2012"},
            {"stage": "first_job", "label": "Junior midwife", "description": "Attended straightforward, low-risk births under supervision.", "year_label": "2012-2014"},
            {"stage": "failure", "label": "A delivery she was attending developed a serious complication requiring emergency hospital transfer", "description": "The mother and baby were ultimately safe, but the frightening experience shook her confidence in her own risk assessment badly.", "year_label": "2014"},
            {"stage": "turning_point", "label": "Pursued additional training in risk assessment and emergency obstetric protocols", "description": "Rebuilt her confidence through deliberate additional education rather than avoidance.", "year_label": "2015"},
            {"stage": "current_role", "label": "Senior Midwife", "description": "Has since safely attended over 800 births.", "year_label": "2017-present"},
        ],
        "day_in_the_life": "Prenatal appointments, labor and delivery attendance which can happen at any hour, and postpartum follow-up care.",
        "weekly_routine": "A mix of scheduled prenatal visits and unpredictable on-call delivery attendance.",
        "biggest_challenges": ["Accurately assessing when a birth needs a higher level of medical intervention than midwifery alone can provide", "Irregular, unpredictable hours around actual deliveries"],
        "favourite_part": "The moment of a healthy birth, and a family's first moments together.",
        "biggest_misconceptions": ["That midwives handle only low-risk births with no real medical training", "That a birth complication reflects a midwife's incompetence rather than the genuine unpredictability of childbirth"],
        "what_surprised_them": "How much rigorous, ongoing risk assessment training real midwifery requires.",
        "biggest_mistake": "During that early complicated delivery, I initially underestimated how quickly the situation was escalating because the early warning signs were subtle, and I didn't call for emergency support as early as I now know I should have. The mother and baby were ultimately safe, but that delay taught me to always err toward calling for help earlier rather than later.",
        "one_regret": "I regret how long I carried guilt about that case instead of channeling it constructively into further training sooner.",
        "salary_reality": "Midwifery salaries in Nigeria's community health system are modest, though the direct, meaningful patient impact is what keeps most midwives in the field.",
        "work_life_balance": "Genuinely unpredictable — births don't follow a schedule, and on-call responsibilities disrupt normal routines regularly.",
        "daily_skills": ["labor and delivery care", "risk assessment", "prenatal and postpartum care"],
        "daily_tools": ["Basic obstetric monitoring equipment", "emergency intervention protocols"],
        "recommended_books": ["Spiritual Midwifery by Ina May Gaskin"],
        "recommended_communities": ["Nigerian Association of Midwives"],
        "advice_for_beginners": "Always err toward calling for emergency support earlier rather than later when something feels uncertain — the delay in my one difficult case taught me this permanently.",
        "advice_for_parents": "A frightening complication during an early delivery is a normal, if terrifying, part of a midwife's training — it builds essential judgment, not evidence of incompetence.",
        "faqs": [{"question": "Is midwifery safe compared to hospital birth with a doctor?", "answer": "For genuinely low-risk pregnancies with proper risk screening and emergency backup protocols in place, midwifery-led birth has strong safety outcomes — appropriate risk assessment and referral pathways are essential."}],
        "projects": ["Has safely attended over 800 births"], "research": [], "certifications": ["Certified Midwife, Nigeria"],
        "conferences": [], "organizations": ["Nigerian Association of Midwives"],
        "volunteer_work": ["Trains junior midwives on emergency risk assessment protocols"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_criminal_defense_attorney_marcus_webb",
        "name": "Marcus Webb, Criminal Defense Attorney",
        "role_type": "industry_professional", "field": "law", "bio": "Represents defendants in criminal cases at a public defender's office; lost his first major trial due to a strategic error he still thinks about.",
        "trait_tags": ["persistence", "communication"], "learning_style_fit": "Students drawn to law's adversarial, high-stakes courtroom side who care about due process.",
        "organization": "A public defender's office", "years_experience": 11, "journey_highlights": ["Lost his first major jury trial due to a strategic error", "Has since successfully defended clients in over 300 cases"],
        "discussion_topics": ["Losing a case you believed you should have won", "Public defense versus private criminal defense", "What courtroom trial work actually feels like"],
        "profession": "Public Defender", "specialization": "Criminal trial defense", "country": "United States", "city": "Detroit",
        "industries": ["law"], "education": ["JD, Wayne State University Law School"],
        "current_role": "Senior Public Defender", "languages": ["English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students drawn to courtroom advocacy and due process work", "Students who've lost something important due to a strategic misjudgment", "Students weighing public defense against private practice or prosecution"],
        "career_ids": ["human_rights_researcher"],
        "career_journey": [
            {"stage": "university", "label": "JD", "description": "Chose criminal defense specifically over more lucrative corporate law tracks.", "year_label": "2008-2011"},
            {"stage": "first_job", "label": "Junior public defender", "description": "Handled a heavy caseload of lower-stakes cases before his first major jury trial.", "year_label": "2011-2013"},
            {"stage": "failure", "label": "Lost his first major jury trial after a strategic decision about which evidence to emphasize backfired", "description": "Believed strongly in his client's case and carried real guilt over the outcome for years.", "year_label": "2013"},
            {"stage": "turning_point", "label": "Rebuilt his trial preparation process around more rigorous mock jury testing of his strategy beforehand", "description": "Never again went to trial without testing his core argument against a practice audience first.", "year_label": "2014"},
            {"stage": "current_role", "label": "Senior Public Defender", "description": "Has since successfully defended clients in over 300 cases.", "year_label": "2017-present"},
        ],
        "day_in_the_life": "A mix of client meetings, case research, plea negotiations, and courtroom appearances.",
        "weekly_routine": "Heavy caseload management throughout the week, with trial preparation intensifying before scheduled court dates.",
        "biggest_challenges": ["Overwhelming caseloads common in public defense work", "The real, life-altering stakes of every case for his clients"],
        "favourite_part": "A not-guilty verdict for a client he genuinely believed deserved a fair chance.",
        "biggest_misconceptions": ["That public defenders are less skilled than private attorneys", "That losing a trial always means the attorney did something wrong, rather than reflecting genuine trial unpredictability"],
        "what_surprised_them": "How much of trial outcomes come down to jury psychology, not just legal argument quality.",
        "biggest_mistake": "In my first major trial, I built my defense strategy around a piece of evidence I was personally convinced was compelling, without properly testing how a jury would actually receive it. It backfired in a way I hadn't anticipated, and I now never finalize a trial strategy without testing it against a mock jury or trusted colleagues first.",
        "one_regret": "I regret trusting my own instinct so completely on that first trial without seeking more senior input on my strategy beforehand.",
        "salary_reality": "Public defender salaries in the US are considerably lower than private criminal defense or corporate law, a deliberate tradeoff for the mission many public defenders choose.",
        "work_life_balance": "Demanding, with heavy caseloads and unpredictable trial schedules that can disrupt personal time significantly.",
        "daily_skills": ["trial advocacy", "legal research", "negotiation"],
        "daily_tools": ["Legal research databases", "case management software"],
        "recommended_books": ["Just Mercy by Bryan Stevenson"],
        "recommended_communities": ["National Association for Public Defense"],
        "advice_for_beginners": "Never finalize a trial strategy without testing it against outside perspective first — my confident, untested first-trial strategy backfired in a way I hadn't anticipated.",
        "advice_for_parents": "Public defense work pays considerably less than private practice, and that's worth understanding — but it's a genuinely respected, essential legal career, not a lesser path.",
        "faqs": [{"question": "Are public defenders less skilled than private attorneys?", "answer": "Not at all — public defenders often have far more trial experience than private attorneys due to heavier caseloads, though they face genuinely difficult resource constraints."}],
        "projects": ["Has successfully defended clients in over 300 cases"], "research": [], "certifications": ["Licensed Attorney, Michigan"],
        "conferences": [], "organizations": ["National Association for Public Defense"],
        "volunteer_work": ["Trains new public defenders on trial strategy testing"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_landscape_architect_petra_novakova",
        "name": "Petra Nováková, Landscape Architect",
        "role_type": "industry_professional", "field": "landscape architecture", "bio": "Designs public parks and urban green spaces; her first major public park design was heavily criticized by residents for not reflecting the community's actual needs.",
        "trait_tags": ["creativity", "communication"], "learning_style_fit": "Students who like combining design, ecology, and public space planning.",
        "organization": "A municipal landscape architecture firm", "years_experience": 10, "journey_highlights": ["Her first major public park design was criticized as disconnected from community needs", "Redesigned her process around community co-design, now used as her firm's standard practice"],
        "discussion_topics": ["Recovering from public criticism of a creative design", "Landscape architecture as ecology plus design", "Designing genuinely for community needs"],
        "profession": "Landscape Architect", "specialization": "Public parks and urban green space", "country": "Czech Republic", "city": "Prague",
        "industries": ["architecture", "urban development"], "education": ["MSc Landscape Architecture, Czech University of Life Sciences Prague"],
        "current_role": "Senior Landscape Architect", "languages": ["Czech", "English", "German"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like design combined with ecology and public space", "Students who've had creative work publicly criticized", "Students interested in urban green space and community-centered design"],
        "career_ids": ["urban_planner"],
        "career_journey": [
            {"stage": "university", "label": "MSc Landscape Architecture", "description": "Focused her thesis on ecological restoration in urban settings.", "year_label": "2009-2015"},
            {"stage": "first_job", "label": "Junior landscape architect", "description": "Assisted senior designers before leading her own public project.", "year_label": "2015-2017"},
            {"stage": "failure", "label": "Her first major independent park design was heavily criticized by residents at a public review meeting", "description": "Residents felt the design reflected her own aesthetic preferences rather than the community's actual recreational needs.", "year_label": "2018"},
            {"stage": "turning_point", "label": "Redesigned her entire design process to start with genuine community co-design workshops", "description": "The revised process became her firm's standard practice for all future public projects.", "year_label": "2019"},
            {"stage": "current_role", "label": "Senior Landscape Architect", "description": "Leads design for major public green space projects across the city.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "A mix of design work, ecological site assessment, and community engagement meetings.",
        "weekly_routine": "Design and drafting work interspersed with community consultation sessions during active projects.",
        "biggest_challenges": ["Balancing ecological best practices against genuine community preferences that sometimes conflict", "Public criticism of creative decisions"],
        "favourite_part": "A park design that residents genuinely use and love, exactly as intended.",
        "biggest_misconceptions": ["That landscape architecture is just picking pretty plants", "That public criticism of a design reflects a lack of real talent"],
        "what_surprised_them": "How much landscape architecture is really about listening to a community, not imposing a personal creative vision.",
        "biggest_mistake": "My first park design was built almost entirely around my own aesthetic vision for the space, without genuinely incorporating community input beyond a single, poorly-attended public meeting. The backlash taught me that meaningful community co-design has to happen from the very start of a project, not as an afterthought.",
        "one_regret": "I regret how confident I was in my own design instincts on that first project — real community input from the start would have avoided the painful public criticism entirely.",
        "salary_reality": "Landscape architecture pays reasonably in the Czech Republic's public sector, though private commercial projects can pay considerably more.",
        "work_life_balance": "Generally steady, with periodic intensity around public consultation phases and project deadlines.",
        "daily_skills": ["landscape design", "ecological assessment", "community engagement"],
        "daily_tools": ["CAD and landscape design software", "GIS mapping tools"],
        "recommended_books": ["The Death and Life of Great American Cities by Jane Jacobs"],
        "recommended_communities": ["Czech Chamber of Architects"],
        "advice_for_beginners": "Build genuine community co-design into a public project from the very beginning, not as an afterthought — my criticized first design skipped this step entirely.",
        "advice_for_parents": "Public criticism of an early creative project is a genuinely painful but survivable part of design careers involving public space — it directly shaped a much better process for her later work.",
        "faqs": [{"question": "How do you design public spaces that communities actually want?", "answer": "Genuine, early community co-design workshops rather than presenting a finished design for approval — input needs to shape the design from the start, not just react to it."}],
        "projects": ["Redesigned community co-design process now used as her firm's standard practice"], "research": [],
        "certifications": [], "conferences": [], "organizations": ["Czech Chamber of Architects"],
        "volunteer_work": ["Runs free community design workshops for neighborhood associations"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch10).")


if __name__ == "__main__":
    asyncio.run(seed())
