"""Connect Batch 1 — Expert Connect seed data, thirteenth (final push)
wave, crossing the 100-expert floor. See seed_experts_tech_and_science.py
for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch13
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_paramedic_connor_walsh",
        "name": "Connor Walsh, Paramedic",
        "role_type": "industry_professional", "field": "emergency medical services", "bio": "Responds to emergency calls as a senior paramedic; froze during his first real cardiac arrest call, a moment that still motivates his training approach today.",
        "trait_tags": ["persistence", "empathy"], "learning_style_fit": "Students who want intense, immediate real-world impact and can handle high-pressure emergencies.",
        "organization": "A regional ambulance service", "years_experience": 11, "journey_highlights": ["Froze for several critical seconds during his first cardiac arrest call", "Now trains new paramedics on managing panic under pressure"],
        "discussion_topics": ["Freezing during a real emergency and recovering", "Paramedic work as a demanding, meaningful career", "What EMS training doesn't fully prepare you for"],
        "profession": "Senior Paramedic", "specialization": "Emergency response", "country": "Ireland", "city": "Dublin",
        "industries": ["healthcare", "emergency services"], "education": ["Paramedic diploma, Dublin City University"],
        "current_role": "Senior Paramedic and Training Officer", "languages": ["English", "Irish"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students who want intense, immediate real-world impact", "Students who've frozen under pressure during training and worry about it", "Students weighing EMS against nursing or other emergency careers"],
        "career_ids": ["physician_general"],
        "career_journey": [
            {"stage": "first_job", "label": "Newly certified paramedic", "description": "Completed rigorous simulation training but had not yet faced a genuinely life-threatening real call.", "year_label": "2013"},
            {"stage": "failure", "label": "Froze for several critical seconds during his first real cardiac arrest response", "description": "The gap between simulation and real-life panic terrified him, though his partner stepped in and the patient survived.", "year_label": "2013"},
            {"stage": "turning_point", "label": "Worked deliberately on stress-inoculation training beyond standard certification", "description": "Sought out additional realistic high-stress training scenarios to close the gap he'd experienced.", "year_label": "2014"},
            {"stage": "current_role", "label": "Senior Paramedic and Training Officer", "description": "Now specifically trains new paramedics on managing real panic under pressure.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Unpredictable emergency response shifts, ranging from routine calls to genuinely life-threatening situations, with detailed documentation after each call.",
        "weekly_routine": "Rotating shift schedule, including nights, since emergencies happen around the clock.",
        "biggest_challenges": ["Sustaining calm, clear decision-making during genuinely life-threatening situations", "The cumulative emotional toll of repeated exposure to trauma and death"],
        "favourite_part": "A patient who survived a call he genuinely thought might not have a good outcome.",
        "biggest_misconceptions": ["That paramedics never feel fear or panic on the job", "That freezing during a first real emergency means you're not cut out for the work"],
        "what_surprised_them": "How different real emergencies feel from even realistic simulation training.",
        "biggest_mistake": "During my first real cardiac arrest call, I froze because nothing in simulation had prepared me for the actual adrenaline and fear of a real dying patient in front of me. My partner had to take the lead while I found my footing. I now specifically build realistic panic-inoculation scenarios into the training I give new paramedics.",
        "one_regret": "I regret feeling deep shame about that freeze for a long time afterward instead of recognizing it as a normal part of the transition from training to real practice.",
        "salary_reality": "Paramedic salaries in Ireland are modest relative to the intensity and responsibility of the role, a real and known tradeoff for those drawn to the work.",
        "work_life_balance": "Genuinely difficult — shift work and the emotional toll of the job require deliberate self-care and support.",
        "daily_skills": ["emergency medical assessment", "rapid decision-making", "trauma care"],
        "daily_tools": ["Emergency medical equipment", "ambulance life support systems"],
        "recommended_books": ["Trauma Stewardship by Laura van Dernoot Lipsky"],
        "recommended_communities": ["Irish paramedics association"],
        "advice_for_beginners": "Expect a real gap between simulation training and your first genuine emergency — freezing briefly the first time is common, not disqualifying.",
        "advice_for_parents": "Freezing during a first real emergency is a normal part of paramedic training that most experienced paramedics have faced — please don't read it as your child lacking what it takes.",
        "faqs": [{"question": "Is it common to freeze during your first real emergency call?", "answer": "Yes — the gap between training simulations and real emergencies is well-documented, and most experienced paramedics have a story like mine."}],
        "projects": [], "research": [], "certifications": ["Advanced Paramedic Certification"],
        "conferences": [], "organizations": ["Irish paramedics association"],
        "volunteer_work": ["Trains new paramedics on stress management and panic response"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_firefighter_diego_fernandez",
        "name": "Diego Fernández, Firefighter",
        "role_type": "industry_professional", "field": "emergency services", "bio": "Serves as a firefighter and rescue specialist; a serious injury during a training exercise nearly ended his career before it began.",
        "trait_tags": ["persistence", "leadership"], "learning_style_fit": "Students drawn to physically demanding, high-stakes public service work.",
        "organization": "A municipal fire department", "years_experience": 13, "journey_highlights": ["A serious training injury nearly ended his career before it started", "Led a rescue team during a major building fire that saved four residents"],
        "discussion_topics": ["Recovering from a career-threatening training injury", "Firefighting as a genuine long-term career", "What the job demands physically and psychologically"],
        "profession": "Firefighter and Rescue Specialist", "specialization": "Structural fire and rescue operations", "country": "Spain", "city": "Valencia",
        "industries": ["emergency services", "government"], "education": ["Firefighter academy training program"],
        "current_role": "Senior Firefighter and Team Leader", "languages": ["Spanish", "Catalan"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students drawn to physically demanding public service work", "Students who've faced a serious injury threatening a dream career", "Students who want to know what firefighting actually demands"],
        "career_ids": [],
        "career_journey": [
            {"stage": "first_job", "label": "Firefighter academy trainee", "description": "Physically rigorous training program with a real risk of injury.", "year_label": "2010"},
            {"stage": "failure", "label": "Suffered a serious knee injury during a training exercise", "description": "Doctors initially told him it might end his firefighting career entirely, a devastating prospect after years of preparation.", "year_label": "2010"},
            {"stage": "turning_point", "label": "Underwent extensive rehabilitation and was cleared to return to full duty after a year", "description": "The recovery period taught him real physical and mental discipline he now applies throughout his career.", "year_label": "2011"},
            {"stage": "promotion", "label": "Progressed to senior firefighter and eventually team leader", "description": "Led a rescue team during a major building fire that saved four residents.", "year_label": "2017-present"},
        ],
        "day_in_the_life": "A mix of physical training, equipment maintenance, community safety education, and emergency response readiness.",
        "weekly_routine": "Shift-based schedule involving extended periods on duty at the station, punctuated by emergency calls.",
        "biggest_challenges": ["The genuine physical danger inherent in the job", "Sustaining physical fitness and readiness over a long career"],
        "favourite_part": "Getting a family safely out of a burning building.",
        "biggest_misconceptions": ["That firefighting is mostly waiting around at the station", "That a serious training injury means the career is over"],
        "what_surprised_them": "How much of the job is preventive — community education and equipment readiness — not just active emergency response.",
        "biggest_mistake": "The injury that nearly ended my career came partly from rushing through a training exercise technique I hadn't fully mastered, eager to keep pace with more experienced trainees. I learned that pushing past genuine physical readiness, even under peer pressure, is a real risk I now train new firefighters to recognize in themselves.",
        "one_regret": "I regret not speaking up when I felt unprepared for that specific training exercise — the pressure to keep pace with peers led me to push past a limit I should have flagged.",
        "salary_reality": "Firefighter salaries in Spain are stable and reasonable within public service, reflecting genuine civil service employment.",
        "work_life_balance": "Shift-based schedule with extended periods on duty, which affects family time differently than a standard workweek.",
        "daily_skills": ["firefighting techniques", "physical fitness", "emergency rescue operations"],
        "daily_tools": ["Firefighting and rescue equipment", "breathing apparatus"],
        "recommended_books": ["Report from Engine Co. 82 by Dennis Smith"],
        "recommended_communities": ["Spanish firefighters association"],
        "advice_for_beginners": "Speak up if you feel genuinely unprepared for a specific training exercise, even under peer pressure — my serious injury came from pushing past that exact instinct.",
        "advice_for_parents": "A serious training injury is a real risk in this physically demanding field, and it's fair to worry about it — but full recovery and a long career afterward, as he found, is genuinely possible.",
        "faqs": [{"question": "Is firefighting training genuinely dangerous?", "answer": "Yes, training exercises carry real injury risk, which is why proper technique and honest self-assessment of readiness matter enormously."}],
        "projects": ["Led a rescue team that saved four residents during a major building fire"], "research": [],
        "certifications": ["Firefighter certification"], "conferences": [], "organizations": ["Spanish firefighters association"],
        "volunteer_work": ["Teaches fire safety education in local schools"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_solar_technician_business_owner_thabo_mokoena",
        "name": "Thabo Mokoena, Solar Energy Technician & Business Owner",
        "role_type": "founder", "field": "renewable energy trades", "bio": "Runs a solar panel installation business; his first year of business nearly failed due to underpricing jobs and poor cash flow management.",
        "trait_tags": ["persistence", "analytical_thinking"], "learning_style_fit": "Students interested in renewable energy trades as a hands-on, growing career field.",
        "organization": "An independent solar installation company", "years_experience": 9, "journey_highlights": ["Nearly went out of business in his first year due to underpricing jobs", "Now employs six technicians across residential and commercial installations"],
        "discussion_topics": ["Nearly failing a new business through poor pricing", "Solar installation as a skilled trades career", "Renewable energy trades beyond engineering degrees"],
        "profession": "Solar Installation Technician, Business Owner", "specialization": "Residential and commercial solar installation", "country": "South Africa", "city": "Pretoria",
        "industries": ["renewable energy", "skilled trades"], "education": ["Electrical trade certification, solar installation specialty training"],
        "current_role": "Owner, Solar Installation Company", "languages": ["English", "Sotho", "Zulu"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in renewable energy trades as a hands-on career", "Students who've nearly failed a new business due to financial mismanagement", "Students weighing trades against a traditional engineering degree"],
        "career_ids": ["sustainability_analyst"],
        "career_journey": [
            {"stage": "first_job", "label": "Electrician apprentice, then solar specialty training", "description": "Added solar installation specialization to his electrical trade certification as the industry grew.", "year_label": "2012-2015"},
            {"stage": "career_transition", "label": "Started his own solar installation business", "description": "Left stable employment to build an independent company, taking on real financial risk.", "year_label": "2016"},
            {"stage": "failure", "label": "Nearly went out of business in his first year due to underpricing jobs and poor cash flow management", "description": "Won contracts by pricing too aggressively low, leaving no real margin to sustain the business.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Rebuilt his pricing model with proper cost accounting and healthy margins", "description": "Worked with a small business advisor to understand real cost structures for the first time.", "year_label": "2017"},
            {"stage": "current_role", "label": "Owner, Solar Installation Company", "description": "Now employs six technicians across residential and commercial installation projects.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "A mix of on-site installation work, client consultations, and business management tasks.",
        "weekly_routine": "Installation projects scheduled throughout the week, with administrative work handled in the evenings.",
        "biggest_challenges": ["Accurate, sustainable pricing that reflects real costs", "The physical demands of installation work combined with running a business"],
        "favourite_part": "Watching a family's electricity bill drop dramatically after an installation.",
        "biggest_misconceptions": ["That solar installation is simple, unskilled work", "That trades businesses can't achieve real financial success"],
        "what_surprised_them": "How much running a trades business is about financial literacy, not just technical installation skill.",
        "biggest_mistake": "I priced my early jobs based on trying to win contracts against competitors rather than on my actual costs, not properly accounting for equipment, labor, and overhead. It nearly bankrupted the business in year one, and I now build every quote from real, detailed cost accounting first.",
        "one_regret": "I regret not seeking a business mentor's guidance before starting — basic cost-accounting knowledge would have prevented my near-failure entirely.",
        "salary_reality": "Solar installation is a growing, well-paying trade in South Africa given increasing energy demand, but proper business pricing is essential to actually capturing that opportunity.",
        "work_life_balance": "Demanding as a business owner, with real physical installation work on top of business management responsibilities.",
        "daily_skills": ["electrical installation", "solar system design", "business pricing and management"],
        "daily_tools": ["Solar installation equipment", "electrical testing tools"],
        "recommended_books": ["Profit First by Mike Michalowicz"],
        "recommended_communities": ["South African Photovoltaic Industry Association"],
        "advice_for_beginners": "Price every job based on real, detailed cost accounting, never just to win against competitors — my near-bankruptcy came from exactly that shortcut.",
        "advice_for_parents": "Renewable energy trades are a genuine, growing career field with real business ownership potential, not a lesser alternative to an engineering degree.",
        "faqs": [{"question": "Is solar installation a growing career field?", "answer": "Yes — demand for renewable energy installation skills is growing significantly as more households and businesses adopt solar power."}],
        "projects": ["Built a company now employing six technicians"], "research": [],
        "certifications": ["Certified Solar PV Installer"], "conferences": [], "organizations": ["South African Photovoltaic Industry Association"],
        "volunteer_work": ["Trains unemployed youth in basic solar installation skills"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_archivist_ingrid_larsen",
        "name": "Ingrid Larsen, Archivist",
        "role_type": "industry_professional", "field": "archival science", "bio": "Manages historical archives at a national library; a preservation error early in her career led to irreversible damage to a rare historical document.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students who love history and want a career focused on preservation and research access, not just study.",
        "organization": "A national library archive", "years_experience": 12, "journey_highlights": ["A preservation handling error caused irreversible damage to a rare historical document", "Now leads digitization efforts protecting the archive's most fragile materials"],
        "discussion_topics": ["An irreversible professional mistake and what it taught her", "Archival science as a career combining history and preservation science", "Digitizing history for public access"],
        "profession": "Senior Archivist", "specialization": "Rare document preservation and digitization", "country": "Norway", "city": "Oslo",
        "industries": ["museums", "culture"], "education": ["MA History, University of Oslo", "MSc Archival Science, Uppsala University"],
        "current_role": "Senior Archivist, Rare Collections", "languages": ["Norwegian", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who love history and want a preservation-focused career", "Students who've made an irreversible mistake and struggled to forgive themselves", "Students interested in digitization and public access to historical materials"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "MA History, then MSc Archival Science", "description": "Combined historical research training with specialized preservation science.", "year_label": "2008-2014"},
            {"stage": "first_job", "label": "Junior archivist", "description": "Handled rare document requests under senior supervision before working independently.", "year_label": "2014-2016"},
            {"stage": "failure", "label": "Made a handling error that caused irreversible damage to a rare historical document", "description": "Used an improper handling technique during a research request, causing damage that could never be fully undone despite immediate conservation efforts.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Became a leading advocate within her institution for stricter handling protocols and digitization priority", "description": "Channeled her guilt into meaningful institutional change rather than letting it end her career.", "year_label": "2017"},
            {"stage": "current_role", "label": "Senior Archivist, Rare Collections", "description": "Now leads digitization efforts specifically protecting the archive's most fragile materials from ever needing physical handling again.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of document preservation work, research assistance for scholars, and digitization project management.",
        "weekly_routine": "Careful preservation and cataloging work throughout the week, with periodic research consultations.",
        "biggest_challenges": ["The irreversible nature of preservation mistakes with truly unique historical materials", "Balancing genuine public and scholarly access against preservation needs"],
        "favourite_part": "Making a previously inaccessible historical document available to researchers worldwide through digitization.",
        "biggest_misconceptions": ["That archival work is simply storing old documents", "That an irreversible mistake with a unique object should end a preservation career"],
        "what_surprised_them": "How much of archival science is genuinely scientific — chemistry, materials science — not just historical knowledge.",
        "biggest_mistake": "I used a handling technique on a rare document that I hadn't verified was appropriate for that specific paper's age and condition, causing irreversible damage during what should have been a routine research request. It remains one of the hardest professional moments of my life, and it's exactly why I now champion digitization as a way to reduce the need for physical handling of our most fragile materials.",
        "one_regret": "I regret not consulting a conservation specialist before that specific handling, given the document's genuine rarity — a five-minute consultation would have prevented irreversible loss.",
        "salary_reality": "Archival science salaries in Norway are modest, reflecting broader cultural sector compensation, despite the highly specialized graduate training required.",
        "work_life_balance": "Generally steady, predictable hours without the emergency demands of many other careers.",
        "daily_skills": ["document preservation techniques", "historical research", "digitization management"],
        "daily_tools": ["Specialized preservation equipment", "high-resolution digitization scanners"],
        "recommended_books": ["Archives Power by Randall Jimerson"],
        "recommended_communities": ["Norwegian Archives Association"],
        "advice_for_beginners": "Always consult a conservation specialist before handling anything genuinely rare or fragile, even for routine requests — my irreversible mistake came from skipping that exact step.",
        "advice_for_parents": "Archival science is a genuine, scientifically rigorous career combining history and preservation expertise, not just a quiet library job.",
        "faqs": [{"question": "Does archival science require a science background?", "answer": "It helps, but most archivists come from history or library science and learn preservation chemistry and materials science through specialized graduate programs."}],
        "projects": ["Leads digitization efforts protecting the archive's most fragile materials"], "research": [], "certifications": [],
        "conferences": [], "organizations": ["Norwegian Archives Association"],
        "volunteer_work": ["Trains junior archivists on proper rare-document handling protocols"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_corporate_lawyer_richard_okoro",
        "name": "Richard Okoro, Corporate Lawyer",
        "role_type": "industry_professional", "field": "law", "bio": "Advises companies on mergers and acquisitions at a corporate law firm; missed a critical contract clause early in his career that nearly cost a client a major deal.",
        "trait_tags": ["analytical_thinking", "persistence"], "learning_style_fit": "Students interested in law's business side, involving complex negotiation and precise contract work.",
        "organization": "A corporate law firm", "years_experience": 12, "journey_highlights": ["Missed a critical contract clause that nearly derailed a major client deal", "Now leads the firm's mergers and acquisitions practice"],
        "discussion_topics": ["Nearly costing a client a major deal through an oversight", "Corporate law versus other legal specialties", "What mergers and acquisitions work actually involves"],
        "profession": "Corporate M&A Attorney", "specialization": "Mergers and acquisitions", "country": "Nigeria", "city": "Lagos",
        "industries": ["law", "finance"], "education": ["Law degree, University of Lagos", "LLM, Harvard Law School"],
        "current_role": "Partner, Mergers and Acquisitions", "languages": ["English", "Igbo"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in the business side of law", "Students who've made a costly detail-oriented mistake under deadline pressure", "Students weighing corporate law against other legal specialties"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "Law degree, then LLM abroad", "description": "Pursued an international master's degree specifically to specialize in corporate law.", "year_label": "2006-2013"},
            {"stage": "first_job", "label": "Junior associate at a corporate law firm", "description": "Worked under intense deadline pressure on complex contract review.", "year_label": "2013-2016"},
            {"stage": "failure", "label": "Missed a critical liability clause during a rushed contract review that nearly derailed a major client deal", "description": "Caught just before signing by a senior partner's final review, the near-miss badly shook his confidence.", "year_label": "2016"},
            {"stage": "turning_point", "label": "Built a rigorous personal checklist system for contract review, regardless of deadline pressure", "description": "Never had a similar near-miss again through the rest of his career.", "year_label": "2017"},
            {"stage": "current_role", "label": "Partner, Mergers and Acquisitions", "description": "Now leads the firm's M&A practice.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Contract review and drafting, client negotiations, and coordinating complex, multi-party deals.",
        "weekly_routine": "Steady deal work punctuated by intense periods before major transaction closings.",
        "biggest_challenges": ["The zero-margin-for-error nature of contract review under real deadline pressure", "Managing multiple complex deals simultaneously"],
        "favourite_part": "Successfully closing a complex deal that genuinely benefits all parties involved.",
        "biggest_misconceptions": ["That corporate law is less rigorous or interesting than litigation", "That a caught near-miss error reflects poor competence rather than appropriate safety systems working"],
        "what_surprised_them": "How much of corporate law success depends on meticulous process discipline, not just legal knowledge.",
        "biggest_mistake": "Under significant deadline pressure on my first major deal, I rushed through a contract review and missed a critical liability clause that could have exposed my client to significant risk. A senior partner's final review caught it before signing. I now use a rigorous personal review checklist for every contract, regardless of how much time pressure exists.",
        "one_regret": "I regret letting deadline pressure override my own thoroughness on that review — the near-miss taught me that rushing is never actually faster once you account for the risk.",
        "salary_reality": "Corporate law, especially M&A work, is among the most financially rewarding legal specialties in Nigeria, reflecting the complexity and stakes involved.",
        "work_life_balance": "Demanding, with real intensity around deal closings that can mean very long hours for stretches.",
        "daily_skills": ["contract drafting and review", "negotiation", "deal structuring"],
        "daily_tools": ["Legal document review software", "deal management platforms"],
        "recommended_books": ["Getting to Yes by Roger Fisher and William Ury"],
        "recommended_communities": ["Nigerian Bar Association corporate law section"],
        "advice_for_beginners": "Build a rigorous personal review checklist for detail-critical work and use it every time, regardless of deadline pressure — my near-miss taught me rushing never actually saves real time.",
        "advice_for_parents": "Corporate law is a genuinely rigorous, high-stakes legal specialty requiring real precision under pressure, not a 'safer' alternative to litigation.",
        "faqs": [{"question": "Is corporate law less demanding than litigation?", "answer": "Not at all — it involves genuinely high-stakes, detail-critical work under real deadline pressure, just without courtroom appearances."}],
        "projects": [], "research": [], "certifications": ["Licensed Attorney, Nigeria"],
        "conferences": [], "organizations": ["Nigerian Bar Association"],
        "volunteer_work": ["Mentors junior associates on contract review discipline"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch13).")


if __name__ == "__main__":
    asyncio.run(seed())
