"""Connect Batch 1 — Expert Connect seed data, sixth wave. See
seed_experts_tech_and_science.py for full module conventions.

Run via: python -m aureon.scripts.seed_experts_batch6
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_renewable_energy_engineer_astrid_lindqvist",
        "name": "Astrid Lindqvist, Renewable Energy Engineer",
        "role_type": "industry_professional", "field": "energy engineering", "bio": "Designs offshore wind farm systems; her first proposed turbine layout underperformed badly against projections once built.",
        "trait_tags": ["analytical_thinking", "values"], "learning_style_fit": "Students combining engineering rigor with real climate motivation.",
        "organization": "An offshore wind energy company", "years_experience": 8, "journey_highlights": ["Her first turbine layout underperformed energy projections by 20%", "Later designs now regularly exceed projected output"],
        "discussion_topics": ["Learning from an underperforming engineering design", "Renewable energy careers beyond solar panels", "Offshore wind engineering specifically"],
        "profession": "Renewable Energy Systems Engineer", "specialization": "Offshore wind farm design", "country": "Denmark", "city": "Aarhus",
        "industries": ["energy", "climate"], "education": ["MSc Wind Energy Engineering, Technical University of Denmark"],
        "current_role": "Senior Wind Energy Engineer", "languages": ["Danish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students interested in renewable energy careers beyond solar panels", "Students who like combining climate motivation with rigorous engineering", "Students who've had a design underperform in the real world"],
        "career_ids": ["sustainability_analyst", "space_systems_engineer"],
        "career_journey": [
            {"stage": "university", "label": "MSc Wind Energy Engineering", "description": "Chose the specialization specifically to work directly on climate solutions.", "year_label": "2012-2016"},
            {"stage": "first_job", "label": "Junior turbine layout engineer", "description": "Designed her first independent offshore farm layout under real commercial pressure.", "year_label": "2016-2019"},
            {"stage": "failure", "label": "Her turbine layout underperformed energy output projections by 20% once built", "description": "Wake interference effects between turbines were more significant than her modeling had accounted for.", "year_label": "2019"},
            {"stage": "turning_point", "label": "Adopted more conservative, better-validated wake modeling for future projects", "description": "Collaborated closely with an academic research group specializing in turbine wake effects.", "year_label": "2020"},
            {"stage": "current_role", "label": "Senior Wind Energy Engineer", "description": "Her subsequent designs now regularly meet or exceed projected output.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "Modeling wind resource and turbine layouts, coordinating with construction and environmental teams.",
        "weekly_routine": "Deep technical modeling most days, with periodic site visits during active construction phases.",
        "biggest_challenges": ["The genuine complexity of predicting real-world turbine interaction effects", "Balancing energy output ambition against environmental and community concerns"],
        "favourite_part": "Watching a wind farm she designed actually powering homes at scale.",
        "biggest_misconceptions": ["That renewable energy engineering is simple compared to traditional power engineering", "That an underperforming first design ends a career in this field"],
        "what_surprised_them": "How much real-world physical complexity (wake effects, weather variability) modeling alone can't fully capture.",
        "biggest_mistake": "My first layout used a simplified wake interference model that significantly underestimated how much turbines would affect each other's output when positioned too closely. It cost the project real revenue, and I now insist on much more conservative, validated modeling for every subsequent design.",
        "one_regret": "I regret not consulting more experienced wake-modeling specialists before finalizing that first layout — a second opinion would have caught the issue before construction.",
        "salary_reality": "Renewable energy engineering pays well in Denmark's mature wind industry, reflecting genuine, growing global demand for this specialized expertise.",
        "work_life_balance": "Generally steady, with real intensity during active construction and commissioning phases.",
        "daily_skills": ["wind resource modeling", "turbine layout design", "energy yield analysis"],
        "daily_tools": ["Wind farm design software", "computational fluid dynamics tools"],
        "recommended_books": ["Wind Energy Explained by Manwell, McGowan, and Rogers"],
        "recommended_communities": ["Danish Wind Industry Association"],
        "advice_for_beginners": "Use conservative, validated models for real-world physical effects rather than simplified assumptions — my underperforming first project taught me this directly.",
        "advice_for_parents": "Renewable energy engineering is a genuine, rigorous engineering discipline with real global demand, not a 'soft' alternative to traditional engineering.",
        "faqs": [{"question": "Is renewable energy engineering a stable career field?", "answer": "Yes — global demand for wind and solar engineering expertise is growing significantly and shows no signs of slowing."}],
        "projects": ["Designed offshore wind layouts now regularly exceeding output projections"], "research": [],
        "certifications": [], "conferences": ["WindEurope Annual Event"], "organizations": ["Danish Wind Industry Association"],
        "volunteer_work": ["Mentors engineering students interested in renewable energy careers"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_physical_therapist_mariana_costa",
        "name": "Mariana Costa, Physical Therapist",
        "role_type": "industry_professional", "field": "physical therapy", "bio": "Works with athletes recovering from injury at a sports medicine clinic; her own career-ending gymnastics injury as a teenager led her to the field.",
        "trait_tags": ["empathy", "analytical_thinking"], "learning_style_fit": "Students interested in anatomy and rehabilitation, especially those with their own injury history.",
        "organization": "A sports medicine clinic", "years_experience": 9, "journey_highlights": ["Her own gymnastics career ended at 16 due to injury", "Now helps elite athletes recover from career-threatening injuries"],
        "discussion_topics": ["Turning a personal injury into a career", "Physical therapy vs. other rehabilitation careers", "Working with athletes under pressure to return quickly"],
        "profession": "Sports Physical Therapist", "specialization": "Athletic injury rehabilitation", "country": "Brazil", "city": "Rio de Janeiro",
        "industries": ["healthcare", "sports"], "education": ["Doctor of Physical Therapy, Federal University of Rio de Janeiro"],
        "current_role": "Lead Physical Therapist, Sports Medicine", "languages": ["Portuguese", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students whose own athletic career was affected by injury", "Students interested in sports medicine specifically", "Students who like anatomy combined with hands-on patient work"],
        "career_ids": [],
        "career_journey": [
            {"stage": "school", "label": "Competitive gymnastics training as a teenager", "description": "A serious knee injury at 16 ended her competitive career and led to months of her own physical therapy.", "year_label": "2004-2008"},
            {"stage": "university", "label": "Doctor of Physical Therapy", "description": "Her own rehabilitation experience directly shaped her choice of career.", "year_label": "2010-2015"},
            {"stage": "first_job", "label": "Physical therapist at a general clinic", "description": "Built broad clinical experience before specializing in sports medicine.", "year_label": "2015-2018"},
            {"stage": "current_role", "label": "Lead Physical Therapist, Sports Medicine", "description": "Now helps elite athletes recover from career-threatening injuries similar to her own.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Back-to-back patient sessions combining hands-on treatment, exercise prescription, and progress assessment.",
        "weekly_routine": "Full clinical schedule with periodic case conferences alongside physicians and coaches.",
        "biggest_challenges": ["Managing an athlete's pressure to return to competition faster than is medically safe", "The emotional weight of working with athletes facing career-ending injuries, as she once did herself"],
        "favourite_part": "An athlete's first pain-free return to their sport after a difficult recovery.",
        "biggest_misconceptions": ["That physical therapy is just stretching and massage", "That a career-ending injury means an athlete's connection to sport is over"],
        "what_surprised_them": "How much psychological support the role requires alongside the physical rehabilitation work.",
        "biggest_mistake": "Early in my career, I pushed a recovering patient's rehabilitation timeline based on a generic protocol rather than their specific injury presentation, which led to a minor setback in their recovery. I learned to individualize every rehabilitation plan much more carefully after that.",
        "one_regret": "I regret not fully processing my own injury grief before starting to treat patients facing similar situations — I initially over-identified with some patients in ways that weren't always helpful for either of us.",
        "salary_reality": "Sports physical therapy pays reasonably well in Brazil relative to general clinical roles, reflecting the specialized training and athlete-facing demand.",
        "work_life_balance": "Generally steady, though competition seasons can mean irregular hours supporting athletes at events.",
        "daily_skills": ["injury assessment", "manual therapy", "exercise prescription"],
        "daily_tools": ["Rehabilitation equipment", "movement assessment technology"],
        "recommended_books": ["Athletic Body in Balance by Gray Cook"],
        "recommended_communities": ["Brazilian Association of Sports Physical Therapy"],
        "advice_for_beginners": "Individualize every rehabilitation plan rather than relying on generic protocols — a one-size-fits-all approach led to a real setback for one of my early patients.",
        "advice_for_parents": "A career-ending sports injury doesn't have to end your child's connection to athletics — physical therapy let me stay deeply connected to sport in a completely new way.",
        "faqs": [{"question": "Do you need a sports background to become a sports physical therapist?", "answer": "It's not required, though many in the field, including me, are drawn to it through personal athletic injury experience."}],
        "projects": [], "research": [], "certifications": ["Licensed Physical Therapist, Brazil"],
        "conferences": [], "organizations": ["Brazilian Association of Sports Physical Therapy"],
        "volunteer_work": ["Provides free injury-prevention clinics for youth gymnastics programs"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_electrician_business_owner_liam_murphy",
        "name": "Liam Murphy, Master Electrician & Business Owner",
        "role_type": "founder", "field": "skilled trades", "bio": "Runs his own electrical contracting business; nearly lost his apprenticeship after a serious safety violation early in his training.",
        "trait_tags": ["persistence", "leadership"], "learning_style_fit": "Students interested in skilled trades as a genuine, well-paying alternative to a university degree.",
        "organization": "An independent electrical contracting business", "years_experience": 16, "journey_highlights": ["Nearly lost his apprenticeship over a serious safety violation", "Built his own contracting business now employing eight electricians"],
        "discussion_topics": ["Skilled trades as a real career alternative to university", "Recovering from a serious early mistake in training", "Building a trades business from an apprenticeship"],
        "profession": "Master Electrician, Business Owner", "specialization": "Residential and commercial electrical contracting", "country": "Ireland", "city": "Cork",
        "industries": ["skilled trades", "construction"], "education": ["Electrical apprenticeship and trade certification"],
        "current_role": "Owner, Electrical Contracting Business", "languages": ["English", "Irish"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students considering skilled trades instead of university", "Students who've made a serious safety mistake early in training", "Students interested in eventually running their own trades business"],
        "career_ids": [],
        "career_journey": [
            {"stage": "school", "label": "Left secondary school for an electrical apprenticeship", "description": "Chose the trades path against some family expectations that he'd attend university.", "year_label": "2007"},
            {"stage": "first_job", "label": "Electrical apprentice", "description": "Learned under a senior electrician on residential and light commercial jobs.", "year_label": "2007-2011"},
            {"stage": "failure", "label": "Committed a serious safety violation that nearly got him removed from his apprenticeship", "description": "Worked on a live circuit without properly confirming it was de-energized, a mistake that could have been fatal and seriously damaged his supervisor's trust in him.", "year_label": "2009"},
            {"stage": "turning_point", "label": "Rebuilt his supervisor's trust through months of scrupulous safety discipline", "description": "The near-miss became the foundation of his lifelong obsession with safety protocol.", "year_label": "2010"},
            {"stage": "career_transition", "label": "Started his own contracting business", "description": "Took on real financial risk to go independent after years as an employed electrician.", "year_label": "2015"},
            {"stage": "current_role", "label": "Owner, Electrical Contracting Business", "description": "Now employs eight electricians across residential and commercial projects.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "A mix of hands-on electrical work, client consultations, and business management for his growing company.",
        "weekly_routine": "On-site work most days, with administrative and business development tasks handled in the evenings.",
        "biggest_challenges": ["Uncompromising safety standards on every job, every time, no exceptions", "Balancing hands-on trade work with running a growing business"],
        "favourite_part": "Training an apprentice who reminds him of his own early, imperfect start.",
        "biggest_misconceptions": ["That trades careers are a 'fallback' for people who couldn't get into university", "That skilled trades don't offer real business ownership opportunities"],
        "what_surprised_them": "How much of running a trades business is client relationships and management, not just technical electrical skill.",
        "biggest_mistake": "Early in my apprenticeship, I worked on what I assumed was a de-energized circuit without properly re-testing it myself first, trusting someone else's word instead of verifying independently. It could have been fatal, and it's the single mistake that shaped my entire approach to safety since.",
        "one_regret": "I regret how close that mistake came to ending my career before it started — it took real, sustained effort to rebuild my supervisor's trust afterward.",
        "salary_reality": "Skilled trades in Ireland pay very well, often exceeding many university-degree-required careers, especially once you own your own business.",
        "work_life_balance": "Demanding as a business owner, though the physical trade work itself has a more predictable daily rhythm than many office careers.",
        "daily_skills": ["electrical installation and repair", "safety compliance", "business management"],
        "daily_tools": ["Electrical testing equipment", "project management software"],
        "recommended_books": ["The E-Myth Revisited by Michael Gerber"],
        "recommended_communities": ["Electrical Contractors Ireland"],
        "advice_for_beginners": "Always independently verify safety conditions yourself, never just trust someone else's word — the near-fatal mistake I made early on taught me this permanently.",
        "advice_for_parents": "A skilled trade is a genuine, often very financially rewarding career path, not a lesser option than university — many electricians and business owners in trades earn more than university graduates in many fields.",
        "faqs": [{"question": "Can skilled trades lead to real business ownership?", "answer": "Absolutely — my own contracting business, now employing eight people, started from a standard electrical apprenticeship."}],
        "projects": ["Built a contracting business now employing eight electricians"], "research": [], "certifications": ["Master Electrician certification"],
        "conferences": [], "organizations": ["Electrical Contractors Ireland"],
        "volunteer_work": ["Trains apprentices with a strong emphasis on safety culture"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_speech_therapist_naledi_dlamini",
        "name": "Naledi Dlamini, Speech-Language Pathologist",
        "role_type": "industry_professional", "field": "speech-language pathology", "bio": "Works with children with speech and language delays at a pediatric clinic; her own childhood stutter shaped her career choice.",
        "trait_tags": ["empathy", "communication"], "learning_style_fit": "Students interested in communication science and working closely with children.",
        "organization": "A pediatric speech and language clinic", "years_experience": 8, "journey_highlights": ["Struggled with a stutter throughout her own childhood", "Now specializes in treating childhood stuttering specifically"],
        "discussion_topics": ["Turning a personal childhood challenge into a specialty", "Speech-language pathology as a career", "Working with children versus adult patients"],
        "profession": "Speech-Language Pathologist", "specialization": "Childhood stuttering and fluency disorders", "country": "South Africa", "city": "Johannesburg",
        "industries": ["healthcare", "education"], "education": ["BSc Speech-Language Pathology, University of the Witwatersrand"],
        "current_role": "Senior Speech-Language Pathologist", "languages": ["English", "Zulu", "Sotho"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students with a personal history of a speech or language challenge", "Students who want to work closely with children in a clinical setting", "Students interested in communication sciences broadly"],
        "career_ids": [],
        "career_journey": [
            {"stage": "school", "label": "Struggled with a significant stutter throughout primary school", "description": "Faced real teasing from classmates and years of her own speech therapy.", "year_label": "1998-2005"},
            {"stage": "university", "label": "BSc Speech-Language Pathology", "description": "Chose the field specifically because of her own childhood experience with therapy.", "year_label": "2010-2014"},
            {"stage": "first_job", "label": "General pediatric speech therapist", "description": "Worked across a broad range of childhood communication disorders before specializing.", "year_label": "2014-2018"},
            {"stage": "current_role", "label": "Senior Speech-Language Pathologist", "description": "Now specializes specifically in childhood stuttering, drawing directly on her own experience.", "year_label": "2019-present"},
        ],
        "day_in_the_life": "Back-to-back sessions with children and their families, combining direct therapy with parent coaching.",
        "weekly_routine": "Clinical sessions throughout the week, with periodic school visits to support children in their classroom environment.",
        "biggest_challenges": ["Helping parents understand that stuttering isn't caused by anything they did wrong", "The emotional weight of working with children facing real social difficulty because of their speech"],
        "favourite_part": "A child's growing confidence speaking up in class after months of therapy.",
        "biggest_misconceptions": ["That stuttering is caused by nervousness or poor parenting", "That speech therapy is only for young children, not a lifelong communication science field"],
        "what_surprised_them": "How much of the work is really about building a child's confidence, not just correcting their speech mechanically.",
        "biggest_mistake": "Early in my career, I focused too narrowly on speech mechanics with a young stuttering patient without adequately addressing his growing social anxiety about speaking in class, which limited his actual progress. I learned to treat the emotional and social dimensions of stuttering as seriously as the speech mechanics themselves.",
        "one_regret": "I regret not disclosing my own stuttering history to families sooner in my career — once I started sharing it, parents and children both trusted the process more deeply.",
        "salary_reality": "Speech-language pathology pays reasonably in South Africa's private healthcare sector, though public sector roles pay considerably less despite equally real need.",
        "work_life_balance": "Generally steady clinical hours, without the emergency demands some healthcare careers carry.",
        "daily_skills": ["speech and language assessment", "therapeutic intervention", "family coaching"],
        "daily_tools": ["Standardized assessment tools", "therapy games and materials"],
        "recommended_books": ["Stuttering and Your Child by Barry Guitar"],
        "recommended_communities": ["South African Speech-Language-Hearing Association"],
        "advice_for_beginners": "Address the emotional and social side of a communication disorder as seriously as the mechanics — my early narrow focus limited a patient's real progress.",
        "advice_for_parents": "Stuttering isn't caused by anything a parent did — please know that guilt isn't warranted, and early, supportive intervention makes a real difference.",
        "faqs": [{"question": "Can a childhood stutter be fully treated?", "answer": "Many children see significant or complete improvement with early intervention, though some continue to manage it into adulthood — either outcome is a normal, real possibility worth discussing honestly."}],
        "projects": [], "research": [], "certifications": ["Licensed Speech-Language Pathologist, South Africa"],
        "conferences": [], "organizations": ["South African Speech-Language-Hearing Association"],
        "volunteer_work": ["Runs free support groups for parents of children who stutter"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_air_traffic_controller_bjorn_hansen",
        "name": "Bjørn Hansen, Air Traffic Controller",
        "role_type": "industry_professional", "field": "aviation", "bio": "Manages air traffic at a busy regional airport; made a spacing error early in training that could have caused a serious incident if not caught by a supervisor.",
        "trait_tags": ["analytical_thinking", "systems_thinking"], "learning_style_fit": "Students who thrive under sustained concentration and split-second decision-making.",
        "organization": "A regional airport air traffic control tower", "years_experience": 10, "journey_highlights": ["Made a serious spacing error during training that a supervisor caught in time", "Now trains new air traffic controllers"],
        "discussion_topics": ["The intense training and certification process for air traffic control", "Recovering from a near-miss training error", "What the job actually feels like moment to moment"],
        "profession": "Air Traffic Controller", "specialization": "Regional airport tower and approach control", "country": "Norway", "city": "Bergen",
        "industries": ["aviation"], "education": ["Air traffic control training program, Avinor Flysikring"],
        "current_role": "Senior Air Traffic Controller and Trainer", "languages": ["Norwegian", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like intense, focused, high-stakes work", "Students who made a serious error during training and worry it disqualifies them", "Students curious what the job actually feels like moment to moment"],
        "career_ids": [],
        "career_journey": [
            {"stage": "first_job", "label": "Entered a specialized air traffic control training program", "description": "The rigorous, high-pressure training washed out many candidates before certification.", "year_label": "2013-2015"},
            {"stage": "failure", "label": "Made a serious aircraft spacing error during a training simulation", "description": "A supervisor caught the error in time, but it shook his confidence badly and nearly led him to withdraw from the program.", "year_label": "2014"},
            {"stage": "turning_point", "label": "Worked intensively with an instructor on rebuilding his situational awareness habits", "description": "Passed certification several months later than his original cohort.", "year_label": "2015"},
            {"stage": "current_role", "label": "Senior Air Traffic Controller and Trainer", "description": "Now trains new controllers through the same difficult certification process he once struggled with.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Intense, focused shifts managing aircraft sequencing and separation, with mandatory breaks built in to maintain concentration.",
        "weekly_routine": "Rotating shift schedule, including nights, since air traffic never fully stops.",
        "biggest_challenges": ["Sustaining intense concentration for extended shift periods", "The real weight of split-second decisions affecting passenger safety"],
        "favourite_part": "The satisfaction of a smoothly managed, high-traffic period with zero incidents.",
        "biggest_misconceptions": ["That the job is mostly quiet monitoring rather than continuous active decision-making", "That a training error disqualifies someone from ultimately succeeding in the role"],
        "what_surprised_them": "How much the job relies on building instinctive pattern recognition through repetition, not just following procedures.",
        "biggest_mistake": "During a training simulation, I lost track of proper spacing between two aircraft because I focused too narrowly on one part of the airspace instead of maintaining broader situational awareness. A supervisor caught it before any real consequence, but it terrified me and completely reshaped how I train my own attention now.",
        "one_regret": "I regret how close I came to quitting after that error — I assumed one serious mistake meant I wasn't cut out for the job, when it was actually a normal, correctable part of training.",
        "salary_reality": "Air traffic controllers in Norway are well-compensated, reflecting the intensive training and high responsibility the role carries.",
        "work_life_balance": "Shift work, including nights and weekends, genuinely disrupts normal routines, though mandatory rest periods are strictly enforced for safety.",
        "daily_skills": ["situational awareness", "rapid decision-making", "clear radio communication"],
        "daily_tools": ["Radar and tower control systems", "aircraft communication radios"],
        "recommended_books": ["Skyfaring by Mark Vanhoenacker"],
        "recommended_communities": ["Norwegian air traffic controllers association"],
        "advice_for_beginners": "A serious training error doesn't mean you're not cut out for this work — mine nearly made me quit, and instead it became the lesson that made me a genuinely more careful controller.",
        "advice_for_parents": "The certification process for this career is intentionally rigorous and includes real setbacks for most trainees — please don't read an early struggle as a sign your child should give up.",
        "faqs": [{"question": "How intense is air traffic controller training?", "answer": "Extremely — it's designed to simulate real high-pressure decision-making, and many candidates face setbacks or need extra time before certification, which is normal."}],
        "projects": [], "research": [], "certifications": ["Certified Air Traffic Controller"],
        "conferences": [], "organizations": ["Norwegian air traffic controllers association"],
        "volunteer_work": ["Trains new controllers through the certification program"],
        "portfolio_links": [], "social_links": [],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (batch6).")


if __name__ == "__main__":
    asyncio.run(seed())
