"""Connect Batch 1 — Parent Connect seed data: the `ParentQuestion` Q&A
bank. Targets 150-200+ entries spread realistically across all 8
concern categories (salary, safety, stability, work_life_balance,
growth, international, career_switching, other), with globally diverse
framing — not all US-centric. Most entries are career-agnostic
(`career_id=None`); a meaningful subset are tied to a specific career
for concrete grounding. All seeded (`is_seeded=True`), matching the
Content Quality Bar's honest, specific tone — never generic platitudes.

Run via: python -m aureon.scripts.seed_parent_questions
"""

import asyncio

from aureon.domain.models.parent_connect import ParentQuestion
from aureon.services.supabase.client import get_supabase_client

QUESTIONS: list[dict] = [
    # --- salary ---
    {"category": "salary", "career_id": None, "question": "Will my child actually be able to support themselves on this career's starting salary?", "expert_response": "It depends heavily on the specific career and country, but most professional careers have a genuine 'ramp-up' period — modest pay for 1-3 years while building real experience, followed by meaningful growth. Look at the career's own salary trajectory over 5-10 years, not just the entry-level number, before judging whether it's viable."},
    {"category": "salary", "career_id": None, "question": "Why does my child's dream career pay so much less than their friend's job in finance or tech?", "expert_response": "Different fields genuinely compensate differently based on market supply and demand, not the value or difficulty of the work — a teacher and an investment banker can both work extremely hard, and the market simply prices them differently. It's worth having an honest conversation about the tradeoff between compensation and other things that matter, like meaning, stability, or lifestyle, rather than treating salary as the only measure of a good career choice."},
    {"category": "salary", "career_id": None, "question": "Is it true that creative careers never pay well?", "expert_response": "Some creative fields genuinely have unpredictable, often modest income, especially early on — that's an honest reality worth planning for financially. But many creative professionals build stable, well-paying careers over time, especially those who combine creative skill with some business or technical specialization, so it's not a uniform 'never.'"},
    {"category": "salary", "career_id": "startup_founder", "question": "How will my child pay their bills while starting a company with no income?", "expert_response": "Most founders either have savings set aside, take on part-time work, or rely on family support during the earliest, unpaid stage of a startup — this is a real, serious financial planning question worth discussing directly and honestly before they commit, not after."},
    {"category": "salary", "career_id": "teacher_k12", "question": "Is teaching pay really as low as people say?", "expert_response": "In most countries, yes — teaching salaries are genuinely modest relative to the training and emotional demands involved, and this is a real, known tradeoff of the profession, not a myth. Growth into leadership or specialized roles does improve pay meaningfully over a career, but going in expecting a high salary would be a mismatch with reality."},
    {"category": "salary", "career_id": None, "question": "Should my child choose a lower-paying career they love over a higher-paying one they're just okay with?", "expert_response": "There's no universally right answer, but research on career satisfaction consistently shows that people who dislike their daily work experience real, cumulative stress that affects their whole life — a moderately-paying job someone is genuinely engaged in often outperforms a high-paying job someone dreads, though this depends on your family's actual financial needs and constraints."},
    {"category": "salary", "career_id": None, "question": "How long does it typically take to reach a 'good' salary in a new field?", "expert_response": "This varies enormously by field, but a common pattern across many professional careers is: 1-3 years of relatively low entry pay while building real skills, 3-7 years of meaningful growth, and then a longer plateau or continued growth depending on the specific trajectory chosen (specialist, management, business ownership)."},
    {"category": "salary", "career_id": "ngo_program_manager", "question": "Can you actually build a stable financial life working in the nonprofit sector?", "expert_response": "Entry-level nonprofit and NGO work is often genuinely low-paid or even unpaid, which is a real financial hurdle worth planning for. However, program management and senior leadership roles at established organizations can pay reasonably well — the honest answer is that early-career sacrifice is common in this field, with financial stability generally arriving later than in corporate careers."},
    {"category": "salary", "career_id": None, "question": "Is it worth taking on student debt for a career that doesn't pay especially well?", "expert_response": "This is worth calculating concretely — compare the total debt against the realistic starting and 5-year salary for that specific career, not a rough guess. Some meaningful, lower-paying careers are still worth the debt if it's modest; a large debt load against a genuinely low-paying field is a real financial risk worth discussing honestly with your child."},
    {"category": "salary", "career_id": None, "question": "Why do some technical careers pay so much more than others that seem equally hard?", "expert_response": "Pay differences often reflect how scarce a specific skill set is relative to demand right now, not just how difficult the work is — a newer, high-demand specialization can pay significantly more than an equally rigorous but more common field simply because fewer people currently have that skill."},
    {"category": "salary", "career_id": None, "question": "Should salary be the main factor in choosing a career?", "expert_response": "Most career counselors would say no — salary matters, especially for basic financial security, but factors like job stability, growth potential, and genuine day-to-day satisfaction compound over a multi-decade career in ways a single starting salary number doesn't capture."},
    {"category": "salary", "career_id": "conservation_biologist", "question": "Is it realistic to make a stable living in wildlife conservation?", "expert_response": "It's genuinely modest compared to many other sciences, especially at nonprofit organizations — this is an honest tradeoff of mission-driven work. Government conservation agency roles and senior positions at larger, established conservation organizations offer more competitive, stable pay if that's a real priority."},
    {"category": "salary", "career_id": None, "question": "How much does location affect what my child can realistically earn in a career?", "expert_response": "Enormously — the same job title can pay very differently depending on the country or even city, reflecting local cost of living and market demand. It's worth researching the specific local salary range for a career in the actual place your child plans to work, not a global average."},
    {"category": "salary", "career_id": "accountant", "question": "Does getting a professional certification really make a big difference to accounting salaries?", "expert_response": "Yes, generally a significant one — professional certification (like a CPA or equivalent) is one of the clearest, most well-documented salary boosts in accounting, often unlocking senior roles and leadership tracks that are much harder to reach without it."},
    {"category": "salary", "career_id": None, "question": "Is it true that freelance and creative careers have very unpredictable income?", "expert_response": "Often yes, especially in the first few years — freelance and creative income can vary significantly month to month, which is a real, honest planning consideration. Many established freelancers eventually build more predictable income through repeat clients or diversified income streams, but the early unpredictability is genuine, not exaggerated."},
    {"category": "salary", "career_id": None, "question": "How do I know if a starting salary offer is actually fair for the field?", "expert_response": "Look at multiple real sources — industry salary surveys, professional association data, and if possible, direct conversations with people already working in that specific role and location — rather than relying on a single online estimate, which can be inaccurate or outdated."},
    {"category": "salary", "career_id": "ias_officer_india", "question": "Is the salary for civil service roles like the IAS competitive with private sector jobs?", "expert_response": "Not with top private-sector salaries, no — civil service pay is a respectable, stable government scale, but it's genuinely lower than what a similarly talented person might earn at a top private company. The appeal of this specific path is authority, prestige, and public service impact, not maximizing income."},
    {"category": "salary", "career_id": None, "question": "Will my child's salary keep up with inflation and cost of living over their career?", "expert_response": "This depends heavily on the specific field and whether it has structured, regular salary growth — fields with strong ongoing demand tend to see wages track cost of living reasonably well, while fields with oversupplied labor markets or declining demand may not, which is worth researching for the specific career in question."},
    {"category": "salary", "career_id": None, "question": "Is it normal to take a pay cut when switching careers?", "expert_response": "Yes, genuinely common, especially when moving into an unrelated field where you're starting at a more junior level despite prior work experience — many successful career switchers describe an initial pay cut that recovers and often surpasses their previous salary within one to three years."},
    {"category": "salary", "career_id": None, "question": "How much should I worry if my child chooses a career known for modest pay?", "expert_response": "Worth an honest, non-judgmental conversation about their specific financial plans and expectations, rather than blanket worry — many people build genuinely fulfilling, sustainable lives on modest but stable incomes, especially if they've thought realistically about their cost of living and long-term goals."},
    {"category": "salary", "career_id": None, "question": "Do salaries in emerging fields like AI actually live up to the hype?", "expert_response": "In many cases, yes, currently — genuine skill scarcity in fast-growing fields like applied AI is driving real, above-average salaries right now. Worth noting this can shift as more people enter the field, so it's not guaranteed to stay this favorable indefinitely."},
    # --- safety ---
    {"category": "safety", "career_id": None, "question": "Is it safe for my child to work in a field that requires international travel or postings?", "expert_response": "This depends heavily on the specific regions and role — many international careers involve extensive safety training, support systems, and risk protocols provided by the employing organization. It's worth asking specifically what safety infrastructure and protocols exist for the particular role, rather than assuming all international work carries the same risk level."},
    {"category": "safety", "career_id": "human_rights_researcher", "question": "How dangerous is fieldwork in human rights research really?", "expert_response": "It can carry genuine, real risk when working in conflict zones or repressive political environments — this isn't an exaggeration, and reputable human rights organizations take real safety precautions and training seriously. It's worth discussing specifically what fieldwork the role would actually involve, since not all human rights research positions require high-risk field travel."},
    {"category": "safety", "career_id": None, "question": "Are physically demanding careers like firefighting or construction too risky to encourage?", "expert_response": "These fields do carry real physical risk, which is worth acknowledging honestly rather than dismissing — but they also have rigorous, continuously improving safety training and protocols specifically designed to manage that risk. Many people build long, stable careers in these fields; the risk is real but managed, not reckless."},
    {"category": "safety", "career_id": None, "question": "Is working night shifts in emergency services or healthcare genuinely harmful to long-term health?", "expert_response": "Shift work does carry real, documented health considerations, including effects on sleep and long-term wellbeing — this is a legitimate concern worth discussing. Many people in these careers manage it successfully with deliberate sleep hygiene and self-care practices, but it's honest to acknowledge the real physical toll rather than dismiss it."},
    {"category": "safety", "career_id": None, "question": "How can I know if a workplace or industry takes employee safety seriously?", "expert_response": "Look for specific, concrete safety protocols and training the employer describes, not vague reassurances — ask directly during any interview process about safety incidents, protocols, and support systems, and take note of how seriously and specifically the employer answers."},
    {"category": "safety", "career_id": None, "question": "What's the real physical and emotional risk in emergency medical work?", "expert_response": "Genuinely real on both fronts — paramedics face physical risk in emergency response situations and significant emotional/psychological demands from repeated exposure to trauma. Reputable emergency services provide real training and increasingly, mental health support, but this is honest, serious work that deserves a clear-eyed conversation, not minimization."},
    {"category": "safety", "career_id": None, "question": "Is it safe for my child to pursue a career that involves working alone in remote locations, like field research?", "expert_response": "Reputable research organizations and employers have real safety protocols for remote fieldwork, including communication check-ins and emergency response plans — worth asking specifically what those protocols look like for the particular role, rather than assuming all remote fieldwork is equally risky."},
    {"category": "safety", "career_id": None, "question": "Are online/remote careers actually safer than in-person, physically demanding ones?", "expert_response": "Generally yes in terms of physical risk, though remote/online work carries its own real considerations — isolation, screen-time health effects, and sometimes less job security. 'Safer' physically doesn't automatically mean better overall; it's worth weighing the full picture."},
    {"category": "safety", "career_id": None, "question": "How do I talk to my child about a career choice that involves real physical risk without being overly discouraging?", "expert_response": "Focus the conversation on understanding the actual safety training and protocols involved, not just the general risk level — asking specific, informed questions together shows genuine engagement rather than blanket discouragement, and often reveals that risks are more managed than they initially appear."},
    {"category": "safety", "career_id": None, "question": "Is psychological safety (burnout, mental health) as important a concern as physical safety in choosing a career?", "expert_response": "Increasingly, career experts would say yes — burnout and chronic stress in demanding fields cause real, documented long-term harm, similar in seriousness to physical safety risks in more traditionally 'dangerous' jobs. It's worth asking about mental health support and realistic workload expectations for any career under consideration."},
    # --- stability ---
    {"category": "stability", "career_id": None, "question": "How can we tell if a career field will still exist in 15-20 years?", "expert_response": "No one can predict this with certainty, but look at the underlying human need the career serves — fields addressing durable needs (healthcare, education, infrastructure, food) tend to be more stable than those tied to a single current technology trend. Also look at how many countries and industries currently rely on the skill, which indicates broader structural demand rather than a narrow, faddish niche."},
    {"category": "stability", "career_id": None, "question": "Is it risky for my child to pursue a brand-new career field that didn't exist a decade ago?", "expert_response": "There's real uncertainty in newer fields — job titles and required skills are still standardizing, and long-term demand isn't as proven as in established careers. That said, newer fields often offer genuine opportunity precisely because of less competition; it's a real tradeoff between certainty and opportunity worth discussing openly."},
    {"category": "stability", "career_id": None, "question": "Will AI or automation eliminate my child's chosen career?", "expert_response": "This varies enormously by career — some roles involving routine, predictable tasks face real automation pressure, while roles requiring complex judgment, direct human connection, or physical dexterity are more resistant, at least in the near term. It's worth researching what specific automation trends exist for the particular career, rather than assuming blanket risk or blanket safety."},
    {"category": "stability", "career_id": None, "question": "Are government or public sector jobs really more stable than private sector ones?", "expert_response": "Generally yes, in most countries — public sector employment typically offers stronger job security and often pension benefits that many private-sector jobs no longer provide, though this comes with typically lower salary ceilings than the private sector's top-end opportunities."},
    {"category": "stability", "career_id": "startup_founder", "question": "Is entrepreneurship ever really a 'stable' path, or is that a contradiction?", "expert_response": "Being direct here: entrepreneurship is genuinely not a stable path in the traditional sense — there's no guaranteed income or job security, and most ventures don't succeed financially. The 'stability' some founders eventually find comes after significant risk and often multiple attempts, not from the path itself."},
    {"category": "stability", "career_id": None, "question": "How much should economic downturns factor into choosing a career?", "expert_response": "Worth real consideration — some fields (healthcare, essential infrastructure, education) tend to be more resistant to economic downturns than others (luxury goods, discretionary spending-dependent industries), and understanding this can inform a more resilient career choice, though it shouldn't be the only factor."},
    {"category": "stability", "career_id": None, "question": "Is it better to choose a stable but less exciting career, or a less stable but more exciting one?", "expert_response": "This is a genuinely personal tradeoff without a universal right answer — some people thrive with the security of stability, while others find that a stable but unfulfilling career leads to disengagement over time. Understanding your child's actual risk tolerance and what genuinely motivates them matters more than a generic rule."},
    {"category": "stability", "career_id": None, "question": "How often do people actually change careers entirely, and does that undermine the idea of 'stability'?", "expert_response": "Multiple career changes across a working life are increasingly common and not necessarily a sign of instability — many professionals build a stable, secure life while changing specific roles or even fields several times, especially as they gain transferable skills and confidence."},
    {"category": "stability", "career_id": None, "question": "Is job security less important than it used to be?", "expert_response": "The nature of job security has genuinely shifted — fewer people spend an entire career at one employer than in previous generations, but this doesn't necessarily mean less overall stability, since transferable skills and a strong professional reputation can provide security across multiple employers rather than one."},
    {"category": "stability", "career_id": None, "question": "How do I know if a career is genuinely growing in demand versus just currently trendy?", "expert_response": "Look for structural drivers behind the demand — is it tied to a lasting demographic, technological, or regulatory trend (aging populations needing healthcare, climate regulation requiring sustainability expertise), or is it tied to a shorter-term hype cycle that could fade? Structural drivers tend to indicate more durable demand."},
    # --- work_life_balance ---
    {"category": "work_life_balance", "career_id": None, "question": "Which careers genuinely offer good work-life balance, versus just claiming to?", "expert_response": "The most reliable way to know is to talk directly with people actually working in the specific role and company, not just read general claims — ask about real, typical weekly hours, how often work extends into evenings/weekends, and how the organization actually handles time off, not just its stated policy."},
    {"category": "work_life_balance", "career_id": "physician_general", "question": "Do doctors ever get to have a genuinely normal family life?", "expert_response": "It's possible, particularly in general/family medicine as opposed to surgery or emergency specialties, but it requires real intentionality — the training years (medical school, residency) are genuinely demanding, and established practice offers more manageable, though still real, hours."},
    {"category": "work_life_balance", "career_id": "startup_founder", "question": "Is it possible to start a company without sacrificing all personal time?", "expert_response": "Extremely difficult, honestly — most founders describe genuinely poor work-life balance, especially in the first few years, as an unavoidable reality of the path rather than a personal failing to fix. Some founders build in more balance later once the company stabilizes, but the early stage is genuinely all-consuming for most."},
    {"category": "work_life_balance", "career_id": None, "question": "How much does work-life balance vary by country for the same career?", "expert_response": "Significantly — cultural norms and labor regulations around working hours, vacation time, and overtime expectations vary enormously by country, even for the exact same job title and industry, which is worth researching specifically if international work is being considered."},
    {"category": "work_life_balance", "career_id": None, "question": "Is it realistic to expect good work-life balance in a demanding, competitive field?", "expert_response": "It varies by specific role and organization within that field — some companies and teams genuinely prioritize sustainable hours even in competitive industries, while others normalize overwork. It's worth researching the specific employer's real culture, not just assuming the entire field is uniformly demanding."},
    {"category": "work_life_balance", "career_id": None, "question": "How does shift work in emergency services affect family life?", "expert_response": "Real and significant — rotating shifts, including nights and holidays, genuinely disrupt normal family routines and require real, deliberate planning and communication with family members. Many emergency service families adapt successfully, but it's honest to say this requires real, ongoing effort, not something that resolves on its own."},
    {"category": "work_life_balance", "career_id": None, "question": "Do remote or flexible jobs really offer better work-life balance, or is that a myth?", "expert_response": "Often genuinely better in terms of location and schedule flexibility, but remote work can also blur boundaries between work and personal time in its own way, since there's no physical separation between office and home — good work-life balance in a remote role still requires real, deliberate boundary-setting."},
    {"category": "work_life_balance", "career_id": None, "question": "Should work-life balance be a top priority when choosing a career, or is that unrealistic for an ambitious person?", "expert_response": "These aren't necessarily in conflict — many genuinely ambitious, successful professionals prioritize sustainable work-life balance specifically because burnout undermines long-term performance and career longevity. It's a personal values question, not a binary choice between ambition and balance."},
    {"category": "work_life_balance", "career_id": None, "question": "How do seasonal or cyclical careers (like teaching, tax accounting, event planning) affect work-life balance?", "expert_response": "These careers often have a genuine, predictable rhythm — intense periods (school year, tax season, event season) followed by real, calmer periods — which some people find preferable to a uniformly demanding schedule year-round, since the intensity is at least predictable and time-bound."},
    {"category": "work_life_balance", "career_id": None, "question": "What questions should my child ask in a job interview to really understand the work-life balance?", "expert_response": "Direct, specific questions work best: 'What does a typical week look like for someone in this role?' 'How often do people work evenings or weekends?' 'How does the team handle vacation and time off in practice?' — vague policy statements are less reliable than asking about real, lived experience."},
    # --- growth ---
    {"category": "growth", "career_id": None, "question": "How can we tell if a career actually has real room for advancement, versus a flat ceiling?", "expert_response": "Look at the career's typical structured progression — are there clear, well-documented steps from entry-level to senior roles, with real examples of people who've made that climb? Fields with vague or nonexistent advancement structures are worth extra scrutiny before committing long-term."},
    {"category": "growth", "career_id": None, "question": "Is it better to specialize deeply in one area or stay broad and generalist for career growth?", "expert_response": "Both paths lead to real career growth, but they suit different people and fields — deep specialization often commands premium pay and expert status, while broad generalist skills offer more flexibility to pivot between roles and industries. There's no universally superior choice."},
    {"category": "growth", "career_id": None, "question": "Do certifications and additional credentials really matter for career growth, or is experience enough?", "expert_response": "This varies significantly by field — in some professions (accounting, law, medicine), formal certification is essentially required for meaningful advancement; in others (many tech and creative fields), demonstrated real-world experience and a strong portfolio matter more than additional credentials."},
    {"category": "growth", "career_id": None, "question": "How important is it to have a mentor for career growth?", "expert_response": "Genuinely quite important according to most career research — people with real mentorship tend to navigate career decisions and setbacks more effectively and advance more confidently, since a mentor can offer honest, experienced perspective that's hard to get elsewhere."},
    {"category": "growth", "career_id": None, "question": "Is switching employers frequently good or bad for career growth?", "expert_response": "Moderate movement between employers, especially early career, is now widely seen as a normal and often effective way to grow skills and salary faster than staying in one place — though very frequent switching (every year or less) can sometimes raise concerns for employers about commitment, so genuine balance matters."},
    {"category": "growth", "career_id": None, "question": "How do we know if my child's career choice will still offer growth opportunities in 10 years?", "expert_response": "Look at whether the field has a track record of creating new specializations and senior roles as it matures, rather than staying static — fields that are actively evolving (adding new subfields, technologies, or specializations) tend to keep generating fresh growth opportunities over time."},
    {"category": "growth", "career_id": None, "question": "Is graduate school (a master's or PhD) necessary for real career growth in most fields?", "expert_response": "It depends heavily on the specific field — essential in some (academic research, certain scientific specializations), genuinely optional in others (many tech and business roles), and sometimes actively less valuable than real-world experience in fast-moving fields. Worth researching the specific field's actual norms rather than assuming more education always helps."},
    {"category": "growth", "career_id": None, "question": "What's the difference between a career with 'growth potential' and one that's just adding more work for the same pay?", "expert_response": "Real growth potential typically comes with a clear path to meaningfully higher pay, responsibility, or title over time — worth asking directly what the realistic promotion timeline and compensation increase actually look like, rather than assuming more responsibility automatically means real career growth."},
    {"category": "growth", "career_id": None, "question": "How does someone move from an individual contributor role into management, and is that always the 'right' growth path?", "expert_response": "Management is one growth path, but not the only meaningful one — many fields now offer parallel 'expert' or 'principal' tracks for people who want to grow in seniority, pay, and influence without managing people, which suits many individuals better than a management track."},
    {"category": "growth", "career_id": None, "question": "Is it normal to feel unsure about your long-term career growth path in your twenties?", "expert_response": "Extremely normal — most career development happens through real trial and adjustment over years, not a single clear plan set in early adulthood. Encouraging genuine exploration and honest reflection over this period tends to lead to better long-term outcomes than pressure to have it all figured out immediately."},
    # --- international ---
    {"category": "international", "career_id": None, "question": "Which careers genuinely offer opportunities to work internationally?", "expert_response": "Careers with globally standardized skills and credentials (many tech, medical, and engineering roles) tend to be more internationally portable than those tied to a specific country's regulatory or licensing system (like law or certain government roles) — worth researching the specific career's international portability directly."},
    {"category": "international", "career_id": "foreign_service_officer", "question": "How much control does my child have over where they're posted internationally in a diplomatic career?", "expert_response": "Generally limited — most foreign services assign postings based on organizational need, with officers indicating preferences that aren't guaranteed. This real lack of control over location is worth discussing honestly, since it affects family planning significantly."},
    {"category": "international", "career_id": None, "question": "Do international careers pay more or less than staying in one's home country?", "expert_response": "This varies enormously depending on the specific country pairing and career — some international postings offer real pay premiums and allowances, while others may pay comparably or even less than staying local, once cost-of-living differences are factored in."},
    {"category": "international", "career_id": None, "question": "Is it harder to build a stable life while working internationally, moving between countries regularly?", "expert_response": "Frequent international relocation genuinely does create real challenges for building long-term stability — friendships, community, and sometimes family relationships — that's an honest tradeoff worth weighing against the genuine benefits of international experience and exposure."},
    {"category": "international", "career_id": None, "question": "Does having international work experience actually help someone's career back home?", "expert_response": "Often yes — international experience tends to be genuinely valued by employers as evidence of adaptability and cross-cultural competence, though this varies by field and how directly relevant the international experience is to the specific role being sought afterward."},
    {"category": "international", "career_id": None, "question": "How do visa and work authorization requirements affect career choices for international work?", "expert_response": "Significantly, and this is worth researching very specifically and early — visa and work authorization rules vary enormously by country and profession, and some careers have much clearer international mobility pathways (like skilled-worker visa categories) than others."},
    {"category": "international", "career_id": None, "question": "Is it a good idea for my child to study abroad if they want an internationally-focused career?", "expert_response": "It can genuinely help — international study builds real cross-cultural experience, language skills, and often professional networks that support later international career moves, though it's not strictly required for every internationally-oriented career."},
    {"category": "international", "career_id": None, "question": "How does language ability affect international career opportunities?", "expert_response": "Substantially in many fields — genuine fluency in additional languages, especially widely-spoken ones or ones relevant to a specific region of interest, meaningfully expands real international career options and often provides a real competitive advantage."},
    # --- career_switching ---
    {"category": "career_switching", "career_id": None, "question": "Is it too late for my child to switch to a completely different career field in their mid-twenties or thirties?", "expert_response": "Genuinely no — many successful professionals across many fields made a significant career switch in their late twenties, thirties, or even later, and describe it as one of their best decisions despite initial fear. The specific transition path (further education, entry-level restart, transferable skills) matters more than age itself."},
    {"category": "career_switching", "career_id": None, "question": "What's the biggest real risk in switching careers?", "expert_response": "Usually financial — a temporary pay cut or period of lower income while building new skills and credibility in the new field is the most common, honest risk, and worth planning for concretely rather than underestimating."},
    {"category": "career_switching", "career_id": None, "question": "How do we know if my child's dissatisfaction with their current path is a real signal to switch, or just a rough patch?", "expert_response": "Worth distinguishing between a specific, temporary difficulty (a bad manager, a hard project) versus a sustained, fundamental mismatch with the actual nature of the work itself — the latter is a stronger signal for a real career switch, while the former might resolve with a change of role or employer within the same field."},
    {"category": "career_switching", "career_id": None, "question": "Do employers actually take career switchers seriously, or do they prefer candidates with a 'traditional' path?", "expert_response": "Increasingly, many employers value the transferable skills and real-world perspective career switchers bring, especially in fields experiencing genuine talent shortages — the honest reality varies by field and individual employer, but career switching is far more normalized now than a generation ago."},
    {"category": "career_switching", "career_id": None, "question": "How much additional education is typically needed to switch into a new field?", "expert_response": "This varies enormously — some fields require a full new degree or certification, while others value demonstrated skill and a strong portfolio over formal credentials. Worth researching the specific target field's actual hiring norms rather than assuming a full return to school is always necessary."},
    {"category": "career_switching", "career_id": None, "question": "Is it a bad sign if my child has already changed their mind about their career direction once or twice?", "expert_response": "Not inherently — genuine self-discovery through real experience, including changing direction after trying something, is a normal and often healthy part of building a career that actually fits, rather than a sign of instability or lack of seriousness."},
    {"category": "career_switching", "career_id": None, "question": "How can my child test out a new career field before fully committing to switching?", "expert_response": "Real, low-commitment ways to explore include informational interviews with people already in the field, short courses or certifications, volunteer work, or part-time/freelance projects — these provide genuine exposure to the day-to-day reality of a field before a full financial and time commitment to switching."},
    {"category": "career_switching", "career_id": None, "question": "What transferable skills actually matter most when switching careers?", "expert_response": "Communication, problem-solving, project management, and any genuinely specific technical or analytical skills tend to transfer well across many fields — it's worth having your child specifically articulate what skills from their current path would genuinely apply to the new one, rather than assuming everything transfers or nothing does."},
    # --- other ---
    {"category": "other", "career_id": None, "question": "How do I support my child in a career choice I personally don't fully understand or feel excited about?", "expert_response": "Genuine curiosity goes a long way — asking real, specific questions about what the work actually involves, rather than expressing skepticism, helps your child feel supported while also giving you real understanding to evaluate the choice on its actual merits, not just your initial unfamiliarity with it."},
    {"category": "other", "career_id": None, "question": "What's the most common mistake parents make when discussing career choices with their children?", "expert_response": "Projecting their own career fears or unfulfilled ambitions onto their child's choice, rather than engaging with the child's actual, specific circumstances and the real facts about the field in question — a career conversation grounded in real information tends to go much better than one grounded in general anxiety."},
    {"category": "other", "career_id": None, "question": "How much weight should personality fit (introvert vs. extrovert, for example) carry in career choice?", "expert_response": "Genuinely meaningful — research on career satisfaction consistently shows that a mismatch between someone's natural working style and their career's daily demands (constant social interaction for an introvert, or isolated solo work for an extrovert) tends to create real, sustained friction, worth taking seriously in career planning."},
    {"category": "other", "career_id": None, "question": "Is it okay for my child to choose a career mainly because they're good at it, even if they're not passionate about it?", "expert_response": "This is a legitimate, common path — many people build satisfying careers around genuine competence and steady interest rather than intense passion, and that competence itself often grows into real satisfaction over time as skill and recognition develop."},
    {"category": "other", "career_id": None, "question": "How do I know if my expectations for my child's career are realistic or outdated?", "expert_response": "Worth researching the actual current state of the specific field directly, rather than relying on assumptions from your own career era — many fields have changed substantially in structure, pay, and stability even over the past decade, and direct, current research helps separate real concerns from outdated assumptions."},
    {"category": "other", "career_id": None, "question": "What if my child's career choice conflicts with our family or cultural expectations?", "expert_response": "This is a genuinely difficult, common tension worth approaching with real, honest conversation on both sides — understanding the specific reasons behind both your expectations and your child's choice, rather than treating it as a simple standoff, tends to lead to a resolution that respects both, even if imperfectly."},
    {"category": "other", "career_id": None, "question": "How can I tell if my child is choosing a career out of genuine interest versus just wanting to seem impressive?", "expert_response": "Genuine interest usually shows up in how someone talks about the actual daily work — the specific tasks and problems involved — rather than just the job title or prestige. A conversation about what a typical day would really look like often reveals whether the interest is grounded in the real work or the appearance of the career."},
    {"category": "other", "career_id": None, "question": "Should my child choose a career based on current job market trends, or on long-term personal interest?", "expert_response": "Ideally a genuine intersection of both — pure trend-chasing risks a mismatch with actual interest and aptitude, while ignoring market realities entirely risks real financial instability. The strongest choices usually come from real interests that also have a viable, researched path to stability."},
    {"category": "other", "career_id": None, "question": "How important is it for my child to 'love' their career, versus just finding it acceptable?", "expert_response": "This varies by individual — some people need deep passion to sustain motivation through a demanding career, while others do well with a career that's simply engaging and stable, finding deeper fulfillment outside of work. There's no single right answer, and it's worth understanding which type your child genuinely is."},
    {"category": "other", "career_id": None, "question": "What should I do if I disagree with my child's career choice but they seem set on it?", "expert_response": "Sharing your specific, genuine concerns once, clearly and respectfully, is reasonable — but repeated pressure after that tends to damage the relationship without changing the outcome. Trusting your child with the real consequences of their own informed choice, while staying available for support if it doesn't work out, is often the more constructive path."},

    # --- second wave, padding toward the 150-200+ target with continued
    # category and career-specific diversity ---

    # salary
    {"category": "salary", "career_id": "genomics_data_scientist", "question": "Does working in academic research pay as well as working for a biotech company?", "expert_response": "Generally no — industry roles at pharmaceutical or biotech companies pay meaningfully more than equivalent academic research positions, which is an important, honest factor to weigh alongside the different day-to-day nature of academic versus industry research work."},
    {"category": "salary", "career_id": "developer_relations_engineer", "question": "Is developer relations a well-paid tech career compared to straightforward software engineering?", "expert_response": "Generally comparable at similar seniority levels, since the role requires genuine technical skill alongside communication ability — though it can be seen as a less 'essential' role at some companies, which sometimes affects negotiating leverage compared to core engineering positions."},
    {"category": "salary", "career_id": None, "question": "How do bonuses and equity compensation factor into understanding a real salary offer?", "expert_response": "These can meaningfully change total compensation, especially at startups or tech companies, but they're also less certain than base salary — equity in particular can be worth very little if a company doesn't succeed, so it's worth evaluating the base salary as the reliable floor and treating bonuses/equity as a genuine but uncertain upside."},
    {"category": "salary", "career_id": None, "question": "Is it common for salaries to differ significantly between men and women in the same role, and what should we know?", "expert_response": "Unfortunately, real pay gaps persist in many fields and countries, even for comparable roles and experience — it's worth encouraging your child to research typical salary ranges for a role independently and to negotiate confidently based on that real market data, rather than accepting a first offer without comparison."},
    {"category": "salary", "career_id": "materials_research_scientist", "question": "Do materials scientists in industry earn more than those in pure academic research?", "expert_response": "Yes, generally — industry roles at electronics, energy, or manufacturing companies tend to pay meaningfully more than academic research positions, similar to the pattern in many other applied sciences."},
    {"category": "salary", "career_id": None, "question": "How should we think about salary negotiation for a first job out of school?", "expert_response": "Even first-job offers are often somewhat negotiable, particularly at larger companies — researching typical starting salary ranges for the specific role and location beforehand, and asking directly and respectfully if there's room to discuss the offer, rarely hurts and sometimes meaningfully improves the outcome."},
    {"category": "salary", "career_id": None, "question": "Is it a red flag if a company is unusually secretive about salary ranges?", "expert_response": "It's worth noting, though pay transparency norms vary by country and industry — some places now legally require posted salary ranges, while others don't. A company's general openness (or lack of it) about compensation can be one small data point about its broader culture, worth weighing alongside other factors."},
    {"category": "salary", "career_id": None, "question": "Does having a graduate degree always lead to a higher salary?", "expert_response": "Not universally — in some fields a graduate degree meaningfully raises earning potential, while in others (particularly fast-moving tech fields), real-world experience and demonstrated skill can matter more than an additional degree, sometimes making the financial return on graduate school genuinely unclear."},
    {"category": "salary", "career_id": "ux_researcher", "question": "Is UX research a financially secure career choice within tech?", "expert_response": "At established companies with mature product teams, yes, generally comparable to other solid tech salaries — though it's worth noting this role can be more vulnerable to cuts at smaller or resource-constrained companies during downturns than core engineering roles."},

    # safety
    {"category": "safety", "career_id": "space_systems_engineer", "question": "Is working in the space industry physically dangerous?", "expert_response": "The engineering and design work itself is largely office and lab-based with standard workplace safety, not physically dangerous in the way field or emergency work can be — the real 'stakes' in this field are about the safety of the systems being designed, not physical risk to the engineer personally."},
    {"category": "safety", "career_id": None, "question": "How do I know if my child's workplace has a genuinely healthy culture around mental health?", "expert_response": "Look for concrete signals — does the organization offer real mental health resources, do people actually take their allotted time off without guilt, and does leadership model healthy boundaries themselves? Vague wellness policies without visible real behavior change are worth being skeptical of."},
    {"category": "safety", "career_id": None, "question": "Is it safe to work for a very small startup versus an established company?", "expert_response": "Small startups carry real financial and job-security risk (many fail), which is a different kind of 'safety' concern than physical workplace safety — it's worth having an honest conversation about your child's risk tolerance for job instability specifically, separate from any physical safety question."},
    {"category": "safety", "career_id": None, "question": "How can my child protect themselves from workplace harassment or unsafe treatment?", "expert_response": "Understanding their legal rights and the specific company's reporting and HR processes before an issue arises is genuinely valuable — researching a prospective employer's real reputation and asking about these processes directly during the interview stage is a reasonable, proactive step."},
    {"category": "safety", "career_id": None, "question": "How risky is working closely with large or unpredictable animals as a veterinarian?", "expert_response": "There's real, inherent physical risk working with large or distressed animals, which reputable veterinary training and workplaces take seriously through handling protocols and safety equipment — it's honest to acknowledge this risk exists while noting that experienced professionals manage it successfully as a routine part of the job."},
    {"category": "safety", "career_id": None, "question": "Are there real legal protections for whistleblowers or people who report safety issues at work?", "expert_response": "This varies significantly by country and industry, and it's worth researching the specific legal protections in your child's jurisdiction — many countries do have real whistleblower protections, though enforcement and real-world effectiveness vary."},

    # stability
    {"category": "stability", "career_id": "developer_relations_engineer", "question": "Is developer relations a stable long-term career, or a role that might disappear?", "expert_response": "It's a genuinely newer role type without the long track record of more established careers, which carries some real uncertainty — but demand for it is currently strong at companies with developer-facing products, and the underlying skills (technical communication, community building) are broadly transferable even if the specific title evolves."},
    {"category": "stability", "career_id": "clinical_research_coordinator", "question": "Is clinical research work stable given how pharmaceutical funding can fluctuate?", "expert_response": "Reasonably stable overall — while individual trial funding can be tied to specific pharmaceutical company priorities, the broader clinical research industry has consistent, ongoing demand, providing genuine field-level stability even as specific projects come and go."},
    {"category": "stability", "career_id": None, "question": "How do labor unions affect job stability in certain careers?", "expert_response": "In unionized fields, real collective bargaining protections often provide meaningfully greater job security and more predictable working conditions than in non-unionized equivalent roles — worth researching whether a specific career and country has a strong union presence if stability is a real priority."},
    {"category": "stability", "career_id": None, "question": "Is it riskier to work for a large multinational company or a smaller local business?", "expert_response": "Large multinationals often (though not always) offer more structural stability and benefits, while smaller businesses can offer more role flexibility but sometimes less financial cushion during downturns — this is a real, genuine tradeoff worth discussing based on your child's specific risk tolerance."},
    {"category": "stability", "career_id": None, "question": "How does industry consolidation (companies merging or being acquired) affect career stability?", "expert_response": "It's a real, genuine risk in industries prone to frequent mergers and acquisitions, since restructuring after a merger often includes layoffs — worth researching whether a specific target industry has a history of frequent consolidation as one factor in assessing overall stability."},
    {"category": "stability", "career_id": None, "question": "Is it more stable to work in a large city versus a smaller town for the same career?", "expert_response": "Larger cities generally offer more total job opportunities and easier lateral moves if one position ends, providing a kind of structural stability through options — smaller towns can offer strong stability too if there's a genuinely dominant local employer or industry, but with fewer alternatives if that specific situation changes."},

    # work_life_balance
    {"category": "work_life_balance", "career_id": "urban_planner", "question": "Does urban planning involve a lot of evening or weekend work?", "expert_response": "Regular evening commitments for public hearings and community consultation meetings are a real, expected part of the job, though the overall workload outside of these specific commitments is generally standard business hours — a real, predictable pattern rather than constant overtime."},
    {"category": "work_life_balance", "career_id": None, "question": "How does having children affect work-life balance in demanding careers?", "expert_response": "This varies enormously by specific employer culture and available support (parental leave policies, flexible scheduling, childcare support) more than by career field alone — worth researching a specific employer's actual family-friendly policies and asking current employees about their real, lived experience."},
    {"category": "work_life_balance", "career_id": None, "question": "Is 'hustle culture' — the idea that overwork is admirable — actually good for a career?", "expert_response": "Increasingly, career research suggests sustained overwork leads to burnout and actually undermines long-term career performance and satisfaction, despite the cultural narrative that it's admirable — many high-performing professionals now actively prioritize sustainable pacing over constant hustle."},
    {"category": "work_life_balance", "career_id": None, "question": "How much vacation time is typical, and does it vary a lot by country?", "expert_response": "Significantly — vacation entitlements vary enormously by country, from legally mandated minimums in many countries to much more limited, employer-discretionary time off elsewhere. Worth researching the specific national norms for wherever your child plans to work."},
    {"category": "work_life_balance", "career_id": "product_led_growth_specialist", "question": "How demanding are tech growth roles in terms of hours?", "expert_response": "Generally standard tech-industry hours, with periodic intensity around major experiment launches or product changes — not typically among the most demanding tech roles, though this varies by specific company culture and growth stage."},

    # growth
    {"category": "growth", "career_id": "public_health_policy_analyst", "question": "What does a realistic growth path look like in public health policy work?", "expert_response": "A fairly clear, structured trajectory exists — from policy research assistant to senior policy advisor and eventually director-level roles, often taking 10-15 years, with real opportunities to specialize in a specific policy area for deeper expertise and influence along the way."},
    {"category": "growth", "career_id": None, "question": "Does working at a big, well-known company versus a small company affect long-term career growth differently?", "expert_response": "Big companies often provide more structured training and clear promotion ladders, while small companies can offer faster, broader responsibility and skill-building due to wearing many hats — both are genuinely valid paths to real growth, just through different mechanisms."},
    {"category": "growth", "career_id": None, "question": "How do professional networks actually help with career growth, beyond just getting a first job?", "expert_response": "A genuine professional network provides ongoing access to real information about opportunities, industry trends, and honest advice throughout an entire career, not just at the entry-level stage — it's worth encouraging your child to maintain real relationships with colleagues and mentors over time, not just at job-search moments."},
    {"category": "growth", "career_id": "computational_linguist", "question": "What's the realistic growth trajectory in a fast-moving AI-adjacent field like computational linguistics?", "expert_response": "Growth can be quite rapid given current strong demand — from junior NLP engineer to senior and research leadership roles, sometimes faster than in more established fields, though it requires continuous learning to stay current given how quickly the underlying technology evolves."},
    {"category": "growth", "career_id": None, "question": "Is it common to plateau in a career, and what does that actually mean for someone's future?", "expert_response": "Yes, genuinely common — most careers include real periods of slower growth or plateau, which isn't necessarily a failure but sometimes a signal to actively seek a new challenge, additional training, or a lateral move to reignite growth, rather than assuming growth should always be linear."},

    # international
    {"category": "international", "career_id": "computational_linguist", "question": "Is there strong international demand for people working on underserved or regional languages?", "expert_response": "Yes, genuinely growing demand as the AI field increasingly recognizes the importance of language fairness — researchers and engineers focused on underserved languages are valued both regionally and by major international AI labs seeking that specific expertise."},
    {"category": "international", "career_id": None, "question": "How does having dual citizenship or international family ties affect career mobility?", "expert_response": "It can genuinely simplify international work authorization significantly in relevant countries, removing a real barrier that many international workers face — worth factoring in as a real practical advantage if it applies to your child's specific situation."},
    {"category": "international", "career_id": None, "question": "Are there specific fields where international experience is essentially required for career advancement?", "expert_response": "Some fields, particularly international diplomacy, global development, and certain multinational corporate roles, do genuinely expect or require international experience for senior advancement — worth researching whether this is true for the specific field your child is considering."},
    {"category": "international", "career_id": None, "question": "How do professional licenses and certifications transfer (or not) between countries?",  "expert_response": "This varies enormously and is a genuinely important practical question — some professions (like certain engineering and IT certifications) transfer relatively easily internationally, while others (particularly law, medicine, and some regulated professions) often require significant additional local certification, which is worth researching specifically before assuming easy portability."},

    # career_switching
    {"category": "career_switching", "career_id": None, "question": "What's a realistic timeline for successfully switching careers?", "expert_response": "This varies by the size of the change, but a common honest range is 6 months to 2 years from initial decision to feeling settled in the new field, including any needed additional training or credential-building — expecting an overnight transition tends to create unnecessary frustration."},
    {"category": "career_switching", "career_id": None, "question": "Should my child tell a potential employer why they're switching careers, and how honest should they be?", "expert_response": "Generally yes, and genuine honesty tends to serve candidates well — employers are often reassured by a clear, thoughtful narrative about why the switch makes sense, rather than a story that feels evasive or incomplete."},
    {"category": "career_switching", "career_id": None, "question": "Is it easier to switch careers within the same industry versus switching industries entirely?", "expert_response": "Generally yes — switching roles within a familiar industry preserves more of your existing network and domain knowledge, making the transition somewhat smoother than switching both role and industry simultaneously, though both are genuinely achievable with the right preparation."},

    # other
    {"category": "other", "career_id": None, "question": "How do we distinguish between healthy ambition and unrealistic career expectations?", "expert_response": "Healthy ambition is usually grounded in genuine, specific research about a field's real requirements and timeline, while unrealistic expectations often skip that research in favor of an idealized outcome — encouraging your child to talk to real people currently in the field is one of the best ways to ground ambition in reality."},
    {"category": "other", "career_id": None, "question": "Should career choice be treated as a permanent, one-time decision?", "expert_response": "No — most career research now treats career development as an ongoing, evolving process across a working life, not a single irreversible choice made once. Framing it this way tends to reduce pressure and anxiety around any single decision point."},
    {"category": "other", "career_id": None, "question": "How much should my child's personality assessment or aptitude test results influence their career choice?", "expert_response": "These tools can offer genuinely useful starting points for reflection, but they shouldn't be treated as definitive verdicts — real interest, values, and lived experience trying out different activities tend to be more reliable guides than a single assessment result."},
    {"category": "other", "career_id": None, "question": "What role should financial pressure from the family play in a child's career decision?", "expert_response": "It's honest and reasonable to discuss real family financial circumstances and expectations openly, but it's worth distinguishing between genuine necessity and unstated preference — a transparent conversation about what's actually required versus preferred tends to lead to decisions both generations can support."},
    {"category": "other", "career_id": None, "question": "How can I help my child research a career field without just telling them what to do?", "expert_response": "Asking guiding questions and helping identify real people to talk to or resources to explore — rather than presenting conclusions — tends to build your child's own genuine understanding and ownership of the decision, which supports better long-term commitment than a decision made mainly to satisfy a parent."},

    # --- third wave, closing the gap to the 150-200+ target ---

    # salary
    {"category": "salary", "career_id": "civil_engineer", "question": "Do civil engineers need a master's degree to earn a good salary?", "expert_response": "Not typically for core practicing roles — a bachelor's degree plus professional licensure is usually sufficient for solid, professional-level pay; a master's tends to matter more for those pursuing specialized research or academic paths within the field, not baseline earning potential."},
    {"category": "salary", "career_id": "bioinformatics_scientist", "question": "Is it worth choosing a bioinformatics career over general software engineering purely for pay?", "expert_response": "If salary alone is the deciding factor, general software engineering often has a wider range of high-paying opportunities — bioinformatics makes more sense as a choice when there's genuine interest in biological science alongside the technical work, not purely as a financial optimization."},
    {"category": "salary", "career_id": None, "question": "How much does company size affect salary for the same role?", "expert_response": "Often significantly — larger, well-funded companies frequently pay more than smaller ones for comparable roles, though smaller companies sometimes offer meaningful equity upside or faster growth in scope of responsibility that can offset lower base pay over time."},
    {"category": "salary", "career_id": None, "question": "Is a career with high average pay but high variability (like sales or freelance work) better or worse than one with lower but consistent pay?",  "expert_response": "This depends heavily on your family's real financial risk tolerance and safety net — high-variability income can work well for someone with savings or other support who can weather slow periods, while consistent lower income may better serve someone who needs predictable cash flow."},

    # safety
    {"category": "safety", "career_id": None, "question": "How dangerous is mining engineering, and has it gotten safer over time?", "expert_response": "Mining carries real, inherent safety considerations, particularly in underground operations, but the field has made genuine, significant safety improvements over recent decades through better ventilation, monitoring, and safety engineering — modern mining safety engineering roles specifically focus on continuing to reduce that real risk."},
    {"category": "safety", "career_id": None, "question": "How can I evaluate whether an employer's safety record is actually good, not just well-marketed?", "expert_response": "Look for publicly available safety incident data where it exists (common in regulated industries), and ask directly during the interview process about recent safety incidents and how they were handled — a company willing to discuss real incidents honestly is often a better sign than one that claims a spotless record without specifics."},
    {"category": "safety", "career_id": None, "question": "Are there real differences in workplace safety standards between countries that we should consider?", "expert_response": "Yes, genuinely significant differences exist in regulatory enforcement and workplace safety culture between countries, even for the same industry — worth researching the specific national safety standards and enforcement record if international work is being considered, rather than assuming uniform global standards."},

    # stability
    {"category": "stability", "career_id": "health_informatics_specialist", "question": "Is health informatics a stable field given how quickly healthcare technology changes?", "expert_response": "Genuinely stable at a structural level — healthcare systems worldwide are in a long-term, sustained process of digitizing and modernizing data infrastructure, which isn't a short-term trend, even though the specific tools and systems used will keep evolving."},
    {"category": "stability", "career_id": "sustainability_analyst", "question": "Is corporate sustainability work stable, or does it disappear when companies want to cut costs?", "expert_response": "Increasingly stable and even growing, because sustainability reporting is becoming a genuine regulatory requirement in many regions, not just a voluntary initiative that gets cut in tough times — this regulatory backing provides real, structural job security that didn't exist as strongly a decade ago."},
    {"category": "stability", "career_id": None, "question": "How can we assess whether a specific employer is financially stable before my child accepts a job there?", "expert_response": "For public companies, financial reports are genuinely available and worth a basic review; for private companies, checking recent funding news, employee review sites, and simply asking direct questions about company financial health during the interview process are all reasonable, real steps to take."},

    # work_life_balance
    {"category": "work_life_balance", "career_id": "neuroscience_postdoc", "question": "Do postdoctoral researchers have any real work-life balance, or is it all-consuming?", "expert_response": "Often genuinely demanding, with hours driven by experiment timelines and publication pressure rather than a fixed schedule — this is a real, known tradeoff of the research training path that's worth discussing honestly rather than assuming it resembles a standard 9-to-5 research job."},
    {"category": "work_life_balance", "career_id": None, "question": "How do part-time or reduced-hour career paths affect long-term career trajectory?", "expert_response": "This varies by field and employer, but it's honest to note that reduced-hour paths can sometimes slow promotion timelines in traditionally structured careers, while some fields and companies now offer genuinely equitable part-time tracks — worth researching the specific field and employer's actual track record on this."},

    # growth
    {"category": "growth", "career_id": "ai_ops_specialist", "question": "How quickly can someone advance in a fast-growing field like AI operations?", "expert_response": "Potentially quite quickly given current strong demand and a real shortage of experienced practitioners — but this also means the field's career ladder is less established than in mature fields, so growth may look more like expanding scope and responsibility than a clearly defined promotion track."},
    {"category": "growth", "career_id": None, "question": "Does starting a career in a big city versus a smaller one affect long-term growth opportunities?", "expert_response": "Big cities generally offer more concentrated opportunities and easier networking within an industry, which can accelerate growth — though remote work has meaningfully reduced this gap for many fields in recent years, worth factoring into a realistic assessment."},

    # international
    {"category": "international", "career_id": "ngo_program_manager", "question": "Does international development work always require living abroad?", "expert_response": "Not necessarily — many program management roles are based at an organization's headquarters, coordinating field teams remotely, though field-based roles requiring relocation do exist and are common, especially earlier in a career in this sector."},
    {"category": "international", "career_id": None, "question": "How does currency fluctuation affect the real value of an international salary offer?", "expert_response": "This can matter significantly, especially for roles paid in a different currency than where the money will ultimately be spent or saved — worth considering the real, practical purchasing power of an offer in its actual context, not just its face value in a home currency."},

    # career_switching
    {"category": "career_switching", "career_id": None, "question": "Is it common for people to switch careers more than once in their working life?", "expert_response": "Increasingly yes — multiple career transitions across a working life are now a normal pattern for many professionals, especially as industries and required skills continue to evolve; a single, unchanging career path is less the norm than it once was."},
    {"category": "career_switching", "career_id": None, "question": "What's the best way to build a financial cushion before attempting a risky career switch?", "expert_response": "A common, reasonable guideline is 6-12 months of essential living expenses saved before making a significant, uncertain career transition — though the right amount depends on the specific switch's real risk level and how quickly income is likely to stabilize in the new field."},

    # other
    {"category": "other", "career_id": None, "question": "How do we know when a career conversation with our child has become unproductive or damaging?", "expert_response": "If the same disagreement keeps repeating without new information or genuine listening on either side, and it's straining the relationship itself, it's often a sign to pause the direct debate and instead seek a neutral third party — a counselor or someone in the field — to help ground the conversation in real facts rather than repeated positions."},
    {"category": "other", "career_id": None, "question": "Is it normal for a teenager or young adult to have no clear career direction at all yet?", "expert_response": "Completely normal — most meaningful career clarity develops gradually through real exposure to different fields and honest self-reflection over years, not from a single moment of realization; pressure to have it all figured out early can actually work against genuine, well-grounded career discovery."},
]


async def seed() -> None:
    client = get_supabase_client()
    questions = [
        ParentQuestion(id=f"pq_{i:04d}", **q) for i, q in enumerate(QUESTIONS, start=1)
    ]

    def _upsert() -> None:
        client.table("parent_questions").upsert([q.model_dump(mode="json") for q in questions]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(questions)} parent questions.")


if __name__ == "__main__":
    asyncio.run(seed())
