"""Journey Stories — Healthcare, Environment & Trades domain group
(Connect Batch 2). 25 new composite Journey Stories across 5 careers:
Physician (General Practice), Conservation Biologist, Traditional Craft
Master (Shokunin), International NGO Program Manager, Civil Engineer.
Every entry is an illustrative composite persona
(`story_type="composite"`) — never a claim of a specific real
individual.

Run via: python -m aureon.scripts.seed_journey_stories_healthcare_environment_and_trades
Idempotent: safe to re-run (upsert on id).
"""

import asyncio

from aureon.domain.models.career import CareerStory
from aureon.services.supabase.client import get_supabase_client

STORIES: list[dict] = [
    # --- Physician (General Practice) ---------------------------------------
    {
        "id": "story_physician_general_2", "career_id": "physician_general",
        "person_label": "Family Physician, 3 years experience",
        "background": "Failed to gain admission to medical school on a first application cycle, and worked as a medical assistant for two years while reapplying.",
        "journey": "Used the two years as a medical assistant to build clinical exposure the first application had lacked, gaining admission on a second attempt.",
        "challenges": "Faced real self-doubt during the two-year gap about whether medicine was still a realistic goal after the initial rejection.",
        "turning_points": "A supervising physician during the medical assistant years specifically encouraging them to reapply, backed by a strong reference letter, restored confidence in the path.",
        "advice": "A first rejection from medical school isn't a final verdict — direct clinical exposure in the interim can genuinely strengthen a second application.",
        "lessons_learned": "Time spent gaining real clinical experience after a rejection can turn out to be more valuable than reapplying immediately without addressing the gap.",
        "trait_tags": ["motivation", "values"],
        "timeline": [
            {"stage": "university", "label": "First medical school rejection", "description": "Failed to gain admission to medical school on a first application cycle.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Medical assistant", "description": "Worked as a medical assistant for two years while reapplying.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "Admission on the second attempt", "description": "Gained admission to medical school on a second application, strengthened by clinical exposure.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": True,
        "uncertainty_period": "Two years of real self-doubt after an initial medical school rejection.",
        "current_outcome": "Works as a family physician, admission secured on a second attempt strengthened by direct clinical experience.",
        "industry": "healthcare", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_physician_general_3", "career_id": "physician_general",
        "person_label": "Family Physician, 12 years experience",
        "background": "Trained and briefly practiced as a physician in another country before immigrating, requiring a full re-qualification process to practice in the new country.",
        "journey": "Spent nearly four years working as a healthcare assistant and completing re-qualification exams before being allowed to practice medicine again.",
        "challenges": "Found it professionally difficult to work in a support role after having already been a fully qualified, practicing physician elsewhere.",
        "turning_points": "Finally being allowed to see patients independently again, after nearly four years, was described as more meaningful than their original medical school graduation had been.",
        "advice": "Re-qualification after immigrating as a trained professional is genuinely difficult, both practically and psychologically — the eventual return to practice is worth the multi-year process.",
        "lessons_learned": "A multi-year professional step backward, forced by re-qualification requirements, doesn't diminish the expertise being rebuilt toward.",
        "trait_tags": ["motivation", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Practicing physician abroad", "description": "Trained and briefly practiced as a physician in another country.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Re-qualification process", "description": "Spent nearly four years as a healthcare assistant completing re-qualification exams.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Practicing independently again", "description": "Was finally allowed to see patients independently again after nearly four years.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Nearly four years of re-qualification, working in a support role after already being a qualified physician.",
        "current_outcome": "Works as a family physician, having rebuilt full practicing status after an immigration-driven re-qualification process.",
        "industry": "healthcare", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_physician_general_4", "career_id": "physician_general",
        "person_label": "Family Physician, 6 years experience",
        "background": "Entered medical school planning to specialize in surgery, drawn to the technical precision and decisive nature of the work.",
        "journey": "A required rotation in family medicine, expected to be the least interesting part of training, revealed an unexpected preference for longitudinal patient relationships over single-procedure interventions.",
        "challenges": "Had to explain the shift away from a higher-prestige surgical specialty to peers and mentors who had assumed the surgical path was set.",
        "turning_points": "Realizing during the rotation that they cared more about a patient's story over years than about a single successful procedure clarified the real preference.",
        "advice": "A required rotation you're dreading can end up revealing more about your genuine preferences than the specialty you entered training already expecting to choose.",
        "lessons_learned": "Prestige within a field, like surgery relative to general practice, doesn't necessarily correlate with genuine personal fit.",
        "trait_tags": ["values", "communication"],
        "timeline": [
            {"stage": "university", "label": "Planning surgery", "description": "Entered medical school planning to specialize in surgery.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A required family medicine rotation", "description": "A required rotation revealed an unexpected preference for longitudinal patient relationships.", "year_label": "Year 3"},
            {"stage": "current_role", "label": "Family Physician", "description": "Chose family medicine over the originally planned surgical specialty.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a family physician, having found longitudinal patient relationships more compelling than a higher-prestige surgical path.",
        "industry": "healthcare", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_physician_general_5", "career_id": "physician_general",
        "person_label": "Family Physician, 20 years experience",
        "background": "Was diagnosed with a chronic illness midway through their own medical career, forcing a period of reduced clinical hours during treatment.",
        "journey": "Returned to full-time family practice after recovery, but with a permanently changed approach to how they discussed chronic illness with their own patients.",
        "challenges": "Faced real professional uncertainty during treatment about whether they'd be able to return to the physically and emotionally demanding pace of full-time practice.",
        "turning_points": "Their own experience as a patient, not just a physician, fundamentally changed how they explained diagnoses and treatment plans to patients afterward.",
        "advice": "Experiencing serious illness yourself, while difficult, can make you a genuinely better physician for patients facing the same uncertainty you once did.",
        "lessons_learned": "Being on the patient side of a diagnosis, even temporarily, provides an understanding of the experience that clinical training alone cannot replicate.",
        "trait_tags": ["values", "communication"],
        "timeline": [
            {"stage": "first_job", "label": "Established family practice", "description": "Practiced family medicine for years before a personal health event.", "year_label": "Year 0"},
            {"stage": "failure", "label": "A chronic illness diagnosis", "description": "Was diagnosed with a chronic illness midway through their career, requiring reduced hours.", "year_label": "Year 15"},
            {"stage": "turning_point", "label": "Returning with a changed approach", "description": "Returned to full-time practice with a fundamentally changed approach to discussing illness with patients.", "year_label": "Year 17"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "A period of reduced clinical hours during treatment, with real uncertainty about returning to full-time practice.",
        "current_outcome": "Continues family practice, personal illness having reshaped how diagnoses and treatment are explained to patients.",
        "industry": "healthcare", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_physician_general_6", "career_id": "physician_general",
        "person_label": "Family Physician, 1 year experience",
        "background": "Was the first in their family to attend university, let alone medical school, in a household with no prior exposure to the medical profession.",
        "journey": "Navigated medical school application and financial aid processes largely alone, without family members who understood the system to guide them.",
        "challenges": "Faced significant unfamiliarity with unwritten norms — networking expectations, informal mentorship culture — that peers from medical families seemed to already know.",
        "turning_points": "A first-generation-student support program at their medical school, connecting them with a mentor who understood the specific gaps, closed much of that informal knowledge deficit.",
        "advice": "If you're navigating a demanding professional path without family precedent, actively seek out formal mentorship — it can substitute for informal knowledge others take for granted.",
        "lessons_learned": "The unwritten norms of a profession can be a real barrier for first-generation entrants, but formal mentorship programs can effectively close that gap.",
        "trait_tags": ["motivation", "values"],
        "timeline": [
            {"stage": "university", "label": "First-generation student", "description": "Was the first in their family to attend university or medical school.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Navigating the system alone", "description": "Faced significant unfamiliarity with unwritten professional norms peers already knew.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A first-generation support program", "description": "A support program connected them with a mentor who closed the informal knowledge gap.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Navigating medical school's unwritten professional norms alone as a first-generation student.",
        "current_outcome": "Works as a family physician, having closed an informal knowledge gap through formal first-generation mentorship.",
        "industry": "healthcare", "story_type": "composite", "source_reference": "",
    },
    # --- Conservation Biologist ----------------------------------------------
    {
        "id": "story_conservation_biologist_2", "career_id": "conservation_biologist",
        "person_label": "Conservation Biologist, 3 years experience",
        "background": "Studied marketing and worked in corporate brand management for four years, entirely disconnected from environmental science.",
        "journey": "Volunteered on weekend habitat restoration projects, which gradually became the most meaningful part of their week, eventually leading to a full career change.",
        "challenges": "Had to complete an entire second undergraduate-equivalent of coursework in ecology, essentially starting over academically in their late twenties.",
        "turning_points": "Being offered a paid seasonal field position, based purely on volunteer track record rather than formal credentials, proved the career change was viable.",
        "advice": "Sustained, consistent volunteer work in a field you're considering can sometimes open doors that formal credentials alone wouldn't yet support.",
        "lessons_learned": "A career change into a credentialed field can sometimes begin through demonstrated commitment via volunteering, before the formal credentials are even finished.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "first_job", "label": "Corporate brand management", "description": "Worked in corporate brand management for four years, disconnected from environmental science.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Weekend habitat restoration", "description": "Volunteered on weekend habitat restoration projects that became the most meaningful part of the week.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "A paid seasonal field position", "description": "Was offered a paid seasonal field position based on volunteer track record.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a conservation biologist, a career change begun through sustained volunteer commitment rather than formal credentials first.",
        "industry": "environmental conservation", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_conservation_biologist_3", "career_id": "conservation_biologist",
        "person_label": "Conservation Biologist, 7 years experience",
        "background": "Grew up in a fishing family whose livelihood depended on a local fish population that collapsed due to overfishing during their teenage years.",
        "journey": "Studied marine biology specifically motivated by wanting to understand and prevent the kind of population collapse that had upended their family's income.",
        "challenges": "Found it professionally and personally complicated to research fisheries policy that sometimes meant advocating for restrictions on the very communities they'd grown up in.",
        "turning_points": "Helping design a sustainable-harvest program that allowed a related fishing community to continue operating, rather than face an outright closure, reconciled the tension.",
        "advice": "Conservation work involving your own community's livelihood is emotionally complicated — look for solutions that balance restriction with continuity, not just prohibition.",
        "lessons_learned": "The most personally meaningful conservation work can also be the most professionally complicated, requiring solutions that don't simply shut communities out.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "school", "label": "A fish population collapse", "description": "Grew up in a fishing family whose livelihood depended on a fish population that collapsed from overfishing.", "year_label": "Year 0"},
            {"stage": "university", "label": "Marine biology, motivated by the collapse", "description": "Studied marine biology motivated by wanting to prevent similar collapses.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "A sustainable-harvest program", "description": "Helped design a sustainable-harvest program allowing a fishing community to continue operating.", "year_label": "Year 7"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a conservation biologist in fisheries, balancing restriction with community continuity rather than simple prohibition.",
        "industry": "environmental conservation", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_conservation_biologist_4", "career_id": "conservation_biologist",
        "person_label": "Conservation Biologist, 5 years experience",
        "background": "Completed a PhD studying a species that, partway through the research, was declared extinct in the wild — an outcome the research had failed to prevent.",
        "journey": "Redirected the remaining PhD research toward captive breeding and reintroduction methodology, rather than treating the extinction as an ending to the work.",
        "challenges": "Carried significant guilt and professional grief over the extinction, despite it resulting from factors well outside their individual control.",
        "turning_points": "The first successful reintroduction of a captive-bred individual from a closely related species gave a tangible sense that the redirected research still mattered.",
        "advice": "A devastating outcome in conservation research, like a species' extinction, doesn't have to end the work — it can redirect it toward preventing the same outcome elsewhere.",
        "lessons_learned": "Professional grief over a conservation failure is real and worth acknowledging, but the underlying expertise built can still be redirected toward genuine impact.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "university", "label": "Studying a species facing extinction", "description": "Studied a species that was declared extinct in the wild during the PhD research.", "year_label": "Year 2"},
            {"stage": "failure", "label": "Extinction in the wild", "description": "The studied species was declared extinct in the wild, an outcome the research failed to prevent.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "A successful reintroduction elsewhere", "description": "The first successful reintroduction of a captive-bred individual from a related species.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Significant professional guilt and grief following a species' extinction during the research.",
        "current_outcome": "Works as a conservation biologist in captive breeding and reintroduction, redirected from an earlier research failure.",
        "industry": "environmental conservation", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_conservation_biologist_5", "career_id": "conservation_biologist",
        "person_label": "Conservation Biologist, 2 years experience",
        "background": "Studied computer science with a focus on data visualization, without a specific interest in ecology or wildlife.",
        "journey": "Took a short-term contract building a data dashboard for a conservation nonprofit and was drawn into full-time conservation work by the fieldwork exposure that came with it.",
        "challenges": "Had to build ecological knowledge largely on the job, since formal training was entirely in computer science rather than biology.",
        "turning_points": "Being invited on a field survey to understand the data they were visualizing revealed an unexpected passion for the fieldwork itself, not just the technical dashboard work.",
        "advice": "A technical contract in an unfamiliar field can be an unplanned way into a career you wouldn't have otherwise considered — stay open to the exposure it provides.",
        "lessons_learned": "Technical skills, like data visualization, can be the entry point into an entirely different field once the underlying subject matter itself becomes genuinely interesting.",
        "trait_tags": ["curiosity", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Computer science, data visualization focus", "description": "Studied computer science with a focus on data visualization.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "A conservation dashboard contract", "description": "Took a short-term contract building a data dashboard for a conservation nonprofit.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "A field survey invitation", "description": "Was invited on a field survey and discovered a passion for the fieldwork itself.", "year_label": "Year 2"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a conservation biologist, having entered the field through an unplanned technical contract.",
        "industry": "environmental conservation", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_conservation_biologist_6", "career_id": "conservation_biologist",
        "person_label": "Senior Conservation Biologist, 15 years experience",
        "background": "Spent the first eight years of a career entirely in field research, with almost no involvement in the policy or funding side of conservation work.",
        "journey": "Was reluctantly promoted into a program leadership role after a mentor's retirement, initially seeing it as a step away from the field work they loved.",
        "challenges": "Missed the direct field research work deeply during the early years of the leadership role, questioning whether they'd made the right move.",
        "turning_points": "Successfully securing multi-year funding for a program that had been on the verge of closure showed a form of impact the individual field research alone couldn't have achieved.",
        "advice": "A move from hands-on field work into program leadership can feel like a loss at first, but it opens a different, larger scale of impact worth genuinely trying.",
        "lessons_learned": "The scale of impact available through securing funding and leading a program can rival, and sometimes exceed, what individual field research alone accomplishes.",
        "trait_tags": ["leadership", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Field research", "description": "Spent eight years entirely in field research with no policy or funding involvement.", "year_label": "Year 0"},
            {"stage": "promotion", "label": "Reluctant program leadership", "description": "Was reluctantly promoted into program leadership after a mentor's retirement.", "year_label": "Year 8"},
            {"stage": "turning_point", "label": "Securing funding for a threatened program", "description": "Secured multi-year funding for a program that had been on the verge of closure.", "year_label": "Year 10"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Early years of the leadership role spent missing direct field research and questioning the move.",
        "current_outcome": "Leads a conservation program, having found a larger-scale form of impact than individual field research alone provided.",
        "industry": "environmental conservation", "story_type": "composite", "source_reference": "",
    },
    # --- Traditional Craft Master (Shokunin) ---------------------------------
    {
        "id": "story_japan_traditional_craft_master_1", "career_id": "japan_traditional_craft_master",
        "person_label": "Traditional Craft Master, 18 years experience",
        "background": "Left a stable corporate office job in their late twenties, against significant family objection, to begin a formal apprenticeship in a traditional craft.",
        "journey": "Spent the first five years of the apprenticeship doing almost entirely preparatory and cleaning work, as is traditional, before being allowed to touch the primary materials directly.",
        "challenges": "Faced serious doubt during those early years about whether the slow, hierarchical apprenticeship system would ever actually lead to real skill development.",
        "turning_points": "Being permitted, after five years, to complete a single small component of a larger piece under the master's supervision marked the first tangible sign of real progress.",
        "advice": "Traditional apprenticeship systems can feel excruciatingly slow by modern standards — trust that the early preparatory years are building foundational skill, not just paying dues.",
        "lessons_learned": "A craft's traditional, slow apprenticeship structure exists for real pedagogical reasons, even when it doesn't feel that way during the early, unglamorous years.",
        "trait_tags": ["work_preferences", "motivation"],
        "timeline": [
            {"stage": "career_transition", "label": "Leaving a corporate job", "description": "Left a stable corporate office job to begin a formal craft apprenticeship, against family objection.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Five years of preparatory work", "description": "Spent five years on preparatory and cleaning work before touching primary materials.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "First supervised component", "description": "Was permitted to complete a single small component of a larger piece under supervision.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Five years of preparatory apprenticeship work with serious doubt about whether it would lead to real skill development.",
        "current_outcome": "Works as a traditional craft master, having trusted a slow, traditional apprenticeship structure through its early years.",
        "industry": "traditional craftsmanship", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_japan_traditional_craft_master_2", "career_id": "japan_traditional_craft_master",
        "person_label": "Traditional Craft Master, 25 years experience",
        "background": "Was born into a family with a multi-generational tradition in the craft, expected from childhood to eventually take over the family workshop.",
        "journey": "Actively rebelled against the expected path as a young adult, working an unrelated corporate job for six years before voluntarily returning to the craft.",
        "challenges": "Had to rebuild trust with an aging parent who had assumed, after the rebellion, that the family tradition might end with their generation.",
        "turning_points": "Choosing to return and formally begin training, entirely voluntarily rather than out of obligation, changed the entire relationship with both the craft and the family.",
        "advice": "If a family tradition feels like an obligation rather than a choice, stepping away and choosing to return later, if you genuinely want to, can make the eventual commitment far more sustainable.",
        "lessons_learned": "A family tradition taken up voluntarily, after genuinely stepping away first, tends to be a far more durable commitment than one accepted only out of obligation.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "school", "label": "Expected to inherit the family craft", "description": "Was expected from childhood to eventually take over the family workshop.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Rebelling against the expected path", "description": "Worked an unrelated corporate job for six years, rebelling against the expected path.", "year_label": "Year 8"},
            {"stage": "turning_point", "label": "Voluntarily returning to the craft", "description": "Chose to return and formally begin training, entirely voluntarily.", "year_label": "Year 14"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Years working an unrelated corporate job, rebelling against an assumed family expectation.",
        "current_outcome": "Works as a traditional craft master, a family tradition ultimately taken up by voluntary choice rather than obligation.",
        "industry": "traditional craftsmanship", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_japan_traditional_craft_master_3", "career_id": "japan_traditional_craft_master",
        "person_label": "Traditional Craft Master, 10 years experience",
        "background": "Immigrated as an adult specifically to pursue an apprenticeship in a craft with no equivalent tradition in their country of origin.",
        "journey": "Spent years navigating both the craft's difficulty and a significant language and cultural barrier as an outsider entering a tradition-bound apprenticeship system.",
        "challenges": "Faced real skepticism from some established practitioners about whether an outsider could genuinely absorb a deeply culturally embedded craft tradition.",
        "turning_points": "A senior master publicly acknowledging their work as meeting the tradition's standards, in front of skeptical peers, was a significant turning point in acceptance.",
        "advice": "Pursuing a deeply culturally rooted craft as an outsider is genuinely harder, in ways beyond the craft skill itself — expect to have to prove belonging, not just competence.",
        "lessons_learned": "Technical skill alone isn't always enough to be accepted into a culturally embedded tradition — sustained respect and genuine cultural engagement matter as much.",
        "trait_tags": ["motivation", "learning_style"],
        "timeline": [
            {"stage": "career_transition", "label": "Immigrating for the apprenticeship", "description": "Immigrated as an adult to pursue an apprenticeship with no equivalent tradition at home.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Skepticism from established practitioners", "description": "Faced skepticism about whether an outsider could genuinely absorb the tradition.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Public acknowledgment from a senior master", "description": "A senior master publicly acknowledged their work as meeting the tradition's standards.", "year_label": "Year 7"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Years navigating skepticism as a cultural outsider entering a tradition-bound craft.",
        "current_outcome": "Works as a traditional craft master, acceptance earned through sustained respect and demonstrated skill as an outsider.",
        "industry": "traditional craftsmanship", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_japan_traditional_craft_master_4", "career_id": "japan_traditional_craft_master",
        "person_label": "Traditional Craft Master, 30 years experience",
        "background": "Trained under a master whose own workshop nearly closed due to declining demand during an economic downturn early in the apprenticeship.",
        "journey": "Helped the struggling workshop survive by developing new, smaller product lines aimed at a different customer base, while continuing traditional training in parallel.",
        "challenges": "Faced internal tension between the craft's traditional purism and the commercial adaptations needed to keep the workshop financially viable.",
        "turning_points": "The new product line's commercial success not only saved the workshop but also introduced the traditional craft to a new generation of customers who hadn't previously known of it.",
        "advice": "A craft's survival sometimes depends on thoughtful commercial adaptation — this doesn't have to mean abandoning its traditional core, if done carefully.",
        "lessons_learned": "Preserving a traditional craft can require genuine commercial innovation, not just resistance to change, especially during periods of declining demand.",
        "trait_tags": ["creativity", "values"],
        "timeline": [
            {"stage": "first_job", "label": "A workshop facing closure", "description": "Trained under a master whose workshop nearly closed due to declining demand.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Developing new product lines", "description": "Helped develop new, smaller product lines aimed at a different customer base.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Commercial success reaches new customers", "description": "The new product line's success introduced the craft to a new generation of customers.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a traditional craft master, having helped the workshop survive through commercial innovation without abandoning tradition.",
        "industry": "traditional craftsmanship", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_japan_traditional_craft_master_5", "career_id": "japan_traditional_craft_master",
        "person_label": "Traditional Craft Master, 6 years experience",
        "background": "Studied industrial design at university, planning a career designing mass-produced consumer products.",
        "journey": "A university project studying traditional craft techniques, meant to be purely academic research, led to a hands-on apprenticeship that became a full career change.",
        "challenges": "Had to reconcile a design education built around scalable mass production with a craft built around deliberately slow, individual, non-scalable work.",
        "turning_points": "Realizing that the deliberate slowness and individuality of the craft was precisely the value it offered, not a limitation to engineer around, resolved that internal tension.",
        "advice": "Training in scalable, mass-production design doesn't disqualify you from valuing and pursuing deliberately unscalable, individual craftsmanship instead.",
        "lessons_learned": "What looks like an inefficiency from a mass-production mindset — deliberate slowness, individual variation — can be the actual source of a craft's value.",
        "trait_tags": ["creativity", "values"],
        "timeline": [
            {"stage": "university", "label": "Industrial design, mass production focus", "description": "Studied industrial design planning a career in mass-produced consumer products.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A research project on traditional craft", "description": "A university research project on traditional craft techniques led to a hands-on apprenticeship.", "year_label": "Year 3"},
            {"stage": "career_transition", "label": "Full career change", "description": "The research project became a full career change into traditional craftsmanship.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a traditional craft master, having found value in deliberate slowness rather than the scalability of original design training.",
        "industry": "traditional craftsmanship", "story_type": "composite", "source_reference": "",
    },
    # --- International NGO Program Manager -----------------------------------
    {
        "id": "story_ngo_program_manager_2", "career_id": "ngo_program_manager",
        "person_label": "International NGO Program Manager, 4 years experience",
        "background": "Worked in corporate finance for three years, financially successful but increasingly disconnected from any sense of direct impact.",
        "journey": "Took an unpaid, three-month volunteer placement with an international NGO during a career break, which turned into a paid program role afterward.",
        "challenges": "Took a very significant pay cut moving from corporate finance into the nonprofit sector, requiring real lifestyle adjustment.",
        "turning_points": "Managing the budget for a program that directly, measurably improved a specific community's access to clean water reconnected financial skills to tangible impact.",
        "advice": "Financial and operational skills from the corporate world are genuinely needed in the nonprofit sector — the transition is more about accepting lower pay than lacking transferable skills.",
        "lessons_learned": "Corporate financial skills find real, direct application in nonprofit program management, once you're willing to accept the pay difference.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "Corporate finance", "description": "Worked in corporate finance for three years, disconnected from a sense of direct impact.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "An unpaid NGO placement", "description": "Took an unpaid, three-month volunteer placement with an international NGO.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "A water program with measurable impact", "description": "Managed a program budget that directly, measurably improved community access to clean water.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as an NGO program manager, corporate financial skills now applied to measurable humanitarian impact.",
        "industry": "international development", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ngo_program_manager_3", "career_id": "ngo_program_manager",
        "person_label": "International NGO Program Manager, 9 years experience",
        "background": "Was displaced as a child during a humanitarian crisis and grew up partly in a refugee settlement before eventually resettling and pursuing university study.",
        "journey": "Studied international development specifically motivated by direct childhood experience of humanitarian aid, both its real help and its real gaps.",
        "challenges": "Found early program management work emotionally difficult, since it often required visiting settings that closely echoed formative childhood experiences.",
        "turning_points": "Redesigning a program's aid distribution process to fix a specific inefficiency they remembered experiencing directly as a child gave the work unusually direct personal meaning.",
        "advice": "Direct lived experience of the systems you now design or manage, even from childhood, can be a genuine source of insight professional training alone doesn't provide.",
        "lessons_learned": "Personal experience of the exact gap you're now professionally trying to close can be both emotionally difficult and uniquely informative.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "school", "label": "Childhood displacement", "description": "Was displaced as a child during a humanitarian crisis, growing up partly in a refugee settlement.", "year_label": "Year 0"},
            {"stage": "university", "label": "International development studies", "description": "Studied international development motivated by direct childhood experience of humanitarian aid.", "year_label": "Year 10"},
            {"stage": "turning_point", "label": "Fixing a remembered inefficiency", "description": "Redesigned an aid distribution process to fix an inefficiency remembered from childhood.", "year_label": "Year 12"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Emotionally difficult early program management work in settings echoing formative childhood experiences.",
        "current_outcome": "Works as an NGO program manager, childhood displacement now directly informing program design.",
        "industry": "international development", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ngo_program_manager_4", "career_id": "ngo_program_manager",
        "person_label": "International NGO Program Manager, 2 years experience",
        "background": "Studied engineering and worked on infrastructure projects for four years, without a specific interest in the humanitarian sector.",
        "journey": "A company-sponsored short-term disaster relief deployment, meant to be a one-off corporate social responsibility trip, led to a full career change into humanitarian program work.",
        "challenges": "Struggled to translate purely technical infrastructure experience into the more people-and-logistics-focused skill set humanitarian program management requires.",
        "turning_points": "Being specifically asked to lead the technical planning for a permanent water infrastructure project, after the short-term deployment ended, was the concrete offer that prompted the full switch.",
        "advice": "A short-term corporate volunteer trip, taken without much personal investment, can end up revealing a genuine career direction you hadn't previously considered.",
        "lessons_learned": "Technical infrastructure skills transfer meaningfully into humanitarian program work, once paired with the sector's people-and-logistics demands.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Infrastructure engineering", "description": "Worked on infrastructure projects for four years without humanitarian sector interest.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A disaster relief deployment", "description": "A company-sponsored short-term disaster relief deployment led to a career change.", "year_label": "Year 4"},
            {"stage": "career_transition", "label": "Leading a water infrastructure project", "description": "Was asked to lead technical planning for a permanent water infrastructure project.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as an NGO program manager, applying infrastructure engineering skills to humanitarian program work.",
        "industry": "international development", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ngo_program_manager_5", "career_id": "ngo_program_manager",
        "person_label": "International NGO Program Manager, 11 years experience",
        "background": "Spent the first six years of a career as a field-based program officer, directly implementing programs rather than managing them from headquarters.",
        "journey": "Was promoted into a headquarters-based program management role, requiring a difficult adjustment from direct field implementation to overseeing programs remotely.",
        "challenges": "Missed the direct, tangible community contact of field work and initially found headquarters strategy work comparatively abstract and unsatisfying.",
        "turning_points": "Deliberately restructuring the role to include regular, planned field visits — rather than accepting a fully remote management structure — made the transition sustainable.",
        "advice": "A promotion away from hands-on work doesn't have to mean abandoning it entirely — actively negotiate the structure of the new role rather than accepting a default that doesn't fit.",
        "lessons_learned": "A role's default structure isn't fixed — deliberately negotiating for the parts of the previous work you valued can make an otherwise unsatisfying promotion work.",
        "trait_tags": ["leadership", "work_preferences"],
        "timeline": [
            {"stage": "first_job", "label": "Field-based program officer", "description": "Spent six years as a field-based program officer directly implementing programs.", "year_label": "Year 0"},
            {"stage": "promotion", "label": "Headquarters program management", "description": "Was promoted into a headquarters-based program management role.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "Negotiating regular field visits", "description": "Restructured the role to include regular, planned field visits.", "year_label": "Year 7"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Initial dissatisfaction with abstract headquarters strategy work after years of direct field implementation.",
        "current_outcome": "Leads NGO programs from headquarters, having negotiated a structure that keeps direct field contact intact.",
        "industry": "international development", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ngo_program_manager_6", "career_id": "ngo_program_manager",
        "person_label": "International NGO Program Manager, 5 years experience",
        "background": "Studied public health with a focus on epidemiology, expecting a research-oriented career in academic or government public health.",
        "journey": "A required practicum placement with an international NGO during graduate school, initially seen as a formality, redirected career interest toward implementation over research.",
        "challenges": "Had to build program management and logistics skills that epidemiology training hadn't covered, since the practicum revealed a gap between research and real-world implementation.",
        "turning_points": "Designing a program's monitoring system, using epidemiological methods applied to real-time program data rather than academic research, combined both skill sets directly.",
        "advice": "A required practicum or internship can end up mattering more for career direction than the actual degree it's attached to — take it seriously.",
        "lessons_learned": "Research training and implementation work aren't opposed — the right role can combine both, using research methods on real-time operational data.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "university", "label": "Epidemiology, research-oriented plan", "description": "Studied public health expecting a research-oriented academic or government career.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A required NGO practicum", "description": "A required practicum placement redirected career interest toward implementation.", "year_label": "Year 2"},
            {"stage": "career_transition", "label": "Combining research and implementation", "description": "Designed a program monitoring system combining epidemiological methods with real-time data.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as an NGO program manager, combining epidemiological research training with direct program implementation.",
        "industry": "international development", "story_type": "composite", "source_reference": "",
    },
    # --- Civil Engineer -------------------------------------------------------
    {
        "id": "story_civil_engineer_2", "career_id": "civil_engineer",
        "person_label": "Civil Engineer, 3 years experience",
        "background": "Failed a core structural analysis course twice during university, seriously doubting whether engineering was the right field.",
        "journey": "Passed the course on a third attempt after switching to a tutor who taught the material through hands-on physical models rather than pure equations.",
        "challenges": "Carried real doubt about their engineering competence into their first job, despite eventually passing every required course.",
        "turning_points": "Correctly diagnosing a structural issue on site, using the same physical-model intuition that had finally unlocked the once-failed course, quieted that doubt.",
        "advice": "Struggling with a core course doesn't predict how you'll perform once the material is applied to real, physical problems rather than abstract exams.",
        "lessons_learned": "The way a subject is taught, not just the subject itself, can be the actual barrier — a different teaching approach can unlock understanding exams alone couldn't measure.",
        "trait_tags": ["learning_style", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Failing structural analysis twice", "description": "Failed a core structural analysis course twice, doubting the choice of engineering.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A hands-on tutor", "description": "Passed the course on a third attempt using a hands-on, physical-model teaching approach.", "year_label": "Year 2"},
            {"stage": "current_role", "label": "Civil Engineer", "description": "Correctly diagnosed a real structural issue on site using the same physical intuition.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Real doubt about engineering competence carried from two failed university attempts at a core course.",
        "current_outcome": "Works as a civil engineer, having found that a different teaching approach unlocked understanding exams alone couldn't measure.",
        "industry": "engineering & construction", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_civil_engineer_3", "career_id": "civil_engineer",
        "person_label": "Civil Engineer, 8 years experience",
        "background": "Worked for five years at a firm designing structures they never saw built in person, all in distant locations.",
        "journey": "Deliberately moved to a smaller regional firm specifically to work on local projects they could visit and walk through after completion.",
        "challenges": "Took a real reduction in project scale and firm prestige to make the move to smaller, local work.",
        "turning_points": "Walking across a pedestrian bridge they'd designed, watching people actually use it, provided a form of satisfaction five years of larger, distant projects never had.",
        "advice": "Project scale and firm prestige aren't the only measures of a satisfying engineering career — proximity to the finished, used result matters too.",
        "lessons_learned": "A smaller-scale, more locally connected engineering role can be more personally satisfying than a larger, more prestigious one you never see completed.",
        "trait_tags": ["values", "work_preferences"],
        "timeline": [
            {"stage": "first_job", "label": "Distant, unseen projects", "description": "Worked five years designing structures in distant locations they never saw built.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Moving to a regional firm", "description": "Deliberately moved to a smaller regional firm for local, visitable projects.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "Walking a bridge they designed", "description": "Walked across a pedestrian bridge they'd designed, watching people actually use it.", "year_label": "Year 7"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a civil engineer at a regional firm, having traded project scale for the satisfaction of visitable, local work.",
        "industry": "engineering & construction", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_civil_engineer_4", "career_id": "civil_engineer",
        "person_label": "Civil Engineer, 5 years experience",
        "background": "Was on site during a partial structural failure early in their career — not one they'd designed, but one they were inspecting — that injured several workers.",
        "journey": "Took a leave of absence afterward to process the incident before returning to site-based engineering work at all.",
        "challenges": "Developed genuine anxiety about site visits for months afterward, despite not having been responsible for the failed structure.",
        "turning_points": "Returning to lead a site safety review process, built directly from lessons of that incident, transformed lingering anxiety into deliberate professional focus.",
        "advice": "Witnessing a serious safety incident, even one you weren't responsible for, can require real recovery time before returning to site work — that's a legitimate need, not a weakness.",
        "lessons_learned": "A traumatic professional incident can be channeled into a specific, valuable focus, like safety process design, rather than simply being pushed past.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "A partial structural failure", "description": "Was on site during a partial structural failure that injured several workers.", "year_label": "Year 2"},
            {"stage": "failure", "label": "A leave of absence", "description": "Took a leave of absence to process the incident before returning to site work.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Leading a safety review process", "description": "Returned to lead a site safety review process built from lessons of the incident.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Months of genuine anxiety about site visits following a serious safety incident.",
        "current_outcome": "Works as a civil engineer specializing in site safety, a difficult incident channeled into deliberate professional focus.",
        "industry": "engineering & construction", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_civil_engineer_5", "career_id": "civil_engineer",
        "person_label": "Civil Engineer, 2 years experience",
        "background": "Studied architecture for two years before switching to civil engineering, preferring structural problem-solving over aesthetic design decisions.",
        "journey": "Found the shift required relearning how to evaluate a building — from primarily visual and spatial criteria to primarily load and material criteria.",
        "challenges": "Had to retake several foundational courses that architecture study hadn't required, effectively losing a year of academic progress in the switch.",
        "turning_points": "Being asked, during a joint architecture-engineering studio project, to explain why a proposed design wouldn't structurally work clarified that this analytical role suited them better than the design role.",
        "advice": "If you're drawn to a building's structural logic more than its appearance, civil engineering may be a better fit than architecture, even after starting down the design path.",
        "lessons_learned": "Two closely related fields, like architecture and civil engineering, can require genuinely different ways of evaluating the same object — it's worth identifying which one you actually think in.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "Starting in architecture", "description": "Studied architecture for two years, preferring structural problem-solving over aesthetics.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Switching to civil engineering", "description": "Switched to civil engineering, retaking foundational courses architecture hadn't required.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "A joint studio project", "description": "A joint architecture-engineering studio project clarified the analytical role suited them better.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Effectively lost a year of academic progress switching from architecture to civil engineering.",
        "current_outcome": "Works as a civil engineer, having found structural analysis a better fit than the design-focused architecture path.",
        "industry": "engineering & construction", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_civil_engineer_6", "career_id": "civil_engineer",
        "person_label": "Senior Civil Engineer, 14 years experience",
        "background": "Worked on a major infrastructure project that was cancelled after four years of design work, when government funding was withdrawn amid a political change.",
        "journey": "Had to rebuild professional momentum after the cancellation, joining a new firm and starting a new project essentially from zero after years of investment in the cancelled one.",
        "challenges": "Faced real professional discouragement watching four years of detailed design work become effectively unusable overnight.",
        "turning_points": "Recognizing that specific design methodologies developed for the cancelled project were directly reusable on the new one meant the years weren't entirely wasted.",
        "advice": "A cancelled project, however discouraging, rarely destroys everything you built during it — look for the specific methods and skills that are still portable.",
        "lessons_learned": "Even when a specific project is cancelled outright, the underlying methods and expertise developed while working on it usually remain genuinely transferable.",
        "trait_tags": ["motivation", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "A major infrastructure project", "description": "Worked on a major infrastructure project for four years before funding was withdrawn.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Project cancellation", "description": "The project was cancelled amid a political change in government funding.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Reusable methodology", "description": "Recognized specific design methodologies from the cancelled project were directly reusable elsewhere.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Real professional discouragement after four years of design work became unusable overnight.",
        "current_outcome": "Works as a senior civil engineer, having rebuilt momentum by porting methodology from a cancelled project to a new one.",
        "industry": "engineering & construction", "story_type": "composite", "source_reference": "",
    },
]


async def seed() -> None:
    client = get_supabase_client()
    stories = [CareerStory.model_validate(s) for s in STORIES]

    def _upsert() -> None:
        client.table("career_stories").upsert(
            [s.model_dump(mode="json") for s in stories]
        ).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(stories)} healthcare, environment & trades Journey Stories.")


if __name__ == "__main__":
    asyncio.run(seed())
