"""Connect Batch 1 — Expert Connect seed data, Design/Architecture/Film/
Music/Fashion/Journalism domain group. See seed_experts_tech_and_science.py
for the full module-level convention notes.

Run via: python -m aureon.scripts.seed_experts_arts_and_public_life
"""

import asyncio

from aureon.domain.models.mentor import Mentor
from aureon.services.supabase.client import get_supabase_client

EXPERTS: list[dict] = [
    {
        "id": "expert_ux_designer_camila_reyes",
        "name": "Camila Reyes, Product Designer",
        "role_type": "industry_professional", "field": "design", "bio": "Leads product design for a fintech app; was rejected from design school twice before getting in on her third application.",
        "trait_tags": ["creativity", "persistence"], "learning_style_fit": "Students who want to know that design school rejection isn't the end of a design career.",
        "organization": "A fintech mobile app company", "years_experience": 8, "journey_highlights": ["Rejected from design school twice", "Redesigned an onboarding flow that doubled activation rate"],
        "discussion_topics": ["Getting rejected from design school and trying again", "Self-taught vs. formal design education", "UX vs. visual design"],
        "profession": "Senior Product Designer", "specialization": "Fintech mobile UX", "country": "Colombia", "city": "Bogotá",
        "industries": ["technology & design", "fintech"], "education": ["Rejected twice, then BFA Design, Universidad de los Andes"],
        "current_role": "Lead Product Designer", "languages": ["Spanish", "English"],
        "accepts_mentorship": True, "max_students": 3,
        "who_should_talk_to_me": ["Students rejected from a design program who feel discouraged", "Students choosing between visual design and UX research", "Self-taught designers unsure if formal education matters"],
        "career_ids": ["ux_researcher"],
        "career_journey": [
            {"stage": "school", "label": "Applied to design school twice and was rejected both times", "description": "Spent two gap years building a portfolio through freelance work instead.", "year_label": "2011-2013"},
            {"stage": "university", "label": "BFA Design, admitted on her third application", "description": "Her improved portfolio from freelance work made the difference.", "year_label": "2014-2018"},
            {"stage": "first_job", "label": "Junior product designer at a small startup", "description": "Learned UX fundamentals on the job, which her degree hadn't covered deeply.", "year_label": "2018-2020"},
            {"stage": "turning_point", "label": "Redesigned the app's onboarding flow", "description": "The redesign doubled the app's user activation rate within a quarter.", "year_label": "2021"},
            {"stage": "current_role", "label": "Lead Product Designer", "description": "Now leads a team of four designers at a fast-growing fintech company.", "year_label": "2022-present"},
        ],
        "day_in_the_life": "Mornings reviewing user research and analytics, afternoons in design critiques and prototyping sessions with engineers.",
        "weekly_routine": "Design sprints most weeks, with regular user testing sessions built into the process.",
        "biggest_challenges": ["Balancing what users say they want against what the data shows they actually do", "Advocating for design quality against tight engineering deadlines"],
        "favourite_part": "Watching a real user complete a task smoothly in a usability test after a redesign.",
        "biggest_misconceptions": ["That design is just making things look pretty", "That rejection from a design program means you lack talent"],
        "what_surprised_them": "How much of design work is really about research and advocacy, not just visual craft.",
        "biggest_mistake": "I once shipped a redesign based purely on my own aesthetic preference without testing it with real users first, and it actually decreased conversion. It taught me to never skip user validation again, no matter how confident I feel.",
        "one_regret": "I regret how discouraged those two rejections made me feel for years — I almost gave up on design entirely instead of building the portfolio that eventually got me in.",
        "salary_reality": "Product design pays well in Colombia's growing tech sector relative to traditional design roles, though still below equivalent US salaries.",
        "work_life_balance": "Generally good, with occasional crunches before major product launches.",
        "daily_skills": ["user research", "prototyping", "visual design", "stakeholder communication"],
        "daily_tools": ["Figma", "Maze (usability testing)", "Notion"],
        "recommended_books": ["Don't Make Me Think by Steve Krug"],
        "recommended_communities": ["Bogotá design meetup community"],
        "advice_for_beginners": "A rejection from a design program isn't a verdict on your talent — build a portfolio through real freelance projects and reapply, exactly like I did.",
        "advice_for_parents": "Two rejections from design school didn't mean design wasn't right for her — it meant she needed more real project experience first, which she went out and got.",
        "faqs": [{"question": "Do I need a design degree to become a product designer?", "answer": "It helps, but a strong portfolio of real projects matters more to most hiring managers than the specific degree."}],
        "projects": ["Redesigned onboarding flow that doubled user activation"], "research": [], "certifications": [],
        "conferences": ["Interaction Design Conference (attendee)"], "organizations": [],
        "volunteer_work": ["Reviews portfolios for design school applicants for free"],
        "portfolio_links": [{"label": "Portfolio", "url": "https://example.com/camilareyes"}], "social_links": [],
    },
    {
        "id": "expert_architect_hiroshi_sato",
        "name": "Hiroshi Sato, Architect",
        "role_type": "industry_professional", "field": "architecture", "bio": "Designs affordable housing projects at a mid-size architecture firm; his first independent building project had a serious structural flaw caught just before construction.",
        "trait_tags": ["creativity", "analytical_thinking"], "learning_style_fit": "Students who want to combine creative vision with real technical constraints.",
        "organization": "A mid-size architecture firm", "years_experience": 13, "journey_highlights": ["Nearly approved a structurally flawed design early in his career", "Designed affordable housing now home to over 500 families"],
        "discussion_topics": ["Architecture school vs. real practice", "Affordable housing design challenges", "Catching a career-threatening mistake in time"],
        "profession": "Principal Architect", "specialization": "Affordable and social housing design", "country": "Japan", "city": "Osaka",
        "industries": ["architecture", "urban development"], "education": ["Master of Architecture, Kyoto University"],
        "current_role": "Principal Architect, Housing Studio", "languages": ["Japanese", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who like both creative design and technical engineering constraints", "Students interested in affordable housing rather than luxury architecture", "Students worried about the pressure of getting a design technically right"],
        "career_ids": ["civil_engineer"],
        "career_journey": [
            {"stage": "university", "label": "Master of Architecture", "description": "Focused his thesis on affordable housing, an unusual choice among classmates drawn to flashier commercial projects.", "year_label": "2005-2011"},
            {"stage": "first_job", "label": "Junior architect at a large commercial firm", "description": "Worked mostly on corporate office buildings, feeling disconnected from his housing interests.", "year_label": "2011-2015"},
            {"stage": "failure", "label": "Nearly approved a structurally flawed independent housing design", "description": "A senior structural engineer caught a load-bearing miscalculation just before construction began — a mistake that could have been catastrophic.", "year_label": "2016"},
            {"stage": "career_transition", "label": "Moved to a smaller firm focused specifically on social housing", "description": "Took a pay cut to work on projects that matched his actual values.", "year_label": "2017"},
            {"stage": "current_role", "label": "Principal Architect, Housing Studio", "description": "Has designed affordable housing developments now home to over 500 families.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "A mix of design work, structural coordination meetings with engineers, and site visits to active construction projects.",
        "weekly_routine": "Design and drafting most days, with structural review meetings and periodic site inspections.",
        "biggest_challenges": ["Designing genuinely dignified housing within extremely tight budget constraints", "The weight of knowing a design error could physically endanger people"],
        "favourite_part": "Visiting a completed housing project and seeing families actually living full, ordinary lives there.",
        "biggest_misconceptions": ["That architecture is mostly about aesthetics — structural safety is the non-negotiable foundation of everything", "That affordable housing design is less prestigious or interesting than luxury projects"],
        "what_surprised_them": "How collaborative real architecture is — his early image of a lone visionary designer was almost entirely wrong.",
        "biggest_mistake": "On my first independent project, I made a load calculation error in a support beam design that a senior structural engineer caught during final review, just weeks before construction. If it had gone unnoticed, the consequences could have been severe. I now triple-check every structural calculation personally, no matter how routine it seems.",
        "one_regret": "I regret not asking for a second opinion on that early design sooner out of a desire to prove myself independently — pride nearly caused a serious problem.",
        "salary_reality": "Architecture in Japan pays modestly relative to the years of training required — affordable housing work pays less still than commercial architecture, a tradeoff I made deliberately for the mission.",
        "work_life_balance": "Demanding during active project phases, calmer during design development stages.",
        "daily_skills": ["architectural design", "structural coordination", "budget management"],
        "daily_tools": ["AutoCAD", "Revit", "structural analysis software"],
        "recommended_books": ["How Buildings Learn by Stewart Brand"],
        "recommended_communities": ["Japan Institute of Architects local chapter"],
        "advice_for_beginners": "Never let pride stop you from asking a more experienced colleague to double-check your structural work — my near-mistake taught me that humility is a technical skill, not just a virtue.",
        "advice_for_parents": "Affordable housing architecture is a real, respected specialization, not a lesser path than commercial or luxury design — it just serves a different, arguably more urgent need.",
        "faqs": [{"question": "Is affordable housing design less interesting than commercial architecture?", "answer": "Not to me — the creative constraint of doing more with less is one of the most interesting design problems architecture offers."}],
        "projects": ["Designed affordable housing developments now home to over 500 families"], "research": [],
        "certifications": ["Licensed Architect, Japan"], "conferences": [], "organizations": ["Japan Institute of Architects"],
        "volunteer_work": ["Advises a nonprofit on disaster-resilient housing design"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_documentary_filmmaker_amelia_okonjo",
        "name": "Amelia Okonjo, Documentary Filmmaker",
        "role_type": "creator", "field": "film", "bio": "Directs documentary films focused on African history and identity; her first feature film was rejected from every festival she submitted to.",
        "trait_tags": ["creativity", "persistence"], "learning_style_fit": "Students who want an honest picture of creative rejection before eventual success.",
        "organization": "Independent filmmaker", "years_experience": 9, "journey_highlights": ["Her first feature film was rejected from over 20 festivals", "Her third film won a major African film festival award"],
        "discussion_topics": ["Handling repeated creative rejection", "Funding independent documentary work", "Film school vs. self-taught filmmaking"],
        "profession": "Documentary Director", "specialization": "African history and identity documentaries", "country": "South Africa", "city": "Johannesburg",
        "industries": ["film", "media"], "education": ["BA Media Studies, University of the Witwatersrand"],
        "current_role": "Independent Documentary Director", "languages": ["English", "Zulu", "Xhosa"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who fear creative rejection", "Students interested in documentary rather than narrative film", "Students unsure how independent filmmakers actually fund their work"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Media Studies", "description": "Made her first short documentary as a student project.", "year_label": "2007-2010"},
            {"stage": "first_job", "label": "Production assistant on commercial video shoots", "description": "Paid the bills with corporate video work while developing her own documentary ideas.", "year_label": "2010-2014"},
            {"stage": "failure", "label": "Her first independent feature was rejected by over 20 festivals", "description": "Spent her savings making the film and questioned whether she had any real talent afterward.", "year_label": "2015"},
            {"stage": "turning_point", "label": "Made a smaller, more personal second film", "description": "Screened it at a local community event rather than chasing major festivals, and the honest response rebuilt her confidence.", "year_label": "2017"},
            {"stage": "current_role", "label": "Independent Documentary Director", "description": "Her third film won a major African film festival award.", "year_label": "2020-present"},
        ],
        "day_in_the_life": "Varies hugely by project phase — research and interviews during production, long solitary hours in the edit during post-production, and grant-writing during funding gaps.",
        "weekly_routine": "No two weeks look alike; funding applications and production work compete constantly for her time.",
        "biggest_challenges": ["The financial instability between projects", "Handling repeated rejection from festivals and funders without losing motivation"],
        "favourite_part": "The first private screening of a finished film for the real people whose stories it tells.",
        "biggest_misconceptions": ["That documentary filmmaking is easier or cheaper than narrative film — the research alone often takes years", "That festival rejection means a film isn't good"],
        "what_surprised_them": "How much of documentary work is relationship-building with subjects, not just filming.",
        "biggest_mistake": "On my first feature, I rushed the edit to meet a festival deadline instead of taking the time the story actually needed, and I believe that hurt the final film. My later, more successful work has always taken the time it needed rather than chasing a deadline.",
        "one_regret": "I regret how personally I took those first 20 rejections — I now know festival programming is subjective and has as much to do with timing and taste as quality.",
        "salary_reality": "Independent documentary filmmaking rarely provides steady income — most filmmakers I know supplement it with commercial video work or teaching, especially early on.",
        "work_life_balance": "Highly irregular — intense production stretches followed by quieter, financially uncertain gaps.",
        "daily_skills": ["directing", "interviewing", "video editing", "grant writing"],
        "daily_tools": ["Premiere Pro", "DSLR/mirrorless cameras", "audio recording equipment"],
        "recommended_books": ["Documentary Storytelling by Sheila Curran Bernard"],
        "recommended_communities": ["South African documentary filmmakers network"],
        "advice_for_beginners": "Make a smaller, honest film before you attempt your dream project — my second, more modest film taught me more than my ambitious, over-budgeted first one.",
        "advice_for_parents": "Rejection is a normal, repeated part of any creative career, not a sign of failure — please help your child separate the two.",
        "faqs": [{"question": "How do independent filmmakers actually make money?", "answer": "Most combine grants, festival prize money, and commercial video work — very few live purely off their personal documentary projects, especially early on."}],
        "projects": ["Directed a documentary that won a major African film festival award"], "research": [],
        "certifications": [], "conferences": ["Durban International Film Festival"], "organizations": [],
        "volunteer_work": ["Teaches a free documentary filmmaking workshop for township youth"],
        "portfolio_links": [{"label": "Vimeo", "url": "https://vimeo.com/example-ameliaokonjo"}], "social_links": [],
    },
    {
        "id": "expert_journalist_marco_ferrari",
        "name": "Marco Ferrari, Investigative Journalist",
        "role_type": "industry_professional", "field": "journalism", "bio": "Covers corruption and public accountability for a national newspaper; was sued for defamation early in his career on a story that turned out to be accurate.",
        "trait_tags": ["persistence", "communication"], "learning_style_fit": "Students drawn to holding power accountable who want to understand the real legal and financial risks involved.",
        "organization": "A national newspaper", "years_experience": 15, "journey_highlights": ["Was sued for defamation on a story that was later vindicated", "Broke a story that led to a government minister's resignation"],
        "discussion_topics": ["Being sued as a journalist", "Investigative journalism vs. daily news reporting", "The declining economics of newspaper journalism"],
        "profession": "Senior Investigative Journalist", "specialization": "Government accountability and corruption reporting", "country": "Italy", "city": "Rome",
        "industries": ["journalism", "media"], "education": ["BA Journalism, Sapienza University of Rome"],
        "current_role": "Senior Investigative Reporter", "languages": ["Italian", "English", "French"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students drawn to investigative journalism specifically", "Students worried about the legal risks of accountability reporting", "Students concerned about journalism's declining job stability"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Journalism", "description": "Interned at a local newspaper throughout his degree.", "year_label": "1998-2002"},
            {"stage": "first_job", "label": "General assignment reporter", "description": "Covered everything from local council meetings to minor crime for several years.", "year_label": "2002-2006"},
            {"stage": "career_transition", "label": "Moved into investigative reporting", "description": "Pitched his first major accountability investigation against editorial skepticism.", "year_label": "2007"},
            {"stage": "failure", "label": "Was sued for defamation over an investigation into local government contracts", "description": "The two-year legal battle was financially and emotionally exhausting, even though the story was ultimately proven accurate.", "year_label": "2009-2011"},
            {"stage": "turning_point", "label": "Won the defamation case and the story's findings were vindicated", "description": "The case established him as a credible, rigorous investigative reporter within the newsroom.", "year_label": "2011"},
            {"stage": "current_role", "label": "Senior Investigative Reporter", "description": "His reporting has led to a government minister's resignation and several policy reforms.", "year_label": "2015-present"},
        ],
        "day_in_the_life": "Days blend document research, source interviews (often off the record), and careful, slow writing that goes through extensive legal review before publication.",
        "weekly_routine": "Investigations unfold over months, not days — most weeks involve incremental research progress rather than dramatic breakthroughs.",
        "biggest_challenges": ["The real legal and financial risk of accountability reporting", "Newsroom budget cuts shrinking the time available for slow, careful investigative work"],
        "favourite_part": "The moment a source's information, verified through months of corroboration, becomes a published story that leads to real accountability.",
        "biggest_misconceptions": ["That investigative journalism is fast-paced and dramatic — it's mostly slow, careful, unglamorous verification work", "That reporters can publish whatever they find without serious legal exposure"],
        "what_surprised_them": "How much investigative journalism resembles detective work — patient, methodical, and often frustratingly slow.",
        "biggest_mistake": "Early in the story that led to my defamation lawsuit, I relied on a single source's account without adequately corroborating one specific claim. The core story was accurate, but that one weaker point gave the subject legal grounds to sue, and it cost the paper significant legal fees to fully vindicate.",
        "one_regret": "I don't regret pursuing that story, but I regret not insisting on a second independent source for every single claim before we published — it's a standard I hold to strictly now.",
        "salary_reality": "Journalism salaries in Italy, like much of the industry globally, have declined significantly as newspaper revenue has shrunk — this is a real, structural challenge for anyone entering the field today.",
        "work_life_balance": "Investigations can consume evenings and weekends for months at a time, especially near publication.",
        "daily_skills": ["investigative research", "source verification", "long-form writing"],
        "daily_tools": ["Public records databases", "encrypted communication tools for sources"],
        "recommended_books": ["All the President's Men by Bernstein and Woodward"],
        "recommended_communities": ["Investigative Reporters and Editors network"],
        "advice_for_beginners": "Never publish a serious accusation on a single uncorroborated source — the lawsuit I survived taught me this the hard way, and it's the rule I'd give any beginner first.",
        "advice_for_parents": "Investigative journalism carries real legal and financial risk, and it's fair to worry about that — but strong newsrooms provide real legal support, and the accountability work genuinely matters.",
        "faqs": [{"question": "Can journalists be personally sued for their reporting?", "answer": "Yes, defamation suits are a real risk in accountability journalism — reputable newsrooms provide legal review and support, but the personal stress is real regardless."}],
        "projects": ["Reporting that led to a government minister's resignation"], "research": [],
        "certifications": [], "conferences": [], "organizations": ["Italian investigative journalists' association"],
        "volunteer_work": ["Trains younger reporters on source verification standards"],
        "portfolio_links": [], "social_links": [],
    },
    {
        "id": "expert_music_producer_tomasz_kowalski",
        "name": "Tomasz Kowalski, Music Producer",
        "role_type": "creator", "field": "music", "bio": "Produces and mixes records for independent artists; quit a stable audio engineering job at 24 to freelance, and spent his first year nearly broke.",
        "trait_tags": ["creativity", "persistence"], "learning_style_fit": "Students who want honesty about the financial instability of creative freelance careers.",
        "organization": "Independent producer", "years_experience": 12, "journey_highlights": ["Nearly went broke in his first year freelancing", "Produced an album that reached a national top-10 chart"],
        "discussion_topics": ["Freelance income instability in creative careers", "Music production as a technical and creative skill", "Building a client base from zero"],
        "profession": "Music Producer and Mixing Engineer", "specialization": "Independent artist production", "country": "Poland", "city": "Warsaw",
        "industries": ["music", "entertainment"], "education": ["Diploma in Audio Engineering, Warsaw audio technical school"],
        "current_role": "Independent Music Producer", "languages": ["Polish", "English"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students considering freelance creative work and worried about income stability", "Students interested in the technical side of music, not just performing", "Students weighing a stable audio job against independent production"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "Diploma in Audio Engineering", "description": "Trained in technical recording and mixing skills.", "year_label": "2009-2011"},
            {"stage": "first_job", "label": "Staff audio engineer at a recording studio", "description": "Stable salary, but limited creative input on the projects he worked on.", "year_label": "2011-2015"},
            {"stage": "career_transition", "label": "Left to freelance as an independent producer", "description": "Had almost no clients in his first six months and lived on savings that nearly ran out entirely.", "year_label": "2015"},
            {"stage": "turning_point", "label": "Produced an album for an independent artist that unexpectedly reached national charts", "description": "The album's success brought a wave of new client inquiries.", "year_label": "2017"},
            {"stage": "current_role", "label": "Independent Music Producer", "description": "Now works with a steady roster of independent artists.", "year_label": "2018-present"},
        ],
        "day_in_the_life": "Studio sessions recording and mixing, interspersed with client calls negotiating new projects and rates.",
        "weekly_routine": "Studio-heavy days mixed with business development — the two halves of freelance creative work most people don't realize both matter equally.",
        "biggest_challenges": ["Irregular income, especially between projects", "Balancing artistic vision against a client's different taste"],
        "favourite_part": "Hearing a rough, unfinished song transform into something an artist is genuinely proud of.",
        "biggest_misconceptions": ["That producers just 'make things sound good' — much of the job is really managing a creative relationship", "That leaving a stable job for freelance work is reckless rather than a real, calculated risk"],
        "what_surprised_them": "How much of freelance success depends on business skills — invoicing, negotiating, marketing — not just technical talent.",
        "biggest_mistake": "In my first year freelancing, I took on too many low-paying projects out of financial desperation, which left me too exhausted to do my best work on any of them. I had to learn to say no to underpriced work, even when money was tight.",
        "one_regret": "I regret not saving a larger financial cushion before leaving my staff job — the fear of running out of money in that first year affected the quality of decisions I was making.",
        "salary_reality": "Freelance music production income is genuinely unpredictable, especially in the first two to three years — I'd recommend a savings cushion of at least six months' expenses before going independent.",
        "work_life_balance": "Irregular by nature — some weeks are packed with sessions, others are quiet, which can be stressful without financial planning.",
        "daily_skills": ["audio mixing", "music production", "client communication", "negotiation"],
        "daily_tools": ["Pro Tools", "Ableton Live", "studio recording equipment"],
        "recommended_books": ["Mixing Secrets for the Small Studio by Mike Senior"],
        "recommended_communities": ["Warsaw independent music producers network"],
        "advice_for_beginners": "Save a real financial cushion before going independent — my first year was nearly derailed by money stress that a bigger buffer would have prevented.",
        "advice_for_parents": "Freelance creative careers can become genuinely stable, but the first few years often involve real financial uncertainty — that's normal, not a sign the path is failing.",
        "faqs": [{"question": "Is it realistic to make a living as an independent music producer?", "answer": "Yes, but it usually takes several years to build a reliable client base — plan financially for a slow ramp-up, not instant income."}],
        "projects": ["Produced an album that reached a national top-10 chart"], "research": [], "certifications": [],
        "conferences": [], "organizations": [], "volunteer_work": ["Offers discounted studio time to young unsigned artists"],
        "portfolio_links": [{"label": "SoundCloud", "url": "https://soundcloud.com/example-tomaszkowalski"}], "social_links": [],
    },
    {
        "id": "expert_fashion_designer_aisha_bello",
        "name": "Aisha Bello, Fashion Designer",
        "role_type": "founder", "field": "fashion", "bio": "Runs an independent fashion label blending traditional West African textiles with contemporary design; her first collection failed to sell at all.",
        "trait_tags": ["creativity", "persistence"], "learning_style_fit": "Students who want honesty about how hard it is to build a fashion business, not just design clothes.",
        "organization": "An independent fashion label", "years_experience": 10, "journey_highlights": ["Her first collection sold zero pieces", "Her label was later featured in a major regional fashion week"],
        "discussion_topics": ["Fashion design vs. fashion business", "Learning from a total commercial failure", "Blending traditional textiles with modern design"],
        "profession": "Fashion Designer and Label Founder", "specialization": "Contemporary West African textile design", "country": "Nigeria", "city": "Lagos",
        "industries": ["fashion", "design"], "education": ["BA Fashion Design, Yaba College of Technology"],
        "current_role": "Founder and Creative Director", "languages": ["English", "Yoruba"],
        "accepts_mentorship": True, "max_students": 2,
        "who_should_talk_to_me": ["Students who want to design clothes but haven't thought about the business side yet", "Students interested in blending traditional craft with contemporary design", "Students who've had a project or product fail commercially"],
        "career_ids": [],
        "career_journey": [
            {"stage": "university", "label": "BA Fashion Design", "description": "Focused her thesis collection on traditional Yoruba textile patterns.", "year_label": "2010-2014"},
            {"stage": "first_job", "label": "Launched her first independent collection", "description": "Sold zero pieces after months of production work and a launch event she funded herself.", "year_label": "2015"},
            {"stage": "failure", "label": "The failed collection left her in significant debt", "description": "Seriously considered abandoning fashion for a more stable career.", "year_label": "2015"},
            {"stage": "career_transition", "label": "Took a job as a pattern-maker for an established label while rebuilding", "description": "Used the steady income and behind-the-scenes business exposure to understand what she'd missed the first time.", "year_label": "2016-2018"},
            {"stage": "turning_point", "label": "Relaunched her label with a smaller, more focused collection", "description": "This time she pre-sold pieces to build capital before full production.", "year_label": "2019"},
            {"stage": "current_role", "label": "Founder and Creative Director", "description": "Her label was featured in a major regional fashion week.", "year_label": "2021-present"},
        ],
        "day_in_the_life": "A mix of design sketching, fabric sourcing, working with local artisans, and increasingly, business operations like inventory and sales.",
        "weekly_routine": "Design and production work most days, with dedicated time for business administration that she once badly neglected.",
        "biggest_challenges": ["Balancing creative integrity against what actually sells", "Managing cash flow in a business with irregular seasonal demand"],
        "favourite_part": "Seeing someone wear a piece that connects traditional textile heritage to their everyday modern life.",
        "biggest_misconceptions": ["That fashion design success is purely about creative talent — business skills matter just as much", "That a failed first collection means you don't have what it takes"],
        "what_surprised_them": "How much of a fashion business is inventory management and cash flow, not just design.",
        "biggest_mistake": "My first collection failed largely because I designed pieces I loved without ever validating whether customers actually wanted them or could afford them — I never talked to a single potential customer before production. I now pre-sell and gather real feedback before committing to full production.",
        "one_regret": "I regret not asking for business mentorship before that first launch — I assumed good design would be enough, and it wasn't.",
        "salary_reality": "Independent fashion labels often take years to become profitable — I personally worked a second job for two years while rebuilding my label after the first failure.",
        "work_life_balance": "Demanding, especially around collection launches and fashion week seasons.",
        "daily_skills": ["garment design", "textile sourcing", "small business management"],
        "daily_tools": ["Sketching software", "pattern-making tools", "inventory management spreadsheets"],
        "recommended_books": ["The Fashion Business Manual by Fashionary"],
        "recommended_communities": ["Lagos Fashion Week designer network"],
        "advice_for_beginners": "Talk to real potential customers before you produce anything — my first collection failed because I skipped this step entirely, assuming my taste would be enough.",
        "advice_for_parents": "A failed first business attempt in a creative field isn't proof the path is wrong — my daughter's second attempt succeeded because of exactly what she learned from the first one failing.",
        "faqs": [{"question": "Do you need a business degree to run a fashion label?", "answer": "Not necessarily, but you do need to actively learn business skills — my design degree alone left me unprepared for that side of the work."}],
        "projects": ["Label featured in a major regional fashion week"], "research": [], "certifications": [],
        "conferences": ["Lagos Fashion Week"], "organizations": [],
        "volunteer_work": ["Mentors young designers on pricing and small-batch production"],
        "portfolio_links": [], "social_links": [{"label": "Instagram", "url": "https://instagram.com/example_aishabello"}],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    experts = [Mentor.model_validate(e) for e in EXPERTS]

    def _upsert() -> None:
        client.table("mentors").upsert([e.model_dump(mode="json") for e in experts]).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(experts)} experts (arts_and_public_life batch).")


if __name__ == "__main__":
    asyncio.run(seed())
