"""Journey Stories — Public Service & Policy domain group (Connect Batch
2). 30 new composite Journey Stories across 6 careers: Foreign Service
Officer, IAS Officer, UK Civil Service Fast Streamer, Municipal Urban
Planner, Public Health Policy Analyst, Human Rights Researcher. Every
entry is an illustrative composite persona (`story_type="composite"`)
— never a claim of a specific real individual.

Run via: python -m aureon.scripts.seed_journey_stories_public_service_and_policy
Idempotent: safe to re-run (upsert on id).
"""

import asyncio

from aureon.domain.models.career import CareerStory
from aureon.services.supabase.client import get_supabase_client

STORIES: list[dict] = [
    # --- Foreign Service Officer --------------------------------------------
    {
        "id": "story_foreign_service_officer_2", "career_id": "foreign_service_officer",
        "person_label": "Foreign Service Officer, 4 years experience",
        "background": "Worked as a corporate lawyer for six years, financially comfortable but increasingly restless in purely commercial legal work.",
        "journey": "Took the notoriously difficult foreign service entrance exam on a whim after a friend mentioned it, and passed on their first attempt despite minimal preparation time.",
        "challenges": "Took a very significant pay cut moving from corporate law into an entry-level diplomatic posting.",
        "turning_points": "Negotiating a small legal technicality in a bilateral trade discussion, drawing directly on their corporate law background, proved the two careers weren't as disconnected as they'd assumed.",
        "advice": "Legal training transfers into diplomacy more directly than people expect — don't assume a law background locks you into private practice.",
        "lessons_learned": "A restless feeling in a financially comfortable role is worth taking seriously, even without a clear alternative plan yet.",
        "trait_tags": ["analytical_thinking", "communication"],
        "timeline": [
            {"stage": "first_job", "label": "Corporate lawyer", "description": "Worked as a corporate lawyer for six years, increasingly restless in commercial work.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Foreign service exam", "description": "Took the foreign service entrance exam on a whim and passed on the first attempt.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "Legal training in a trade negotiation", "description": "Negotiated a legal technicality in a bilateral trade discussion using corporate law background.", "year_label": "Year 8"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a foreign service officer, having found legal training transfers more directly into diplomacy than expected.",
        "industry": "diplomacy & international relations", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_foreign_service_officer_3", "career_id": "foreign_service_officer",
        "person_label": "Foreign Service Officer, 9 years experience",
        "background": "Grew up as the child of migrant workers, moving between three countries before the age of twelve.",
        "journey": "That early cross-cultural instability, initially seen as a childhood hardship, became a genuine professional asset once they entered the foreign service.",
        "challenges": "Struggled during childhood with a sense of not fully belonging in any single culture or country.",
        "turning_points": "Being specifically assigned to a posting because of childhood familiarity with the region's languages and customs reframed the early instability as unusual expertise.",
        "advice": "An unstable or unconventional childhood, especially one involving multiple cultures, can become a genuine professional strength later on.",
        "lessons_learned": "What feels like a personal hardship in childhood can quietly become exactly the expertise a later career specifically needs.",
        "trait_tags": ["communication", "curiosity"],
        "timeline": [
            {"stage": "school", "label": "Moving between three countries", "description": "Grew up moving between three countries before age twelve, as the child of migrant workers.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Entering the foreign service", "description": "Entered the foreign service after competitive selection.", "year_label": "Year 10"},
            {"stage": "turning_point", "label": "Assigned for cultural familiarity", "description": "Was assigned to a posting specifically for childhood familiarity with the region's languages and customs.", "year_label": "Year 11"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "A childhood sense of not fully belonging to any single culture or country.",
        "current_outcome": "Works as a foreign service officer, an unconventional multicultural childhood now recognized as professional expertise.",
        "industry": "diplomacy & international relations", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_foreign_service_officer_4", "career_id": "foreign_service_officer",
        "person_label": "Foreign Service Officer, 2 years experience",
        "background": "Failed the foreign service entrance exam twice before passing on a third attempt, four years after first taking it.",
        "journey": "Spent the years between attempts working in international nonprofit roles, deliberately building the field experience the exam feedback suggested was lacking.",
        "challenges": "Faced serious doubt after the second failed attempt about whether to keep pursuing a goal that had already taken years without success.",
        "turning_points": "A mentor who had also failed the exam twice before eventually passing offered concrete reassurance that the setback pattern wasn't unusual or disqualifying.",
        "advice": "Repeated failure on a single, highly competitive entrance exam is common enough that it shouldn't be read as a signal you're unsuited to the field.",
        "lessons_learned": "The years spent failing an exam can still be used productively to build exactly the experience the next attempt needs.",
        "trait_tags": ["motivation", "values"],
        "timeline": [
            {"stage": "career_transition", "label": "First exam failure", "description": "Failed the foreign service entrance exam on the first attempt.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Second exam failure", "description": "Failed a second time, prompting serious doubt about continuing to pursue the goal.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Passing on the third attempt", "description": "Passed the exam on a third attempt after building field experience in the interim.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Four years and two failed attempts at a highly competitive entrance exam, with real doubt about continuing.",
        "current_outcome": "Works as a foreign service officer, entrance secured on the third attempt after years of deliberate preparation.",
        "industry": "diplomacy & international relations", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_foreign_service_officer_5", "career_id": "foreign_service_officer",
        "person_label": "Foreign Service Officer, 15 years experience",
        "background": "Entered the foreign service with a strong interest in economic diplomacy, expecting a career focused primarily on trade negotiations.",
        "journey": "An unplanned posting to a crisis region during an early rotation redirected their specialization entirely, toward humanitarian and conflict-adjacent diplomatic work.",
        "challenges": "Found the crisis posting far more emotionally demanding than the trade-focused career they'd originally envisioned and prepared for.",
        "turning_points": "Successfully coordinating an evacuation of citizens during a sudden regional crisis proved a capability under pressure they hadn't known they had.",
        "advice": "An early rotation you didn't choose can end up defining your entire specialization — stay open to it rather than treating it as a detour from the 'real' plan.",
        "lessons_learned": "Crisis experience, however unwelcome at the time, can reveal capabilities and interests a carefully planned career path never would have surfaced.",
        "trait_tags": ["leadership", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Expecting economic diplomacy", "description": "Entered the foreign service expecting a career focused on trade negotiations.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "An unplanned crisis posting", "description": "Was posted to a crisis region during an early rotation, redirecting their specialization.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Coordinating an evacuation", "description": "Successfully coordinated an evacuation of citizens during a sudden regional crisis.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Specializes in humanitarian and conflict-adjacent diplomacy, a direction found through an unplanned early posting.",
        "industry": "diplomacy & international relations", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_foreign_service_officer_6", "career_id": "foreign_service_officer",
        "person_label": "Foreign Service Officer, 6 years experience",
        "background": "Studied engineering as an undergraduate with no exposure to international relations, planning a conventional technical career.",
        "journey": "A university study-abroad semester, taken almost as an afterthought to fulfill a general elective requirement, redirected their entire career interest toward diplomacy.",
        "challenges": "Had to essentially start over academically, pursuing a graduate degree in international relations with no undergraduate background in the subject.",
        "turning_points": "Being the only person in a study-abroad group who could technically explain a local infrastructure failure to confused local officials revealed an unexpected use for the engineering background.",
        "advice": "A general elective or study-abroad requirement, taken without much thought, can end up redirecting an entire career more than a deliberately chosen major.",
        "lessons_learned": "An unrelated technical background doesn't have to be abandoned when you switch fields — it can become a distinguishing asset within the new one.",
        "trait_tags": ["curiosity", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Engineering degree", "description": "Studied engineering with no exposure to international relations.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A study-abroad elective", "description": "A general elective study-abroad semester redirected career interest toward diplomacy.", "year_label": "Year 2"},
            {"stage": "career_transition", "label": "Graduate study in international relations", "description": "Pursued a graduate degree in international relations with no prior background.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a foreign service officer, an engineering background now a distinguishing technical asset in diplomatic postings.",
        "industry": "diplomacy & international relations", "story_type": "composite", "source_reference": "",
    },
    # --- IAS Officer (India) --------------------------------------------
    {
        "id": "story_ias_officer_india_2", "career_id": "ias_officer_india",
        "person_label": "IAS Officer, 3 years experience (India)",
        "background": "Attempted the UPSC civil services exam four times over six years while working a full-time job to support family, before finally succeeding.",
        "journey": "Continued studying early mornings and late nights for years, repeatedly falling just short of the required rank, before a fifth and final successful attempt.",
        "challenges": "Faced enormous family and social pressure around the repeated attempts, in a context where the exam's difficulty and prestige are widely understood.",
        "turning_points": "A supportive comment from a previous year's failed-attempt rank list, showing steady incremental improvement each year, was what kept them from giving up before the final attempt.",
        "advice": "Track your own incremental progress across attempts, not just the pass/fail outcome — steady improvement is a real signal worth trusting.",
        "lessons_learned": "Multiple years of near-misses on an extremely competitive exam can still end in success if the underlying trend is genuinely improving.",
        "trait_tags": ["motivation", "values"],
        "timeline": [
            {"stage": "career_transition", "label": "Working while studying", "description": "Worked a full-time job to support family while studying for the UPSC exam.", "year_label": "Year 0"},
            {"stage": "failure", "label": "Four unsuccessful attempts", "description": "Fell short of the required rank across four attempts over six years.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "A fifth, successful attempt", "description": "Succeeded on a fifth attempt after years of steady incremental improvement.", "year_label": "Year 6"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Six years and four unsuccessful UPSC attempts, under significant family and social pressure.",
        "current_outcome": "Works as an IAS officer, selection secured on a fifth attempt after years of tracked incremental progress.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ias_officer_india_3", "career_id": "ias_officer_india",
        "person_label": "IAS Officer, 7 years experience (India)",
        "background": "Was working as an engineer at a private company, financially secure, when they decided to leave and pursue the civil services exam full-time.",
        "journey": "Quit a stable, well-paying job with no guarantee of exam success, studying full-time for two years on savings before being selected.",
        "challenges": "Watched savings steadily deplete during the two years of full-time preparation, with real financial anxiety about the decision if the exam didn't work out.",
        "turning_points": "Passing the exam on the very attempt they had privately decided would be their last, before returning to engineering if unsuccessful, made the risk feel retroactively justified.",
        "advice": "A full-time pivot to prepare for a highly competitive exam is a genuine financial risk — go in with a clear, honest limit for how long you'll try before reassessing.",
        "lessons_learned": "Setting an honest limit in advance, rather than pursuing a goal indefinitely, can make an otherwise risky full-time pivot more manageable.",
        "trait_tags": ["motivation", "leadership"],
        "timeline": [
            {"stage": "first_job", "label": "Private-sector engineer", "description": "Worked as an engineer at a private company, financially secure.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Quitting to study full-time", "description": "Quit a stable job to study full-time for two years on savings.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Passing on the self-imposed final attempt", "description": "Passed the exam on the attempt they had privately decided would be their last.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": True,
        "uncertainty_period": "Two years of full-time exam preparation on depleting savings, with real financial anxiety about the decision.",
        "current_outcome": "Works as an IAS officer, a financially risky full-time pivot that succeeded within a self-imposed limit.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ias_officer_india_4", "career_id": "ias_officer_india",
        "person_label": "IAS Officer, 12 years experience (India)",
        "background": "Came from a rural farming family with no prior history of government service, the first in their extended family to attempt the civil services exam.",
        "journey": "Had to travel significant distances for coaching and study resources unavailable locally, relying on scholarships and family sacrifice to fund preparation.",
        "challenges": "Lacked the informal guidance and family networks more urban, established candidates often had access to during preparation.",
        "turning_points": "Being posted, years later, to a district that included villages similar to the one they grew up in gave their administrative work a direct, personal resonance.",
        "advice": "Coming from a background without established networks in civil service is a real disadvantage in preparation, but not in the actual work once selected.",
        "lessons_learned": "A background without institutional advantages can become a source of unusually direct, personal motivation once the work itself begins.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "school", "label": "Rural farming family, no prior civil service history", "description": "Grew up in a rural farming family, the first to attempt the civil services exam.", "year_label": "Year 0"},
            {"stage": "university", "label": "Traveling for coaching resources", "description": "Traveled significant distances for coaching unavailable locally, funded by scholarships.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Posted near a familiar community", "description": "Was posted to a district including villages similar to the one they grew up in.", "year_label": "Year 8"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Preparing without the informal guidance and networks more established candidates often had access to.",
        "current_outcome": "Works as an IAS officer, administrative work carrying direct personal resonance from a rural background.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ias_officer_india_5", "career_id": "ias_officer_india",
        "person_label": "IAS Officer, 5 years experience (India)",
        "background": "Studied medicine and briefly practiced as a doctor before deciding clinical practice wasn't where they wanted to have long-term impact.",
        "journey": "Left medical practice after two years to prepare for the civil services exam, drawn to policy-level impact on public health rather than individual patient care.",
        "challenges": "Faced significant confusion and pushback from family and medical colleagues about leaving a respected, established medical career.",
        "turning_points": "Being posted to a health administration role that let them redesign a district's public health program used both the medical background and the new administrative authority together.",
        "advice": "Leaving one respected, established career for another isn't a step down if the second path lets you use the first career's expertise at a different scale.",
        "lessons_learned": "Administrative and policy roles can be a genuine continuation of a clinical calling, applied at a different, larger scale rather than a departure from it.",
        "trait_tags": ["values", "leadership"],
        "timeline": [
            {"stage": "first_job", "label": "Practicing physician", "description": "Practiced medicine for two years before deciding clinical practice wasn't the right long-term fit.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Leaving medicine for the civil services exam", "description": "Left medical practice to prepare for the civil services exam.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Redesigning a district health program", "description": "Was posted to a health administration role and redesigned a district's public health program.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as an IAS officer in health administration, applying medical expertise at a policy scale rather than individually.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_ias_officer_india_6", "career_id": "ias_officer_india",
        "person_label": "IAS Officer, 1 year experience (India)",
        "background": "Prepared for the civil services exam while simultaneously working a demanding corporate job, studying almost entirely on commutes and weekends.",
        "journey": "Succeeded on the first attempt, an outcome widely considered unusual given the limited dedicated study time available while employed full-time.",
        "challenges": "Had almost no leisure time for nearly two years, sustaining the dual load of a demanding job and rigorous exam preparation simultaneously.",
        "turning_points": "A structured, ruthlessly prioritized study plan, built specifically around the limited available hours, proved more effective than the unlimited-time approach many full-time candidates used.",
        "advice": "Working full-time while preparing for a major exam isn't automatically a disadvantage — tight constraints can force a more efficient, prioritized study approach.",
        "lessons_learned": "A severely limited amount of study time, used with rigorous prioritization, can outperform an unlimited amount of time used less deliberately.",
        "trait_tags": ["motivation", "work_preferences"],
        "timeline": [
            {"stage": "career_transition", "label": "Studying around a full-time job", "description": "Prepared for the exam almost entirely on commutes and weekends while employed full-time.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A ruthlessly prioritized study plan", "description": "Built a structured study plan around limited available hours.", "year_label": "Year 1"},
            {"stage": "current_role", "label": "IAS Officer", "description": "Succeeded on the first attempt despite limited dedicated study time.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Nearly two years with almost no leisure time, sustaining a demanding job alongside rigorous exam preparation.",
        "current_outcome": "Works as an IAS officer, having succeeded on the first attempt through disciplined prioritization rather than unlimited study time.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    # --- UK Civil Service Fast Streamer -------------------------------------
    {
        "id": "story_uk_civil_service_fast_streamer_1", "career_id": "uk_civil_service_fast_streamer",
        "person_label": "Civil Service Fast Streamer, 2 years experience",
        "background": "Studied history at university with no specific career plan, assuming it would lead to teaching or further academic study.",
        "journey": "Applied to the Fast Stream programme on the recommendation of a university careers advisor, mostly to keep options open rather than out of a strong initial interest.",
        "challenges": "Felt initially unqualified compared to fellow Fast Streamers with more directly relevant degrees in politics, economics, or public policy.",
        "turning_points": "A rotation working on a historical policy review, where their history training let them analyze precedent more thoroughly than colleagues, proved the degree was directly useful, not just tangentially relevant.",
        "advice": "A humanities degree without an obvious career pipeline can still be a genuine asset in policy work — the analytical skills transfer more than they seem to on paper.",
        "lessons_learned": "A degree chosen without a specific career plan in mind can still turn out to be directly, unexpectedly useful in an eventual role.",
        "trait_tags": ["analytical_thinking", "curiosity"],
        "timeline": [
            {"stage": "university", "label": "History degree, no clear plan", "description": "Studied history with no specific career plan.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Applying to the Fast Stream", "description": "Applied to the Fast Stream programme on a careers advisor's recommendation.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "A historical policy review", "description": "A rotation on a historical policy review proved the history degree directly useful.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a Civil Service Fast Streamer, a history degree proving unexpectedly and directly useful in policy work.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_uk_civil_service_fast_streamer_2", "career_id": "uk_civil_service_fast_streamer",
        "person_label": "Civil Service Fast Streamer, 4 years experience",
        "background": "Worked in retail management for three years after leaving university without completing a planned graduate scheme application cycle.",
        "journey": "Applied to the Fast Stream at the maximum eligible age, several years after most applicants, after growing restless with retail management's ceiling.",
        "challenges": "Felt noticeably older than most fellow Fast Streamers during the initial cohort training, questioning whether the age gap would be a genuine obstacle.",
        "turning_points": "Being specifically valued for real people-management experience from retail, which many younger Fast Streamers lacked, reframed the age gap as an asset in early rotations.",
        "advice": "There's no fixed 'right age' to enter a competitive graduate scheme — real management experience gained elsewhere can offset arriving later than typical.",
        "lessons_learned": "Years spent in an unrelated but genuinely skill-building role, like retail management, aren't wasted time relative to a more direct, earlier entry path.",
        "trait_tags": ["leadership", "motivation"],
        "timeline": [
            {"stage": "first_job", "label": "Retail management", "description": "Worked in retail management for three years after university.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Applying at the maximum eligible age", "description": "Applied to the Fast Stream several years after most applicants.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "People-management experience valued", "description": "Was valued for real people-management experience many younger Fast Streamers lacked.", "year_label": "Year 4"},
        ],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Uncertainty about whether entering the programme later than typical would be a genuine obstacle.",
        "current_outcome": "Works as a Fast Streamer, retail management experience recognized as a genuine asset rather than a delay.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_uk_civil_service_fast_streamer_3", "career_id": "uk_civil_service_fast_streamer",
        "person_label": "Civil Service Fast Streamer, 1 year experience",
        "background": "Was rejected from the Fast Stream programme on a first application straight out of university, without clear feedback on why.",
        "journey": "Spent a year working for a local council in a junior policy support role, then reapplied to the Fast Stream with concrete local government experience to point to.",
        "challenges": "Faced real disappointment after the first rejection, uncertain whether to reapply or pursue a different path in local government permanently.",
        "turning_points": "Being asked directly, in the second application's interview, about the local council experience — clearly the deciding factor missing the first time — confirmed the year had closed the right gap.",
        "advice": "A first rejection from a competitive scheme without clear feedback can still be addressed by proactively building the kind of experience the scheme likely values.",
        "lessons_learned": "A year spent in adjacent, hands-on public-sector work can supply exactly the concrete experience an unclear rejection was actually about.",
        "trait_tags": ["motivation", "values"],
        "timeline": [
            {"stage": "university", "label": "First Fast Stream rejection", "description": "Was rejected from the Fast Stream on a first application straight out of university.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Local council policy support", "description": "Worked for a local council in a junior policy support role for a year.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "Reapplying with concrete experience", "description": "Reapplied with local council experience, clearly the deciding factor in the second interview.", "year_label": "Year 1"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Real disappointment and uncertainty after a first unclear rejection, unsure whether to reapply.",
        "current_outcome": "Works as a Fast Streamer, entrance secured on a second attempt built on concrete local government experience.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_uk_civil_service_fast_streamer_4", "career_id": "uk_civil_service_fast_streamer",
        "person_label": "Civil Service Fast Streamer, 6 years experience",
        "background": "Studied economics and initially planned a career in investment banking, completing several finance-focused internships during university.",
        "journey": "Turned down a banking offer after a summer internship left them uneasy about the sector's day-to-day incentive structure, applying to the Fast Stream instead.",
        "challenges": "Faced real skepticism from university peers and family about turning down a prestigious, high-paying banking offer for public service.",
        "turning_points": "Leading an economic policy project with directly visible public benefit, unlike the internship's more abstract client value, confirmed the trade-off had been worth it.",
        "advice": "A prestigious offer that leaves you uneasy is worth taking that unease seriously, even against significant social and financial pressure to accept it.",
        "lessons_learned": "Turning down a conventionally prestigious path for one aligned with your actual values can be the right call, even when it's hard to explain to others at the time.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Economics degree, banking internships", "description": "Studied economics, planning investment banking, with finance-focused internships.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "Turning down a banking offer", "description": "Turned down a banking offer after an internship left them uneasy about the sector.", "year_label": "Year 3"},
            {"stage": "current_role", "label": "Civil Service Fast Streamer", "description": "Led an economic policy project with directly visible public benefit.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a Fast Streamer, having turned down a prestigious banking offer for values-aligned public service.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_uk_civil_service_fast_streamer_5", "career_id": "uk_civil_service_fast_streamer",
        "person_label": "Civil Service Fast Streamer, 3 years experience",
        "background": "Immigrated as a teenager and became a naturalized citizen just before the minimum eligibility window for applying to the Fast Stream.",
        "journey": "Spent the intervening years working in a variety of part-time and administrative roles while waiting for citizenship eligibility, treating the wait as active preparation rather than passive delay.",
        "challenges": "Faced a genuinely uncertain, multi-year wait for citizenship processing, with no guaranteed timeline for when eligibility would actually arrive.",
        "turning_points": "Finally receiving citizenship confirmation and being able to apply immediately, with years of prepared material and practice interviews ready, made the long wait feel purposeful rather than wasted.",
        "advice": "If eligibility for something you want is genuinely out of your control and delayed, use the waiting period deliberately rather than treating it as dead time.",
        "lessons_learned": "A long, uncertain wait for eligibility can still be used to prepare thoroughly, so the eventual opportunity is met fully ready rather than from a standing start.",
        "trait_tags": ["motivation", "values"],
        "timeline": [
            {"stage": "career_transition", "label": "Awaiting citizenship eligibility", "description": "Waited a genuinely uncertain, multi-year period for citizenship processing.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Part-time and administrative roles", "description": "Worked a variety of part-time and administrative roles while waiting, treating it as active preparation.", "year_label": "Year 2"},
            {"stage": "turning_point", "label": "Citizenship confirmed, applying immediately", "description": "Received citizenship confirmation and applied immediately with years of prepared material.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "A multi-year, genuinely uncertain wait for citizenship eligibility with no guaranteed timeline.",
        "current_outcome": "Works as a Fast Streamer, a long eligibility wait used deliberately to prepare rather than treated as wasted time.",
        "industry": "public administration", "story_type": "composite", "source_reference": "",
    },
    # --- Municipal Urban Planner --------------------------------------------
    {
        "id": "story_urban_planner_1", "career_id": "urban_planner",
        "person_label": "Municipal Urban Planner, 5 years experience",
        "background": "Studied architecture with a strong interest in individual building design, not city-scale planning.",
        "journey": "Worked at an architecture firm for two years before realizing the constraints they found most interesting were at the neighborhood and city scale, not the single-building scale.",
        "challenges": "Had to return to school for an urban planning credential, effectively restarting at a junior level after already building two years of architecture experience.",
        "turning_points": "Working on a public plaza redesign that visibly changed how an entire neighborhood used the space, rather than just one building, confirmed the scale shift was the right call.",
        "advice": "If the scale of the problems you're most drawn to doesn't match your current role's scope, it's worth considering an adjacent field, even if it means restarting.",
        "lessons_learned": "The specific scale of a problem — building versus block versus city — can matter as much as the subject matter itself in finding the right fit.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "university", "label": "Architecture degree", "description": "Studied architecture with a strong interest in individual building design.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Architecture firm", "description": "Worked at an architecture firm for two years.", "year_label": "Year 1"},
            {"stage": "career_transition", "label": "Urban planning credential", "description": "Returned to school for an urban planning credential, restarting at a junior level.", "year_label": "Year 3"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a municipal urban planner, having found neighborhood-scale problems a better fit than single-building design.",
        "industry": "urban development", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_urban_planner_2", "career_id": "urban_planner",
        "person_label": "Municipal Urban Planner, 8 years experience",
        "background": "Grew up in a rapidly changing neighborhood, watching gentrification displace long-time residents including their own extended family.",
        "journey": "Studied urban planning specifically motivated by wanting to influence how future development balanced growth against displacement, rather than treating displacement as an unavoidable side effect.",
        "challenges": "Frequently found themselves in professional tension with developers and even some colleagues who saw displacement concerns as secondary to growth targets.",
        "turning_points": "Successfully advocating for an affordable-housing requirement in a major development plan, over significant developer pushback, felt like a direct answer to their original motivation.",
        "advice": "A personal experience of a systemic problem, like displacement, can sustain the professional persistence needed to actually change how that problem gets handled.",
        "lessons_learned": "Professional tension with colleagues over values isn't necessarily a sign you're in the wrong role — sometimes it's a sign the role needs your specific values represented.",
        "trait_tags": ["values", "leadership"],
        "timeline": [
            {"stage": "school", "label": "Watching gentrification firsthand", "description": "Grew up watching gentrification displace long-time residents, including extended family.", "year_label": "Year 0"},
            {"stage": "university", "label": "Urban planning, motivated by displacement", "description": "Studied urban planning motivated by wanting to balance growth against displacement.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "An affordable-housing requirement", "description": "Successfully advocated for an affordable-housing requirement over developer pushback.", "year_label": "Year 8"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a municipal urban planner, professional persistence sustained by a personal experience of displacement.",
        "industry": "urban development", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_urban_planner_3", "career_id": "urban_planner",
        "person_label": "Municipal Urban Planner, 3 years experience",
        "background": "Studied civil engineering with a focus on transportation infrastructure, without direct interest in the broader planning process around it.",
        "journey": "Took a transportation planning role at a city agency and gradually became involved in the wider land-use decisions that transportation projects depended on.",
        "challenges": "Had to build political and stakeholder-negotiation skills that pure engineering training hadn't required, since planning work involves far more public input than infrastructure design alone.",
        "turning_points": "Leading a contentious public meeting about a proposed transit line, and successfully finding a compromise route, proved they could handle the human side of planning, not just the technical side.",
        "advice": "An engineering background is a strong foundation for planning, but be ready to build negotiation and public-communication skills the technical training won't cover.",
        "lessons_learned": "Planning work requires as much stakeholder negotiation skill as technical infrastructure knowledge — the two need to be built together.",
        "trait_tags": ["analytical_thinking", "communication"],
        "timeline": [
            {"stage": "university", "label": "Civil engineering, transportation focus", "description": "Studied civil engineering focused on transportation infrastructure.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Transportation planning role", "description": "Took a transportation planning role at a city agency.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A contentious public meeting", "description": "Led a public meeting about a proposed transit line and found a compromise route.", "year_label": "Year 3"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a municipal urban planner, having built negotiation skills alongside the original engineering training.",
        "industry": "urban development", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_urban_planner_4", "career_id": "urban_planner",
        "person_label": "Municipal Urban Planner, 10 years experience",
        "background": "Started as a junior planner in a fast-growing suburban city, working almost entirely on greenfield residential development approvals.",
        "journey": "Requested a transfer to a much older, established city's planning department, drawn to the more complex problem of retrofitting infrastructure into existing dense areas.",
        "challenges": "Found the retrofit work far slower and more politically complicated than greenfield approvals, which had been comparatively straightforward.",
        "turning_points": "Successfully completing a years-long project converting an underused industrial corridor into mixed-use development taught patience that greenfield work never had to teach.",
        "advice": "Greenfield and retrofit planning are genuinely different skill sets — if one feels too easy or too frustrating, the other type of city might be a better fit.",
        "lessons_learned": "Complex, slow-moving retrofit projects can be more professionally satisfying than faster, simpler greenfield work, even though they're objectively harder.",
        "trait_tags": ["work_preferences", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "Greenfield suburban planning", "description": "Worked as a junior planner on greenfield residential development approvals.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Transfer to an established city", "description": "Requested a transfer to an older city's planning department for retrofit work.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "An industrial corridor conversion", "description": "Completed a years-long project converting an industrial corridor into mixed-use development.", "year_label": "Year 9"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a municipal urban planner specializing in retrofit projects, a deliberate move from faster greenfield work.",
        "industry": "urban development", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_urban_planner_5", "career_id": "urban_planner",
        "person_label": "Municipal Urban Planner, 2 years experience",
        "background": "Studied environmental science with a focus on climate resilience, without a specific plan around urban planning as a career.",
        "journey": "Took an internship with a city's climate adaptation office and discovered urban planning was where climate resilience actually got implemented at the neighborhood level.",
        "challenges": "Had to learn zoning law and land-use regulation essentially from scratch, since environmental science training hadn't covered the regulatory side of implementation.",
        "turning_points": "Seeing a flood-resilience zoning change they'd worked on directly protect homes during an actual flood event within their first year made the regulatory learning curve feel worthwhile.",
        "advice": "If you're drawn to environmental issues but want to see tangible, local implementation rather than only research or advocacy, urban planning is where that often happens.",
        "lessons_learned": "Environmental science expertise finds real, direct implementation through the unglamorous regulatory work of urban planning.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Environmental science, climate resilience focus", "description": "Studied environmental science with a focus on climate resilience.", "year_label": "Year 0"},
            {"stage": "internship", "label": "Climate adaptation office", "description": "Interned with a city's climate adaptation office.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "A zoning change protects homes", "description": "A flood-resilience zoning change they worked on directly protected homes during a real flood.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a municipal urban planner, implementing climate resilience through zoning rather than research or advocacy alone.",
        "industry": "urban development", "story_type": "composite", "source_reference": "",
    },
    # --- Public Health Policy Analyst ---------------------------------------
    {
        "id": "story_public_health_policy_analyst_1", "career_id": "public_health_policy_analyst",
        "person_label": "Public Health Policy Analyst, 4 years experience",
        "background": "Worked as an emergency room nurse for five years, seeing the same preventable conditions arrive repeatedly due to gaps in upstream public health policy.",
        "journey": "Left direct clinical nursing to pursue a public health policy degree, driven by frustration at treating the same downstream symptoms of policy failures repeatedly.",
        "challenges": "Missed the immediate, tangible feedback of direct patient care during the transition to slower-moving, more abstract policy work.",
        "turning_points": "Seeing a policy change they'd helped draft measurably reduce ER visits for a specific preventable condition, a year after implementation, provided the tangible feedback policy work usually lacks.",
        "advice": "If you're treating the same preventable problem repeatedly in a frontline role, consider whether policy work might address the actual source rather than the symptoms.",
        "lessons_learned": "Policy work's feedback loop is much slower than clinical care's, but it can eventually deliver the kind of large-scale impact frontline work alone can't.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "Emergency room nurse", "description": "Worked as an ER nurse for five years, seeing repeated preventable conditions.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Public health policy degree", "description": "Left clinical nursing to pursue a public health policy degree.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "A policy change reduces ER visits", "description": "A policy change they helped draft measurably reduced ER visits for a preventable condition.", "year_label": "Year 7"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a public health policy analyst, addressing the upstream causes clinical nursing could only treat downstream.",
        "industry": "public health & policy", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_public_health_policy_analyst_2", "career_id": "public_health_policy_analyst",
        "person_label": "Public Health Policy Analyst, 6 years experience",
        "background": "Studied economics with a focus on health economics, expecting to work in insurance or hospital financial analysis.",
        "journey": "A graduate internship at a health department's policy office, taken mainly for the resume line, revealed a stronger interest in population-level health outcomes than institutional finance.",
        "challenges": "Took a lower starting salary in public policy compared to the private-sector health finance offers they'd also received.",
        "turning_points": "Modeling the population health impact of a proposed tobacco tax change, and seeing that model directly inform legislative debate, made the pay difference feel like a reasonable trade.",
        "advice": "A resume-line internship, taken without much enthusiasm, can end up revealing your genuine interest more clearly than a carefully chosen one.",
        "lessons_learned": "Seeing your analysis directly inform a real policy debate can outweigh a private-sector salary premium, if that kind of impact is what actually motivates you.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "university", "label": "Health economics degree", "description": "Studied health economics expecting to work in insurance or hospital finance.", "year_label": "Year 0"},
            {"stage": "internship", "label": "Health department internship", "description": "Interned at a health department's policy office mainly for the resume line.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "A tobacco tax model informs debate", "description": "Modeled the population health impact of a proposed tobacco tax change, informing legislative debate.", "year_label": "Year 5"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a public health policy analyst, having chosen legislative impact over a higher private-sector salary.",
        "industry": "public health & policy", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_public_health_policy_analyst_3", "career_id": "public_health_policy_analyst",
        "person_label": "Public Health Policy Analyst, 2 years experience",
        "background": "Lived through a major public health emergency as a university student, watching policy decisions directly shape their community's outcomes in real time.",
        "journey": "That experience, initially just a disruptive part of student life, became the direct motivation for a graduate degree in public health policy afterward.",
        "challenges": "Struggled to translate a broad, emotionally driven interest in 'doing something' about public health into a specific, analytically rigorous skill set.",
        "turning_points": "A professor's feedback that their strongest work was the quantitative policy modeling, not the qualitative advocacy writing they'd expected to prefer, redirected their specialization.",
        "advice": "A strong emotional motivation to work in public health doesn't automatically tell you which specific skill set within the field — quantitative or advocacy-focused — actually suits you.",
        "lessons_learned": "The specific skill within a broad, motivating field that you're actually best at can differ from the one you initially assumed would be your strength.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "university", "label": "Living through a public health emergency", "description": "Lived through a major public health emergency as a university student.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Graduate study in public health policy", "description": "Pursued a graduate degree in public health policy, motivated by the emergency.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "Quantitative modeling over advocacy writing", "description": "A professor's feedback redirected specialization toward quantitative policy modeling.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a public health policy analyst specializing in quantitative modeling, a skill discovered rather than originally assumed.",
        "industry": "public health & policy", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_public_health_policy_analyst_4", "career_id": "public_health_policy_analyst",
        "person_label": "Public Health Policy Analyst, 9 years experience",
        "background": "Worked in pharmaceutical industry market access for six years, focused on getting new drugs approved for insurance reimbursement.",
        "journey": "Grew uncomfortable with aspects of the industry's pricing incentives and moved to a government policy role focused on drug affordability from the opposite side of the table.",
        "challenges": "Faced skepticism from new public-sector colleagues about whether industry experience represented a genuine change of perspective or just a career move.",
        "turning_points": "Using detailed knowledge of industry pricing strategy to help draft a more effective affordability regulation proved the industry background was a genuine asset, not a conflict.",
        "advice": "Industry experience in a field you now want to help regulate isn't disqualifying — used honestly, it can make you more effective at understanding how the regulation will actually be received.",
        "lessons_learned": "Insider knowledge of an industry's incentive structure can become the specific expertise that makes a policy role protecting the public more effective, not less credible.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Pharmaceutical market access", "description": "Worked in pharmaceutical market access for six years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Move to government policy", "description": "Moved to a government policy role focused on drug affordability.", "year_label": "Year 6"},
            {"stage": "turning_point", "label": "Industry knowledge drafts better regulation", "description": "Used industry pricing knowledge to help draft a more effective affordability regulation.", "year_label": "Year 7"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a public health policy analyst, industry pricing expertise now applied to public-interest regulation.",
        "industry": "public health & policy", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_public_health_policy_analyst_5", "career_id": "public_health_policy_analyst",
        "person_label": "Public Health Policy Analyst, 1 year experience",
        "background": "Studied data science with a general interest in social impact applications, without a specific focus on health.",
        "journey": "Joined a public health department's data team on a short-term contract, which was extended repeatedly as their analysis proved directly useful to ongoing policy decisions.",
        "challenges": "Faced job insecurity for over a year, working on a series of short-term contract renewals rather than a stable permanent position.",
        "turning_points": "Being offered a permanent policy analyst role, specifically citing the contract work's consistent impact, ended the extended period of contract-to-contract uncertainty.",
        "advice": "A string of short-term contract renewals can be genuinely stressful, but it can also be the slow, real path to a permanent role if the work keeps proving its value.",
        "lessons_learned": "Contract instability, while stressful, doesn't necessarily mean a lack of genuine progress toward a stable role — sometimes it's simply how that progress unfolds.",
        "trait_tags": ["analytical_thinking", "motivation"],
        "timeline": [
            {"stage": "university", "label": "Data science degree", "description": "Studied data science with a general interest in social impact applications.", "year_label": "Year 0"},
            {"stage": "first_job", "label": "Short-term contract renewals", "description": "Worked a series of short-term contract renewals on a public health data team.", "year_label": "Year 1"},
            {"stage": "turning_point", "label": "A permanent role offered", "description": "Was offered a permanent policy analyst role after the contract work's consistent impact.", "year_label": "Year 2"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Over a year of job insecurity across a series of short-term contract renewals.",
        "current_outcome": "Works as a public health policy analyst in a permanent role, secured through consistent contract-based impact.",
        "industry": "public health & policy", "story_type": "composite", "source_reference": "",
    },
    # --- Human Rights Researcher ---------------------------------------------
    {
        "id": "story_human_rights_researcher_1", "career_id": "human_rights_researcher",
        "person_label": "Human Rights Researcher, 3 years experience",
        "background": "Studied journalism and worked as a foreign correspondent for four years, covering conflict zones and their humanitarian aftermath.",
        "journey": "Grew frustrated with journalism's episodic coverage of human rights abuses and moved into rights documentation work that continued past the news cycle.",
        "challenges": "Had to learn the specific legal and evidentiary standards human rights documentation requires, which journalism training hadn't covered.",
        "turning_points": "Contributing documentation used in an actual accountability proceeding, rather than a news story that faded within days, gave a sense of durable impact journalism hadn't provided.",
        "advice": "If journalism's fast news cycle feels frustrating for covering deep, ongoing issues, human rights documentation offers the same investigative skills applied over a longer arc.",
        "lessons_learned": "Investigative skills built in journalism transfer directly to human rights documentation, which can offer a more durable form of accountability than a single news cycle.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "first_job", "label": "Foreign correspondent", "description": "Worked as a foreign correspondent covering conflict zones for four years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Move to rights documentation", "description": "Moved into human rights documentation work that continued past the news cycle.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Documentation used in accountability proceedings", "description": "Contributed documentation used in an actual accountability proceeding.", "year_label": "Year 6"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a human rights researcher, applying journalism investigative skills toward more durable accountability outcomes.",
        "industry": "human rights advocacy", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_human_rights_researcher_2", "career_id": "human_rights_researcher",
        "person_label": "Human Rights Researcher, 6 years experience",
        "background": "Studied law with the original goal of corporate legal practice, completing a standard sequence of commercial law internships.",
        "journey": "A required pro bono placement during law school, working on an asylum case, redirected their entire legal interest toward human rights work.",
        "challenges": "Took a substantial pay cut moving from the corporate law track into human rights nonprofit work after graduation.",
        "turning_points": "The asylum case they'd worked on during the placement was ultimately successful, giving direct, tangible evidence of the kind of outcome corporate work rarely offered.",
        "advice": "A required placement you didn't choose, like mandatory pro bono work, can end up revealing your real professional direction more clearly than your planned track.",
        "lessons_learned": "A single case with a direct, tangible human outcome can outweigh years of planned career direction built around prestige or income alone.",
        "trait_tags": ["values", "analytical_thinking"],
        "timeline": [
            {"stage": "university", "label": "Law school, corporate track", "description": "Studied law with the original goal of corporate legal practice.", "year_label": "Year 0"},
            {"stage": "turning_point", "label": "A required asylum case placement", "description": "A required pro bono placement working on an asylum case redirected legal interest.", "year_label": "Year 2"},
            {"stage": "career_transition", "label": "Human rights nonprofit work", "description": "Took a pay cut to move into human rights nonprofit work after graduation.", "year_label": "Year 3"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a human rights researcher, a required placement having redirected an original corporate law plan.",
        "industry": "human rights advocacy", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_human_rights_researcher_3", "career_id": "human_rights_researcher",
        "person_label": "Human Rights Researcher, 4 years experience",
        "background": "Grew up in a country under an authoritarian government, later emigrating for university study elsewhere.",
        "journey": "Studied political science specifically to understand the systemic conditions behind the human rights situation they'd grown up under, then moved directly into human rights research.",
        "challenges": "Found the research work emotionally difficult at times, given how closely it mirrored personal and family experiences.",
        "turning_points": "Publishing a research report specifically cited in international pressure on the government of their home country connected personal history directly to professional output.",
        "advice": "Personal experience of the systemic issue you research can be emotionally taxing, but it also brings an understanding no purely academic training can replicate.",
        "lessons_learned": "The most emotionally difficult research to do is sometimes also the research you're most equipped, by lived experience, to do well.",
        "trait_tags": ["values", "motivation"],
        "timeline": [
            {"stage": "school", "label": "Growing up under authoritarian government", "description": "Grew up in a country under an authoritarian government before emigrating.", "year_label": "Year 0"},
            {"stage": "university", "label": "Political science, motivated by lived experience", "description": "Studied political science to understand the systemic conditions they grew up under.", "year_label": "Year 5"},
            {"stage": "turning_point", "label": "A report cited in international pressure", "description": "Published a research report specifically cited in international pressure on their home government.", "year_label": "Year 8"},
        ],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Ongoing emotional difficulty doing research work that closely mirrored personal and family experience.",
        "current_outcome": "Works as a human rights researcher, personal history now directly informing internationally cited research.",
        "industry": "human rights advocacy", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_human_rights_researcher_4", "career_id": "human_rights_researcher",
        "person_label": "Human Rights Researcher, 8 years experience",
        "background": "Worked as a statistician for a market research firm for four years, applying quantitative methods to consumer behavior studies.",
        "journey": "Volunteered evenings and weekends helping a human rights organization analyze survey data, and was eventually offered a full-time research role there.",
        "challenges": "Had to learn an entirely new subject-matter domain, since quantitative skills from market research didn't automatically transfer human rights context and ethics.",
        "turning_points": "A statistical analysis they contributed, identifying a pattern of abuse across a large dataset that qualitative review alone had missed, proved quantitative skills had a genuine, distinct role in the field.",
        "advice": "Quantitative skills built in an unrelated commercial field can find a genuinely valuable second life in human rights work, which increasingly relies on large-scale data analysis.",
        "lessons_learned": "A technical skill set built for one purpose, like market research statistics, can uncover patterns in a completely different, higher-stakes domain that purely qualitative methods would miss.",
        "trait_tags": ["analytical_thinking", "values"],
        "timeline": [
            {"stage": "first_job", "label": "Market research statistician", "description": "Worked as a statistician for a market research firm for four years.", "year_label": "Year 0"},
            {"stage": "career_transition", "label": "Volunteering with a human rights organization", "description": "Volunteered evenings and weekends analyzing survey data for a human rights organization.", "year_label": "Year 4"},
            {"stage": "turning_point", "label": "Statistics uncover a hidden abuse pattern", "description": "Contributed a statistical analysis identifying a pattern of abuse a qualitative review had missed.", "year_label": "Year 5"},
        ],
        "career_switch": True, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a human rights researcher, applying market research statistical training to uncovering abuse patterns at scale.",
        "industry": "human rights advocacy", "story_type": "composite", "source_reference": "",
    },
    {
        "id": "story_human_rights_researcher_5", "career_id": "human_rights_researcher",
        "person_label": "Human Rights Researcher, 2 years experience",
        "background": "Studied anthropology with a focus on community-based fieldwork, initially planning an academic research career.",
        "journey": "A fieldwork placement documenting a marginalized community's living conditions led directly to a job offer from a human rights organization working with that same community.",
        "challenges": "Had to navigate real tension between academic research norms, which prioritize neutral observation, and advocacy work, which requires taking an active position.",
        "turning_points": "A community member directly telling them the documentation had helped secure a concrete policy change reframed the value of moving from observation to advocacy.",
        "advice": "Academic fieldwork skills translate well into human rights research, but be ready for the shift from observing a situation to actively advocating to change it.",
        "lessons_learned": "The move from academic observation to advocacy work is a real adjustment, but the underlying fieldwork skills carry over directly.",
        "trait_tags": ["curiosity", "values"],
        "timeline": [
            {"stage": "university", "label": "Anthropology, community fieldwork", "description": "Studied anthropology with a focus on community-based fieldwork.", "year_label": "Year 0"},
            {"stage": "internship", "label": "A fieldwork placement", "description": "Completed a fieldwork placement documenting a marginalized community's living conditions.", "year_label": "Year 3"},
            {"stage": "turning_point", "label": "Documentation secures a policy change", "description": "A community member confirmed the documentation had helped secure a concrete policy change.", "year_label": "Year 4"},
        ],
        "career_switch": False, "gap_year": False, "uncertainty_period": "",
        "current_outcome": "Works as a human rights researcher, having moved from academic observation into direct advocacy work.",
        "industry": "human rights advocacy", "story_type": "composite", "source_reference": "",
    },
]


async def seed() -> None:
    client = get_supabase_client()
    stories = [CareerStory.model_validate(s) for s in STORIES]

    def _upsert() -> None:
        client.table("career_stories").upsert(
            [s.model_dump(mode="json") for s in stories]
        ).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(stories)} public service & policy Journey Stories.")


if __name__ == "__main__":
    asyncio.run(seed())
