"""Student Stories (Connect restructuring) — second batch, bringing the
standalone student-discovery catalog from 24 to 54 entries, matching the
PRD's 50-100 quality-over-quantity target. Same conventions as
seed_student_discovery_stories.py: every row is
story_type="composite_student_discovery", illustrative composites built
from common exploration patterns, never a claim of a specific real
individual. Covers the 3 careers the first batch didn't reach
(health_informatics_specialist, product_led_growth_specialist,
uk_civil_service_fast_streamer) plus a genuinely different narrative
angle on every career already covered once — not a re-templated repeat.

Run via: python -m aureon.scripts.seed_student_discovery_stories_batch2
Idempotent: safe to re-run (upsert on id).
"""

import asyncio

from aureon.domain.models.career import CareerStory
from aureon.services.supabase.client import get_supabase_client

STORIES: list[dict] = [
    {
        "id": "student_story_health_informatics_1", "career_id": "health_informatics_specialist",
        "person_label": "First-Generation College Student, Rural Background",
        "background": "Grew up in a small town an hour from the nearest hospital and always assumed 'working in healthcare' meant becoming a nurse or doctor — the only two healthcare jobs anyone around them had ever named.",
        "journey": "A summer internship filing digital records at a rural clinic turned into fixing the clinic's broken patient-scheduling spreadsheet, which turned into genuine fascination with how much of healthcare is actually information management, not bedside care.",
        "challenges": "Had no language for what they were interested in — 'I like organizing hospital data' didn't sound like a real career to say out loud at home.",
        "turning_points": "The clinic's office manager used the phrase 'health informatics' once, almost in passing, and it was the first time the interest had a name.",
        "advice": "If you can't name what you're interested in yet, that's not a sign you're not interested in anything real — sometimes the field just hasn't been named to you.",
        "lessons_learned": "A hospital runs on more than clinical work, and the parts that run on data and systems needed someone exactly like them.",
        "trait_tags": ["analytical_thinking", "systems_thinking", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "The whole internship, spent assuming they'd have to eventually pick between 'real healthcare work' and what they actually enjoyed.",
        "current_outcome": "Applying to health informatics programs, now able to explain the field clearly to family.",
        "industry": "healthcare technology",
        "discovery_themes": ["missing_world_discovery", "found_my_passion", "hidden_strength"],
    },
    {
        "id": "student_story_product_led_growth_1", "career_id": "product_led_growth_specialist",
        "person_label": "Second-Year Business Student",
        "background": "Picked a general business major because it felt safe and broad, without a specific direction, and grew increasingly bored by purely theoretical marketing coursework.",
        "journey": "A part-time job doing customer support for a small software company put them face to face with real user complaints daily — and they kept noticing patterns no one on the product team seemed to be tracking.",
        "challenges": "Assumed 'product' roles required a computer science background they didn't have, so didn't think it was open to them.",
        "turning_points": "Built a simple spreadsheet tracking which complaints led to cancellations and showed it to their manager unprompted — who forwarded it straight to the product team, who actually used it.",
        "advice": "Noticing a pattern no one else is tracking is a real, valuable skill on its own — you don't always need the 'expected' background to contribute something real.",
        "lessons_learned": "Business skills applied to a specific, concrete product problem feel completely different from business skills applied to nothing in particular.",
        "trait_tags": ["analytical_thinking", "communication", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Shifted their business major's electives toward product analytics, aiming for a product-focused role after graduation.",
        "industry": "technology & product",
        "discovery_themes": ["unexpected_career", "hidden_strength", "found_my_passion"],
    },
    {
        "id": "student_story_uk_civil_service_1", "career_id": "uk_civil_service_fast_streamer",
        "person_label": "Recent Graduate, One Year Into a Private-Sector Job",
        "background": "Took a well-paying consulting job right after graduation because it was the 'obvious good choice,' and every friend and family member congratulated them for it.",
        "journey": "A year into the job, the work paid well but felt disconnected from anything they actually cared about — a chance conversation with a former classmate now in public service made them realize they'd never seriously considered it.",
        "challenges": "Leaving a prestigious, well-paying job to apply for a government graduate scheme felt, to nearly everyone around them, like a step backward.",
        "turning_points": "Sitting down and writing out, honestly, what parts of their current job actually felt meaningful versus which parts they only valued because other people were impressed by them — the list was shorter than expected.",
        "advice": "A career that impresses other people and a career that's actually right for you are sometimes the same thing, and sometimes they're not — it's worth checking honestly which one you're in.",
        "lessons_learned": "Prestige and personal fit are two completely different measurements, and it's possible to have a lot of one and very little of the other.",
        "trait_tags": ["values", "decision_style", "persistence"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Several months of quietly questioning the job before telling anyone they were considering leaving.",
        "current_outcome": "Applied to a public service graduate scheme, awaiting results, prepared either way to keep asking this question of future jobs.",
        "industry": "public administration",
        "discovery_themes": ["changed_my_mind", "still_figuring_it_out", "unexpected_career"],
    },
    {
        "id": "student_story_ux_researcher_2", "career_id": "ux_researcher",
        "person_label": "Fine Arts Student",
        "background": "Enrolled in fine arts assuming 'design' meant galleries and visual art, and felt increasingly unsure that was really the life they wanted.",
        "journey": "A friend studying computer science asked them to sit in on a few informal usability tests for a class project — watching real people struggle to use an app was oddly the most engaging afternoon they'd had all semester.",
        "challenges": "Worried that moving toward tech-adjacent design would mean abandoning the visual/creative training they'd already invested in.",
        "turning_points": "Realized the usability sessions used exactly the same close observational skills their art training had already built — just pointed at people using software instead of pointed at a canvas.",
        "advice": "A skill you built for one purpose often transfers somewhere you didn't expect — it's worth asking what a skill actually *is*, not just what it was originally for.",
        "lessons_learned": "Creative training and technical fields aren't opposites — some of the most useful work sits exactly at their intersection.",
        "trait_tags": ["creativity", "empathy", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Most of their first two years, unsure if fine arts was really 'for' them long-term.",
        "current_outcome": "Adding a human-computer-interaction minor alongside their fine arts degree.",
        "industry": "technology & design",
        "discovery_themes": ["interdisciplinary_path", "creative_path", "found_my_passion"],
    },
    {
        "id": "student_story_conservation_biologist_2", "career_id": "conservation_biologist",
        "person_label": "Lifelong City Resident",
        "background": "Grew up in a dense city apartment with essentially zero regular access to nature, and never imagined conservation work as something available to someone like them.",
        "journey": "A mandatory university field course took the whole class to a wetland restoration site for one weekend — it was the first extended time they'd ever spent immersed in a natural ecosystem, and it left an unexpected, lasting impression.",
        "challenges": "Felt like an outsider among conservation-track classmates who'd grown up hiking and camping, worried they were 'behind' in ways that couldn't be caught up on.",
        "turning_points": "A professor pointed out that urban ecology and green infrastructure — bringing conservation thinking into cities — was an entire, growing subfield that needed people who understood city life, not despite their background but because of it.",
        "advice": "Not fitting the 'typical' image of a field doesn't mean you don't belong in it — sometimes your different background is exactly the perspective that field needs.",
        "lessons_learned": "There's more than one way into a field, and the 'standard' path isn't the only legitimate one.",
        "trait_tags": ["curiosity", "systems_thinking", "persistence"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Ongoing self-doubt about belonging, gradually easing as they found the urban ecology subfield.",
        "current_outcome": "Focusing their coursework on urban ecology and green infrastructure specifically.",
        "industry": "environmental conservation",
        "discovery_themes": ["non_traditional_path", "hidden_strength", "interdisciplinary_path"],
    },
    {
        "id": "student_story_genomics_data_scientist_2", "career_id": "genomics_data_scientist",
        "person_label": "Math Major, Assumed Biology Wasn't for Them",
        "background": "Was always 'the math person' in school and had quietly written off biology entirely after a rough high school experience with memorization-heavy coursework.",
        "journey": "A university statistics course used a genetics dataset as its main example, and the actual mathematical structure of the problem — pattern-finding across huge amounts of biological data — didn't resemble the memorization they remembered from high school biology at all.",
        "challenges": "Assumed switching any attention toward biology this late would mean abandoning years of math-focused progress.",
        "turning_points": "A conversation with the course's teaching assistant clarified that genomics research today leans heavily on exactly the statistical and computational skills they already had — biology was the subject, but math was the actual daily tool.",
        "advice": "The version of a subject you disliked in school is not necessarily what that subject actually is at a professional level — it might be worth a second look through a different door.",
        "lessons_learned": "Disliking how a subject was taught once is different from disliking the subject itself.",
        "trait_tags": ["analytical_thinking", "curiosity", "persistence"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Added a computational biology minor without changing their math major.",
        "industry": "biotechnology",
        "discovery_themes": ["changed_my_mind", "interdisciplinary_path", "stem_path"],
    },
    {
        "id": "student_story_civil_engineer_2", "career_id": "civil_engineer",
        "person_label": "Former Architecture Student",
        "background": "Started in architecture school specifically to design beautiful buildings, drawn entirely by the aesthetic and creative side of the profession.",
        "journey": "A joint studio project with civil engineering students, focused on making a building actually structurally sound rather than just visually striking, unexpectedly became the part of the project they cared about most.",
        "challenges": "Switching from architecture to civil engineering felt like giving up on the creative ambition that got them into the field in the first place.",
        "turning_points": "Realized that structural engineering has its own form of creativity — solving a genuinely hard physical problem elegantly — just expressed through different constraints than pure aesthetics.",
        "advice": "Leaving a specific path doesn't have to mean leaving what drew you to it in the first place — sometimes the thing you loved shows up again somewhere else.",
        "lessons_learned": "Creativity isn't confined to fields that look creative from the outside.",
        "trait_tags": ["creativity", "analytical_thinking", "persistence"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "One full semester spent deciding whether switching majors this late was a mistake.",
        "current_outcome": "Transferred into civil engineering, now specifically drawn to structural design.",
        "industry": "infrastructure & construction",
        "discovery_themes": ["changed_my_mind", "found_my_passion"],
    },
    {
        "id": "student_story_teacher_k12_2", "career_id": "teacher_k12",
        "person_label": "Finance Track Student",
        "background": "Was on a clear, family-approved track toward a finance career, with an internship already lined up, and no real reason to question the plan.",
        "journey": "Started volunteering as a weekend math tutor for extra income, expecting it to be a forgettable side job — instead, the moment a struggling student finally understood a concept became the best part of their week, every week.",
        "challenges": "A teaching career paid dramatically less than the finance path they were already on, and family reaction to even mentioning the idea was immediately negative.",
        "turning_points": "Kept a private note of which moments in their week actually felt good versus which felt like obligation — tutoring dominated the 'actually good' list, month after month, undeniably.",
        "advice": "Pay attention to which parts of your week you're genuinely excited about, not just which parts you're good at or expected to want.",
        "lessons_learned": "A side activity chosen for practical reasons can reveal something more honest about you than the path you were officially planning.",
        "trait_tags": ["communication", "empathy", "patience"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Still ongoing — weighing the financial trade-off honestly rather than pretending it doesn't matter.",
        "current_outcome": "Pursuing a teaching credential alongside finishing their finance degree, keeping both doors open.",
        "industry": "education",
        "discovery_themes": ["parent_expectations", "changed_my_mind", "still_figuring_it_out"],
    },
    {
        "id": "student_story_craft_master_2", "career_id": "japan_traditional_craft_master",
        "person_label": "Diaspora Student Raised Abroad",
        "background": "Grew up outside the country their family originally came from, with only distant, secondhand knowledge of a traditional craft their grandparent had once practiced.",
        "journey": "A university exchange semester placed them, almost by administrative accident, in the same region their family was from — and a chance visit to a small workshop turned into weeks of informally learning the basics of the craft.",
        "challenges": "Worried that learning a heritage craft as an outsider — even one connected to their own family — would feel inauthentic or presumptuous.",
        "turning_points": "The workshop's master, on hearing about their grandparent, treated the connection as exactly the reason to teach them properly, not a reason for hesitation.",
        "advice": "A connection to something doesn't have to be complete or lifelong to be real — showing up with genuine respect and curiosity counts for a lot.",
        "lessons_learned": "Heritage isn't only inherited automatically — sometimes it has to be actively sought out and re-learned.",
        "trait_tags": ["patience", "curiosity", "values"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "The whole exchange semester, unsure whether pursuing this seriously was an overreach.",
        "current_outcome": "Planning a longer apprenticeship stay after graduation to continue training formally.",
        "industry": "traditional craft & heritage",
        "discovery_themes": ["non_traditional_path", "vocational_path", "life_mission"],
    },
    {
        "id": "student_story_dev_rel_2", "career_id": "developer_relations_engineer",
        "person_label": "Self-Described Introvert, Computer Science Major",
        "background": "Chose computer science specifically because it had a reputation for solitary, heads-down work, assuming that suited their quiet personality best.",
        "journey": "Reluctantly agreed to help a struggling classmate debug an assignment, expecting to dislike it — instead found real satisfaction in explaining a confusing concept clearly and watching it click for someone else.",
        "challenges": "Had built a strong personal identity around being 'not a people person,' and a role built around communication felt like it contradicted that identity.",
        "turning_points": "Noticed that one-on-one technical explanation, unlike large-group social situations, didn't drain them the way they expected — it energized them.",
        "advice": "The kind of 'people work' that suits you might look completely different from the kind you're picturing — don't rule out an entire category based on one narrow version of it.",
        "lessons_learned": "Introversion and enjoying technical communication aren't actually in conflict — the two assumptions had just never been tested against each other.",
        "trait_tags": ["communication", "analytical_thinking", "empathy"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Started a small YouTube channel explaining coding concepts, alongside their coursework.",
        "industry": "technology",
        "discovery_themes": ["hidden_strength", "changed_my_mind", "found_my_passion"],
    },
    {
        "id": "student_story_foreign_service_2", "career_id": "foreign_service_officer",
        "person_label": "Student From a Small Town, Never Traveled Abroad",
        "background": "Grew up in a small town with no passport and no family history of international travel, so a career built around global affairs never felt like a realistic option.",
        "journey": "A free online language-exchange program, joined mostly out of boredom, connected them with a conversation partner overseas — the resulting year-long friendship made 'the rest of the world' feel concrete and reachable for the first time.",
        "challenges": "Assumed careers in foreign service were reserved for people who'd already traveled extensively or came from diplomatic families.",
        "turning_points": "Their language partner mentioned that most people in the field started with curiosity and self-study, not inherited connections — a genuinely surprising reframe.",
        "advice": "Not having traveled yet is a starting point, not a disqualification — curiosity about the wider world can be built from exactly where you are.",
        "lessons_learned": "Global fields aren't only open to people who already had global childhoods.",
        "trait_tags": ["curiosity", "communication", "persistence"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Years of assuming the field simply wasn't accessible to someone with their background.",
        "current_outcome": "Studying international relations and actively saving for their first passport and trip abroad.",
        "industry": "international affairs",
        "discovery_themes": ["missing_world_discovery", "non_traditional_path", "found_my_passion"],
    },
    {
        "id": "student_story_human_rights_2", "career_id": "human_rights_researcher",
        "person_label": "Pre-Law Biology Student",
        "background": "Was pursuing biology specifically as a pre-med track, following a fairly linear plan toward medical school.",
        "journey": "A family member's difficult experience navigating a discriminatory healthcare system became the subject of a required ethics essay — researching it seriously opened up an entire field of healthcare-focused human rights work they hadn't known existed.",
        "challenges": "Felt like abandoning years of pre-med preparation would mean the time had been wasted.",
        "turning_points": "Realized the research skills and healthcare knowledge from their biology track weren't wasted at all — they were exactly the grounding needed for health-focused human rights research specifically.",
        "advice": "A change in direction rarely erases what came before it — look for how your existing skills actually transfer before assuming you have to start over.",
        "lessons_learned": "A personal experience close to home can reveal a field that abstract classroom material never would have.",
        "trait_tags": ["empathy", "analytical_thinking", "values"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Several months reconciling the sense of 'wasted' pre-med years with the new direction.",
        "current_outcome": "Applying to graduate programs in health policy and human rights specifically, not medical school.",
        "industry": "human rights & public health",
        "discovery_themes": ["unexpected_career", "changed_my_mind", "interdisciplinary_path"],
    },
    {
        "id": "student_story_startup_founder_2", "career_id": "startup_founder",
        "person_label": "Community College Student, No Startup Connections",
        "background": "Assumed entrepreneurship required existing wealth, investor connections, or an elite university network — none of which they had access to.",
        "journey": "Started selling a small handmade product locally just to cover textbook costs, and the process of pricing, marketing, and fulfilling orders taught them, almost accidentally, the actual mechanics of running a tiny business.",
        "challenges": "Had no formal business training and initially dismissed the whole experience as 'not real entrepreneurship,' just a side hustle.",
        "turning_points": "A local small-business mentorship program pointed out that what they'd already built — from nothing, with no funding — was a genuine, if small, entrepreneurial track record.",
        "advice": "You don't need permission, funding, or an elite pedigree to start being an entrepreneur — you might have already started without realizing it counted.",
        "lessons_learned": "Entrepreneurship can start from necessity and grow into genuine interest, not just the other way around.",
        "trait_tags": ["persistence", "creativity", "decision_style"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Growing the small business deliberately now, alongside community college coursework in business.",
        "industry": "entrepreneurship",
        "discovery_themes": ["hidden_strength", "non_traditional_path", "found_my_passion"],
    },
    {
        "id": "student_story_urban_planner_2", "career_id": "urban_planner",
        "person_label": "Longtime City-Building Game Player",
        "background": "Spent years playing city-simulation video games as a hobby, never once connecting the interest to a real academic field or career.",
        "journey": "A general-education course on urban studies used real zoning maps and traffic-flow problems as case studies — the exact same kinds of trade-offs they'd spent years balancing casually in a game.",
        "challenges": "Worried that a career interest that started with a video game would sound unserious to family or advisors.",
        "turning_points": "Realized the instinct for balancing competing needs — housing, transit, green space — that the game had quietly built in them was directly transferable to how planners actually think.",
        "advice": "An interest that started as 'just a game' or 'just a hobby' can still point toward something real — the instinct underneath it is what matters, not where it came from.",
        "lessons_learned": "Years of casual practice at a skill, even through play, can add up to real intuition for a field.",
        "trait_tags": ["systems_thinking", "creativity", "analytical_thinking"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Declared a minor in urban studies alongside their original major.",
        "industry": "urban planning",
        "discovery_themes": ["hidden_strength", "unexpected_career", "found_my_passion"],
    },
    {
        "id": "student_story_ai_ops_2", "career_id": "ai_ops_specialist",
        "person_label": "Self-Taught Programmer, No Computer Science Degree",
        "background": "Studied an unrelated subject in university and only learned to code afterward, through free online tutorials, while working an unrelated day job.",
        "journey": "Automating a repetitive part of their own day job with a simple script snowballed into genuine fascination with how larger systems are kept running reliably — leading them down a self-directed path into infrastructure and operations work.",
        "challenges": "Constantly worried that not having a formal computer science degree would disqualify them from being taken seriously in a technical field.",
        "turning_points": "Contributed a real fix to an open-source project's deployment tooling, and it was merged — concrete proof their self-taught skills held up against a real technical bar.",
        "advice": "A degree is one path into a technical field, not the only one — a track record of real, working contributions can speak just as loudly.",
        "lessons_learned": "Confidence in a technical field can be built through evidence of real work, not only through credentials.",
        "trait_tags": ["persistence", "analytical_thinking", "systems_thinking"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Years of self-doubt about legitimacy without a formal technical degree.",
        "current_outcome": "Working part-time in a junior operations role while continuing to build a public portfolio of contributions.",
        "industry": "technology infrastructure",
        "discovery_themes": ["non_traditional_path", "hidden_strength", "persistence"],
    },
    {
        "id": "student_story_clinical_research_2", "career_id": "clinical_research_coordinator",
        "person_label": "Pre-Med Student Reconsidering Clinical Practice",
        "background": "Had wanted to be a doctor since childhood and structured their entire university path around medical school admission.",
        "journey": "A summer shadowing physicians revealed they found the repeated, direct patient interaction more emotionally draining than expected — while a brief rotation through the hospital's research office, coordinating an ongoing clinical trial, felt energizing instead.",
        "challenges": "Questioning the medical school plan after so many years of certainty felt like a kind of identity crisis, not just a career decision.",
        "turning_points": "A research coordinator mentioned that their role let them stay deeply connected to patient care and medical progress without daily direct clinical practice — a version of 'medicine' they hadn't known existed.",
        "advice": "A long-held career goal can still be worth questioning honestly once you have real experience of what it actually involves day to day.",
        "lessons_learned": "There's more than one way to stay close to a field you care about, even if the most obvious path turns out not to fit.",
        "trait_tags": ["analytical_thinking", "communication", "persistence"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "The entire summer, and months afterward, genuinely unsure what this meant for years of prior planning.",
        "current_outcome": "Shifted their post-graduation plan toward clinical research coordination roles instead of medical school applications.",
        "industry": "clinical research",
        "discovery_themes": ["changed_my_mind", "still_figuring_it_out", "unexpected_career"],
    },
    {
        "id": "student_story_computational_linguist_2", "career_id": "computational_linguist",
        "person_label": "Bilingual Student, Language Learning Hobbyist",
        "background": "Grew up speaking two languages at home and had spent years informally learning a third and fourth as a personal hobby, never considering it career-relevant.",
        "journey": "A friend studying computer science mentioned struggling with a project on automatic translation, and helping debug why the translations sounded 'off' pulled directly on years of intuitive, informal language knowledge.",
        "challenges": "Assumed 'language skills' and 'technical skills' were simply two separate, unrelated categories of ability.",
        "turning_points": "Realized their instinct for exactly *why* a translation sounded wrong — not just that it did — was a real, specific, technically useful skill few of the computer science students had.",
        "advice": "A hobby you've built real depth in, even informally, might be more professionally valuable than you assume — it's worth asking where it could actually be applied.",
        "lessons_learned": "Fluency and intuition built through genuine interest can become a real technical advantage in the right field.",
        "trait_tags": ["curiosity", "analytical_thinking", "communication"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Added a computer science minor specifically to pursue computational linguistics formally.",
        "industry": "artificial intelligence & language technology",
        "discovery_themes": ["hidden_strength", "interdisciplinary_path", "found_my_passion"],
    },
    {
        "id": "student_story_materials_science_2", "career_id": "materials_research_scientist",
        "person_label": "Hands-On Hobbyist Mechanic",
        "background": "Spent years fixing and modifying cars and bikes as a hobby, and assumed 'scientist' meant something entirely separate from hands-on, physical tinkering work.",
        "journey": "A university materials science lab tour, focused on why certain metal alloys fail under stress, described almost exactly the kind of hands-on problem-diagnosis they'd been doing casually on engines for years.",
        "challenges": "Pictured scientific research as purely theoretical desk work and worried their hands-on, practical instincts wouldn't translate.",
        "turning_points": "A lab technician explained that materials science research is unusually hands-on compared to other sciences — failure testing, physical samples, real material behavior — closer to mechanical tinkering than most people expect.",
        "advice": "The stereotype of what a field 'looks like' day to day is often wrong — it's worth checking the actual daily work before ruling yourself out.",
        "lessons_learned": "Practical, hands-on instincts have a real place in serious scientific research, not just in a garage.",
        "trait_tags": ["analytical_thinking", "persistence", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Requested a placement in the materials testing lab for their next research rotation.",
        "industry": "materials science & engineering",
        "discovery_themes": ["hidden_strength", "unexpected_career", "interdisciplinary_path"],
    },
    {
        "id": "student_story_public_health_policy_2", "career_id": "public_health_policy_analyst",
        "person_label": "Economics Student",
        "background": "Was drawn to economics for its analytical rigor, initially aiming toward a generic finance-sector career after graduation.",
        "journey": "A course project analyzing the economic impact of a regional public health intervention showed them how the exact same statistical tools they enjoyed in finance could be pointed at problems with direct human consequences.",
        "challenges": "Worried that moving away from finance toward public-sector-adjacent work meant giving up a more lucrative, 'safer' career trajectory.",
        "turning_points": "Realized the analytical satisfaction they got from the health-policy project was noticeably stronger than anything they'd felt in finance-focused coursework — a real, measurable difference in their own engagement.",
        "advice": "Pay attention to where you feel most engaged doing the same *kind* of work, not just which version pays best on paper.",
        "lessons_learned": "The same core skill set can be pointed at very different outcomes — it's worth choosing deliberately, not defaulting to the most obvious application.",
        "trait_tags": ["analytical_thinking", "values", "communication"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Weighing the financial trade-off honestly, still an active, ongoing consideration.",
        "current_outcome": "Pursuing a public health policy specialization alongside their economics degree.",
        "industry": "public health policy",
        "discovery_themes": ["changed_my_mind", "found_my_passion", "life_mission"],
    },
    {
        "id": "student_story_ngo_program_manager_2", "career_id": "ngo_program_manager",
        "person_label": "Business Student Uncomfortable With Pure Profit Focus",
        "background": "Studied business administration on a conventional corporate track, but grew increasingly uneasy with coursework that treated profit as the only meaningful measure of success.",
        "journey": "A required community-engagement project partnering with a local nonprofit exposed them to program management work that used identical planning, budgeting, and logistics skills — aimed at community outcomes instead of profit margins.",
        "challenges": "Assumed a 'real' business career had to mean the corporate sector, and nonprofit work felt like an unrealistic, less serious detour.",
        "turning_points": "Realized the nonprofit's program director was doing genuinely sophisticated operational and financial planning — just measured against a different kind of success than a corporate balance sheet.",
        "advice": "Business and management skills aren't owned by the corporate sector — the same rigor can be pointed at a mission you actually believe in.",
        "lessons_learned": "Discomfort with part of your planned path is worth investigating directly, not pushing past silently.",
        "trait_tags": ["values", "leadership", "analytical_thinking"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Most of their degree, quietly uneasy without being able to name exactly why.",
        "current_outcome": "Seeking nonprofit-sector internships specifically instead of corporate ones for their final year.",
        "industry": "nonprofit & social impact",
        "discovery_themes": ["changed_my_mind", "life_mission", "found_my_passion"],
    },
    {
        "id": "student_story_sustainability_analyst_2", "career_id": "sustainability_analyst",
        "person_label": "Student From a Farming Family",
        "background": "Grew up helping on a family farm and assumed agriculture and 'sustainability careers' — which they'd only ever heard discussed in corporate or academic terms — were two completely separate worlds.",
        "journey": "A university sustainability course used real agricultural data, including water-use and soil-health metrics strikingly similar to conversations they'd overheard their whole life at home — for the first time, the family's practical knowledge and an academic field visibly overlapped.",
        "challenges": "Worried that pursuing this academically would look like it dismissed their family's traditional, non-academic farming knowledge as insufficient.",
        "turning_points": "Brought a genuine question from their family's own land-management practices into a class discussion, and it turned out to be more sophisticated than most of the textbook examples — their family knowledge was an asset, not a gap to fill.",
        "advice": "Knowledge you grew up with informally can be exactly as valuable as anything taught in a classroom — the two aren't in competition.",
        "lessons_learned": "A field can feel unfamiliar by name while actually being deeply familiar in substance.",
        "trait_tags": ["systems_thinking", "values", "analytical_thinking"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Focusing their sustainability coursework specifically on agricultural systems, staying connected to their family's land.",
        "industry": "sustainability & agriculture",
        "discovery_themes": ["interdisciplinary_path", "hidden_strength", "found_my_passion"],
    },
    {
        "id": "student_story_bioinformatics_2", "career_id": "bioinformatics_scientist",
        "person_label": "Computer Science Student, Unfulfilled by Pure Software Work",
        "background": "Was a strong computer science student on a conventional software-engineering track, technically successful but increasingly unenthusiastic about the work itself.",
        "journey": "A roommate studying biology, venting about slow, manual data analysis for a research project, got informal help writing a script to automate it — and watching biological research move faster because of code felt different from any other programming they'd done.",
        "challenges": "Had already accepted a software engineering internship and worried pivoting now would mean losing that opportunity for something uncertain.",
        "turning_points": "Realized the dissatisfaction wasn't with programming itself, but with the *purpose* their code was serving — biology gave the same technical work a concrete, felt purpose.",
        "advice": "If a skill you're good at doesn't feel satisfying, the problem might be what you're pointing it at, not the skill itself.",
        "lessons_learned": "Technical ability without a meaningful application can feel hollow, even when you're objectively succeeding at it.",
        "trait_tags": ["analytical_thinking", "curiosity", "values"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "The length of the software internship, spent quietly reconsidering while still fulfilling the commitment.",
        "current_outcome": "Completed the internship as agreed, then applied for bioinformatics-focused research positions for the following summer.",
        "industry": "biotechnology",
        "discovery_themes": ["changed_my_mind", "interdisciplinary_path", "life_mission"],
    },
    {
        "id": "student_story_physician_general_2", "career_id": "physician_general",
        "person_label": "Student Who Nearly Didn't Apply Due to Cost",
        "background": "Wanted to become a doctor since childhood but came from a family with no way to realistically fund the years of required training, and had quietly begun planning a different, more immediately affordable career instead.",
        "journey": "A guidance counselor pointed them toward need-based scholarship programs and loan-forgiveness options specifically for students committing to underserved-area practice — financial paths they hadn't known existed.",
        "challenges": "Had almost entirely given up on medicine as unrealistic before learning these options existed at all.",
        "turning_points": "Meeting a practicing physician who had used exactly this kind of underserved-area program made the path feel concrete rather than theoretical.",
        "advice": "Before ruling out a path purely on assumed cost, it's worth researching the specific, real financial pathways that might exist — the assumption is sometimes more limiting than the actual reality.",
        "lessons_learned": "A closed door can sometimes be reopened with better information, not just more willpower.",
        "trait_tags": ["persistence", "values", "decision_style"],
        "career_switch": False, "gap_year": True,
        "uncertainty_period": "A full gap year spent believing medicine simply wasn't financially realistic for them.",
        "current_outcome": "Applying to medical school with a specific underserved-area scholarship program identified and targeted.",
        "industry": "healthcare",
        "discovery_themes": ["gap_year", "found_my_passion", "still_figuring_it_out"],
    },
    {
        "id": "student_story_neuroscience_2", "career_id": "neuroscience_postdoc",
        "person_label": "Psychology Student Torn Between Therapy and Research",
        "background": "Entered psychology genuinely torn between wanting to help people directly through therapy and being drawn to the more abstract, research-oriented side of the field.",
        "journey": "A required research methods course, paired with a part-time job as a peer counselor, let them experience both sides directly in the same semester — and the research side left them thinking about problems for days afterward in a way the counseling work didn't.",
        "challenges": "Felt guilty considering research over direct clinical helping work, as if it were a less compassionate choice.",
        "turning_points": "A professor pointed out that research improving the scientific understanding behind treatment helps far more people indirectly than one counselor can help directly — reframing research as its own form of care.",
        "advice": "Helping people doesn't only look like direct, in-person care — some of the most impactful help happens further upstream.",
        "lessons_learned": "Two paths that feel like opposites can both stem from the same underlying motivation, just expressed differently.",
        "trait_tags": ["curiosity", "empathy", "analytical_thinking"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Most of their undergraduate years, torn between the two directions.",
        "current_outcome": "Pursuing a research-focused graduate track in neuroscience, while continuing peer counseling as a volunteer.",
        "industry": "neuroscience research",
        "discovery_themes": ["still_figuring_it_out", "found_my_passion", "life_mission"],
    },
    {
        "id": "student_story_space_systems_2", "career_id": "space_systems_engineer",
        "person_label": "Small-Town Student, No Local Aerospace Industry",
        "background": "Grew up in a small town with no aerospace companies, universities, or visible industry connection to space at all, and assumed the field was reserved for people from very different backgrounds.",
        "journey": "A school robotics club, started almost as an afterthought by one enthusiastic teacher, entered a regional competition — and the experience of building something that had to work reliably under real physical constraints hooked them completely.",
        "challenges": "Had no mentors, role models, or local community connected to aerospace to ask for guidance.",
        "turning_points": "The robotics club's regional competition connected them, for the first time, with a university student studying aerospace engineering who was willing to answer questions honestly over email.",
        "advice": "Not having a local community around a field yet doesn't mean you can't build one — sometimes it starts with a single willing mentor found through an unrelated activity.",
        "lessons_learned": "Access to a field can be built gradually through small, unglamorous starting points like a school club.",
        "trait_tags": ["persistence", "analytical_thinking", "curiosity"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Applying to aerospace engineering programs, staying in touch with their robotics-club-found mentor.",
        "industry": "aerospace",
        "discovery_themes": ["missing_world_discovery", "found_my_passion", "non_traditional_path"],
    },
    {
        "id": "student_story_accountant_2", "career_id": "accountant",
        "person_label": "Creative-Minded Student Who Assumed Accounting Was Purely Dull",
        "background": "Enjoyed puzzles, strategy games, and creative problem-solving, and had written off accounting entirely as tedious, purely repetitive work.",
        "journey": "Took an introductory accounting course only to satisfy a requirement, expecting to dislike it — instead found the process of tracing a financial discrepancy to its root cause genuinely puzzle-like and satisfying.",
        "challenges": "Had built a strong personal identity around being a 'creative person,' and accounting didn't fit that self-image at all.",
        "turning_points": "Realized that finding a hidden error in a set of books scratched exactly the same mental itch as solving a difficult puzzle or strategy game — the two weren't as different as assumed.",
        "advice": "A field's reputation and its actual daily texture can be two very different things — it's worth testing the reputation against real experience before ruling it out.",
        "lessons_learned": "Being a 'creative person' doesn't mean only certain fields are available to you — creativity shows up in unexpected places.",
        "trait_tags": ["analytical_thinking", "creativity", "persistence"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "",
        "current_outcome": "Declared accounting as a second major alongside their original field.",
        "industry": "finance & accounting",
        "discovery_themes": ["changed_my_mind", "hidden_strength", "found_my_passion"],
    },
    {
        "id": "student_story_ias_officer_2", "career_id": "ias_officer_india",
        "person_label": "Corporate-Track Student, Family Pride at Stake",
        "background": "Was pursuing a corporate career path specifically because it carried clear, easily explained prestige within their extended family and community.",
        "journey": "A university community-service placement in local government administration exposed them to the direct, tangible impact a single well-run public office could have on hundreds of ordinary daily lives.",
        "challenges": "Worried that shifting toward public service, even a prestigious form of it, would be seen by their family as choosing a harder, slower, less impressive path.",
        "turning_points": "Watched a local administrator resolve a long-standing community water-access problem within weeks through sheer persistent follow-up — a scale of visible, immediate impact the corporate track had never offered them.",
        "advice": "Prestige recognized by your community and genuine personal fit can point in the same direction — but it's worth checking that they actually do before assuming they don't.",
        "lessons_learned": "Direct, visible impact on real people's daily lives can be more motivating than status alone.",
        "trait_tags": ["leadership", "values", "persistence"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "Months spent reconciling family expectations with a genuinely new direction.",
        "current_outcome": "Began serious preparation for civil service examinations, with cautious but growing family support.",
        "industry": "public administration",
        "discovery_themes": ["parent_expectations", "changed_my_mind", "life_mission"],
    },
    {
        "id": "student_story_health_informatics_2", "career_id": "health_informatics_specialist",
        "person_label": "Nursing Student Drawn to Systems, Not Bedside Care",
        "background": "Enrolled in a nursing program assuming direct patient care was the only real way to contribute to healthcare, despite a nagging sense that the clinical environment itself didn't fully suit them.",
        "journey": "A clinical rotation shadowing the hospital's electronic health records team, originally scheduled as a minor administrative requirement, revealed an entire role built around making patient data actually usable and safe for clinical staff.",
        "challenges": "Felt like stepping away from bedside nursing would be seen as 'giving up' on direct patient care, by both themselves and their nursing cohort.",
        "turning_points": "Realized that a well-designed patient record system prevents real medical errors at scale — a form of patient care that happens before a nurse ever enters the room.",
        "advice": "Contributing to patient wellbeing doesn't only happen at the bedside — some of the most protective work in healthcare happens in the systems behind it.",
        "lessons_learned": "There's more than one legitimate way to care for patients within healthcare, even for someone trained specifically in direct clinical care.",
        "trait_tags": ["systems_thinking", "empathy", "analytical_thinking"],
        "career_switch": True, "gap_year": False,
        "uncertainty_period": "The whole clinical rotation cycle, quietly questioning whether bedside nursing truly fit.",
        "current_outcome": "Exploring a transition from clinical nursing coursework toward a health informatics specialization.",
        "industry": "healthcare technology",
        "discovery_themes": ["changed_my_mind", "unexpected_career", "hidden_strength"],
    },
    {
        "id": "student_story_uk_civil_service_2", "career_id": "uk_civil_service_fast_streamer",
        "person_label": "Business Student, Unfulfilled by Private-Sector Internship",
        "background": "Completed a competitive private-sector internship exactly as planned, expecting it to confirm a straightforward corporate career path.",
        "journey": "A required cross-sector project during the internship briefly partnered them with a public-sector policy team, and the scale of the problems being worked on — affecting entire regions rather than a single company's bottom line — stuck with them long after the internship ended.",
        "challenges": "Everyone around them assumed the internship would lead directly to a job offer, and questioning that plan felt like second-guessing a clear win.",
        "turning_points": "Noticed they kept thinking about the policy project's public-sector problems weeks later, while the core private-sector work had already faded from memory — a genuine, telling difference in what stayed with them.",
        "advice": "Notice which parts of an experience you keep thinking about afterward, unprompted — that's often more honest data than which parts looked most impressive at the time.",
        "lessons_learned": "A successful, well-executed experience can still reveal that a different path fits better.",
        "trait_tags": ["values", "analytical_thinking", "decision_style"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "The months following the internship, reconciling its 'success' with a growing pull elsewhere.",
        "current_outcome": "Applying to public service graduate schemes alongside, not instead of, private-sector offers, to compare directly.",
        "industry": "public administration",
        "discovery_themes": ["still_figuring_it_out", "changed_my_mind", "unexpected_career"],
    },
    {
        "id": "student_story_product_led_growth_2", "career_id": "product_led_growth_specialist",
        "person_label": "Psychology Student Applying Behavioral Science Practically",
        "background": "Studied psychology out of genuine interest in human behavior, without a clear sense of what career would actually use that interest directly.",
        "journey": "A research assistantship studying decision-making and habit formation led to an internship at a small app company, applying the exact same behavioral principles to understanding why users stopped using a product after the first week.",
        "challenges": "Assumed psychology only led toward clinical or academic research roles, not toward technology or business.",
        "turning_points": "Realized the company's product team was essentially running informal behavioral experiments constantly, without calling it that — the exact methodology from their research assistantship, just applied commercially.",
        "advice": "A field's typical career paths aren't the only real ones — look at what the field's actual skills and methods are, and ask where else they might apply.",
        "lessons_learned": "Academic training can transfer directly into unexpected commercial contexts, if you look past the 'expected' career list.",
        "trait_tags": ["curiosity", "analytical_thinking", "empathy"],
        "career_switch": False, "gap_year": False,
        "uncertainty_period": "Most of their degree, unsure what non-clinical, non-academic path psychology could actually lead to.",
        "current_outcome": "Seeking further product-focused internships specifically at the intersection of psychology and technology.",
        "industry": "technology & product",
        "discovery_themes": ["unexpected_career", "interdisciplinary_path", "found_my_passion"],
    },
]


async def seed() -> None:
    client = get_supabase_client()
    stories = [CareerStory.model_validate({**s, "story_type": "composite_student_discovery"}) for s in STORIES]

    def _upsert() -> None:
        client.table("career_stories").upsert(
            [s.model_dump(mode="json") for s in stories]
        ).execute()

    await asyncio.to_thread(_upsert)
    print(f"Seeded {len(stories)} more student discovery Student Stories.")


if __name__ == "__main__":
    asyncio.run(seed())
